SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/about_panel.cxx File Reference
about_panel.cxx File Reference
#include "about_panel.h"
#include <FL/Fl_Pixmap.H>
Functions
void show_help (const char *name)
Fl_Double_Window * make_about_panel ()
Variables
Fl_Double_Window * about_panel = (Fl_Double_Window *)0
Function Documentation
Fl_Double_Window* make_about_panel ()
Definition at line 273 of file about_panel.cxx.
References about_panel, Fl_Widget::align(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Group::end(), FL_ALIGN_INSIDE, FL_ALIGN_TOP_LEFT, FL_DARK1, FL_DARK_BLUE, FL_LIGHT1, Fl_Window::hotspot(), Fl_Widget::image(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::selection_color(), and Fl_Window::set_non_modal().
Referenced by about_cb().
void show_help (const char * name)
Definition at line 848 of file fluid.cxx.
Referenced by help_cb(), and manual_cb().
Variable Documentation
Fl_Double_Window* about_panel = (Fl_Double_Window *)0
Definition at line 33 of file about_panel.cxx.
Referenced by about_cb(), exit_cb(), and make_about_panel().