SfR Fresh Dox - fltk: fltk-1.3.0rc3/zlib/adler32.c File Reference
adler32.c File Reference
#include "zlib.h"
Defines
#define ZLIB_INTERNAL
#define BASE 65521UL
#define NMAX 5552
#define DO1(buf, i) {adler += (buf)[i]; sum2 += adler;}
#define DO2(buf, i) DO1(buf,i); DO1(buf,i+1);
#define DO4(buf, i) DO2(buf,i); DO2(buf,i+2);
#define DO8(buf, i) DO4(buf,i); DO4(buf,i+4);
#define DO16(buf) DO8(buf,0); DO8(buf,8);
#define MOD(a) a %= BASE
#define MOD4(a) a %= BASE
Functions
uLong ZEXPORT adler32 (uLong adler, const Bytef *buf, uInt len)
uLong ZEXPORT adler32_combine (uLong adler1, uLong adler2, z_off_t len2)
Define Documentation
#define BASE 65521UL
Definition at line 11 of file adler32.c.
Referenced by adler32(), and adler32_combine().
#define DO1 (buf, i) {adler += (buf)[i]; sum2 += adler;}
Definition at line 15 of file adler32.c.
#define DO16 (buf) DO8(buf,0); DO8(buf,8);
Definition at line 19 of file adler32.c.
Referenced by adler32().
#define DO2 (buf, i) DO1(buf,i); DO1(buf,i+1);
Definition at line 16 of file adler32.c.
#define DO4 (buf, i) DO2(buf,i); DO2(buf,i+2);
Definition at line 17 of file adler32.c.
#define DO8 (buf, i) DO4(buf,i); DO4(buf,i+4);
Definition at line 18 of file adler32.c.
#define MOD (a) a %= BASE
Definition at line 52 of file adler32.c.
Referenced by adler32(), and adler32_combine().
#define MOD4 (a) a %= BASE
Definition at line 53 of file adler32.c.
Referenced by adler32().
#define NMAX 5552
Definition at line 12 of file adler32.c.
Referenced by adler32().
#define ZLIB_INTERNAL
Definition at line 8 of file adler32.c.
Function Documentation
uLong ZEXPORT adler32 (uLong adler, const Bytef * buf, uInt len)
Definition at line 57 of file adler32.c.
References BASE, DO16, MOD, MOD4, NMAX, and Z_NULL.
Referenced by deflate(), deflateReset(), deflateSetDictionary(), inflate(), inflateSetDictionary(), and read_buf().
uLong ZEXPORT adler32_combine (uLong adler1, uLong adler2, z_off_t len2)
Definition at line 128 of file adler32.c.
References BASE, and MOD.