SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/alignment_panel.h File Reference
alignment_panel.h File Reference
#include <FL/Fl.H>
#include <FL/Fl_Text_Buffer.H>
#include <FL/Fl_Text_Display.H>
#include <FL/filename.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Preferences.H>
#include <FL/Fl_Tooltip.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Round_Button.H>
Functions
void load_history ()
void redraw_browser ()
void header_input_cb (Fl_Input *, void *)
void code_input_cb (Fl_Input *, void *)
void include_H_from_C_button_cb (Fl_Check_Button *, void *)
void use_FL_COMMAND_button_cb (Fl_Check_Button *, void *)
void i18n_type_cb (Fl_Choice *, void *)
void i18n_text_cb (Fl_Input *, void *)
void i18n_int_cb (Fl_Int_Input *, void *)
Fl_Double_Window * make_project_window ()
void i18n_cb (Fl_Choice *, void *)
void scheme_cb (Fl_Choice *, void *)
Fl_Double_Window * make_settings_window ()
void do_shell_command (Fl_Return_Button *, void *)
Fl_Double_Window * make_shell_window ()
void grid_cb (Fl_Int_Input *, long)
void guides_cb (Fl_Check_Button *, long)
void default_widget_size_cb (Fl_Round_Button *, long)
Fl_Double_Window * make_layout_window ()
void show_global_settings_window ()
Fl_Double_Window * make_global_settings_window ()
Variables
int show_comments
int show_coredevmenus
struct Fl_Menu_Item * dbmanager_item
Fl_Preferences fluid_prefs
Fl_Text_Buffer * shell_run_buffer
Fl_Double_Window * project_window
Fl_Input * header_file_input
Fl_Input * code_file_input
Fl_Check_Button * include_H_from_C_button
Fl_Check_Button * use_FL_COMMAND_button
Fl_Choice * i18n_type_chooser
Fl_Input * i18n_include_input
Fl_Input * i18n_file_input
Fl_Int_Input * i18n_set_input
Fl_Input * i18n_function_input
Fl_Menu_Item menu_i18n_type_chooser []
Fl_Double_Window * settings_window
Fl_Choice * scheme_choice
Fl_Check_Button * tooltips_button
Fl_Check_Button * completion_button
Fl_Check_Button * openlast_button
Fl_Check_Button * prevpos_button
Fl_Check_Button * show_comments_button
Fl_Spinner * recent_spinner
Fl_Menu_Item menu_scheme_choice []
Fl_Double_Window * shell_window
Fl_Input * shell_command_input
Fl_Check_Button * shell_writecode_button
Fl_Check_Button * shell_writemsgs_button
Fl_Check_Button * shell_savefl_button
Fl_Double_Window * shell_run_window
Fl_Text_Display * shell_run_display
Fl_Return_Button * shell_run_button
Fl_Double_Window * grid_window
Fl_Int_Input * horizontal_input
Fl_Int_Input * vertical_input
Fl_Int_Input * snap_input
Fl_Check_Button * guides_toggle
Fl_Round_Button * def_widget_size [6]
Fl_Double_Window * global_settings_window
Fl_Choice * wVisibleFocus
Fl_Choice * wArrowFocus
Fl_Choice * wShowTooltips
Fl_Choice * wDNDText
Fl_Choice * wUserOrSystem
Fl_Menu_Item menu_wVisibleFocus []
Fl_Menu_Item menu_wArrowFocus []
Fl_Menu_Item menu_wShowTooltips []
Fl_Menu_Item menu_wDNDText []
Fl_Menu_Item menu_wUserOrSystem []
Function Documentation
void code_input_cb (Fl_Input * , void *)
Definition at line 258 of file Fl_Window_Type.cxx.
References set_modflag(), and Fl_Input_::value().
Referenced by make_project_window().
void default_widget_size_cb (Fl_Round_Button * , long)
Definition at line 121 of file Fl_Window_Type.cxx.
References Fl_Widget_Type::default_size, Fl_Preferences::set(), Fl_Button::setonly(), and size.
Referenced by make_layout_window().
void do_shell_command (Fl_Return_Button * , void *)
Definition at line 2042 of file fluid.cxx.
References Fl_Widget::activate(), Fl::add_fd(), Fl_Text_Buffer::append(), Fl_Widget::deactivate(), Fl_Process::desc(), fl_alert(), fl_beep(), Fl_Window::hotspot(), Fl_Window::label(), NULL, Fl_Process::popen(), shell_pipe_cb(), shell_run_buffer, shell_run_button, shell_run_display, shell_run_window, Fl_Double_Window::show(), Fl_Window::shown(), Fl_Text_Buffer::text(), and Fl::wait().
Referenced by make_shell_window().
void grid_cb (Fl_Int_Input * , long)
Definition at line 87 of file Fl_Window_Type.cxx.
References Fl_Type::first, gridx, gridy, Fl::h(), Fl_Type::is_window(), Fl_Type::next, Fl_Widget_Type::o, Fl_Preferences::set(), snap, Fl_Input_::value(), Fl::w(), and w.
Referenced by main(), and make_layout_window().
void guides_cb (Fl_Check_Button * , long)
Definition at line 75 of file Fl_Window_Type.cxx.
References Fl_Type::first, Fl_Type::next, Fl_Widget_Type::o, Fl_Preferences::set(), show_guides, Fl_Button::value(), and w.
Referenced by make_layout_window().
void header_input_cb (Fl_Input * , void *)
Definition at line 253 of file Fl_Window_Type.cxx.
References set_modflag(), and Fl_Input_::value().
Referenced by make_project_window().
void i18n_cb (Fl_Choice * , void *)
void i18n_int_cb (Fl_Int_Input * , void *)
Definition at line 179 of file Fl_Window_Type.cxx.
References i18n_set, i18n_set_input, set_modflag(), undo_checkpoint(), and Fl_Input_::value().
Referenced by make_project_window().
void i18n_text_cb (Fl_Input * , void *)
Definition at line 166 of file Fl_Window_Type.cxx.
References i18n_file, i18n_file_input, i18n_function, i18n_function_input, i18n_include, i18n_include_input, set_modflag(), undo_checkpoint(), and Fl_Input_::value().
Referenced by make_project_window().
void i18n_type_cb (Fl_Choice * , void *)
Definition at line 129 of file Fl_Window_Type.cxx.
References Fl_Widget::hide(), i18n_file, i18n_file_input, i18n_function, i18n_function_input, i18n_include, i18n_include_input, i18n_set, i18n_set_input, i18n_type, set_modflag(), Fl_Widget::show(), undo_checkpoint(), Fl_Input_::value(), and Fl_Choice::value().
Referenced by make_project_window().
void include_H_from_C_button_cb (Fl_Check_Button * , void *)
Definition at line 264 of file Fl_Window_Type.cxx.
References include_H_from_C, set_modflag(), and Fl_Button::value().
Referenced by make_project_window().
void load_history ()
Definition at line 1798 of file fluid.cxx.
References absolute_history, fl_filename_relative(), FL_MENU_DIVIDER, Fl_Menu_Item::flags, fluid_prefs, Fl_Preferences::get(), Fl_Menu_Item::hide(), i, and relative_history.
Referenced by make_main_window().
Fl_Double_Window* make_global_settings_window ()
Definition at line 667 of file alignment_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Menu_::down_box(), Fl_Group::end(), FL_ALIGN_INSIDE, FL_ALIGN_TOP_LEFT, FL_BORDER_BOX, FL_GTK_DOWN_BOX, FL_LIGHT1, global_settings_window, Fl_Widget::labelfont(), Fl_Menu_::menu(), Fl::option(), Fl::OPTION_SHOW_TOOLTIPS, and Fl_Widget::tooltip().
Referenced by make_main_window(), and show_global_settings_window().
Fl_Double_Window* make_layout_window ()
Definition at line 398 of file alignment_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), default_widget_size_cb(), Fl_Button::down_box(), Fl_Group::end(), FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_DOWN_BOX, FL_ROUND_DOWN_BOX, FL_THIN_DOWN_BOX, FL_WHEN_ENTER_KEY, FL_WHEN_RELEASE, grid_cb(), grid_window, guides_cb(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Window::set_non_modal(), Fl_Widget::tooltip(), Fl_Widget::type(), and Fl_Widget::when().
Referenced by make_main_window().
Fl_Double_Window* make_project_window ()
Definition at line 66 of file alignment_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), code_input_cb(), Fl_Menu_::down_box(), Fl_Button::down_box(), Fl_Group::end(), FL_ALIGN_INSIDE, FL_ALIGN_WRAP, FL_BORDER_BOX, FL_DOWN_BOX, FL_THIN_DOWN_BOX, FL_THIN_UP_BOX, FL_WHEN_CHANGED, header_input_cb(), Fl_Widget::hide(), i18n_int_cb(), i18n_text_cb(), i18n_type_cb(), include_H_from_C_button_cb(), Fl_Widget::labelfont(), Fl_Menu_::menu(), project_window, Fl_Widget::selection_color(), Fl_Window::set_modal(), Fl_Input_::textfont(), Fl_Widget::tooltip(), Fl_Widget::type(), use_FL_COMMAND_button_cb(), and Fl_Widget::when().
Referenced by show_project_cb().
Fl_Double_Window* make_settings_window ()
Definition at line 212 of file alignment_panel.cxx.
References Fl_Widget::align(), b, Fl_Widget::callback(), Fl_Button::down_box(), Fl_Menu_::down_box(), Fl_Tooltip::enable(), Fl_Group::end(), FL_ALIGN_CENTER, FL_ALIGN_LEFT, FL_BORDER_BOX, FL_DOWN_BOX, FL_WHEN_CHANGED, fluid_prefs, Fl_Preferences::get(), Fl_Widget::labelfont(), Fl_Spinner::maximum(), Fl_Menu_::menu(), scheme_cb(), Fl_Window::set_non_modal(), settings_window, show_comments, Fl_Widget::tooltip(), Fl_Spinner::value(), Fl_Button::value(), Fl_Choice::value(), and Fl_Widget::when().
Referenced by make_main_window().
Fl_Double_Window* make_shell_window ()
Definition at line 327 of file alignment_panel.cxx.
References Fl_Widget::align(), b, Fl_Widget::box(), buf, Fl_Text_Display::buffer(), Fl_Widget::callback(), Fl_Group::current(), do_shell_command(), Fl_Button::down_box(), Fl_Group::end(), FL_ALIGN_TOP_LEFT, FL_DOWN_BOX, fluid_prefs, Fl_Preferences::get(), Fl_Widget::labelfont(), Fl_Group::resizable(), shell_run_window, Fl_Text_Display::textfont(), Fl_Button::value(), and Fl_Input_::value().
Referenced by make_main_window().
void redraw_browser ()
Definition at line 394 of file Fl_Type.cxx.
Referenced by name_public_cb(), name_public_member_cb(), Fl_Class_Type::open(), Fl_DeclBlock_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_Function_Type::open(), reveal_in_browser(), selection_changed(), and Fl_Widget_Type::subclass().
void scheme_cb (Fl_Choice * , void *)
Definition at line 1689 of file fluid.cxx.
References fluid_prefs, NULL, Fl::scheme(), scheme_choice, Fl_Preferences::set(), and Fl_Choice::value().
void show_global_settings_window ()
Definition at line 573 of file alignment_panel.cxx.
References fl_message(), global_settings_window, make_global_settings_window(), and Fl_Double_Window::show().
Referenced by show_global_settings_cb().
void use_FL_COMMAND_button_cb (Fl_Check_Button * , void *)
Definition at line 271 of file Fl_Window_Type.cxx.
References set_modflag(), use_FL_COMMAND, and Fl_Button::value().
Referenced by make_project_window().
Variable Documentation
Fl_Input* code_file_input
Definition at line 43 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Check_Button* completion_button
Definition at line 175 of file alignment_panel.cxx.
Referenced by write_cb(), and write_strings_cb().
struct Fl_Menu_Item* dbmanager_item
Fl_Round_Button* def_widget_size[6]
Definition at line 396 of file alignment_panel.cxx.
Referenced by show_grid_cb().
Fl_Preferences fluid_prefs
Referenced by exit_cb(), load_history(), make_main_window(), make_settings_window(), make_shell_window(), position_window(), save_position(), save_template_cb(), scheme_cb(), toggle_sourceview_cb(), update_history(), and update_sourceview_cb().
Fl_Double_Window* global_settings_window
Definition at line 588 of file alignment_panel.cxx.
Referenced by make_global_settings_window(), show_global_settings_cb(), and show_global_settings_window().
Fl_Double_Window* grid_window
Definition at line 382 of file alignment_panel.cxx.
Referenced by make_layout_window(), and show_grid_cb().
Fl_Check_Button* guides_toggle
Definition at line 390 of file alignment_panel.cxx.
Referenced by show_grid_cb().
Fl_Input* header_file_input
Definition at line 41 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Int_Input* horizontal_input
Definition at line 384 of file alignment_panel.cxx.
Referenced by main(), and show_grid_cb().
Fl_Input* i18n_file_input
Definition at line 60 of file alignment_panel.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), and show_project_cb().
Fl_Input* i18n_function_input
Definition at line 64 of file alignment_panel.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), and show_project_cb().
Fl_Input* i18n_include_input
Definition at line 58 of file alignment_panel.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), and show_project_cb().
Fl_Int_Input* i18n_set_input
Definition at line 62 of file alignment_panel.cxx.
Referenced by i18n_int_cb(), i18n_type_cb(), and show_project_cb().
Fl_Choice* i18n_type_chooser
Definition at line 49 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Check_Button* include_H_from_C_button
Definition at line 45 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Menu_Item menu_i18n_type_chooser[]
Definition at line 51 of file alignment_panel.cxx.
Fl_Menu_Item menu_scheme_choice[]
Definition at line 160 of file alignment_panel.cxx.
Fl_Menu_Item menu_wArrowFocus[]
Definition at line 611 of file alignment_panel.cxx.
Fl_Menu_Item menu_wDNDText[]
Definition at line 639 of file alignment_panel.cxx.
Fl_Menu_Item menu_wShowTooltips[]
Definition at line 625 of file alignment_panel.cxx.
Fl_Menu_Item menu_wUserOrSystem[]
Definition at line 652 of file alignment_panel.cxx.
Fl_Menu_Item menu_wVisibleFocus[]
Definition at line 597 of file alignment_panel.cxx.
Fl_Check_Button* openlast_button
Definition at line 181 of file alignment_panel.cxx.
Referenced by main().
Fl_Check_Button* prevpos_button
Definition at line 187 of file alignment_panel.cxx.
Referenced by position_window().
Fl_Double_Window* project_window
Definition at line 35 of file alignment_panel.cxx.
Referenced by make_project_window(), and show_project_cb().
Fl_Spinner* recent_spinner
Definition at line 201 of file alignment_panel.cxx.
Fl_Choice* scheme_choice
Definition at line 158 of file alignment_panel.cxx.
Referenced by scheme_cb().
Fl_Double_Window* settings_window
Definition at line 156 of file alignment_panel.cxx.
Referenced by make_settings_window(), and show_settings_cb().
Fl_Input* shell_command_input
Definition at line 289 of file alignment_panel.cxx.
Referenced by show_shell_window().
Fl_Text_Buffer* shell_run_buffer
Definition at line 33 of file alignment_panel.cxx.
Referenced by do_shell_command(), and shell_pipe_cb().
Fl_Return_Button* shell_run_button
Definition at line 321 of file alignment_panel.cxx.
Referenced by do_shell_command().
Fl_Text_Display* shell_run_display
Definition at line 319 of file alignment_panel.cxx.
Referenced by do_shell_command(), and shell_pipe_cb().
Fl_Double_Window* shell_run_window
Definition at line 317 of file alignment_panel.cxx.
Referenced by do_shell_command(), and make_shell_window().
Fl_Check_Button* shell_savefl_button
Definition at line 307 of file alignment_panel.cxx.
Fl_Double_Window* shell_window
Definition at line 287 of file alignment_panel.cxx.
Referenced by show_shell_window().
Fl_Check_Button* shell_writecode_button
Definition at line 295 of file alignment_panel.cxx.
Fl_Check_Button* shell_writemsgs_button
Definition at line 301 of file alignment_panel.cxx.
int show_comments
Definition at line 102 of file fluid.cxx.
Referenced by make_main_window(), and make_settings_window().
Fl_Check_Button* show_comments_button
Definition at line 193 of file alignment_panel.cxx.
int show_coredevmenus
Definition at line 103 of file fluid.cxx.
Fl_Int_Input* snap_input
Definition at line 388 of file alignment_panel.cxx.
Referenced by show_grid_cb().
Fl_Check_Button* tooltips_button
Definition at line 168 of file alignment_panel.cxx.
Fl_Check_Button* use_FL_COMMAND_button
Definition at line 47 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Int_Input* vertical_input
Definition at line 386 of file alignment_panel.cxx.
Referenced by show_grid_cb().
Fl_Choice* wArrowFocus
Definition at line 604 of file alignment_panel.cxx.
Fl_Choice* wDNDText
Definition at line 632 of file alignment_panel.cxx.
Fl_Choice* wShowTooltips
Definition at line 618 of file alignment_panel.cxx.
Fl_Choice* wUserOrSystem
Definition at line 646 of file alignment_panel.cxx.
Fl_Choice* wVisibleFocus
Definition at line 590 of file alignment_panel.cxx.