SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/alignment_panel.cxx File Reference
alignment_panel.cxx File Reference
#include "alignment_panel.h"
#include <FL/Fl_Preferences.H>
#include <FL/fl_ask.H>
Functions
Fl_Double_Window * make_project_window ()
void scheme_cb (Fl_Choice *, void *)
Fl_Double_Window * make_settings_window ()
Fl_Double_Window * make_shell_window ()
Fl_Double_Window * make_layout_window ()
void show_global_settings_window ()
Fl_Double_Window * make_global_settings_window ()
Variables
Fl_Text_Buffer * shell_run_buffer
Fl_Double_Window * project_window = (Fl_Double_Window *)0
Fl_Input * header_file_input = (Fl_Input *)0
Fl_Input * code_file_input = (Fl_Input *)0
Fl_Check_Button * include_H_from_C_button = (Fl_Check_Button *)0
Fl_Check_Button * use_FL_COMMAND_button = (Fl_Check_Button *)0
Fl_Choice * i18n_type_chooser = (Fl_Choice *)0
Fl_Menu_Item menu_i18n_type_chooser []
Fl_Input * i18n_include_input = (Fl_Input *)0
Fl_Input * i18n_file_input = (Fl_Input *)0
Fl_Int_Input * i18n_set_input = (Fl_Int_Input *)0
Fl_Input * i18n_function_input = (Fl_Input *)0
Fl_Double_Window * settings_window = (Fl_Double_Window *)0
Fl_Choice * scheme_choice = (Fl_Choice *)0
Fl_Menu_Item menu_scheme_choice []
Fl_Check_Button * tooltips_button = (Fl_Check_Button *)0
Fl_Check_Button * completion_button = (Fl_Check_Button *)0
Fl_Check_Button * openlast_button = (Fl_Check_Button *)0
Fl_Check_Button * prevpos_button = (Fl_Check_Button *)0
Fl_Check_Button * show_comments_button = (Fl_Check_Button *)0
Fl_Spinner * recent_spinner = (Fl_Spinner *)0
Fl_Double_Window * shell_window = (Fl_Double_Window *)0
Fl_Input * shell_command_input = (Fl_Input *)0
Fl_Check_Button * shell_writecode_button = (Fl_Check_Button *)0
Fl_Check_Button * shell_writemsgs_button = (Fl_Check_Button *)0
Fl_Check_Button * shell_savefl_button = (Fl_Check_Button *)0
Fl_Double_Window * shell_run_window = (Fl_Double_Window *)0
Fl_Text_Display * shell_run_display = (Fl_Text_Display *)0
Fl_Return_Button * shell_run_button = (Fl_Return_Button *)0
Fl_Double_Window * grid_window = (Fl_Double_Window *)0
Fl_Int_Input * horizontal_input = (Fl_Int_Input *)0
Fl_Int_Input * vertical_input = (Fl_Int_Input *)0
Fl_Int_Input * snap_input = (Fl_Int_Input *)0
Fl_Check_Button * guides_toggle = (Fl_Check_Button *)0
Fl_Round_Button * def_widget_size [6] = {(Fl_Round_Button *)0}
Fl_Double_Window * global_settings_window = (Fl_Double_Window *)0
Fl_Choice * wVisibleFocus = (Fl_Choice *)0
Fl_Menu_Item menu_wVisibleFocus []
Fl_Choice * wArrowFocus = (Fl_Choice *)0
Fl_Menu_Item menu_wArrowFocus []
Fl_Choice * wShowTooltips = (Fl_Choice *)0
Fl_Menu_Item menu_wShowTooltips []
Fl_Choice * wDNDText = (Fl_Choice *)0
Fl_Menu_Item menu_wDNDText []
Fl_Choice * wUserOrSystem = (Fl_Choice *)0
Fl_Menu_Item menu_wUserOrSystem []
Function Documentation
Fl_Double_Window* make_global_settings_window ()
Definition at line 667 of file alignment_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Menu_::down_box(), Fl_Group::end(), FL_ALIGN_INSIDE, FL_ALIGN_TOP_LEFT, FL_BORDER_BOX, FL_GTK_DOWN_BOX, FL_LIGHT1, global_settings_window, Fl_Widget::labelfont(), Fl_Menu_::menu(), Fl::option(), Fl::OPTION_SHOW_TOOLTIPS, and Fl_Widget::tooltip().
Referenced by make_main_window(), and show_global_settings_window().
Fl_Double_Window* make_layout_window ()
Definition at line 398 of file alignment_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), default_widget_size_cb(), Fl_Button::down_box(), Fl_Group::end(), FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_DOWN_BOX, FL_ROUND_DOWN_BOX, FL_THIN_DOWN_BOX, FL_WHEN_ENTER_KEY, FL_WHEN_RELEASE, grid_cb(), grid_window, guides_cb(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Window::set_non_modal(), Fl_Widget::tooltip(), Fl_Widget::type(), and Fl_Widget::when().
Referenced by make_main_window().
Fl_Double_Window* make_project_window ()
Definition at line 66 of file alignment_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), code_input_cb(), Fl_Menu_::down_box(), Fl_Button::down_box(), Fl_Group::end(), FL_ALIGN_INSIDE, FL_ALIGN_WRAP, FL_BORDER_BOX, FL_DOWN_BOX, FL_THIN_DOWN_BOX, FL_THIN_UP_BOX, FL_WHEN_CHANGED, header_input_cb(), Fl_Widget::hide(), i18n_int_cb(), i18n_text_cb(), i18n_type_cb(), include_H_from_C_button_cb(), Fl_Widget::labelfont(), Fl_Menu_::menu(), project_window, Fl_Widget::selection_color(), Fl_Window::set_modal(), Fl_Input_::textfont(), Fl_Widget::tooltip(), Fl_Widget::type(), use_FL_COMMAND_button_cb(), and Fl_Widget::when().
Referenced by show_project_cb().
Fl_Double_Window* make_settings_window ()
Definition at line 212 of file alignment_panel.cxx.
References Fl_Widget::align(), b, Fl_Widget::callback(), Fl_Button::down_box(), Fl_Menu_::down_box(), Fl_Tooltip::enable(), Fl_Group::end(), FL_ALIGN_CENTER, FL_ALIGN_LEFT, FL_BORDER_BOX, FL_DOWN_BOX, FL_WHEN_CHANGED, fluid_prefs, Fl_Preferences::get(), Fl_Widget::labelfont(), Fl_Spinner::maximum(), Fl_Menu_::menu(), scheme_cb(), Fl_Window::set_non_modal(), settings_window, show_comments, Fl_Widget::tooltip(), Fl_Spinner::value(), Fl_Button::value(), Fl_Choice::value(), and Fl_Widget::when().
Referenced by make_main_window().
Fl_Double_Window* make_shell_window ()
Definition at line 327 of file alignment_panel.cxx.
References Fl_Widget::align(), b, Fl_Widget::box(), buf, Fl_Text_Display::buffer(), Fl_Widget::callback(), Fl_Group::current(), do_shell_command(), Fl_Button::down_box(), Fl_Group::end(), FL_ALIGN_TOP_LEFT, FL_DOWN_BOX, fluid_prefs, Fl_Preferences::get(), Fl_Widget::labelfont(), Fl_Group::resizable(), shell_run_window, Fl_Text_Display::textfont(), Fl_Button::value(), and Fl_Input_::value().
Referenced by make_main_window().
void scheme_cb (Fl_Choice * , void *)
Definition at line 1689 of file fluid.cxx.
Referenced by make_settings_window().
void show_global_settings_window ()
Definition at line 573 of file alignment_panel.cxx.
References fl_message(), global_settings_window, make_global_settings_window(), and Fl_Double_Window::show().
Referenced by show_global_settings_cb().
Variable Documentation
Fl_Input* code_file_input = (Fl_Input *)0
Definition at line 43 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Check_Button* completion_button = (Fl_Check_Button *)0
Definition at line 175 of file alignment_panel.cxx.
Referenced by write_cb(), and write_strings_cb().
Fl_Round_Button* def_widget_size[6] = {(Fl_Round_Button *)0}
Definition at line 396 of file alignment_panel.cxx.
Referenced by show_grid_cb().
Fl_Double_Window* global_settings_window = (Fl_Double_Window *)0
Definition at line 588 of file alignment_panel.cxx.
Referenced by make_global_settings_window(), show_global_settings_cb(), and show_global_settings_window().
Fl_Double_Window* grid_window = (Fl_Double_Window *)0
Definition at line 382 of file alignment_panel.cxx.
Referenced by make_layout_window(), and show_grid_cb().
Fl_Check_Button* guides_toggle = (Fl_Check_Button *)0
Definition at line 390 of file alignment_panel.cxx.
Referenced by show_grid_cb().
Fl_Input* header_file_input = (Fl_Input *)0
Definition at line 41 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Int_Input* horizontal_input = (Fl_Int_Input *)0
Definition at line 384 of file alignment_panel.cxx.
Referenced by main(), and show_grid_cb().
Fl_Input* i18n_file_input = (Fl_Input *)0
Definition at line 60 of file alignment_panel.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), and show_project_cb().
Fl_Input* i18n_function_input = (Fl_Input *)0
Definition at line 64 of file alignment_panel.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), and show_project_cb().
Fl_Input* i18n_include_input = (Fl_Input *)0
Definition at line 58 of file alignment_panel.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), and show_project_cb().
Fl_Int_Input* i18n_set_input = (Fl_Int_Input *)0
Definition at line 62 of file alignment_panel.cxx.
Referenced by i18n_int_cb(), i18n_type_cb(), and show_project_cb().
Fl_Choice* i18n_type_chooser = (Fl_Choice *)0
Definition at line 49 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Check_Button* include_H_from_C_button = (Fl_Check_Button *)0
Definition at line 45 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Menu_Item menu_i18n_type_chooser[]
Initial value:
 {
 {"None", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"GNU gettext", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"POSIX catgets", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 51 of file alignment_panel.cxx.
Fl_Menu_Item menu_scheme_choice[]
Initial value:
 {
 {"Default", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"None", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Plastic", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"GTK+", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 160 of file alignment_panel.cxx.
Fl_Menu_Item menu_wArrowFocus[]
Initial value:
 {
 {"off", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"on", 0,  0, (void*)(1), 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"default", 0,  0, (void*)(2), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 611 of file alignment_panel.cxx.
Fl_Menu_Item menu_wDNDText[]
Initial value:
 {
 {"off", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"on", 0,  0, (void*)(1), 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"default", 0,  0, (void*)(2), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 639 of file alignment_panel.cxx.
Fl_Menu_Item menu_wShowTooltips[]
Initial value:
 {
 {"off", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"on", 0,  0, (void*)(1), 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"default", 0,  0, (void*)(2), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 625 of file alignment_panel.cxx.
Fl_Menu_Item menu_wUserOrSystem[]
Initial value:
 {
 {"User Settings", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"System Settings", 0,  0, (void*)(1), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 652 of file alignment_panel.cxx.
Fl_Menu_Item menu_wVisibleFocus[]
Initial value:
 {
 {"off", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"on", 0,  0, (void*)(1), 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"default", 0,  0, (void*)(2), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 597 of file alignment_panel.cxx.
Fl_Check_Button* openlast_button = (Fl_Check_Button *)0
Definition at line 181 of file alignment_panel.cxx.
Referenced by main().
Fl_Check_Button* prevpos_button = (Fl_Check_Button *)0
Definition at line 187 of file alignment_panel.cxx.
Referenced by position_window().
Fl_Double_Window* project_window = (Fl_Double_Window *)0
Definition at line 35 of file alignment_panel.cxx.
Referenced by make_project_window(), and show_project_cb().
Fl_Spinner* recent_spinner = (Fl_Spinner *)0
Definition at line 201 of file alignment_panel.cxx.
Fl_Choice* scheme_choice = (Fl_Choice *)0
Definition at line 158 of file alignment_panel.cxx.
Referenced by scheme_cb().
Fl_Double_Window* settings_window = (Fl_Double_Window *)0
Definition at line 156 of file alignment_panel.cxx.
Referenced by make_settings_window(), and show_settings_cb().
Fl_Input* shell_command_input = (Fl_Input *)0
Definition at line 289 of file alignment_panel.cxx.
Referenced by show_shell_window().
Fl_Text_Buffer* shell_run_buffer
Definition at line 33 of file alignment_panel.cxx.
Referenced by do_shell_command(), and shell_pipe_cb().
Fl_Return_Button* shell_run_button = (Fl_Return_Button *)0
Definition at line 321 of file alignment_panel.cxx.
Referenced by do_shell_command().
Fl_Text_Display* shell_run_display = (Fl_Text_Display *)0
Definition at line 319 of file alignment_panel.cxx.
Referenced by do_shell_command(), and shell_pipe_cb().
Fl_Double_Window* shell_run_window = (Fl_Double_Window *)0
Definition at line 317 of file alignment_panel.cxx.
Referenced by do_shell_command(), and make_shell_window().
Fl_Check_Button* shell_savefl_button = (Fl_Check_Button *)0
Definition at line 307 of file alignment_panel.cxx.
Fl_Double_Window* shell_window = (Fl_Double_Window *)0
Definition at line 287 of file alignment_panel.cxx.
Referenced by show_shell_window().
Fl_Check_Button* shell_writecode_button = (Fl_Check_Button *)0
Definition at line 295 of file alignment_panel.cxx.
Fl_Check_Button* shell_writemsgs_button = (Fl_Check_Button *)0
Definition at line 301 of file alignment_panel.cxx.
Fl_Check_Button* show_comments_button = (Fl_Check_Button *)0
Definition at line 193 of file alignment_panel.cxx.
Fl_Int_Input* snap_input = (Fl_Int_Input *)0
Definition at line 388 of file alignment_panel.cxx.
Referenced by show_grid_cb().
Fl_Check_Button* tooltips_button = (Fl_Check_Button *)0
Definition at line 168 of file alignment_panel.cxx.
Fl_Check_Button* use_FL_COMMAND_button = (Fl_Check_Button *)0
Definition at line 47 of file alignment_panel.cxx.
Referenced by show_project_cb().
Fl_Int_Input* vertical_input = (Fl_Int_Input *)0
Definition at line 386 of file alignment_panel.cxx.
Referenced by show_grid_cb().
Fl_Choice* wArrowFocus = (Fl_Choice *)0
Definition at line 604 of file alignment_panel.cxx.
Fl_Choice* wDNDText = (Fl_Choice *)0
Definition at line 632 of file alignment_panel.cxx.
Fl_Choice* wShowTooltips = (Fl_Choice *)0
Definition at line 618 of file alignment_panel.cxx.
Fl_Choice* wUserOrSystem = (Fl_Choice *)0
Definition at line 646 of file alignment_panel.cxx.
Fl_Choice* wVisibleFocus = (Fl_Choice *)0
Definition at line 590 of file alignment_panel.cxx.