SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/align_widget.cxx File Reference
align_widget.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "Fl_Widget_Type.h"
#include "undo.h"
Defines
#define BREAK_ON_FIRST break
Functions
void align_widget_cb (Fl_Widget *, long how)
void widget_size_cb (Fl_Widget *, long size)
Define Documentation
#define BREAK_ON_FIRST break
the first behaviour always uses the first selected widget as a reference the second behaviour uses the largest widget (most extreme positions) as a reference.
Definition at line 38 of file align_widget.cxx.
Referenced by align_widget_cb().
Function Documentation
void align_widget_cb (Fl_Widget * , long how)
Definition at line 41 of file align_widget.cxx.
References BREAK_ON_FIRST, Fl_Type::first, Fl_Widget::h(), Fl_Type::is_menu_button(), Fl_Type::is_widget(), Fl_Type::level, min, Fl_Type::next, Fl_Type::parent, Fl_Widget::redraw(), Fl_Widget::resize(), Fl_Type::selected, set_modflag(), undo_checkpoint(), Fl_Widget::w(), w, Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
void widget_size_cb (Fl_Widget * , long size)
Definition at line 512 of file align_widget.cxx.
References f, Fl_Type::first, int, Fl_Widget::labelsize(), Fl_Type::next, Fl_Widget::redraw(), set_modflag(), undo_checkpoint(), w, and Fl_Widget::window().