SfR Fresh Dox - fltk: Fl_Overlay_Window Class Reference
Fl_Overlay_Window Class Reference
#include <Fl_Overlay_Window.H>
Public Member Functions
void show ()
void flush ()
void hide ()
void resize (int, int, int, int)
~Fl_Overlay_Window ()
int can_do_overlay ()
void redraw_overlay ()
Fl_Overlay_Window (int W, int H, const char *l=0)
Fl_Overlay_Window (int X, int Y, int W, int H, const char *l=0)
void show (int a, char **b)
Detailed Description
This window provides double buffering and also the ability to draw the "overlay" which is another picture placed on top of the main image. The overlay is designed to be a rapidly-changing but simple graphic such as a mouse selection box. Fl_Overlay_Window uses the overlay planes provided by your graphics hardware if they are available.
If no hardware support is found the overlay is simulated by drawing directly into the on-screen copy of the double-buffered window, and "erased" by copying the backbuffer over it again. This means the overlay will blink if you change the image in the window.
Definition at line 47 of file Fl_Overlay_Window.H.
Constructor & Destructor Documentation
Fl_Overlay_Window::~Fl_Overlay_Window ()
Destroys the window and all child widgets.
Definition at line 78 of file Fl_Overlay_Window.cxx.
References hide().
Fl_Overlay_Window::Fl_Overlay_Window (int W, int H, const char * l = 0) [inline]
Creates a new Fl_Overlay_Window widget using the given position, size, and label (title) string. If the positions (x,y) are not given, then the window manager will choose them.
Definition at line 66 of file Fl_Overlay_Window.H.
References Fl_Widget::image().
Fl_Overlay_Window::Fl_Overlay_Window (int X, int Y, int W, int H, const char * l = 0) [inline]
See Fl_Overlay_Window::Fl_Overlay_Window(int W, int H, const char *l=0)
Definition at line 71 of file Fl_Overlay_Window.H.
References Fl_Widget::image().
Member Function Documentation
int Fl_Overlay_Window::can_do_overlay ()
Definition at line 85 of file Fl_Overlay_Window.cxx.
void Fl_Overlay_Window::flush () [virtual]
Forces the window to be redrawn.
Reimplemented from Fl_Double_Window.
Definition at line 54 of file Fl_Overlay_Window.cxx.
References Fl_Widget::clear_damage(), Fl_Widget::damage(), FL_DAMAGE_OVERLAY, fl_display, fl_xid(), Fl_Window::shown(), XMapWindow, and XUnmapWindow.
void Fl_Overlay_Window::hide () [virtual]
Removes the window from the screen. If the window is already hidden or has not been shown then this does nothing and is harmless.
Reimplemented from Fl_Double_Window.
Definition at line 50 of file Fl_Overlay_Window.cxx.
Referenced by ~Fl_Overlay_Window().
void Fl_Overlay_Window::redraw_overlay ()
Call this to indicate that the overlay data has changed and needs to be redrawn. The overlay will be clear until the first time this is called, so if you want an initial display you must call this after calling show().
Definition at line 93 of file Fl_Overlay_Window.cxx.
References Fl_Widget::clear_damage(), Fl_Widget::damage(), FL_DAMAGE_CHILD, and FL_DAMAGE_OVERLAY.
void Fl_Overlay_Window::resize (int X, int Y, int W, int H) [virtual]
Changes the size and position of the window. If shown() is true, these changes are communicated to the window server (which may refuse that size and cause a further resize). If shown() is false, the size and position are used when show() is called. See Fl_Group for the effect of resizing on the child widgets.
You can also call the Fl_Widget methods size(x,y) and position(w,h), which are inline wrappers for this virtual function.
A top-level window can not force, but merely suggest a position and size to the operating system. The window manager may not be willing or able to display a window at the desired position or with the given dimensions. It is up to the application developer to verify window parameters after the resize request.
resize a window
Reimplemented from Fl_Double_Window.
Reimplemented in Overlay_Window.
Definition at line 70 of file Fl_Overlay_Window.cxx.
References Fl_Widget::h(), Fl_Window::resize(), and Fl_Widget::w().
void Fl_Overlay_Window::show (int argc, char ** argv) [inline]
Puts the window on the screen and parses command-line arguments.
Usually (on X) this has the side effect of opening the display.
This form should be used for top-level windows, at least for the first (main) window. It allows standard arguments to be parsed from the command-line. You can use argc and argv from main(int argc, char **argv) for this call.
The first call also sets up some system-specific internal variables like the system colors.
Todo:
explain which system parameters are set up.
Parameters:
argc command-line argument count, usually from main()
argv command-line argument vector, usually from main()
See also:
virtual void Fl_Window::show()
Reimplemented from Fl_Double_Window.
Definition at line 73 of file Fl_Overlay_Window.H.
void Fl_Overlay_Window::show () [virtual]
Puts the window on the screen. Usually (on X) this has the side effect of opening the display.
If the window is already shown then it is restored and raised to the top. This is really convenient because your program can call show() at any time, even if the window is already up. It also means that show() serves the purpose of raise() in other toolkits.
Fl_Window::show(int argc, char **argv) is used for top-level windows and allows standard arguments to be parsed from the command-line.
See also:
Fl_Window::show(int argc, char **argv)
make a window visible
Reimplemented from Fl_Double_Window.
Definition at line 45 of file Fl_Overlay_Window.cxx.
References Fl_Window::show().
Referenced by Fl_Window_Type::open().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Overlay_Window.H
fltk-1.3.0rc3/src/Fl_Overlay_Window.cxx