SfR Fresh Dox - fltk: Fl_Double_Window Class Reference
Fl_Double_Window Class Reference
#include <Fl_Double_Window.H>
Public Member Functions
void show ()
void show (int a, char **b)
void flush ()
void resize (int, int, int, int)
void hide ()
~Fl_Double_Window ()
Fl_Double_Window (int W, int H, const char *l=0)
Fl_Double_Window (int X, int Y, int W, int H, const char *l=0)
Protected Member Functions
void flush (int eraseoverlay)
Protected Attributes
char force_doublebuffering_
Detailed Description
The Fl_Double_Window provides a double-buffered window. If possible this will use the X double buffering extension (Xdbe). If not, it will draw the window data into an off-screen pixmap, and then copy it to the on-screen window.
It is highly recommended that you put the following code before the first show() of any window in your program:
  Fl::visual(FL_DOUBLE|FL_INDEX)
This makes sure you can use Xdbe on servers where double buffering does not exist for every visual.
Definition at line 49 of file Fl_Double_Window.H.
Constructor & Destructor Documentation
Fl_Double_Window::~Fl_Double_Window ()
The destructor also deletes all the children. This allows a whole tree to be deleted at once, without having to keep a pointer to all the children in the user code.
Definition at line 455 of file Fl_Double_Window.cxx.
References hide().
Fl_Double_Window::Fl_Double_Window (int W, int H, const char * l = 0) [inline]
Creates a new Fl_Double_Window widget using the given position, size, and label (title) string.
Definition at line 69 of file Fl_Double_Window.H.
References FL_DOUBLE_WINDOW, and Fl_Widget::type().
Fl_Double_Window::Fl_Double_Window (int X, int Y, int W, int H, const char * l = 0) [inline]
See Fl_Double_Window::Fl_Double_Window(int w, int h, const char *label = 0)
Definition at line 74 of file Fl_Double_Window.H.
References FL_DOUBLE_WINDOW, and Fl_Widget::type().
Member Function Documentation
void Fl_Double_Window::flush (int eraseoverlay) [protected]
Forces the window to be redrawn.
Parameters:
[in] eraseoverlay non-zero to erase overlay, zero to ignore
Fl_Overlay_Window relies on flush(1) copying the back buffer to the front everywhere, even if damage() == 0, thus erasing the overlay, and leaving the clip region set to the entire window.
Definition at line 333 of file Fl_Double_Window.cxx.
References Fl_X::backbuffer_bad, Fl_Widget::clear_damage(), Fl_Widget::damage(), Fl_Window::draw(), fl_begin_offscreen(), fl_clip_box(), fl_clip_region(), fl_copy_offscreen(), fl_create_offscreen(), FL_DAMAGE_ALL, FL_DAMAGE_EXPOSE, fl_display, fl_end_offscreen(), fl_gc, fl_makeDC(), fl_restore_clip(), fl_window, fl_xid(), force_doublebuffering_, H, Fl_Widget::h(), Fl_X::i(), Fl_Window::make_current(), Fl_X::other_xid, Fl_X::region, Fl_Widget::w(), XDestroyRegion(), and Fl_X::xid.
void Fl_Double_Window::flush () [virtual]
Forces the window to be redrawn.
Reimplemented from Fl_Window.
Reimplemented in Fl_Overlay_Window.
Definition at line 323 of file Fl_Double_Window.cxx.
void Fl_Double_Window::hide () [virtual]
Removes the window from the screen. If the window is already hidden or has not been shown then this does nothing and is harmless.
Reimplemented from Fl_Window.
Reimplemented in Fl_Overlay_Window.
Definition at line 439 of file Fl_Double_Window.cxx.
References fl_delete_offscreen(), Fl_X::i(), and Fl_X::other_xid.
Referenced by Fl_Help_Dialog::hide(), Fl_File_Chooser::hide(), Fl_Class_Type::open(), Fl_Comment_Type::open(), Fl_DeclBlock_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_CodeBlock_Type::open(), Fl_Code_Type::open(), Fl_Function_Type::open(), print_cb(), toggle_sourceview_cb(), and ~Fl_Double_Window().
void Fl_Double_Window::resize (int X, int Y, int W, int H) [virtual]
Changes the size and position of the window. If shown() is true, these changes are communicated to the window server (which may refuse that size and cause a further resize). If shown() is false, the size and position are used when show() is called. See Fl_Group for the effect of resizing on the child widgets.
You can also call the Fl_Widget methods size(x,y) and position(w,h), which are inline wrappers for this virtual function.
A top-level window can not force, but merely suggest a position and size to the operating system. The window manager may not be willing or able to display a window at the desired position or with the given dimensions. It is up to the application developer to verify window parameters after the resize request.
resize a window
Reimplemented from Fl_Window.
Reimplemented in Fl_Overlay_Window, and Overlay_Window.
Definition at line 417 of file Fl_Double_Window.cxx.
References fl_delete_offscreen(), fl_display, Fl_Widget::h(), Fl_X::i(), Fl_X::other_xid, and Fl_Widget::w().
Referenced by Fl_Help_Dialog::resize().
void Fl_Double_Window::show (int argc, char ** argv) [inline]
Puts the window on the screen and parses command-line arguments.
Usually (on X) this has the side effect of opening the display.
This form should be used for top-level windows, at least for the first (main) window. It allows standard arguments to be parsed from the command-line. You can use argc and argv from main(int argc, char **argv) for this call.
The first call also sets up some system-specific internal variables like the system colors.
Todo:
explain which system parameters are set up.
Parameters:
argc command-line argument count, usually from main()
argv command-line argument vector, usually from main()
See also:
virtual void Fl_Window::show()
Reimplemented from Fl_Window.
Reimplemented in Fl_Overlay_Window.
Definition at line 60 of file Fl_Double_Window.H.
void Fl_Double_Window::show () [virtual]
Puts the window on the screen. Usually (on X) this has the side effect of opening the display.
If the window is already shown then it is restored and raised to the top. This is really convenient because your program can call show() at any time, even if the window is already up. It also means that show() serves the purpose of raise() in other toolkits.
Fl_Window::show(int argc, char **argv) is used for top-level windows and allows standard arguments to be parsed from the command-line.
See also:
Fl_Window::show(int argc, char **argv)
make a window visible
Reimplemented from Fl_Window.
Reimplemented in Fl_Overlay_Window.
Definition at line 64 of file Fl_Double_Window.cxx.
Referenced by about_cb(), do_shell_command(), new_cb(), Fl_Class_Type::open(), Fl_Comment_Type::open(), Fl_DeclBlock_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_CodeBlock_Type::open(), Fl_Code_Type::open(), Fl_Function_Type::open(), print_menu_cb(), save_template_cb(), Fl_Help_Dialog::show(), Fl_File_Chooser::show(), show_global_settings_window(), show_grid_cb(), show_project_cb(), show_settings_cb(), show_shell_window(), Fl_PostScript_Printer::start_job(), and toggle_sourceview_cb().
Member Data Documentation
char Fl_Double_Window::force_doublebuffering_ [protected]
Force double buffering, even if the OS already buffers windows (overlays need that on MacOS and Windows2000)
Definition at line 57 of file Fl_Double_Window.H.
Referenced by flush().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Double_Window.H
fltk-1.3.0rc3/src/Fl_Double_Window.cxx