SfR Fresh Dox - fltk: igroup Class Reference
igroup Class Reference
#include <Fl_Type.h>
Public Member Functions
void resize (int, int, int, int)
void full_resize (int X, int Y, int W, int H)
igroup (int X, int Y, int W, int H)
Detailed Description
Definition at line 412 of file Fl_Type.h.
Constructor & Destructor Documentation
igroup::igroup (int X, int Y, int W, int H) [inline]
Definition at line 416 of file Fl_Type.h.
References Fl_Group::current().
Member Function Documentation
void igroup::full_resize (int X, int Y, int W, int H) [inline]
Definition at line 415 of file Fl_Type.h.
References resize().
void igroup::resize (int X, int Y, int W, int H) [virtual]
Resizes the Fl_Group widget and all of its children.
The Fl_Group widget first resizes itself, and then it moves and resizes all its children according to the rules documented for Fl_Group::resizable(Fl_Widget*)
See also:
Fl_Group::resizable(Fl_Widget*)
Fl_Group::resizable()
Fl_Widget::resize(int,int,int,int)
Reimplemented from Fl_Group.
Definition at line 41 of file Fl_Group_Type.cxx.
References Fl_Widget::redraw().
Referenced by full_resize().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Group_Type.cxx