SfR Fresh Dox - fltk: Fl_Graphics_Driver Class Reference
Fl_Graphics_Driver Class Reference
A virtual class subclassed for each graphics driver FLTK uses.
#include <Fl_Device.H>
Public Member Functions
virtual ~Fl_Graphics_Driver ()
The destructor.
Static Public Attributes
static const char * class_id = "Fl_Graphics_Driver"
A string that identifies each subclass of Fl_Device.
Protected Member Functions
Fl_Graphics_Driver ()
The constructor.
virtual void rect (int x, int y, int w, int h)
see fl_rect(int x, int y, int w, int h).
virtual void rectf (int x, int y, int w, int h)
see fl_rectf(int x, int y, int w, int h).
virtual void line_style (int style, int width=0, char *dashes=0)
see fl_line_style(int style, int width, char* dashes).
virtual void xyline (int x, int y, int x1)
see fl_xyline(int x, int y, int x1).
virtual void xyline (int x, int y, int x1, int y2)
see fl_xyline(int x, int y, int x1, int y2).
virtual void xyline (int x, int y, int x1, int y2, int x3)
see fl_xyline(int x, int y, int x1, int y2, int x3).
virtual void yxline (int x, int y, int y1)
see fl_yxline(int x, int y, int y1).
virtual void yxline (int x, int y, int y1, int x2)
see fl_yxline(int x, int y, int y1, int x2).
virtual void yxline (int x, int y, int y1, int x2, int y3)
see fl_yxline(int x, int y, int y1, int x2, int y3).
virtual void line (int x, int y, int x1, int y1)
see fl_line(int x, int y, int x1, int y1).
virtual void line (int x, int y, int x1, int y1, int x2, int y2)
see fl_line(int x, int y, int x1, int y1, int x2, int y2).
virtual void draw (const char *str, int n, int x, int y)
see fl_draw(const char *str, int n, int x, int y).
virtual void draw (int angle, const char *str, int n, int x, int y)
see fl_draw(int angle, const char *str, int n, int x, int y).
virtual void rtl_draw (const char *str, int n, int x, int y)
see fl_rtl_draw(const char *str, int n, int x, int y).
virtual void font (Fl_Font face, Fl_Fontsize size)
see fl_font(Fl_Font face, Fl_Fontsize size).
virtual void color (Fl_Color c)
see fl_color(Fl_Color c).
virtual void color (uchar r, uchar g, uchar b)
see fl_color(uchar r, uchar g, uchar b).
virtual void point (int x, int y)
see fl_point(int x, int y).
virtual void loop (int x0, int y0, int x1, int y1, int x2, int y2)
see fl_loop(int x0, int y0, int x1, int y1, int x2, int y2).
virtual void loop (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3)
see fl_loop(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3).
virtual void polygon (int x0, int y0, int x1, int y1, int x2, int y2)
see fl_polygon(int x0, int y0, int x1, int y1, int x2, int y2).
virtual void polygon (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3)
see fl_polygon(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3).
virtual void begin_points ()
see fl_begin_points().
virtual void begin_line ()
see fl_begin_line().
virtual void begin_loop ()
see fl_begin_loop().
virtual void begin_polygon ()
see fl_begin_polygon().
virtual void vertex (double x, double y)
see fl_vertex(double x, double y).
virtual void curve (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3)
see fl_curve(double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3).
virtual void circle (double x, double y, double r)
see fl_circle(double x, double y, double r).
virtual void arc (double x, double y, double r, double start, double end)
see fl_arc(double x, double y, double r, double start, double end).
virtual void arc (int x, int y, int w, int h, double a1, double a2)
see fl_arc(int x, int y, int w, int h, double a1, double a2).
virtual void pie (int x, int y, int w, int h, double a1, double a2)
see fl_pie(int x, int y, int w, int h, double a1, double a2).
virtual void end_points ()
see fl_end_points().
virtual void end_line ()
see fl_end_line().
virtual void end_loop ()
see fl_end_loop().
virtual void end_polygon ()
see fl_end_polygon().
virtual void begin_complex_polygon ()
see fl_begin_complex_polygon().
virtual void gap ()
see fl_gap().
virtual void end_complex_polygon ()
see fl_end_complex_polygon().
virtual void transformed_vertex (double xf, double yf)
see fl_transformed_vertex(double xf, double yf).
virtual void push_clip (int x, int y, int w, int h)
see fl_push_clip(int x, int y, int w, int h).
virtual int clip_box (int x, int y, int w, int h, int &X, int &Y, int &W, int &H)
see fl_clip_box(int x, int y, int w, int h, int &X, int &Y, int &W, int &H).
virtual int not_clipped (int x, int y, int w, int h)
see fl_not_clipped(int x, int y, int w, int h).
virtual void push_no_clip ()
see fl_push_no_clip().
virtual void pop_clip ()
see fl_pop_clip().
virtual void draw_image (const uchar *buf, int X, int Y, int W, int H, int D=3, int L=0)
see fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L).
virtual void draw_image_mono (const uchar *buf, int X, int Y, int W, int H, int D=1, int L=0)
see fl_draw_image_mono(const uchar* buf, int X,int Y,int W,int H, int D, int L).
virtual void draw_image (Fl_Draw_Image_Cb cb, void *data, int X, int Y, int W, int H, int D=3)
see fl_draw_image(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
virtual void draw_image_mono (Fl_Draw_Image_Cb cb, void *data, int X, int Y, int W, int H, int D=1)
see fl_draw_image_mono(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
virtual void draw (Fl_RGB_Image *rgb, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_RGB_Image object to the device.
virtual void draw (Fl_Pixmap *pxm, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_Pixmap object to the device.
virtual void draw (Fl_Bitmap *bm, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_Bitmap object to the device.
Friends
class Fl_Pixmap
class Fl_Bitmap
class Fl_RGB_Image
class Fl_PostScript_Graphics_Driver
void fl_rect (int x, int y, int w, int h)
void fl_rectf (int x, int y, int w, int h)
void fl_line_style (int style, int width, char *dashes)
void fl_xyline (int x, int y, int x1)
void fl_xyline (int x, int y, int x1, int y2)
void fl_xyline (int x, int y, int x1, int y2, int x3)
void fl_yxline (int x, int y, int y1)
void fl_yxline (int x, int y, int y1, int x2)
void fl_yxline (int x, int y, int y1, int x2, int y3)
void fl_line (int x, int y, int x1, int y1)
void fl_line (int x, int y, int x1, int y1, int x2, int y2)
void fl_draw (const char *str, int n, int x, int y)
void fl_draw (int angle, const char *str, int n, int x, int y)
void fl_rtl_draw (const char *str, int n, int x, int y)
void fl_font (Fl_Font face, Fl_Fontsize size)
void fl_color (Fl_Color c)
void fl_color (uchar r, uchar g, uchar b)
void fl_point (int x, int y)
void fl_loop (int x0, int y0, int x1, int y1, int x2, int y2)
void fl_loop (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3)
void fl_polygon (int x0, int y0, int x1, int y1, int x2, int y2)
void fl_polygon (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3)
void fl_begin_points ()
void fl_begin_line ()
void fl_begin_loop ()
void fl_begin_polygon ()
void fl_vertex (double x, double y)
void fl_curve (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3)
void fl_circle (double x, double y, double r)
void fl_arc (double x, double y, double r, double start, double end)
void fl_arc (int x, int y, int w, int h, double a1, double a2)
void fl_pie (int x, int y, int w, int h, double a1, double a2)
void fl_end_points ()
void fl_end_line ()
void fl_end_loop ()
void fl_end_polygon ()
void fl_transformed_vertex (double xf, double yf)
void fl_push_clip (int x, int y, int w, int h)
int fl_clip_box (int x, int y, int w, int h, int &X, int &Y, int &W, int &H)
int fl_not_clipped (int x, int y, int w, int h)
void fl_push_no_clip ()
void fl_pop_clip ()
void fl_begin_complex_polygon ()
void fl_gap ()
void fl_end_complex_polygon ()
void fl_draw_image (const uchar *buf, int X, int Y, int W, int H, int D, int L)
void fl_draw_image_mono (const uchar *buf, int X, int Y, int W, int H, int D, int L)
void fl_draw_image (Fl_Draw_Image_Cb cb, void *data, int X, int Y, int W, int H, int D)
FL_EXPORT void fl_draw_image_mono (Fl_Draw_Image_Cb cb, void *data, int X, int Y, int W, int H, int D)
Detailed Description
A virtual class subclassed for each graphics driver FLTK uses.
The protected virtual methods of this class are those that a graphics driver should implement to support all of FLTK drawing functions.
The public API for drawing operations is functionally presented in Drawing Things in FLTK and as function lists in the Drawing functions and Color & Font functions modules.
Definition at line 96 of file Fl_Device.H.
Constructor & Destructor Documentation
Fl_Graphics_Driver::Fl_Graphics_Driver () [inline, protected]
The constructor.
Definition at line 159 of file Fl_Device.H.
virtual Fl_Graphics_Driver::~Fl_Graphics_Driver () [inline, virtual]
The destructor.
Definition at line 282 of file Fl_Device.H.
Member Function Documentation
void Fl_Graphics_Driver::arc (double x, double y, double r, double start, double end) [protected, virtual]
see fl_arc(double x, double y, double r, double start, double end).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 46 of file fl_arc.cxx.
References epsilon, fl_transform_dx(), fl_transform_dy(), fl_vertex, i, int, and M_PI.
Referenced by fl_arc().
void Fl_Graphics_Driver::arc (int x, int y, int w, int h, double a1, double a2) [protected, virtual]
see fl_arc(int x, int y, int w, int h, double a1, double a2).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 50 of file fl_arci.cxx.
References CGContextRestoreGState, CGContextSaveGState, f, fl_display, fl_gc, fl_RGB(), fl_window, h, int, and M_PI.
void Fl_Graphics_Driver::begin_complex_polygon () [protected, virtual]
see fl_begin_complex_polygon().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 287 of file fl_vertex.cxx.
References fl_begin_polygon.
Referenced by fl_begin_complex_polygon().
void Fl_Graphics_Driver::begin_line () [protected, virtual]
see fl_begin_line().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 150 of file fl_vertex.cxx.
References LINE.
Referenced by fl_begin_line().
void Fl_Graphics_Driver::begin_loop () [protected, virtual]
see fl_begin_loop().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 152 of file fl_vertex.cxx.
References LOOP.
Referenced by fl_begin_loop().
void Fl_Graphics_Driver::begin_points () [protected, virtual]
see fl_begin_points().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 148 of file fl_vertex.cxx.
References POINT_.
Referenced by fl_begin_points().
void Fl_Graphics_Driver::begin_polygon () [protected, virtual]
see fl_begin_polygon().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 154 of file fl_vertex.cxx.
References POLYGON.
Referenced by fl_begin_polygon().
void Fl_Graphics_Driver::circle (double x, double y, double r) [protected, virtual]
see fl_circle(double x, double y, double r).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 339 of file fl_vertex.cxx.
References matrix::a, matrix::b, matrix::c, CGContextFillPath, matrix::d, f, fl_brush(), fl_display, fl_gc, fl_transform_x(), fl_transform_y(), fl_window, h, int, M_PI, POLYGON, and w.
Referenced by fl_circle().
int Fl_Graphics_Driver::clip_box (int x, int y, int w, int h, int & X, int & Y, int & W, int & H) [protected, virtual]
see fl_clip_box(int x, int y, int w, int h, int &X, int &Y, int &W, int &H).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 651 of file fl_rect.cxx.
References Fl_Printer::class_id, Fl_Device::class_name(), fl_gc, h, XRectangle::height, i, int, rect(), Fl_Surface_Device::surface(), w, XRectangle::width, XRectangle::x, x, XClipBox(), XDestroyRegion(), XRectangleRegion(), XRectangle::y, and y.
Referenced by fl_clip_box().
virtual void Fl_Graphics_Driver::color (Fl_Color c) [inline, protected, virtual]
see fl_color(Fl_Color c).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 191 of file Fl_Device.H.
Referenced by fl_color().
virtual void Fl_Graphics_Driver::color (uchar r, uchar g, uchar b) [inline, protected, virtual]
see fl_color(uchar r, uchar g, uchar b).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 193 of file Fl_Device.H.
void Fl_Graphics_Driver::curve (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3) [protected, virtual]
see fl_curve(double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 41 of file fl_curve.cxx.
References b, fl_transform_x(), fl_transform_y(), fl_transformed_vertex, int, m, x, and y.
Referenced by fl_curve().
virtual void Fl_Graphics_Driver::draw (const char * str, int n, int x, int y) [inline, protected, virtual]
see fl_draw(const char *str, int n, int x, int y).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 183 of file Fl_Device.H.
Referenced by Fl_Pixmap::draw(), Fl_RGB_Image::draw(), Fl_Bitmap::draw(), and fl_draw().
virtual void Fl_Graphics_Driver::draw (Fl_Pixmap * pxm, int XP, int YP, int WP, int HP, int cx, int cy) [inline, protected, virtual]
Draws an Fl_Pixmap object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 271 of file Fl_Device.H.
virtual void Fl_Graphics_Driver::draw (int angle, const char * str, int n, int x, int y) [inline, protected, virtual]
see fl_draw(int angle, const char *str, int n, int x, int y).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 185 of file Fl_Device.H.
virtual void Fl_Graphics_Driver::draw (Fl_RGB_Image * rgb, int XP, int YP, int WP, int HP, int cx, int cy) [inline, protected, virtual]
Draws an Fl_RGB_Image object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 265 of file Fl_Device.H.
virtual void Fl_Graphics_Driver::draw (Fl_Bitmap * bm, int XP, int YP, int WP, int HP, int cx, int cy) [inline, protected, virtual]
Draws an Fl_Bitmap object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 277 of file Fl_Device.H.
virtual void Fl_Graphics_Driver::draw_image (const uchar * buf, int X, int Y, int W, int H, int D = 3, int L = 0) [inline, protected, virtual]
see fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 252 of file Fl_Device.H.
Referenced by fl_draw_image().
virtual void Fl_Graphics_Driver::draw_image (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 3) [inline, protected, virtual]
see fl_draw_image(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 256 of file Fl_Device.H.
virtual void Fl_Graphics_Driver::draw_image_mono (const uchar * buf, int X, int Y, int W, int H, int D = 1, int L = 0) [inline, protected, virtual]
see fl_draw_image_mono(const uchar* buf, int X,int Y,int W,int H, int D, int L).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 254 of file Fl_Device.H.
Referenced by fl_draw_image_mono().
virtual void Fl_Graphics_Driver::draw_image_mono (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 1) [inline, protected, virtual]
see fl_draw_image_mono(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 258 of file Fl_Device.H.
void Fl_Graphics_Driver::end_complex_polygon () [protected, virtual]
see fl_end_complex_polygon().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 308 of file fl_vertex.cxx.
References CGContextClosePath, CGContextFillPath, CGContextMoveToPoint, fl_brush(), fl_display, fl_end_line, fl_gap, fl_gc, fl_window, and i.
Referenced by fl_end_complex_polygon().
void Fl_Graphics_Driver::end_line () [protected, virtual]
see fl_end_line().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 222 of file fl_vertex.cxx.
References CGContextMoveToPoint, fl_display, fl_end_points, fl_gc, fl_window, and i.
Referenced by fl_end_line().
void Fl_Graphics_Driver::end_loop () [protected, virtual]
see fl_end_loop().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 248 of file fl_vertex.cxx.
References fl_end_line, and fl_transformed_vertex.
Referenced by fl_end_loop().
void Fl_Graphics_Driver::end_points () [protected, virtual]
see fl_end_points().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 204 of file fl_vertex.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, fl_RGB(), fl_window, and i.
Referenced by fl_end_points().
void Fl_Graphics_Driver::end_polygon () [protected, virtual]
see fl_end_polygon().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 254 of file fl_vertex.cxx.
References CGContextClosePath, CGContextFillPath, CGContextMoveToPoint, fl_brush(), fl_display, fl_end_line, fl_gc, fl_window, and i.
Referenced by fl_end_polygon().
virtual void Fl_Graphics_Driver::font (Fl_Font face, Fl_Fontsize size) [inline, protected, virtual]
see fl_font(Fl_Font face, Fl_Fontsize size).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 189 of file Fl_Device.H.
Referenced by fl_font().
void Fl_Graphics_Driver::gap () [protected, virtual]
see fl_gap().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 295 of file fl_vertex.cxx.
References fl_transformed_vertex.
Referenced by fl_gap(), and line_style().
void Fl_Graphics_Driver::line (int x, int y, int x1, int y1, int x2, int y2) [protected, virtual]
see fl_line(int x, int y, int x1, int y1, int x2, int y2).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 359 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, fl_RGB(), fl_window, x, and y.
void Fl_Graphics_Driver::line (int x, int y, int x1, int y1) [protected, virtual]
see fl_line(int x, int y, int x1, int y1).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 339 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, fl_RGB(), and fl_window.
Referenced by fl_line().
void Fl_Graphics_Driver::line_style (int style, int width = 0, char * dashes = 0) [protected, virtual]
see fl_line_style(int style, int width, char* dashes).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 59 of file fl_line_style.cxx.
References buf, Fl_Printer::class_id, Fl_Device::class_name(), Fl::error, fl_current_xmap, FL_DASH, FL_DASHDOT, FL_DASHDOTDOT, fl_display, FL_DOT, fl_gc, fl_line_width_, fl_quartz_restore_line_style_(), fl_RGB(), FL_SOLID, gap(), NULL, Fl_XMap::pen, s1, Fl_Surface_Device::surface(), w, and width.
Referenced by fl_line_style().
void Fl_Graphics_Driver::loop (int x0, int y0, int x1, int y1, int x2, int y2) [protected, virtual]
see fl_loop(int x0, int y0, int x1, int y1, int x2, int y2).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 385 of file fl_rect.cxx.
References CGContextClosePath, CGContextMoveToPoint, fl_display, fl_gc, fl_window, x, and y.
Referenced by fl_loop().
void Fl_Graphics_Driver::loop (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3) [protected, virtual]
see fl_loop(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 411 of file fl_rect.cxx.
References CGContextClosePath, CGContextMoveToPoint, fl_display, fl_gc, fl_window, x, and y.
int Fl_Graphics_Driver::not_clipped (int x, int y, int w, int h) [protected, virtual]
see fl_not_clipped(int x, int y, int w, int h).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 620 of file fl_rect.cxx.
References Fl_Printer::class_id, Fl_Device::class_name(), fl_gc, h, i, rect(), Fl_Surface_Device::surface(), w, x, and y.
Referenced by fl_not_clipped().
void Fl_Graphics_Driver::pie (int x, int y, int w, int h, double a1, double a2) [protected, virtual]
see fl_pie(int x, int y, int w, int h, double a1, double a2).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 85 of file fl_arci.cxx.
References CGContextClosePath, CGContextFillPath, CGContextRestoreGState, CGContextSaveGState, f, fl_brush(), fl_display, fl_gc, fl_RGB(), fl_window, h, int, and M_PI.
Referenced by fl_pie().
void Fl_Graphics_Driver::point (int x, int y) [protected, virtual]
see fl_point(int x, int y).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 492 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, fl_RGB(), and fl_window.
Referenced by fl_point().
void Fl_Graphics_Driver::polygon (int x0, int y0, int x1, int y1, int x2, int y2) [protected, virtual]
see fl_polygon(int x0, int y0, int x1, int y1, int x2, int y2).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 440 of file fl_rect.cxx.
References CGContextClosePath, CGContextFillPath, CGContextMoveToPoint, fl_brush(), fl_display, fl_gc, fl_window, x, and y.
Referenced by fl_polygon().
void Fl_Graphics_Driver::polygon (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3) [protected, virtual]
see fl_polygon(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 465 of file fl_rect.cxx.
References CGContextClosePath, CGContextFillPath, CGContextMoveToPoint, fl_brush(), fl_display, fl_gc, fl_window, x, and y.
void Fl_Graphics_Driver::pop_clip () [protected, virtual]
see fl_pop_clip().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 612 of file fl_rect.cxx.
References fl_restore_clip(), Fl::warning, and XDestroyRegion().
Referenced by fl_pop_clip().
void Fl_Graphics_Driver::push_clip (int x, int y, int w, int h) [protected, virtual]
see fl_push_clip(int x, int y, int w, int h).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 568 of file fl_rect.cxx.
References fl_restore_clip(), STACK_MAX, Fl::warning, XDestroyRegion(), and XRectangleRegion().
Referenced by fl_push_clip().
void Fl_Graphics_Driver::push_no_clip () [protected, virtual]
see fl_push_no_clip().
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 605 of file fl_rect.cxx.
References fl_restore_clip(), STACK_MAX, and Fl::warning.
Referenced by fl_push_no_clip().
void Fl_Graphics_Driver::rect (int x, int y, int w, int h) [protected, virtual]
see fl_rect(int x, int y, int w, int h).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 161 of file fl_rect.cxx.
References f, fl_display, fl_gc, and fl_window.
Referenced by clip_box(), fl_rect(), not_clipped(), and rectf().
void Fl_Graphics_Driver::rectf (int x, int y, int w, int h) [protected, virtual]
see fl_rectf(int x, int y, int w, int h).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 183 of file fl_rect.cxx.
References CGContextFillRect, f, fl_brush(), fl_display, fl_gc, fl_window, h, rect(), w, x, and y.
Referenced by fl_rectf().
virtual void Fl_Graphics_Driver::rtl_draw (const char * str, int n, int x, int y) [inline, protected, virtual]
see fl_rtl_draw(const char *str, int n, int x, int y).
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 187 of file Fl_Device.H.
Referenced by fl_rtl_draw().
void Fl_Graphics_Driver::transformed_vertex (double xf, double yf) [protected, virtual]
see fl_transformed_vertex(double xf, double yf).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 192 of file fl_vertex.cxx.
References fl_transformed_vertex.
Referenced by fl_transformed_vertex().
void Fl_Graphics_Driver::vertex (double x, double y) [protected, virtual]
see fl_vertex(double x, double y).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 200 of file fl_vertex.cxx.
References matrix::a, matrix::b, matrix::c, matrix::d, fl_transformed_vertex, matrix::x, and matrix::y.
Referenced by fl_vertex().
void Fl_Graphics_Driver::xyline (int x, int y, int x1) [protected, virtual]
see fl_xyline(int x, int y, int x1).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 203 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, and fl_window.
Referenced by fl_xyline().
void Fl_Graphics_Driver::xyline (int x, int y, int x1, int y2) [protected, virtual]
see fl_xyline(int x, int y, int x1, int y2).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 219 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, and fl_window.
void Fl_Graphics_Driver::xyline (int x, int y, int x1, int y2, int x3) [protected, virtual]
see fl_xyline(int x, int y, int x1, int y2, int x3).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 243 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, and fl_window.
void Fl_Graphics_Driver::yxline (int x, int y, int y1, int x2, int y3) [protected, virtual]
see fl_yxline(int x, int y, int y1, int x2, int y3).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 312 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, and fl_window.
void Fl_Graphics_Driver::yxline (int x, int y, int y1, int x2) [protected, virtual]
see fl_yxline(int x, int y, int y1, int x2).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 288 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, and fl_window.
void Fl_Graphics_Driver::yxline (int x, int y, int y1) [protected, virtual]
see fl_yxline(int x, int y, int y1).
Reimplemented in Fl_PostScript_Graphics_Driver.
Definition at line 270 of file fl_rect.cxx.
References CGContextMoveToPoint, f, fl_display, fl_gc, and fl_window.
Referenced by fl_yxline().
Friends And Related Function Documentation
void fl_arc (double x, double y, double r, double start, double end) [friend]
Add a series of points to the current path on the arc of a circle; you can get elliptical paths by using scale and rotate before calling fl_arc().
Parameters:
[in] x,y,r center and radius of circular arc
[in] start,end angles of start and end of arc measured in degrees counter-clockwise from 3 o'clock. If end is less than start then it draws the arc in a clockwise direction.
Definition at line 375 of file fl_draw.H.
void fl_arc (int x, int y, int w, int h, double a1, double a2) [friend]
Draw ellipse sections using integer coordinates.
These functions match the rather limited circle drawing code provided by X and WIN32. The advantage over using fl_arc with floating point coordinates is that they are faster because they often use the hardware, and they draw much nicer small circles, since the small sizes are often hard-coded bitmaps.
If a complete circle is drawn it will fit inside the passed bounding box. The two angles are measured in degrees counterclockwise from 3 o'clock and are the starting and ending angle of the arc, a2 must be greater or equal to a1.
fl_arc() draws a series of lines to approximate the arc. Notice that the integer version of fl_arc() has a different number of arguments than the double version fl_arc(double x, double y, double r, double start, double end)
Parameters:
[in] x,y,w,h bounding box of complete circle
[in] a1,a2 start and end angles of arc measured in degrees counter-clockwise from 3 o'clock. a2 must be greater than or equal to a1.
Definition at line 311 of file fl_draw.H.
void fl_begin_complex_polygon () [friend]
Starts drawing a complex filled polygon.
The polygon may be concave, may have holes in it, or may be several disconnected pieces. Call fl_gap() to separate loops of the path.
To outline the polygon, use fl_begin_loop() and replace each fl_gap() with fl_end_loop();fl_begin_loop() pairs.
Note:
For portability, you should only draw polygons that appear the same whether "even/odd" or "non-zero" winding rules are used to fill them. Holes should be drawn in the opposite direction to the outside loop.
Definition at line 414 of file fl_draw.H.
void fl_begin_line () [friend]
Starts drawing a list of lines.
Definition at line 343 of file fl_draw.H.
void fl_begin_loop () [friend]
Starts drawing a closed sequence of lines.
Definition at line 347 of file fl_draw.H.
void fl_begin_points () [friend]
Starts drawing a list of points. Points are added to the list with fl_vertex()
Definition at line 339 of file fl_draw.H.
void fl_begin_polygon () [friend]
Starts drawing a convex filled polygon.
Definition at line 351 of file fl_draw.H.
Referenced by begin_complex_polygon().
friend class Fl_Bitmap [friend]
Definition at line 105 of file Fl_Device.H.
void fl_circle (double x, double y, double r) [friend]
fl_circle() is equivalent to fl_arc(x,y,r,0,360), but may be faster.
It must be the only thing in the path: if you want a circle as part of a complex polygon you must use fl_arc()
Parameters:
[in] x,y,r center and radius of circle
Definition at line 383 of file fl_draw.H.
int fl_clip_box (int x, int y, int w, int h, int & X, int & Y, int & W, int & H) [friend]
Intersects the rectangle with the current clip region and returns the bounding box of the result.
Returns non-zero if the resulting rectangle is different to the original. This can be used to limit the necessary drawing to a rectangle. W and H are set to zero if the rectangle is completely outside the region.
Parameters:
[in] x,y,w,h position and size of rectangle
[out] X,Y,W,H position and size of resulting bounding box. W and H are set to zero if the rectangle is completely outside the region.
Returns:
Non-zero if the resulting rectangle is different to the original.
Definition at line 133 of file fl_draw.H.
Referenced by Fl_Xlib_Graphics_Driver::draw().
void fl_color (Fl_Color c) [friend]
Sets the color for all subsequent drawing operations. For colormapped displays, a color cell will be allocated out of fl_colormap the first time you use a color. If the colormap fills up then a least-squares algorithm is used to find the closest color. If no valid graphical context (fl_gc) is available, the foreground is not set for the current window.
Parameters:
[in] c color
Definition at line 61 of file fl_draw.H.
Referenced by Fl_Xlib_Graphics_Driver::color().
void fl_color (uchar r, uchar g, uchar b) [friend]
Set the color for all subsequent drawing operations. The closest possible match to the RGB color is used. The RGB color is used directly on TrueColor displays. For colormap visuals the nearest index in the gray ramp or color cube is used. If no valid graphical context (fl_gc) is available, the foreground is not set for the current window.
Parameters:
[in] r,g,b color components
Definition at line 74 of file fl_draw.H.
void fl_curve (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3) [friend]
Add a series of points on a Bezier curve to the path. The curve ends (and two of the points) are at X0,Y0 and X3,Y3.
Parameters:
[in] X0,Y0 curve start point
[in] X1,Y1 curve control point
[in] X2,Y2 curve control point
[in] X3,Y3 curve end point
Definition at line 365 of file fl_draw.H.
void fl_draw (int angle, const char * str, int n, int x, int y) [friend]
Draws an array of n characters starting at the given location, rotating angle degrees counterclockwise.
Definition at line 563 of file fl_draw.H.
void fl_draw (const char * str, int n, int x, int y) [friend]
Draws an array of n characters starting at the given location.
Definition at line 558 of file fl_draw.H.
Referenced by Fl_Xlib_Graphics_Driver::draw().
void fl_draw_image (const uchar * buf, int X, int Y, int W, int H, int D = 3, int L = 0) [friend]
Draw an 8-bit per color RGB or luminance image.
Parameters:
[in] buf points at the "r" data of the top-left pixel. Color data must be in r,g,b order.
[in] X,Y position where to put top-left corner of image
[in] W,H size of the image
[in] D delta to add to the pointer between pixels. it may be any value greater than or equal to 3, or it can be negative to flip the image horizontally
[in] L delta to add to the pointer between lines (if 0 is passed it uses W * D), and may be larger than W * D to crop data, or negative to flip the image vertically
It is highly recommended that you put the following code before the first show() of any window in your program to get rid of the dithering if possible:
  Fl::visual(FL_RGB);
Gray scale (1-channel) images may be drawn. This is done if abs(D) is less than 3, or by calling fl_draw_image_mono(). Only one 8-bit sample is used for each pixel, and on screens with different numbers of bits for red, green, and blue only gray colors are used. Setting D greater than 1 will let you display one channel of a color image.
Note:
The X version does not support all possible visuals. If FLTK cannot draw the image in the current visual it will abort. FLTK supports any visual of 8 bits or less, and all common TrueColor visuals up to 32 bits.
Definition at line 618 of file fl_draw.H.
Referenced by Fl_Xlib_Graphics_Driver::draw().
void fl_draw_image (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 3) [friend]
Draw image using callback function to generate image data. You can generate the image as it is being drawn, or do arbitrary decompression of stored data, provided it can be decompressed to individual scan lines easily.
Parameters:
[in] cb callback function to generate scan line data
[in] data user data passed to callback function
[in] X,Y
[in] W,H
[in] D
See also:
fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L)
The callback function cb is called with the void* data user data pointer to allow access to a structure of information about the image, and the x, y, and w of the scan line desired from the image. 0,0 is the upper-left corner of the image, not X, Y. A pointer to a buffer to put the data into is passed. You must copy w pixels from scanline y, starting at pixel x, to this buffer.
Due to cropping, less than the whole image may be requested. So x may be greater than zero, the first y may be greater than zero, and w may be less than W. The buffer is long enough to store the entire W * D pixels, this is for convenience with some decompression schemes where you must decompress the entire line at once: decompress it into the buffer, and then if x is not zero, copy the data over so the x'th pixel is at the start of the buffer.
You can assume the y's will be consecutive, except the first one may be greater than zero.
If D is 4 or more, you must fill in the unused bytes with zero.
Definition at line 660 of file fl_draw.H.
void fl_draw_image_mono (const uchar * buf, int X, int Y, int W, int H, int D = 1, int L = 0) [friend]
Draw a gray-scale (1 channel) image.
See also:
fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L)
Definition at line 625 of file fl_draw.H.
FL_EXPORT void fl_draw_image_mono (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D) [friend]
Draw gray-scale image using callback function to generate image data.
See also:
fl_draw_image(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D)
void fl_end_complex_polygon () [friend]
Ends complex filled polygon, and draws.
Definition at line 425 of file fl_draw.H.
void fl_end_line () [friend]
Ends list of lines, and draws.
Definition at line 391 of file fl_draw.H.
Referenced by end_complex_polygon(), end_loop(), and end_polygon().
void fl_end_loop () [friend]
Ends closed sequence of lines, and draws.
Definition at line 395 of file fl_draw.H.
void fl_end_points () [friend]
Ends list of points, and draws.
Definition at line 387 of file fl_draw.H.
Referenced by end_line().
void fl_end_polygon () [friend]
Ends convex filled polygon, and draws.
Definition at line 399 of file fl_draw.H.
void fl_font (Fl_Font face, Fl_Fontsize size) [friend]
Sets the current font, which is then used in various drawing routines. You may call this outside a draw context if necessary to call fl_width(), but on X this will open the display.
The font is identified by a face and a size. The size of the font is measured in pixels and not "points". Lines should be spaced size pixels apart or more.
Definition at line 452 of file fl_draw.H.
Referenced by Fl_Xlib_Graphics_Driver::draw(), and Fl_Xlib_Graphics_Driver::rtl_draw().
void fl_gap () [friend]
Call fl_gap() to separate loops of the path.
It is unnecessary but harmless to call fl_gap() before the first vertex, after the last vertex, or several times in a row.
Definition at line 421 of file fl_draw.H.
Referenced by end_complex_polygon().
void fl_line (int x, int y, int x1, int y1) [friend]
Draws a line from (x,y) to (x1,y1)
Definition at line 230 of file fl_draw.H.
void fl_line (int x, int y, int x1, int y1, int x2, int y2) [friend]
Draws a line from (x,y) to (x1,y1) and another from (x1,y1) to (x2,y2)
Definition at line 234 of file fl_draw.H.
void fl_line_style (int style, int width = 0, char * dashes = 0) [friend]
Sets how to draw lines (the "pen"). If you change this it is your responsibility to set it back to the default using fl_line_style(0).
Parameters:
[in] style A bitmask which is a bitwise-OR of a line style, a cap style, and a join style. If you don't specify a dash type you will get a solid line. If you don't specify a cap or join type you will get a system-defined default of whatever value is fastest.
[in] width The thickness of the lines in pixels. Zero results in the system defined default, which on both X and Windows is somewhat different and nicer than 1.
[in] dashes A pointer to an array of dash lengths, measured in pixels. The first location is how long to draw a solid portion, the next is how long to draw the gap, then the solid, etc. It is terminated with a zero-length entry. A NULL pointer or a zero-length array results in a solid line. Odd array sizes are not supported and result in undefined behavior.
Note:
Because of how line styles are implemented on Win32 systems, you must set the line style after setting the drawing color. If you set the color after the line style you will lose the line style settings.
The dashes array does not work under Windows 95, 98 or Me, since those operating systems do not support complex line styles.
Definition at line 184 of file fl_draw.H.
void fl_loop (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3) [friend]
Outlines a 4-sided polygon with lines
Definition at line 244 of file fl_draw.H.
void fl_loop (int x0, int y0, int x1, int y1, int x2, int y2) [friend]
Outlines a 3-sided polygon with lines
Definition at line 240 of file fl_draw.H.
int fl_not_clipped (int x, int y, int w, int h) [friend]
Does the rectangle intersect the current clip region?
Parameters:
[in] x,y,w,h position and size of rectangle
Returns:
non-zero if any of the rectangle intersects the current clip region. If this returns 0 you don't have to draw the object.
Note:
Under X this returns 2 if the rectangle is partially clipped, and 1 if it is entirely inside the clip region.
Definition at line 118 of file fl_draw.H.
void fl_pie (int x, int y, int w, int h, double a1, double a2) [friend]
Draw filled ellipse sections using integer coordinates.
Like fl_arc(), but fl_pie() draws a filled-in pie slice. This slice may extend outside the line drawn by fl_arc(); to avoid this use w - 1 and h - 1.
Parameters:
[in] x,y,w,h bounding box of complete circle
[in] a1,a2 start and end angles of arc measured in degrees counter-clockwise from 3 o'clock. a2 must be greater than or equal to a1.
Definition at line 324 of file fl_draw.H.
friend class Fl_Pixmap [friend]
Definition at line 104 of file Fl_Device.H.
void fl_point (int x, int y) [friend]
Draws a single pixel at the given coordinates
Definition at line 154 of file fl_draw.H.
void fl_polygon (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3) [friend]
Fills a 4-sided polygon. The polygon must be convex.
Definition at line 255 of file fl_draw.H.
void fl_polygon (int x0, int y0, int x1, int y1, int x2, int y2) [friend]
Fills a 3-sided polygon. The polygon must be convex.
Definition at line 251 of file fl_draw.H.
void fl_pop_clip () [friend]
Restores the previous clip region.
You must call fl_pop_clip() once for every time you call fl_push_clip(). Unpredictable results may occur if the clip stack is not empty when you return to FLTK.
Definition at line 107 of file fl_draw.H.
friend class Fl_PostScript_Graphics_Driver [friend]
Definition at line 107 of file Fl_Device.H.
void fl_push_clip (int x, int y, int w, int h) [friend]
Intersects the current clip region with a rectangle and pushes this new region onto the stack.
Parameters:
[in] x,y,w,h position and size
Definition at line 93 of file fl_draw.H.
void fl_push_no_clip () [friend]
Pushes an empty clip region onto the stack so nothing will be clipped.
Definition at line 99 of file fl_draw.H.
void fl_rect (int x, int y, int w, int h) [friend]
Draws a 1-pixel border inside the given bounding box. This function is meant for quick drawing of simple boxes. The behavior is undefined for line widths that are not 1.
Definition at line 208 of file fl_draw.H.
void fl_rectf (int x, int y, int w, int h) [friend]
Colors with current color a rectangle that exactly fills the given bounding box
Definition at line 213 of file fl_draw.H.
friend class Fl_RGB_Image [friend]
Definition at line 106 of file Fl_Device.H.
void fl_rtl_draw (const char * str, int n, int x, int y) [friend]
Draws an array of n characters right to left starting at given location.
Definition at line 567 of file fl_draw.H.
void fl_transformed_vertex (double xf, double yf) [friend]
Adds coordinate pair to the vertex list without further transformations.
Parameters:
[in] xf,yf transformed coordinate
Definition at line 435 of file fl_draw.H.
Referenced by curve(), end_loop(), gap(), transformed_vertex(), and vertex().
void fl_vertex (double x, double y) [friend]
Adds a single vertex to the current path.
Parameters:
[in] x,y coordinate
Definition at line 356 of file fl_draw.H.
Referenced by arc().
void fl_xyline (int x, int y, int x1) [friend]
Draws a horizontal line from (x,y) to (x1,y)
Definition at line 262 of file fl_draw.H.
void fl_xyline (int x, int y, int x1, int y2, int x3) [friend]
Draws a horizontal line from (x,y) to (x1,y), then a vertical from (x1,y) to (x1,y2) and then another horizontal from (x1,y2) to (x3,y2)
Definition at line 271 of file fl_draw.H.
void fl_xyline (int x, int y, int x1, int y2) [friend]
Draws a horizontal line from (x,y) to (x1,y), then vertical from (x1,y) to (x1,y2)
Definition at line 266 of file fl_draw.H.
void fl_yxline (int x, int y, int y1, int x2) [friend]
Draws a vertical line from (x,y) to (x,y1), then a horizontal from (x,y1) to (x2,y1)
Definition at line 281 of file fl_draw.H.
void fl_yxline (int x, int y, int y1, int x2, int y3) [friend]
Draws a vertical line from (x,y) to (x,y1) then a horizontal from (x,y1) to (x2,y1), then another vertical from (x2,y1) to (x2,y3)
Definition at line 286 of file fl_draw.H.
void fl_yxline (int x, int y, int y1) [friend]
Draws a vertical line from (x,y) to (x,y1)
Definition at line 277 of file fl_draw.H.
Member Data Documentation
const char * Fl_Graphics_Driver::class_id = "Fl_Graphics_Driver" [static]
A string that identifies each subclass of Fl_Device.
Function class_name() applied to a device of this class returns this string.
Reimplemented from Fl_Device.
Reimplemented in Fl_Xlib_Graphics_Driver, and Fl_PostScript_Graphics_Driver.
Definition at line 277 of file Fl_Device.H.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Device.H
fltk-1.3.0rc3/src/fl_arc.cxx
fltk-1.3.0rc3/src/fl_arci.cxx
fltk-1.3.0rc3/src/fl_curve.cxx
fltk-1.3.0rc3/src/Fl_Device.cxx
fltk-1.3.0rc3/src/fl_line_style.cxx
fltk-1.3.0rc3/src/fl_rect.cxx
fltk-1.3.0rc3/src/fl_vertex.cxx