SfR Fresh Dox - fltk: Fl_Plugin_Manager Class Reference
Fl_Plugin_Manager Class Reference
Fl_Plugin_Manager manages link-time and run-time plugin binaries.
#include <Fl_Plugin.H>
Public Member Functions
Fl_Plugin_Manager (const char *klass)
Manage all plugins belonging to one class.
~Fl_Plugin_Manager ()
Remove the plugin manager.
int plugins ()
Return the number of plugins in the klass.
Fl_Plugin * plugin (int index)
Return the address of a plugin by index.
Fl_Plugin * plugin (const char *name)
Return the address of a plugin by name.
Fl_Preferences::ID addPlugin (const char *name, Fl_Plugin *plugin)
This function adds a new plugin to the database.
Static Public Member Functions
static void removePlugin (Fl_Preferences::ID id)
Remove any plugin.
static int load (const char *filename)
Load a module from disk.
static int loadAll (const char *filepath, const char *pattern=0)
Use this function to load a whole directory full of modules.
Detailed Description
Fl_Plugin_Manager manages link-time and run-time plugin binaries.
See also:
Fl_Plugin
Definition at line 83 of file Fl_Plugin.H.
Constructor & Destructor Documentation
Fl_Plugin_Manager::Fl_Plugin_Manager (const char * klass)
Manage all plugins belonging to one class.
Definition at line 1653 of file Fl_Preferences.cxx.
Fl_Plugin_Manager::~Fl_Plugin_Manager ()
Remove the plugin manager.
Calling this does not remove the database itself or any plugins. It just removes the reference to the database.
Definition at line 1666 of file Fl_Preferences.cxx.
Member Function Documentation
Fl_Preferences::ID Fl_Plugin_Manager::addPlugin (const char * name, Fl_Plugin * plugin)
This function adds a new plugin to the database.
There is no need to call this function explicitly. Every Fl_Plugin constructor will call this function at initialization time.
Definition at line 1743 of file Fl_Preferences.cxx.
References Fl_Preferences::id(), and Fl_Preferences::set().
Referenced by Fl_Plugin::Fl_Plugin().
int Fl_Plugin_Manager::load (const char * filename) [static]
Load a module from disk.
A module must be a dynamically linkable file for the given operating system. When loading a module, its +init function will be called which in turn calls the constructor of all statically initialized Fl_Plugin classes and adds them to the database.
Definition at line 1772 of file Fl_Preferences.cxx.
Referenced by loadAll().
int Fl_Plugin_Manager::loadAll (const char * filepath, const char * pattern = 0) [static]
Use this function to load a whole directory full of modules.
Definition at line 1787 of file Fl_Preferences.cxx.
References dirent, fl_filename_list(), fl_filename_match(), i, and load().
Fl_Plugin * Fl_Plugin_Manager::plugin (int index)
Return the address of a plugin by index.
Definition at line 1703 of file Fl_Preferences.cxx.
References Fl_Preferences::get().
Referenced by main(), and Fl_Paged_Device::print_widget().
Fl_Plugin * Fl_Plugin_Manager::plugin (const char * name)
Return the address of a plugin by name.
Definition at line 1718 of file Fl_Preferences.cxx.
References Fl_Preferences::get(), and Fl_Preferences::groupExists().
int Fl_Plugin_Manager::plugins () [inline]
Return the number of plugins in the klass.
Definition at line 91 of file Fl_Plugin.H.
References Fl_Preferences::groups().
Referenced by main().
void Fl_Plugin_Manager::removePlugin (Fl_Preferences::ID id) [static]
Remove any plugin.
There is no need to call this function explicitly. Every Fl_Plugin destructor will call this function at destruction time.
Definition at line 1760 of file Fl_Preferences.cxx.
References Fl_Preferences::remove().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Plugin.H
fltk-1.3.0rc3/src/Fl_Preferences.cxx