SfR Fresh Dox - fltk: Fl_Progress Class Reference
Fl_Progress Class Reference
#include <Fl_Progress.H>
Public Member Functions
Fl_Progress (int x, int y, int w, int h, const char *l=0)
void maximum (float v)
float maximum () const
void minimum (float v)
float minimum () const
void value (float v)
float value () const
Protected Member Functions
virtual void draw ()
Detailed Description
Displays a progress bar for the user.
Definition at line 47 of file Fl_Progress.H.
Constructor & Destructor Documentation
Fl_Progress::Fl_Progress (int X, int Y, int W, int H, const char * L = 0)
The constructor creates the progress bar using the position, size, and label.
You can set the background color with color() and the progress bar color with selection_color(), or you can set both colors together with color(unsigned bg, unsigned sel).
The default colors are FL_BACKGROUND2_COLOR and FL_YELLOW, resp.
Definition at line 110 of file Fl_Progress.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::color(), f, FL_ALIGN_INSIDE, FL_BACKGROUND2_COLOR, FL_DOWN_BOX, FL_YELLOW, maximum(), minimum(), and value().
Member Function Documentation
void Fl_Progress::draw (void) [protected, virtual]
Draws the progress bar.
Implements Fl_Widget.
Definition at line 54 of file Fl_Progress.cxx.
References Fl_Widget::active_r(), Fl_Widget::box(), Fl::box_dh(), Fl::box_dw(), Fl::box_dx(), Fl::box_dy(), Fl_Widget::color(), Fl_Widget::draw_box(), Fl_Widget::draw_label(), fl_contrast(), fl_inactive(), fl_pop_clip(), fl_push_clip(), Fl_Widget::h(), int, Fl_Widget::labelcolor(), Fl_Widget::selection_color(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
void Fl_Progress::maximum (float v) [inline]
Sets the maximum value in the progress widget.
Definition at line 62 of file Fl_Progress.H.
References Fl_Widget::redraw().
Referenced by print_cb().
float Fl_Progress::maximum () const [inline]
Gets the maximum value in the progress widget.
Definition at line 64 of file Fl_Progress.H.
Referenced by Fl_Progress().
float Fl_Progress::minimum () const [inline]
Gets the minimum value in the progress widget.
Definition at line 69 of file Fl_Progress.H.
Referenced by Fl_Progress().
void Fl_Progress::minimum (float v) [inline]
Sets the minimum value in the progress widget.
Definition at line 67 of file Fl_Progress.H.
References Fl_Widget::redraw().
Referenced by print_cb().
void Fl_Progress::value (float v) [inline]
Sets the current value in the progress widget.
Definition at line 72 of file Fl_Progress.H.
References Fl_Widget::redraw().
Referenced by print_cb(), and Fl_Progress_Type::widget().
float Fl_Progress::value () const [inline]
Gets the current value in the progress widget.
Definition at line 74 of file Fl_Progress.H.
Referenced by Fl_Progress().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Progress.H
fltk-1.3.0rc3/src/Fl_Progress.cxx