SfR Fresh Dox - fltk: Fl_Submenu_Type Class Reference
Fl_Submenu_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Menu_Item * subtypes ()
const char * type_name ()
const char * alt_type_name ()
int is_parent () const
int is_button () const
Fl_Type * make ()
void add_child (Fl_Type *a, Fl_Type *b)
void move_child (Fl_Type *a, Fl_Type *b)
void remove_child (Fl_Type *a)
int pixmapID ()
Detailed Description
Definition at line 649 of file Fl_Type.h.
Member Function Documentation
void Fl_Submenu_Type::add_child (Fl_Type * a, Fl_Type * b) [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 659 of file Fl_Type.h.
References Fl_Type::add_child(), and Fl_Type::parent.
const char* Fl_Submenu_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Menu_Item_Type.
Definition at line 653 of file Fl_Type.h.
int Fl_Submenu_Type::is_button () const [inline, virtual]
Reimplemented from Fl_Menu_Item_Type.
Definition at line 655 of file Fl_Type.h.
int Fl_Submenu_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 654 of file Fl_Type.h.
Fl_Type * Fl_Submenu_Type::make () [virtual]
Reimplemented from Fl_Menu_Item_Type.
Definition at line 135 of file Fl_Menu_Type.cxx.
void Fl_Submenu_Type::move_child (Fl_Type * a, Fl_Type * b) [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 660 of file Fl_Type.h.
References Fl_Type::move_child(), and Fl_Type::parent.
int Fl_Submenu_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Menu_Item_Type.
Definition at line 662 of file Fl_Type.h.
void Fl_Submenu_Type::remove_child (Fl_Type * a) [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 661 of file Fl_Type.h.
References Fl_Type::parent, and Fl_Type::remove_child().
Fl_Menu_Item* Fl_Submenu_Type::subtypes () [inline, virtual]
Reimplemented from Fl_Menu_Item_Type.
Definition at line 651 of file Fl_Type.h.
const char* Fl_Submenu_Type::type_name () [inline, virtual]
Reimplemented from Fl_Menu_Item_Type.
Definition at line 652 of file Fl_Type.h.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Menu_Type.cxx