SfR Fresh Dox - fltk: Fl_FormsBitmap Class Reference
Fl_FormsBitmap Class Reference
#include <Fl_FormsBitmap.H>
Public Member Functions
Fl_FormsBitmap (Fl_Boxtype, int, int, int, int, const char *=0)
void set (int W, int H, const uchar *bits)
void bitmap (Fl_Bitmap *B)
Fl_Bitmap * bitmap () const
Protected Member Functions
void draw ()
Detailed Description
Forms compatibility Bitmap Image Widget
Definition at line 39 of file Fl_FormsBitmap.H.
Constructor & Destructor Documentation
Fl_FormsBitmap::Fl_FormsBitmap (Fl_Boxtype t, int X, int Y, int W, int H, const char * l = 0)
Creates a bitmap widget from a box type, position, size and optional label specification
Definition at line 30 of file forms_bitmap.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::color(), FL_ALIGN_BOTTOM, and FL_BLACK.
Member Function Documentation
void Fl_FormsBitmap::bitmap (Fl_Bitmap * B) [inline]
Sets a new bitmap.
Definition at line 48 of file Fl_FormsBitmap.H.
Fl_Bitmap* Fl_FormsBitmap::bitmap () const [inline]
Gets a the current associated Fl_Bitmap objects.
Definition at line 50 of file Fl_FormsBitmap.H.
Referenced by set().
void Fl_FormsBitmap::draw (void) [protected, virtual]
Draws the bitmap and its associated box.
Implements Fl_Widget.
Definition at line 45 of file forms_bitmap.cxx.
References Fl_Widget::box(), Fl_Widget::color(), draw(), Fl_Widget::draw_box(), Fl_Widget::draw_label(), fl_color(), Fl_Widget::h(), Fl_Widget::selection_color(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by draw().
void Fl_FormsBitmap::set (int W, int H, const uchar * bits)
Sets a new bitmap bits with size W,H. Deletes the previous one.
Definition at line 39 of file forms_bitmap.cxx.
References bitmap().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_FormsBitmap.H
fltk-1.3.0rc3/src/forms_bitmap.cxx