SfR Fresh Dox - fltk: Fl_Function_Type Class Reference
Fl_Function_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Function_Type ()
~Fl_Function_Type ()
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void open ()
int ismain ()
virtual const char * type_name ()
virtual const char * title ()
int is_parent () const
int is_code_block () const
virtual int is_public () const
int pixmapID ()
void write_properties ()
void read_property (const char *)
int has_signature (const char *, const char *) const
Detailed Description
Definition at line 165 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_Function_Type::Fl_Function_Type () [inline]
Definition at line 169 of file Fl_Type.h.
Fl_Function_Type::~Fl_Function_Type () [inline]
Definition at line 173 of file Fl_Type.h.
Member Function Documentation
int Fl_Function_Type::has_signature (const char * rtype, const char * sig) const
Definition at line 419 of file Fl_Function_Type.cxx.
References fl_filename_match(), and Fl_Type::name().
Referenced by Fl_Class_Type::has_function(), and has_toplevel_function().
int Fl_Function_Type::is_code_block () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 186 of file Fl_Type.h.
int Fl_Function_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 185 of file Fl_Type.h.
int Fl_Function_Type::is_public () const [virtual]
Reimplemented from Fl_Type.
Definition at line 127 of file Fl_Function_Type.cxx.
int Fl_Function_Type::ismain () [inline]
Definition at line 180 of file Fl_Type.h.
References Fl_Type::name_.
Referenced by write_code1(), and write_code2().
Fl_Type * Fl_Function_Type::make () [virtual]
Implements Fl_Type.
Definition at line 129 of file Fl_Function_Type.cxx.
References Fl_Type::current, Fl_Type::is_decl_block(), Fl_Type::name(), and Fl_Type::parent.
void Fl_Function_Type::open () [virtual]
Reimplemented from Fl_Type.
Definition at line 172 of file Fl_Function_Type.cxx.
References Fl_Text_Display::buffer(), c_check(), Fl_Type::comment(), f_c_button, f_comment_input, f_name_input, f_panel_cancel, f_panel_ok, f_public_choice, f_public_member_choice, f_return_type_input, fl_alert(), function_panel, Fl_Double_Window::hide(), Fl_Widget::hide(), Fl_Type::is_in_class(), make_function_panel(), Fl_Type::name(), Fl::readqueue(), redraw_browser(), set_modflag(), Fl_Double_Window::show(), Fl_Widget::show(), Fl_Input_::static_value(), storestring(), Fl_Input_::value(), Fl_Button::value(), Fl_Choice::value(), w, and Fl::wait().
int Fl_Function_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 188 of file Fl_Type.h.
void Fl_Function_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Type.
Definition at line 155 of file Fl_Function_Type.cxx.
References read_word(), and storestring().
virtual const char* Fl_Function_Type::title () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 182 of file Fl_Type.h.
References Fl_Type::name().
virtual const char* Fl_Function_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 181 of file Fl_Type.h.
void Fl_Function_Type::write_code1 () [virtual]
Reimplemented from Fl_Type.
Definition at line 248 of file Fl_Function_Type.cxx.
References Fl_Type::class_name(), indentation, Fl_Type::is_widget(), ismain(), Fl_Type::level, Fl_Type::name(), Fl_Type::next, subclassname(), write_c(), Fl_Type::write_comment_c(), write_h(), and write_public().
void Fl_Function_Type::write_code2 () [virtual]
Reimplemented from Fl_Type.
Definition at line 399 of file Fl_Function_Type.cxx.
References indentation, Fl_Type::is_window(), ismain(), Fl_Type::level, Fl_Type::name(), Fl_Type::next, and write_c().
void Fl_Function_Type::write_properties () [virtual]
Reimplemented from Fl_Type.
Definition at line 142 of file Fl_Function_Type.cxx.
References write_string(), and write_word().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx