SfR Fresh Dox - fltk: Fl_Browser_Type Class Reference
Fl_Browser_Type Class Reference
Public Member Functions
virtual void ideal_size (int &w, int &h)
virtual const char * type_name ()
virtual const char * alt_type_name ()
Fl_Widget * widget (int x, int y, int w, int h)
Fl_Widget_Type * _make ()
int pixmapID ()
Detailed Description
Definition at line 217 of file factory.cxx.
Member Function Documentation
Fl_Widget_Type* Fl_Browser_Type::_make () [inline, virtual]
Implements Fl_Widget_Type.
Definition at line 248 of file factory.cxx.
virtual const char* Fl_Browser_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 234 of file factory.cxx.
virtual void Fl_Browser_Type::ideal_size (int & w, int & h) [inline, virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 221 of file factory.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dw(), fl_font(), fl_height(), fl_width(), int, Fl_Widget_Type::o, Fl_Browser_::textfont(), and Fl_Browser_::textsize().
int Fl_Browser_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 249 of file factory.cxx.
virtual const char* Fl_Browser_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 233 of file factory.cxx.
Fl_Widget* Fl_Browser_Type::widget (int x, int y, int w, int h) [inline, virtual]
Implements Fl_Widget_Type.
Definition at line 235 of file factory.cxx.
References Fl_Browser::add(), b, buffer, and i.
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/fluid/factory.cxx