SfR Fresh Dox - fltk: Fl_Group_Type Class Reference
Fl_Group_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
virtual const char * type_name ()
virtual const char * alt_type_name ()
Fl_Widget * widget (int X, int Y, int W, int H)
Fl_Widget_Type * _make ()
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void add_child (Fl_Type *, Fl_Type *)
void move_child (Fl_Type *, Fl_Type *)
void remove_child (Fl_Type *)
int is_parent () const
int is_group () const
int pixmapID ()
virtual Fl_Widget * enter_live_mode (int top=0)
virtual void leave_live_mode ()
virtual void copy_properties ()
Detailed Description
Definition at line 433 of file Fl_Type.h.
Member Function Documentation
Fl_Widget_Type* Fl_Group_Type::_make () [inline, virtual]
Implements Fl_Widget_Type.
Reimplemented in Fl_Pack_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, Fl_Tile_Type, and Fl_Wizard_Type.
Definition at line 439 of file Fl_Type.h.
void Fl_Group_Type::add_child (Fl_Type * cc, Fl_Type * before) [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Table_Type, and Fl_Tabs_Type.
Definition at line 279 of file Fl_Group_Type.cxx.
References b, Fl_Type::insert(), Fl_Widget_Type::o, and Fl_Widget::redraw().
virtual const char* Fl_Group_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Pack_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, Fl_Tile_Type, and Fl_Wizard_Type.
Definition at line 436 of file Fl_Type.h.
void Fl_Group_Type::copy_properties () [virtual]
copy all properties from the edit widget to the live widget
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Pack_Type, Fl_Scroll_Type, and Fl_Tile_Type.
Definition at line 392 of file Fl_Group_Type.cxx.
Referenced by Fl_Table_Type::enter_live_mode(), Fl_Tabs_Type::enter_live_mode(), and enter_live_mode().
Fl_Widget * Fl_Group_Type::enter_live_mode (int top = 0) [virtual]
Build widgets and dataset needed in live mode.
Returns:
a widget pointer that the live mode initiator can 'show()'
See also:
leave_live_mode()
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Table_Type, Fl_Tabs_Type, and Fl_Scroll_Type.
Definition at line 345 of file Fl_Group_Type.cxx.
References copy_properties(), Fl_Group::end(), Fl_Type::enter_live_mode(), Fl_Widget::h(), Fl_Type::level, Fl_Widget_Type::live_widget, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
int Fl_Group_Type::is_group () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 447 of file Fl_Type.h.
int Fl_Group_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 446 of file Fl_Type.h.
void Fl_Group_Type::leave_live_mode () [virtual]
Release all resources created when enetring live mode.
See also:
enter_live_mode()
Reimplemented from Fl_Widget_Type.
Definition at line 386 of file Fl_Group_Type.cxx.
Fl_Type * Fl_Group_Type::make () [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 48 of file Fl_Group_Type.cxx.
Referenced by group_cb().
void Fl_Group_Type::move_child (Fl_Type * cc, Fl_Type * before) [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Table_Type.
Definition at line 326 of file Fl_Group_Type.cxx.
References b, Fl_Type::insert(), Fl_Widget_Type::o, Fl_Widget::redraw(), and Fl_Type::remove().
int Fl_Group_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Pack_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, Fl_Tile_Type, and Fl_Wizard_Type.
Definition at line 448 of file Fl_Type.h.
void Fl_Group_Type::remove_child (Fl_Type * cc) [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Table_Type, and Fl_Tabs_Type.
Definition at line 305 of file Fl_Group_Type.cxx.
References Fl_Widget_Type::o, and Fl_Type::remove().
virtual const char* Fl_Group_Type::type_name () [inline, virtual]
Implements Fl_Type.
Reimplemented in Fl_Pack_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, Fl_Tile_Type, and Fl_Wizard_Type.
Definition at line 435 of file Fl_Type.h.
Fl_Widget* Fl_Group_Type::widget (int X, int Y, int W, int H) [inline, virtual]
Implements Fl_Widget_Type.
Reimplemented in Fl_Table_Type, Fl_Tabs_Type, and Fl_Wizard_Type.
Definition at line 437 of file Fl_Type.h.
References Fl_Type::current.
void Fl_Group_Type::write_code1 () [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 123 of file Fl_Group_Type.cxx.
void Fl_Group_Type::write_code2 () [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 127 of file Fl_Group_Type.cxx.
References indent(), Fl_Type::name(), Fl_Widget_Type::resizable(), Fl_Widget_Type::write_block_close(), write_c(), and Fl_Widget_Type::write_extra_code().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Group_Type.cxx