SfR Fresh Dox - fltk: Fl_Input_Choice_Type Class Reference
Fl_Input_Choice_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
virtual void ideal_size (int &w, int &h)
virtual const char * type_name ()
virtual const char * alt_type_name ()
virtual Fl_Type * click_test (int, int)
Fl_Widget * widget (int X, int Y, int W, int H)
Fl_Widget_Type * _make ()
virtual void build_menu ()
int pixmapID ()
void copy_properties ()
Detailed Description
Definition at line 745 of file Fl_Type.h.
Member Function Documentation
Fl_Widget_Type* Fl_Input_Choice_Type::_make () [inline, virtual]
Implements Fl_Widget_Type.
Definition at line 777 of file Fl_Type.h.
virtual const char* Fl_Input_Choice_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 769 of file Fl_Type.h.
void Fl_Input_Choice_Type::build_menu () [virtual]
Reimplemented from Fl_Menu_Type.
Definition at line 62 of file Fl_Menu_Type.cxx.
References Fl_Menu_Item::callback(), FL_SUBMENU, Fl_Menu_Item::flags, i, Fl_Widget::image(), Fl_Type::is_menu_item(), Fl_Type::is_parent(), Fl_Widget::label(), Fl_Menu_Item::label(), Fl_Image::label(), Fl_Menu_Item::labelcolor(), Fl_Menu_Item::labelfont(), Fl_Menu_Item::labelsize(), Fl_Widget::labeltype(), Fl_Menu_Item::labeltype(), Fl_Type::level, m, Fl_Input_Choice::menu(), Fl_Menu_Type::menusize, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::redraw(), Fl_Menu_Item::shortcut(), and w.
Referenced by click_test().
Fl_Type * Fl_Input_Choice_Type::click_test (int , int) [virtual]
Reimplemented from Fl_Menu_Type.
Definition at line 541 of file Fl_Menu_Type.cxx.
References build_menu(), FL_MENU_RADIO, FL_MENU_TOGGLE, FL_PUSH, Fl_Menu_Item::flags, Fl_Widget::handle(), m, Fl_Menu_Type::menusize, Fl_Menu_::mvalue(), Fl_Widget_Type::o, Fl::pushed(), Fl_Type::selected, Fl_Menu_Item::user_data(), Fl_Menu_::value(), and w.
void Fl_Input_Choice_Type::copy_properties () [virtual]
copy all properties from the edit widget to the live widget
Reimplemented from Fl_Menu_Type.
Definition at line 531 of file Fl_Menu_Type.cxx.
References Fl_Input_Choice::down_box(), Fl_Widget_Type::live_widget, Fl_Input_Choice::menu(), Fl_Widget_Type::o, Fl_Input_Choice::textcolor(), Fl_Input_Choice::textfont(), and Fl_Input_Choice::textsize().
virtual void Fl_Input_Choice_Type::ideal_size (int & w, int & h) [inline, virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 758 of file Fl_Type.h.
References Fl_Widget::box(), Fl::box_dw(), fl_font(), fl_height(), fl_width(), int, Fl_Widget_Type::o, Fl_Input_Choice::textfont(), Fl_Input_Choice::textsize(), and Fl_Widget::w().
int Fl_Input_Choice_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 779 of file Fl_Type.h.
virtual const char* Fl_Input_Choice_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 768 of file Fl_Type.h.
Fl_Widget* Fl_Input_Choice_Type::widget (int X, int Y, int W, int H) [inline, virtual]
Implements Fl_Widget_Type.
Definition at line 771 of file Fl_Type.h.
References Fl_Input_Choice::menu(), and Fl_Input_Choice::value().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Menu_Type.cxx