SfR Fresh Dox - fltk: Fl_Help_Dialog Class Reference
Fl_Help_Dialog Class Reference
#include <Fl_Help_Dialog.H>
Public Member Functions
Fl_Help_Dialog ()
~Fl_Help_Dialog ()
int h ()
void hide ()
void load (const char *f)
void position (int xx, int yy)
void resize (int xx, int yy, int ww, int hh)
void show ()
void show (int argc, char **argv)
void textsize (Fl_Fontsize s)
Fl_Fontsize textsize ()
void topline (const char *n)
void topline (int n)
void value (const char *f)
const char * value () const
int visible ()
int w ()
int x ()
int y ()
Detailed Description
The Fl_Help_Dialog widget displays a standard help dialog window using the Fl_Help_View widget.
Definition at line 43 of file Fl_Help_Dialog.H.
Constructor & Destructor Documentation
Fl_Help_Dialog::Fl_Help_Dialog ()
The constructor creates the dialog pictured above.
Definition at line 149 of file Fl_Help_Dialog.cxx.
References Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Group::current(), Fl_Widget::deactivate(), Fl_Group::end(), FL_BACKGROUND2_COLOR, FL_DOWN_BOX, FL_FLAT_BOX, fl_register_images(), FL_WHEN_ENTER_KEY_ALWAYS, Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Group::resizable(), Fl_Button::shortcut(), Fl_Window::size_range(), Fl_Input_::textfont(), Fl_Widget::tooltip(), Fl_Widget::user_data(), and Fl_Widget::when().
Fl_Help_Dialog::~Fl_Help_Dialog ()
The destructor destroys the widget and frees all memory that has been allocated for the current file.
Definition at line 213 of file Fl_Help_Dialog.cxx.
Member Function Documentation
int Fl_Help_Dialog::h ()
Returns the position and size of the help dialog.
Definition at line 217 of file Fl_Help_Dialog.cxx.
References Fl_Widget::h().
void Fl_Help_Dialog::hide ()
Hides the Fl_Help_Dialog window.
Definition at line 221 of file Fl_Help_Dialog.cxx.
References Fl_Double_Window::hide().
void Fl_Help_Dialog::load (const char * f)
Loads the specified HTML file into the Fl_Help_View widget. The filename can also contain a target name ("filename.html#target").
Definition at line 225 of file Fl_Help_Dialog.cxx.
References Fl_Window::label(), Fl_Help_View::load(), Fl_Widget::set_changed(), and Fl_Help_View::title().
Referenced by show_help().
void Fl_Help_Dialog::position (int x, int y)
Set the screen position of the dialog.
Definition at line 231 of file Fl_Help_Dialog.cxx.
References Fl_Widget::position().
void Fl_Help_Dialog::resize (int xx, int yy, int ww, int hh)
Change the position and size of the dialog.
Definition at line 235 of file Fl_Help_Dialog.cxx.
References Fl_Double_Window::resize().
void Fl_Help_Dialog::show ()
Shows the Fl_Help_Dialog window.
Shows the main Help Dialog Window Delegates call to encapsulated window_ void Fl_Window::show() method
Definition at line 239 of file Fl_Help_Dialog.cxx.
References Fl_Double_Window::show().
Referenced by show_help().
void Fl_Help_Dialog::show (int argc, char ** argv)
Shows the main Help Dialog Window Delegates call to encapsulated window_ void Fl_Window::show(int argc, char **argv) instance method
Definition at line 243 of file Fl_Help_Dialog.cxx.
References Fl_Double_Window::show().
void Fl_Help_Dialog::textsize (Fl_Fontsize s)
Sets or gets the default text size for the help view.
Sets the internal Fl_Help_View instance text size. Delegates call to encapsulated view_ void Fl_Help_View::textsize(Fl_Fontsize s) instance method
Definition at line 247 of file Fl_Help_Dialog.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), and Fl_Help_View::textsize().
uchar Fl_Help_Dialog::textsize ()
Sets or gets the default text size for the help view.
Definition at line 261 of file Fl_Help_Dialog.cxx.
References Fl_Help_View::textsize().
void Fl_Help_Dialog::topline (int n)
Sets the top line in the Fl_Help_View widget to the named or numbered line.
Definition at line 269 of file Fl_Help_Dialog.cxx.
References Fl_Help_View::topline().
void Fl_Help_Dialog::topline (const char * n)
Sets the top line in the Fl_Help_View widget to the named or numbered line.
Definition at line 265 of file Fl_Help_Dialog.cxx.
References Fl_Help_View::topline().
const char * Fl_Help_Dialog::value () const
The first form sets the current buffer to the string provided and reformats the text. It also clears the history of the "back" and "forward" buttons. The second form returns the current buffer contents.
Definition at line 279 of file Fl_Help_Dialog.cxx.
References Fl_Help_View::value().
void Fl_Help_Dialog::value (const char * v)
The first form sets the current buffer to the string provided and reformats the text. It also clears the history of the "back" and "forward" buttons. The second form returns the current buffer contents.
Definition at line 273 of file Fl_Help_Dialog.cxx.
References Fl_Window::label(), Fl_Widget::set_changed(), Fl_Help_View::title(), and Fl_Help_View::value().
int Fl_Help_Dialog::visible ()
Returns 1 if the Fl_Help_Dialog window is visible.
Definition at line 283 of file Fl_Help_Dialog.cxx.
References Fl_Widget::visible().
int Fl_Help_Dialog::w ()
Returns the position and size of the help dialog.
Definition at line 287 of file Fl_Help_Dialog.cxx.
References Fl_Widget::w().
int Fl_Help_Dialog::x ()
Returns the position and size of the help dialog.
Definition at line 291 of file Fl_Help_Dialog.cxx.
References Fl_Widget::x().
int Fl_Help_Dialog::y ()
Returns the position and size of the help dialog.
Definition at line 295 of file Fl_Help_Dialog.cxx.
References Fl_Widget::y().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Help_Dialog.H
fltk-1.3.0rc3/src/Fl_Help_Dialog.cxx
fltk-1.3.0rc3/src/Fl_Help_Dialog_Dox.cxx