SfR Fresh Dox - fltk: Fl_Menu_Bar Class Reference
Fl_Menu_Bar Class Reference
#include <Fl_Menu_Bar.H>
Public Member Functions
int handle (int)
Fl_Menu_Bar (int X, int Y, int W, int H, const char *l=0)
Protected Member Functions
void draw ()
Detailed Description
This widget provides a standard menubar interface. Usually you will put this widget along the top edge of your window. The height of the widget should be 30 for the menu titles to draw correctly with the default font.
The items on the bar and the menus they bring up are defined by a single Fl_Menu_Item array. Because a Fl_Menu_Item array defines a hierarchy, the top level menu defines the items in the menubar, while the submenus define the pull-down menus. Sub-sub menus and lower pop up to the right of the submenus.
If there is an item in the top menu that is not a title of a submenu, then it acts like a "button" in the menubar. Clicking on it will pick it.
When the user picks an item off the menu, the item's callback is done with the menubar as the Fl_Widget* argument. If the item does not have a callback the menubar's callback is done instead.
Submenus will also pop up in response to shortcuts indicated by putting a '&' character in the name field of the menu item. If you put a '&' character in a top-level "button" then the shortcut picks it. The '&' character in submenus is ignored until the menu is popped up.
Typing the shortcut() of any of the menu items will cause callbacks exactly the same as when you pick the item with the mouse.
Definition at line 62 of file Fl_Menu_Bar.H.
Constructor & Destructor Documentation
Fl_Menu_Bar::Fl_Menu_Bar (int X, int Y, int W, int H, const char * l = 0) [inline]
Creates a new Fl_Menu_Bar widget using the given position, size, and label string. The default boxtype is FL_UP_BOX.
The constructor sets menu() to NULL. See Fl_Menu_ for the methods to set or change the menu.
labelsize(), labelfont(), and labelcolor() are used to control how the menubar items are drawn. They are initialized from the Fl_Menu static variables, but you can change them if desired.
label() is ignored unless you change align() to put it outside the menubar.
The destructor removes the Fl_Menu_Bar widget and all of its menu items.
Definition at line 81 of file Fl_Menu_Bar.H.
Member Function Documentation
void Fl_Menu_Bar::draw () [protected, virtual]
Draws the widget. Never call this function directly. FLTK will schedule redrawing whenever needed. If your widget must be redrawn as soon as possible, call redraw() instead.
Override this function to draw your own widgets.
If you ever need to call another widget's draw method from within your own draw() method, e.g. for an embedded scrollbar, you can do it (because draw() is virtual) like this:
        Fl_Widget *s = &scroll;         // scroll is an embedded Fl_Scrollbar
        s->draw();                      // calls Fl_Scrollbar::draw()
Implements Fl_Widget.
Definition at line 32 of file Fl_Menu_Bar.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dy(), Fl_Menu_Item::draw(), Fl_Widget::draw_box(), fl_color(), FL_DARK3, FL_LIGHT3, FL_MENU_DIVIDER, fl_yxline(), Fl_Menu_Item::flags, Fl_Widget::h(), m, Fl_Menu_Item::measure(), Fl_Menu_::menu(), Fl_Menu_Item::next(), Fl_Menu_Item::text, Fl_Menu_::text(), Fl_Widget::x(), and Fl_Widget::y().
int Fl_Menu_Bar::handle (int event) [virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Widget.
Definition at line 54 of file Fl_Menu_Bar.cxx.
References Fl_Menu_Item::find_shortcut(), FL_ENTER, FL_LEAVE, FL_PUSH, FL_SHORTCUT, Fl_Widget::h(), Fl_Menu_::menu(), Fl_Menu_::picked(), Fl_Menu_Item::pulldown(), Fl_Menu_Item::submenu(), Fl_Menu_::test_shortcut(), Fl_Menu_::text(), Fl_Widget::visible_r(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Menu_Bar.H
fltk-1.3.0rc3/src/Fl_Menu_Bar.cxx