SfR Fresh Dox - fltk: Fl_Wizard Class Reference
Fl_Wizard Class Reference
#include <Fl_Wizard.H>
Public Member Functions
Fl_Wizard (int, int, int, int, const char *=0)
void next ()
void prev ()
Fl_Widget * value ()
void value (Fl_Widget *)
Detailed Description
This widget is based off the Fl_Tabs widget, but instead of displaying tabs it only changes "tabs" under program control. Its primary purpose is to support "wizards" that step a user through configuration or troubleshooting tasks.
As with Fl_Tabs, wizard panes are composed of child (usually Fl_Group) widgets. Navigation buttons must be added separately.
Definition at line 50 of file Fl_Wizard.H.
Constructor & Destructor Documentation
Fl_Wizard::Fl_Wizard (int xx, int yy, int ww, int hh, const char * l = 0)
The constructor creates the Fl_Wizard widget at the specified position and size.
The inherited destructor destroys the widget and its children.
Definition at line 56 of file Fl_Wizard.cxx.
References Fl_Widget::box(), and FL_THIN_UP_BOX.
Member Function Documentation
void Fl_Wizard::next ()
This method shows the next child of the wizard. If the last child is already visible, this function does nothing.
Definition at line 98 of file Fl_Wizard.cxx.
References Fl_Group::array(), Fl_Group::children(), and value().
void Fl_Wizard::prev ()
Shows the previous child.
Definition at line 115 of file Fl_Wizard.cxx.
References Fl_Group::array(), Fl_Group::children(), and value().
Fl_Widget * Fl_Wizard::value ()
Gets the current visible child widget.
Definition at line 133 of file Fl_Wizard.cxx.
References Fl_Group::array(), Fl_Group::children(), Fl_Widget::hide(), and Fl_Widget::show().
Referenced by next(), and prev().
void Fl_Wizard::value (Fl_Widget * kid)
Sets the child widget that is visible.
Definition at line 165 of file Fl_Wizard.cxx.
References Fl_Group::array(), Fl_Group::children(), Fl_Window::cursor(), FL_CURSOR_DEFAULT, Fl_Widget::show(), Fl_Widget::visible(), and Fl_Widget::window().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Wizard.H
fltk-1.3.0rc3/src/Fl_Wizard.cxx