SfR Fresh Dox - fltk: FLEnum Class Reference
FLEnum Class Reference
Public Member Functions
ULONG __stdcall AddRef (void)
ULONG __stdcall Release (void)
HRESULT __stdcall QueryInterface (REFIID iid, void **ppvObject)
HRESULT __stdcall Next (ULONG celt, FORMATETC *rgelt, ULONG *pceltFetched)
HRESULT __stdcall Skip (ULONG celt)
HRESULT __stdcall Reset (void)
HRESULT __stdcall Clone (IEnumFORMATETC **ppenum)
FLEnum (void)
virtual ~FLEnum (void)
Public Attributes
int n
LONG m_lRefCount
Detailed Description
Definition at line 352 of file fl_dnd_win32.cxx.
Constructor & Destructor Documentation
FLEnum::FLEnum (void) [inline]
Definition at line 413 of file fl_dnd_win32.cxx.
References m_lRefCount, and n.
Referenced by Clone().
virtual FLEnum::~FLEnum (void) [inline, virtual]
Definition at line 418 of file fl_dnd_win32.cxx.
References n.
Member Function Documentation
ULONG __stdcall FLEnum::AddRef (void) [inline]
Definition at line 358 of file fl_dnd_win32.cxx.
References m_lRefCount.
Referenced by QueryInterface().
HRESULT __stdcall FLEnum::Clone (IEnumFORMATETC ** ppenum) [inline]
Definition at line 408 of file fl_dnd_win32.cxx.
References FLEnum().
HRESULT __stdcall FLEnum::Next (ULONG celt, FORMATETC * rgelt, ULONG * pceltFetched) [inline]
Definition at line 384 of file fl_dnd_win32.cxx.
References n, and NULL.
HRESULT __stdcall FLEnum::QueryInterface (REFIID iid, void ** ppvObject) [inline]
Definition at line 373 of file fl_dnd_win32.cxx.
References AddRef().
ULONG __stdcall FLEnum::Release (void) [inline]
Definition at line 362 of file fl_dnd_win32.cxx.
References m_lRefCount.
HRESULT __stdcall FLEnum::Reset (void) [inline]
Definition at line 403 of file fl_dnd_win32.cxx.
References n.
HRESULT __stdcall FLEnum::Skip (ULONG celt) [inline]
Definition at line 398 of file fl_dnd_win32.cxx.
References n.
Member Data Documentation
LONG FLEnum::m_lRefCount
Definition at line 356 of file fl_dnd_win32.cxx.
Referenced by AddRef(), FLEnum(), and Release().
int FLEnum::n
Definition at line 355 of file fl_dnd_win32.cxx.
Referenced by FLEnum(), Next(), Reset(), Skip(), and ~FLEnum().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/src/fl_dnd_win32.cxx