SfR Fresh Dox - fltk: Fl_Widget_Class_Type Class Reference
Fl_Widget_Class_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Widget_Class_Type ()
virtual void write_properties ()
virtual void read_property (const char *)
void write_code1 ()
void write_code2 ()
Fl_Type * make ()
virtual const char * type_name ()
int pixmapID ()
int is_parent () const
int is_code_block () const
int is_decl_block () const
int is_class () const
Public Attributes
char write_public_state
char wc_relative
Detailed Description
Definition at line 603 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_Widget_Class_Type::Fl_Widget_Class_Type () [inline]
Definition at line 605 of file Fl_Type.h.
References wc_relative, and write_public_state.
Member Function Documentation
int Fl_Widget_Class_Type::is_class () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 624 of file Fl_Type.h.
int Fl_Widget_Class_Type::is_code_block () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 622 of file Fl_Type.h.
int Fl_Widget_Class_Type::is_decl_block () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 623 of file Fl_Type.h.
int Fl_Widget_Class_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Window_Type.
Definition at line 621 of file Fl_Type.h.
Fl_Type * Fl_Widget_Class_Type::make () [virtual]
Reimplemented from Fl_Window_Type.
Definition at line 1446 of file Fl_Window_Type.cxx.
References Fl_Type::current, gridx, gridy, Fl_Type::is_class(), Fl_Type::is_decl_block(), Fl_Type::is_widget(), Fl_Type::name(), Fl_Widget_Type::o, Fl_Window_Type::Overlay_Window, Fl_Type::parent, w, and Overlay_Window::window.
int Fl_Widget_Class_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Window_Type.
Definition at line 620 of file Fl_Type.h.
void Fl_Widget_Class_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Window_Type.
Definition at line 1480 of file Fl_Window_Type.cxx.
References wc_relative.
virtual const char* Fl_Widget_Class_Type::type_name () [inline, virtual]
Reimplemented from Fl_Window_Type.
Definition at line 619 of file Fl_Type.h.
void Fl_Widget_Class_Type::write_code1 () [virtual]
Reimplemented from Fl_Window_Type.
Definition at line 1488 of file Fl_Window_Type.cxx.
References Fl_Widget::h(), Fl_Type::label(), Fl_Type::name(), Fl_Widget_Type::o, Fl_Widget_Type::subclass(), Fl_Widget::w(), wc_relative, write_c(), write_cstring(), write_h(), write_public_state, and Fl_Widget_Type::write_widget_code().
void Fl_Widget_Class_Type::write_code2 () [virtual]
Reimplemented from Fl_Window_Type.
Definition at line 1549 of file Fl_Window_Type.cxx.
References indent(), Fl_Window_Type::modal, Fl_Window_Type::non_modal, Fl_Widget_Type::o, Fl_Widget_Type::resizable(), wc_relative, write_c(), write_cstring(), Fl_Widget_Type::write_extra_code(), and Fl_Widget_Type::xclass.
void Fl_Widget_Class_Type::write_properties () [virtual]
Reimplemented from Fl_Window_Type.
Definition at line 1475 of file Fl_Window_Type.cxx.
References wc_relative, and write_string().
Member Data Documentation
char Fl_Widget_Class_Type::wc_relative
Definition at line 611 of file Fl_Type.h.
Referenced by Fl_Widget_Class_Type(), read_property(), wc_relative_cb(), write_code1(), write_code2(), and write_properties().
char Fl_Widget_Class_Type::write_public_state
Definition at line 610 of file Fl_Type.h.
Referenced by Fl_Widget_Class_Type(), write_code1(), and write_public().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Window_Type.cxx