SfR Fresh Dox - fltk: Shortcut_Button Class Reference
Shortcut_Button Class Reference
#include <Shortcut_Button.h>
Public Member Functions
int handle (int)
void draw ()
Shortcut_Button (int X, int Y, int W, int H, const char *l=0)
Public Attributes
int svalue
Detailed Description
Definition at line 30 of file Shortcut_Button.h.
Constructor & Destructor Documentation
Shortcut_Button::Shortcut_Button (int X, int Y, int W, int H, const char * l = 0) [inline]
Definition at line 35 of file Shortcut_Button.h.
References svalue.
Member Function Documentation
void Shortcut_Button::draw () [virtual]
Draws the widget. Never call this function directly. FLTK will schedule redrawing whenever needed. If your widget must be redrawn as soon as possible, call redraw() instead.
Override this function to draw your own widgets.
If you ever need to call another widget's draw method from within your own draw() method, e.g. for an embedded scrollbar, you can do it (because draw() is virtual) like this:
        Fl_Widget *s = &scroll;         // scroll is an embedded Fl_Scrollbar
        s->draw();                      // calls Fl_Scrollbar::draw()
Reimplemented from Fl_Button.
Definition at line 570 of file Fl_Menu_Type.cxx.
References buf, Fl_Widget::draw_box(), FL_ALIGN_LEFT, fl_color(), FL_CTRL, FL_DOWN_BOX, fl_draw(), fl_font(), FL_FOREGROUND_COLOR, FL_HELVETICA, FL_META, fl_shortcut_label(), fl_snprintf(), FL_UP_BOX, FL_WHITE, Fl_Widget::h(), svalue, use_FL_COMMAND, Fl_Button::value(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
int Shortcut_Button::handle (int event) [virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Button.
Definition at line 583 of file Fl_Menu_Type.cxx.
References Fl_Widget::changed(), Fl_Widget::do_callback(), Fl::event_key(), Fl::event_state(), Fl::event_text(), FL_ALT, FL_BackSpace, FL_CTRL, FL_FOCUS, FL_KEYBOARD, FL_META, FL_RELEASE, FL_SHIFT, FL_TOGGLE_BUTTON, FL_UNFOCUS, Fl::focus(), Fl_Widget::redraw(), Fl_Widget::set_changed(), svalue, Fl_Widget::take_focus(), Fl_Widget::type(), Fl_Button::value(), and Fl_Widget::when().
Member Data Documentation
int Shortcut_Button::svalue
Definition at line 32 of file Shortcut_Button.h.
Referenced by draw(), handle(), Shortcut_Button(), and shortcut_in_cb().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Shortcut_Button.h
fltk-1.3.0rc3/fluid/Fl_Menu_Type.cxx