SfR Fresh Dox - fltk: Fl_Surface_Device Class Reference
Fl_Surface_Device Class Reference
A surface that's susceptible to receive graphical output.
#include <Fl_Device.H>
Public Member Functions
virtual void set_current (void)
Use this drawing surface for future graphics requests.
void driver (Fl_Graphics_Driver *graphics_driver)
Sets the graphics driver of this drawing surface.
Fl_Graphics_Driver * driver ()
Returns the graphics driver of this drawing surface.
virtual ~Fl_Surface_Device ()
The destructor.
Static Public Member Functions
static Fl_Surface_Device * surface ()
the surface that currently receives graphics output
Static Public Attributes
static const char * class_id = "Fl_Surface_Device"
A string that identifies each subclass of Fl_Device.
Protected Member Functions
Fl_Surface_Device (Fl_Graphics_Driver *graphics_driver)
Constructor that sets the graphics driver to use for the created surface.
Detailed Description
A surface that's susceptible to receive graphical output.
Definition at line 367 of file Fl_Device.H.
Constructor & Destructor Documentation
Fl_Surface_Device::Fl_Surface_Device (Fl_Graphics_Driver * graphics_driver) [inline, protected]
Constructor that sets the graphics driver to use for the created surface.
Definition at line 372 of file Fl_Device.H.
virtual Fl_Surface_Device::~Fl_Surface_Device () [inline, virtual]
The destructor.
Definition at line 383 of file Fl_Device.H.
Member Function Documentation
void Fl_Surface_Device::driver (Fl_Graphics_Driver * graphics_driver) [inline]
Sets the graphics driver of this drawing surface.
Definition at line 377 of file Fl_Device.H.
Referenced by fl_copy_offscreen(), and Fl_PostScript_Graphics_Driver::font().
Fl_Graphics_Driver* Fl_Surface_Device::driver () [inline]
Returns the graphics driver of this drawing surface.
Reimplemented in Fl_PostScript_File_Device.
Definition at line 379 of file Fl_Device.H.
void Fl_Surface_Device::set_current (void) [virtual]
Use this drawing surface for future graphics requests.
Definition at line 48 of file Fl_Device.cxx.
References fl_graphics_driver, and fl_surface.
Referenced by Fl_PostScript_File_Device::end_job(), Fl_Paged_Device::print_window_part(), Fl_PostScript_Printer::start_job(), and Fl_PostScript_File_Device::start_job().
static Fl_Surface_Device* Fl_Surface_Device::surface () [inline, static]
the surface that currently receives graphics output
Definition at line 381 of file Fl_Device.H.
References fl_surface.
Referenced by Fl_Graphics_Driver::clip_box(), Fl_Graphics_Driver::line_style(), Fl_Graphics_Driver::not_clipped(), Fl_Paged_Device::print_window_part(), and XRectangleRegion().
Member Data Documentation
const char * Fl_Surface_Device::class_id = "Fl_Surface_Device" [static]
A string that identifies each subclass of Fl_Device.
Function class_name() applied to a device of this class returns this string.
Reimplemented from Fl_Device.
Reimplemented in Fl_Display_Device, Fl_Paged_Device, Fl_PostScript_File_Device, Fl_PostScript_Printer, and Fl_Printer.
Definition at line 372 of file Fl_Device.H.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Device.H
fltk-1.3.0rc3/src/Fl_Device.cxx