SfR Fresh Dox - fltk: Fl_Display_Device Class Reference
Fl_Display_Device Class Reference
A display to which the computer can draw.
#include <Fl_Device.H>
Public Member Functions
Fl_Display_Device (Fl_Graphics_Driver *graphics_driver)
A constructor that sets the graphics driver used by the display.
Static Public Member Functions
static Fl_Display_Device * display_device ()
Returns the platform's display device.
Static Public Attributes
static const char * class_id = "Fl_Display_Device"
A string that identifies each subclass of Fl_Device.
Detailed Description
A display to which the computer can draw.
Definition at line 389 of file Fl_Device.H.
Constructor & Destructor Documentation
Fl_Display_Device::Fl_Display_Device (Fl_Graphics_Driver * graphics_driver) [inline]
A constructor that sets the graphics driver used by the display.
Definition at line 393 of file Fl_Device.H.
References Fl_Device::class_name().
Member Function Documentation
static Fl_Display_Device* Fl_Display_Device::display_device () [inline, static]
Returns the platform's display device.
Definition at line 397 of file Fl_Device.H.
References fl_display_device.
Referenced by Fl_PostScript_File_Device::end_job(), Fl_PostScript_Graphics_Driver::font(), and Fl_Paged_Device::print_window_part().
Member Data Documentation
const char * Fl_Display_Device::class_id = "Fl_Display_Device" [static]
A string that identifies each subclass of Fl_Device.
Function class_name() applied to a device of this class returns this string.
Reimplemented from Fl_Surface_Device.
Definition at line 391 of file Fl_Device.H.
Referenced by XRectangleRegion().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Device.H
fltk-1.3.0rc3/src/Fl_Device.cxx