SfR Fresh Dox - fltk: Fl_Xlib_Graphics_Driver Class Reference
Fl_Xlib_Graphics_Driver Class Reference
The Xlib-specific graphics class.
#include <Fl_Device.H>
Public Member Functions
Fl_Xlib_Graphics_Driver ()
The constructor.
void color (Fl_Color c)
see fl_color(Fl_Color c).
void color (uchar r, uchar g, uchar b)
see fl_color(uchar r, uchar g, uchar b).
void draw (const char *str, int n, int x, int y)
see fl_draw(const char *str, int n, int x, int y).
void draw (int angle, const char *str, int n, int x, int y)
see fl_draw(int angle, const char *str, int n, int x, int y).
void rtl_draw (const char *str, int n, int x, int y)
see fl_rtl_draw(const char *str, int n, int x, int y).
void font (Fl_Font face, Fl_Fontsize size)
see fl_font(Fl_Font face, Fl_Fontsize size).
void draw (Fl_Pixmap *pxm, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_Pixmap object to the device.
void draw (Fl_Bitmap *pxm, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_Bitmap object to the device.
void draw (Fl_RGB_Image *img, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_RGB_Image object to the device.
void draw_image (const uchar *buf, int X, int Y, int W, int H, int D=3, int L=0)
see fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L).
void draw_image (Fl_Draw_Image_Cb cb, void *data, int X, int Y, int W, int H, int D=3)
see fl_draw_image(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
void draw_image_mono (const uchar *buf, int X, int Y, int W, int H, int D=1, int L=0)
see fl_draw_image_mono(const uchar* buf, int X,int Y,int W,int H, int D, int L).
void draw_image_mono (Fl_Draw_Image_Cb cb, void *data, int X, int Y, int W, int H, int D=1)
see fl_draw_image_mono(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
Static Public Attributes
static const char * class_id = "Fl_Xlib_Graphics_Driver"
A string that identifies each subclass of Fl_Device.
Detailed Description
The Xlib-specific graphics class.
This class is implemented only on the Xlib platform.
Definition at line 343 of file Fl_Device.H.
Constructor & Destructor Documentation
Fl_Xlib_Graphics_Driver::Fl_Xlib_Graphics_Driver () [inline]
The constructor.
Definition at line 346 of file Fl_Device.H.
References class_id, and Fl_Device::class_name().
Member Function Documentation
void Fl_Xlib_Graphics_Driver::color (Fl_Color c) [virtual]
see fl_color(Fl_Color c).
Reimplemented from Fl_Graphics_Driver.
Definition at line 130 of file fl_color.cxx.
References Fl_Graphics_Driver::fl_color, fl_color_, fl_display, fl_gc, fl_xpixel(), and i.
void Fl_Xlib_Graphics_Driver::color (uchar r, uchar g, uchar b) [virtual]
see fl_color(uchar r, uchar g, uchar b).
Reimplemented from Fl_Graphics_Driver.
Definition at line 141 of file fl_color.cxx.
References fl_color_, fl_display, fl_gc, fl_rgb_color(), and fl_xpixel().
void Fl_Xlib_Graphics_Driver::draw (int angle, const char * str, int n, int x, int y) [virtual]
see fl_draw(int angle, const char *str, int n, int x, int y).
Reimplemented from Fl_Graphics_Driver.
Definition at line 329 of file fl_font_x.cxx.
References Fl_Graphics_Driver::fl_draw.
void Fl_Xlib_Graphics_Driver::draw (Fl_Bitmap * bm, int XP, int YP, int WP, int HP, int cx, int cy) [virtual]
Draws an Fl_Bitmap object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Graphics_Driver.
Definition at line 352 of file Fl_Bitmap.cxx.
References Fl_Bitmap::array, Fl_Image::draw_empty(), fl_create_bitmask(), fl_display, fl_gc, fl_window, Fl_Image::h(), H, start, and Fl_Image::w().
void Fl_Xlib_Graphics_Driver::draw (Fl_RGB_Image * rgb, int XP, int YP, int WP, int HP, int cx, int cy) [virtual]
Draws an Fl_RGB_Image object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Graphics_Driver.
Definition at line 531 of file Fl_Image.cxx.
References Fl_RGB_Image::array, Fl_Image::d(), Fl_Image::draw_empty(), fl_begin_offscreen(), Fl_Graphics_Driver::fl_clip_box, fl_copy_offscreen(), fl_create_offscreen(), fl_display, Fl_Graphics_Driver::fl_draw_image, fl_end_offscreen(), fl_gc, fl_restore_clip(), Fl_Image::h(), H, Fl_Image::ld(), start, and Fl_Image::w().
void Fl_Xlib_Graphics_Driver::draw (const char * str, int n, int x, int y) [virtual]
see fl_draw(const char *str, int n, int x, int y).
Reimplemented from Fl_Graphics_Driver.
Definition at line 321 of file fl_font_x.cxx.
References current_font, fl_display, Fl_Graphics_Driver::fl_font, fl_gc, FL_HELVETICA, fl_window, and XUtf8DrawString().
void Fl_Xlib_Graphics_Driver::draw (Fl_Pixmap * pxm, int XP, int YP, int WP, int HP, int cx, int cy) [virtual]
Draws an Fl_Pixmap object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Graphics_Driver.
Definition at line 193 of file Fl_Pixmap.cxx.
References Fl_Image::data(), Fl_Image::draw_empty(), fl_begin_offscreen(), FL_BLACK, Fl_Graphics_Driver::fl_clip_box, fl_copy_offscreen(), fl_create_bitmask(), fl_create_offscreen(), fl_display, fl_draw_pixmap(), fl_end_offscreen(), fl_gc, fl_restore_clip(), Fl_Image::h(), H, Fl_Pixmap::measure(), start, and Fl_Image::w().
void Fl_Xlib_Graphics_Driver::draw_image (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 3) [virtual]
see fl_draw_image(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
Reimplemented from Fl_Graphics_Driver.
Definition at line 549 of file fl_draw_image.cxx.
void Fl_Xlib_Graphics_Driver::draw_image (const uchar * buf, int X, int Y, int W, int H, int D = 3, int L = 0) [virtual]
see fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L).
Reimplemented from Fl_Graphics_Driver.
Definition at line 546 of file fl_draw_image.cxx.
void Fl_Xlib_Graphics_Driver::draw_image_mono (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 1) [virtual]
see fl_draw_image_mono(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
Reimplemented from Fl_Graphics_Driver.
Definition at line 556 of file fl_draw_image.cxx.
void Fl_Xlib_Graphics_Driver::draw_image_mono (const uchar * buf, int X, int Y, int W, int H, int D = 1, int L = 0) [virtual]
see fl_draw_image_mono(const uchar* buf, int X,int Y,int W,int H, int D, int L).
Reimplemented from Fl_Graphics_Driver.
Definition at line 553 of file fl_draw_image.cxx.
void Fl_Xlib_Graphics_Driver::font (Fl_Font face, Fl_Fontsize size) [virtual]
see fl_font(Fl_Font face, Fl_Fontsize size).
Reimplemented from Fl_Graphics_Driver.
Definition at line 272 of file fl_font_x.cxx.
References current_font, f, and size.
void Fl_Xlib_Graphics_Driver::rtl_draw (const char * str, int n, int x, int y) [virtual]
see fl_rtl_draw(const char *str, int n, int x, int y).
Reimplemented from Fl_Graphics_Driver.
Definition at line 334 of file fl_font_x.cxx.
References current_font, fl_display, Fl_Graphics_Driver::fl_font, fl_gc, FL_HELVETICA, fl_window, and XUtf8DrawRtlString().
Member Data Documentation
const char * Fl_Xlib_Graphics_Driver::class_id = "Fl_Xlib_Graphics_Driver" [static]
A string that identifies each subclass of Fl_Device.
Function class_name() applied to a device of this class returns this string.
Reimplemented from Fl_Graphics_Driver.
Definition at line 346 of file Fl_Device.H.
Referenced by Fl_Xlib_Graphics_Driver().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Device.H
fltk-1.3.0rc3/src/Fl_Bitmap.cxx
fltk-1.3.0rc3/src/fl_color.cxx
fltk-1.3.0rc3/src/Fl_Device.cxx
fltk-1.3.0rc3/src/fl_draw_image.cxx
fltk-1.3.0rc3/src/fl_font_x.cxx
fltk-1.3.0rc3/src/fl_font_xft.cxx
fltk-1.3.0rc3/src/Fl_Image.cxx
fltk-1.3.0rc3/src/Fl_Pixmap.cxx