SfR Fresh Dox - fltk: Fl_TooltipBox Class Reference
Fl_TooltipBox Class Reference
Public Member Functions
Fl_TooltipBox ()
void draw ()
void layout ()
void show ()
Detailed Description
This widget creates a tooltip box window, with no caption.
Definition at line 50 of file Fl_Tooltip.cxx.
Constructor & Destructor Documentation
Fl_TooltipBox::Fl_TooltipBox () [inline]
Creates the box window
Definition at line 53 of file Fl_Tooltip.cxx.
References Fl_Group::end(), Fl_Window::set_override(), and Fl_Window::set_tooltip_window().
Member Function Documentation
void Fl_TooltipBox::draw () [virtual]
Draws the widget. Never call this function directly. FLTK will schedule redrawing whenever needed. If your widget must be redrawn as soon as possible, call redraw() instead.
Override this function to draw your own widgets.
If you ever need to call another widget's draw method from within your own draw() method, e.g. for an embedded scrollbar, you can do it (because draw() is virtual) like this:
        Fl_Widget *s = &scroll;         // scroll is an embedded Fl_Scrollbar
        s->draw();                      // calls Fl_Scrollbar::draw()
Reimplemented from Fl_Window.
Definition at line 106 of file Fl_Tooltip.cxx.
References Fl_Tooltip::color(), Fl_Widget::draw_box(), FL_ALIGN_LEFT, FL_ALIGN_WRAP, FL_BORDER_BOX, fl_color(), fl_draw(), fl_font(), Fl_Tooltip::font(), Fl_Widget::h(), Fl_Tooltip::size(), Fl_Tooltip::textcolor(), and Fl_Widget::w().
void Fl_TooltipBox::layout ()
Definition at line 78 of file Fl_Tooltip.cxx.
References Fl_Tooltip::current(), Fl::event_x_root(), Fl::event_y_root(), FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_WRAP, fl_font(), fl_measure(), Fl_Tooltip::font(), H, MAX_WIDTH, Fl_Window::resize(), Fl::screen_xywh(), Fl_Tooltip::size(), and Fl_Widget::window().
void Fl_TooltipBox::show () [inline, virtual]
Shows the tooltip windows only if a tooltip text is available.
Reimplemented from Fl_Menu_Window.
Definition at line 61 of file Fl_Tooltip.cxx.
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/src/Fl_Tooltip.cxx