SfR Fresh Dox - fltk: Widget_Browser Class Reference
Widget_Browser Class Reference
Public Member Functions
int handle (int)
void callback ()
Widget_Browser (int, int, int, int, const char *=0)
Friends
class Fl_Type
Detailed Description
Definition at line 178 of file Fl_Type.cxx.
Constructor & Destructor Documentation
Widget_Browser::Widget_Browser (int X, int Y, int W, int H, const char * l = 0)
Definition at line 225 of file Fl_Type.cxx.
References callback(), FL_MULTI_BROWSER, FL_WHEN_RELEASE, Fl_Widget::type(), and Fl_Widget::when().
Member Function Documentation
void Widget_Browser::callback ()
Definition at line 398 of file Fl_Type.cxx.
References Fl_Browser_::selection(), and selection_changed().
Referenced by Widget_Browser().
int Widget_Browser::handle (int event) [virtual]
Handles the event within the normal widget bounding box.
Parameters:
[in] event The event to process.
Returns:
1 if event was processed, 0 if not.
Reimplemented from Fl_Browser_.
Definition at line 402 of file Fl_Type.cxx.
References Fl_Browser_::bbox(), Fl::event_clicks(), Fl::event_inside(), Fl::event_state(), Fl::event_x(), Fl::event_y(), Fl_Browser_::find_item(), FL_CTRL, FL_DRAG, FL_PUSH, FL_RELEASE, H, Fl_Browser_::hposition(), Fl_Type::is_parent(), Fl_Type::level, Fl_Type::new_selected, Fl_Type::next, Fl_Type::open(), Fl_Type::open_, Fl_Widget::redraw(), Fl_Browser_::redraw_line(), and Fl_Type::title().
Friends And Related Function Documentation
friend class Fl_Type [friend]
Definition at line 179 of file Fl_Type.cxx.
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/fluid/Fl_Type.cxx