SfR Fresh Dox - fltk: Fl_Help_View Class Reference
Fl_Help_View Class Reference
#include <Fl_Help_View.H>
Public Member Functions
Fl_Help_View (int xx, int yy, int ww, int hh, const char *l=0)
~Fl_Help_View ()
const char * directory () const
const char * filename () const
int find (const char *s, int p=0)
void link (Fl_Help_Func *fn)
int load (const char *f)
void resize (int, int, int, int)
int size () const
void size (int W, int H)
void textcolor (Fl_Color c)
Fl_Color textcolor () const
void textfont (Fl_Font f)
Fl_Font textfont () const
void textsize (Fl_Fontsize s)
Fl_Fontsize textsize () const
const char * title ()
void topline (const char *n)
void topline (int)
int topline () const
void leftline (int)
int leftline () const
void value (const char *val)
const char * value () const
void clear_selection ()
void select_all ()
int scrollbar_size () const
void scrollbar_size (int size)
Detailed Description
The Fl_Help_View widget displays HTML text. Most HTML 2.0 elements are supported, as well as a primitive implementation of tables. GIF, JPEG, and PNG images are displayed inline.
Supported HTML tags:
A: HREF/NAME
B
BODY: BGCOLOR/TEXT/LINK
BR
CENTER
CODE
DD
DL
DT
EM
FONT: COLOR/SIZE/FACE=(helvetica/arial/sans/times/serif/symbol/courier)
H1/H2/H3/H4/H5/H6
HEAD
HR
I
IMG: SRC/WIDTH/HEIGHT/ALT
KBD
LI
OL
P
PRE
STRONG
TABLE: TH/TD/TR/BORDER/BGCOLOR/COLSPAN/ALIGN=CENTER|RIGHT|LEFT
TITLE
TT
U
UL
VAR
Supported color names:
black,red,green,yellow,blue,magenta,fuchsia,cyan,aqua,white,gray,grey,lime,maroon,navy,olive,purple,silver,teal.
Supported urls:
Internal: file:
External: http: ftp: https: ipp: mailto: news:
Quoted char names:
Aacute aacute Acirc acirc acute AElig aelig Agrave agrave amp Aring aring Atilde atilde Auml auml
brvbar bull
Ccedil ccedil cedil cent copy curren
deg divide
Eacute eacute Ecirc ecirc Egrave egrave ETH eth Euml euml euro
frac12 frac14 frac34
gt
Iacute iacute Icirc icirc iexcl Igrave igrave iquest Iuml iuml
laquo lt
macr micro middot
nbsp not Ntilde ntilde
Oacute oacute Ocirc ocirc Ograve ograve ordf ordm Oslash oslash Otilde otilde Ouml ouml
para premil plusmn pound
quot
raquo reg
sect shy sup1 sup2 sup3 szlig
THORN thorn times trade
Uacute uacute Ucirc ucirc Ugrave ugrave uml Uuml uuml
Yacute yacute
yen Yuml yuml
Definition at line 212 of file Fl_Help_View.H.
Constructor & Destructor Documentation
Fl_Help_View::Fl_Help_View (int xx, int yy, int ww, int hh, const char * l = 0)
The constructor creates the Fl_Help_View widget at the specified position and size.
Definition at line 3032 of file Fl_Help_View.cxx.
References Fl_Widget::callback(), Fl_Widget::color(), Fl_Group::end(), FL_BACKGROUND2_COLOR, FL_BACKGROUND_COLOR, FL_FOREGROUND_COLOR, FL_HORIZONTAL, FL_SELECTION_COLOR, FL_TIMES, NULL, resize(), Fl_Widget::show(), Fl_Valuator::step(), Fl_Widget::type(), and Fl_Scrollbar::value().
Fl_Help_View::~Fl_Help_View ()
Destroys the Fl_Help_View widget.
The destructor destroys the widget and frees all memory that has been allocated for the current document.
Definition at line 3098 of file Fl_Help_View.cxx.
References clear_selection().
Member Function Documentation
void Fl_Help_View::clear_selection ()
Removes the current text selection.
Definition at line 2753 of file Fl_Help_View.cxx.
Referenced by load(), value(), and ~Fl_Help_View().
const char* Fl_Help_View::directory () const [inline]
Returns the current directory for the text in the buffer.
Definition at line 299 of file Fl_Help_View.H.
const char* Fl_Help_View::filename () const [inline]
Returns the current filename for the text in the buffer.
Definition at line 302 of file Fl_Help_View.H.
int Fl_Help_View::find (const char * s, int p = 0)
Finds the specified string s at starting position p.
Returns:
the matching position or -1 if not found
Definition at line 999 of file Fl_Help_View.cxx.
References b, Fl_Help_Block::end, Fl_Help_Block::h, i, Fl_Help_Block::start, topline(), and Fl_Help_Block::y.
void Fl_Help_View::leftline (int left)
Scrolls the text to the indicated position, given a pixel column.
If the given pixel value left is out of range, then the text is scrolled to the left or right side of the document, resp.
Parameters:
[in] left left column number in pixels (0 = left side)
Definition at line 3317 of file Fl_Help_View.cxx.
References Fl_Widget::redraw(), scrollbar_size(), Fl_Scrollbar::value(), and Fl_Widget::w().
int Fl_Help_View::leftline () const [inline]
Gets the left position in pixels.
Definition at line 353 of file Fl_Help_View.H.
Referenced by value().
void Fl_Help_View::link (Fl_Help_Func * fn) [inline]
This method assigns a callback function to use when a link is followed or a file is loaded (via Fl_Help_View::load()) that requires a different file or path.
The callback function receives a pointer to the Fl_Help_View widget and the URI or full pathname for the file in question. It must return a pathname that can be opened as a local file or NULL:
    const char *fn(Fl_Widget *w, const char *uri);
The link function can be used to retrieve remote or virtual documents, returning a temporary file that contains the actual data. If the link function returns NULL, the value of the Fl_Help_View widget will remain unchanged.
If the link callback cannot handle the URI scheme, it should return the uri value unchanged or set the value() of the widget before returning NULL.
Definition at line 327 of file Fl_Help_View.H.
int Fl_Help_View::load (const char * f)
Loads the specified file.
This method loads the specified file or URL.
Definition at line 3110 of file Fl_Help_View.cxx.
References clear_selection(), fl_fopen(), fl_open_uri(), FL_PATH_MAX, fp, NULL, SEEK_END, snprintf, strlcpy, topline(), and value().
Referenced by Fl_Help_Dialog::load().
void Fl_Help_View::resize (int xx, int yy, int ww, int hh) [virtual]
Resizes the help widget.
Reimplemented from Fl_Group.
Definition at line 3234 of file Fl_Help_View.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dw(), Fl::box_dx(), Fl::box_dy(), FL_DOWN_BOX, Fl_Widget::h(), Fl_Widget::resize(), scrollbar_size(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by Fl_Help_View().
int Fl_Help_View::scrollbar_size () const [inline]
Gets the current size of the scrollbars' troughs, in pixels.
If this value is zero (default), this widget will use the Fl::scrollbar_size() value as the scrollbar's width.
Returns:
Scrollbar size in pixels, or 0 if the global Fl::scrollbar_size() is being used.
See also:
Fl::scrollbar_size(int)
Definition at line 368 of file Fl_Help_View.H.
Referenced by leftline(), resize(), and topline().
void Fl_Help_View::scrollbar_size (int size) [inline]
Sets the pixel size of the scrollbars' troughs to the size, in pixels.
Normally you should not need this method, and should use Fl::scrollbar_size(int) instead to manage the size of ALL your widgets' scrollbars. This ensures your application has a consistent UI, is the default behavior, and is normally what you want.
Only use THIS method if you really need to override the global scrollbar size. The need for this should be rare.
Setting size to the special value of 0 causes the widget to track the global Fl::scrollbar_size(), which is the default.
Parameters:
[in] size Sets the scrollbar size in pixels.
If 0 (default), scrollbar size tracks the global Fl::scrollbar_size()
See also:
Fl::scrollbar_size()
Definition at line 390 of file Fl_Help_View.H.
References Fl_Widget::size().
void Fl_Help_View::select_all ()
Selects all the text in the view.
Definition at line 2759 of file Fl_Help_View.cxx.
void Fl_Help_View::size (int W, int H) [inline]
Changes the size of the widget.
size(W, H) is a shortcut for resize(x(), y(), W, H).
Parameters:
[in] W,H new size
See also:
position(int,int), resize(int,int,int,int)
Reimplemented from Fl_Widget.
Definition at line 332 of file Fl_Help_View.H.
References size.
int Fl_Help_View::size () const [inline]
Gets the size of the help view.
Definition at line 331 of file Fl_Help_View.H.
void Fl_Help_View::textcolor (Fl_Color c) [inline]
Sets the default text color.
Definition at line 334 of file Fl_Help_View.H.
Fl_Color Fl_Help_View::textcolor () const [inline]
Returns the current default text color.
Definition at line 336 of file Fl_Help_View.H.
void Fl_Help_View::textfont (Fl_Font f) [inline]
Sets the default text font.
Definition at line 338 of file Fl_Help_View.H.
References f.
Referenced by Fl_Help_View_Type::ideal_size().
Fl_Font Fl_Help_View::textfont () const [inline]
Returns the current default text font.
Definition at line 340 of file Fl_Help_View.H.
void Fl_Help_View::textsize (Fl_Fontsize s) [inline]
Sets the default text size.
Definition at line 342 of file Fl_Help_View.H.
Referenced by Fl_Help_View_Type::ideal_size(), and Fl_Help_Dialog::textsize().
Fl_Fontsize Fl_Help_View::textsize () const [inline]
Gets the default text size.
Definition at line 344 of file Fl_Help_View.H.
const char* Fl_Help_View::title () [inline]
Returns the current document title, or NULL if there is no title.
Definition at line 346 of file Fl_Help_View.H.
Referenced by Fl_Help_Dialog::load(), and Fl_Help_Dialog::value().
void Fl_Help_View::topline (const char * n)
Scrolls the text to the indicated position, given a named destination.
Parameters:
[in] n target name
Definition at line 3261 of file Fl_Help_View.cxx.
References key, Fl_Help_Target::name, NULL, strlcpy, topline(), and Fl_Help_Target::y.
Referenced by Fl_Help_Dialog::topline().
int Fl_Help_View::topline () const [inline]
Returns the current top line in pixels.
Definition at line 350 of file Fl_Help_View.H.
Referenced by find(), load(), topline(), and value().
void Fl_Help_View::topline (int top)
Scrolls the text to the indicated position, given a pixel line.
If the given pixel value top is out of range, then the text is scrolled to the top or bottom of the document, resp.
Parameters:
[in] top top line number in pixels (0 = start of document)
Definition at line 3288 of file Fl_Help_View.cxx.
References Fl_Widget::do_callback(), Fl_Widget::h(), Fl_Widget::redraw(), scrollbar_size(), and Fl_Scrollbar::value().
const char* Fl_Help_View::value () const [inline]
Returns the current buffer contents.
Definition at line 356 of file Fl_Help_View.H.
Referenced by load().
void Fl_Help_View::value (const char * val)
Sets the current help text buffer to the string provided and reformats the text.
The provided character string val is copied internally and will be freed when value() is called again, or when the widget is destroyed.
If val is NULL, then the widget is cleared.
Definition at line 3344 of file Fl_Help_View.cxx.
References clear_selection(), leftline(), Fl_Widget::set_changed(), and topline().
Referenced by Fl_Help_Dialog::value(), and Fl_Help_View_Type::widget().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Help_View.H
fltk-1.3.0rc3/src/Fl_Help_View.cxx