SfR Fresh Dox - fltk: Fl_Window_Type Class Reference
Fl_Window_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Window_Type ()
Fl_Type * make ()
virtual const char * type_name ()
virtual const char * alt_type_name ()
void open ()
void fix_overlay ()
uchar * read_image (int &ww, int &hh)
virtual void write_properties ()
virtual void read_property (const char *)
virtual int read_fdesign (const char *, const char *)
void add_child (Fl_Type *, Fl_Type *)
void move_child (Fl_Type *, Fl_Type *)
void remove_child (Fl_Type *)
int is_parent () const
int is_group () const
int is_window () const
Fl_Widget * enter_live_mode (int top=0)
void leave_live_mode ()
void copy_properties ()
Public Attributes
uchar modal
uchar non_modal
int sr_min_w
int sr_min_h
int sr_max_w
int sr_max_h
Protected Types
enum {
LEFT = 1, RIGHT = 2, BOTTOM = 4, TOP = 8,
DRAG = 16, BOX = 32
}
Protected Member Functions
Fl_Menu_Item * subtypes ()
void draw_overlay ()
void newdx ()
void newposition (Fl_Widget_Type *, int &x, int &y, int &w, int &h)
int handle (int)
virtual void setlabel (const char *)
void write_code1 ()
void write_code2 ()
Fl_Widget_Type * _make ()
Fl_Widget * widget (int, int, int, int)
void moveallchildren ()
int pixmapID ()
Protected Attributes
int mx
int my
int x1
int y1
int bx
int by
int br
int bt
int sx
int sy
int sr
int st
int dx
int dy
int drag
int numselected
int recalc
Friends
class Overlay_Window
Detailed Description
Definition at line 543 of file Fl_Type.h.
Member Enumeration Documentation
anonymous enum [protected]
Enumerator:
LEFT
RIGHT
BOTTOM
TOP
DRAG
BOX
Definition at line 556 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_Window_Type::Fl_Window_Type () [inline]
Definition at line 572 of file Fl_Type.h.
References drag, dx, dy, sr_max_h, sr_max_w, sr_min_h, and sr_min_w.
Referenced by make().
Member Function Documentation
Fl_Widget_Type* Fl_Window_Type::_make () [inline, protected, virtual]
Implements Fl_Widget_Type.
Definition at line 564 of file Fl_Type.h.
void Fl_Window_Type::add_child (Fl_Type * cc, Fl_Type * before) [virtual]
Reimplemented from Fl_Type.
Definition at line 393 of file Fl_Window_Type.cxx.
References b, Fl_Type::insert(), Fl_Type::is_widget(), Fl_Widget_Type::o, and Fl_Widget::redraw().
virtual const char* Fl_Window_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 577 of file Fl_Type.h.
void Fl_Window_Type::copy_properties () [virtual]
copy all properties from the edit widget to the live widget
Todo:
copy resizing constraints over
Reimplemented from Fl_Widget_Type.
Definition at line 1590 of file Fl_Window_Type.cxx.
Referenced by enter_live_mode().
void Fl_Window_Type::draw_overlay () [protected]
Definition at line 733 of file Fl_Window_Type.cxx.
References Fl_Widget::align(), BOTTOM, BOX, br, bt, bx, by, DRAG, drag, dx, dy, FL_ALIGN_BOTTOM, FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_ALIGN_TOP, FL_ALIGN_WRAP, fl_color(), FL_DOT, fl_line_style(), fl_min(), fl_rect(), fl_rectf(), FL_RED, FL_SOLID, h, Fl_Widget::h(), Fl_Widget_Type::ideal_size(), Fl_Widget_Type::ideal_spacing(), Fl_Type::is_group(), Fl_Type::is_widget(), Fl_Widget::labelsize(), LEFT, Fl_Type::level, Fl_Widget::measure_label(), mx, my, newposition(), Fl_Type::next, numselected, Fl_Widget_Type::o, recalc, RIGHT, Fl_Type::selected, show_guides, sr, st, sx, sy, TOP, Fl_Widget::visible_r(), w, Fl_Widget::w(), x, Fl_Widget::x(), x1, y, Fl_Widget::y(), and y1.
Fl_Widget * Fl_Window_Type::enter_live_mode (int top = 0) [virtual]
Build widgets and dataset needed in live mode.
Returns:
a widget pointer that the live mode initiator can 'show()'
See also:
leave_live_mode()
Reimplemented from Fl_Widget_Type.
Definition at line 1569 of file Fl_Window_Type.cxx.
References copy_properties(), Fl_Group::end(), Fl_Type::enter_live_mode(), Fl_Widget::h(), Fl_Type::level, Fl_Widget_Type::live_widget, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
void Fl_Window_Type::fix_overlay ()
Definition at line 1097 of file Fl_Window_Type.cxx.
References Fl_Menu_Item::label(), Fl_Widget_Type::o, and recalc.
int Fl_Window_Type::handle (int event) [protected]
Definition at line 1184 of file Fl_Window_Type.cxx.
References BOTTOM, BOX, br, bt, bx, by, Fl_Menu_Item::callback(), Fl_Type::click_test(), Fl_Type::current, deselect(), Fl_Menu_Item::do_callback(), DRAG, drag, dx, dy, Fl::event_button(), Fl::event_clicks(), Fl::event_inside(), Fl::event_is_click(), Fl::event_key(), Fl::event_state(), Fl::event_x(), Fl::event_y(), FL_CTRL, FL_Down, FL_DRAG, FL_Escape, FL_KEYBOARD, FL_Left, FL_PUSH, FL_RELEASE, FL_Right, FL_SHIFT, FL_SHORTCUT, FL_Tab, FL_Up, gridx, gridy, Fl_Widget::h(), i, Fl_Type::is_menu_item(), Fl_Type::is_widget(), LEFT, Fl_Type::level, m, moveallchildren(), mx, my, newdx(), Fl_Type::next, numselected, Fl_Widget_Type::o, open(), Fl_Type::open(), Fl_Type::parent, Fl_Widget::parent(), Fl_Menu_Item::popup(), Fl_Type::prev, reveal_in_browser(), RIGHT, select(), Fl_Type::selected, snap, Fl_Menu_Item::test_shortcut(), toggle_overlays(), TOP, Fl_Widget::w(), Fl_Widget::x(), x1, Fl_Widget::y(), and y1.
int Fl_Window_Type::is_group () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 593 of file Fl_Type.h.
int Fl_Window_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Widget_Class_Type.
Definition at line 592 of file Fl_Type.h.
int Fl_Window_Type::is_window () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 594 of file Fl_Type.h.
void Fl_Window_Type::leave_live_mode () [virtual]
Release all resources created when enetring live mode.
See also:
enter_live_mode()
Reimplemented from Fl_Widget_Type.
Definition at line 1584 of file Fl_Window_Type.cxx.
Fl_Type * Fl_Window_Type::make () [virtual]
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Widget_Class_Type.
Definition at line 364 of file Fl_Window_Type.cxx.
References Fl_Type::add(), Fl_Type::current, drag, Fl_Type::factory, fl_message(), Fl_Window_Type(), gridx, gridy, Fl_Type::is_code_block(), modal, non_modal, numselected, Fl_Widget_Type::o, Overlay_Window, Fl_Type::parent, w, and Overlay_Window::window.
void Fl_Window_Type::move_child (Fl_Type * cc, Fl_Type * before) [virtual]
Reimplemented from Fl_Type.
Definition at line 407 of file Fl_Window_Type.cxx.
References b, Fl_Type::insert(), Fl_Widget_Type::o, and Fl_Type::remove().
void Fl_Window_Type::moveallchildren () [protected]
Definition at line 1149 of file Fl_Window_Type.cxx.
References dx, dy, fix_group_size(), i, Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::level, newposition(), Fl_Type::next, Fl_Widget_Type::o, recalc, Fl_Widget::redraw(), Fl_Widget::resize(), Fl_Type::selected, set_modflag(), undo_checkpoint(), x, and y.
Referenced by handle().
void Fl_Window_Type::newdx () [protected]
Definition at line 531 of file Fl_Window_Type.cxx.
References BOTTOM, BOX, br, bt, bx, by, DRAG, drag, dx, dy, Fl::event_state(), FL_ALT, gridx, gridy, LEFT, mx, my, Fl_Widget_Type::o, RIGHT, snap, TOP, x1, and y1.
Referenced by handle().
void Fl_Window_Type::newposition (Fl_Widget_Type * myo, int & x, int & y, int & w, int & h) [protected]
Definition at line 576 of file Fl_Window_Type.cxx.
References BOTTOM, br, bt, bx, by, DRAG, drag, dx, dy, Fl_Widget::h(), LEFT, Fl_Widget_Type::o, RIGHT, TOP, Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by draw_overlay(), and moveallchildren().
void Fl_Window_Type::open () [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 419 of file Fl_Window_Type.cxx.
References gridx, gridy, Fl::h(), Fl_Widget::image(), Fl_Widget_Type::o, Fl_Group::resizable(), Fl::scheme_bg_, Fl_Overlay_Window::show(), Fl_Window::shown(), Fl_Window::size_range(), Fl::w(), and w.
Referenced by handle(), and read_property().
int Fl_Window_Type::pixmapID () [inline, protected, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Widget_Class_Type.
Definition at line 568 of file Fl_Type.h.
int Fl_Window_Type::read_fdesign (const char * propname, const char * value) [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 1422 of file Fl_Window_Type.cxx.
References Fl_Widget::box(), FL_NO_BOX, Fl_Widget::h(), Fl_Type::label(), Fl_Widget_Type::o, Fl_Widget::size(), Fl_Widget::w(), and x.
uchar * Fl_Window_Type::read_image (int & ww, int & hh)
Definition at line 436 of file Fl_Window_Type.cxx.
References Fl_Widget_Type::o, Overlay_Window::read_image(), and w.
Referenced by print_cb(), and save_template_cb().
void Fl_Window_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Widget_Class_Type.
Definition at line 1397 of file Fl_Window_Type.cxx.
References Fl::first_window(), modal, non_modal, Fl_Widget_Type::o, open(), read_word(), sr_max_h, sr_max_w, sr_min_h, sr_min_w, storestring(), and Fl_Widget_Type::xclass.
void Fl_Window_Type::remove_child (Fl_Type * cc) [virtual]
Reimplemented from Fl_Type.
Definition at line 401 of file Fl_Window_Type.cxx.
References Fl_Widget_Type::o, and Fl_Type::remove().
void Fl_Window_Type::setlabel (const char * n) [protected, virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 507 of file Fl_Window_Type.cxx.
References Fl_Widget_Type::o.
Fl_Menu_Item* Fl_Window_Type::subtypes () [inline, protected, virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 546 of file Fl_Type.h.
References window_type_menu.
virtual const char* Fl_Window_Type::type_name () [inline, virtual]
Implements Fl_Type.
Reimplemented in Fl_Widget_Class_Type.
Definition at line 576 of file Fl_Type.h.
Fl_Widget* Fl_Window_Type::widget (int , int , int , int) [inline, protected, virtual]
Implements Fl_Widget_Type.
Definition at line 565 of file Fl_Type.h.
void Fl_Window_Type::write_code1 () [protected, virtual]
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Widget_Class_Type.
Definition at line 1356 of file Fl_Window_Type.cxx.
void Fl_Window_Type::write_code2 () [protected, virtual]
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Widget_Class_Type.
Definition at line 1360 of file Fl_Window_Type.cxx.
References indent(), Fl_Type::is_class(), modal, Fl_Type::name(), non_modal, Fl_Widget_Type::o, Fl_Widget_Type::resizable(), sr_max_h, sr_max_w, sr_min_h, sr_min_w, Fl_Widget_Type::write_block_close(), write_c(), write_cstring(), Fl_Widget_Type::write_extra_code(), and Fl_Widget_Type::xclass.
void Fl_Window_Type::write_properties () [virtual]
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Widget_Class_Type.
Definition at line 1385 of file Fl_Window_Type.cxx.
References modal, non_modal, Fl_Widget_Type::o, sr_max_h, sr_max_w, sr_min_h, sr_min_w, Fl_Widget::visible(), write_string(), write_word(), and Fl_Widget_Type::xclass.
Friends And Related Function Documentation
friend class Overlay_Window [friend]
Definition at line 548 of file Fl_Type.h.
Referenced by Fl_Widget_Class_Type::make(), and make().
Member Data Documentation
int Fl_Window_Type::br [protected]
Definition at line 551 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), newdx(), and newposition().
int Fl_Window_Type::bt [protected]
Definition at line 551 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), newdx(), and newposition().
int Fl_Window_Type::bx [protected]
Definition at line 551 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), newdx(), and newposition().
int Fl_Window_Type::by [protected]
Definition at line 551 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), newdx(), and newposition().
int Fl_Window_Type::drag [protected]
Definition at line 554 of file Fl_Type.h.
Referenced by draw_overlay(), Fl_Window_Type(), handle(), make(), newdx(), and newposition().
int Fl_Window_Type::dx [protected]
Definition at line 553 of file Fl_Type.h.
Referenced by draw_overlay(), Fl_Window_Type(), handle(), moveallchildren(), newdx(), and newposition().
int Fl_Window_Type::dy [protected]
Definition at line 553 of file Fl_Type.h.
Referenced by draw_overlay(), Fl_Window_Type(), handle(), moveallchildren(), newdx(), and newposition().
uchar Fl_Window_Type::modal
Definition at line 573 of file Fl_Type.h.
Referenced by make(), read_property(), Fl_Widget_Class_Type::write_code2(), write_code2(), and write_properties().
int Fl_Window_Type::mx [protected]
Definition at line 549 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), and newdx().
int Fl_Window_Type::my [protected]
Definition at line 549 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), and newdx().
uchar Fl_Window_Type::non_modal
Definition at line 573 of file Fl_Type.h.
Referenced by make(), read_property(), Fl_Widget_Class_Type::write_code2(), write_code2(), and write_properties().
int Fl_Window_Type::numselected [protected]
Definition at line 555 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), and make().
int Fl_Window_Type::recalc [protected]
Definition at line 566 of file Fl_Type.h.
Referenced by draw_overlay(), fix_overlay(), and moveallchildren().
int Fl_Window_Type::sr [protected]
Definition at line 552 of file Fl_Type.h.
Referenced by draw_overlay().
int Fl_Window_Type::sr_max_h
Definition at line 600 of file Fl_Type.h.
Referenced by Fl_Window_Type(), live_mode_cb(), read_property(), set_max_size_cb(), write_code2(), and write_properties().
int Fl_Window_Type::sr_max_w
Definition at line 600 of file Fl_Type.h.
Referenced by Fl_Window_Type(), live_mode_cb(), read_property(), set_max_size_cb(), write_code2(), and write_properties().
int Fl_Window_Type::sr_min_h
Definition at line 600 of file Fl_Type.h.
Referenced by Fl_Window_Type(), live_mode_cb(), read_property(), set_min_size_cb(), write_code2(), and write_properties().
int Fl_Window_Type::sr_min_w
Definition at line 600 of file Fl_Type.h.
Referenced by Fl_Window_Type(), live_mode_cb(), read_property(), set_min_size_cb(), write_code2(), and write_properties().
int Fl_Window_Type::st [protected]
Definition at line 552 of file Fl_Type.h.
Referenced by draw_overlay().
int Fl_Window_Type::sx [protected]
Definition at line 552 of file Fl_Type.h.
Referenced by draw_overlay().
int Fl_Window_Type::sy [protected]
Definition at line 552 of file Fl_Type.h.
Referenced by draw_overlay().
int Fl_Window_Type::x1 [protected]
Definition at line 550 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), and newdx().
int Fl_Window_Type::y1 [protected]
Definition at line 550 of file Fl_Type.h.
Referenced by draw_overlay(), handle(), and newdx().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Window_Type.cxx