SfR Fresh Dox - fltk: CodeViewer Class Reference
CodeViewer Class Reference
#include <CodeEditor.h>
Public Member Functions
CodeViewer (int X, int Y, int W, int H, const char *L=0)
Protected Member Functions
int handle (int ev)
Event handling.
Detailed Description
Definition at line 73 of file CodeEditor.h.
Constructor & Destructor Documentation
CodeViewer::CodeViewer (int X, int Y, int W, int H, const char * L = 0)
Definition at line 409 of file CodeEditor.cxx.
References Fl_Text_Display::CARET_CURSOR, Fl_Text_Display::cursor_style(), Fl_Text_Editor::default_key_function(), Fl_Text_Editor::key_bindings, Fl_Text_Editor::kf_ignore(), and Fl_Text_Editor::remove_all_key_bindings().
Member Function Documentation
int CodeViewer::handle (int e) [inline, protected, virtual]
Event handling.
Reimplemented from Fl_Text_Editor.
Definition at line 81 of file CodeEditor.h.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/CodeEditor.h
fltk-1.3.0rc3/fluid/CodeEditor.cxx