SfR Fresh Dox - fltk: Fl_PostScript_Printer Class Reference
Fl_PostScript_Printer Class Reference
#include <Fl_Printer.H>
Public Member Functions
int start_job (int pages, int *firstpage=NULL, int *lastpage=NULL)
Starts a print job.
Static Public Attributes
static const char * class_id = Fl_Printer::class_id
A string that identifies each subclass of Fl_Device.
Protected Member Functions
Fl_PostScript_Printer (void)
The constructor.
Friends
class Fl_Printer
Detailed Description
Print support under Unix/Linux.
Class Fl_PostScript_Printer is implemented only on the Unix/Linux platform. It has no public constructor. Use Fl_Printer instead that is cross-platform and has the same API.
Definition at line 107 of file Fl_Printer.H.
Constructor & Destructor Documentation
Fl_PostScript_Printer::Fl_PostScript_Printer (void) [inline, protected]
The constructor.
Definition at line 111 of file Fl_Printer.H.
References class_id, and Fl_Device::class_name().
Member Function Documentation
int Fl_PostScript_Printer::start_job (int pagecount, int * frompage = NULL, int * topage = NULL) [virtual]
Starts a print job.
Parameters:
[in] pagecount the total number of pages of the job
[out] frompage if non-null, *frompage is set to the first page the user wants printed
[out] topage if non-null, *topage is set to the last page the user wants printed
Returns:
0 iff OK
Reimplemented from Fl_Paged_Device.
Definition at line 1474 of file Fl_PostScript.cxx.
References Fl_Paged_Device::A4, Fl_Widget::deactivate(), Fl_Widget::do_callback(), Fl_PostScript_File_Device::driver(), fl_alert(), int, Fl_Paged_Device::LANDSCAPE, Fl_Paged_Device::LETTER, make_print_panel(), Fl_Menu_::menu(), Fl_Paged_Device::PORTRAIT, print_all, print_choice, print_collate_button, print_copies, print_from, print_load(), print_output_mode, print_page_size, print_pages, print_panel, print_selection, print_to, Fl_Surface_Device::set_current(), Fl_Button::setonly(), Fl_Double_Window::show(), Fl_Window::shown(), snprintf, Fl_Menu_::text(), Fl_Menu_Item::user_data(), Fl_Spinner::value(), value, Fl_Button::value(), Fl_Choice::value(), Fl_Input_::value(), and Fl::wait().
Referenced by Fl_Printer::start_job().
Friends And Related Function Documentation
friend class Fl_Printer [friend]
Definition at line 108 of file Fl_Printer.H.
Member Data Documentation
const char * Fl_PostScript_Printer::class_id = Fl_Printer::class_id [static]
A string that identifies each subclass of Fl_Device.
Function class_name() applied to a device of this class returns this string.
Reimplemented from Fl_PostScript_File_Device.
Definition at line 111 of file Fl_Printer.H.
Referenced by Fl_PostScript_Printer().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Printer.H
fltk-1.3.0rc3/src/Fl_PostScript.cxx
fltk-1.3.0rc3/src/Fl_Printer.cxx