SfR Fresh Dox - fltk: Fl_Tiled_Image Class Reference
Fl_Tiled_Image Class Reference
#include <Fl_Tiled_Image.H>
Public Member Functions
Fl_Tiled_Image (Fl_Image *i, int W=0, int H=0)
virtual ~Fl_Tiled_Image ()
virtual Fl_Image * copy (int W, int H)
Fl_Image * copy ()
virtual void color_average (Fl_Color c, float i)
virtual void desaturate ()
virtual void draw (int X, int Y, int W, int H, int cx, int cy)
void draw (int X, int Y)
Fl_Image * image ()
Protected Attributes
Fl_Image * image_
int alloc_image_
Detailed Description
This class supports tiling of images over a specified area. The source (tile) image is not copied unless you call the color_average(), desaturate(), or inactive() methods.
Definition at line 45 of file Fl_Tiled_Image.H.
Constructor & Destructor Documentation
Fl_Tiled_Image::Fl_Tiled_Image (Fl_Image * i, int W = 0, int H = 0)
The constructors create a new tiled image containing the specified image. Use a width and height of 0 to tile the whole window/widget.
Definition at line 37 of file Fl_Tiled_Image.cxx.
References alloc_image_, Fl::h(), Fl_Image::h(), i, image_, Fl::w(), and Fl_Image::w().
Referenced by copy().
Fl_Tiled_Image::~Fl_Tiled_Image () [virtual]
The destructor frees all memory and server resources that are used by the tiled image.
Definition at line 51 of file Fl_Tiled_Image.cxx.
References alloc_image_, and image_.
Member Function Documentation
void Fl_Tiled_Image::color_average (Fl_Color c, float i) [virtual]
The color_average() method averages the colors in the image with the FLTK color value c. The i argument specifies the amount of the original image to combine with the color, so a value of 1.0 results in no color blend, and a value of 0.0 results in a constant image of the specified color. The original image data is not altered by this method.
Reimplemented from Fl_Image.
Definition at line 73 of file Fl_Tiled_Image.cxx.
References alloc_image_, Fl_Image::color_average(), Fl_Image::copy(), and image_.
Fl_Image* Fl_Tiled_Image::copy () [inline]
The copy() method creates a copy of the specified image. If the width and height are provided, the image is resized to the specified size. The image should be deleted (or in the case of Fl_Shared_Image, released) when you are done with it.
Reimplemented from Fl_Image.
Definition at line 57 of file Fl_Tiled_Image.H.
References copy(), Fl_Image::h(), and Fl_Image::w().
Referenced by copy().
Fl_Image * Fl_Tiled_Image::copy (int W, int H) [virtual]
The copy() method creates a copy of the specified image. If the width and height are provided, the image is resized to the specified size. The image should be deleted (or in the case of Fl_Shared_Image, released) when you are done with it.
Reimplemented from Fl_Image.
Definition at line 61 of file Fl_Tiled_Image.cxx.
References Fl_Tiled_Image(), Fl_Image::h(), image_, and Fl_Image::w().
void Fl_Tiled_Image::desaturate () [virtual]
The desaturate() method converts an image to grayscale. If the image contains an alpha channel (depth = 4), the alpha channel is preserved. This method does not alter the original image data.
Reimplemented from Fl_Image.
Definition at line 89 of file Fl_Tiled_Image.cxx.
References alloc_image_, Fl_Image::copy(), Fl_Image::desaturate(), and image_.
void Fl_Tiled_Image::draw (int X, int Y, int W, int H, int cx, int cy) [virtual]
The draw() methods draw the image. This form specifies a bounding box for the image, with the origin (upper-lefthand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Image.
Definition at line 104 of file Fl_Tiled_Image.cxx.
References Fl_Image::draw(), fl_pop_clip(), fl_push_clip(), H, Fl_Image::h(), image_, and Fl_Image::w().
void Fl_Tiled_Image::draw (int X, int Y) [inline]
The draw() methods draw the image. This form specifies the upper-lefthand corner of the image
Reimplemented from Fl_Image.
Definition at line 61 of file Fl_Tiled_Image.H.
References draw(), Fl_Image::h(), and Fl_Image::w().
Referenced by draw().
Fl_Image* Fl_Tiled_Image::image () [inline]
Gets The image that is shared
Definition at line 63 of file Fl_Tiled_Image.H.
Member Data Documentation
int Fl_Tiled_Image::alloc_image_ [protected]
Definition at line 49 of file Fl_Tiled_Image.H.
Referenced by color_average(), desaturate(), Fl_Tiled_Image(), and ~Fl_Tiled_Image().
Fl_Image* Fl_Tiled_Image::image_ [protected]
Definition at line 48 of file Fl_Tiled_Image.H.
Referenced by color_average(), copy(), desaturate(), draw(), Fl_Tiled_Image(), and ~Fl_Tiled_Image().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Tiled_Image.H
fltk-1.3.0rc3/src/Fl_Tiled_Image.cxx