SfR Fresh Dox - fltk: FLDataObject Class Reference
FLDataObject Class Reference
Public Member Functions
FLDataObject ()
HRESULT STDMETHODCALLTYPE QueryInterface (REFIID riid, LPVOID *ppvObject)
ULONG STDMETHODCALLTYPE AddRef ()
ULONG STDMETHODCALLTYPE Release ()
HRESULT STDMETHODCALLTYPE GetData (FORMATETC *pformatetcIn, STGMEDIUM *pmedium)
HRESULT STDMETHODCALLTYPE QueryGetData (FORMATETC *pformatetc)
HRESULT STDMETHODCALLTYPE GetDataHere (FORMATETC *, STGMEDIUM *)
HRESULT STDMETHODCALLTYPE GetCanonicalFormatEtc (FORMATETC *, FORMATETC *)
HRESULT STDMETHODCALLTYPE SetData (FORMATETC *, STGMEDIUM *, BOOL)
HRESULT STDMETHODCALLTYPE EnumFormatEtc (DWORD, IEnumFORMATETC **)
HRESULT STDMETHODCALLTYPE DAdvise (FORMATETC *, DWORD, IAdviseSink *, DWORD *)
HRESULT STDMETHODCALLTYPE DUnadvise (DWORD)
HRESULT STDMETHODCALLTYPE EnumDAdvise (IEnumSTATDATA **)
Detailed Description
This is the actual object that FLTK can drop somewhere.
The implementation is minimal, but it should work with all decent Win32 drop targets
Definition at line 429 of file fl_dnd_win32.cxx.
Constructor & Destructor Documentation
FLDataObject::FLDataObject () [inline]
Definition at line 434 of file fl_dnd_win32.cxx.
Member Function Documentation
ULONG STDMETHODCALLTYPE FLDataObject::AddRef (void) [inline]
Definition at line 445 of file fl_dnd_win32.cxx.
Referenced by Fl::dnd().
HRESULT STDMETHODCALLTYPE FLDataObject::DAdvise (FORMATETC * , DWORD , IAdviseSink * , DWORD *) [inline]
Definition at line 519 of file fl_dnd_win32.cxx.
HRESULT STDMETHODCALLTYPE FLDataObject::DUnadvise (DWORD) [inline]
Definition at line 521 of file fl_dnd_win32.cxx.
HRESULT STDMETHODCALLTYPE FLDataObject::EnumDAdvise (IEnumSTATDATA **) [inline]
Definition at line 522 of file fl_dnd_win32.cxx.
HRESULT STDMETHODCALLTYPE FLDataObject::EnumFormatEtc (DWORD , IEnumFORMATETC **) [inline]
Definition at line 517 of file fl_dnd_win32.cxx.
HRESULT STDMETHODCALLTYPE FLDataObject::GetCanonicalFormatEtc (FORMATETC * , FORMATETC *) [inline]
Definition at line 515 of file fl_dnd_win32.cxx.
HRESULT STDMETHODCALLTYPE FLDataObject::GetData (FORMATETC * pformatetcIn, STGMEDIUM * pmedium) [inline]
Definition at line 454 of file fl_dnd_win32.cxx.
References fl_selection_buffer, fl_selection_length, fl_utf8toUtf16(), and NULL.
HRESULT STDMETHODCALLTYPE FLDataObject::GetDataHere (FORMATETC * , STGMEDIUM *) [inline]
Definition at line 514 of file fl_dnd_win32.cxx.
HRESULT STDMETHODCALLTYPE FLDataObject::QueryGetData (FORMATETC * pformatetc) [inline]
Definition at line 500 of file fl_dnd_win32.cxx.
HRESULT STDMETHODCALLTYPE FLDataObject::QueryInterface (REFIID riid, LPVOID * ppvObject) [inline]
Definition at line 435 of file fl_dnd_win32.cxx.
References NULL.
ULONG STDMETHODCALLTYPE FLDataObject::Release () [inline]
Definition at line 446 of file fl_dnd_win32.cxx.
Referenced by Fl::dnd().
HRESULT STDMETHODCALLTYPE FLDataObject::SetData (FORMATETC * , STGMEDIUM * , BOOL) [inline]
Definition at line 516 of file fl_dnd_win32.cxx.
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/src/fl_dnd_win32.cxx