SfR Fresh Dox - fltk: Fl_X Class Reference
Fl_X Class Reference
#include <win32.H>
Public Member Functions
void setwindow (Fl_Window *wi)
void flush ()
void set_minmax (LPMINMAXINFO minmax)
void mapraise ()
void setwindow (Fl_Window *wi)
void sendxjunk ()
void flush ()
Static Public Member Functions
static Fl_X * i (const Fl_Window *w)
static int fake_X_wm (const Fl_Window *w, int &X, int &Y, int &bt, int &bx, int &by)
static Fl_X * make (Fl_Window *)
static Fl_X * i (const Fl_Window *wi)
static void make_xid (Fl_Window *, XVisualInfo *=fl_visual, Colormap=fl_colormap)
static Fl_X * set_xid (Fl_Window *, Window)
static void x (Fl_Window *wi, int X)
static void y (Fl_Window *wi, int Y)
Public Attributes
Window xid
HBITMAP other_xid
Fl_Window * w
Fl_Region region
Fl_X * next
int wait_for_expose
HDC private_dc
HCURSOR cursor
HDC saved_hdc
Window other_xid
char wait_for_expose
char backbuffer_bad
Static Public Attributes
static Fl_X * first
Detailed Description
Definition at line 72 of file win32.H.
Member Function Documentation
int Fl_X::fake_X_wm (const Fl_Window * w, int & X, int & Y, int & bt, int & bx, int & by) [static]
Todo:
this is a leftover from OS9 times. Please check how much applies to Carbon!
Definition at line 1734 of file Fl_mac.cxx.
References Fl_Window::border(), dx, dy, Fl_Widget::h(), H, Fl_Widget::parent(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by make(), and set_minmax().
void Fl_X::flush () [inline]
Initialize the given port for redraw and call the windw's flush() to actually draw the content
Definition at line 90 of file win32.H.
References w.
void Fl_X::flush () [inline]
Definition at line 155 of file x.H.
References w.
static Fl_X* Fl_X::i (const Fl_Window * w) [inline, static]
Definition at line 86 of file win32.H.
Referenced by Fl_Window::border(), Fl::first_window(), fl_handle(), fl_xid(), Fl_Menu_Window::flush(), Fl_Double_Window::flush(), Fl_Double_Window::hide(), MacMapWindow(), MacUnmapWindow(), make(), make_xid(), and Fl_Double_Window::resize().
static Fl_X* Fl_X::i (const Fl_Window * wi) [inline, static]
Definition at line 149 of file x.H.
Fl_X * Fl_X::make (Fl_Window * w) [static]
go ahead, create that (sub)window
Todo:
we should make menu windows slightly transparent for the new Mac look
Definition at line 2102 of file Fl_mac.cxx.
References carbonKeyboardHandler(), carbonTextHandler(), Fl_Group::current(), cursor, Fl::e_number, Fl_Tooltip::enter, fake_X_wm(), first, fl_default_cursor, fl_disable_transient_for, fl_fix_focus(), fl_open_display(), FL_SHOW, fl_show_iconic, fl_xid(), Fl_Widget::flags(), Fl_Widget::FORCE_POSITION, Fl::grab(), Fl_Widget::h(), Fl_Window::handle(), i(), Fl_Window::label(), Fl_Window::modal(), Fl::modal_, next, Fl_Window::non_modal(), other_xid, Fl_Window::override(), Fl_Widget::parent(), pw, rect(), Fl_Widget::redraw(), region, Fl_Group::resizable(), Fl_Widget::set_visible(), Fl_Window::size_range(), w, Fl_Widget::w(), wait_for_expose, Fl_Widget::window(), Fl::x(), x(), Fl_Widget::x(), xid, Fl::y(), and Fl_Widget::y().
Referenced by Fl_Window::show().
void Fl_X::make_xid (Fl_Window * win, XVisualInfo * visual = fl_visual, Colormap colormap = fl_colormap) [static]
Definition at line 1545 of file Fl_x.cxx.
References Fl_Window::border(), buffer, Fl_Group::current(), Fl::e_number, fl_background_pixel, fl_disable_transient_for, FL_SHOW, fl_xid(), Fl_Widget::flags(), Fl_Widget::FORCE_POSITION, Fl::grab(), H, Fl_Widget::h(), Fl_Window::handle(), i(), Fl_Window::icon(), Fl_Window::iconlabel(), Fl_Window::label(), mask, Fl_Window::menu_window(), next, Fl_Window::non_modal(), Fl_Window::override(), Fl_Widget::parent(), Fl_Widget::redraw(), Fl::screen_xywh(), sendxjunk(), Fl_Widget::set_visible(), set_xid(), Fl_Window::tooltip_window(), version, Fl_Widget::visible(), w, Fl_Widget::w(), Fl_Widget::window(), Fl_Widget::x(), Fl_Window::xclass(), xid, XMapWindow, and Fl_Widget::y().
Referenced by Fl_Menu_Window::show().
void Fl_X::mapraise ()
void Fl_X::sendxjunk ()
Definition at line 1715 of file Fl_x.cxx.
References Fl_Window::border(), Fl_Widget::flags(), Fl_Widget::FORCE_POSITION, h, Fl_Widget::h(), Fl_Window::override(), Fl_Widget::parent(), Fl_Group::resizable(), Fl_Window::size_range(), Fl_Widget::w(), w, Fl_Widget::x(), xid, and Fl_Widget::y().
Referenced by Fl_Window::border(), and make_xid().
void Fl_X::set_minmax (LPMINMAXINFO minmax)
Definition at line 1693 of file Fl_win32.cxx.
References fake_X_wm().
Fl_X * Fl_X::set_xid (Fl_Window * win, Window winxid) [static]
Definition at line 1513 of file Fl_x.cxx.
References backbuffer_bad, first, fl_fix_focus(), Fl_Window::modal(), Fl::modal_, next, other_xid, region, setwindow(), wait_for_expose, and xid.
Referenced by make_xid().
void Fl_X::setwindow (Fl_Window * wi) [inline]
Definition at line 89 of file win32.H.
References w.
Referenced by set_xid().
void Fl_X::setwindow (Fl_Window * wi) [inline]
Definition at line 150 of file x.H.
References w.
static void Fl_X::x (Fl_Window * wi, int X) [inline, static]
Definition at line 156 of file x.H.
References Fl_Widget::x().
Referenced by make().
static void Fl_X::y (Fl_Window * wi, int Y) [inline, static]
Definition at line 157 of file x.H.
References Fl_Widget::y().
Member Data Documentation
char Fl_X::backbuffer_bad
Definition at line 147 of file x.H.
Referenced by Fl_Double_Window::flush(), and set_xid().
HCURSOR Fl_X::cursor
Definition at line 82 of file win32.H.
Referenced by make().
Fl_X * Fl_X::first [static]
Definition at line 85 of file win32.H.
Referenced by Fl::check(), fl_find(), MacUnlinkWindow(), make(), Fl::run(), set_xid(), and Fl::wait().
Fl_X * Fl_X::next
Definition at line 79 of file win32.H.
Referenced by fl_find(), Fl_Window::hide(), MacUnlinkWindow(), make(), make_xid(), and set_xid().
HBITMAP Fl_X::other_xid
Definition at line 76 of file win32.H.
Referenced by Fl_Double_Window::flush(), Fl_Double_Window::hide(), make(), Fl_Double_Window::resize(), and set_xid().
Window Fl_X::other_xid
Definition at line 142 of file x.H.
HDC Fl_X::private_dc
Definition at line 81 of file win32.H.
Referenced by Fl_Window::hide().
Fl_Region Fl_X::region
Definition at line 78 of file win32.H.
Referenced by Fl_Widget::damage(), Fl_Menu_Window::flush(), Fl_Double_Window::flush(), Fl_Window::flush(), Fl_Window::hide(), make(), and set_xid().
HDC Fl_X::saved_hdc
Definition at line 83 of file win32.H.
Fl_Window * Fl_X::w
Definition at line 77 of file win32.H.
Referenced by Fl::first_window(), fl_find(), make(), make_xid(), Fl::next_window(), and sendxjunk().
int Fl_X::wait_for_expose
Definition at line 80 of file win32.H.
Referenced by fl_handle(), make(), and set_xid().
char Fl_X::wait_for_expose
Definition at line 146 of file x.H.
Window Fl_X::xid
Definition at line 75 of file win32.H.
Referenced by fl_find(), fl_xid(), Fl_Menu_Window::flush(), Fl_Double_Window::flush(), Fl_Window::hide(), Fl_Window::iconize(), make(), Fl_Window::make_current(), make_xid(), Fl_Window::resize(), sendxjunk(), set_xid(), and Fl_Window::show().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/win32.H
fltk-1.3.0rc3/FL/x.H
fltk-1.3.0rc3/src/Fl.cxx
fltk-1.3.0rc3/src/Fl_mac.cxx
fltk-1.3.0rc3/src/Fl_win32.cxx
fltk-1.3.0rc3/src/Fl_x.cxx