SfR Fresh Dox - fltk: Fl_Spinner Class Reference
Fl_Spinner Class Reference
#include <Fl_Spinner.H>
Public Member Functions
Fl_Spinner (int X, int Y, int W, int H, const char *L=0)
const char * format ()
void format (const char *f)
int handle (int event)
double maxinum () const
double maximum () const
void maximum (double m)
double mininum () const
double minimum () const
void minimum (double m)
void range (double a, double b)
void resize (int X, int Y, int W, int H)
double step () const
void step (double s)
Fl_Color textcolor () const
void textcolor (Fl_Color c)
Fl_Font textfont () const
void textfont (Fl_Font f)
Fl_Fontsize textsize () const
void textsize (Fl_Fontsize s)
uchar type () const
void type (uchar v)
double value () const
void value (double v)
Detailed Description
This widget is a combination of the input widget and repeat buttons. The user can either type into the input area or use the buttons to change the value.
Definition at line 51 of file Fl_Spinner.H.
Constructor & Destructor Documentation
Fl_Spinner::Fl_Spinner (int X, int Y, int W, int H, const char * L = 0) [inline]
Creates a new Fl_Spinner widget using the given position, size, and label string.
Inherited destructor Destroys the widget and any value associated with it.
Definition at line 126 of file Fl_Spinner.H.
References Fl_Widget::align(), Fl_Group::end(), FL_ALIGN_LEFT, FL_INT_INPUT, FL_WHEN_ENTER_KEY, and FL_WHEN_RELEASE.
Member Function Documentation
const char* Fl_Spinner::format () [inline]
Sets or returns the format string for the value.
Definition at line 153 of file Fl_Spinner.H.
void Fl_Spinner::format (const char * f) [inline]
Sets or returns the format string for the value.
Definition at line 155 of file Fl_Spinner.H.
References f.
int Fl_Spinner::handle (int event) [inline, virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Group.
Definition at line 157 of file Fl_Spinner.H.
References Fl::event_key(), FL_Down, FL_FOCUS, FL_KEYDOWN, FL_SHORTCUT, FL_Up, and Fl_Group::handle().
double Fl_Spinner::maximum () const [inline]
Gets the maximum value of the widget.
Definition at line 180 of file Fl_Spinner.H.
Referenced by Fl_Widget_Type::copy_properties(), make_settings_window(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
void Fl_Spinner::maximum (double m) [inline]
Sets the maximum value of the widget.
Definition at line 182 of file Fl_Spinner.H.
References m.
double Fl_Spinner::maxinum () const [inline]
Speling mistakes retained for source compatibility
Deprecated:
Definition at line 178 of file Fl_Spinner.H.
double Fl_Spinner::minimum () const [inline]
Gets the minimum value of the widget.
Definition at line 186 of file Fl_Spinner.H.
Referenced by Fl_Widget_Type::copy_properties(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
void Fl_Spinner::minimum (double m) [inline]
Sets the minimum value of the widget.
Definition at line 188 of file Fl_Spinner.H.
References m.
double Fl_Spinner::mininum () const [inline]
Speling mistakes retained for source compatibility
Deprecated:
Definition at line 184 of file Fl_Spinner.H.
void Fl_Spinner::range (double a, double b) [inline]
Sets the minimum and maximum values for the widget.
Definition at line 190 of file Fl_Spinner.H.
References b.
void Fl_Spinner::resize (int X, int Y, int W, int H) [inline, virtual]
Resizes the Fl_Group widget and all of its children.
The Fl_Group widget first resizes itself, and then it moves and resizes all its children according to the rules documented for Fl_Group::resizable(Fl_Widget*)
See also:
Fl_Group::resizable(Fl_Widget*)
Fl_Group::resizable()
Fl_Widget::resize(int,int,int,int)
Reimplemented from Fl_Group.
Definition at line 191 of file Fl_Spinner.H.
References Fl_Group::resize().
double Fl_Spinner::step () const [inline]
Sets or returns the amount to change the value when the user clicks a button. Before setting step to a non-integer value, the spinner type() should be changed to floating point.
Definition at line 204 of file Fl_Spinner.H.
Referenced by Fl_Widget_Type::copy_properties(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
void Fl_Spinner::step (double s) [inline]
See double Fl_Spinner::step() const
Definition at line 206 of file Fl_Spinner.H.
References FL_FLOAT_INPUT, and FL_INT_INPUT.
void Fl_Spinner::textcolor (Fl_Color c) [inline]
Sets the color of the text in the input field.
Definition at line 217 of file Fl_Spinner.H.
Fl_Color Fl_Spinner::textcolor () const [inline]
Gets the color of the text in the input field.
Definition at line 213 of file Fl_Spinner.H.
Fl_Font Fl_Spinner::textfont () const [inline]
Gets the font of the text in the input field.
Definition at line 221 of file Fl_Spinner.H.
Referenced by Fl_Spinner_Type::ideal_size().
void Fl_Spinner::textfont (Fl_Font f) [inline]
Sets the font of the text in the input field.
Definition at line 225 of file Fl_Spinner.H.
void Fl_Spinner::textsize (Fl_Fontsize s) [inline]
Sets the size of the text in the input field.
Definition at line 233 of file Fl_Spinner.H.
Fl_Fontsize Fl_Spinner::textsize () const [inline]
Gets the size of the text in the input field.
Definition at line 229 of file Fl_Spinner.H.
Referenced by Fl_Spinner_Type::ideal_size().
void Fl_Spinner::type (uchar v) [inline]
See uchar Fl_Spinner::type() const
Reimplemented from Fl_Widget.
Definition at line 244 of file Fl_Spinner.H.
References FL_FLOAT_INPUT.
uchar Fl_Spinner::type () const [inline]
Sets or Gets the numeric representation in the input field. Valid values are FL_INT_INPUT and FL_FLOAT_INPUT. The first form also changes the format() template. Setting a new spinner type via a superclass pointer will not work.
Note:
type is not a virtual function.
Reimplemented from Fl_Widget.
Definition at line 242 of file Fl_Spinner.H.
Referenced by Fl_Widget_Type::write_widget_code().
void Fl_Spinner::value (double v) [inline]
Sets the current value of the widget. Before setting value to a non-integer value, the spinner type() should be changed to floating point.
Definition at line 259 of file Fl_Spinner.H.
double Fl_Spinner::value () const [inline]
Gets the current value of the widget.
Definition at line 253 of file Fl_Spinner.H.
Referenced by Fl_Widget_Type::copy_properties(), make_settings_window(), print_cb(), Fl_PostScript_Printer::start_job(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/FL/Fl_Spinner.H