SfR Fresh Dox - fltk: Fl_DeclBlock_Type Class Reference
Fl_DeclBlock_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_DeclBlock_Type ()
~Fl_DeclBlock_Type ()
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void open ()
virtual const char * type_name ()
void write_properties ()
void read_property (const char *)
int is_parent () const
int is_decl_block () const
virtual int is_public () const
int pixmapID ()
Detailed Description
Definition at line 259 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_DeclBlock_Type::Fl_DeclBlock_Type () [inline]
Definition at line 263 of file Fl_Type.h.
Fl_DeclBlock_Type::~Fl_DeclBlock_Type () [inline]
Definition at line 264 of file Fl_Type.h.
Member Function Documentation
int Fl_DeclBlock_Type::is_decl_block () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 275 of file Fl_Type.h.
int Fl_DeclBlock_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 274 of file Fl_Type.h.
int Fl_DeclBlock_Type::is_public () const [virtual]
Reimplemented from Fl_Type.
Definition at line 946 of file Fl_Function_Type.cxx.
Fl_Type * Fl_DeclBlock_Type::make () [virtual]
Implements Fl_Type.
Definition at line 948 of file Fl_Function_Type.cxx.
References Fl_Type::current, Fl_Type::is_decl_block(), Fl_Type::name(), and Fl_Type::parent.
void Fl_DeclBlock_Type::open () [virtual]
Reimplemented from Fl_Type.
Definition at line 982 of file Fl_Function_Type.cxx.
References c_check(), decl_after_input, decl_before_input, declblock_panel, declblock_panel_cancel, declblock_panel_ok, declblock_public_choice, fl_alert(), Fl_Double_Window::hide(), make_declblock_panel(), Fl_Type::name(), Fl::readqueue(), redraw_browser(), set_modflag(), Fl_Double_Window::show(), Fl_Input_::static_value(), storestring(), Fl_Input_::value(), Fl_Choice::value(), w, and Fl::wait().
int Fl_DeclBlock_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 277 of file Fl_Type.h.
void Fl_DeclBlock_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Type.
Definition at line 970 of file Fl_Function_Type.cxx.
References read_word(), and storestring().
virtual const char* Fl_DeclBlock_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 271 of file Fl_Type.h.
void Fl_DeclBlock_Type::write_code1 () [virtual]
Reimplemented from Fl_Type.
Definition at line 1020 of file Fl_Function_Type.cxx.
References Fl_Type::name(), write_c(), and write_h().
void Fl_DeclBlock_Type::write_code2 () [virtual]
Reimplemented from Fl_Type.
Definition at line 1027 of file Fl_Function_Type.cxx.
References write_c(), and write_h().
void Fl_DeclBlock_Type::write_properties () [virtual]
Reimplemented from Fl_Type.
Definition at line 960 of file Fl_Function_Type.cxx.
References write_string(), and write_word().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx