SfR Fresh Dox - fltk: Fl_Menu_Type Class Reference
Fl_Menu_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
int is_menu_button () const
int is_parent () const
virtual void build_menu ()
Fl_Menu_Type ()
~Fl_Menu_Type ()
void add_child (Fl_Type *, Fl_Type *)
void move_child (Fl_Type *, Fl_Type *)
void remove_child (Fl_Type *)
Fl_Type * click_test (int x, int y)
void write_code2 ()
void copy_properties ()
Public Attributes
int menusize
Detailed Description
Definition at line 667 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_Menu_Type::Fl_Menu_Type () [inline]
Definition at line 684 of file Fl_Type.h.
References menusize.
Fl_Menu_Type::~Fl_Menu_Type () [inline]
Definition at line 685 of file Fl_Type.h.
References menusize, and Fl_Widget_Type::o.
Member Function Documentation
void Fl_Menu_Type::add_child (Fl_Type * , Fl_Type *) [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 688 of file Fl_Type.h.
References build_menu().
void Fl_Menu_Type::build_menu () [virtual]
Reimplemented in Fl_Input_Choice_Type.
Definition at line 395 of file Fl_Menu_Type.cxx.
References Fl_Menu_Item::callback(), FL_SUBMENU, Fl_Menu_Item::flags, i, Fl_Widget::image(), Fl_Type::is_menu_item(), Fl_Type::is_parent(), Fl_Widget::label(), Fl_Menu_Item::label(), Fl_Image::label(), Fl_Menu_Item::labelcolor(), Fl_Menu_Item::labelfont(), Fl_Menu_Item::labelsize(), Fl_Widget::labeltype(), Fl_Menu_Item::labeltype(), Fl_Type::level, m, Fl_Menu_::menu(), menusize, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::redraw(), Fl_Menu_Item::shortcut(), and w.
Referenced by add_child(), click_test(), move_child(), and remove_child().
Fl_Type * Fl_Menu_Type::click_test (int x, int y) [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Input_Choice_Type.
Definition at line 442 of file Fl_Menu_Type.cxx.
References build_menu(), FL_MENU_RADIO, FL_MENU_TOGGLE, FL_PUSH, Fl_Menu_Item::flags, Fl_Widget::handle(), m, menusize, Fl_Menu_::mvalue(), Fl_Widget_Type::o, Fl::pushed(), Fl_Type::selected, Fl_Menu_Item::user_data(), Fl_Menu_::value(), and w.
void Fl_Menu_Type::copy_properties () [virtual]
copy all properties from the edit widget to the live widget
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Input_Choice_Type.
Definition at line 497 of file Fl_Menu_Type.cxx.
References Fl_Menu_::down_box(), Fl_Widget_Type::live_widget, Fl_Menu_::menu(), Fl_Widget_Type::o, Fl_Menu_::textcolor(), Fl_Menu_::textfont(), and Fl_Menu_::textsize().
int Fl_Menu_Type::is_menu_button () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 680 of file Fl_Type.h.
int Fl_Menu_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 681 of file Fl_Type.h.
void Fl_Menu_Type::move_child (Fl_Type * , Fl_Type *) [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 689 of file Fl_Type.h.
References build_menu().
void Fl_Menu_Type::remove_child (Fl_Type *) [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 690 of file Fl_Type.h.
References build_menu().
void Fl_Menu_Type::write_code2 () [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 460 of file Fl_Menu_Type.cxx.
References i, indent(), Fl_Type::is_menu_item(), Fl_Type::label(), Fl_Menu_Item_Type::menu_name(), Fl_Type::msgnum(), Fl_Type::name(), Fl_Type::next, unique_id(), and write_c().
Member Data Documentation
int Fl_Menu_Type::menusize
Definition at line 682 of file Fl_Type.h.
Referenced by build_menu(), Fl_Input_Choice_Type::build_menu(), Fl_Input_Choice_Type::click_test(), click_test(), Fl_Menu_Type(), and ~Fl_Menu_Type().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Menu_Type.cxx