SfR Fresh Dox - fltk: Fl_Table Class Reference
Fl_Table Class Reference
#include <Fl_Table.H>
Classes
class IntVector
Public Types
enum TableContext {
CONTEXT_NONE = 0, CONTEXT_STARTPAGE = 0x01, CONTEXT_ENDPAGE = 0x02, CONTEXT_ROW_HEADER = 0x04,
CONTEXT_COL_HEADER = 0x08, CONTEXT_CELL = 0x10, CONTEXT_TABLE = 0x20, CONTEXT_RC_RESIZE = 0x40
}
Public Member Functions
Fl_Table (int X, int Y, int W, int H, const char *l=0)
~Fl_Table ()
virtual void clear ()
void table_box (Fl_Boxtype val)
Fl_Boxtype table_box (void)
virtual void rows (int val)
int rows ()
virtual void cols (int val)
int cols ()
void visible_cells (int &r1, int &r2, int &c1, int &c2)
int is_interactive_resize ()
int row_resize ()
void row_resize (int flag)
int col_resize ()
void col_resize (int flag)
int col_resize_min ()
void col_resize_min (int val)
int row_resize_min ()
void row_resize_min (int val)
int row_header ()
void row_header (int flag)
int col_header ()
void col_header (int flag)
void col_header_height (int height)
int col_header_height ()
void row_header_width (int width)
int row_header_width ()
void row_header_color (Fl_Color val)
Fl_Color row_header_color ()
void col_header_color (Fl_Color val)
Fl_Color col_header_color ()
void row_height (int row, int height)
int row_height (int row)
void col_width (int col, int width)
int col_width (int col)
void row_height_all (int height)
void col_width_all (int width)
void row_position (int row)
void col_position (int col)
int row_position ()
int col_position ()
void top_row (int row)
int top_row ()
int is_selected (int r, int c)
void get_selection (int &row_top, int &col_left, int &row_bot, int &col_right)
void set_selection (int row_top, int col_left, int row_bot, int col_right)
int move_cursor (int R, int C)
void resize (int X, int Y, int W, int H)
void draw (void)
void init_sizes ()
void add (Fl_Widget &w)
void add (Fl_Widget *w)
void insert (Fl_Widget &w, int n)
void insert (Fl_Widget &w, Fl_Widget *w2)
void remove (Fl_Widget &w)
void begin ()
void end ()
Fl_Widget *const array ()
Fl_Widget * child (int n) const
int children () const
int find (const Fl_Widget *w) const
int find (const Fl_Widget &w) const
int callback_row ()
int callback_col ()
TableContext callback_context ()
void do_callback (TableContext context, int row, int col)
Protected Types
enum ResizeFlag {
RESIZE_NONE = 0, RESIZE_COL_LEFT = 1, RESIZE_COL_RIGHT = 2, RESIZE_ROW_ABOVE = 3,
RESIZE_ROW_BELOW = 4
}
Protected Member Functions
int handle (int e)
void recalc_dimensions ()
void table_resized ()
void table_scrolled ()
void get_bounds (TableContext context, int &X, int &Y, int &W, int &H)
void change_cursor (Fl_Cursor newcursor)
TableContext cursor2rowcol (int &R, int &C, ResizeFlag &resizeflag)
int find_cell (TableContext context, int R, int C, int &X, int &Y, int &W, int &H)
int row_col_clamp (TableContext context, int &R, int &C)
virtual void draw_cell (TableContext context, int R=0, int C=0, int X=0, int Y=0, int W=0, int H=0)
long row_scroll_position (int row)
long col_scroll_position (int col)
int is_fltk_container ()
void damage_zone (int r1, int c1, int r2, int c2, int r3=0, int c3=0)
void redraw_range (int toprow, int botrow, int leftcol, int rightcol)
Static Protected Member Functions
static void scroll_cb (Fl_Widget *, void *)
Protected Attributes
int table_w
int table_h
int toprow
int botrow
int leftcol
int rightcol
int current_row
int current_col
int select_row
int select_col
int toprow_scrollpos
int leftcol_scrollpos
int tix
int tiy
int tiw
int tih
int tox
int toy
int tow
int toh
int wix
int wiy
int wiw
int wih
Fl_Scroll * table
Fl_Scrollbar * vscrollbar
Fl_Scrollbar * hscrollbar
Detailed Description
A table of widgets or other content.
This is the base class for table widgets.
To be useful it must be subclassed and several virtual functions defined. Normally applications use widgets derived from this widget, and do not use this widget directly; this widget is usually too low level to be used directly by applications.
This widget does not handle the data in the table. The draw_cell() method must be overridden by a subclass to manage drawing the contents of the cells.
This widget can be used in several ways:
As a custom widget; see examples/table-simple.cxx and test/table.cxx. Very optimal for even extremely large tables.
As a table made up of a single FLTK widget instanced all over the table, simulating a numeric spreadsheet. See examples/table-spreadsheet.cxx and examples/table-spreadsheet-with-keyboard-nav.cxx. Optimal for large tables.
As a regular container of FLTK widgets, one widget per cell. See examples/table-as-container.cxx. Not recommended for large tables.
When acting as part of a custom widget, events on the cells and/or headings generate callbacks when they are clicked by the user. You control when events are generated based on the setting for Fl_Table::when().
When acting as a container for FLTK widgets, the FLTK widgets maintain themselves. Although the draw_cell() method must be overridden, its contents can be very simple. See the draw_cell() code in examples/table-simple.cxx.
The following variables are available to classes deriving from Fl_Table:
x()/y()/w()/h()
Fl_Table widget's outer dimension. The outer edge of the border of the Fl_Table. (Red in the diagram above)
wix/wiy/wiw/wih
Fl_Table widget's inner dimension. The inner edge of the border of the Fl_Table. eg. if the Fl_Table's box() is FL_NO_BOX, these values are the same as x()/y()/w()/h(). (Yellow in the diagram above)
tox/toy/tow/toh
The table's outer dimension. The outer edge of the border around the cells, but inside the row/col headings and scrollbars. (Green in the diagram above)
tix/tiy/tiw/tih The table's inner dimension. The inner edge of the border around the cells, but inside the row/col headings and scrollbars. AKA the table's clip region. eg. if the table_box() is FL_NO_BOX, these values are the same as tox/toyy/tow/toh. (Blue in the diagram above)
CORE DEVELOPERS
Greg Ercolano : 12/16/2002 - initial implementation 12/16/02. Fl_Table, Fl_Table_Row, docs.
Jean-Marc Lienher : 02/22/2004 - added keyboard nav + mouse selection, and ported Fl_Table into fltk-utf8-1.1.4
OTHER CONTRIBUTORS
Inspired by the Feb 2000 version of FLVW's Flvw_Table widget. Mucho thanks to those folks.
Mister Satan : 04/07/2003 - MinGW porting mods, and singleinput.cxx; a cool Fl_Input oriented spreadsheet example
Marek Paliwoda : 01/08/2003 - Porting mods for Borland
Ori Berger : 03/16/2006 - Optimizations for >500k rows/cols
LICENSE
Greg added the following license to the original distribution of Fl_Table. He kindly gave his permission to integrate Fl_Table and Fl_Table_Row into FLTK, allowing FLTK license to apply while his widgets are part of the library.
If used on its own, this is the license that applies:
 Fl_Table License
 December 16, 2002
 The Fl_Table library and included programs are provided under the terms
 of the GNU Library General Public License (LGPL) with the following
 exceptions:
 1. Modifications to the Fl_Table configure script, config
 header file, and makefiles by themselves to support
 a specific platform do not constitute a modified or
 derivative work.
 The authors do request that such modifications be
 contributed to the Fl_Table project - send all
 contributions to "erco at seriss dot com".
 2. Widgets that are subclassed from Fl_Table widgets do not
 constitute a derivative work.
 3. Static linking of applications and widgets to the
 Fl_Table library does not constitute a derivative work
 and does not require the author to provide source
 code for the application or widget, use the shared
 Fl_Table libraries, or link their applications or
 widgets against a user-supplied version of Fl_Table.
 If you link the application or widget to a modified
 version of Fl_Table, then the changes to Fl_Table must be
 provided under the terms of the LGPL in sections
 1, 2, and 4.
 4. You do not have to provide a copy of the Fl_Table license
 with programs that are linked to the Fl_Table library, nor
 do you have to identify the Fl_Table license in your
 program or documentation as required by section 6
 of the LGPL.
 However, programs must still identify their use of Fl_Table.
 The following example statement can be included in user
 documentation to satisfy this requirement:
 [program/widget] is based in part on the work of
 the Fl_Table project http://seriss.com/people/erco/fltk/Fl_Table/
Definition at line 181 of file Fl_Table.H.
Member Enumeration Documentation
enum Fl_Table::ResizeFlag [protected]
Enumerator:
RESIZE_NONE
RESIZE_COL_LEFT
RESIZE_COL_RIGHT
RESIZE_ROW_ABOVE
RESIZE_ROW_BELOW
Definition at line 285 of file Fl_Table.H.
enum Fl_Table::TableContext
The context bit flags for Fl_Table related callbacks (eg. draw_cell(), callback(), etc)
Enumerator:
CONTEXT_NONE
no known context
CONTEXT_STARTPAGE
before a page is redrawn
CONTEXT_ENDPAGE
after a page is redrawn
CONTEXT_ROW_HEADER
in the row header
CONTEXT_COL_HEADER
in the col header
CONTEXT_CELL
in one of the cells
CONTEXT_TABLE
in a dead zone of table
CONTEXT_RC_RESIZE
column or row being resized
Definition at line 186 of file Fl_Table.H.
Constructor & Destructor Documentation
Fl_Table::Fl_Table (int X, int Y, int W, int H, const char * l = 0)
The constructor for the Fl_Table. This creates an empty table with no rows or columns, with headers and row/column resize behavior disabled.
Definition at line 102 of file Fl_Table.cxx.
References Fl_Group::begin(), botrow, Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), current_col, current_row, end(), Fl_Group::end(), FL_CURSOR_DEFAULT, FL_HORIZONTAL, FL_NO_BOX, FL_THIN_DOWN_FRAME, FL_VERTICAL, Fl_Widget::h(), Fl_Widget::hide(), hscrollbar, leftcol, leftcol_scrollpos, Fl_Widget::redraw(), rightcol, scroll_cb(), SCROLLBAR_SIZE, select_col, select_row, table, table_h, table_resized(), table_w, toprow, toprow_scrollpos, Fl_Widget::type(), vscrollbar, Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
Fl_Table::~Fl_Table ()
The destructor for the Fl_Table. Destroys the table and its associated widgets.
Definition at line 166 of file Fl_Table.cxx.
Member Function Documentation
void Fl_Table::add (Fl_Widget & o) [inline]
The widget is removed from its current group (if any) and then added to the end of this group.
Reimplemented from Fl_Group.
Definition at line 858 of file Fl_Table.H.
void Fl_Table::add (Fl_Widget * o) [inline]
See void Fl_Group::add(Fl_Widget &w)
Reimplemented from Fl_Group.
Definition at line 861 of file Fl_Table.H.
Fl_Widget* const Fl_Table::array () [inline]
Definition at line 888 of file Fl_Table.H.
void Fl_Table::begin () [inline]
Sets the current group so you can build the widget tree by just constructing the widgets.
begin() is automatically called by the constructor for Fl_Group (and thus for Fl_Window as well). begin() is exactly the same as current(this). Don't forget to end() the group or window!
Reimplemented from Fl_Group.
Definition at line 873 of file Fl_Table.H.
int Fl_Table::callback_col () [inline]
Returns the current column the event occurred on.
This function should only be used from within the user's callback function
Definition at line 943 of file Fl_Table.H.
TableContext Fl_Table::callback_context () [inline]
Returns the current 'table context'.
This function should only be used from within the user's callback function
Definition at line 952 of file Fl_Table.H.
int Fl_Table::callback_row () [inline]
Returns the current row the event occurred on.
This function should only be used from within the user's callback function
Definition at line 934 of file Fl_Table.H.
void Fl_Table::change_cursor (Fl_Cursor newcursor) [protected]
Definition at line 635 of file Fl_Table.cxx.
References FL_BLACK, fl_cursor(), and FL_WHITE.
Referenced by handle().
Fl_Widget* Fl_Table::child (int n) const [inline]
Returns the child widget by an index.
When using the Fl_Table as a container for FLTK widgets, this method returns the widget pointer from the internal array of widgets in the container.
Typically used in loops, eg:
   for ( int i=0; i<children(); i++ ) {
     Fl_Widget *w = child(i);
     [..]
   }
Reimplemented from Fl_Group.
Definition at line 906 of file Fl_Table.H.
int Fl_Table::children () const [inline]
Returns the number of children in the table.
When using the Fl_Table as a container for FLTK widgets, this method returns how many child widgets the table has.
See also:
child(int)
Reimplemented from Fl_Group.
Definition at line 918 of file Fl_Table.H.
virtual void Fl_Table::clear () [inline, virtual]
Clears the table to zero rows, zero columns. Same as rows(0); cols(0);
See also:
rows(int), cols(int)
Reimplemented from Fl_Group.
Reimplemented in Fl_Table_Row.
Definition at line 493 of file Fl_Table.H.
int Fl_Table::col_header () [inline]
Returns if column headers are enabled or not.
Definition at line 666 of file Fl_Table.H.
Referenced by cursor2rowcol(), draw(), Fluid_Table::Fluid_Table(), and recalc_dimensions().
void Fl_Table::col_header (int flag) [inline]
Enable or disable column headers. If changed, the table is redrawn.
Definition at line 674 of file Fl_Table.H.
References flag, and Fl_Widget::redraw().
void Fl_Table::col_header_color (Fl_Color val) [inline]
Sets the color for column headers and redraws the table.
Definition at line 730 of file Fl_Table.H.
References Fl_Widget::redraw(), and val.
Fl_Color Fl_Table::col_header_color () [inline]
Gets the color for column headers.
Definition at line 738 of file Fl_Table.H.
void Fl_Table::col_header_height (int height) [inline]
Sets the height in pixels for column headers and redraws the table.
Definition at line 683 of file Fl_Table.H.
References height, and Fl_Widget::redraw().
int Fl_Table::col_header_height () [inline]
Gets the column header height.
Definition at line 692 of file Fl_Table.H.
Referenced by draw(), find_cell(), get_bounds(), handle(), and recalc_dimensions().
void Fl_Table::col_position (int col)
Sets the column scroll position to column 'col', and causes the screen to redraw.
Definition at line 52 of file Fl_Table.cxx.
References col_scroll_position(), cols(), hscrollbar, Fl_Valuator::maximum(), Fl_Widget::redraw(), table_scrolled(), table_w, and tiw.
int Fl_Table::col_position () [inline]
Returns the current column scroll position as a column number.
Definition at line 811 of file Fl_Table.H.
Referenced by move_cursor().
int Fl_Table::col_resize () [inline]
Returns the current value of this flag.
Definition at line 601 of file Fl_Table.H.
Referenced by cursor2rowcol(), and Fluid_Table::Fluid_Table().
void Fl_Table::col_resize (int flag) [inline]
Allows/disallows column resizing by the user. 1=allow interactive resizing, 0=disallow interactive resizing. Since interactive resizing is done via the column headers, col_header() must also be enabled to allow resizing.
Definition at line 610 of file Fl_Table.H.
References flag.
int Fl_Table::col_resize_min () [inline]
Sets the current column minimum resize value. This is used to prevent the user from interactively resizing any column to be smaller than 'pixels'. Must be a value >=1.
Definition at line 619 of file Fl_Table.H.
void Fl_Table::col_resize_min (int val) [inline]
Returns the current column minimum resize value.
Definition at line 626 of file Fl_Table.H.
long Fl_Table::col_scroll_position (int col) [protected]
Definition at line 85 of file Fl_Table.cxx.
References col_width(), leftcol, and leftcol_scrollpos.
Referenced by col_position(), find_cell(), and table_resized().
int Fl_Table::col_width (int col) [inline]
Returns the current width of the specified column in pixels.
Definition at line 767 of file Fl_Table.H.
void Fl_Table::col_width (int col, int width)
Sets the width of the specified column in pixels, and the table is redrawn. callback() will be invoked with CONTEXT_RC_RESIZE if the column's width was actually changed, and when() is FL_WHEN_CHANGED.
Definition at line 195 of file Fl_Table.cxx.
References Fl_Widget::callback(), CONTEXT_RC_RESIZE, Fl_Widget::do_callback(), FL_WHEN_CHANGED, int, Fl_Widget::redraw(), rightcol, table_resized(), Fl_Widget::when(), and width.
Referenced by col_scroll_position(), find_cell(), handle(), and table_scrolled().
void Fl_Table::col_width_all (int width) [inline]
Convenience method to set the width of all columns to the same value, in pixels. The screen is redrawn.
Definition at line 785 of file Fl_Table.H.
Referenced by Fluid_Table::Fluid_Table().
void Fl_Table::cols (int val) [virtual]
Set the number of columns in the table and redraw.
Definition at line 620 of file Fl_Table.cxx.
References Fl_Widget::redraw(), table_resized(), and val.
int Fl_Table::cols () [inline]
Get the number of columns in the table.
Definition at line 534 of file Fl_Table.H.
Referenced by col_position(), Fluid_Table::Fluid_Table(), handle(), move_cursor(), and table_resized().
Fl_Table::TableContext Fl_Table::cursor2rowcol (int & R, int & C, ResizeFlag & resizeflag) [protected]
Definition at line 283 of file Fl_Table.cxx.
References botrow, col_header(), col_resize(), CONTEXT_CELL, CONTEXT_COL_HEADER, CONTEXT_NONE, CONTEXT_ROW_HEADER, CONTEXT_TABLE, Fl::event_inside(), Fl::event_x(), Fl::event_y(), find_cell(), get_bounds(), H, leftcol, RESIZE_COL_LEFT, RESIZE_COL_RIGHT, RESIZE_NONE, RESIZE_ROW_ABOVE, RESIZE_ROW_BELOW, rightcol, row_header(), row_resize(), toh, toprow, tow, tox, and toy.
Referenced by Fl_Table_Row::handle(), and handle().
void Fl_Table::damage_zone (int r1, int c1, int r2, int c2, int r3 = 0, int c3 = 0) [protected]
Definition at line 642 of file Fl_Table.cxx.
References botrow, leftcol, redraw_range(), rightcol, and toprow.
Referenced by handle(), move_cursor(), and set_selection().
void Fl_Table::do_callback (TableContext context, int row, int col) [inline]
Definition at line 956 of file Fl_Table.H.
References Fl_Widget::do_callback(), and row.
void Fl_Table::draw (void) [virtual]
Draws the widget. Never call this function directly. FLTK will schedule redrawing whenever needed. If your widget must be redrawn as soon as possible, call redraw() instead.
Override this function to draw your own widgets.
If you ever need to call another widget's draw method from within your own draw() method, e.g. for an embedded scrollbar, you can do it (because draw() is virtual) like this:
        Fl_Widget *s = &scroll;         // scroll is an embedded Fl_Scrollbar
        s->draw();                      // calls Fl_Scrollbar::draw()
Reimplemented from Fl_Group.
Definition at line 1119 of file Fl_Table.cxx.
References botrow, Fl_Widget::box(), Fl::box_dw(), Fl::box_dx(), col_header(), col_header_height(), Fl_Widget::color(), CONTEXT_CELL, CONTEXT_COL_HEADER, CONTEXT_ENDPAGE, CONTEXT_ROW_HEADER, CONTEXT_STARTPAGE, Fl_Widget::damage(), Fl_Widget::draw_box(), draw_cell(), FL_DAMAGE_ALL, FL_DAMAGE_CHILD, fl_pop_clip(), fl_push_clip(), fl_rectf(), get_bounds(), H, Fl_Widget::h(), hscrollbar, leftcol, rightcol, row_header(), row_header_width(), SCROLLBAR_SIZE, table, table_h, table_w, tih, tiw, tix, tiy, toh, toprow, tow, tox, toy, Fl_Widget::visible(), vscrollbar, Fl_Widget::w(), wih, wiw, wix, wiy, Fl_Widget::x(), and Fl_Widget::y().
virtual void Fl_Table::draw_cell (TableContext context, int R = 0, int C = 0, int X = 0, int Y = 0, int W = 0, int H = 0) [inline, protected, virtual]
Subclass should override this method to handle drawing the cells.
This method will be called whenever the table is redrawn, once per cell.
Only cells that are completely (or partially) visible will be told to draw.
context will be one of the following:
Fl_Table::CONTEXT_STARTPAGE
When table, or parts of the table, are about to be redrawn.
Use to initialize static data, such as font selections.
R/C will be zero,
X/Y/W/H will be the dimensions of the table's entire data area.
(Useful for locking a database before accessing; see also visible_cells())
Fl_Table::CONTEXT_ENDPAGE When table has completed being redrawn.
R/C will be zero, X/Y/W/H dimensions of table's data area.
(Useful for unlocking a database after accessing)
Fl_Table::CONTEXT_ROW_HEADER Whenever a row header cell needs to be drawn.
R will be the row number of the header being redrawn,
C will be zero,
X/Y/W/H will be the fltk drawing area of the row header in the window
Fl_Table::CONTEXT_COL_HEADER Whenever a column header cell needs to be drawn.
R will be zero,
C will be the column number of the header being redrawn,
X/Y/W/H will be the fltk drawing area of the column header in the window
Fl_Table::CONTEXT_CELL Whenever a data cell in the table needs to be drawn.
R/C will be the row/column of the cell to be drawn,
X/Y/W/H will be the fltk drawing area of the cell in the window
Fl_Table::CONTEXT_RC_RESIZE
Whenever table or row/column is resized or scrolled, either interactively or via col_width() or row_height().
R/C/X/Y/W/H will all be zero.
Useful for fltk containers that need to resize or move the child fltk widgets.
row and col will be set to the row and column number of the cell being drawn. In the case of row headers, col will be 0. In the case of column headers, row will be 0.
x/y/w/h will be the position and dimensions of where the cell should be drawn.
In the case of custom widgets, a minimal draw_cell() override might look like the following. With custom widgets it is up to the caller to handle drawing everything within the dimensions of the cell, including handling the selection color. Note all clipping must be handled as well; this allows drawing outside the dimensions of the cell if so desired for 'custom effects'.
   // This is called whenever Fl_Table wants you to draw a cell
   void MyTable::draw_cell(TableContext context, int R=0, int C=0, int X=0, int Y=0, int W=0, int H=0) {
       static char s[40];
       sprintf(s, "%d/%d", R, C);              // text for each cell
       switch ( context ) {
           case CONTEXT_STARTPAGE:             // Fl_Table telling us its starting to draw page
               fl_font(FL_HELVETICA, 16);
               return;
           case CONTEXT_ROW_HEADER:            // Fl_Table telling us it's draw row/col headers
           case CONTEXT_COL_HEADER:
               fl_push_clip(X, Y, W, H);
               {
                   fl_draw_box(FL_THIN_UP_BOX, X, Y, W, H, color());
                   fl_color(FL_BLACK);
                   fl_draw(s, X, Y, W, H, FL_ALIGN_CENTER);
               }
               fl_pop_clip();
               return;
           case CONTEXT_CELL:                  // Fl_Table telling us to draw cells
               fl_push_clip(X, Y, W, H);
               {
                   // BG COLOR
                   fl_color( row_selected(R) ? selection_color() : FL_WHITE);
                   fl_rectf(X, Y, W, H);
                   // TEXT
                   fl_color(FL_BLACK);
                   fl_draw(s, X, Y, W, H, FL_ALIGN_CENTER);
                   // BORDER
                   fl_color(FL_LIGHT2);
                   fl_rect(X, Y, W, H);
               }
               fl_pop_clip();
               return;
       default:
           return;
       }
       //NOTREACHED
   }
Definition at line 440 of file Fl_Table.H.
Referenced by draw(), and table_scrolled().
void Fl_Table::end () [inline]
Exactly the same as current(this->parent()). Any new widgets added to the widget tree will be added to the parent of the group.
Reimplemented from Fl_Group.
Definition at line 876 of file Fl_Table.H.
References Fl_Group::current(), and Fl_Widget::parent().
Referenced by Fl_Table().
int Fl_Table::find (const Fl_Widget * o) const [inline]
Searches the child array for the widget and returns the index. Returns children() if the widget is NULL or not found.
Reimplemented from Fl_Group.
Definition at line 921 of file Fl_Table.H.
int Fl_Table::find (const Fl_Widget & o) const [inline]
See int Fl_Group::find(const Fl_Widget *w) const
Reimplemented from Fl_Group.
Definition at line 924 of file Fl_Table.H.
int Fl_Table::find_cell (TableContext context, int R, int C, int & X, int & Y, int & W, int & H) [protected]
Reimplemented in Fl_Table_Row.
Definition at line 363 of file Fl_Table.cxx.
References col_header_height(), col_scroll_position(), col_width(), CONTEXT_CELL, CONTEXT_COL_HEADER, CONTEXT_ROW_HEADER, CONTEXT_TABLE, hscrollbar, row_col_clamp(), row_header_width(), row_height(), row_scroll_position(), tix, tiy, Fl_Scrollbar::value(), vscrollbar, wix, and wiy.
Referenced by cursor2rowcol(), and Fl_Table_Row::find_cell().
void Fl_Table::get_bounds (TableContext context, int & X, int & Y, int & W, int & H) [protected]
Definition at line 247 of file Fl_Table.cxx.
References col_header_height(), CONTEXT_COL_HEADER, CONTEXT_ROW_HEADER, CONTEXT_TABLE, row_header_width(), tih, tiw, tix, tiy, toh, tow, tox, toy, wix, and wiy.
Referenced by cursor2rowcol(), and draw().
void Fl_Table::get_selection (int & row_top, int & col_left, int & row_bot, int & col_right)
Gets the region of cells selected (highlighted).
Parameters:
[in] row_top Returns the top row of selection area
[in] col_left Returns the left column of selection area
[in] row_bot Returns the bottom row of selection area
[in] col_right Returns the right column of selection area
Definition at line 1078 of file Fl_Table.cxx.
References current_col, current_row, select_col, and select_row.
int Fl_Table::handle (int event) [protected, virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Group.
Reimplemented in Fl_Table_Row.
Definition at line 700 of file Fl_Table.cxx.
References botrow, Fl_Widget::callback(), change_cursor(), col_header_height(), col_width(), cols(), Fl_Widget::contains(), CONTEXT_CELL, CONTEXT_COL_HEADER, CONTEXT_NONE, CONTEXT_RC_RESIZE, CONTEXT_ROW_HEADER, CONTEXT_TABLE, current_col, current_row, cursor2rowcol(), damage_zone(), Fl_Widget::do_callback(), Fl::event_button(), Fl::event_clicks(), Fl::event_inside(), Fl::event_key(), Fl::event_state(), Fl::event_x(), Fl::event_y(), FL_CURSOR_DEFAULT, FL_CURSOR_NS, FL_CURSOR_WE, FL_Down, FL_DRAG, FL_End, FL_ENTER, FL_FOCUS, FL_Home, FL_KEYBOARD, FL_LEAVE, FL_Left, FL_MOVE, FL_Page_Down, FL_Page_Up, FL_PUSH, FL_RELEASE, FL_Right, FL_SHIFT, FL_Tab, FL_UNFOCUS, FL_Up, FL_WHEN_CHANGED, FL_WHEN_NOT_CHANGED, FL_WHEN_RELEASE, Fl_Group::focus(), Fl::focus(), Fl_Widget::h(), hscrollbar, move_cursor(), PRINTEVENT, Fl_Widget::redraw(), RESIZE_COL_LEFT, RESIZE_NONE, RESIZE_ROW_ABOVE, row_header_width(), row_height(), rows(), select_col, select_row, table_resized(), Fl_Widget::take_focus(), toprow, vscrollbar, Fl_Widget::w(), Fl_Widget::when(), Fl_Widget::x(), and Fl_Widget::y().
void Fl_Table::init_sizes () [inline]
Resets the internal array of widget sizes and positions.
The Fl_Group widget keeps track of the original widget sizes and positions when resizing occurs so that if you resize a window back to its original size the widgets will be in the correct places. If you rearrange the widgets in your group, call this method to register the new arrangement with the Fl_Group that contains them.
If you add or remove widgets, this will be done automatically.
Note:
The internal array of widget sizes and positions will be allocated and filled when the next resize() occurs.
See also:
sizes()
Reimplemented from Fl_Group.
Definition at line 854 of file Fl_Table.H.
Referenced by table_resized().
void Fl_Table::insert (Fl_Widget & o, int index) [inline]
The widget is removed from its current group (if any) and then inserted into this group. It is put at index n - or at the end, if n >= children(). This can also be used to rearrange the widgets inside a group.
Reimplemented from Fl_Group.
Definition at line 864 of file Fl_Table.H.
void Fl_Table::insert (Fl_Widget & o, Fl_Widget * before) [inline]
This does insert(w, find(before)). This will append the widget if before is not in the group.
Reimplemented from Fl_Group.
Definition at line 867 of file Fl_Table.H.
int Fl_Table::is_fltk_container () [inline, protected]
Definition at line 447 of file Fl_Table.H.
References Fl_Group::children().
int Fl_Table::is_interactive_resize () [inline]
Returns 1 if someone is interactively resizing a row or column. You can currently call this only from within your callback().
Definition at line 577 of file Fl_Table.H.
int Fl_Table::is_selected (int r, int c)
See if the cell at row r and column c is selected.
Returns:
1 if the cell is selected, 0 if not.
Definition at line 1047 of file Fl_Table.cxx.
References current_col, current_row, select_col, and select_row.
int Fl_Table::move_cursor (int R, int C)
Definition at line 668 of file Fl_Table.cxx.
References botrow, col_position(), cols(), current_col, current_row, damage_zone(), Fl::event_state(), FL_SHIFT, rightcol, row_position(), rows(), select_col, and select_row.
Referenced by handle().
void Fl_Table::recalc_dimensions () [protected]
Definition at line 468 of file Fl_Table.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dw(), Fl::box_dx(), Fl::box_dy(), col_header(), col_header_height(), Fl_Widget::h(), Fl_Widget::hide(), hscrollbar, Fl_Group::init_sizes(), Fl_Scroll::resize(), row_header(), row_header_width(), SCROLLBAR_SIZE, Fl_Widget::show(), table, table_h, table_w, tih, tiw, tix, tiy, toh, tow, tox, toy, vscrollbar, Fl_Widget::w(), wih, wiw, wix, wiy, Fl_Widget::x(), and Fl_Widget::y().
Referenced by scroll_cb(), and table_resized().
void Fl_Table::redraw_range (int toprow, int botrow, int leftcol, int rightcol) [inline, protected]
Definition at line 455 of file Fl_Table.H.
References Fl_Widget::damage(), and FL_DAMAGE_CHILD.
Referenced by damage_zone(), and Fl_Table_Row::select_row().
void Fl_Table::remove (Fl_Widget & o) [inline]
Removes a widget from the group but does not delete it.
This method does nothing if the widget is not a child of the group.
This method differs from the clear() method in that it only affects a single widget and does not delete it from memory.
Note:
If you have the child's index anyway, use remove(int index) instead, because this doesn't need a child lookup in the group's table of children. This can be much faster, if there are lots of children.
Reimplemented from Fl_Group.
Definition at line 870 of file Fl_Table.H.
References w.
void Fl_Table::resize (int X, int Y, int W, int H) [virtual]
Changes the size of the Fl_Table, causing it to redraw.
Reimplemented from Fl_Group.
Definition at line 1028 of file Fl_Table.cxx.
References Fl_Widget::redraw(), and table_resized().
int Fl_Table::row_col_clamp (TableContext context, int & R, int & C) [protected]
Definition at line 221 of file Fl_Table.cxx.
References CONTEXT_CELL, CONTEXT_COL_HEADER, and CONTEXT_ROW_HEADER.
Referenced by find_cell().
void Fl_Table::row_header (int flag) [inline]
Enables/disables showing the row headers. 1=enabled, 0=disabled. If changed, the table is redrawn.
Definition at line 657 of file Fl_Table.H.
References flag, and Fl_Widget::redraw().
int Fl_Table::row_header () [inline]
Returns the value of this flag.
Definition at line 649 of file Fl_Table.H.
Referenced by cursor2rowcol(), draw(), Fluid_Table::Fluid_Table(), and recalc_dimensions().
void Fl_Table::row_header_color (Fl_Color val) [inline]
Sets the row header color and causes the screen to redraw.
Definition at line 715 of file Fl_Table.H.
References Fl_Widget::redraw(), and val.
Fl_Color Fl_Table::row_header_color () [inline]
Returns the current row header color.
Definition at line 723 of file Fl_Table.H.
int Fl_Table::row_header_width () [inline]
Returns the current row header width (in pixels).
Definition at line 708 of file Fl_Table.H.
Referenced by draw(), find_cell(), get_bounds(), handle(), and recalc_dimensions().
void Fl_Table::row_header_width (int width) [inline]
Sets the row header width to n and causes the screen to redraw.
Definition at line 699 of file Fl_Table.H.
References Fl_Widget::redraw(), and width.
int Fl_Table::row_height (int row) [inline]
Returns the current height of the specified row as a value in pixels.
Definition at line 753 of file Fl_Table.H.
void Fl_Table::row_height (int row, int height)
Sets the height of the specified row in pixels, and the table is redrawn. callback() will be invoked with CONTEXT_RC_RESIZE if the row's height was actually changed, and when() is FL_WHEN_CHANGED.
Definition at line 171 of file Fl_Table.cxx.
References botrow, Fl_Widget::callback(), CONTEXT_RC_RESIZE, Fl_Widget::do_callback(), FL_WHEN_CHANGED, height, int, Fl_Widget::redraw(), row, table_resized(), and Fl_Widget::when().
Referenced by find_cell(), handle(), row_scroll_position(), and table_scrolled().
void Fl_Table::row_height_all (int height) [inline]
Convenience method to set the height of all rows to the same value, in pixels. The screen is redrawn.
Definition at line 775 of file Fl_Table.H.
Referenced by Fluid_Table::Fluid_Table().
void Fl_Table::row_position (int row)
Sets the row scroll position to 'row', and causes the screen to redraw.
Definition at line 36 of file Fl_Table.cxx.
References Fl_Valuator::maximum(), Fl_Widget::redraw(), row, row_scroll_position(), rows(), table_h, table_scrolled(), tih, and vscrollbar.
int Fl_Table::row_position () [inline]
Returns the current row scroll position as a row number.
Definition at line 804 of file Fl_Table.H.
Referenced by Fl_Table_Row::handle(), and move_cursor().
void Fl_Table::row_resize (int flag) [inline]
Allows/disallows row resizing by the user. 1=allow interactive resizing, 0=disallow interactive resizing. Since interactive resizing is done via the row headers, row_header() must also be enabled to allow resizing.
Definition at line 594 of file Fl_Table.H.
References flag.
int Fl_Table::row_resize () [inline]
Returns the current value of this flag.
Definition at line 584 of file Fl_Table.H.
Referenced by cursor2rowcol(), and Fluid_Table::Fluid_Table().
int Fl_Table::row_resize_min () [inline]
Returns the current row minimum resize value.
Definition at line 633 of file Fl_Table.H.
void Fl_Table::row_resize_min (int val) [inline]
Sets the current row minimum resize value. This is used to prevent the user from interactively resizing any row to be smaller than 'pixels'. Must be a value >=1.
Definition at line 642 of file Fl_Table.H.
long Fl_Table::row_scroll_position (int row) [protected]
Definition at line 68 of file Fl_Table.cxx.
References row, row_height(), toprow, and toprow_scrollpos.
Referenced by find_cell(), row_position(), and table_resized().
void Fl_Table::rows (int val) [virtual]
Sets the number of rows in the table, and the table is redrawn.
Reimplemented in Fl_Table_Row.
Definition at line 598 of file Fl_Table.cxx.
References botrow, Fl_Widget::redraw(), table_resized(), and val.
int Fl_Table::rows () [inline]
Returns the number of rows in the table.
Reimplemented in Fl_Table_Row.
Definition at line 522 of file Fl_Table.H.
Referenced by Fluid_Table::Fluid_Table(), handle(), move_cursor(), row_position(), and table_resized().
void Fl_Table::scroll_cb (Fl_Widget * w, void * data) [static, protected]
Definition at line 590 of file Fl_Table.cxx.
References recalc_dimensions(), Fl_Widget::redraw(), and table_scrolled().
Referenced by Fl_Table().
void Fl_Table::set_selection (int row_top, int col_left, int row_bot, int col_right)
Sets the region of cells to be selected (highlighted).
So for instance, set_selection(0,0,0,0) selects the top/left cell in the table. And set_selection(0,0,1,1) selects the four cells in rows 0 and 1, column 0 and 1.
Parameters:
[in] row_top Top row of selection area
[in] col_left Left column of selection area
[in] row_bot Bottom row of selection area
[in] col_right Right column of selection area
Definition at line 1106 of file Fl_Table.cxx.
References current_col, current_row, damage_zone(), select_col, and select_row.
Fl_Boxtype Fl_Table::table_box (void) [inline]
Returns the current box type used for the data table.
Definition at line 510 of file Fl_Table.H.
void Fl_Table::table_box (Fl_Boxtype val) [inline]
Sets the kind of box drawn around the data table, the default being FL_NO_BOX. Changing this value will cause the table to redraw.
Definition at line 502 of file Fl_Table.H.
void Fl_Table::table_resized () [protected]
Definition at line 550 of file Fl_Table.cxx.
References Fl_Slider::bounds(), Fl_Valuator::clamp(), col_scroll_position(), cols(), hscrollbar, init_sizes(), Fl_Valuator::precision(), recalc_dimensions(), Fl_Widget::resize(), row_scroll_position(), rows(), SCROLLBAR_SIZE, Fl_Slider::slider_size(), table_h, table_scrolled(), table_w, tih, tiw, Fl_Scrollbar::value(), Fl_Widget::visible(), vscrollbar, wih, wiw, wix, and wiy.
Referenced by col_width(), cols(), Fl_Table(), handle(), resize(), row_height(), and rows().
void Fl_Table::table_scrolled () [protected]
Definition at line 508 of file Fl_Table.cxx.
References botrow, col_width(), CONTEXT_RC_RESIZE, draw_cell(), hscrollbar, leftcol, leftcol_scrollpos, rightcol, row, row_height(), tih, tiw, toprow, toprow_scrollpos, Fl_Scrollbar::value(), vscrollbar, Fl_Widget::x(), and Fl_Widget::y().
Referenced by col_position(), row_position(), scroll_cb(), and table_resized().
void Fl_Table::top_row (int row) [inline]
Sets which row should be at the top of the table, scrolling as necessary, and the table is redrawn. If the table cannot be scrolled that far, it is scrolled as far as possible.
Definition at line 820 of file Fl_Table.H.
int Fl_Table::top_row () [inline]
Returns the current top row shown in the table. This row may be partially obscured.
Definition at line 828 of file Fl_Table.H.
void Fl_Table::visible_cells (int & r1, int & r2, int & c1, int & c2) [inline]
Returns the range of row and column numbers for all visible and partially visible cells in the table.
These values can be used e.g. by your draw_cell() routine during CONTEXT_STARTPAGE to figure out what cells are about to be redrawn for the purposes of locking the data from a database before it's drawn.
          leftcol             rightcol
             :                   :
   toprow .. .-------------------.
             |                   |
             |  V I S I B L E    |
             |                   |
             |    T A B L E      |
             |                   |
   botrow .. '-------------------`
e.g. in a table where the visible rows are 5-20, and the visible columns are 100-120, then those variables would be:
toprow = 5
botrow = 20
leftcol = 100
rightcol = 120
Definition at line 566 of file Fl_Table.H.
Member Data Documentation
int Fl_Table::botrow [protected]
Definition at line 294 of file Fl_Table.H.
Referenced by cursor2rowcol(), damage_zone(), draw(), Fl_Table(), Fl_Table_Row::handle(), handle(), move_cursor(), row_height(), rows(), Fl_Table_Row::select_row(), and table_scrolled().
int Fl_Table::current_col [protected]
Definition at line 297 of file Fl_Table.H.
Referenced by Fl_Table(), get_selection(), handle(), is_selected(), move_cursor(), and set_selection().
int Fl_Table::current_row [protected]
Definition at line 297 of file Fl_Table.H.
Referenced by Fl_Table(), get_selection(), handle(), is_selected(), move_cursor(), and set_selection().
Fl_Scrollbar* Fl_Table::hscrollbar [protected]
Definition at line 311 of file Fl_Table.H.
Referenced by col_position(), draw(), find_cell(), Fl_Table(), handle(), recalc_dimensions(), table_resized(), and table_scrolled().
int Fl_Table::leftcol [protected]
Definition at line 294 of file Fl_Table.H.
Referenced by col_scroll_position(), cursor2rowcol(), damage_zone(), draw(), Fl_Table(), Fl_Table_Row::select_row(), and table_scrolled().
int Fl_Table::leftcol_scrollpos [protected]
Definition at line 302 of file Fl_Table.H.
Referenced by col_scroll_position(), Fl_Table(), and table_scrolled().
int Fl_Table::rightcol [protected]
Definition at line 294 of file Fl_Table.H.
Referenced by col_width(), cursor2rowcol(), damage_zone(), draw(), Fl_Table(), move_cursor(), Fl_Table_Row::select_row(), and table_scrolled().
int Fl_Table::select_col [protected]
Definition at line 298 of file Fl_Table.H.
Referenced by Fl_Table(), get_selection(), handle(), is_selected(), move_cursor(), and set_selection().
int Fl_Table::select_row [protected]
Definition at line 298 of file Fl_Table.H.
Referenced by Fl_Table(), get_selection(), handle(), is_selected(), move_cursor(), and set_selection().
Fl_Scroll* Fl_Table::table [protected]
Definition at line 309 of file Fl_Table.H.
Referenced by draw(), Fl_Table(), and recalc_dimensions().
int Fl_Table::table_h [protected]
Definition at line 293 of file Fl_Table.H.
Referenced by draw(), Fl_Table(), Fl_Table_Row::handle(), recalc_dimensions(), row_position(), and table_resized().
int Fl_Table::table_w [protected]
Definition at line 293 of file Fl_Table.H.
Referenced by col_position(), draw(), Fl_Table(), Fl_Table_Row::handle(), recalc_dimensions(), and table_resized().
int Fl_Table::tih [protected]
Definition at line 305 of file Fl_Table.H.
Referenced by draw(), get_bounds(), recalc_dimensions(), row_position(), table_resized(), and table_scrolled().
int Fl_Table::tiw [protected]
Definition at line 305 of file Fl_Table.H.
Referenced by col_position(), draw(), get_bounds(), recalc_dimensions(), table_resized(), and table_scrolled().
int Fl_Table::tix [protected]
Definition at line 305 of file Fl_Table.H.
Referenced by draw(), find_cell(), get_bounds(), Fl_Table_Row::handle(), and recalc_dimensions().
int Fl_Table::tiy [protected]
Definition at line 305 of file Fl_Table.H.
Referenced by draw(), find_cell(), get_bounds(), Fl_Table_Row::handle(), and recalc_dimensions().
int Fl_Table::toh [protected]
Definition at line 306 of file Fl_Table.H.
Referenced by cursor2rowcol(), draw(), get_bounds(), Fl_Table_Row::handle(), and recalc_dimensions().
int Fl_Table::toprow [protected]
Definition at line 294 of file Fl_Table.H.
Referenced by cursor2rowcol(), damage_zone(), draw(), Fl_Table(), handle(), row_scroll_position(), Fl_Table_Row::select_row(), and table_scrolled().
int Fl_Table::toprow_scrollpos [protected]
Definition at line 301 of file Fl_Table.H.
Referenced by Fl_Table(), row_scroll_position(), and table_scrolled().
int Fl_Table::tow [protected]
Definition at line 306 of file Fl_Table.H.
Referenced by cursor2rowcol(), draw(), get_bounds(), and recalc_dimensions().
int Fl_Table::tox [protected]
Definition at line 306 of file Fl_Table.H.
Referenced by cursor2rowcol(), draw(), get_bounds(), and recalc_dimensions().
int Fl_Table::toy [protected]
Definition at line 306 of file Fl_Table.H.
Referenced by cursor2rowcol(), draw(), get_bounds(), Fl_Table_Row::handle(), and recalc_dimensions().
Fl_Scrollbar* Fl_Table::vscrollbar [protected]
Definition at line 310 of file Fl_Table.H.
Referenced by draw(), find_cell(), Fl_Table(), handle(), recalc_dimensions(), row_position(), table_resized(), and table_scrolled().
int Fl_Table::wih [protected]
Definition at line 307 of file Fl_Table.H.
Referenced by draw(), recalc_dimensions(), and table_resized().
int Fl_Table::wiw [protected]
Definition at line 307 of file Fl_Table.H.
Referenced by draw(), recalc_dimensions(), and table_resized().
int Fl_Table::wix [protected]
Definition at line 307 of file Fl_Table.H.
Referenced by draw(), find_cell(), get_bounds(), recalc_dimensions(), and table_resized().
int Fl_Table::wiy [protected]
Definition at line 307 of file Fl_Table.H.
Referenced by draw(), find_cell(), get_bounds(), recalc_dimensions(), and table_resized().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Table.H
fltk-1.3.0rc3/src/Fl_Table.cxx