SfR Fresh Dox - fltk: Fl_File_Browser Class Reference
Fl_File_Browser Class Reference
#include <Fl_File_Browser.H>
Public Types
enum { FILES, DIRECTORIES }
Public Member Functions
Fl_File_Browser (int, int, int, int, const char *=0)
uchar iconsize () const
void iconsize (uchar s)
void filter (const char *pattern)
const char * filter () const
int load (const char *directory, Fl_File_Sort_F *sort=fl_numericsort)
Fl_Fontsize textsize () const
void textsize (Fl_Fontsize s)
int filetype () const
void filetype (int t)
Detailed Description
The Fl_File_Browser widget displays a list of filenames, optionally with file-specific icons.
Definition at line 48 of file Fl_File_Browser.H.
Member Enumeration Documentation
anonymous enum
Enumerator:
FILES
DIRECTORIES
Definition at line 64 of file Fl_File_Browser.H.
Constructor & Destructor Documentation
Fl_File_Browser::Fl_File_Browser (int X, int Y, int W, int H, const char * l = 0)
The constructor creates the Fl_File_Browser widget at the specified position and size. The destructor destroys the widget and frees all memory that has been allocated.
Definition at line 400 of file Fl_File_Browser.cxx.
References FILES, and textsize().
Member Function Documentation
int Fl_File_Browser::filetype () const [inline]
Sets or gets the file browser type, FILES or DIRECTORIES. When set to FILES, both files and directories are shown. Otherwise only directories are shown.
Definition at line 108 of file Fl_File_Browser.H.
Referenced by Fl_File_Chooser::type().
void Fl_File_Browser::filetype (int t) [inline]
Sets or gets the file browser type, FILES or DIRECTORIES. When set to FILES, both files and directories are shown. Otherwise only directories are shown.
Definition at line 115 of file Fl_File_Browser.H.
const char* Fl_File_Browser::filter () const [inline]
Sets or gets the filename filter. The pattern matching uses the fl_filename_match() function in FLTK.
Definition at line 88 of file Fl_File_Browser.H.
void Fl_File_Browser::filter (const char * pattern)
Sets or gets the filename filter. The pattern matching uses the fl_filename_match() function in FLTK.
Definition at line 631 of file Fl_File_Browser.cxx.
Referenced by Fl_File_Chooser::filter(), and Fl_File_Chooser::rescan_keep_filename().
void Fl_File_Browser::iconsize (uchar s) [inline]
Sets or gets the size of the icons. The default size is 20 pixels.
Definition at line 75 of file Fl_File_Browser.H.
uchar Fl_File_Browser::iconsize () const [inline]
Sets or gets the size of the icons. The default size is 20 pixels.
Definition at line 73 of file Fl_File_Browser.H.
References Fl_Widget::redraw().
Referenced by Fl_File_Chooser::iconsize().
int Fl_File_Browser::load (const char * directory, Fl_File_Sort_F * sort = fl_numericsort)
Loads the specified directory into the browser. If icons have been loaded then the correct icon is associated with each file in the list.
The sort argument specifies a sort function to be used with fl_filename_list().
Definition at line 420 of file Fl_File_Browser.cxx.
References _fl_filename_isdir_quick(), Fl_Browser::add(), Fl_Browser::clear(), Fl_File_Icon::DEVICE, Fl_File_Icon::DIRECTORY, dirent, FILES, Fl_Group::find(), Fl_File_Icon::find(), fl_filename_list(), fl_filename_match(), fl_fopen(), FL_PATH_MAX, i, Fl_Browser::icon(), Fl_Browser::insert(), m, NULL, snprintf, start, strlcat, strlcpy, and Fl_File_Icon::type().
Referenced by Fl_File_Chooser::rescan(), Fl_File_Chooser::rescan_keep_filename(), and Fl_File_Browser_Type::widget().
Fl_Fontsize Fl_File_Browser::textsize () const [inline]
Gets the default text size (in pixels) for the lines in the browser.
Reimplemented from Fl_Browser_.
Definition at line 99 of file Fl_File_Browser.H.
Referenced by Fl_File_Browser(), Fl_File_Browser_Type::ideal_size(), and Fl_File_Chooser::textsize().
void Fl_File_Browser::textsize (Fl_Fontsize size) [inline]
Sets the default text size (in pixels) for the lines in the browser to size.
Reimplemented from Fl_Browser_.
Definition at line 100 of file Fl_File_Browser.H.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_File_Browser.H
fltk-1.3.0rc3/src/Fl_File_Browser.cxx