SfR Fresh Dox - fltk: Fl_Output_Type Class Reference
Fl_Output_Type Class Reference
Public Member Functions
virtual void ideal_size (int &w, int &h)
virtual const char * type_name ()
virtual const char * alt_type_name ()
Fl_Widget * widget (int x, int y, int w, int h)
Fl_Widget_Type * _make ()
int pixmapID ()
Detailed Description
Definition at line 808 of file factory.cxx.
Member Function Documentation
Fl_Widget_Type* Fl_Output_Type::_make () [inline, virtual]
Reimplemented from Fl_Input_Type.
Definition at line 828 of file factory.cxx.
virtual const char* Fl_Output_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Input_Type.
Definition at line 822 of file factory.cxx.
virtual void Fl_Output_Type::ideal_size (int & w, int & h) [inline, virtual]
Reimplemented from Fl_Input_Type.
Definition at line 811 of file factory.cxx.
References Fl_Widget::box(), Fl::box_dw(), fl_font(), fl_height(), fl_width(), int, Fl_Widget_Type::o, Fl_Input_::textfont(), and Fl_Input_::textsize().
int Fl_Output_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Input_Type.
Definition at line 829 of file factory.cxx.
virtual const char* Fl_Output_Type::type_name () [inline, virtual]
Reimplemented from Fl_Input_Type.
Definition at line 821 of file factory.cxx.
Fl_Widget* Fl_Output_Type::widget (int x, int y, int w, int h) [inline, virtual]
Reimplemented from Fl_Input_Type.
Definition at line 823 of file factory.cxx.
References Fl_Input_::value().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/fluid/factory.cxx