SfR Fresh Dox - fltk: Fl_Process Class Reference
Fl_Process Class Reference
Public Member Functions
Fl_Process ()
~Fl_Process ()
FILE * popen (const char *cmd, const char *mode="r")
int close ()
FILE * desc () const
char * get_line (char *line, size_t s) const
Protected Attributes
FILE * _fpt
Detailed Description
Definition at line 1877 of file fluid.cxx.
Constructor & Destructor Documentation
Fl_Process::Fl_Process () [inline]
Definition at line 1880 of file fluid.cxx.
References _fpt, and NULL.
Fl_Process::~Fl_Process () [inline]
Definition at line 1881 of file fluid.cxx.
References _fpt, and close().
Member Function Documentation
int Fl_Process::close ()
Definition at line 1965 of file fluid.cxx.
References _fpt, and NULL.
Referenced by popen(), shell_pipe_cb(), and ~Fl_Process().
FILE* Fl_Process::desc () const [inline]
Definition at line 1888 of file fluid.cxx.
References _fpt.
Referenced by do_shell_command(), and shell_pipe_cb().
char* Fl_Process::get_line (char * line, size_t s) const [inline]
Definition at line 1889 of file fluid.cxx.
References _fpt, and NULL.
Referenced by shell_pipe_cb().
FILE * Fl_Process::popen (const char * cmd, const char * mode = "r")
Definition at line 1924 of file fluid.cxx.
References _fpt, close(), NULL, and TRUE.
Referenced by do_shell_command().
Member Data Documentation
FILE* Fl_Process::_fpt [protected]
Definition at line 1911 of file fluid.cxx.
Referenced by close(), desc(), Fl_Process(), get_line(), popen(), and ~Fl_Process().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/fluid/fluid.cxx