SfR Fresh Dox - fltk: menuwindow Class Reference
menuwindow Class Reference
Public Member Functions
int handle (int)
menuwindow (const Fl_Menu_Item *m, int X, int Y, int W, int H, const Fl_Menu_Item *picked, const Fl_Menu_Item *title, int menubar=0, int menubar_title=0, int right_edge=0)
~menuwindow ()
void set_selected (int)
int find_selected (int mx, int my)
int titlex (int)
void autoscroll (int)
void position (int x, int y)
int is_inside (int x, int y)
Public Attributes
menutitle * title
int itemheight
int numitems
int selected
int drawn_selected
int shortcutWidth
const Fl_Menu_Item * menu
Detailed Description
Definition at line 93 of file Fl_Menu.cxx.
Constructor & Destructor Documentation
menuwindow::menuwindow (const Fl_Menu_Item * m, int X, int Y, int W, int H, const Fl_Menu_Item * picked, const Fl_Menu_Item * title, int menubar = 0, int menubar_title = 0, int right_edge = 0)
Definition at line 273 of file Fl_Menu.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dx(), Fl::box_dy(), BW, Fl_Window::clear_border(), Fl_Menu_Window::clear_overlay(), Fl_Widget::color(), drawn_selected, dy, Fl_Group::end(), Fl_Menu_Item::first(), FL_FLAT_BOX, FL_GRAY, FL_NO_BOX, FL_NO_LABEL, fl_shortcut_label(), FL_SUBMENU, FL_SUBMENU_POINTER, FL_UP_BOX, fl_utf_nb_char(), fl_width(), Fl_Menu_Item::flags, Fl_Widget::h(), int, itemheight, Fl_Menu_Item::labelcolor_, Fl_Menu_Item::labeltype_, LEADING, m, Fl_Menu_Item::measure(), menu, Fl_Menu_Item::next(), numitems, Fl::scheme(), Fl::screen_xywh(), selected, Fl_Window::set_menu_window(), Fl_Window::set_modal(), Fl_Menu_Item::shortcut_, shortcutWidth, Fl_Menu_Item::text, title, Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
menuwindow::~menuwindow ()
Definition at line 399 of file Fl_Menu.cxx.
References Fl_Menu_Window::hide(), and title.
Member Function Documentation
void menuwindow::autoscroll (int n)
Definition at line 411 of file Fl_Menu.cxx.
References Fl_Widget::box(), Fl::box_dx(), itemheight, position(), Fl::screen_xywh(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by Fl_Menu_Item::pulldown().
int menuwindow::find_selected (int mx, int my)
Definition at line 503 of file Fl_Menu.cxx.
References Fl_Widget::box(), Fl::box_dx(), Fl_Menu_Item::first(), Fl_Widget::h(), Fl_Menu_Item::measure(), menu, Fl_Menu_Item::next(), numitems, Fl_Menu_Item::text, Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
int menuwindow::handle (int event) [virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Window.
Definition at line 625 of file Fl_Menu.cxx.
References DONE_STATE, menustate::fakemenu, Fl_Menu_Window::hide(), i, menustate::nummenus, menustate::p, menustate::state, and title.
Referenced by Fl_Menu_Item::pulldown().
int menuwindow::is_inside (int x, int y)
Definition at line 533 of file Fl_Menu.cxx.
References Fl_Widget::h(), Fl_Widget::w(), Fl_Window::x_root(), and Fl_Window::y_root().
void menuwindow::position (int X, int Y)
Repositions the window or widget.
position(X, Y) is a shortcut for resize(X, Y, w(), h()).
Parameters:
[in] X,Y new position relative to the parent window
See also:
resize(int,int,int,int), size(int,int)
Reimplemented from Fl_Widget.
Definition at line 404 of file Fl_Menu.cxx.
References Fl_Widget::position(), title, and Fl_Widget::y().
Referenced by autoscroll(), and Fl_Menu_Item::pulldown().
void menuwindow::set_selected (int n)
Definition at line 497 of file Fl_Menu.cxx.
References Fl_Widget::damage(), FL_DAMAGE_CHILD, and selected.
Referenced by Fl_Menu_Item::pulldown().
int menuwindow::titlex (int n)
Definition at line 525 of file Fl_Menu.cxx.
References Fl_Menu_Item::first(), m, Fl_Menu_Item::measure(), menu, and Fl_Menu_Item::next().
Referenced by Fl_Menu_Item::pulldown().
Member Data Documentation
int menuwindow::drawn_selected
Definition at line 105 of file Fl_Menu.cxx.
Referenced by menuwindow().
int menuwindow::itemheight
Definition at line 102 of file Fl_Menu.cxx.
Referenced by autoscroll(), menuwindow(), and Fl_Menu_Item::pulldown().
const Fl_Menu_Item* menuwindow::menu
Definition at line 107 of file Fl_Menu.cxx.
Referenced by find_selected(), menuwindow(), Fl_Menu_Item::pulldown(), and titlex().
int menuwindow::numitems
Definition at line 103 of file Fl_Menu.cxx.
Referenced by find_selected(), and menuwindow().
int menuwindow::selected
Definition at line 104 of file Fl_Menu.cxx.
Referenced by menuwindow(), Fl_Menu_Item::pulldown(), and set_selected().
int menuwindow::shortcutWidth
Definition at line 106 of file Fl_Menu.cxx.
Referenced by menuwindow().
menutitle* menuwindow::title
Definition at line 97 of file Fl_Menu.cxx.
Referenced by handle(), menuwindow(), position(), Fl_Menu_Item::pulldown(), and ~menuwindow().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/src/Fl_Menu.cxx