SfR Fresh Dox - fltk: Fl_Input_Type Class Reference
Fl_Input_Type Class Reference
Public Member Functions
virtual void ideal_size (int &w, int &h)
virtual const char * type_name ()
virtual const char * alt_type_name ()
int is_input () const
Fl_Widget * widget (int x, int y, int w, int h)
Fl_Widget_Type * _make ()
int pixmapID ()
virtual void copy_properties ()
Detailed Description
Definition at line 470 of file factory.cxx.
Member Function Documentation
Fl_Widget_Type* Fl_Input_Type::_make () [inline, virtual]
Implements Fl_Widget_Type.
Reimplemented in Fl_Output_Type.
Definition at line 492 of file factory.cxx.
virtual const char* Fl_Input_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Output_Type.
Definition at line 485 of file factory.cxx.
virtual void Fl_Input_Type::copy_properties () [inline, virtual]
copy all properties from the edit widget to the live widget
Reimplemented from Fl_Widget_Type.
Definition at line 494 of file factory.cxx.
References Fl_Widget_Type::live_widget, Fl_Widget_Type::o, Fl_Input_::shortcut(), Fl_Input_::textcolor(), Fl_Input_::textfont(), and Fl_Input_::textsize().
virtual void Fl_Input_Type::ideal_size (int & w, int & h) [inline, virtual]
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Output_Type.
Definition at line 474 of file factory.cxx.
References Fl_Widget::box(), Fl::box_dw(), fl_font(), fl_height(), fl_width(), int, Fl_Widget_Type::o, Fl_Input_::textfont(), and Fl_Input_::textsize().
int Fl_Input_Type::is_input () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 486 of file factory.cxx.
int Fl_Input_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Output_Type.
Definition at line 493 of file factory.cxx.
virtual const char* Fl_Input_Type::type_name () [inline, virtual]
Implements Fl_Type.
Reimplemented in Fl_Output_Type.
Definition at line 484 of file factory.cxx.
Fl_Widget* Fl_Input_Type::widget (int x, int y, int w, int h) [inline, virtual]
Implements Fl_Widget_Type.
Reimplemented in Fl_Output_Type.
Definition at line 487 of file factory.cxx.
References Fl_Input_::value().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/fluid/factory.cxx