SfR Fresh Dox - fltk: Fl_Choice_Type Class Reference
Fl_Choice_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
virtual void ideal_size (int &w, int &h)
virtual const char * type_name ()
virtual const char * alt_type_name ()
Fl_Widget * widget (int X, int Y, int W, int H)
Fl_Widget_Type * _make ()
int pixmapID ()
Detailed Description
Definition at line 720 of file Fl_Type.h.
Member Function Documentation
Fl_Widget_Type* Fl_Choice_Type::_make () [inline, virtual]
Implements Fl_Widget_Type.
Definition at line 740 of file Fl_Type.h.
virtual const char* Fl_Choice_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 734 of file Fl_Type.h.
virtual void Fl_Choice_Type::ideal_size (int & w, int & h) [inline, virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 722 of file Fl_Type.h.
References Fl_Widget::box(), Fl::box_dh(), Fl_Widget::h(), Fl_Widget::labelsize(), and Fl_Widget_Type::o.
int Fl_Choice_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 741 of file Fl_Type.h.
virtual const char* Fl_Choice_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 733 of file Fl_Type.h.
Fl_Widget* Fl_Choice_Type::widget (int X, int Y, int W, int H) [inline, virtual]
Implements Fl_Widget_Type.
Definition at line 735 of file Fl_Type.h.
References Fl_Menu_::menu().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/fluid/Fl_Type.h