SfR Fresh Dox - fltk: Fl_Menu_Window Class Reference
Fl_Menu_Window Class Reference
#include <Fl_Menu_Window.H>
Public Member Functions
void show ()
void erase ()
void flush ()
void hide ()
unsigned int overlay ()
void set_overlay ()
void clear_overlay ()
~Fl_Menu_Window ()
Fl_Menu_Window (int W, int H, const char *l=0)
Fl_Menu_Window (int X, int Y, int W, int H, const char *l=0)
Detailed Description
The Fl_Menu_Window widget is a window type used for menus. By default the window is drawn in the hardware overlay planes if they are available so that the menu don't force the rest of the window to redraw.
Definition at line 42 of file Fl_Menu_Window.H.
Constructor & Destructor Documentation
Fl_Menu_Window::~Fl_Menu_Window ()
Destroys the window and all of its children.
Definition at line 104 of file Fl_Menu_Window.cxx.
References hide().
Fl_Menu_Window::Fl_Menu_Window (int W, int H, const char * l = 0) [inline]
Creates a new Fl_Menu_Window widget using the given size, and label string.
Definition at line 58 of file Fl_Menu_Window.H.
References Fl_Widget::image().
Fl_Menu_Window::Fl_Menu_Window (int X, int Y, int W, int H, const char * l = 0) [inline]
Creates a new Fl_Menu_Window widget using the given position, size, and label string.
Definition at line 61 of file Fl_Menu_Window.H.
References Fl_Widget::image().
Member Function Documentation
void Fl_Menu_Window::clear_overlay () [inline]
Tells FLTK to use normal drawing planes instead of overlay planes. This is usually necessary if your menu contains multi-color pixmaps.
Definition at line 55 of file Fl_Menu_Window.H.
Referenced by menutitle::menutitle(), and menuwindow::menuwindow().
void Fl_Menu_Window::erase ()
Erases the window, does nothing if HAVE_OVERLAY is not defined config.h
Definition at line 87 of file Fl_Menu_Window.cxx.
References fl_display, fl_xid(), gc, and Fl_Window::shown().
Referenced by hide().
void Fl_Menu_Window::flush () [virtual]
Forces the window to be drawn, this window is also made current and calls draw().
Reimplemented from Fl_Single_Window.
Definition at line 65 of file Fl_Menu_Window.cxx.
References Fl_Window::current_, Fl_Window::draw(), fl_clip_region(), fl_display, fl_gc, fl_overlay, fl_window, gc, Fl_X::i(), overlay(), Fl_X::region, and Fl_X::xid.
void Fl_Menu_Window::hide () [virtual]
Removes the window from the screen. If the window is already hidden or has not been shown then this does nothing and is harmless.
Reimplemented from Fl_Window.
Definition at line 98 of file Fl_Menu_Window.cxx.
References erase().
Referenced by Fl_Tooltip::enter_area(), menuwindow::handle(), Fl_Menu_Item::pulldown(), ~Fl_Menu_Window(), and menuwindow::~menuwindow().
unsigned int Fl_Menu_Window::overlay () [inline]
Tells if hardware overlay mode is set
Definition at line 50 of file Fl_Menu_Window.H.
Referenced by flush(), and show().
void Fl_Menu_Window::set_overlay () [inline]
Tells FLTK to use hardware overlay planes if they are available.
Definition at line 52 of file Fl_Menu_Window.H.
void Fl_Menu_Window::show () [virtual]
Puts the window on the screen. Usually (on X) this has the side effect of opening the display.
If the window is already shown then it is restored and raised to the top. This is really convenient because your program can call show() at any time, even if the window is already up. It also means that show() serves the purpose of raise() in other toolkits.
Fl_Window::show(int argc, char **argv) is used for top-level windows and allows standard arguments to be parsed from the command-line.
See also:
Fl_Window::show(int argc, char **argv)
make a window visible
Reimplemented from Fl_Single_Window.
Reimplemented in Fl_TooltipBox.
Definition at line 53 of file Fl_Menu_Window.cxx.
References fl_background_pixel, fl_display, int, Fl_X::make_xid(), overlay(), and Fl_Window::shown().
Referenced by Fl_Menu_Item::pulldown().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Menu_Window.H
fltk-1.3.0rc3/src/Fl_Menu_Window.cxx