SfR Fresh Dox - fltk: Fl_Decl_Type Class Reference
Fl_Decl_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void open ()
virtual const char * type_name ()
void write_properties ()
void read_property (const char *)
virtual int is_public () const
int pixmapID ()
Protected Attributes
char public_
char static_
Detailed Description
Definition at line 226 of file Fl_Type.h.
Member Function Documentation
int Fl_Decl_Type::is_public () const [virtual]
Reimplemented from Fl_Type.
Definition at line 562 of file Fl_Function_Type.cxx.
References Fl_Type::is_decl_block(), Fl_Type::is_public(), Fl_Type::parent, and public_.
Fl_Type * Fl_Decl_Type::make () [virtual]
Implements Fl_Type.
Reimplemented in Fl_Data_Type.
Definition at line 573 of file Fl_Function_Type.cxx.
References Fl_Type::current, Fl_Type::is_decl_block(), Fl_Type::parent, and public_.
void Fl_Decl_Type::open () [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Data_Type.
Definition at line 614 of file Fl_Function_Type.cxx.
References Fl_Text_Display::buffer(), c_check(), Fl_Type::comment(), decl_choice, decl_class_choice, decl_comment_input, decl_input, decl_panel, decl_panel_cancel, decl_panel_ok, fl_alert(), Fl_Double_Window::hide(), Fl_Widget::hide(), Fl_Type::is_in_class(), make_decl_panel(), Fl_Type::name(), public_, Fl::readqueue(), redraw_browser(), set_modflag(), Fl_Double_Window::show(), Fl_Widget::show(), static_, Fl_Input_::static_value(), Fl_Input_::value(), Fl_Choice::value(), w, and Fl::wait().
int Fl_Decl_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Data_Type.
Definition at line 239 of file Fl_Type.h.
void Fl_Decl_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Data_Type.
Definition at line 598 of file Fl_Function_Type.cxx.
References public_, and static_.
virtual const char* Fl_Decl_Type::type_name () [inline, virtual]
Implements Fl_Type.
Reimplemented in Fl_Data_Type.
Definition at line 235 of file Fl_Type.h.
void Fl_Decl_Type::write_code1 () [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Data_Type.
Definition at line 675 of file Fl_Function_Type.cxx.
References Fl_Type::class_name(), Fl_Type::is_in_class(), Fl_Type::name(), public_, static_, write_c(), Fl_Type::write_comment_c(), Fl_Type::write_comment_h(), write_h(), and write_public().
void Fl_Decl_Type::write_code2 () [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Data_Type.
Definition at line 738 of file Fl_Function_Type.cxx.
void Fl_Decl_Type::write_properties () [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Data_Type.
Definition at line 585 of file Fl_Function_Type.cxx.
References public_, static_, and write_string().
Member Data Documentation
char Fl_Decl_Type::public_ [protected]
Definition at line 228 of file Fl_Type.h.
Referenced by is_public(), Fl_Data_Type::make(), make(), Fl_Data_Type::open(), open(), read_property(), Fl_Data_Type::write_code1(), write_code1(), and write_properties().
char Fl_Decl_Type::static_ [protected]
Definition at line 229 of file Fl_Type.h.
Referenced by Fl_Data_Type::open(), open(), read_property(), Fl_Data_Type::write_code1(), write_code1(), and write_properties().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx