SfR Fresh Dox - fltk: Overlay_Window Class Reference
Overlay_Window Class Reference
Public Member Functions
int handle (int)
Overlay_Window (int W, int H)
void resize (int, int, int, int)
uchar * read_image (int &ww, int &hh)
Public Attributes
Fl_Window_Type * window
Detailed Description
Definition at line 290 of file Fl_Window_Type.cxx.
Constructor & Destructor Documentation
Overlay_Window::Overlay_Window (int W, int H) [inline]
Definition at line 296 of file Fl_Window_Type.cxx.
References Fl_Window::current().
Member Function Documentation
int Overlay_Window::handle (int event) [virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Window.
Definition at line 352 of file Fl_Window_Type.cxx.
References FL_HIDE, FL_SHOW, Fl_Window::handle(), and Fl_Widget::window().
uchar * Overlay_Window::read_image (int & ww, int & hh)
Definition at line 319 of file Fl_Window_Type.cxx.
References fl_begin_offscreen(), fl_create_offscreen(), fl_delete_offscreen(), fl_end_offscreen(), fl_read_image(), Fl_Widget::h(), Fl_Widget::image(), Fl_Window::make_current(), Fl_Widget::redraw(), Fl::scheme_bg_, Fl_Window::shown(), and Fl_Widget::w().
Referenced by Fl_Window_Type::read_image().
void Overlay_Window::resize (int X, int Y, int W, int H) [virtual]
Changes the size and position of the window. If shown() is true, these changes are communicated to the window server (which may refuse that size and cause a further resize). If shown() is false, the size and position are used when show() is called. See Fl_Group for the effect of resizing on the child widgets.
You can also call the Fl_Widget methods size(x,y) and position(w,h), which are inline wrappers for this virtual function.
A top-level window can not force, but merely suggest a position and size to the operating system. The window manager may not be willing or able to display a window at the desired position or with the given dimensions. It is up to the application developer to verify window parameters after the resize request.
resize a window
Reimplemented from Fl_Overlay_Window.
Definition at line 515 of file Fl_Window_Type.cxx.
References Fl_Widget::h(), Fl_Group::resizable(), set_modflag(), and Fl_Widget::w().
Member Data Documentation
Fl_Window_Type* Overlay_Window::window
Definition at line 294 of file Fl_Window_Type.cxx.
Referenced by Fl_Widget_Class_Type::make(), and Fl_Window_Type::make().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/fluid/Fl_Window_Type.cxx