SfR Fresh Dox - fltk: Fl_Device Class Reference
Fl_Device Class Reference
All graphical output devices and all graphics systems.
#include <Fl_Device.H>
Public Member Functions
const char * class_name ()
Returns the name of the class of this object.
Protected Member Functions
void class_name (const char *name)
Sets the class name.
Static Protected Attributes
static const char * class_id = "Fl_Device"
A string that identifies each subclass of Fl_Device.
Detailed Description
All graphical output devices and all graphics systems.
Definition at line 65 of file Fl_Device.H.
Member Function Documentation
void Fl_Device::class_name (const char * name) [inline, protected]
Sets the class name.
Definition at line 70 of file Fl_Device.H.
References name.
Referenced by fl_draw_pixmap(), and Fl_Graphics_Driver::line_style().
const char* Fl_Device::class_name () [inline]
Returns the name of the class of this object.
The class of an instance of an Fl_Device subclass can be checked with code such as:
   if ( instance->class_name() == Fl_Printer::class_id ) { ... }
Definition at line 85 of file Fl_Device.H.
Referenced by Fl_Graphics_Driver::clip_box(), Fl_Display_Device::Fl_Display_Device(), Fl_Paged_Device::Fl_Paged_Device(), Fl_PostScript_File_Device::Fl_PostScript_File_Device(), Fl_PostScript_Graphics_Driver::Fl_PostScript_Graphics_Driver(), Fl_PostScript_Printer::Fl_PostScript_Printer(), Fl_Printer::Fl_Printer(), Fl_Xlib_Graphics_Driver::Fl_Xlib_Graphics_Driver(), and Fl_Graphics_Driver::not_clipped().
Member Data Documentation
const char * Fl_Device::class_id = "Fl_Device" [static, protected]
A string that identifies each subclass of Fl_Device.
Function class_name() applied to a device of this class returns this string.
Reimplemented in Fl_Graphics_Driver, Fl_Xlib_Graphics_Driver, Fl_Surface_Device, Fl_Display_Device, Fl_Paged_Device, Fl_PostScript_Graphics_Driver, Fl_PostScript_File_Device, Fl_PostScript_Printer, and Fl_Printer.
Definition at line 70 of file Fl_Device.H.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Device.H
fltk-1.3.0rc3/src/Fl_Device.cxx