SfR Fresh Dox - fltk: DataReady Class Reference
DataReady Class Reference
Classes
struct FD
Public Member Functions
DataReady ()
~DataReady ()
void DataLock ()
void DataUnlock ()
int IsThreadRunning ()
int GetNfds ()
int GetCancelPipe (int ix)
fd_set GetFdset (int ix)
void AddFD (int n, int events, void(*cb)(int, void *), void *v)
void RemoveFD (int n, int events)
int CheckData (fd_set &r, fd_set &w, fd_set &x)
void HandleData (fd_set &r, fd_set &w, fd_set &x)
void StartThread (void *userdata)
void CancelThread (const char *reason)
Static Public Member Functions
static void * DataReadyThread (void *self)
Detailed Description
Definition at line 226 of file Fl_mac.cxx.
Constructor & Destructor Documentation
DataReady::DataReady () [inline]
Definition at line 247 of file Fl_mac.cxx.
References NULL.
DataReady::~DataReady () [inline]
Definition at line 261 of file Fl_mac.cxx.
References CancelThread(), and DEBUGTEXT.
Member Function Documentation
void DataReady::AddFD (int n, int events, void(*)(int, void *) cb, void * v)
Definition at line 294 of file Fl_mac.cxx.
References DataLock(), DataUnlock(), i, POLLERR, POLLIN, POLLOUT, and RemoveFD().
void DataReady::CancelThread (const char * reason)
Definition at line 442 of file Fl_mac.cxx.
References DataLock(), DataUnlock(), DEBUGMSG, and NULL.
Referenced by StartThread(), and ~DataReady().
int DataReady::CheckData (fd_set & r, fd_set & w, fd_set & x)
Definition at line 346 of file Fl_mac.cxx.
References DataLock(), DataUnlock(), DEBUGPERRORMSG, select(), w, and x.
void DataReady::DataLock () [inline]
Definition at line 273 of file Fl_mac.cxx.
Referenced by AddFD(), CancelThread(), CheckData(), DataReadyThread(), RemoveFD(), and StartThread().
void * DataReady::DataReadyThread (void * self) [static]
Definition at line 382 of file Fl_mac.cxx.
References DataLock(), DEBUGMSG, DEBUGPERRORMSG, kEventClassFLTK, kEventFLTKDataReady, NULL, select(), w, and x.
Referenced by StartThread().
void DataReady::DataUnlock () [inline]
Definition at line 274 of file Fl_mac.cxx.
Referenced by AddFD(), CancelThread(), CheckData(), RemoveFD(), and StartThread().
int DataReady::GetCancelPipe (int ix) [inline]
Definition at line 279 of file Fl_mac.cxx.
fd_set DataReady::GetFdset (int ix) [inline]
Definition at line 280 of file Fl_mac.cxx.
int DataReady::GetNfds () [inline]
Definition at line 278 of file Fl_mac.cxx.
void DataReady::HandleData (fd_set & r, fd_set & w, fd_set & x)
Definition at line 360 of file Fl_mac.cxx.
References DEBUGMSG, f, i, POLLERR, POLLIN, and POLLOUT.
int DataReady::IsThreadRunning () [inline]
Definition at line 277 of file Fl_mac.cxx.
void DataReady::RemoveFD (int n, int events)
Definition at line 320 of file Fl_mac.cxx.
References DataLock(), DataUnlock(), i, POLLERR, POLLIN, and POLLOUT.
Referenced by AddFD(), and Fl::remove_fd().
void DataReady::StartThread (void * userdata)
Definition at line 430 of file Fl_mac.cxx.
References CancelThread(), DataLock(), DataReadyThread(), DataUnlock(), DEBUGMSG, DEBUGTEXT, and NULL.
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/src/Fl_mac.cxx