SfR Fresh Dox - fltk: Fl_JPEG_Image Class Reference
Fl_JPEG_Image Class Reference
#include <Fl_JPEG_Image.H>
Public Member Functions
Fl_JPEG_Image (const char *filename)
The constructor loads the JPEG image from the given jpeg filename.
Fl_JPEG_Image (const char *name, const unsigned char *data)
The constructor loads the JPEG image from memory.
Detailed Description
The Fl_JPEG_Image class supports loading, caching, and drawing of Joint Photographic Experts Group (JPEG) File Interchange Format (JFIF) images. The class supports grayscale and color (RGB) JPEG image files.
Definition at line 41 of file Fl_JPEG_Image.H.
Constructor & Destructor Documentation
Fl_JPEG_Image::Fl_JPEG_Image (const char * filename)
The constructor loads the JPEG image from the given jpeg filename.
The inherited destructor frees all memory and server resources that are used by the image.
There is no error function in this class. If the image has loaded correctly, w(), h(), and d() should return values greater zero.
Parameters:
filename a full path and name pointing to a valid jpeg file.
Definition at line 103 of file Fl_JPEG_Image.cxx.
References Fl_RGB_Image::alloc_array, Fl_RGB_Image::array, Fl_Image::d(), FALSE, fl_fopen(), fp, Fl_Image::h(), JCS_RGB, jpeg_calc_output_dimensions(), jpeg_create_decompress, jpeg_destroy_decompress(), jpeg_finish_decompress(), jpeg_read_header(), jpeg_read_scanlines(), jpeg_std_error(), jpeg_stdio_src(), NULL, jpeg_decompress_struct::out_color_components, jpeg_decompress_struct::out_color_space, jpeg_decompress_struct::output_components, jpeg_decompress_struct::output_height, jpeg_decompress_struct::output_scanline, jpeg_decompress_struct::output_width, jpeg_decompress_struct::quantize_colors, row, and Fl_Image::w().
Fl_JPEG_Image::Fl_JPEG_Image (const char * name, const unsigned char * data)
The constructor loads the JPEG image from memory.
The inherited destructor frees all memory and server resources that are used by the image.
There is no error function in this class. If the image has loaded correctly, w(), h(), and d() should return values greater zero.
Parameters:
name developer shoud provide a unique name for this image
data a pointer to the memorry location of the jpeg image
Definition at line 280 of file Fl_JPEG_Image.cxx.
References Fl_RGB_Image::alloc_array, Fl_RGB_Image::array, Fl_Image::d(), FALSE, Fl_Image::h(), JCS_RGB, jpeg_calc_output_dimensions(), jpeg_create_decompress, jpeg_destroy_decompress(), jpeg_finish_decompress(), jpeg_read_header(), jpeg_read_scanlines(), jpeg_std_error(), jpeg_decompress_struct::out_color_components, jpeg_decompress_struct::out_color_space, jpeg_decompress_struct::output_components, jpeg_decompress_struct::output_height, jpeg_decompress_struct::output_scanline, jpeg_decompress_struct::output_width, jpeg_decompress_struct::quantize_colors, row, and Fl_Image::w().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_JPEG_Image.H
fltk-1.3.0rc3/src/Fl_JPEG_Image.cxx