SfR Fresh Dox - fltk: FLDropTarget Class Reference
FLDropTarget Class Reference
Public Member Functions
FLDropTarget ()
HRESULT STDMETHODCALLTYPE QueryInterface (REFIID riid, LPVOID *ppvObject)
ULONG STDMETHODCALLTYPE AddRef ()
ULONG STDMETHODCALLTYPE Release ()
HRESULT STDMETHODCALLTYPE DragEnter (IDataObject *pDataObj, DWORD, POINTL pt, DWORD *pdwEffect)
HRESULT STDMETHODCALLTYPE DragOver (DWORD, POINTL pt, DWORD *pdwEffect)
HRESULT STDMETHODCALLTYPE DragLeave ()
HRESULT STDMETHODCALLTYPE Drop (IDataObject *data, DWORD, POINTL pt, DWORD *)
Detailed Description
subclass the IDropTarget to receive data from DnD operations
Definition at line 63 of file fl_dnd_win32.cxx.
Constructor & Destructor Documentation
FLDropTarget::FLDropTarget () [inline]
Definition at line 69 of file fl_dnd_win32.cxx.
Member Function Documentation
ULONG STDMETHODCALLTYPE FLDropTarget::AddRef () [inline]
Definition at line 80 of file fl_dnd_win32.cxx.
HRESULT STDMETHODCALLTYPE FLDropTarget::DragEnter (IDataObject * pDataObj, DWORD , POINTL pt, DWORD * pdwEffect) [inline]
Definition at line 88 of file fl_dnd_win32.cxx.
References Fl::e_x, Fl::e_x_root, Fl::e_y, Fl::e_y_root, FL_DND_ENTER, fl_find(), Fl::handle(), Fl_Widget::x(), and Fl_Widget::y().
HRESULT STDMETHODCALLTYPE FLDropTarget::DragLeave () [inline]
Definition at line 146 of file fl_dnd_win32.cxx.
References FL_DND_LEAVE, and Fl::handle().
HRESULT STDMETHODCALLTYPE FLDropTarget::DragOver (DWORD , POINTL pt, DWORD * pdwEffect) [inline]
Definition at line 115 of file fl_dnd_win32.cxx.
References Fl::e_x, Fl::e_x_root, Fl::e_y, Fl::e_y_root, FL_DND_DRAG, Fl::handle(), Fl_Widget::x(), and Fl_Widget::y().
HRESULT STDMETHODCALLTYPE FLDropTarget::Drop (IDataObject * data, DWORD , POINTL pt, DWORD *) [inline]
Definition at line 155 of file fl_dnd_win32.cxx.
References b, Fl::belowmouse(), Fl::e_length, Fl::e_number, Fl::e_text, Fl::e_x, Fl::e_x_root, Fl::e_y, Fl::e_y_root, FL_DND_RELEASE, fl_dnd_target_window, FL_PASTE, fl_xid(), Fl_Widget::handle(), Fl::handle(), Fl_Widget::parent(), w, Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
HRESULT STDMETHODCALLTYPE FLDropTarget::QueryInterface (REFIID riid, LPVOID * ppvObject) [inline]
Definition at line 70 of file fl_dnd_win32.cxx.
References NULL.
ULONG STDMETHODCALLTYPE FLDropTarget::Release () [inline]
Definition at line 81 of file fl_dnd_win32.cxx.
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/src/fl_dnd_win32.cxx