SfR Fresh Dox - fltk: Flcc_ValueBox Class Reference
Flcc_ValueBox Class Reference
#include <Fl_Color_Chooser.H>
Public Member Functions
int handle (int)
Flcc_ValueBox (int X, int Y, int W, int H)
Protected Member Functions
void draw ()
int handle_key (int)
Detailed Description
For internal use only
Definition at line 59 of file Fl_Color_Chooser.H.
Constructor & Destructor Documentation
Flcc_ValueBox::Flcc_ValueBox (int X, int Y, int W, int H) [inline]
Definition at line 66 of file Fl_Color_Chooser.H.
References py.
Member Function Documentation
void Flcc_ValueBox::draw () [protected, virtual]
Draws the widget. Never call this function directly. FLTK will schedule redrawing whenever needed. If your widget must be redrawn as soon as possible, call redraw() instead.
Override this function to draw your own widgets.
If you ever need to call another widget's draw method from within your own draw() method, e.g. for an embedded scrollbar, you can do it (because draw() is virtual) like this:
        Fl_Widget *s = &scroll;         // scroll is an embedded Fl_Scrollbar
        s->draw();                      // calls Fl_Scrollbar::draw()
Implements Fl_Widget.
Definition at line 385 of file Fl_Color_Chooser.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dw(), Fl::box_dx(), Fl::box_dy(), Fl_Widget::damage(), Fl_Widget::draw_box(), FL_DAMAGE_ALL, FL_DAMAGE_EXPOSE, fl_draw_image(), FL_FOREGROUND_COLOR, FL_GRAY, fl_pop_clip(), fl_push_clip(), FL_UP_BOX, Fl::focus(), Fl_Widget::h(), Fl_Color_Chooser::hsv2rgb(), Fl_Color_Chooser::hue(), int, Fl_Widget::parent(), py, Fl_Color_Chooser::saturation(), tb, tg, Fl_Color_Chooser::value(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
int Flcc_ValueBox::handle (int event) [virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Widget.
Definition at line 341 of file Fl_Color_Chooser.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dy(), Fl_Widget::do_callback(), Fl::event_key(), Fl::event_y(), FL_DRAG, FL_FOCUS, FL_KEYBOARD, FL_PUSH, FL_UNFOCUS, Fl::focus(), Fl_Widget::h(), handle_key(), Fl_Color_Chooser::hsv(), Fl_Color_Chooser::hue(), Fl_Widget::parent(), Fl_Widget::redraw(), Fl_Color_Chooser::saturation(), Fl_Color_Chooser::value(), Fl::visible_focus(), and Fl_Widget::y().
int Flcc_ValueBox::handle_key (int key) [protected]
Definition at line 404 of file Fl_Color_Chooser.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl_Widget::do_callback(), FL_Down, FL_Up, Fl_Widget::h(), Fl_Color_Chooser::hsv(), Fl_Color_Chooser::hue(), int, Fl_Widget::parent(), Fl_Color_Chooser::saturation(), and Fl_Color_Chooser::value().
Referenced by handle().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Color_Chooser.H
fltk-1.3.0rc3/src/Fl_Color_Chooser.cxx