SfR Fresh Dox - fltk: Fl_Table_Type Class Reference
Fl_Table_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
virtual const char * type_name ()
virtual const char * alt_type_name ()
Fl_Widget_Type * _make ()
Fl_Widget * widget (int X, int Y, int W, int H)
int pixmapID ()
virtual Fl_Widget * enter_live_mode (int top=0)
void add_child (Fl_Type *, Fl_Type *)
void move_child (Fl_Type *, Fl_Type *)
void remove_child (Fl_Type *)
Detailed Description
Definition at line 470 of file Fl_Type.h.
Member Function Documentation
Fl_Widget_Type* Fl_Table_Type::_make () [inline, virtual]
Reimplemented from Fl_Group_Type.
Definition at line 474 of file Fl_Type.h.
void Fl_Table_Type::add_child (Fl_Type * cc, Fl_Type * before) [virtual]
Reimplemented from Fl_Group_Type.
Definition at line 290 of file Fl_Group_Type.cxx.
References b, fl_message(), Fl_Widget_Type::o, and Fl_Widget::redraw().
virtual const char* Fl_Table_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Group_Type.
Definition at line 473 of file Fl_Type.h.
Fl_Widget * Fl_Table_Type::enter_live_mode (int top = 0) [virtual]
Build widgets and dataset needed in live mode.
Returns:
a widget pointer that the live mode initiator can 'show()'
See also:
leave_live_mode()
Reimplemented from Fl_Group_Type.
Definition at line 376 of file Fl_Group_Type.cxx.
References Fl_Group_Type::copy_properties(), Fl_Group::end(), Fl_Widget::h(), Fl_Widget_Type::live_widget, Fl_Widget_Type::o, Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
void Fl_Table_Type::move_child (Fl_Type * cc, Fl_Type * before) [virtual]
Reimplemented from Fl_Group_Type.
Definition at line 334 of file Fl_Group_Type.cxx.
References b, Fl_Type::insert(), Fl_Widget_Type::o, Fl_Widget::redraw(), and Fl_Type::remove().
int Fl_Table_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Group_Type.
Definition at line 476 of file Fl_Type.h.
void Fl_Table_Type::remove_child (Fl_Type * cc) [virtual]
Reimplemented from Fl_Group_Type.
Definition at line 318 of file Fl_Group_Type.cxx.
References Fl_Widget_Type::o, and Fl_Type::remove().
virtual const char* Fl_Table_Type::type_name () [inline, virtual]
Reimplemented from Fl_Group_Type.
Definition at line 472 of file Fl_Type.h.
References table_type_name.
Fl_Widget * Fl_Table_Type::widget (int X, int Y, int W, int H) [virtual]
Reimplemented from Fl_Group_Type.
Definition at line 228 of file Fl_Group_Type.cxx.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Group_Type.cxx