SfR Fresh Dox - fltk: Fl_Bitmap Class Reference
Fl_Bitmap Class Reference
#include <Fl_Bitmap.H>
Public Member Functions
Fl_Bitmap (const uchar *bits, int W, int H)
Fl_Bitmap (const char *bits, int W, int H)
virtual ~Fl_Bitmap ()
virtual Fl_Image * copy (int W, int H)
Fl_Image * copy ()
virtual void draw (int X, int Y, int W, int H, int cx=0, int cy=0)
void draw (int X, int Y)
virtual void label (Fl_Widget *w)
virtual void label (Fl_Menu_Item *m)
virtual void uncache ()
Public Attributes
const uchar * array
int alloc_array
Friends
class Fl_Quartz_Graphics_Driver
class Fl_GDI_Graphics_Driver
class Fl_Xlib_Graphics_Driver
Detailed Description
The Fl_Bitmap class supports caching and drawing of mono-color (bitmap) images. Images are drawn using the current color.
Definition at line 42 of file Fl_Bitmap.H.
Constructor & Destructor Documentation
Fl_Bitmap::Fl_Bitmap (const uchar * bits, int W, int H) [inline]
The constructors create a new bitmap from the specified bitmap data
The constructors create a new bitmap from the specified bitmap data.
Definition at line 66 of file Fl_Bitmap.H.
References Fl_Image::data().
Referenced by copy().
Fl_Bitmap::Fl_Bitmap (const char * array, int W, int H) [inline]
The constructors create a new bitmap from the specified bitmap data
The constructors create a new bitmap from the specified bitmap data.
Definition at line 69 of file Fl_Bitmap.H.
References Fl_Image::data().
Fl_Bitmap::~Fl_Bitmap () [virtual]
The destructor free all memory and server resources that are used by the bitmap.
Definition at line 377 of file Fl_Bitmap.cxx.
References alloc_array, and uncache().
Member Function Documentation
Fl_Image * Fl_Bitmap::copy (int W, int H) [virtual]
The copy() method creates a copy of the specified image. If the width and height are provided, the image is resized to the specified size. The image should be deleted (or in the case of Fl_Shared_Image, released) when you are done with it.
Reimplemented from Fl_Image.
Definition at line 402 of file Fl_Bitmap.cxx.
References alloc_array, dx, dy, Fl_Bitmap(), H, Fl_Image::h(), and Fl_Image::w().
Fl_Image* Fl_Bitmap::copy () [inline]
The copy() method creates a copy of the specified image. If the width and height are provided, the image is resized to the specified size. The image should be deleted (or in the case of Fl_Shared_Image, released) when you are done with it.
Reimplemented from Fl_Image.
Definition at line 73 of file Fl_Bitmap.H.
References copy(), Fl_Image::h(), and Fl_Image::w().
Referenced by copy().
void Fl_Bitmap::draw (int X, int Y) [inline]
The draw() methods draw the image. This form specifies the upper-lefthand corner of the image
Reimplemented from Fl_Image.
Definition at line 75 of file Fl_Bitmap.H.
References draw(), Fl_Image::h(), and Fl_Image::w().
Referenced by draw().
void Fl_Bitmap::draw (int X, int Y, int W, int H, int cx = 0, int cy = 0) [virtual]
The draw() methods draw the image. This form specifies a bounding box for the image, with the origin (upper-lefthand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Image.
Definition at line 251 of file Fl_Bitmap.cxx.
References Fl_Graphics_Driver::draw(), and fl_graphics_driver.
Referenced by Fl_Adjuster::draw().
void Fl_Bitmap::label (Fl_Menu_Item * m) [virtual]
The label() methods are an obsolete way to set the image attribute of a widget or menu item. Use the image() or deimage() methods of the Fl_Widget and Fl_Menu_Item classes instead.
Reimplemented from Fl_Image.
Definition at line 397 of file Fl_Bitmap.cxx.
References _FL_IMAGE_LABEL, Fl_Menu_Item::label(), Fl_Image::labeltype(), Fl_Image::measure(), and Fl::set_labeltype().
void Fl_Bitmap::label (Fl_Widget * widget) [virtual]
The label() methods are an obsolete way to set the image attribute of a widget or menu item. Use the image() or deimage() methods of the Fl_Widget and Fl_Menu_Item classes instead.
Reimplemented from Fl_Image.
Definition at line 393 of file Fl_Bitmap.cxx.
References Fl_Widget::image().
void Fl_Bitmap::uncache () [virtual]
If the image has been cached for display, delete the cache data. This allows you to change the data used for the image and then redraw it without recreating an image object.
Reimplemented from Fl_Image.
Definition at line 382 of file Fl_Bitmap.cxx.
References fl_delete_bitmask().
Referenced by ~Fl_Bitmap().
Friends And Related Function Documentation
friend class Fl_GDI_Graphics_Driver [friend]
Definition at line 44 of file Fl_Bitmap.H.
friend class Fl_Quartz_Graphics_Driver [friend]
Definition at line 43 of file Fl_Bitmap.H.
friend class Fl_Xlib_Graphics_Driver [friend]
Definition at line 45 of file Fl_Bitmap.H.
Member Data Documentation
int Fl_Bitmap::alloc_array
Non-zero if array points to bitmap data allocated internally
Definition at line 51 of file Fl_Bitmap.H.
Referenced by copy(), and ~Fl_Bitmap().
const uchar* Fl_Bitmap::array
pointer to raw bitmap data
Definition at line 49 of file Fl_Bitmap.H.
Referenced by Fl_PostScript_Graphics_Driver::draw(), Fl_Xlib_Graphics_Driver::draw(), and Fl_XBM_Image::Fl_XBM_Image().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Bitmap.H
fltk-1.3.0rc3/src/Fl_Bitmap.cxx