SfR Fresh Dox - fltk: Fl_Pixmap Class Reference
Fl_Pixmap Class Reference
#include <Fl_Pixmap.H>
Public Member Functions
Fl_Pixmap (char *const *D)
Fl_Pixmap (uchar *const *D)
Fl_Pixmap (const char *const *D)
Fl_Pixmap (const uchar *const *D)
virtual ~Fl_Pixmap ()
virtual Fl_Image * copy (int W, int H)
Fl_Image * copy ()
virtual void color_average (Fl_Color c, float i)
virtual void desaturate ()
virtual void draw (int X, int Y, int W, int H, int cx=0, int cy=0)
void draw (int X, int Y)
virtual void label (Fl_Widget *w)
virtual void label (Fl_Menu_Item *m)
virtual void uncache ()
Public Attributes
int alloc_data
Protected Member Functions
void measure ()
Friends
class Fl_Quartz_Graphics_Driver
class Fl_GDI_Graphics_Driver
class Fl_Xlib_Graphics_Driver
Detailed Description
The Fl_Pixmap class supports caching and drawing of colormap (pixmap) images, including transparency.
Definition at line 47 of file Fl_Pixmap.H.
Constructor & Destructor Documentation
Fl_Pixmap::Fl_Pixmap (char *const * D) [inline, explicit]
The constructors create a new pixmap from the specified XPM data.
Definition at line 76 of file Fl_Pixmap.H.
References Fl_Image::measure().
Referenced by copy().
Fl_Pixmap::Fl_Pixmap (uchar *const * D) [inline, explicit]
The constructors create a new pixmap from the specified XPM data.
Definition at line 78 of file Fl_Pixmap.H.
References Fl_Image::measure().
Fl_Pixmap::Fl_Pixmap (const char *const * D) [inline, explicit]
The constructors create a new pixmap from the specified XPM data.
Definition at line 80 of file Fl_Pixmap.H.
References Fl_Image::measure().
Fl_Pixmap::Fl_Pixmap (const uchar *const * D) [inline, explicit]
The constructors create a new pixmap from the specified XPM data.
Definition at line 82 of file Fl_Pixmap.H.
References Fl_Image::measure().
Fl_Pixmap::~Fl_Pixmap () [virtual]
The destructor free all memory and server resources that are used by the pixmap.
Definition at line 240 of file Fl_Pixmap.cxx.
References uncache().
Member Function Documentation
void Fl_Pixmap::color_average (Fl_Color c, float i) [virtual]
The color_average() method averages the colors in the image with the FLTK color value c. The i argument specifies the amount of the original image to combine with the color, so a value of 1.0 results in no color blend, and a value of 0.0 results in a constant image of the specified color. The original image data is not altered by this method.
Reimplemented from Fl_Image.
Definition at line 413 of file Fl_Pixmap.cxx.
References b, chars_per_pixel, color(), Fl_Image::data(), f, fl_parse_color(), Fl::get_color(), and uncache().
Fl_Image * Fl_Pixmap::copy (int W, int H) [virtual]
The copy() method creates a copy of the specified image. If the width and height are provided, the image is resized to the specified size. The image should be deleted (or in the case of Fl_Shared_Image, released) when you are done with it.
Reimplemented from Fl_Image.
Definition at line 315 of file Fl_Pixmap.cxx.
References alloc_data, chars_per_pixel, Fl_Image::data(), dx, dy, Fl_Pixmap(), H, Fl_Image::h(), i, new_row, and Fl_Image::w().
Fl_Image* Fl_Pixmap::copy () [inline]
The copy() method creates a copy of the specified image. If the width and height are provided, the image is resized to the specified size. The image should be deleted (or in the case of Fl_Shared_Image, released) when you are done with it.
Reimplemented from Fl_Image.
Definition at line 85 of file Fl_Pixmap.H.
References copy(), Fl_Image::h(), and Fl_Image::w().
Referenced by copy().
void Fl_Pixmap::desaturate () [virtual]
The desaturate() method converts an image to grayscale. If the image contains an alpha channel (depth = 4), the alpha channel is preserved. This method does not alter the original image data.
Reimplemented from Fl_Image.
Definition at line 505 of file Fl_Pixmap.cxx.
References b, chars_per_pixel, Fl_Image::data(), fl_parse_color(), i, and uncache().
void Fl_Pixmap::draw (int X, int Y) [inline]
The draw() methods draw the image. This form specifies the upper-lefthand corner of the image
Reimplemented from Fl_Image.
Definition at line 89 of file Fl_Pixmap.H.
References draw(), Fl_Image::h(), and Fl_Image::w().
Referenced by draw().
void Fl_Pixmap::draw (int X, int Y, int W, int H, int cx = 0, int cy = 0) [virtual]
The draw() methods draw the image. This form specifies a bounding box for the image, with the origin (upper-lefthand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Image.
Definition at line 77 of file Fl_Pixmap.cxx.
References Fl_Graphics_Driver::draw(), and fl_graphics_driver.
Referenced by Fl_FormsPixmap::draw().
void Fl_Pixmap::label (Fl_Widget * widget) [virtual]
The label() methods are an obsolete way to set the image attribute of a widget or menu item. Use the image() or deimage() methods of the Fl_Widget and Fl_Menu_Item classes instead.
Reimplemented from Fl_Image.
Definition at line 257 of file Fl_Pixmap.cxx.
References Fl_Widget::image().
void Fl_Pixmap::label (Fl_Menu_Item * m) [virtual]
The label() methods are an obsolete way to set the image attribute of a widget or menu item. Use the image() or deimage() methods of the Fl_Widget and Fl_Menu_Item classes instead.
Reimplemented from Fl_Image.
Definition at line 261 of file Fl_Pixmap.cxx.
References _FL_IMAGE_LABEL, Fl_Menu_Item::label(), Fl_Image::labeltype(), Fl_Image::measure(), and Fl::set_labeltype().
void Fl_Pixmap::measure () [protected]
Definition at line 67 of file Fl_Pixmap.cxx.
References Fl_Image::data(), fl_measure_pixmap(), Fl_Image::h(), H, and Fl_Image::w().
Referenced by Fl_Xlib_Graphics_Driver::draw(), and Fl_XPM_Image::Fl_XPM_Image().
void Fl_Pixmap::uncache () [virtual]
If the image has been cached for display, delete the cache data. This allows you to change the data used for the image and then redraw it without recreating an image object.
Reimplemented from Fl_Image.
Definition at line 245 of file Fl_Pixmap.cxx.
References fl_delete_bitmask(), and fl_delete_offscreen().
Referenced by color_average(), desaturate(), Fl::reload_scheme(), and ~Fl_Pixmap().
Friends And Related Function Documentation
friend class Fl_GDI_Graphics_Driver [friend]
Definition at line 49 of file Fl_Pixmap.H.
friend class Fl_Quartz_Graphics_Driver [friend]
Definition at line 48 of file Fl_Pixmap.H.
friend class Fl_Xlib_Graphics_Driver [friend]
Definition at line 50 of file Fl_Pixmap.H.
Member Data Documentation
int Fl_Pixmap::alloc_data
Definition at line 61 of file Fl_Pixmap.H.
Referenced by copy(), Fl_GIF_Image::Fl_GIF_Image(), and Fl_XPM_Image::Fl_XPM_Image().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Pixmap.H
fltk-1.3.0rc3/src/Fl_Pixmap.cxx