SfR Fresh Dox - fltk: Fl_Class_Type Class Reference
Fl_Class_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Class_Type ()
~Fl_Class_Type ()
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void open ()
virtual const char * type_name ()
int is_parent () const
int is_decl_block () const
int is_class () const
virtual int is_public () const
int pixmapID ()
void write_properties ()
void read_property (const char *)
void prefix (const char *p)
const char * prefix () const
int has_function (const char *, const char *) const
Public Attributes
char write_public_state
Fl_Class_Type * parent_class
Detailed Description
Definition at line 297 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_Class_Type::Fl_Class_Type () [inline]
Definition at line 301 of file Fl_Type.h.
Fl_Class_Type::~Fl_Class_Type () [inline]
Definition at line 302 of file Fl_Type.h.
Member Function Documentation
int Fl_Class_Type::has_function (const char * rtype, const char * sig) const
Return 1 if this class contains a function with the given signature.
Definition at line 1460 of file Fl_Function_Type.cxx.
References Fl_Function_Type::has_signature(), Fl_Type::level, Fl_Type::next, and Fl_Type::type_name().
Referenced by Fl_Widget_Type::write_static().
int Fl_Class_Type::is_class () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 317 of file Fl_Type.h.
int Fl_Class_Type::is_decl_block () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 316 of file Fl_Type.h.
int Fl_Class_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 315 of file Fl_Type.h.
int Fl_Class_Type::is_public () const [virtual]
Reimplemented from Fl_Type.
Definition at line 1307 of file Fl_Function_Type.cxx.
Fl_Type * Fl_Class_Type::make () [virtual]
Implements Fl_Type.
Definition at line 1314 of file Fl_Function_Type.cxx.
References Fl_Type::current, Fl_Type::is_decl_block(), Fl_Type::name(), and Fl_Type::parent.
void Fl_Class_Type::open () [virtual]
Reimplemented from Fl_Type.
Definition at line 1351 of file Fl_Function_Type.cxx.
References Fl_Text_Display::buffer(), c_check(), c_comment_input, c_name_input, c_panel_cancel, c_panel_ok, c_public_button, c_subclass_input, class_panel, Fl_Type::comment(), fl_alert(), FL_PATH_MAX, Fl_Double_Window::hide(), is_id(), make_class_panel(), Fl_Type::name(), prefix(), Fl::readqueue(), redraw_browser(), set_modflag(), Fl_Double_Window::show(), Fl_Input_::static_value(), storestring(), Fl_Input_::value(), Fl_Button::value(), w, and Fl::wait().
int Fl_Class_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 319 of file Fl_Type.h.
const char* Fl_Class_Type::prefix () const [inline]
Definition at line 325 of file Fl_Type.h.
Referenced by open(), and write_code1().
void Fl_Class_Type::prefix (const char * p)
Definition at line 1309 of file Fl_Function_Type.cxx.
void Fl_Class_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Type.
Definition at line 1339 of file Fl_Function_Type.cxx.
References read_word(), and storestring().
virtual const char* Fl_Class_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 314 of file Fl_Type.h.
void Fl_Class_Type::write_code1 () [virtual]
Reimplemented from Fl_Type.
Definition at line 1438 of file Fl_Function_Type.cxx.
References current_class, Fl_Type::name(), parent_class, prefix(), Fl_Type::write_comment_h(), write_h(), and write_public_state.
void Fl_Class_Type::write_code2 () [virtual]
Reimplemented from Fl_Type.
Definition at line 1452 of file Fl_Function_Type.cxx.
References parent_class, and write_h().
void Fl_Class_Type::write_properties () [virtual]
Reimplemented from Fl_Type.
Definition at line 1327 of file Fl_Function_Type.cxx.
References write_string(), and write_word().
Member Data Documentation
Fl_Class_Type* Fl_Class_Type::parent_class
Definition at line 308 of file Fl_Type.h.
Referenced by write_code1(), and write_code2().
char Fl_Class_Type::write_public_state
Definition at line 307 of file Fl_Type.h.
Referenced by write_code1(), and write_public().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx