SfR Fresh Dox - fltk: Fluid_Image Class Reference
Fluid_Image Class Reference
#include <Fluid_Image.h>
Public Member Functions
void decrement ()
void increment ()
void image (Fl_Widget *)
void deimage (Fl_Widget *)
void write_static ()
void write_code (const char *var, int inactive=0)
const char * name () const
Static Public Member Functions
static Fluid_Image * find (const char *)
Public Attributes
int written
Protected Member Functions
Fluid_Image (const char *name)
~Fluid_Image ()
Detailed Description
Definition at line 38 of file Fluid_Image.h.
Constructor & Destructor Documentation
Fluid_Image::Fluid_Image (const char * name) [protected]
Definition at line 214 of file Fluid_Image.cxx.
References Fl_Shared_Image::get(), and written.
Referenced by find().
Fluid_Image::~Fluid_Image () [protected]
Definition at line 231 of file Fluid_Image.cxx.
References Fl_Shared_Image::release().
Member Function Documentation
void Fluid_Image::decrement ()
Definition at line 225 of file Fluid_Image.cxx.
Referenced by Fl_Widget_Type::setimage(), and Fl_Widget_Type::setinactive().
void Fluid_Image::deimage (Fl_Widget * o)
Definition at line 45 of file Fluid_Image.cxx.
References Fl_Widget::deimage(), and Fl_Widget::window().
Referenced by Fl_Widget_Type::setinactive().
Fluid_Image * Fluid_Image::find (const char * iname) [static]
Definition at line 166 of file Fluid_Image.cxx.
References b, f, fl_fopen(), Fluid_Image(), goto_source_dir(), Fl_Image::h(), i, leave_source_dir(), read_error(), and Fl_Image::w().
Referenced by Fl_Widget_Type::image_name(), Fl_Widget_Type::inactive_name(), Fl_Widget_Type::read_property(), and ui_find_image().
void Fluid_Image::image (Fl_Widget * o)
Definition at line 41 of file Fluid_Image.cxx.
References Fl_Widget::image(), and Fl_Widget::window().
Referenced by Fl_Widget_Type::setimage().
void Fluid_Image::increment ()
Definition at line 221 of file Fluid_Image.cxx.
Referenced by Fl_Widget_Type::setimage(), and Fl_Widget_Type::setinactive().
const char* Fluid_Image::name () const [inline]
Definition at line 54 of file Fluid_Image.h.
Referenced by write_code(), and write_static().
void Fluid_Image::write_code (const char * var, int inactive = 0)
Definition at line 153 of file Fluid_Image.cxx.
References fl_filename_name(), indent(), name(), unique_id(), and write_c().
Referenced by Fl_Menu_Item_Type::write_code1(), and Fl_Widget_Type::write_widget_code().
void Fluid_Image::write_static ()
Definition at line 54 of file Fluid_Image.cxx.
References Fl_Image::count(), Fl_Image::d(), data, Fl_Image::data(), f, fl_filename_ext(), fl_filename_name(), fl_fopen(), Fl_Image::h(), i, Fl_Image::ld(), name(), SEEK_END, SEEK_SET, unique_id(), Fl_Image::w(), write_c(), write_cdata(), write_cstring(), and write_number.
Referenced by Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
Member Data Documentation
int Fluid_Image::written
Definition at line 46 of file Fluid_Image.h.
Referenced by Fluid_Image(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fluid_Image.h
fltk-1.3.0rc3/fluid/Fluid_Image.cxx