SfR Fresh Dox - fltk: Fl_Clock Class Reference
Fl_Clock Class Reference
This widget provides a round analog clock display.
#include <Fl_Clock.H>
Public Member Functions
int handle (int)
Fl_Clock (int X, int Y, int W, int H, const char *L=0)
Fl_Clock (uchar t, int X, int Y, int W, int H, const char *L)
~Fl_Clock ()
Detailed Description
This widget provides a round analog clock display.
Fl_Clock is provided for Forms compatibility. It installs a 1-second timeout callback using Fl::add_timeout(). You can choose the rounded or square type of the clock with type(), see below.
type() FL_SQUARE_CLOCK and FL_ROUND_CLOCK
Definition at line 122 of file Fl_Clock.H.
Constructor & Destructor Documentation
Fl_Clock::Fl_Clock (int X, int Y, int W, int H, const char * L = 0)
Create an Fl_Clock widget using the given position, size, and label string. The default boxtype is FL_NO_BOX.
Parameters:
[in] X,Y,W,H position and size of the widget
[in] L widget label, default is no label
Definition at line 176 of file Fl_Clock.cxx.
Fl_Clock::Fl_Clock (uchar t, int X, int Y, int W, int H, const char * L)
Create an Fl_Clock widget using the given boxtype, position, size, and label string.
Parameters:
[in] t boxtype
[in] X,Y,W,H position and size of the widget
[in] L widget label, default is no label
Definition at line 186 of file Fl_Clock.cxx.
References Fl_Widget::box(), FL_NO_BOX, FL_ROUND_CLOCK, FL_UP_BOX, and Fl_Widget::type().
Fl_Clock::~Fl_Clock ()
The destructor removes the clock.
Definition at line 212 of file Fl_Clock.cxx.
References Fl::remove_timeout().
Member Function Documentation
int Fl_Clock::handle (int event) [virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Widget.
Definition at line 197 of file Fl_Clock.cxx.
References FL_HIDE, FL_SHOW, and Fl::remove_timeout().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Clock.H
fltk-1.3.0rc3/src/Fl_Clock.cxx