SfR Fresh Dox - fltk: Fl_Menu_Item_Type Class Reference
Fl_Menu_Item_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Menu_Item * subtypes ()
const char * type_name ()
const char * alt_type_name ()
Fl_Type * make ()
int is_menu_item () const
int is_button () const
Fl_Widget * widget (int, int, int, int)
Fl_Widget_Type * _make ()
const char * menu_name (int &i)
int flags ()
void write_static ()
void write_item ()
void write_code1 ()
void write_code2 ()
int pixmapID ()
Detailed Description
Definition at line 630 of file Fl_Type.h.
Member Function Documentation
Fl_Widget_Type* Fl_Menu_Item_Type::_make () [inline, virtual]
Implements Fl_Widget_Type.
Definition at line 639 of file Fl_Type.h.
const char* Fl_Menu_Item_Type::alt_type_name () [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Submenu_Type.
Definition at line 634 of file Fl_Type.h.
int Fl_Menu_Item_Type::flags ()
Definition at line 271 of file Fl_Menu_Type.cxx.
References Fl_Widget::active(), FL_MENU_DIVIDER, FL_MENU_INACTIVE, FL_MENU_INVISIBLE, FL_MENU_VALUE, FL_SUBMENU, FL_SUBMENU_POINTER, Fl_Widget_Type::hotspot(), i, Fl_Type::is_parent(), NULL, Fl_Widget_Type::o, Fl_Widget::type(), Fl_Type::user_data(), value, and Fl_Widget::visible().
Referenced by write_item().
int Fl_Menu_Item_Type::is_button () const [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Submenu_Type.
Definition at line 637 of file Fl_Type.h.
int Fl_Menu_Item_Type::is_menu_item () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 636 of file Fl_Type.h.
Fl_Type * Fl_Menu_Item_Type::make () [virtual]
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Submenu_Type.
Definition at line 110 of file Fl_Menu_Type.cxx.
References Fl_Type::add(), Fl_Type::current, Fl_Widget_Type::default_size, Fl_Type::factory, fl_message(), Fl_Type::is_menu_button(), Fl_Type::is_menu_item(), Fl_Type::is_parent(), Fl_Type::label(), Fl_Widget::labelsize(), Fl_Widget_Type::o, and Fl_Type::parent.
const char * Fl_Menu_Item_Type::menu_name (int & i)
Definition at line 156 of file Fl_Menu_Type.cxx.
References Fl_Type::is_menu_item(), Fl_Type::is_parent(), Fl_Type::label(), Fl_Type::level, Fl_Type::name(), Fl_Type::next, Fl_Type::prev, and unique_id().
Referenced by write_code1(), Fl_Menu_Type::write_code2(), and write_static().
int Fl_Menu_Item_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Submenu_Type.
Definition at line 646 of file Fl_Type.h.
Fl_Menu_Item* Fl_Menu_Item_Type::subtypes () [inline, virtual]
Reimplemented from Fl_Widget_Type.
Reimplemented in Fl_Submenu_Type.
Definition at line 632 of file Fl_Type.h.
References menu_item_type_menu.
const char* Fl_Menu_Item_Type::type_name () [inline, virtual]
Implements Fl_Type.
Reimplemented in Fl_Submenu_Type.
Definition at line 633 of file Fl_Type.h.
Fl_Widget* Fl_Menu_Item_Type::widget (int , int , int , int) [inline, virtual]
Implements Fl_Widget_Type.
Definition at line 638 of file Fl_Type.h.
void Fl_Menu_Item_Type::write_code1 () [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 327 of file Fl_Menu_Type.cxx.
References array_name(), Fl_Type::callback(), Fl_Type::callback_name(), Fl_Type::class_name(), Fl_Widget_Type::extra_code(), i, Fl_Widget_Type::image, indent(), Fl_Type::is_menu_item(), is_name(), isdeclare(), menu_name(), Fl_Type::name(), NUM_EXTRA_CODE, Fl_Type::prev, Fl_Widget_Type::public_, Fl_Type::user_data_type(), write_c(), Fluid_Image::write_code(), write_h(), and write_public().
void Fl_Menu_Item_Type::write_code2 () [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 386 of file Fl_Menu_Type.cxx.
void Fl_Menu_Item_Type::write_item ()
Definition at line 284 of file Fl_Menu_Type.cxx.
References Fl_Type::callback(), Fl_Type::callback_name(), Fl_Type::class_name(), FL_CTRL, FL_META, flags(), Fl_Widget_Type::image, is_name(), Fl_Type::label(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), Fl_Widget_Type::o, use_FL_COMMAND, Fl_Type::user_data(), write_c(), and write_cstring().
void Fl_Menu_Item_Type::write_static () [virtual]
Reimplemented from Fl_Widget_Type.
Definition at line 172 of file Fl_Menu_Type.cxx.
References array_name(), Fl_Type::callback(), Fl_Type::callback_name(), Fl_Type::class_name(), Fl_Widget_Type::extra_code(), i, Fl_Widget_Type::image, Fl_Type::is_class(), is_id(), Fl_Type::is_menu_item(), is_name(), Fl_Type::is_widget(), isdeclare(), Fl_Type::level, m, menu_name(), Fl_Type::name(), Fl_Type::next, NUM_EXTRA_CODE, Fl_Type::parent, Fl_Type::prev, Fl_Type::user_data_type(), Fl_Type::user_defined(), write_c(), write_declare(), write_number, Fluid_Image::write_static(), and Fluid_Image::written.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Menu_Type.cxx