SfR Fresh Dox - fltk: Fl_Round_Button Class Reference
Fl_Round_Button Class Reference
#include <Fl_Round_Button.H>
Public Member Functions
Fl_Round_Button (int x, int y, int w, int h, const char *l=0)
Detailed Description
Buttons generate callbacks when they are clicked by the user. You control exactly when and how by changing the values for type() and when().
The Fl_Round_Button subclass display the "on" state by turning on a light, rather than drawing pushed in. The shape of the "light" is initially set to FL_ROUND_DOWN_BOX. The color of the light when on is controlled with selection_color(), which defaults to FL_RED.
Definition at line 48 of file Fl_Round_Button.H.
Constructor & Destructor Documentation
Fl_Round_Button::Fl_Round_Button (int X, int Y, int W, int H, const char * l = 0)
Creates a new Fl_Round_Button widget using the given position, size, and label string.
Definition at line 39 of file Fl_Round_Button.cxx.
References Fl_Widget::box(), Fl_Button::down_box(), FL_FOREGROUND_COLOR, FL_NO_BOX, FL_ROUND_DOWN_BOX, and Fl_Widget::selection_color().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Round_Button.H
fltk-1.3.0rc3/src/Fl_Round_Button.cxx