SfR Fresh Dox - fltk: Fl_PostScript_Graphics_Driver Class Reference
Fl_PostScript_Graphics_Driver Class Reference
PostScript graphical backend.
#include <Fl_PostScript.H>
Classes
class Clip
Public Types
enum SHAPE {
NONE = 0, LINE, LOOP, POLYGON,
POINTS
}
Public Member Functions
void concat ()
void reconcat ()
void recover ()
void reset ()
int start_postscript (int pagecount, enum Fl_Paged_Device::Page_Format format, enum Fl_Paged_Device::Page_Layout layout)
void draw (const char *s, int n, int x, int y)
see fl_draw(const char *str, int n, int x, int y).
void draw (int angle, const char *str, int n, int x, int y)
see fl_draw(int angle, const char *str, int n, int x, int y).
void rtl_draw (const char *s, int n, int x, int y)
see fl_rtl_draw(const char *str, int n, int x, int y).
void transformed_draw (const char *s, int n, double x, double y)
void transformed_draw (const char *s, double x, double y)
int alpha_mask (const uchar *data, int w, int h, int D, int LD=0)
void draw_scaled_image (const uchar *data, double x, double y, double w, double h, int iw, int ih, int D=3, int LD=0)
void draw_scaled_image_mono (const uchar *data, double x, double y, double w, double h, int iw, int ih, int D=3, int LD=0)
void draw_scaled_image (Fl_Draw_Image_Cb call, void *data, double x, double y, double w, double h, int iw, int ih, int D)
void draw_scaled_image_mono (Fl_Draw_Image_Cb call, void *data, double x, double y, double w, double h, int iw, int ih, int D)
void color (Fl_Color c)
see fl_color(Fl_Color c).
void color (uchar r, uchar g, uchar b)
see fl_color(uchar r, uchar g, uchar b).
void push_clip (int x, int y, int w, int h)
see fl_push_clip(int x, int y, int w, int h).
int clip_box (int x, int y, int w, int h, int &X, int &Y, int &W, int &H)
see fl_clip_box(int x, int y, int w, int h, int &X, int &Y, int &W, int &H).
int not_clipped (int x, int y, int w, int h)
see fl_not_clipped(int x, int y, int w, int h).
void push_no_clip ()
see fl_push_no_clip().
void pop_clip ()
see fl_pop_clip().
void line_style (int style, int width=0, char *dashes=0)
see fl_line_style(int style, int width, char* dashes).
void rect (int x, int y, int w, int h)
see fl_rect(int x, int y, int w, int h).
void rectf (int x, int y, int w, int h)
see fl_rectf(int x, int y, int w, int h).
void xyline (int x, int y, int x1)
see fl_xyline(int x, int y, int x1).
void xyline (int x, int y, int x1, int y2)
see fl_xyline(int x, int y, int x1, int y2).
void xyline (int x, int y, int x1, int y2, int x3)
see fl_xyline(int x, int y, int x1, int y2, int x3).
void yxline (int x, int y, int y1)
see fl_yxline(int x, int y, int y1).
void yxline (int x, int y, int y1, int x2)
see fl_yxline(int x, int y, int y1, int x2).
void yxline (int x, int y, int y1, int x2, int y3)
see fl_yxline(int x, int y, int y1, int x2, int y3).
void line (int x1, int y1, int x2, int y2)
see fl_line(int x, int y, int x1, int y1).
void line (int x1, int y1, int x2, int y2, int x3, int y3)
see fl_line(int x, int y, int x1, int y1, int x2, int y2).
void loop (int x0, int y0, int x1, int y1, int x2, int y2)
see fl_loop(int x0, int y0, int x1, int y1, int x2, int y2).
void loop (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3)
see fl_loop(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3).
void polygon (int x0, int y0, int x1, int y1, int x2, int y2)
see fl_polygon(int x0, int y0, int x1, int y1, int x2, int y2).
void polygon (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3)
see fl_polygon(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3).
void point (int x, int y)
see fl_point(int x, int y).
void begin_points ()
see fl_begin_points().
void begin_line ()
see fl_begin_line().
void begin_loop ()
see fl_begin_loop().
void begin_polygon ()
see fl_begin_polygon().
void vertex (double x, double y)
see fl_vertex(double x, double y).
void curve (double x, double y, double x1, double y1, double x2, double y2, double x3, double y3)
see fl_curve(double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3).
void circle (double x, double y, double r)
see fl_circle(double x, double y, double r).
void arc (double x, double y, double r, double start, double a)
see fl_arc(double x, double y, double r, double start, double end).
void arc (int x, int y, int w, int h, double a1, double a2)
see fl_arc(int x, int y, int w, int h, double a1, double a2).
void pie (int x, int y, int w, int h, double a1, double a2)
see fl_pie(int x, int y, int w, int h, double a1, double a2).
void end_points ()
see fl_end_points().
void end_line ()
see fl_end_line().
void end_loop ()
see fl_end_loop().
void end_polygon ()
see fl_end_polygon().
void begin_complex_polygon ()
see fl_begin_complex_polygon().
void gap ()
see fl_gap().
void end_complex_polygon ()
see fl_end_complex_polygon().
void transformed_vertex (double x, double y)
see fl_transformed_vertex(double xf, double yf).
void font (int face, int size)
see fl_font(Fl_Font face, Fl_Fontsize size).
int font ()
int size ()
double width (unsigned c)
double width (const char *s, int n)
int descent ()
int height ()
void draw_image (const uchar *d, int x, int y, int w, int h, int delta=3, int ldelta=0)
see fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L).
void draw_image_mono (const uchar *d, int x, int y, int w, int h, int delta=1, int ld=0)
see fl_draw_image_mono(const uchar* buf, int X,int Y,int W,int H, int D, int L).
void draw_image (Fl_Draw_Image_Cb call, void *data, int x, int y, int w, int h, int delta=3)
see fl_draw_image(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
void draw_image_mono (Fl_Draw_Image_Cb call, void *data, int x, int y, int w, int h, int delta=1)
see fl_draw_image_mono(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
void page_policy (int p)
int page_policy ()
void close_command (int(*cmd)(FILE *))
FILE * file ()
void interpolate (int i)
int interpolate ()
void page (double pw, double ph, int media=0)
void page (int format)
void place (double x, double y, double tx, double ty, double scale=1)
Fl_PostScript_Graphics_Driver ()
The constructor.
void draw (Fl_Pixmap *pxm, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_Pixmap object to the device.
void draw (Fl_Bitmap *bitmap, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_Bitmap object to the device.
void draw (Fl_RGB_Image *rgb, int XP, int YP, int WP, int HP, int cx, int cy)
Draws an Fl_RGB_Image object to the device.
~Fl_PostScript_Graphics_Driver ()
The destructor.
Public Attributes
Clip * clip_
int lang_level_
int font_
int size_
int gap_
int pages_
double width_
double height_
int shape_
int linewidth_
int linestyle_
int interpolate_
unsigned char cr_
unsigned char cg_
unsigned char cb_
char linedash_ [256]
uchar * mask
int mx
int my
int(* close_cmd_)(FILE *)
int page_policy_
int nPages
int orientation_
float scale_x
float scale_y
float angle
int left_margin
int top_margin
FILE * output
double pw_
double ph_
uchar bg_r
uchar bg_g
uchar bg_b
enum Fl_Paged_Device::Page_Format page_format_
char * ps_filename_
Static Public Attributes
static const char * class_id = "Fl_PostScript_Graphics_Driver"
A string that identifies each subclass of Fl_Device.
Detailed Description
PostScript graphical backend.
PostScript text uses vectorial fonts for the latin alphabet (exactly: all unicode characters between U+0020 and U+017F, that is, ASCII, Latin-1 Supplement and Latin Extended-A charts) plus a few other characters:
Char Codepoint Name Char Codepoint Name Char Codepoint Name
U+0192 florin U+201A quotesinglbase U+2122 trademark
U+02C6 circumflex U+201C quotedblleft U+2202 partialdiff
U+02C7 caron U+201D quotedblright U+2206 Delta
U+02D8 breve U+201E quotedblbase U+2211 summation
U+02D9 dotaccent U+2020 dagger U+221A radical
U+02DA ring U+2021 daggerdbl U+221E infinity
U+02DB ogonek U+2022 bullet U+2260 notequal
U+02DC tilde U+2026 ellipsis U+2264 lessequal
U+02DD hungarumlaut U+2030 perthousand U+2265 greaterequal
U+2013 endash U+2039 guilsinglleft U+25CA lozenge
U+2014 emdash U+203A guilsinglright U+FB01 fi
U+2018 quoteleft / U+2044 fraction U+FB02 fl
U+2019 quoteright U+20AC Euro U+F8FF apple (Mac OS only)
All other unicode characters are output as a bitmap.
FLTK standard fonts are output using PostScript standard fonts: Helvetica, Courier, Times (and their bold, oblique, italic variants).
Definition at line 64 of file Fl_PostScript.H.
Member Enumeration Documentation
enum Fl_PostScript_Graphics_Driver::SHAPE
Enumerator:
NONE
LINE
LOOP
POLYGON
POINTS
Definition at line 69 of file Fl_PostScript.H.
Constructor & Destructor Documentation
Fl_PostScript_Graphics_Driver::Fl_PostScript_Graphics_Driver (void)
The constructor.
Definition at line 43 of file Fl_PostScript.cxx.
References bg_b, bg_g, bg_r, class_id, Fl_Device::class_name(), close_cmd_, lang_level_, mask, NULL, ps_filename_, scale_x, and scale_y.
Fl_PostScript_Graphics_Driver::~Fl_PostScript_Graphics_Driver ()
The destructor.
Definition at line 56 of file Fl_PostScript.cxx.
References ps_filename_.
Member Function Documentation
int Fl_PostScript_Graphics_Driver::alpha_mask (const uchar * data, int w, int h, int D, int LD = 0)
mask row index
Definition at line 39 of file ps_image.cxx.
References h, i, mask, mx, my, val, and w.
Referenced by draw().
void Fl_PostScript_Graphics_Driver::arc (double x, double y, double r, double start, double end) [virtual]
see fl_arc(double x, double y, double r, double start, double end).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1205 of file Fl_PostScript.cxx.
References gap_, NONE, and shape_.
Referenced by arc(), and pie().
void Fl_PostScript_Graphics_Driver::arc (int x, int y, int w, int h, double a1, double a2) [virtual]
see fl_arc(int x, int y, int w, int h, double a1, double a2).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1215 of file Fl_PostScript.cxx.
References arc(), begin_line(), and end_line().
void Fl_PostScript_Graphics_Driver::begin_complex_polygon () [inline, virtual]
see fl_begin_complex_polygon().
Reimplemented from Fl_Graphics_Driver.
Definition at line 179 of file Fl_PostScript.H.
References begin_polygon().
void Fl_PostScript_Graphics_Driver::begin_line () [virtual]
see fl_begin_line().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1141 of file Fl_PostScript.cxx.
References concat(), gap_, LINE, and shape_.
Referenced by arc().
void Fl_PostScript_Graphics_Driver::begin_loop () [virtual]
see fl_begin_loop().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1149 of file Fl_PostScript.cxx.
References concat(), gap_, LOOP, and shape_.
void Fl_PostScript_Graphics_Driver::begin_points () [virtual]
see fl_begin_points().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1132 of file Fl_PostScript.cxx.
References concat(), gap_, POINTS, and shape_.
void Fl_PostScript_Graphics_Driver::begin_polygon () [virtual]
see fl_begin_polygon().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1157 of file Fl_PostScript.cxx.
References concat(), gap_, POLYGON, and shape_.
Referenced by begin_complex_polygon(), and pie().
void Fl_PostScript_Graphics_Driver::circle (double x, double y, double r) [virtual]
see fl_circle(double x, double y, double r).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1190 of file Fl_PostScript.cxx.
References concat(), NONE, reconcat(), and shape_.
int Fl_PostScript_Graphics_Driver::clip_box (int x, int y, int w, int h, int & X, int & Y, int & W, int & H) [virtual]
see fl_clip_box(int x, int y, int w, int h, int &X, int &Y, int &W, int &H).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1325 of file Fl_PostScript.cxx.
References clip_, Fl_PostScript_Graphics_Driver::Clip::h, h, Fl_PostScript_Graphics_Driver::Clip::w, w, Fl_PostScript_Graphics_Driver::Clip::x, x, Fl_PostScript_Graphics_Driver::Clip::y, and y.
Referenced by not_clipped(), and push_clip().
void Fl_PostScript_Graphics_Driver::close_command (int(*)(FILE *) cmd) [inline]
Definition at line 200 of file Fl_PostScript.H.
References close_cmd_.
Referenced by Fl_PostScript_File_Device::start_job().
void Fl_PostScript_Graphics_Driver::color (Fl_Color c) [virtual]
see fl_color(Fl_Color c).
Reimplemented from Fl_Graphics_Driver.
Definition at line 938 of file Fl_PostScript.cxx.
References cb_, cg_, cr_, and Fl::get_color().
Referenced by recover().
void Fl_PostScript_Graphics_Driver::color (uchar r, uchar g, uchar b) [virtual]
see fl_color(uchar r, uchar g, uchar b).
Reimplemented from Fl_Graphics_Driver.
Definition at line 943 of file Fl_PostScript.cxx.
References b, cb_, cg_, cr_, fl_color_, fl_rgb_color(), and output.
void Fl_PostScript_Graphics_Driver::concat ()
Definition at line 1121 of file Fl_PostScript.cxx.
References matrix::a, matrix::b, matrix::c, matrix::d, matrix::x, and matrix::y.
Referenced by begin_line(), begin_loop(), begin_points(), begin_polygon(), circle(), and transformed_vertex().
void Fl_PostScript_Graphics_Driver::curve (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3) [virtual]
see fl_curve(double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1178 of file Fl_PostScript.cxx.
References gap_, NONE, and shape_.
int Fl_PostScript_Graphics_Driver::descent ()
void Fl_PostScript_Graphics_Driver::draw (Fl_Pixmap * pxm, int XP, int YP, int WP, int HP, int cx, int cy) [virtual]
Draws an Fl_Pixmap object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Graphics_Driver.
Definition at line 461 of file ps_image.cxx.
References Fl_Image::data(), FL_BLACK, fl_draw_pixmap(), fl_measure_pixmap(), h, mask, mx, my, pop_clip(), push_clip(), and w.
void Fl_PostScript_Graphics_Driver::draw (Fl_Bitmap * bm, int XP, int YP, int WP, int HP, int cx, int cy) [virtual]
Draws an Fl_Bitmap object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Graphics_Driver.
Definition at line 491 of file ps_image.cxx.
References Fl_Bitmap::array, Fl_Image::h(), h, i, output, pop_clip(), push_clip(), Fl_Image::w(), and w.
void Fl_PostScript_Graphics_Driver::draw (Fl_RGB_Image * rgb, int XP, int YP, int WP, int HP, int cx, int cy) [virtual]
Draws an Fl_RGB_Image object to the device.
Specifies a bounding box for the image, with the origin (upper left-hand corner) of the image offset by the cx and cy arguments.
Reimplemented from Fl_Graphics_Driver.
Definition at line 477 of file ps_image.cxx.
References alpha_mask(), Fl_RGB_Image::array, Fl_Image::d(), draw_scaled_image(), Fl_Image::h(), h, lang_level_, Fl_Image::ld(), mask, pop_clip(), push_clip(), Fl_Image::w(), and w.
void Fl_PostScript_Graphics_Driver::draw (const char * str, int n, int x, int y) [inline, virtual]
see fl_draw(const char *str, int n, int x, int y).
Reimplemented from Fl_Graphics_Driver.
Definition at line 120 of file Fl_PostScript.H.
References transformed_draw().
void Fl_PostScript_Graphics_Driver::draw (int angle, const char * str, int n, int x, int y) [virtual]
see fl_draw(int angle, const char *str, int n, int x, int y).
Reimplemented from Fl_Graphics_Driver.
Definition at line 958 of file Fl_PostScript.cxx.
References output, and transformed_draw().
void Fl_PostScript_Graphics_Driver::draw_image (const uchar * buf, int X, int Y, int W, int H, int D = 3, int L = 0) [inline, virtual]
see fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L).
Reimplemented from Fl_Graphics_Driver.
Definition at line 192 of file Fl_PostScript.H.
References draw_scaled_image().
void Fl_PostScript_Graphics_Driver::draw_image (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 3) [inline, virtual]
see fl_draw_image(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
Reimplemented from Fl_Graphics_Driver.
Definition at line 194 of file Fl_PostScript.H.
References draw_scaled_image().
void Fl_PostScript_Graphics_Driver::draw_image_mono (const uchar * buf, int X, int Y, int W, int H, int D = 1, int L = 0) [inline, virtual]
see fl_draw_image_mono(const uchar* buf, int X,int Y,int W,int H, int D, int L).
Reimplemented from Fl_Graphics_Driver.
Definition at line 193 of file Fl_PostScript.H.
References draw_scaled_image_mono().
void Fl_PostScript_Graphics_Driver::draw_image_mono (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 1) [inline, virtual]
see fl_draw_image_mono(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D).
Reimplemented from Fl_Graphics_Driver.
Definition at line 195 of file Fl_PostScript.H.
References draw_scaled_image_mono().
void Fl_PostScript_Graphics_Driver::draw_scaled_image (const uchar * data, double x, double y, double w, double h, int iw, int ih, int D = 3, int LD = 0)
Definition at line 198 of file ps_image.cxx.
References bg_b, bg_g, bg_r, draw_scaled_image_mono(), i, interpolate_, lang_level_, mask, mx, my, and output.
Referenced by draw(), and draw_image().
void Fl_PostScript_Graphics_Driver::draw_scaled_image (Fl_Draw_Image_Cb call, void * data, double x, double y, double w, double h, int iw, int ih, int D)
Definition at line 265 of file ps_image.cxx.
References i, interpolate_, lang_level_, mask, mx, my, and output.
void Fl_PostScript_Graphics_Driver::draw_scaled_image_mono (const uchar * data, double x, double y, double w, double h, int iw, int ih, int D = 3, int LD = 0)
Definition at line 351 of file ps_image.cxx.
References bg_b, bg_g, bg_r, i, interpolate_, lang_level_, mask, mx, my, and output.
Referenced by draw_image_mono(), and draw_scaled_image().
void Fl_PostScript_Graphics_Driver::draw_scaled_image_mono (Fl_Draw_Image_Cb call, void * data, double x, double y, double w, double h, int iw, int ih, int D)
Definition at line 412 of file ps_image.cxx.
References i, interpolate_, lang_level_, mask, mx, my, and output.
void Fl_PostScript_Graphics_Driver::end_complex_polygon () [inline, virtual]
see fl_end_complex_polygon().
Reimplemented from Fl_Graphics_Driver.
Definition at line 181 of file Fl_PostScript.H.
References end_polygon().
void Fl_PostScript_Graphics_Driver::end_line () [virtual]
see fl_end_line().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1254 of file Fl_PostScript.cxx.
References gap_, NONE, reconcat(), and shape_.
Referenced by arc().
void Fl_PostScript_Graphics_Driver::end_loop () [virtual]
see fl_end_loop().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1261 of file Fl_PostScript.cxx.
References gap_, NONE, reconcat(), and shape_.
void Fl_PostScript_Graphics_Driver::end_points () [virtual]
see fl_end_points().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1246 of file Fl_PostScript.cxx.
References gap_, NONE, reconcat(), and shape_.
void Fl_PostScript_Graphics_Driver::end_polygon () [virtual]
see fl_end_polygon().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1269 of file Fl_PostScript.cxx.
References gap_, NONE, reconcat(), and shape_.
Referenced by end_complex_polygon(), and pie().
FILE* Fl_PostScript_Graphics_Driver::file () [inline]
Definition at line 201 of file Fl_PostScript.H.
References output.
void Fl_PostScript_Graphics_Driver::font (int face, int size) [virtual]
see fl_font(Fl_Font face, Fl_Fontsize size).
Reimplemented from Fl_Graphics_Driver.
Definition at line 929 of file Fl_PostScript.cxx.
References Fl_Display_Device::display_device(), Fl_Surface_Device::driver(), f, FL_COURIER, FL_FREE_FONT, font_, output, and size_.
int Fl_PostScript_Graphics_Driver::font () [inline]
Definition at line 185 of file Fl_PostScript.H.
References font_.
Referenced by recover().
void Fl_PostScript_Graphics_Driver::gap () [inline, virtual]
see fl_gap().
Reimplemented from Fl_Graphics_Driver.
Definition at line 180 of file Fl_PostScript.H.
References gap_.
int Fl_PostScript_Graphics_Driver::height ()
void Fl_PostScript_Graphics_Driver::interpolate (int i) [inline]
Definition at line 205 of file Fl_PostScript.H.
References i, and interpolate_.
int Fl_PostScript_Graphics_Driver::interpolate () [inline]
Definition at line 206 of file Fl_PostScript.H.
References interpolate_.
void Fl_PostScript_Graphics_Driver::line (int x, int y, int x1, int y1, int x2, int y2) [virtual]
see fl_line(int x, int y, int x1, int y1, int x2, int y2).
Reimplemented from Fl_Graphics_Driver.
Definition at line 711 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::line (int x, int y, int x1, int y1) [virtual]
see fl_line(int x, int y, int x1, int y1).
Reimplemented from Fl_Graphics_Driver.
Definition at line 705 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::line_style (int style, int width = 0, char * dashes = 0) [virtual]
see fl_line_style(int style, int width, char* dashes).
Reimplemented from Fl_Graphics_Driver.
Definition at line 851 of file Fl_PostScript.cxx.
References FL_CAP_SQUARE, linedash_, linestyle_, linewidth_, output, and width().
Referenced by page(), and recover().
void Fl_PostScript_Graphics_Driver::loop (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3) [virtual]
see fl_loop(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3).
Reimplemented from Fl_Graphics_Driver.
Definition at line 795 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::loop (int x0, int y0, int x1, int y1, int x2, int y2) [virtual]
see fl_loop(int x0, int y0, int x1, int y1, int x2, int y2).
Reimplemented from Fl_Graphics_Driver.
Definition at line 785 of file Fl_PostScript.cxx.
References output.
int Fl_PostScript_Graphics_Driver::not_clipped (int x, int y, int w, int h) [virtual]
see fl_not_clipped(int x, int y, int w, int h).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1361 of file Fl_PostScript.cxx.
References clip_, clip_box(), H, and Fl_PostScript_Graphics_Driver::Clip::w.
void Fl_PostScript_Graphics_Driver::page (double pw, double ph, int media = 0)
Definition at line 624 of file Fl_PostScript.cxx.
References lang_level_, line_style(), Fl_Paged_Device::MEDIA, nPages, output, ph, ph_, pw, pw_, reset(), and Fl_Paged_Device::REVERSED.
Referenced by page(), and Fl_PostScript_File_Device::start_page().
void Fl_PostScript_Graphics_Driver::page (int format)
Definition at line 673 of file Fl_PostScript.cxx.
References Fl_Paged_Device::LANDSCAPE, page(), Fl_Paged_Device::page_formats, ph_, and pw_.
void Fl_PostScript_Graphics_Driver::page_policy (int p)
Definition at line 614 of file Fl_PostScript.cxx.
References lang_level_, output, and page_policy_.
int Fl_PostScript_Graphics_Driver::page_policy () [inline]
Definition at line 199 of file Fl_PostScript.H.
References page_policy_.
void Fl_PostScript_Graphics_Driver::pie (int x, int y, int w, int h, double a1, double a2) [virtual]
see fl_pie(int x, int y, int w, int h, double a1, double a2).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1234 of file Fl_PostScript.cxx.
References arc(), begin_polygon(), end_polygon(), and vertex().
void Fl_PostScript_Graphics_Driver::place (double x, double y, double tx, double ty, double scale = 1)
void Fl_PostScript_Graphics_Driver::point (int x, int y) [virtual]
see fl_point(int x, int y).
Reimplemented from Fl_Graphics_Driver.
Definition at line 828 of file Fl_PostScript.cxx.
References rectf().
void Fl_PostScript_Graphics_Driver::polygon (int x0, int y0, int x1, int y1, int x2, int y2) [virtual]
see fl_polygon(int x0, int y0, int x1, int y1, int x2, int y2).
Reimplemented from Fl_Graphics_Driver.
Definition at line 806 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::polygon (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3) [virtual]
see fl_polygon(int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3).
Reimplemented from Fl_Graphics_Driver.
Definition at line 816 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::pop_clip () [virtual]
see fl_pop_clip().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1312 of file Fl_PostScript.cxx.
References clip_, Fl_PostScript_Graphics_Driver::Clip::h, lang_level_, Fl_PostScript_Graphics_Driver::Clip::prev, recover(), Fl_PostScript_Graphics_Driver::Clip::w, Fl_PostScript_Graphics_Driver::Clip::x, and Fl_PostScript_Graphics_Driver::Clip::y.
Referenced by draw().
void Fl_PostScript_Graphics_Driver::push_clip (int x, int y, int w, int h) [virtual]
see fl_push_clip(int x, int y, int w, int h).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1290 of file Fl_PostScript.cxx.
References clip_, clip_box(), Fl_PostScript_Graphics_Driver::Clip::h, lang_level_, Fl_PostScript_Graphics_Driver::Clip::prev, recover(), Fl_PostScript_Graphics_Driver::Clip::w, Fl_PostScript_Graphics_Driver::Clip::x, and Fl_PostScript_Graphics_Driver::Clip::y.
Referenced by draw().
void Fl_PostScript_Graphics_Driver::push_no_clip () [virtual]
see fl_push_no_clip().
Reimplemented from Fl_Graphics_Driver.
Definition at line 1302 of file Fl_PostScript.cxx.
References clip_, Fl_PostScript_Graphics_Driver::Clip::h, lang_level_, Fl_PostScript_Graphics_Driver::Clip::prev, recover(), Fl_PostScript_Graphics_Driver::Clip::w, Fl_PostScript_Graphics_Driver::Clip::x, and Fl_PostScript_Graphics_Driver::Clip::y.
void Fl_PostScript_Graphics_Driver::reconcat ()
Definition at line 1125 of file Fl_PostScript.cxx.
References matrix::a, matrix::b, matrix::c, matrix::d, matrix::x, and matrix::y.
Referenced by circle(), end_line(), end_loop(), end_points(), end_polygon(), and transformed_vertex().
void Fl_PostScript_Graphics_Driver::recover ()
Definition at line 589 of file Fl_PostScript.cxx.
References cb_, cg_, color(), cr_, font(), font_, line_style(), linedash_, linestyle_, linewidth_, and size_.
Referenced by pop_clip(), push_clip(), and push_no_clip().
void Fl_PostScript_Graphics_Driver::rect (int x, int y, int w, int h) [virtual]
see fl_rect(int x, int y, int w, int h).
Reimplemented from Fl_Graphics_Driver.
Definition at line 686 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::rectf (int x, int y, int w, int h) [virtual]
see fl_rectf(int x, int y, int w, int h).
Reimplemented from Fl_Graphics_Driver.
Definition at line 701 of file Fl_PostScript.cxx.
References output.
Referenced by point().
void Fl_PostScript_Graphics_Driver::reset ()
Definition at line 595 of file Fl_PostScript.cxx.
References cb_, cg_, clip_, cr_, FL_HELVETICA, FL_SOLID, font_, gap_, linedash_, linestyle_, linewidth_, Fl_PostScript_Graphics_Driver::Clip::prev, and size_.
Referenced by Fl_PostScript_File_Device::end_job(), page(), and start_postscript().
void Fl_PostScript_Graphics_Driver::rtl_draw (const char * str, int n, int x, int y) [virtual]
see fl_rtl_draw(const char *str, int n, int x, int y).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1097 of file Fl_PostScript.cxx.
References fl_utf8decode(), fl_utf8encode(), fl_width(), and transformed_draw().
int Fl_PostScript_Graphics_Driver::size () [inline]
Definition at line 186 of file Fl_PostScript.H.
References size_.
int Fl_PostScript_Graphics_Driver::start_postscript (int pagecount, enum Fl_Paged_Device::Page_Format format, enum Fl_Paged_Device::Page_Layout layout)
Definition at line 531 of file Fl_PostScript.cxx.
References Fl_Paged_Device::A4, h, Fl_Paged_Device::LANDSCAPE, lang_level_, left_margin, name, nPages, output, page_format_, Fl_Paged_Device::page_formats, page_policy_, pages_, reset(), top_margin, w, and x.
Referenced by Fl_PostScript_File_Device::start_job().
void Fl_PostScript_Graphics_Driver::transformed_draw (const char * s, double x, double y)
void Fl_PostScript_Graphics_Driver::transformed_draw (const char * s, int n, double x, double y)
Definition at line 1061 of file Fl_PostScript.cxx.
References fl_utf8decode(), fl_width(), int, and width().
Referenced by draw(), and rtl_draw().
void Fl_PostScript_Graphics_Driver::transformed_vertex (double xf, double yf) [virtual]
see fl_transformed_vertex(double xf, double yf).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1278 of file Fl_PostScript.cxx.
References concat(), gap_, and reconcat().
void Fl_PostScript_Graphics_Driver::vertex (double x, double y) [virtual]
see fl_vertex(double x, double y).
Reimplemented from Fl_Graphics_Driver.
Definition at line 1165 of file Fl_PostScript.cxx.
References gap_, POINTS, and shape_.
Referenced by pie().
double Fl_PostScript_Graphics_Driver::width (const char * s, int n)
double Fl_PostScript_Graphics_Driver::width (unsigned c)
Referenced by line_style(), and transformed_draw().
void Fl_PostScript_Graphics_Driver::xyline (int x, int y, int x1, int y2, int x3) [virtual]
see fl_xyline(int x, int y, int x1, int y2, int x3).
Reimplemented from Fl_Graphics_Driver.
Definition at line 721 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::xyline (int x, int y, int x1, int y2) [virtual]
see fl_xyline(int x, int y, int x1, int y2).
Reimplemented from Fl_Graphics_Driver.
Definition at line 733 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::xyline (int x, int y, int x1) [virtual]
see fl_xyline(int x, int y, int x1).
Reimplemented from Fl_Graphics_Driver.
Definition at line 744 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::yxline (int x, int y, int y1, int x2, int y3) [virtual]
see fl_yxline(int x, int y, int y1, int x2, int y3).
Reimplemented from Fl_Graphics_Driver.
Definition at line 754 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::yxline (int x, int y, int y1, int x2) [virtual]
see fl_yxline(int x, int y, int y1, int x2).
Reimplemented from Fl_Graphics_Driver.
Definition at line 766 of file Fl_PostScript.cxx.
References output.
void Fl_PostScript_Graphics_Driver::yxline (int x, int y, int y1) [virtual]
see fl_yxline(int x, int y, int y1).
Reimplemented from Fl_Graphics_Driver.
Definition at line 776 of file Fl_PostScript.cxx.
References output.
Member Data Documentation
float Fl_PostScript_Graphics_Driver::angle
Definition at line 109 of file Fl_PostScript.H.
Referenced by Fl_PostScript_File_Device::origin(), Fl_PostScript_File_Device::rotate(), Fl_PostScript_File_Device::scale(), and Fl_PostScript_File_Device::start_page().
uchar Fl_PostScript_Graphics_Driver::bg_b
Definition at line 116 of file Fl_PostScript.H.
Referenced by draw_scaled_image(), draw_scaled_image_mono(), and Fl_PostScript_Graphics_Driver().
uchar Fl_PostScript_Graphics_Driver::bg_g
Definition at line 116 of file Fl_PostScript.H.
Referenced by draw_scaled_image(), draw_scaled_image_mono(), and Fl_PostScript_Graphics_Driver().
uchar Fl_PostScript_Graphics_Driver::bg_r
Definition at line 116 of file Fl_PostScript.H.
Referenced by draw_scaled_image(), draw_scaled_image_mono(), and Fl_PostScript_Graphics_Driver().
unsigned char Fl_PostScript_Graphics_Driver::cb_
Definition at line 91 of file Fl_PostScript.H.
Referenced by color(), recover(), and reset().
unsigned char Fl_PostScript_Graphics_Driver::cg_
Definition at line 91 of file Fl_PostScript.H.
Referenced by color(), recover(), and reset().
const char * Fl_PostScript_Graphics_Driver::class_id = "Fl_PostScript_Graphics_Driver" [static]
A string that identifies each subclass of Fl_Device.
Function class_name() applied to a device of this class returns this string.
Reimplemented from Fl_Graphics_Driver.
Definition at line 66 of file Fl_PostScript.H.
Referenced by Fl_PostScript_Graphics_Driver().
Clip* Fl_PostScript_Graphics_Driver::clip_
Definition at line 76 of file Fl_PostScript.H.
Referenced by clip_box(), Fl_PostScript_File_Device::end_job(), not_clipped(), pop_clip(), push_clip(), push_no_clip(), and reset().
int(* Fl_PostScript_Graphics_Driver::close_cmd_)(FILE *)
Definition at line 102 of file Fl_PostScript.H.
Referenced by close_command(), Fl_PostScript_File_Device::end_job(), and Fl_PostScript_Graphics_Driver().
unsigned char Fl_PostScript_Graphics_Driver::cr_
Definition at line 91 of file Fl_PostScript.H.
Referenced by color(), recover(), and reset().
int Fl_PostScript_Graphics_Driver::font_
Definition at line 79 of file Fl_PostScript.H.
Referenced by font(), recover(), and reset().
int Fl_PostScript_Graphics_Driver::gap_
Definition at line 81 of file Fl_PostScript.H.
Referenced by arc(), begin_line(), begin_loop(), begin_points(), begin_polygon(), curve(), end_line(), end_loop(), end_points(), end_polygon(), gap(), reset(), transformed_vertex(), and vertex().
double Fl_PostScript_Graphics_Driver::height_
Definition at line 85 of file Fl_PostScript.H.
int Fl_PostScript_Graphics_Driver::interpolate_
Definition at line 90 of file Fl_PostScript.H.
Referenced by draw_scaled_image(), draw_scaled_image_mono(), and interpolate().
int Fl_PostScript_Graphics_Driver::lang_level_
Definition at line 78 of file Fl_PostScript.H.
Referenced by draw(), draw_scaled_image(), draw_scaled_image_mono(), Fl_PostScript_Graphics_Driver(), page(), page_policy(), pop_clip(), push_clip(), push_no_clip(), and start_postscript().
int Fl_PostScript_Graphics_Driver::left_margin
Definition at line 110 of file Fl_PostScript.H.
Referenced by Fl_PostScript_File_Device::margins(), Fl_PostScript_File_Device::origin(), Fl_PostScript_File_Device::printable_rect(), Fl_PostScript_File_Device::rotate(), Fl_PostScript_File_Device::scale(), Fl_PostScript_File_Device::start_page(), and start_postscript().
char Fl_PostScript_Graphics_Driver::linedash_[256]
Definition at line 92 of file Fl_PostScript.H.
Referenced by line_style(), recover(), and reset().
int Fl_PostScript_Graphics_Driver::linestyle_
Definition at line 89 of file Fl_PostScript.H.
Referenced by line_style(), recover(), and reset().
int Fl_PostScript_Graphics_Driver::linewidth_
Definition at line 88 of file Fl_PostScript.H.
Referenced by line_style(), recover(), and reset().
uchar* Fl_PostScript_Graphics_Driver::mask
Definition at line 98 of file Fl_PostScript.H.
Referenced by alpha_mask(), draw(), draw_scaled_image(), draw_scaled_image_mono(), and Fl_PostScript_Graphics_Driver().
int Fl_PostScript_Graphics_Driver::mx
Definition at line 99 of file Fl_PostScript.H.
Referenced by alpha_mask(), draw(), draw_scaled_image(), and draw_scaled_image_mono().
int Fl_PostScript_Graphics_Driver::my
Definition at line 100 of file Fl_PostScript.H.
Referenced by alpha_mask(), draw(), draw_scaled_image(), and draw_scaled_image_mono().
int Fl_PostScript_Graphics_Driver::nPages
Definition at line 104 of file Fl_PostScript.H.
Referenced by Fl_PostScript_File_Device::end_job(), page(), and start_postscript().
int Fl_PostScript_Graphics_Driver::orientation_
Definition at line 105 of file Fl_PostScript.H.
FILE* Fl_PostScript_Graphics_Driver::output
Definition at line 113 of file Fl_PostScript.H.
Referenced by color(), draw(), draw_scaled_image(), draw_scaled_image_mono(), Fl_PostScript_File_Device::end_job(), file(), font(), line(), line_style(), loop(), Fl_PostScript_File_Device::origin(), page(), page_policy(), polygon(), rect(), rectf(), Fl_PostScript_File_Device::rotate(), Fl_PostScript_File_Device::scale(), Fl_PostScript_File_Device::start_job(), Fl_PostScript_File_Device::start_page(), start_postscript(), xyline(), and yxline().
enum Fl_Paged_Device::Page_Format Fl_PostScript_Graphics_Driver::page_format_
Definition at line 131 of file Fl_PostScript.H.
Referenced by Fl_PostScript_File_Device::start_page(), and start_postscript().
int Fl_PostScript_Graphics_Driver::page_policy_
Definition at line 103 of file Fl_PostScript.H.
Referenced by page_policy(), and start_postscript().
int Fl_PostScript_Graphics_Driver::pages_
Definition at line 82 of file Fl_PostScript.H.
Referenced by Fl_PostScript_File_Device::end_job(), and start_postscript().
double Fl_PostScript_Graphics_Driver::ph_
Definition at line 114 of file Fl_PostScript.H.
Referenced by page(), and Fl_PostScript_File_Device::printable_rect().
char* Fl_PostScript_Graphics_Driver::ps_filename_
Definition at line 132 of file Fl_PostScript.H.
Referenced by Fl_PostScript_Graphics_Driver(), Fl_PostScript_File_Device::start_job(), and ~Fl_PostScript_Graphics_Driver().
double Fl_PostScript_Graphics_Driver::pw_
Definition at line 114 of file Fl_PostScript.H.
Referenced by page(), and Fl_PostScript_File_Device::printable_rect().
float Fl_PostScript_Graphics_Driver::scale_x
Definition at line 107 of file Fl_PostScript.H.
Referenced by Fl_PostScript_Graphics_Driver(), Fl_PostScript_File_Device::margins(), Fl_PostScript_File_Device::origin(), Fl_PostScript_File_Device::printable_rect(), Fl_PostScript_File_Device::rotate(), Fl_PostScript_File_Device::scale(), and Fl_PostScript_File_Device::start_page().
float Fl_PostScript_Graphics_Driver::scale_y
Definition at line 108 of file Fl_PostScript.H.
Referenced by Fl_PostScript_Graphics_Driver(), Fl_PostScript_File_Device::margins(), Fl_PostScript_File_Device::origin(), Fl_PostScript_File_Device::printable_rect(), Fl_PostScript_File_Device::rotate(), Fl_PostScript_File_Device::scale(), and Fl_PostScript_File_Device::start_page().
int Fl_PostScript_Graphics_Driver::shape_
Definition at line 87 of file Fl_PostScript.H.
Referenced by arc(), begin_line(), begin_loop(), begin_points(), begin_polygon(), circle(), curve(), end_line(), end_loop(), end_points(), end_polygon(), and vertex().
int Fl_PostScript_Graphics_Driver::size_
Definition at line 80 of file Fl_PostScript.H.
Referenced by font(), recover(), reset(), and size().
int Fl_PostScript_Graphics_Driver::top_margin
Definition at line 111 of file Fl_PostScript.H.
Referenced by Fl_PostScript_File_Device::margins(), Fl_PostScript_File_Device::origin(), Fl_PostScript_File_Device::printable_rect(), Fl_PostScript_File_Device::rotate(), Fl_PostScript_File_Device::scale(), Fl_PostScript_File_Device::start_page(), and start_postscript().
double Fl_PostScript_Graphics_Driver::width_
Definition at line 84 of file Fl_PostScript.H.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_PostScript.H
fltk-1.3.0rc3/src/Fl_PostScript.cxx
fltk-1.3.0rc3/src/ps_image.cxx