SfR Fresh Dox - fltk: Fl_Code_Type Class Reference
Fl_Code_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void open ()
virtual const char * type_name ()
int is_code_block () const
int pixmapID ()
virtual int is_public () const
Detailed Description
Definition at line 194 of file Fl_Type.h.
Member Function Documentation
int Fl_Code_Type::is_code_block () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 201 of file Fl_Type.h.
int Fl_Code_Type::is_public () const [virtual]
Reimplemented from Fl_Type.
Definition at line 691 of file Fl_Type.cxx.
Fl_Type * Fl_Code_Type::make () [virtual]
Implements Fl_Type.
Definition at line 431 of file Fl_Function_Type.cxx.
References Fl_Type::add(), Fl_Type::current, Fl_Type::factory, fl_message(), Fl_Type::is_code_block(), Fl_Type::name(), and Fl_Type::parent.
void Fl_Code_Type::open () [virtual]
Reimplemented from Fl_Type.
Definition at line 445 of file Fl_Function_Type.cxx.
References Fl_Text_Display::buffer(), c_check(), code_input, code_panel, code_panel_cancel, code_panel_ok, fl_alert(), Fl_Double_Window::hide(), make_code_panel(), Fl_Type::name(), Fl::readqueue(), Fl_Double_Window::show(), w, and Fl::wait().
int Fl_Code_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 202 of file Fl_Type.h.
virtual const char* Fl_Code_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 200 of file Fl_Type.h.
void Fl_Code_Type::write_code1 () [virtual]
Reimplemented from Fl_Type.
Definition at line 471 of file Fl_Function_Type.cxx.
References indent(), Fl_Type::name(), and write_c().
void Fl_Code_Type::write_code2 () [virtual]
Reimplemented from Fl_Type.
Definition at line 485 of file Fl_Function_Type.cxx.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx
fltk-1.3.0rc3/fluid/Fl_Type.cxx