SfR Fresh Dox - fltk: Fl_Widget_Type Class Reference
Fl_Widget_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
void setimage (Fluid_Image *)
void setinactive (Fluid_Image *)
Fl_Widget_Type ()
Fl_Type * make ()
void open ()
const char * extra_code (int n) const
void extra_code (int n, const char *)
const char * subclass () const
void subclass (const char *)
const char * tooltip () const
void tooltip (const char *)
const char * image_name () const
void image_name (const char *)
const char * inactive_name () const
void inactive_name (const char *)
uchar hotspot () const
void hotspot (uchar v)
uchar resizable () const
void resizable (uchar v)
virtual int textstuff (int what, Fl_Font &, int &, Fl_Color &)
virtual Fl_Menu_Item * subtypes ()
virtual int is_widget () const
virtual int is_public () const
virtual void write_properties ()
virtual void read_property (const char *)
virtual int read_fdesign (const char *, const char *)
virtual Fl_Widget * enter_live_mode (int top=0)
virtual void leave_live_mode ()
virtual void copy_properties ()
virtual void ideal_size (int &w, int &h)
virtual void ideal_spacing (int &x, int &y)
~Fl_Widget_Type ()
void redraw ()
Public Attributes
const char * xclass
Fl_Widget * o
int public_
Fluid_Image * image
Fluid_Image * inactive
Static Public Attributes
static int default_size = FL_NORMAL_SIZE
Protected Member Functions
void write_static ()
void write_code1 ()
void write_widget_code ()
void write_extra_code ()
void write_block_close ()
void write_code2 ()
void write_color (const char *, Fl_Color)
Protected Attributes
Fl_Widget * live_widget
Detailed Description
Definition at line 333 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_Widget_Type::Fl_Widget_Type ()
Definition at line 205 of file Fl_Widget_Type.cxx.
References image, inactive, NUM_EXTRA_CODE, o, public_, and xclass.
Fl_Widget_Type::~Fl_Widget_Type ()
Definition at line 219 of file Fl_Widget_Type.cxx.
References Fl_Widget::hide(), NUM_EXTRA_CODE, o, and Fl_Widget::parent().
Member Function Documentation
void Fl_Widget_Type::copy_properties () [virtual]
copy all properties from the edit widget to the live widget
Reimplemented from Fl_Type.
Reimplemented in Fl_Input_Type, Fl_Group_Type, Fl_Pack_Type, Fl_Scroll_Type, Fl_Tile_Type, Fl_Window_Type, Fl_Menu_Type, and Fl_Input_Choice_Type.
Definition at line 2784 of file Fl_Widget_Type.cxx.
References Fl_Widget::active(), Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Button::down_box(), Fl_Widget::hide(), Fl_Type::is_button(), Fl_Type::is_input(), Fl_Type::is_spinner(), Fl_Type::is_text_display(), Fl_Type::is_valuator(), Fl_Type::is_value_input(), Fl_Widget::label(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), live_widget, Fl_Spinner::maximum(), Fl_Valuator::maximum(), Fl_Spinner::minimum(), Fl_Valuator::minimum(), o, Fl_Widget::parent(), Fl_Group::resizable(), resizable(), Fl_Widget::selection_color(), Fl_Text_Display::shortcut(), Fl_Value_Input::shortcut(), Fl_Input_::shortcut(), Fl_Button::shortcut(), Fl_Slider::slider_size(), Fl_Spinner::step(), Fl_Valuator::step(), tooltip(), Fl_Widget::tooltip(), Fl_Widget::type(), Fl_Spinner::value(), Fl_Valuator::value(), Fl_Button::value(), Fl_Widget::visible(), and w.
Referenced by enter_live_mode().
Fl_Widget * Fl_Widget_Type::enter_live_mode (int top = 0) [virtual]
Build widgets and dataset needed in live mode.
Returns:
a widget pointer that the live mode initiator can 'show()'
See also:
leave_live_mode()
Reimplemented from Fl_Type.
Reimplemented in Fl_Group_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, and Fl_Window_Type.
Definition at line 2771 of file Fl_Widget_Type.cxx.
References copy_properties(), Fl_Widget::h(), live_widget, Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by live_mode_cb().
const char* Fl_Widget_Type::extra_code (int n) const [inline]
Definition at line 372 of file Fl_Type.h.
Referenced by read_fdesign(), read_property(), v_input_cb(), write_code1(), Fl_Menu_Item_Type::write_code1(), write_extra_code(), write_properties(), write_static(), and Fl_Menu_Item_Type::write_static().
void Fl_Widget_Type::extra_code (int n, const char * n)
Definition at line 234 of file Fl_Widget_Type.cxx.
References storestring().
uchar Fl_Widget_Type::hotspot () const [inline]
Definition at line 382 of file Fl_Type.h.
Referenced by Fl_Menu_Item_Type::flags(), hotspot_cb(), read_property(), write_properties(), and write_widget_code().
void Fl_Widget_Type::hotspot (uchar v) [inline]
Definition at line 383 of file Fl_Type.h.
void Fl_Widget_Type::ideal_size (int & w, int & h) [virtual]
Reimplemented in Fl_Button_Type, Fl_Return_Button_Type, Fl_Light_Button_Type, Fl_Check_Button_Type, Fl_Round_Button_Type, Fl_Browser_Type, Fl_Check_Browser_Type, Fl_Tree_Type, Fl_File_Browser_Type, Fl_Spinner_Type, Fl_Input_Type, Fl_File_Input_Type, Fl_Text_Display_Type, Fl_Text_Editor_Type, Fl_Help_View_Type, Fl_Output_Type, Fl_Value_Input_Type, Fl_Value_Output_Type, Fl_Menu_Button_Type, Fl_Choice_Type, Fl_Input_Choice_Type, and Fl_Menu_Bar_Type.
Definition at line 81 of file Fl_Widget_Type.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dw(), Fl_Widget::labelsize(), Fl_Widget::measure_label(), and o.
Referenced by Fl_Window_Type::draw_overlay().
void Fl_Widget_Type::ideal_spacing (int & x, int & y) [virtual]
Reimplemented in Fl_Tabs_Type.
Definition at line 94 of file Fl_Widget_Type.cxx.
References Fl_Widget::labelsize(), and o.
Referenced by Fl_Window_Type::draw_overlay().
void Fl_Widget_Type::image_name (const char * n)
Definition at line 249 of file Fl_Widget_Type.cxx.
References Fluid_Image::find(), setimage(), and storestring().
const char* Fl_Widget_Type::image_name () const [inline]
Definition at line 378 of file Fl_Type.h.
Referenced by read_property(), and write_properties().
void Fl_Widget_Type::inactive_name (const char * n)
Definition at line 254 of file Fl_Widget_Type.cxx.
References Fluid_Image::find(), setinactive(), and storestring().
const char* Fl_Widget_Type::inactive_name () const [inline]
Definition at line 380 of file Fl_Type.h.
Referenced by read_property(), and write_properties().
int Fl_Widget_Type::is_public () const [virtual]
Reimplemented from Fl_Type.
Definition at line 62 of file Fl_Widget_Type.cxx.
References public_.
int Fl_Widget_Type::is_widget () const [virtual]
Reimplemented from Fl_Type.
Definition at line 61 of file Fl_Widget_Type.cxx.
Referenced by h_cb(), image_browse_cb(), image_cb(), inactive_browse_cb(), inactive_cb(), tooltip_cb(), w_cb(), x_cb(), and y_cb().
void Fl_Widget_Type::leave_live_mode () [virtual]
Release all resources created when enetring live mode.
See also:
enter_live_mode()
Reimplemented from Fl_Type.
Reimplemented in Fl_Group_Type, and Fl_Window_Type.
Definition at line 2778 of file Fl_Widget_Type.cxx.
Fl_Type * Fl_Widget_Type::make () [virtual]
Implements Fl_Type.
Reimplemented in Fl_Group_Type, Fl_Window_Type, Fl_Widget_Class_Type, Fl_Menu_Item_Type, and Fl_Submenu_Type.
Definition at line 103 of file Fl_Widget_Type.cxx.
References Fl_Type::current, Fl_Type::factory, fl_message(), force_parent, gridx, gridy, H, Fl_Widget::h(), Fl_Type::is_group(), Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::is_window(), Fl_Type::label(), Fl_Widget::label(), o, Fl_Type::parent, reading_file, Fl_Widget::user_data(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
void Fl_Widget_Type::open () [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Window_Type.
Definition at line 1876 of file Fl_Widget_Type.cxx.
References make_widget_panel(), and Fl_Window::show().
int Fl_Widget_Type::read_fdesign (const char * propname, const char * value) [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Window_Type.
Definition at line 2676 of file Fl_Widget_Type.cxx.
References Fl_Widget::align(), Fl_Widget::box(), boxnumber(), buf, Fl_Type::callback(), Fl_Widget::color(), extra_code(), Fl_Type::factory, FL_ALIGN_BOTTOM, FL_ALIGN_CENTER, FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_ALIGN_TOP, FL_WHEN_RELEASE, Fl_Widget::h(), h, Fl_Type::is_widget(), Fl_Type::is_window(), item_number(), Fl_Type::label(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), lookup_symbol(), Fl_Type::name(), Fl_Type::parent, pasteoffset, resizable(), Fl_Widget::resize(), Fl_Widget::type(), Fl_Type::user_data(), Fl_Type::user_data_type(), w, Fl_Widget::when(), x, y, and ZERO_ENTRY.
Referenced by read_fdesign().
void Fl_Widget_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Window_Type, and Fl_Widget_Class_Type.
Definition at line 2509 of file Fl_Widget_Type.cxx.
References Fl_Widget::align(), Fl_Widget::box(), boxnumber(), Fl_Widget::color(), Fl_Widget::deactivate(), extra_code(), f, Fluid_Image::find(), h, Fl_Widget::hide(), hotspot(), image_name(), inactive_name(), Fl_Type::is_button(), Fl_Type::is_input(), Fl_Type::is_menu_button(), Fl_Type::is_spinner(), Fl_Type::is_text_display(), Fl_Type::is_valuator(), Fl_Type::is_value_input(), item_number(), Fl_Type::label(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), NUM_EXTRA_CODE, Fl_Widget::parent(), pasteoffset, public_, read_error(), read_word(), resizable(), Fl_Widget::resize(), Fl_Widget::selection_color(), setimage(), subclass(), subtypes(), textstuff(), tooltip(), Fl_Widget::type(), Fl_Type::type_name(), value, w, Fl_Widget::when(), Fl_Widget::window(), Fl_Widget::x(), x, Fl_Widget::y(), y, and ZERO_ENTRY.
void Fl_Widget_Type::redraw ()
Definition at line 259 of file Fl_Widget_Type.cxx.
References Fl_Type::add_child(), Fl_Type::is_menu_item(), Fl_Type::is_widget(), o, Fl_Type::parent, and Fl_Widget::redraw().
Referenced by active_cb(), align_cb(), align_position_cb(), align_text_image_cb(), box_cb(), down_box_cb(), hotspot_cb(), labelcolor_cb(), labelfont_cb(), labelsize_cb(), labeltype_cb(), setimage(), setinactive(), subtype_cb(), value_cb(), visible_cb(), and xclass_cb().
uchar Fl_Widget_Type::resizable () const
Definition at line 854 of file Fl_Widget_Type.cxx.
References Fl_Type::is_window(), o, Fl_Widget::parent(), and Fl_Group::resizable().
Referenced by copy_properties(), read_fdesign(), read_property(), resizable(), resizable_cb(), Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), Fl_Group_Type::write_code2(), write_properties(), and write_widget_code().
void Fl_Widget_Type::resizable (uchar v)
Definition at line 861 of file Fl_Widget_Type.cxx.
References Fl_Type::is_window(), o, Fl_Widget::parent(), Fl_Group::resizable(), and resizable().
void Fl_Widget_Type::setimage (Fluid_Image * i)
Definition at line 180 of file Fl_Widget_Type.cxx.
References Fluid_Image::decrement(), i, Fl_Widget::image(), Fluid_Image::image(), image, Fluid_Image::increment(), Fl_Type::is_window(), o, and redraw().
Referenced by image_name(), and read_property().
void Fl_Widget_Type::setinactive (Fluid_Image * i)
Definition at line 190 of file Fl_Widget_Type.cxx.
References Fluid_Image::decrement(), Fl_Widget::deimage(), Fluid_Image::deimage(), i, inactive, Fluid_Image::increment(), Fl_Type::is_window(), o, and redraw().
Referenced by inactive_name().
void Fl_Widget_Type::subclass (const char * n)
Definition at line 239 of file Fl_Widget_Type.cxx.
References redraw_browser(), storestring(), and Fl_Type::visible.
const char* Fl_Widget_Type::subclass () const [inline]
Definition at line 374 of file Fl_Type.h.
Referenced by read_property(), subclass_cb(), subclassname(), Fl_Widget_Class_Type::write_code1(), write_properties(), write_static(), and write_widget_code().
Fl_Menu_Item * Fl_Widget_Type::subtypes () [virtual]
Reimplemented in Fl_Window_Type, Fl_Menu_Item_Type, and Fl_Submenu_Type.
Definition at line 1701 of file Fl_Widget_Type.cxx.
Referenced by read_property(), subtype_cb(), and write_properties().
int Fl_Widget_Type::textstuff (int what, Fl_Font & , int & , Fl_Color &) [virtual]
Reimplemented in Fl_Value_Input_Type, and Fl_Value_Output_Type.
Definition at line 1361 of file Fl_Widget_Type.cxx.
Referenced by read_property(), textcolor_cb(), textfont_cb(), textsize_cb(), write_properties(), and write_widget_code().
void Fl_Widget_Type::tooltip (const char * n)
Definition at line 244 of file Fl_Widget_Type.cxx.
References o, storestring(), and Fl_Widget::tooltip().
const char* Fl_Widget_Type::tooltip () const [inline]
Definition at line 376 of file Fl_Type.h.
Referenced by copy_properties(), read_property(), write_properties(), write_strings(), and write_widget_code().
void Fl_Widget_Type::write_block_close () [protected]
Definition at line 2375 of file Fl_Widget_Type.cxx.
References indent(), indentation, Fl_Type::name(), subclassname(), and write_c().
Referenced by Fl_Window_Type::write_code2(), write_code2(), and Fl_Group_Type::write_code2().
void Fl_Widget_Type::write_code1 () [protected, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Group_Type, Fl_Window_Type, Fl_Widget_Class_Type, and Fl_Menu_Item_Type.
Definition at line 2072 of file Fl_Widget_Type.cxx.
References array_name(), Fl_Type::callback(), Fl_Type::callback_name(), Fl_Type::class_name(), extra_code(), Fl_Widget::h(), i18n_file, i18n_function, i18n_set, i18n_type, indent(), indentation, is_name(), Fl_Type::is_parent(), Fl_Type::is_window(), isdeclare(), Fl_Type::label(), Fl_Type::msgnum(), Fl_Type::name(), NUM_EXTRA_CODE, ptr, public_, subclassname(), Fl_Type::user_data_type(), Fl_Widget::w(), write_c(), write_cstring(), write_h(), write_public(), write_widget_code(), Fl_Widget::x(), and Fl_Widget::y().
void Fl_Widget_Type::write_code2 () [protected, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Group_Type, Fl_Window_Type, Fl_Widget_Class_Type, Fl_Menu_Item_Type, and Fl_Menu_Type.
Definition at line 2381 of file Fl_Widget_Type.cxx.
References write_block_close(), and write_extra_code().
void Fl_Widget_Type::write_color (const char * field, Fl_Color color) [protected]
Definition at line 2171 of file Fl_Widget_Type.cxx.
References FL_BACKGROUND2_COLOR, FL_BACKGROUND_COLOR, FL_BLACK, FL_BLUE, FL_CYAN, FL_DARK1, FL_DARK2, FL_DARK3, FL_DARK_BLUE, FL_DARK_CYAN, FL_DARK_GREEN, FL_DARK_MAGENTA, FL_DARK_RED, FL_DARK_YELLOW, FL_FOREGROUND_COLOR, FL_GRAY0, FL_GREEN, FL_INACTIVE_COLOR, FL_LIGHT1, FL_LIGHT2, FL_LIGHT3, FL_MAGENTA, FL_RED, FL_SELECTION_COLOR, FL_WHITE, FL_YELLOW, indent(), Fl_Type::is_class(), Fl_Type::name(), and write_c().
Referenced by write_widget_code().
void Fl_Widget_Type::write_extra_code () [protected]
Definition at line 2369 of file Fl_Widget_Type.cxx.
References extra_code(), indent(), isdeclare(), NUM_EXTRA_CODE, and write_c().
Referenced by Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), write_code2(), and Fl_Group_Type::write_code2().
void Fl_Widget_Type::write_properties () [virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Window_Type, and Fl_Widget_Class_Type.
Definition at line 2388 of file Fl_Widget_Type.cxx.
References Fl_Widget::active(), Fl_Widget::align(), b, Fl_Widget::box(), boxname(), Fl_Widget::color(), Fl_Menu_::down_box(), Fl_Input_Choice::down_box(), Fl_Button::down_box(), extra_code(), f, Fl_Type::factory, Fl_Widget::h(), hotspot(), image_name(), inactive_name(), Fl_Type::is_button(), Fl_Type::is_input(), Fl_Type::is_menu_button(), Fl_Type::is_menu_item(), Fl_Type::is_spinner(), Fl_Type::is_text_display(), Fl_Type::is_valuator(), Fl_Type::is_value_input(), Fl_Type::is_window(), item_name(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), Fl_Type::level, Fl_Spinner::maximum(), Fl_Valuator::maximum(), Fl_Spinner::minimum(), Fl_Valuator::minimum(), NUM_EXTRA_CODE, public_, resizable(), Fl_Widget::selection_color(), Fl_Button::shortcut(), Fl_Text_Display::shortcut(), Fl_Value_Input::shortcut(), Fl_Input_::shortcut(), Fl_Spinner::step(), Fl_Valuator::step(), subclass(), subtypes(), textstuff(), tooltip(), Fl_Widget::type(), type, Fl_Type::type_name(), Fl_Spinner::value(), Fl_Valuator::value(), Fl_Button::value(), Fl_Widget::visible(), Fl_Widget::w(), Fl_Widget::when(), write_indent(), write_string(), write_word(), x, Fl_Widget::x(), y, and Fl_Widget::y().
void Fl_Widget_Type::write_static () [protected, virtual]
Reimplemented from Fl_Type.
Reimplemented in Fl_Menu_Item_Type.
Definition at line 1976 of file Fl_Widget_Type.cxx.
References array_name(), buf, Fl_Type::callback(), Fl_Type::callback_name(), Fl_Type::class_name(), extra_code(), Fl_Class_Type::has_function(), has_toplevel_function(), image, inactive, Fl_Type::is_class(), is_id(), Fl_Type::is_in_class(), is_name(), Fl_Type::is_widget(), isdeclare(), NULL, NUM_EXTRA_CODE, Fl_Type::parent, public_, snprintf, subclass(), subclassname(), Fl_Type::type_name(), Fl_Type::user_data_type(), write_c(), write_declare(), write_h(), write_number, Fluid_Image::write_static(), and Fluid_Image::written.
void Fl_Widget_Type::write_widget_code () [protected]
Definition at line 2210 of file Fl_Widget_Type.cxx.
References Fl_Widget::active(), Fl_Widget::align(), b, Fl_Widget::box(), boxname(), Fl_Type::callback(), Fl_Type::callback_name(), Fl_Type::class_name(), Fl_Widget::color(), Fl_Menu_::down_box(), Fl_Input_Choice::down_box(), Fl_Button::down_box(), f, Fl_Type::factory, FL_ALIGN_INSIDE, FL_CTRL, FL_META, FL_WHEN_NEVER, FL_WHEN_NOT_CHANGED, hotspot(), i18n_file, i18n_function, i18n_set, i18n_type, image, inactive, indent(), Fl_Type::is_button(), Fl_Type::is_class(), Fl_Type::is_group(), Fl_Type::is_input(), Fl_Type::is_menu_button(), Fl_Type::is_spinner(), Fl_Type::is_text_display(), Fl_Type::is_valuator(), Fl_Type::is_value_input(), Fl_Type::is_widget(), Fl_Type::is_window(), item_name(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), Fl_Spinner::maximum(), Fl_Valuator::maximum(), Fl_Spinner::minimum(), Fl_Valuator::minimum(), Fl_Type::msgnum(), Fl_Type::name(), o, Fl_Widget::parent(), Fl_Type::parent, resizable(), Fl_Widget::selection_color(), Fl_Spinner::step(), Fl_Valuator::step(), subclass(), textstuff(), tooltip(), Fl_Spinner::type(), type, Fl_Type::type_name(), use_FL_COMMAND, Fl_Type::user_data(), Fl_Spinner::value(), Fl_Valuator::value(), Fl_Button::value(), Fl_Widget::visible(), Fl_Widget::when(), write_c(), Fluid_Image::write_code(), write_color(), write_cstring(), x, and y.
Referenced by Fl_Widget_Class_Type::write_code1(), and write_code1().
Member Data Documentation
int Fl_Widget_Type::default_size = FL_NORMAL_SIZE [static]
Definition at line 357 of file Fl_Type.h.
Referenced by default_widget_size_cb(), labelsize_cb(), Fl_Menu_Item_Type::make(), make_main_window(), show_grid_cb(), and textsize_cb().
Fluid_Image* Fl_Widget_Type::image
Definition at line 363 of file Fl_Type.h.
Referenced by Fl_Widget_Type(), setimage(), Fl_Menu_Item_Type::write_code1(), Fl_Menu_Item_Type::write_item(), write_static(), Fl_Menu_Item_Type::write_static(), and write_widget_code().
Fluid_Image* Fl_Widget_Type::inactive
Definition at line 365 of file Fl_Type.h.
Referenced by Fl_Widget_Type(), setinactive(), write_static(), and write_widget_code().
Fl_Widget* Fl_Widget_Type::live_widget [protected]
Definition at line 354 of file Fl_Type.h.
Referenced by Fl_Pack_Type::copy_properties(), copy_properties(), Fl_Input_Choice_Type::copy_properties(), Fl_Menu_Type::copy_properties(), Fl_Scroll_Type::copy_properties(), Fl_Input_Type::copy_properties(), Fl_Window_Type::enter_live_mode(), enter_live_mode(), Fl_Scroll_Type::enter_live_mode(), Fl_Table_Type::enter_live_mode(), Fl_Tabs_Type::enter_live_mode(), and Fl_Group_Type::enter_live_mode().
Fl_Widget* Fl_Widget_Type::o
Definition at line 360 of file Fl_Type.h.
Referenced by active_cb(), Fl_Window_Type::add_child(), Fl_Table_Type::add_child(), Fl_Group_Type::add_child(), align_cb(), align_position_cb(), align_text_image_cb(), border_cb(), box_cb(), Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), check_redraw_corresponding_parent(), Fl_Input_Choice_Type::click_test(), Fl_Menu_Type::click_test(), Fl_Tabs_Type::click_test(), color2_cb(), color_cb(), Fl_Pack_Type::copy_properties(), copy_properties(), Fl_Input_Choice_Type::copy_properties(), Fl_Menu_Type::copy_properties(), Fl_Scroll_Type::copy_properties(), Fl_Input_Type::copy_properties(), down_box_cb(), Fl_Window_Type::draw_overlay(), Fl_Window_Type::enter_live_mode(), Fl_Scroll_Type::enter_live_mode(), Fl_Table_Type::enter_live_mode(), Fl_Tabs_Type::enter_live_mode(), Fl_Group_Type::enter_live_mode(), fix_group_size(), Fl_Window_Type::fix_overlay(), Fl_Widget_Type(), Fl_Menu_Item_Type::flags(), grid_cb(), group_cb(), guides_cb(), Fl_Window_Type::handle(), ideal_size(), Fl_Menu_Bar_Type::ideal_size(), Fl_Input_Choice_Type::ideal_size(), Fl_Choice_Type::ideal_size(), Fl_Menu_Button_Type::ideal_size(), Fl_Value_Output_Type::ideal_size(), Fl_Value_Input_Type::ideal_size(), Fl_Output_Type::ideal_size(), Fl_Help_View_Type::ideal_size(), Fl_Text_Editor_Type::ideal_size(), Fl_Text_Display_Type::ideal_size(), Fl_File_Input_Type::ideal_size(), Fl_Input_Type::ideal_size(), Fl_Spinner_Type::ideal_size(), Fl_File_Browser_Type::ideal_size(), Fl_Check_Browser_Type::ideal_size(), Fl_Browser_Type::ideal_size(), Fl_Return_Button_Type::ideal_size(), Fl_Button_Type::ideal_size(), ideal_spacing(), Fl_Tabs_Type::ideal_spacing(), labelcolor_cb(), labelfont_cb(), labelsize_cb(), labeltype_cb(), Fl_Widget_Class_Type::make(), Fl_Window_Type::make(), make(), Fl_Menu_Item_Type::make(), max_cb(), min_cb(), Fl_Window_Type::move_child(), Fl_Table_Type::move_child(), Fl_Group_Type::move_child(), Fl_Window_Type::moveallchildren(), Fl_Window_Type::newdx(), Fl_Window_Type::newposition(), Fl_Window_Type::open(), Fl_Window_Type::read_fdesign(), read_fdesign(), Fl_Window_Type::read_image(), Fl_Window_Type::read_property(), redraw(), Fl_Window_Type::remove_child(), Fl_Table_Type::remove_child(), Fl_Tabs_Type::remove_child(), Fl_Group_Type::remove_child(), resizable(), set_max_size_cb(), set_min_size_cb(), setimage(), setinactive(), Fl_Window_Type::setlabel(), shortcut_in_cb(), slider_size_cb(), step_cb(), subclassname(), subtype_cb(), textcolor_cb(), textfont_cb(), textsize_cb(), Fl_Value_Output_Type::textstuff(), Fl_Value_Input_Type::textstuff(), toggle_overlays(), tooltip(), value_cb(), visible_cb(), when_button_cb(), when_cb(), Fl_Widget_Class_Type::write_code1(), Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), Fl_Menu_Item_Type::write_item(), Fl_Window_Type::write_properties(), write_widget_code(), xclass_cb(), Fl_Menu_Type::~Fl_Menu_Type(), and ~Fl_Widget_Type().
int Fl_Widget_Type::public_
Definition at line 361 of file Fl_Type.h.
Referenced by Fl_Widget_Type(), is_public(), name_public_cb(), name_public_member_cb(), read_property(), write_code1(), Fl_Menu_Item_Type::write_code1(), write_properties(), and write_static().
const char* Fl_Widget_Type::xclass
Definition at line 359 of file Fl_Type.h.
Referenced by Fl_Widget_Type(), Fl_Window_Type::read_property(), Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), Fl_Window_Type::write_properties(), and xclass_cb().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Widget_Type.cxx