SfR Fresh Dox - fltk: Fl_Glut_Window Class Reference
Fl_Glut_Window Class Reference
#include <glut.H>
Public Member Functions
void make_current ()
Fl_Glut_Window (int w, int h, const char *)
Fl_Glut_Window (int x, int y, int w, int h, const char *)
~Fl_Glut_Window ()
Public Attributes
int number
int menu [3]
void(* display)()
void(* overlaydisplay)()
void(* reshape)(int w, int h)
void(* keyboard)(uchar, int x, int y)
void(* mouse)(int b, int state, int x, int y)
void(* motion)(int x, int y)
void(* passivemotion)(int x, int y)
void(* entry)(int)
void(* visibility)(int)
void(* special)(int, int x, int y)
Protected Member Functions
void draw ()
void draw_overlay ()
int handle (int)
Detailed Description
GLUT is emulated using this window class and these static variables (plus several more static variables hidden in glut_compatability.cxx):
Definition at line 53 of file glut.H.
Constructor & Destructor Documentation
Fl_Glut_Window::Fl_Glut_Window (int w, int h, const char *)
Fl_Glut_Window::Fl_Glut_Window (int x, int y, int w, int h, const char *)
Fl_Glut_Window::~Fl_Glut_Window ()
Member Function Documentation
void Fl_Glut_Window::draw (void) [protected, virtual]
Draws the Fl_Gl_Window.
You must override the draw() method.
You must subclass Fl_Gl_Window and provide an implementation for draw(). You may also provide an implementation of draw_overlay() if you want to draw into the overlay planes. You can avoid reinitializing the viewport and lights and other things by checking valid() at the start of draw() and only doing the initialization if it is false.
The draw() method can only use OpenGL calls. Do not attempt to call X, any of the functions in <FL/fl_draw.H>, or glX directly. Do not call gl_start() or gl_finish().
If double-buffering is enabled in the window, the back and front buffers are swapped after this function is completed.
Reimplemented from Fl_Gl_Window.
void Fl_Glut_Window::draw_overlay () [protected, virtual]
Reimplemented from Fl_Gl_Window.
int Fl_Glut_Window::handle (int event) [protected, virtual]
Handle some FLTK events as needed.
Reimplemented from Fl_Gl_Window.
void Fl_Glut_Window::make_current ()
Sets things up so that the drawing functions in <FL/fl_draw.H> will go into this window. This is useful for incremental update of windows, such as in an idle callback, which will make your program behave much better if it draws a slow graphic. Danger: incremental update is very hard to debug and maintain!
This method only works for the Fl_Window and Fl_Gl_Window derived classes.
make all drawing go into this window (called by subclass flush() impl.)
Reimplemented from Fl_Gl_Window.
Referenced by glutUseLayer().
Member Data Documentation
void(* Fl_Glut_Window::display)()
Definition at line 65 of file glut.H.
Referenced by glutDisplayFunc().
void(* Fl_Glut_Window::entry)(int)
Definition at line 72 of file glut.H.
Referenced by glutEntryFunc().
void(* Fl_Glut_Window::keyboard)(uchar, int x, int y)
Definition at line 68 of file glut.H.
Referenced by glutKeyboardFunc().
int Fl_Glut_Window::menu[3]
Definition at line 63 of file glut.H.
Referenced by glutAttachMenu(), and glutDetachMenu().
void(* Fl_Glut_Window::motion)(int x, int y)
Definition at line 70 of file glut.H.
Referenced by glutMotionFunc().
void(* Fl_Glut_Window::mouse)(int b, int state, int x, int y)
Definition at line 69 of file glut.H.
Referenced by glutMouseFunc().
int Fl_Glut_Window::number
Definition at line 62 of file glut.H.
Referenced by glutGetWindow().
void(* Fl_Glut_Window::overlaydisplay)()
Definition at line 66 of file glut.H.
Referenced by glutOverlayDisplayFunc().
void(* Fl_Glut_Window::passivemotion)(int x, int y)
Definition at line 71 of file glut.H.
Referenced by glutPassiveMotionFunc().
void(* Fl_Glut_Window::reshape)(int w, int h)
Definition at line 67 of file glut.H.
Referenced by glutReshapeFunc().
void(* Fl_Glut_Window::special)(int, int x, int y)
Definition at line 74 of file glut.H.
Referenced by glutSpecialFunc().
void(* Fl_Glut_Window::visibility)(int)
Definition at line 73 of file glut.H.
Referenced by glutVisibilityFunc().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/FL/glut.H