SfR Fresh Dox - fltk: CodeEditor Class Reference
CodeEditor Class Reference
#include <CodeEditor.h>
Public Member Functions
CodeEditor (int X, int Y, int W, int H, const char *L=0)
~CodeEditor ()
int top_line ()
Detailed Description
Definition at line 44 of file CodeEditor.h.
Constructor & Destructor Documentation
CodeEditor::CodeEditor (int X, int Y, int W, int H, const char * L = 0)
Definition at line 372 of file CodeEditor.cxx.
References Fl_Text_Editor::add_key_binding(), Fl_Text_Buffer::add_modify_callback(), Fl_Text_Display::buffer(), FL_Enter, FL_TEXT_EDITOR_ANY_STATE, Fl_Text_Display::highlight_data(), Fl_Text_Buffer::length(), Fl_Text_Display::mBuffer, Fl_Text_Display::mStyleBuffer, and Fl_Text_Buffer::text().
CodeEditor::~CodeEditor ()
Definition at line 398 of file CodeEditor.cxx.
References buf, Fl_Text_Display::buffer(), Fl_Text_Display::mBuffer, and Fl_Text_Display::mStyleBuffer.
Member Function Documentation
int CodeEditor::top_line () [inline]
Definition at line 70 of file CodeEditor.h.
References Fl_Text_Display::get_absolute_top_line_number().
Referenced by update_sourceview_cb().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/CodeEditor.h
fltk-1.3.0rc3/fluid/CodeEditor.cxx