SfR Fresh Dox - fltk: Fl_Data_Type Class Reference
Fl_Data_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Data_Type ()
~Fl_Data_Type ()
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void open ()
virtual const char * type_name ()
void write_properties ()
void read_property (const char *)
int pixmapID ()
Detailed Description
Definition at line 242 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_Data_Type::Fl_Data_Type () [inline]
Definition at line 245 of file Fl_Type.h.
Fl_Data_Type::~Fl_Data_Type () [inline]
Definition at line 246 of file Fl_Type.h.
Member Function Documentation
Fl_Type * Fl_Data_Type::make () [virtual]
Reimplemented from Fl_Decl_Type.
Definition at line 742 of file Fl_Function_Type.cxx.
References Fl_Type::current, Fl_Type::is_decl_block(), Fl_Type::parent, and Fl_Decl_Type::public_.
void Fl_Data_Type::open () [virtual]
Reimplemented from Fl_Decl_Type.
Definition at line 771 of file Fl_Function_Type.cxx.
References Fl_Text_Display::buffer(), Fl_Type::comment(), data_choice, data_class_choice, data_comment_input, data_filebrowser, data_filename, data_input, data_panel, data_panel_cancel, data_panel_ok, fl_alert(), fl_file_chooser(), goto_source_dir(), Fl_Double_Window::hide(), Fl_Widget::hide(), Fl_Type::is_in_class(), leave_source_dir(), make_data_panel(), Fl_Type::name(), Fl_Decl_Type::public_, Fl::readqueue(), redraw_browser(), set_modflag(), Fl_Double_Window::show(), Fl_Widget::show(), Fl_Decl_Type::static_, Fl_Input_::static_value(), Fl_Input_::value(), Fl_Choice::value(), w, and Fl::wait().
int Fl_Data_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Decl_Type.
Definition at line 256 of file Fl_Type.h.
void Fl_Data_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Decl_Type.
Definition at line 763 of file Fl_Function_Type.cxx.
References read_word(), and storestring().
virtual const char* Fl_Data_Type::type_name () [inline, virtual]
Reimplemented from Fl_Decl_Type.
Definition at line 253 of file Fl_Type.h.
void Fl_Data_Type::write_code1 () [virtual]
Reimplemented from Fl_Decl_Type.
Definition at line 873 of file Fl_Function_Type.cxx.
References Fl_Type::class_name(), compile_only, data, f, fl_alert(), fl_fopen(), Fl_Type::is_in_class(), Fl_Type::name(), Fl_Decl_Type::public_, SEEK_END, SEEK_SET, Fl_Decl_Type::static_, write_c(), write_cdata(), Fl_Type::write_comment_c(), Fl_Type::write_comment_h(), write_h(), write_public(), and write_sourceview.
void Fl_Data_Type::write_code2 () [virtual]
Reimplemented from Fl_Decl_Type.
Definition at line 942 of file Fl_Function_Type.cxx.
void Fl_Data_Type::write_properties () [virtual]
Reimplemented from Fl_Decl_Type.
Definition at line 755 of file Fl_Function_Type.cxx.
References write_string(), and write_word().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx