SfR Fresh Dox - fltk: Fl_Comment_Type Class Reference
Fl_Comment_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void open ()
virtual const char * type_name ()
virtual const char * title ()
void write_properties ()
void read_property (const char *)
virtual int is_public () const
virtual int is_comment () const
int pixmapID ()
Detailed Description
Definition at line 280 of file Fl_Type.h.
Member Function Documentation
virtual int Fl_Comment_Type::is_comment () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 293 of file Fl_Type.h.
virtual int Fl_Comment_Type::is_public () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 292 of file Fl_Type.h.
Fl_Type * Fl_Comment_Type::make () [virtual]
Implements Fl_Type.
Definition at line 1036 of file Fl_Function_Type.cxx.
References Fl_Type::current, Fl_Type::is_code_block(), and Fl_Type::parent.
void Fl_Comment_Type::open () [virtual]
Reimplemented from Fl_Type.
Definition at line 1086 of file Fl_Function_Type.cxx.
References Fl_Menu_::add(), Fl_Text_Display::buffer(), Fl_Menu_::clear(), comment_in_header, comment_in_source, comment_input, comment_load, comment_panel, comment_panel_cancel, comment_panel_ok, comment_predefined, Fl_Preferences::deleteEntry(), fl_alert(), fl_choice(), fl_file_chooser(), fl_file_chooser_ok_label(), fl_input(), fl_message(), FL_PATH_MAX, Fl_Preferences::get(), Fl_Double_Window::hide(), i, Fl_Menu_::item_pathname(), make_comment_panel(), Fl_Menu_::menu(), Fl_Type::name(), NULL, Fl::readqueue(), Fl_Menu_::remove(), Fl_Preferences::set(), set_modflag(), Fl_Double_Window::show(), Fl_Menu_::size(), Fl_Preferences::USER, Fl_Menu_::value(), Fl_Button::value(), w, and Fl::wait().
int Fl_Comment_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 294 of file Fl_Type.h.
void Fl_Comment_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Type.
Definition at line 1056 of file Fl_Function_Type.cxx.
const char * Fl_Comment_Type::title () [virtual]
Reimplemented from Fl_Type.
Definition at line 1205 of file Fl_Function_Type.cxx.
References Fl_Type::name(), and type_name().
virtual const char* Fl_Comment_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 288 of file Fl_Type.h.
Referenced by title().
void Fl_Comment_Type::write_code1 () [virtual]
Reimplemented from Fl_Type.
Definition at line 1228 of file Fl_Function_Type.cxx.
References b, Fl_Type::name(), write_c(), and write_h().
void Fl_Comment_Type::write_code2 () [virtual]
Reimplemented from Fl_Type.
Definition at line 1267 of file Fl_Function_Type.cxx.
void Fl_Comment_Type::write_properties () [virtual]
Reimplemented from Fl_Type.
Definition at line 1050 of file Fl_Function_Type.cxx.
References write_string().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx