SfR Fresh Dox - fltk: Fl_CodeBlock_Type Class Reference
Fl_CodeBlock_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
Fl_CodeBlock_Type ()
~Fl_CodeBlock_Type ()
Fl_Type * make ()
void write_code1 ()
void write_code2 ()
void open ()
virtual const char * type_name ()
int is_code_block () const
int is_parent () const
virtual int is_public () const
int pixmapID ()
void write_properties ()
void read_property (const char *)
Detailed Description
Definition at line 206 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_CodeBlock_Type::Fl_CodeBlock_Type () [inline]
Definition at line 209 of file Fl_Type.h.
Referenced by make().
Fl_CodeBlock_Type::~Fl_CodeBlock_Type () [inline]
Definition at line 210 of file Fl_Type.h.
Member Function Documentation
int Fl_CodeBlock_Type::is_code_block () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 218 of file Fl_Type.h.
int Fl_CodeBlock_Type::is_parent () const [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 219 of file Fl_Type.h.
int Fl_CodeBlock_Type::is_public () const [virtual]
Reimplemented from Fl_Type.
Definition at line 692 of file Fl_Type.cxx.
Fl_Type * Fl_CodeBlock_Type::make () [virtual]
Implements Fl_Type.
Definition at line 489 of file Fl_Function_Type.cxx.
References Fl_Type::add(), Fl_Type::current, Fl_Type::factory, Fl_CodeBlock_Type(), fl_message(), Fl_Type::is_code_block(), Fl_Type::name(), and Fl_Type::parent.
void Fl_CodeBlock_Type::open () [virtual]
Reimplemented from Fl_Type.
Definition at line 520 of file Fl_Function_Type.cxx.
References c_check(), code_after_input, code_before_input, codeblock_panel, codeblock_panel_cancel, codeblock_panel_ok, fl_alert(), Fl_Double_Window::hide(), make_codeblock_panel(), Fl_Type::name(), Fl::readqueue(), Fl_Double_Window::show(), Fl_Input_::static_value(), storestring(), Fl_Input_::value(), w, and Fl::wait().
int Fl_CodeBlock_Type::pixmapID () [inline, virtual]
Reimplemented from Fl_Type.
Definition at line 221 of file Fl_Type.h.
void Fl_CodeBlock_Type::read_property (const char * c) [virtual]
Reimplemented from Fl_Type.
Definition at line 512 of file Fl_Function_Type.cxx.
References read_word(), and storestring().
virtual const char* Fl_CodeBlock_Type::type_name () [inline, virtual]
Implements Fl_Type.
Definition at line 217 of file Fl_Type.h.
void Fl_CodeBlock_Type::write_code1 () [virtual]
Reimplemented from Fl_Type.
Definition at line 548 of file Fl_Function_Type.cxx.
References indent(), indentation, Fl_Type::name(), and write_c().
void Fl_CodeBlock_Type::write_code2 () [virtual]
Reimplemented from Fl_Type.
Definition at line 554 of file Fl_Function_Type.cxx.
References indent(), indentation, and write_c().
void Fl_CodeBlock_Type::write_properties () [virtual]
Reimplemented from Fl_Type.
Definition at line 504 of file Fl_Function_Type.cxx.
References write_string(), and write_word().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx
fltk-1.3.0rc3/fluid/Fl_Type.cxx