SfR Fresh Dox - fltk: Fl_FormsPixmap Class Reference
Fl_FormsPixmap Class Reference
Forms pixmap drawing routines.
#include <Fl_FormsPixmap.H>
Public Member Functions
Fl_FormsPixmap (Fl_Boxtype t, int X, int Y, int W, int H, const char *L=0)
void set (char *const *bits)
void Pixmap (Fl_Pixmap *B)
Fl_Pixmap * Pixmap () const
Protected Member Functions
void draw ()
Detailed Description
Forms pixmap drawing routines.
Definition at line 40 of file Fl_FormsPixmap.H.
Constructor & Destructor Documentation
Fl_FormsPixmap::Fl_FormsPixmap (Fl_Boxtype t, int X, int Y, int W, int H, const char * L = 0)
Creates a new Fl_FormsPixmap widget using the given box type, position, size and label string.
Parameters:
[in] t box type
[in] X,Y,W,H position and size
[in] L widget label, default is no label
Definition at line 37 of file forms_pixmap.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::color(), FL_ALIGN_BOTTOM, and FL_BLACK.
Member Function Documentation
void Fl_FormsPixmap::draw () [protected, virtual]
Draws the widget. Never call this function directly. FLTK will schedule redrawing whenever needed. If your widget must be redrawn as soon as possible, call redraw() instead.
Override this function to draw your own widgets.
If you ever need to call another widget's draw method from within your own draw() method, e.g. for an embedded scrollbar, you can do it (because draw() is virtual) like this:
        Fl_Widget *s = &scroll;         // scroll is an embedded Fl_Scrollbar
        s->draw();                      // calls Fl_Scrollbar::draw()
Implements Fl_Widget.
Definition at line 55 of file forms_pixmap.cxx.
References Fl_Widget::box(), Fl_Widget::color(), Fl_Pixmap::draw(), Fl_Widget::draw_box(), Fl_Widget::draw_label(), fl_color(), Fl_Widget::h(), Fl_Widget::selection_color(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
Fl_Pixmap* Fl_FormsPixmap::Pixmap () const [inline]
Get the internal pixmap pointer.
Definition at line 56 of file Fl_FormsPixmap.H.
References b.
void Fl_FormsPixmap::Pixmap (Fl_Pixmap * B) [inline]
Set the internal pixmap pointer to an existing pixmap.
Parameters:
[in] B existing pixmap
Definition at line 53 of file Fl_FormsPixmap.H.
References b.
void Fl_FormsPixmap::set (char *const * bits)
Set/create the internal pixmap using raw data.
Parameters:
[in] bits raw data
Definition at line 50 of file forms_pixmap.cxx.
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_FormsPixmap.H
fltk-1.3.0rc3/src/forms_pixmap.cxx