SfR Fresh Dox - fltk: menutitle Class Reference
menutitle Class Reference
Public Member Functions
menutitle (int X, int Y, int W, int H, const Fl_Menu_Item *)
Public Attributes
const Fl_Menu_Item * menu
Detailed Description
Definition at line 85 of file Fl_Menu.cxx.
Constructor & Destructor Documentation
menutitle::menutitle (int X, int Y, int W, int H, const Fl_Menu_Item * L)
Definition at line 263 of file Fl_Menu.cxx.
References Fl_Window::clear_border(), Fl_Menu_Window::clear_overlay(), Fl_Group::end(), FL_NO_LABEL, Fl_Menu_Item::labelcolor_, Fl_Menu_Item::labeltype_, menu, Fl::scheme(), Fl_Window::set_menu_window(), and Fl_Window::set_modal().
Member Data Documentation
const Fl_Menu_Item* menutitle::menu
Definition at line 88 of file Fl_Menu.cxx.
Referenced by menutitle().
The documentation for this class was generated from the following file:
fltk-1.3.0rc3/src/Fl_Menu.cxx