SfR Fresh Dox - fltk: Fl_Type Class Reference
Fl_Type Class Reference
#include <Fl_Type.h>
Public Member Functions
const char * callback_name ()
virtual ~Fl_Type ()
virtual Fl_Type * make ()=0
void add (Fl_Type *parent)
void insert (Fl_Type *n)
Fl_Type * remove ()
void move_before (Fl_Type *)
virtual const char * title ()
virtual const char * type_name ()=0
virtual const char * alt_type_name ()
const char * name () const
void name (const char *)
const char * label () const
void label (const char *)
const char * callback () const
void callback (const char *)
const char * user_data () const
void user_data (const char *)
const char * user_data_type () const
void user_data_type (const char *)
const char * comment ()
void comment (const char *)
virtual Fl_Type * click_test (int, int)
virtual void add_child (Fl_Type *, Fl_Type *beforethis)
virtual void move_child (Fl_Type *, Fl_Type *beforethis)
virtual void remove_child (Fl_Type *)
virtual void open ()
void write ()
virtual void write_properties ()
virtual void read_property (const char *)
virtual int read_fdesign (const char *, const char *)
virtual void write_static ()
virtual void write_code1 ()
virtual void write_code2 ()
void write_comment_h (const char *ind="")
void write_comment_c (const char *ind="")
virtual Fl_Widget * enter_live_mode (int top=0)
virtual void leave_live_mode ()
virtual void copy_properties ()
int msgnum ()
virtual int is_parent () const
virtual int is_widget () const
virtual int is_button () const
virtual int is_input () const
virtual int is_value_input () const
virtual int is_text_display () const
virtual int is_valuator () const
virtual int is_spinner () const
virtual int is_menu_item () const
virtual int is_menu_button () const
virtual int is_group () const
virtual int is_window () const
virtual int is_code_block () const
virtual int is_decl_block () const
virtual int is_comment () const
virtual int is_class () const
virtual int is_public () const
virtual int pixmapID ()
const char * class_name (const int need_nest) const
class Fl_Class_Type * is_in_class () const
Public Attributes
Fl_Type * parent
char new_selected
char selected
char open_
char visible
char rtti
int level
static Fl_Type * last
Fl_Type * next
Fl_Type * prev
Fl_Type * factory
int code_position
int header_position
int code_position_end
int header_position_end
Static Public Attributes
static Fl_Type * first
static Fl_Type * current
Protected Member Functions
Fl_Type ()
int user_defined (const char *cbname) const
Protected Attributes
const char * name_
const char * label_
const char * callback_
const char * user_data_
const char * user_data_type_
const char * comment_
Friends
class Widget_Browser
class Fl_Window_Type
Fl_Widget * make_type_browser (int, int, int, int, const char *l=0)
Detailed Description
Definition at line 45 of file Fl_Type.h.
Constructor & Destructor Documentation
Fl_Type::Fl_Type () [protected]
Definition at line 466 of file Fl_Type.cxx.
References callback_, code_position, code_position_end, comment_, factory, header_position, header_position_end, label_, level, name_, new_selected, next, parent, prev, rtti, selected, user_data_, user_data_type_, and visible.
Fl_Type::~Fl_Type () [virtual]
Definition at line 658 of file Fl_Type.cxx.
References callback_, comment_, current, Fl_Browser_::deleting(), first, label_, last, name_, next, parent, prev, remove_child(), user_data_, and user_data_type_.
Member Function Documentation
void Fl_Type::add (Fl_Type * parent)
Definition at line 501 of file Fl_Type.cxx.
References add_child(), first, last, level, next, open_, parent, prev, Fl_Widget::redraw(), set_modflag(), and undo_checkpoint().
Referenced by group_cb(), Fl_Window_Type::make(), Fl_Menu_Item_Type::make(), Fl_CodeBlock_Type::make(), and Fl_Code_Type::make().
void Fl_Type::add_child (Fl_Type * , Fl_Type * beforethis) [virtual]
Reimplemented in Fl_Group_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Window_Type, Fl_Submenu_Type, and Fl_Menu_Type.
Definition at line 496 of file Fl_Type.cxx.
Referenced by add(), Fl_Submenu_Type::add_child(), insert(), read_file(), and Fl_Widget_Type::redraw().
virtual const char* Fl_Type::alt_type_name () [inline, virtual]
Reimplemented in Fl_Box_Type, Fl_Button_Type, Fl_Return_Button_Type, Fl_Repeat_Button_Type, Fl_Light_Button_Type, Fl_Check_Button_Type, Fl_Round_Button_Type, Fl_Browser_Type, Fl_Check_Browser_Type, Fl_Tree_Type, Fl_File_Browser_Type, Fl_Counter_Type, Fl_Spinner_Type, Fl_Input_Type, Fl_File_Input_Type, Fl_Text_Display_Type, Fl_Text_Editor_Type, Fl_Clock_Type, Fl_Help_View_Type, Fl_Progress_Type, Fl_Adjuster_Type, Fl_Dial_Type, Fl_Roller_Type, Fl_Slider_Type, Fl_Scrollbar_Type, Fl_Output_Type, Fl_Value_Input_Type, Fl_Value_Output_Type, Fl_Value_Slider_Type, Fl_Group_Type, Fl_Pack_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, Fl_Tile_Type, Fl_Wizard_Type, Fl_Window_Type, Fl_Menu_Item_Type, Fl_Submenu_Type, Fl_Menu_Button_Type, Fl_Choice_Type, Fl_Input_Choice_Type, and Fl_Menu_Bar_Type.
Definition at line 96 of file Fl_Type.h.
References type_name().
Referenced by Fl_Type_make().
void Fl_Type::callback (const char * n)
Definition at line 636 of file Fl_Type.cxx.
References callback_, and storestring().
const char* Fl_Type::callback () const [inline]
Definition at line 102 of file Fl_Type.h.
References callback_.
Referenced by callback_cb(), callback_name(), Fl_Widget_Type::read_fdesign(), read_property(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Menu_Item_Type::write_item(), write_properties(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), and Fl_Widget_Type::write_widget_code().
const char * Fl_Type::callback_name ()
Definition at line 2065 of file Fl_Widget_Type.cxx.
References callback(), is_name(), label(), name(), and unique_id().
Referenced by Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Menu_Item_Type::write_item(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), and Fl_Widget_Type::write_widget_code().
const char * Fl_Type::class_name (const int need_nest) const
Definition at line 1271 of file Fl_Function_Type.cxx.
References class_name(), is_class(), name(), parent, strlcat, and strlcpy.
Referenced by array_name(), class_name(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Data_Type::write_code1(), Fl_Decl_Type::write_code1(), Fl_Function_Type::write_code1(), Fl_Menu_Item_Type::write_item(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), and Fl_Widget_Type::write_widget_code().
Fl_Type * Fl_Type::click_test (int , int) [virtual]
Reimplemented in Fl_Tabs_Type, Fl_Menu_Type, and Fl_Input_Choice_Type.
Definition at line 495 of file Fl_Type.cxx.
Referenced by Fl_Window_Type::handle().
const char* Fl_Type::comment () [inline]
Definition at line 108 of file Fl_Type.h.
References comment_.
Referenced by Fl_Class_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_Function_Type::open(), read_property(), write_comment_c(), write_comment_h(), and write_properties().
void Fl_Type::comment (const char * n)
Definition at line 648 of file Fl_Type.cxx.
References comment_, and storestring().
void Fl_Type::copy_properties () [virtual]
Copy all needed properties for this tye into the live object.
Reimplemented in Fl_Input_Type, Fl_Widget_Type, Fl_Group_Type, Fl_Pack_Type, Fl_Scroll_Type, Fl_Tile_Type, Fl_Window_Type, Fl_Menu_Type, and Fl_Input_Choice_Type.
Definition at line 1008 of file Fl_Type.cxx.
Fl_Widget * Fl_Type::enter_live_mode (int top = 0) [virtual]
Build widgets and dataset needed in live mode.
Returns:
a widget pointer that the live mode initiator can 'show()'
See also:
leave_live_mode()
Reimplemented in Fl_Widget_Type, Fl_Group_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, and Fl_Window_Type.
Definition at line 994 of file Fl_Type.cxx.
Referenced by Fl_Window_Type::enter_live_mode(), Fl_Scroll_Type::enter_live_mode(), Fl_Tabs_Type::enter_live_mode(), and Fl_Group_Type::enter_live_mode().
void Fl_Type::insert (Fl_Type * n)
Definition at line 541 of file Fl_Type.cxx.
References add_child(), first, level, next, parent, prev, Fl_Widget::redraw(), and visible.
Referenced by Fl_Window_Type::add_child(), Fl_Group_Type::add_child(), Fl_Window_Type::move_child(), Fl_Table_Type::move_child(), Fl_Group_Type::move_child(), and ungroup_cb().
int Fl_Type::is_button () const [virtual]
Reimplemented in Fl_Button_Type, Fl_Menu_Item_Type, and Fl_Submenu_Type.
Definition at line 677 of file Fl_Type.cxx.
Referenced by Fl_Widget_Type::copy_properties(), down_box_cb(), Fl_Widget_Type::read_property(), shortcut_in_cb(), value_cb(), Fl_Widget_Type::write_properties(), Fl_Widget_Type::write_widget_code(), and xclass_cb().
int Fl_Type::is_class () const [virtual]
Reimplemented in Fl_Class_Type, and Fl_Widget_Class_Type.
Definition at line 688 of file Fl_Type.cxx.
Referenced by class_name(), is_in_class(), Fl_Widget_Class_Type::make(), subclassname(), write(), Fl_Window_Type::write_code2(), Fl_Widget_Type::write_color(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), and Fl_Widget_Type::write_widget_code().
int Fl_Type::is_code_block () const [virtual]
Reimplemented in Fl_Function_Type, Fl_Code_Type, Fl_CodeBlock_Type, and Fl_Widget_Class_Type.
Definition at line 685 of file Fl_Type.cxx.
Referenced by Fl_Window_Type::make(), Fl_Comment_Type::make(), Fl_CodeBlock_Type::make(), and Fl_Code_Type::make().
int Fl_Type::is_comment () const [virtual]
Reimplemented in Fl_Comment_Type.
Definition at line 687 of file Fl_Type.cxx.
Referenced by name(), and write_code().
int Fl_Type::is_decl_block () const [virtual]
Reimplemented in Fl_DeclBlock_Type, Fl_Class_Type, and Fl_Widget_Class_Type.
Definition at line 686 of file Fl_Type.cxx.
Referenced by Fl_Decl_Type::is_public(), Fl_Widget_Class_Type::make(), Fl_Class_Type::make(), Fl_DeclBlock_Type::make(), Fl_Data_Type::make(), Fl_Decl_Type::make(), and Fl_Function_Type::make().
int Fl_Type::is_group () const [virtual]
Reimplemented in Fl_Group_Type, and Fl_Window_Type.
Definition at line 683 of file Fl_Type.cxx.
Referenced by Fl_Window_Type::draw_overlay(), fix_group_size(), Fl_Widget_Type::make(), and Fl_Widget_Type::write_widget_code().
const Fl_Class_Type * Fl_Type::is_in_class () const
If this Type resides inside a class, this function returns the class type, or null.
Definition at line 1296 of file Fl_Function_Type.cxx.
References is_class(), and parent.
Referenced by has_toplevel_function(), name_public_cb(), name_public_member_cb(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_Function_Type::open(), Fl_Data_Type::write_code1(), Fl_Decl_Type::write_code1(), and Fl_Widget_Type::write_static().
int Fl_Type::is_input () const [virtual]
Reimplemented in Fl_Input_Type, and Fl_File_Input_Type.
Definition at line 678 of file Fl_Type.cxx.
Referenced by Fl_Widget_Type::copy_properties(), Fl_Widget_Type::read_property(), shortcut_in_cb(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
int Fl_Type::is_menu_button () const [virtual]
Reimplemented in Fl_Menu_Type.
Definition at line 682 of file Fl_Type.cxx.
Referenced by align_widget_cb(), down_box_cb(), Fl_Menu_Item_Type::make(), read_file(), Fl_Widget_Type::read_property(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
int Fl_Type::is_menu_item () const [virtual]
Reimplemented in Fl_Menu_Item_Type.
Definition at line 681 of file Fl_Type.cxx.
Referenced by align_cb(), align_position_cb(), align_text_image_cb(), box_cb(), Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), color2_cb(), color_cb(), down_box_cb(), group_cb(), Fl_Window_Type::handle(), hotspot_cb(), Fl_Widget_Type::make(), Fl_Menu_Item_Type::make(), Fl_Menu_Item_Type::menu_name(), Fl_Window_Type::moveallchildren(), Fl_Widget_Type::redraw(), resizable_cb(), sort(), subclass_cb(), ungroup_cb(), value_cb(), when_button_cb(), when_cb(), Fl_Menu_Item_Type::write_code1(), Fl_Menu_Type::write_code2(), Fl_Widget_Type::write_properties(), Fl_Menu_Item_Type::write_static(), and xclass_cb().
int Fl_Type::is_parent () const [virtual]
Reimplemented in Fl_Function_Type, Fl_CodeBlock_Type, Fl_DeclBlock_Type, Fl_Class_Type, Fl_Group_Type, Fl_Window_Type, Fl_Widget_Class_Type, Fl_Submenu_Type, and Fl_Menu_Type.
Definition at line 673 of file Fl_Type.cxx.
Referenced by Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), Fl_Menu_Item_Type::flags(), Widget_Browser::handle(), Fl_Menu_Item_Type::make(), Fl_Menu_Item_Type::menu_name(), write(), Fl_Widget_Type::write_code1(), and write_properties().
int Fl_Type::is_public () const [virtual]
Reimplemented in Fl_Function_Type, Fl_Code_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, and Fl_Widget_Type.
Definition at line 689 of file Fl_Type.cxx.
Referenced by Fl_Decl_Type::is_public().
int Fl_Type::is_spinner () const [virtual]
Reimplemented in Fl_Spinner_Type.
Definition at line 676 of file Fl_Type.cxx.
Referenced by Fl_Widget_Type::copy_properties(), max_cb(), min_cb(), Fl_Widget_Type::read_property(), step_cb(), subtype_cb(), value_cb(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
int Fl_Type::is_text_display () const [virtual]
Reimplemented in Fl_Text_Display_Type, and Fl_Text_Editor_Type.
Definition at line 680 of file Fl_Type.cxx.
Referenced by Fl_Widget_Type::copy_properties(), Fl_Widget_Type::read_property(), shortcut_in_cb(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
int Fl_Type::is_valuator () const [virtual]
Reimplemented in Fl_Value_Input_Type, and Fl_Value_Output_Type.
Definition at line 675 of file Fl_Type.cxx.
Referenced by Fl_Widget_Type::copy_properties(), max_cb(), min_cb(), Fl_Widget_Type::read_property(), slider_size_cb(), step_cb(), value_cb(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
int Fl_Type::is_value_input () const [virtual]
Reimplemented in Fl_Value_Input_Type.
Definition at line 679 of file Fl_Type.cxx.
Referenced by Fl_Widget_Type::copy_properties(), Fl_Widget_Type::read_property(), shortcut_in_cb(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
int Fl_Type::is_widget () const [virtual]
Reimplemented in Fl_Widget_Type.
Definition at line 674 of file Fl_Type.cxx.
Referenced by Fl_Window_Type::add_child(), align_widget_cb(), check_redraw_corresponding_parent(), Fl_Window_Type::draw_overlay(), group_cb(), Fl_Window_Type::handle(), hotspot_cb(), Fl_Widget_Class_Type::make(), Fl_Widget_Type::make(), move_before(), Fl_Window_Type::moveallchildren(), msgnum(), Fl_Widget_Type::read_fdesign(), Fl_Widget_Type::redraw(), sort(), subclassname(), ungroup_cb(), Fl_Function_Type::write_code1(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), write_strings(), and Fl_Widget_Type::write_widget_code().
int Fl_Type::is_window () const [virtual]
Reimplemented in Fl_Window_Type.
Definition at line 684 of file Fl_Type.cxx.
Referenced by active_cb(), border_cb(), grid_cb(), hotspot_cb(), image_browse_cb(), image_cb(), inactive_browse_cb(), inactive_cb(), live_mode_cb(), Fl_Widget_Type::make(), max_h_cb(), max_w_cb(), min_h_cb(), min_w_cb(), modal_cb(), non_modal_cb(), print_cb(), print_menu_cb(), Fl_Widget_Type::read_fdesign(), Fl_Widget_Type::resizable(), save_template_cb(), Fl_Widget_Type::setimage(), Fl_Widget_Type::setinactive(), slider_size_cb(), visible_cb(), Fl_Widget_Type::write_code1(), Fl_Function_Type::write_code2(), Fl_Widget_Type::write_properties(), Fl_Widget_Type::write_widget_code(), and xclass_cb().
const char* Fl_Type::label () const [inline]
Definition at line 100 of file Fl_Type.h.
References label_.
Referenced by callback_name(), label_cb(), Fl_Widget_Type::make(), Fl_Menu_Item_Type::make(), Fl_Menu_Item_Type::menu_name(), msgnum(), Fl_Window_Type::read_fdesign(), Fl_Widget_Type::read_fdesign(), read_fdesign(), Fl_Widget_Type::read_property(), read_property(), revert_cb(), Fl_Widget_Class_Type::write_code1(), Fl_Widget_Type::write_code1(), Fl_Menu_Type::write_code2(), Fl_Menu_Item_Type::write_item(), write_properties(), and write_strings().
void Fl_Type::label (const char * n)
Definition at line 629 of file Fl_Type.cxx.
References label_, name_, Fl_Widget::redraw(), storestring(), and visible.
void Fl_Type::leave_live_mode () [virtual]
Release all resources created when enetring live mode.
See also:
enter_live_mode()
Reimplemented in Fl_Widget_Type, Fl_Group_Type, and Fl_Window_Type.
Definition at line 1002 of file Fl_Type.cxx.
Referenced by live_mode_cb().
virtual Fl_Type* Fl_Type::make () [pure virtual]
Implemented in Fl_Function_Type, Fl_Code_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_Data_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, Fl_Widget_Type, Fl_Group_Type, Fl_Window_Type, Fl_Widget_Class_Type, Fl_Menu_Item_Type, and Fl_Submenu_Type.
Referenced by Fl_Type_make().
void Fl_Type::move_before (Fl_Type * g)
Definition at line 776 of file Fl_Type.cxx.
References Fl_Browser_::display(), Fl_Browser_::inserting(), is_widget(), last, level, move_child(), next, parent, prev, and Fl_Widget::redraw().
Referenced by earlier_cb(), group_cb(), later_cb(), and sort().
void Fl_Type::move_child (Fl_Type * , Fl_Type * beforethis) [virtual]
Reimplemented in Fl_Group_Type, Fl_Table_Type, Fl_Window_Type, Fl_Submenu_Type, and Fl_Menu_Type.
Definition at line 497 of file Fl_Type.cxx.
Referenced by move_before(), and Fl_Submenu_Type::move_child().
int Fl_Type::msgnum ()
Definition at line 560 of file Fl_Type.cxx.
References is_widget(), label(), parent, and prev.
Referenced by Fl_Widget_Type::write_code1(), Fl_Menu_Type::write_code2(), and Fl_Widget_Type::write_widget_code().
void Fl_Type::name (const char * n)
Definition at line 622 of file Fl_Type.cxx.
References is_comment(), name_, Fl_Widget::redraw(), storestring(), and visible.
const char* Fl_Type::name () const [inline]
Definition at line 98 of file Fl_Type.h.
References name_.
Referenced by array_name(), callback_name(), class_name(), Fl_Function_Type::has_signature(), Fl_Widget_Class_Type::make(), Fl_Class_Type::make(), Fl_DeclBlock_Type::make(), Fl_CodeBlock_Type::make(), Fl_Code_Type::make(), Fl_Function_Type::make(), Fl_Menu_Item_Type::menu_name(), name_cb(), Fl_Class_Type::open(), Fl_Comment_Type::open(), Fl_DeclBlock_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_CodeBlock_Type::open(), Fl_Code_Type::open(), Fl_Function_Type::open(), Fl_Widget_Type::read_fdesign(), read_fdesign(), Fl_Function_Type::title(), title(), Fl_Comment_Type::title(), user_defined(), write(), Fl_Widget_Type::write_block_close(), Fl_Widget_Class_Type::write_code1(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Class_Type::write_code1(), Fl_Comment_Type::write_code1(), Fl_DeclBlock_Type::write_code1(), Fl_Data_Type::write_code1(), Fl_Decl_Type::write_code1(), Fl_CodeBlock_Type::write_code1(), Fl_Code_Type::write_code1(), Fl_Function_Type::write_code1(), Fl_Window_Type::write_code2(), Fl_Menu_Type::write_code2(), Fl_Group_Type::write_code2(), Fl_Function_Type::write_code2(), Fl_Widget_Type::write_color(), Fl_Menu_Item_Type::write_static(), and Fl_Widget_Type::write_widget_code().
void Fl_Type::open () [virtual]
Reimplemented in Fl_Function_Type, Fl_Code_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_Data_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, Fl_Widget_Type, and Fl_Window_Type.
Definition at line 652 of file Fl_Type.cxx.
References type_name().
Referenced by Fl_Window_Type::handle(), Widget_Browser::handle(), openwidget_cb(), and type_make_cb().
virtual int Fl_Type::pixmapID () [inline, virtual]
Reimplemented in Fl_Box_Type, Fl_Button_Type, Fl_Return_Button_Type, Fl_Repeat_Button_Type, Fl_Light_Button_Type, Fl_Check_Button_Type, Fl_Round_Button_Type, Fl_Browser_Type, Fl_Check_Browser_Type, Fl_Tree_Type, Fl_File_Browser_Type, Fl_Input_Type, Fl_File_Input_Type, Fl_Text_Display_Type, Fl_Text_Editor_Type, Fl_Clock_Type, Fl_Help_View_Type, Fl_Progress_Type, Fl_Adjuster_Type, Fl_Dial_Type, Fl_Roller_Type, Fl_Slider_Type, Fl_Scrollbar_Type, Fl_Output_Type, Fl_Value_Input_Type, Fl_Value_Output_Type, Fl_Value_Slider_Type, Fl_Function_Type, Fl_Code_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_Data_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, Fl_Group_Type, Fl_Pack_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, Fl_Tile_Type, Fl_Wizard_Type, Fl_Window_Type, Fl_Widget_Class_Type, Fl_Menu_Item_Type, Fl_Submenu_Type, Fl_Menu_Button_Type, Fl_Choice_Type, Fl_Input_Choice_Type, and Fl_Menu_Bar_Type.
Definition at line 159 of file Fl_Type.h.
Referenced by fill_in_New_Menu().
int Fl_Type::read_fdesign (const char * , const char *) [virtual]
Reimplemented in Fl_Widget_Type, and Fl_Window_Type.
Definition at line 907 of file Fl_Type.cxx.
void Fl_Type::read_property (const char * c) [virtual]
Reimplemented in Fl_Function_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_Data_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, Fl_Widget_Type, Fl_Window_Type, and Fl_Widget_Class_Type.
Definition at line 888 of file Fl_Type.cxx.
References callback(), comment(), label(), open_, read_error(), read_word(), select(), user_data(), and user_data_type().
Fl_Type * Fl_Type::remove ()
Definition at line 577 of file Fl_Type.cxx.
References first, last, level, next, parent, prev, Fl_Widget::redraw(), remove_child(), and selection_changed().
Referenced by group_cb(), Fl_Window_Type::move_child(), Fl_Table_Type::move_child(), Fl_Group_Type::move_child(), Fl_Window_Type::remove_child(), Fl_Table_Type::remove_child(), Fl_Group_Type::remove_child(), and ungroup_cb().
void Fl_Type::remove_child (Fl_Type *) [virtual]
Reimplemented in Fl_Group_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Window_Type, Fl_Submenu_Type, and Fl_Menu_Type.
Definition at line 498 of file Fl_Type.cxx.
Referenced by remove(), Fl_Submenu_Type::remove_child(), and ~Fl_Type().
const char * Fl_Type::title () [virtual]
Reimplemented in Fl_Function_Type, and Fl_Comment_Type.
Definition at line 260 of file Fl_Type.cxx.
References name(), and type_name().
Referenced by Widget_Browser::handle(), name_cb(), and write_code1().
virtual const char* Fl_Type::type_name () [pure virtual]
Implemented in Fl_Box_Type, Fl_Button_Type, Fl_Return_Button_Type, Fl_Repeat_Button_Type, Fl_Light_Button_Type, Fl_Check_Button_Type, Fl_Round_Button_Type, Fl_Browser_Type, Fl_Check_Browser_Type, Fl_Tree_Type, Fl_File_Browser_Type, Fl_Counter_Type, Fl_Spinner_Type, Fl_Input_Type, Fl_File_Input_Type, Fl_Text_Display_Type, Fl_Text_Editor_Type, Fl_Clock_Type, Fl_Help_View_Type, Fl_Progress_Type, Fl_Adjuster_Type, Fl_Dial_Type, Fl_Roller_Type, Fl_Slider_Type, Fl_Scrollbar_Type, Fl_Output_Type, Fl_Value_Input_Type, Fl_Value_Output_Type, Fl_Value_Slider_Type, Fl_Function_Type, Fl_Code_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_Data_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, Fl_Group_Type, Fl_Pack_Type, Fl_Table_Type, Fl_Tabs_Type, Fl_Scroll_Type, Fl_Tile_Type, Fl_Wizard_Type, Fl_Window_Type, Fl_Widget_Class_Type, Fl_Menu_Item_Type, Fl_Submenu_Type, Fl_Menu_Button_Type, Fl_Choice_Type, Fl_Input_Choice_Type, and Fl_Menu_Bar_Type.
Referenced by alt_type_name(), color_cb(), down_box_cb(), fill_in_New_Menu(), Fl_Type_make(), group_cb(), Fl_Class_Type::has_function(), has_toplevel_function(), open(), Fl_Widget_Type::read_property(), subclassname(), title(), ungroup_cb(), user_defined(), visible_cb(), wc_relative_cb(), write(), Fl_Widget_Type::write_properties(), Fl_Widget_Type::write_static(), and Fl_Widget_Type::write_widget_code().
const char* Fl_Type::user_data () const [inline]
Definition at line 104 of file Fl_Type.h.
References user_data_.
Referenced by Fl_Menu_Item_Type::flags(), Fl_Widget_Type::read_fdesign(), read_property(), user_data_cb(), Fl_Menu_Item_Type::write_item(), write_properties(), and Fl_Widget_Type::write_widget_code().
void Fl_Type::user_data (const char * n)
Definition at line 640 of file Fl_Type.cxx.
References storestring(), and user_data_.
const char* Fl_Type::user_data_type () const [inline]
Definition at line 106 of file Fl_Type.h.
References user_data_type_.
Referenced by Fl_Widget_Type::read_fdesign(), read_property(), user_data_type_cb(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), write_properties(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
void Fl_Type::user_data_type (const char * n)
Definition at line 644 of file Fl_Type.cxx.
References storestring(), and user_data_type_.
int Fl_Type::user_defined (const char * cbname) const [protected]
Check whether callback name is declared anywhere else by the user
Warning: this just checks that the name is declared somewhere, but it should probably also check that the name corresponds to a plain function or a member function within the same class and that the parameter types match.
Definition at line 1019 of file Fl_Type.cxx.
References name(), next, and type_name().
Referenced by Fl_Menu_Item_Type::write_static().
void Fl_Type::write ()
Definition at line 835 of file Fl_Type.cxx.
References is_class(), is_parent(), level, name(), next, type_name(), write(), write_close(), write_indent(), write_open(), write_properties(), and write_word().
Referenced by write().
void Fl_Type::write_code1 () [virtual]
Reimplemented in Fl_Function_Type, Fl_Code_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_Data_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, Fl_Widget_Type, Fl_Group_Type, Fl_Window_Type, Fl_Widget_Class_Type, and Fl_Menu_Item_Type.
Definition at line 595 of file code.cxx.
References title(), write_c(), and write_h().
Referenced by write_code().
void Fl_Type::write_code2 () [virtual]
Reimplemented in Fl_Function_Type, Fl_Code_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_Data_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, Fl_Widget_Type, Fl_Group_Type, Fl_Window_Type, Fl_Widget_Class_Type, Fl_Menu_Item_Type, and Fl_Menu_Type.
Definition at line 599 of file code.cxx.
void Fl_Type::write_comment_c (const char * pre = "")
Write a comment inot the header file.
Definition at line 950 of file Fl_Type.cxx.
References comment(), and write_c().
Referenced by Fl_Data_Type::write_code1(), Fl_Decl_Type::write_code1(), and Fl_Function_Type::write_code1().
void Fl_Type::write_comment_h (const char * pre = "")
Write a comment inot the header file.
Definition at line 927 of file Fl_Type.cxx.
References comment(), and write_h().
Referenced by Fl_Class_Type::write_code1(), Fl_Data_Type::write_code1(), and Fl_Decl_Type::write_code1().
void Fl_Type::write_properties () [virtual]
Reimplemented in Fl_Function_Type, Fl_CodeBlock_Type, Fl_Decl_Type, Fl_Data_Type, Fl_DeclBlock_Type, Fl_Comment_Type, Fl_Class_Type, Fl_Widget_Type, Fl_Window_Type, and Fl_Widget_Class_Type.
Definition at line 858 of file Fl_Type.cxx.
References callback(), comment(), is_parent(), label(), level, open_, selected, user_data(), user_data_type(), write_indent(), and write_word().
Referenced by write().
void Fl_Type::write_static () [virtual]
Reimplemented in Fl_Widget_Type, and Fl_Menu_Item_Type.
Definition at line 594 of file code.cxx.
Friends And Related Function Documentation
friend class Fl_Window_Type [friend]
Definition at line 49 of file Fl_Type.h.
Fl_Widget* make_type_browser (int , int , int , int , const char * l = 0) [friend]
friend class Widget_Browser [friend]
Definition at line 47 of file Fl_Type.h.
Referenced by make_widget_browser().
Member Data Documentation
const char* Fl_Type::callback_ [protected]
Definition at line 58 of file Fl_Type.h.
Referenced by callback(), Fl_Type(), and ~Fl_Type().
int Fl_Type::code_position
Definition at line 78 of file Fl_Type.h.
Referenced by Fl_Type(), update_sourceview_position(), and write_code().
int Fl_Type::code_position_end
Definition at line 79 of file Fl_Type.h.
Referenced by Fl_Type(), update_sourceview_position(), and write_code().
const char* Fl_Type::comment_ [protected]
Definition at line 61 of file Fl_Type.h.
Referenced by comment(), Fl_Type(), and ~Fl_Type().
Fl_Type * Fl_Type::current [static]
Definition at line 116 of file Fl_Type.h.
Referenced by copy_cb(), cut_cb(), delete_cb(), duplicate_cb(), group_cb(), Fl_Window_Type::handle(), Fl_Widget_Class_Type::make(), Fl_Window_Type::make(), Fl_Widget_Type::make(), Fl_Menu_Item_Type::make(), Fl_Class_Type::make(), Fl_Comment_Type::make(), Fl_DeclBlock_Type::make(), Fl_Data_Type::make(), Fl_Decl_Type::make(), Fl_CodeBlock_Type::make(), Fl_Code_Type::make(), Fl_Function_Type::make(), openwidget_cb(), read_fdesign(), read_file(), select_all_cb(), select_none_cb(), ungroup_cb(), update_sourceview_position(), Fl_Wizard_Type::widget(), Fl_Tabs_Type::widget(), Fl_Group_Type::widget(), and ~Fl_Type().
Fl_Type* Fl_Type::factory
Definition at line 75 of file Fl_Type.h.
Referenced by Fl_Type(), Fl_Window_Type::make(), Fl_Widget_Type::make(), Fl_Menu_Item_Type::make(), Fl_CodeBlock_Type::make(), Fl_Code_Type::make(), Fl_Widget_Type::read_fdesign(), Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
Fl_Type * Fl_Type::first [static]
Definition at line 72 of file Fl_Type.h.
Referenced by active_cb(), add(), align_cb(), align_position_cb(), align_text_image_cb(), align_widget_cb(), box_cb(), callback_cb(), color2_cb(), color_cb(), down_box_cb(), grid_cb(), group_cb(), guides_cb(), h_cb(), image_browse_cb(), image_cb(), inactive_browse_cb(), inactive_cb(), insert(), label_cb(), labelcolor_cb(), labelfont_cb(), labelsize_cb(), labeltype_cb(), max_cb(), max_h_cb(), max_w_cb(), min_cb(), min_h_cb(), min_w_cb(), name_public_cb(), name_public_member_cb(), print_cb(), print_menu_cb(), read_file(), redraw_overlays(), remove(), save_template_cb(), selection_changed(), set_max_size_cb(), set_min_size_cb(), shortcut_in_cb(), slider_size_cb(), sort(), step_cb(), subclass_cb(), subtype_cb(), textcolor_cb(), textfont_cb(), textsize_cb(), toggle_overlays(), tooltip_cb(), user_data_cb(), user_data_type_cb(), v_input_cb(), value_cb(), visible_cb(), w_cb(), wc_relative_cb(), when_button_cb(), when_cb(), widget_size_cb(), write_code(), write_file(), write_strings(), x_cb(), xclass_cb(), y_cb(), and ~Fl_Type().
int Fl_Type::header_position
Definition at line 78 of file Fl_Type.h.
Referenced by Fl_Type(), update_sourceview_position(), and write_code().
int Fl_Type::header_position_end
Definition at line 79 of file Fl_Type.h.
Referenced by Fl_Type(), update_sourceview_position(), and write_code().
const char* Fl_Type::label_ [protected]
Definition at line 57 of file Fl_Type.h.
Referenced by Fl_Type(), label(), and ~Fl_Type().
Fl_Type * Fl_Type::last
Definition at line 72 of file Fl_Type.h.
Referenced by add(), move_before(), remove(), write_code(), and ~Fl_Type().
int Fl_Type::level
Definition at line 71 of file Fl_Type.h.
Referenced by add(), align_widget_cb(), Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), Fl_Window_Type::draw_overlay(), earlier_cb(), Fl_Window_Type::enter_live_mode(), Fl_Scroll_Type::enter_live_mode(), Fl_Tabs_Type::enter_live_mode(), Fl_Group_Type::enter_live_mode(), fix_group_size(), Fl_Type(), group_cb(), Fl_Window_Type::handle(), Widget_Browser::handle(), Fl_Class_Type::has_function(), hotspot_cb(), insert(), later_cb(), Fl_Menu_Item_Type::menu_name(), move_before(), Fl_Window_Type::moveallchildren(), remove(), select_all_cb(), select_none_cb(), sort(), ungroup_cb(), write(), write_code(), Fl_Function_Type::write_code1(), Fl_Function_Type::write_code2(), Fl_Widget_Type::write_properties(), write_properties(), and Fl_Menu_Item_Type::write_static().
const char* Fl_Type::name_ [protected]
Definition at line 56 of file Fl_Type.h.
Referenced by Fl_Type(), Fl_Function_Type::ismain(), label(), name(), and ~Fl_Type().
char Fl_Type::new_selected
Definition at line 66 of file Fl_Type.h.
Referenced by Fl_Type(), Widget_Browser::handle(), select_all_cb(), and select_none_cb().
Fl_Type* Fl_Type::next
Definition at line 73 of file Fl_Type.h.
Referenced by active_cb(), add(), align_widget_cb(), box_cb(), Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), color2_cb(), color_cb(), delete_all(), down_box_cb(), Fl_Window_Type::draw_overlay(), earlier_cb(), Fl_Window_Type::enter_live_mode(), Fl_Scroll_Type::enter_live_mode(), Fl_Tabs_Type::enter_live_mode(), Fl_Group_Type::enter_live_mode(), fix_group_size(), Fl_Type(), grid_cb(), guides_cb(), h_cb(), Fl_Window_Type::handle(), Widget_Browser::handle(), Fl_Class_Type::has_function(), has_toplevel_function(), hotspot_cb(), image_browse_cb(), image_cb(), inactive_browse_cb(), inactive_cb(), insert(), label_cb(), labelcolor_cb(), labelfont_cb(), labelsize_cb(), labeltype_cb(), later_cb(), Fl_Menu_Item_Type::menu_name(), move_before(), Fl_Window_Type::moveallchildren(), name_public_cb(), name_public_member_cb(), print_cb(), print_menu_cb(), read_file(), redraw_overlays(), remove(), save_template_cb(), select_all_cb(), select_none_cb(), shortcut_in_cb(), sort(), toggle_overlays(), tooltip_cb(), ungroup_cb(), user_defined(), visible_cb(), w_cb(), wc_relative_cb(), when_button_cb(), when_cb(), widget_size_cb(), write(), write_code(), Fl_Function_Type::write_code1(), Fl_Menu_Type::write_code2(), Fl_Function_Type::write_code2(), Fl_Menu_Item_Type::write_static(), write_strings(), x_cb(), xclass_cb(), y_cb(), and ~Fl_Type().
char Fl_Type::open_
Definition at line 68 of file Fl_Type.h.
Referenced by add(), Widget_Browser::handle(), read_property(), reveal_in_browser(), and write_properties().
Fl_Type* Fl_Type::parent
Definition at line 65 of file Fl_Type.h.
Referenced by add(), Fl_Submenu_Type::add_child(), align_widget_cb(), class_name(), color_cb(), cut_cb(), delete_cb(), Fl_Type(), group_cb(), Fl_Window_Type::handle(), hotspot_cb(), insert(), is_in_class(), Fl_Decl_Type::is_public(), Fl_Widget_Class_Type::make(), Fl_Window_Type::make(), Fl_Widget_Type::make(), Fl_Menu_Item_Type::make(), Fl_Class_Type::make(), Fl_Comment_Type::make(), Fl_DeclBlock_Type::make(), Fl_Data_Type::make(), Fl_Decl_Type::make(), Fl_CodeBlock_Type::make(), Fl_Code_Type::make(), Fl_Function_Type::make(), move_before(), Fl_Submenu_Type::move_child(), msgnum(), Fl_Widget_Type::read_fdesign(), Fl_Widget_Type::redraw(), remove(), Fl_Submenu_Type::remove_child(), reveal_in_browser(), select_all_cb(), select_none_cb(), ungroup_cb(), visible_cb(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), Fl_Widget_Type::write_widget_code(), and ~Fl_Type().
Fl_Type * Fl_Type::prev
Definition at line 73 of file Fl_Type.h.
Referenced by add(), array_name(), earlier_cb(), Fl_Type(), Fl_Window_Type::handle(), insert(), later_cb(), Fl_Menu_Item_Type::menu_name(), move_before(), msgnum(), remove(), Fl_Menu_Item_Type::write_code1(), Fl_Menu_Item_Type::write_static(), and ~Fl_Type().
char Fl_Type::rtti
Definition at line 70 of file Fl_Type.h.
Referenced by Fl_Type().
char Fl_Type::selected
Definition at line 67 of file Fl_Type.h.
Referenced by align_widget_cb(), check_redraw_corresponding_parent(), Fl_Input_Choice_Type::click_test(), Fl_Menu_Type::click_test(), cut_cb(), delete_all(), delete_cb(), Fl_Window_Type::draw_overlay(), earlier_cb(), Fl_Type(), group_cb(), Fl_Window_Type::handle(), later_cb(), Fl_Window_Type::moveallchildren(), print_cb(), print_menu_cb(), read_file(), selection_changed(), sort(), ungroup_cb(), and write_properties().
const char* Fl_Type::user_data_ [protected]
Definition at line 59 of file Fl_Type.h.
Referenced by Fl_Type(), user_data(), and ~Fl_Type().
const char* Fl_Type::user_data_type_ [protected]
Definition at line 60 of file Fl_Type.h.
Referenced by Fl_Type(), user_data_type(), and ~Fl_Type().
char Fl_Type::visible
Definition at line 69 of file Fl_Type.h.
Referenced by Fl_Type(), insert(), label(), name(), and Fl_Widget_Type::subclass().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/fluid/Fl_Type.h
fltk-1.3.0rc3/fluid/code.cxx
fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx
fltk-1.3.0rc3/fluid/Fl_Type.cxx
fltk-1.3.0rc3/fluid/Fl_Widget_Type.cxx