SfR Fresh Dox - fltk: Fl_Window Class Reference
Fl_Window Class Reference
#include <Fl_Window.H>
Public Member Functions
Fl_Window (int w, int h, const char *title=0)
Fl_Window (int x, int y, int w, int h, const char *title=0)
virtual ~Fl_Window ()
virtual int handle (int)
virtual void resize (int, int, int, int)
void border (int b)
void clear_border ()
unsigned int border () const
void set_override ()
unsigned int override () const
void set_modal ()
unsigned int modal () const
void set_non_modal ()
unsigned int non_modal () const
void set_menu_window ()
unsigned int menu_window () const
void set_tooltip_window ()
unsigned int tooltip_window () const
void hotspot (int x, int y, int offscreen=0)
void hotspot (const Fl_Widget *, int offscreen=0)
void hotspot (const Fl_Widget &p, int offscreen=0)
void free_position ()
void size_range (int a, int b, int c=0, int d=0, int e=0, int f=0, int g=0)
const char * label () const
const char * iconlabel () const
void label (const char *)
void iconlabel (const char *)
void label (const char *label, const char *iconlabel)
void copy_label (const char *a)
const char * xclass () const
void xclass (const char *c)
const void * icon () const
void icon (const void *ic)
int shown ()
virtual void show ()
virtual void hide ()
void show (int argc, char **argv)
void fullscreen ()
void fullscreen_off (int, int, int, int)
void iconize ()
int x_root () const
int y_root () const
void make_current ()
virtual Fl_Window * as_window ()
void cursor (Fl_Cursor, Fl_Color=FL_BLACK, Fl_Color=FL_WHITE)
void default_cursor (Fl_Cursor, Fl_Color=FL_BLACK, Fl_Color=FL_WHITE)
Static Public Member Functions
static void default_xclass (const char *)
static const char * default_xclass ()
static Fl_Window * current ()
static void default_callback (Fl_Window *, void *v)
Protected Member Functions
virtual void draw ()
virtual void flush ()
void force_position (int force)
int force_position () const
Static Protected Attributes
static Fl_Window * current_
Friends
class Fl_X
Detailed Description
This widget produces an actual window. This can either be a main window, with a border and title and all the window management controls, or a "subwindow" inside a window. This is controlled by whether or not the window has a parent().
Once you create a window, you usually add children Fl_Widget 's to it by using window->add(child) for each new widget. See Fl_Group for more information on how to add and remove children.
There are several subclasses of Fl_Window that provide double-buffering, overlay, menu, and OpenGL support.
The window's callback is done if the user tries to close a window using the window manager and Fl::modal() is zero or equal to the window. Fl_Window has a default callback that calls Fl_Window::hide().
Definition at line 58 of file Fl_Window.H.
Constructor & Destructor Documentation
Fl_Window::Fl_Window (int w, int h, const char * title = 0)
Creates a window from the given size and title. If Fl_Group::current() is not NULL, the window is created as a subwindow of the parent window.
The first form of the constructor creates a top-level window and asks the window manager to position the window. The second form of the constructor either creates a subwindow or a top-level window at the specified location (x,y) , subject to window manager configuration. If you do not specify the position of the window, the window manager will pick a place to show the window or allow the user to pick a location. Use position(x,y) or hotspot() before calling show() to request a position on the screen. See Fl_Window::resize() for some more details on positioning windows.
Top-level windows initially have visible() set to 0 and parent() set to NULL. Subwindows initially have visible() set to 1 and parent() set to the parent window pointer.
Fl_Widget::box() defaults to FL_FLAT_BOX. If you plan to completely fill the window with children widgets you should change this to FL_NO_BOX. If you turn the window border off you may want to change this to FL_UP_BOX.
See also:
Fl_Window(int x, int y, int w, int h, const char* title = 0)
Definition at line 75 of file Fl_Window.cxx.
References Fl_Widget::clear_visible(), FL_BLACK, FL_CURSOR_DEFAULT, and FL_WHITE.
Fl_Window::Fl_Window (int x, int y, int w, int h, const char * title = 0)
Creates a window from the given position, size and title.
See also:
Fl_Window::Fl_Window(int w, int h, const char *title = 0)
Definition at line 65 of file Fl_Window.cxx.
References FL_BLACK, FL_CURSOR_DEFAULT, FL_WHITE, Fl_Widget::FORCE_POSITION, and Fl_Widget::set_flag().
Fl_Window::~Fl_Window () [virtual]
The destructor also deletes all the children. This allows a whole tree to be deleted at once, without having to keep a pointer to all the children in the user code. A kludge has been done so the Fl_Window and all of its children can be automatic (local) variables, but you must declare the Fl_Window first so that it is destroyed last.
Definition at line 1307 of file Fl.cxx.
References hide().
Member Function Documentation
virtual Fl_Window* Fl_Window::as_window () [inline, virtual]
Returns an Fl_Window pointer if this widget is an Fl_Window.
Use this method if you have a widget (pointer) and need to know whether this widget is derived from Fl_Window. If it returns non-NULL, then the widget in question is derived from Fl_Window, and you can use the returned pointer to access its children or other Fl_Window-specific methods.
Return values:
NULL if this widget is not derived from Fl_Window.
Note:
This method is provided to avoid dynamic_cast.
See also:
Fl_Widget::as_group(), Fl_Widget::as_gl_window()
Reimplemented from Fl_Widget.
Definition at line 430 of file Fl_Window.H.
unsigned int Fl_Window::border () const [inline]
See void Fl_Window::border(int)
Definition at line 191 of file Fl_Window.H.
References Fl_Widget::flags(), and Fl_Widget::NOBORDER.
Referenced by border(), fullscreen(), fullscreen_off(), and hotspot().
void Fl_Window::border (int b)
Sets whether or not the window manager border is around the window. The default value is true. void border(int) can be used to turn the border on and off. Under most X window managers this does not work after show() has been called, although SGI's 4DWM does work.
Definition at line 43 of file Fl_Window_fullscreen.cxx.
References border(), Fl_Widget::clear_flag(), Fl_X::i(), Fl_Widget::NOBORDER, Fl_X::sendxjunk(), Fl_Widget::set_flag(), and shown().
Referenced by Fl_X::fake_X_wm(), Fl_X::make_xid(), and Fl_X::sendxjunk().
void Fl_Window::clear_border () [inline]
Fast inline function to turn the window manager border off. It only works before show() is called.
Definition at line 189 of file Fl_Window.H.
References Fl_Widget::set_flag().
Referenced by ColorMenu::ColorMenu(), fl_show_form(), menutitle::menutitle(), and menuwindow::menuwindow().
void Fl_Window::copy_label (const char * new_label)
Sets the current label. Unlike label(), this method allocates a copy of the label string instead of using the original string pointer.
The internal copy will automatically be freed whenever you assign a new label or when the widget is destroyed.
Parameters:
[in] new_label the new label text
See also:
label()
Reimplemented from Fl_Widget.
Definition at line 148 of file Fl_Window.cxx.
References Fl_Widget::clear_flag(), Fl_Widget::COPIED_LABEL, Fl_Widget::flags(), iconlabel(), label(), and Fl_Widget::set_flag().
Fl_Window * Fl_Window::current () [static]
Returns the last window that was made current.
See also:
Fl_Window::make_current()
Reimplemented from Fl_Group.
Definition at line 179 of file Fl_Window.cxx.
References current_.
Referenced by fl_read_image(), fl_scroll(), Overlay_Window::Overlay_Window(), and Fl_Paged_Device::print_window_part().
void Fl_Window::cursor (Fl_Cursor c, Fl_Color fg = FL_BLACK, Fl_Color bg = FL_WHITE)
Changes the cursor for this window. This always calls the system, if you are changing the cursor a lot you may want to keep track of how you set it in a static variable and call this only if the new cursor is different.
The type Fl_Cursor is an enumeration defined in <FL/Enumerations.H>. (Under X you can get any XC_cursor value by passing Fl_Cursor((XC_foo/2)+1)). The colors only work on X, they are not implemented on WIN32.
For back compatibility only.
Definition at line 283 of file fl_cursor.cxx.
References b, CURSORSIZE, FL_CURSOR_DEFAULT, FL_CURSOR_NESW, FL_CURSOR_NS, fl_display, fl_screen, fl_xid(), Fl::get_color(), HOTXY, m, and shown().
Referenced by default_cursor(), fl_cursor(), glutSetCursor(), Fl_Text_Editor::handle(), Fl_Text_Display::handle(), Fl_Input::handle(), Fl_File_Input::handle(), Fl_Input_::handletext(), hide(), Fl_File_Chooser::rescan_keep_filename(), and Fl_Wizard::value().
void Fl_Window::default_callback (Fl_Window * win, void * v) [static]
Back compatibility: Sets the default callback v for win to call on close event
Definition at line 174 of file Fl_Window.cxx.
References Fl::atclose.
void Fl_Window::default_cursor (Fl_Cursor c, Fl_Color fg = FL_BLACK, Fl_Color bg = FL_WHITE)
Sets the default window cursor as well as its color.
For back compatibility only.
Definition at line 54 of file fl_cursor.cxx.
References cursor().
const char * Fl_Window::default_xclass () [static]
Returns the default xclass.
See also:
Fl_Window::default_xclass(const char *)
Definition at line 188 of file Fl_Window.cxx.
Referenced by xclass().
void Fl_Window::default_xclass (const char * xc) [static]
Sets the default window xclass.
The default xclass is used for all windows that don't have their own xclass set before show() is called. You can change the default xclass whenever you want, but this only affects windows that are created (and shown) after this call.
The given string xc is copied. You can use a local variable or free the string immediately after this call.
If you don't call this, the default xclass for all windows will be "FLTK". You can reset the default xclass by specifying NULL for xc.
If you call Fl_Window::xclass(const char *) for any window, then this also sets the default xclass, unless it has been set before.
Parameters:
[in] xc default xclass for all windows subsequently created
See also:
Fl_Window::xclass(const char *)
Definition at line 217 of file Fl_Window.cxx.
void Fl_Window::draw () [protected, virtual]
Draws the widget. Never call this function directly. FLTK will schedule redrawing whenever needed. If your widget must be redrawn as soon as possible, call redraw() instead.
Override this function to draw your own widgets.
If you ever need to call another widget's draw method from within your own draw() method, e.g. for an embedded scrollbar, you can do it (because draw() is virtual) like this:
        Fl_Widget *s = &scroll;         // scroll is an embedded Fl_Scrollbar
        s->draw();                      // calls Fl_Scrollbar::draw()
Reimplemented from Fl_Group.
Reimplemented in Fl_Gl_Window, Fl_Glut_Window, and Fl_TooltipBox.
Definition at line 104 of file Fl_Window.cxx.
References Fl_Widget::box(), Fl::box_dh(), Fl::box_dw(), Fl::box_dx(), Fl::box_dy(), Fl_Widget::color(), Fl_Widget::damage(), Fl_Widget::draw_box(), Fl_Group::draw_children(), dx, dy, f, FL_BLACK, fl_color(), fl_color_average(), FL_DAMAGE_CHILD, fl_gc, fl_line(), FL_WHITE, Fl_Widget::h(), Fl_Widget::parent(), Fl_Group::resizable(), and Fl_Widget::w().
Referenced by Fl_Menu_Window::flush(), Fl_Double_Window::flush(), and flush().
void Fl_Window::flush () [protected, virtual]
Forces the window to be drawn, this window is also made current and calls draw().
Reimplemented in Fl_Double_Window, Fl_Gl_Window, Fl_Menu_Window, Fl_Overlay_Window, and Fl_Single_Window.
Definition at line 1542 of file Fl.cxx.
References draw(), fl_clip_region(), make_current(), and Fl_X::region.
int Fl_Window::force_position () const [inline, protected]
Returns the internal state of the window's FORCE_POSITION flag.
Return values:
1 if flag is set
0 otherwise
See also:
force_position(int)
Definition at line 110 of file Fl_Window.H.
References Fl_Widget::flags().
void Fl_Window::force_position (int force) [inline, protected]
Sets an internal flag that tells FLTK and the window manager to honor position requests.
This is used internally and should not be needed by user code.
Parameters:
[in] force 1 to set the FORCE_POSITION flag, 0 to clear it
Definition at line 98 of file Fl_Window.H.
References Fl_Widget::clear_flag(), and Fl_Widget::set_flag().
void Fl_Window::free_position () [inline]
Undoes the effect of a previous resize() or show() so that the next time show() is called the window manager is free to position the window.
This is for Forms compatibility only.
Deprecated:
please use force_position(0) instead
Definition at line 277 of file Fl_Window.H.
References Fl_Widget::clear_flag().
Referenced by fl_show_form().
void Fl_Window::fullscreen ()
Makes the window completely fill the screen, without any window manager border visible. You must use fullscreen_off() to undo this. This may not work with all window managers.
Definition at line 63 of file Fl_Window_fullscreen.cxx.
References border(), Fl::h(), Fl_Widget::h(), resize(), Fl::screen_xywh(), Fl::w(), Fl_Widget::w(), Fl::x(), Fl_Widget::x(), Fl::y(), and Fl_Widget::y().
Referenced by fl_show_form(), and glutFullScreen().
void Fl_Window::fullscreen_off (int X, int Y, int W, int H)
Turns off any side effects of fullscreen() and does resize(x,y,w,h).
Definition at line 85 of file Fl_Window_fullscreen.cxx.
References border(), and resize().
int Fl_Window::handle (int event) [virtual]
Handles the specified event. You normally don't call this method directly, but instead let FLTK do it when the user interacts with the widget.
When implemented in a widget, this function must return 0 if the widget does not use the event or 1 otherwise.
Most of the time, you want to call the inherited handle() method in your overridden method so that you don't short-circuit events that you don't handle. In this last case you should return the callee retval.
Parameters:
[in] event the kind of event received
Return values:
0 if the event was not used or understood
1 if the event was used and can be deleted
See also:
Fl_Event
Reimplemented from Fl_Group.
Reimplemented in Fl_Gl_Window, Fl_Glut_Window, Overlay_Window, and menuwindow.
Definition at line 1322 of file Fl.cxx.
References fl_display, FL_HIDE, FL_SHOW, FL_WINDOW, fl_xid(), Fl_Widget::parent(), show(), shown(), Fl_Widget::type(), Fl_Widget::visible(), XMapWindow, and XUnmapWindow.
Referenced by Overlay_Window::handle(), hide(), Fl_X::make(), and Fl_X::make_xid().
void Fl_Window::hide () [virtual]
Removes the window from the screen. If the window is already hidden or has not been shown then this does nothing and is harmless.
Reimplemented from Fl_Widget.
Reimplemented in Fl_Double_Window, Fl_Gl_Window, Fl_Menu_Window, and Fl_Overlay_Window.
Definition at line 1210 of file Fl.cxx.
References Fl_Widget::clear_visible(), cursor(), Fl::first_window(), FL_CURSOR_DEFAULT, fl_destroy_xft_draw(), fl_display, fl_gc, FL_HIDE, fl_release_dc(), fl_throw_focus(), fl_window, fl_xid(), handle(), hide(), modal(), Fl_X::next, Fl::next_window(), non_modal(), NULL, Fl_Widget::parent(), Fl_X::private_dc, Fl_X::region, Fl_Widget::set_visible(), show(), shown(), Fl_Widget::w(), Fl_Widget::window(), XDestroyRegion(), XDestroyWindow, and Fl_X::xid.
Referenced by cancel_cb(), Fl::default_atclose(), fl_hide_form(), hide(), live_mode_cb(), ok_cb(), toggle_widgetbin_cb(), and ~Fl_Window().
void Fl_Window::hotspot (int x, int y, int offscreen = 0)
Positions the window so that the mouse is pointing at the given position, or at the center of the given widget, which may be the window itself. If the optional offscreen parameter is non-zero, then the window is allowed to extend off the screen (this does not work with some X window managers).
See also:
position()
Definition at line 33 of file Fl_Window_hotspot.cxx.
References border(), Fl::get_mouse(), Fl_Widget::h(), Fl_Widget::position(), Fl::screen_xywh(), Fl_Widget::w(), and Fl_Widget::x().
Referenced by do_shell_command(), Fl_Color_Chooser::fl_color_chooser(), Fl_File_Chooser::Fl_File_Chooser(), fl_set_form_hotobject(), fl_set_form_hotspot(), fl_show_form(), hotspot(), make_about_panel(), make_class_panel(), make_code_panel(), make_codeblock_panel(), make_comment_panel(), make_data_panel(), make_decl_panel(), make_declblock_panel(), make_function_panel(), make_widget_panel(), Fl_File_Chooser::show(), show_global_settings_cb(), show_grid_cb(), show_project_cb(), show_settings_cb(), and show_shell_window().
void Fl_Window::hotspot (const Fl_Widget & p, int offscreen = 0) [inline]
See void Fl_Window::hotspot(int x, int y, int offscreen = 0)
Definition at line 267 of file Fl_Window.H.
References hotspot().
Referenced by hotspot().
void Fl_Window::hotspot (const Fl_Widget * o, int offscreen = 0)
See void Fl_Window::hotspot(int x, int y, int offscreen = 0)
Definition at line 87 of file Fl_Window_hotspot.cxx.
References Fl_Widget::h(), hotspot(), Fl_Widget::w(), Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
const void* Fl_Window::icon () const [inline]
Gets the current icon window target dependent data.
Definition at line 334 of file Fl_Window.H.
Referenced by Fl_X::make_xid().
void Fl_Window::icon (const void * ic) [inline]
Sets the current icon window target dependent data.
Definition at line 336 of file Fl_Window.H.
void Fl_Window::iconize ()
Iconifies the window. If you call this when shown() is false it will show() it as an icon. If the window is already iconified this does nothing.
Call show() to restore the window.
When a window is iconified/restored (either by these calls or by the user) the handle() method is called with FL_HIDE and FL_SHOW events and visible() is turned on and off.
There is no way to control what is drawn in the icon except with the string passed to Fl_Window::xclass(). You should not rely on window managers displaying the icons.
Definition at line 32 of file Fl_Window_iconize.cxx.
References fl_display, fl_screen, fl_show_iconic, show(), shown(), and Fl_X::xid.
Referenced by glutIconifyWindow().
const char* Fl_Window::iconlabel () const [inline]
See void Fl_Window::iconlabel(const char*)
Definition at line 320 of file Fl_Window.H.
Referenced by copy_label(), glutSetIconTitle(), label(), and Fl_X::make_xid().
void Fl_Window::iconlabel (const char * iname)
Sets the icon label.
Definition at line 159 of file Fl_Window.cxx.
References label().
const char* Fl_Window::label () const [inline]
See void Fl_Window::label(const char*)
Reimplemented from Fl_Widget.
Definition at line 318 of file Fl_Window.H.
References Fl_Widget::label().
Referenced by copy_label(), do_shell_command(), Fl_File_Chooser::Fl_File_Chooser(), fl_set_form_title(), fl_show_form(), fl_title_form(), glutSetWindowTitle(), iconlabel(), label(), Fl_File_Chooser::label(), Fl_Help_Dialog::load(), Fl_X::make(), Fl_X::make_xid(), name_cb(), new_cb(), open_history_cb(), print_cb(), save_template_cb(), set_modflag(), show(), and Fl_Help_Dialog::value().
void Fl_Window::label (const char * name)
Sets the window title bar label.
Reimplemented from Fl_Widget.
Definition at line 144 of file Fl_Window.cxx.
References iconlabel(), and label().
void Fl_Window::label (const char * name, const char * iconlabel)
Sets the icon label.
set the window title bar
Todo:
make the titlebar icon work!
Definition at line 2362 of file Fl_mac.cxx.
References fl_xid(), label(), and shown().
void Fl_Window::make_current ()
Sets things up so that the drawing functions in <FL/fl_draw.H> will go into this window. This is useful for incremental update of windows, such as in an idle callback, which will make your program behave much better if it draws a slow graphic. Danger: incremental update is very hard to debug and maintain!
This method only works for the Fl_Window and Fl_Gl_Window derived classes.
make all drawing go into this window (called by subclass flush() impl.)
Reimplemented in Fl_Gl_Window, Fl_Single_Window, and Fl_Glut_Window.
Definition at line 2443 of file Fl_mac.cxx.
References CGContextSaveGState, current_, fl_clip_region(), fl_gc, fl_window, fl_window_region, Fl_Widget::h(), QDBeginCGContext, Fl_Widget::visible_r(), Fl_Widget::w(), Fl_Widget::window(), Fl_Widget::x(), Fl_X::xid, and Fl_Widget::y().
Referenced by callback_cb(), Fl_Double_Window::flush(), flush(), Fl_Paged_Device::print_window_part(), and Overlay_Window::read_image().
unsigned int Fl_Window::menu_window () const [inline]
Returns true if this window is a menu window.
Definition at line 233 of file Fl_Window.H.
References Fl_Widget::flags(), and Fl_Widget::MENU_WINDOW.
Referenced by Fl_X::make_xid().
unsigned int Fl_Window::modal () const [inline]
Returns true if this window is modal.
Definition at line 206 of file Fl_Window.H.
References Fl_Widget::flags(), and Fl_Widget::MODAL.
Referenced by hide(), Fl_X::make(), print_cb(), and Fl_X::set_xid().
unsigned int Fl_Window::non_modal () const [inline]
Returns true if this window is modal or non-modal.
Definition at line 215 of file Fl_Window.H.
References Fl_Widget::flags(), and Fl_Widget::MODAL.
Referenced by hide(), Fl_X::make(), and Fl_X::make_xid().
unsigned int Fl_Window::override () const [inline]
Returns non zero if FL_OVERRIDE flag is set, 0 otherwise.
Definition at line 195 of file Fl_Window.H.
References Fl_Widget::flags(), and Fl_Widget::OVERRIDE.
Referenced by Fl_X::make(), Fl_X::make_xid(), and Fl_X::sendxjunk().
void Fl_Window::resize (int X, int Y, int W, int H) [virtual]
Changes the size and position of the window. If shown() is true, these changes are communicated to the window server (which may refuse that size and cause a further resize). If shown() is false, the size and position are used when show() is called. See Fl_Group for the effect of resizing on the child widgets.
You can also call the Fl_Widget methods size(x,y) and position(w,h), which are inline wrappers for this virtual function.
A top-level window can not force, but merely suggest a position and size to the operating system. The window manager may not be willing or able to display a window at the desired position or with the given dimensions. It is up to the application developer to verify window parameters after the resize request.
resize a window
Reimplemented from Fl_Group.
Reimplemented in Fl_Double_Window, Fl_Gl_Window, Fl_Overlay_Window, and Overlay_Window.
Definition at line 2401 of file Fl_mac.cxx.
References Fl_Widget::FORCE_POSITION, H, Fl_Widget::h(), Fl_Widget::parent(), Fl_Widget::redraw(), Fl_Group::resizable(), Fl_Widget::set_flag(), shown(), size_range(), Fl_Widget::w(), Fl_Widget::x(), Fl_X::xid, and Fl_Widget::y().
Referenced by fl_handle(), fl_set_form_geometry(), fullscreen(), fullscreen_off(), Fl_TooltipBox::layout(), position_window(), Fl_Overlay_Window::resize(), and show().
void Fl_Window::set_menu_window () [inline]
Marks the window as a menu window.
This is intended for internal use, but it can also be used if you write your own menu handling. However, this is not recommended.
This flag is used for correct "parenting" of windows in communication with the windowing system. Modern X window managers can use different flags to distinguish menu and tooltip windows from normal windows.
This must be called before the window is shown and cannot be changed later.
Definition at line 230 of file Fl_Window.H.
References Fl_Widget::set_flag().
Referenced by menutitle::menutitle(), and menuwindow::menuwindow().
void Fl_Window::set_modal () [inline]
A "modal" window, when shown(), will prevent any events from being delivered to other windows in the same program, and will also remain on top of the other windows (if the X window manager supports the "transient for" property). Several modal windows may be shown at once, in which case only the last one shown gets events. You can see which window (if any) is modal by calling Fl::modal().
Definition at line 204 of file Fl_Window.H.
References Fl_Widget::set_flag().
Referenced by ColorMenu::ColorMenu(), Fl_Color_Chooser::fl_color_chooser(), Fl_File_Chooser::Fl_File_Chooser(), fl_show_form(), live_mode_cb(), make_class_panel(), make_code_panel(), make_codeblock_panel(), make_comment_panel(), make_declblock_panel(), make_function_panel(), make_print_panel(), make_project_window(), make_template_panel(), menutitle::menutitle(), and menuwindow::menuwindow().
void Fl_Window::set_non_modal () [inline]
A "non-modal" window (terminology borrowed from Microsoft Windows) acts like a modal() one in that it remains on top, but it has no effect on event delivery. There are three states for a window: modal, non-modal, and normal.
Definition at line 213 of file Fl_Window.H.
References Fl_Widget::set_flag().
Referenced by make_about_panel(), make_layout_window(), make_settings_window(), and make_widgetbin().
void Fl_Window::set_override () [inline]
Activates the flags NOBORDER|FL_OVERRIDE
Definition at line 193 of file Fl_Window.H.
References Fl_Widget::set_flag().
Referenced by Fl_TooltipBox::Fl_TooltipBox().
void Fl_Window::set_tooltip_window () [inline]
Marks the window as a tooltip window.
This is intended for internal use, but it can also be used if you write your own tooltip handling. However, this is not recommended.
This flag is used for correct "parenting" of windows in communication with the windowing system. Modern X window managers can use different flags to distinguish menu and tooltip windows from normal windows.
This must be called before the window is shown and cannot be changed later.
Note:
Since Fl_Tooltip_Window is derived from Fl_Menu_Window, this also clears the menu_window() state.
Definition at line 251 of file Fl_Window.H.
References Fl_Widget::clear_flag(), and Fl_Widget::set_flag().
Referenced by Fl_TooltipBox::Fl_TooltipBox().
void Fl_Window::show (int argc, char ** argv)
Puts the window on the screen and parses command-line arguments.
Usually (on X) this has the side effect of opening the display.
This form should be used for top-level windows, at least for the first (main) window. It allows standard arguments to be parsed from the command-line. You can use argc and argv from main(int argc, char **argv) for this call.
The first call also sets up some system-specific internal variables like the system colors.
Todo:
explain which system parameters are set up.
Parameters:
argc command-line argument count, usually from main()
argv command-line argument vector, usually from main()
See also:
virtual void Fl_Window::show()
Reimplemented in Fl_Double_Window, Fl_Gl_Window, Fl_Overlay_Window, and Fl_Single_Window.
Definition at line 298 of file Fl_arg.cxx.
References Fl::args(), buffer, Fl::dnd_text_ops(), Fl_Tooltip::enable(), Fl::first_window(), fl_display, fl_filename_name(), fl_xid(), Fl::get_system_colors(), Fl_Widget::h(), key, label(), Fl_Group::resizable(), resize(), Fl::scheme(), show(), Fl_Widget::size(), val, Fl_Widget::visible_focus(), Fl_Widget::w(), Fl_Widget::x(), xclass(), and Fl_Widget::y().
void Fl_Window::show () [virtual]
Puts the window on the screen. Usually (on X) this has the side effect of opening the display.
If the window is already shown then it is restored and raised to the top. This is really convenient because your program can call show() at any time, even if the window is already up. It also means that show() serves the purpose of raise() in other toolkits.
Fl_Window::show(int argc, char **argv) is used for top-level windows and allows standard arguments to be parsed from the command-line.
See also:
Fl_Window::show(int argc, char **argv)
make a window visible
Reimplemented from Fl_Widget.
Reimplemented in Fl_Double_Window, Fl_Gl_Window, Fl_Menu_Window, Fl_Overlay_Window, Fl_Single_Window, and Fl_TooltipBox.
Definition at line 2374 of file Fl_mac.cxx.
References Fl_Widget::align(), Fl_Tooltip::exit, FL_ALIGN_CENTER, FL_ALIGN_CLIP, FL_ALIGN_INSIDE, fl_capture, FL_NO_LABEL, FL_NORMAL_LABEL, Fl_Widget::image(), Fl_Widget::labeltype(), Fl_X::make(), Fl_Widget::parent(), Fl::scheme_bg_, shown(), and Fl_X::xid.
Referenced by Fl_Color_Chooser::fl_color_chooser(), fl_handle(), fl_pop_form(), fl_raise_form(), fl_show_form(), handle(), Fl::handle(), hide(), iconize(), live_mode_cb(), main(), Fl_Widget_Type::open(), Fl_Paged_Device::print_window_part(), ColorMenu::run(), Fl_Overlay_Window::show(), show(), Fl_Single_Window::show(), Fl_Gl_Window::show(), and toggle_widgetbin_cb().
int Fl_Window::shown () [inline]
Returns non-zero if show() has been called (but not hide()). You can tell if a window is iconified with (w->shown() && !w->visible()).
Definition at line 343 of file Fl_Window.H.
References i.
Referenced by border(), cursor(), do_shell_command(), Fl_Tooltip::enter_area(), Fl_Menu_Window::erase(), Fl::first_window(), Fl_Color_Chooser::fl_color_chooser(), Fl_Overlay_Window::flush(), handle(), Fl::handle(), hide(), iconize(), label(), new_cb(), Fl_Window_Type::open(), Fl_Menu_Item::pulldown(), Overlay_Window::read_image(), resize(), save_position(), save_template_cb(), Fl_Menu_Window::show(), show(), Fl_File_Chooser::shown(), and Fl_PostScript_Printer::start_job().
void Fl_Window::size_range (int a, int b, int c = 0, int d = 0, int e = 0, int f = 0, int g = 0) [inline]
Sets the allowable range the user can resize this window to. This only works for top-level windows.
minw and minh are the smallest the window can be. Either value must be greater than 0.
maxw and maxh are the largest the window can be. If either is equal to the minimum then you cannot resize in that direction. If either is zero then FLTK picks a maximum size in that direction such that the window will fill the screen.
dw and dh are size increments. The window will be constrained to widths of minw + N * dw, where N is any non-negative integer. If these are less or equal to 1 they are ignored (this is ignored on WIN32).
aspect is a flag that indicates that the window should preserve its aspect ratio. This only works if both the maximum and minimum have the same aspect ratio (ignored on WIN32 and by many X window managers).
If this function is not called, FLTK tries to figure out the range from the setting of resizable():
If resizable() is NULL (this is the default) then the window cannot be resized and the resize border and max-size control will not be displayed for the window.
If either dimension of resizable() is less than 100, then that is considered the minimum size. Otherwise the resizable() has a minimum size of 100.
If either dimension of resizable() is zero, then that is also the maximum size (so the window cannot resize in that direction).
It is undefined what happens if the current size does not fit in the constraints passed to size_range().
Definition at line 314 of file Fl_Window.H.
References b, dh, dw, and f.
Referenced by Fl_File_Chooser::Fl_File_Chooser(), Fl_Help_Dialog::Fl_Help_Dialog(), live_mode_cb(), Fl_X::make(), make_class_panel(), make_code_panel(), make_codeblock_panel(), make_comment_panel(), make_data_panel(), make_decl_panel(), make_declblock_panel(), make_sourceview(), make_widget_panel(), Fl_Window_Type::open(), resize(), resizeform(), and Fl_X::sendxjunk().
unsigned int Fl_Window::tooltip_window () const [inline]
Returns true if this window is a tooltip window.
Definition at line 254 of file Fl_Window.H.
References Fl_Widget::flags(), and Fl_Widget::TOOLTIP_WINDOW.
Referenced by Fl_X::make_xid().
int Fl_Window::x_root () const
Gets the x position of the window on the screen
Definition at line 92 of file Fl_Window.cxx.
References Fl_Widget::window(), Fl_Widget::x(), and x_root().
Referenced by menuwindow::is_inside(), and x_root().
void Fl_Window::xclass (const char * xc)
Sets the xclass for this window.
A string used to tell the system what type of window this is. Mostly this identifies the picture to draw in the icon. This only works if called before calling show().
Under X, this is turned into a XA_WM_CLASS pair by truncating at the first non-alphanumeric character and capitalizing the first character, and the second one if the first is 'x'. Thus "foo" turns into "foo, Foo", and "xprog.1" turns into "xprog, XProg".
Under Microsoft Windows, this string is used as the name of the WNDCLASS structure, though it is not clear if this can have any visible effect.
Since:
FLTK 1.3 the passed string is copied. You can use a local variable or free the string immediately after this call. Note that FLTK 1.1 stores the pointer without copying the string.
If the default xclass has not yet been set, this also sets the default xclass for all windows created subsequently.
See also:
Fl_Window::default_xclass(const char *)
Definition at line 252 of file Fl_Window.cxx.
References default_xclass().
const char * Fl_Window::xclass () const
Returns the xclass for this window, or a default.
See also:
Fl_Window::default_xclass(const char *)
Fl_Window::xclass(const char *)
Definition at line 271 of file Fl_Window.cxx.
References default_xclass().
Referenced by Fl::get_system_colors(), Fl_X::make_xid(), Fl::scheme(), and show().
int Fl_Window::y_root () const
Gets the y position of the window on the screen
Definition at line 98 of file Fl_Window.cxx.
References Fl_Widget::window(), Fl_Widget::y(), and y_root().
Referenced by menuwindow::is_inside(), and y_root().
Friends And Related Function Documentation
friend class Fl_X [friend]
Definition at line 62 of file Fl_Window.H.
Member Data Documentation
Fl_Window * Fl_Window::current_ [static, protected]
Stores the last window that was made current. See current() const
Reimplemented from Fl_Group.
Definition at line 85 of file Fl_Window.H.
Referenced by current(), Fl_Menu_Window::flush(), and make_current().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Window.H
fltk-1.3.0rc3/src/Fl.cxx
fltk-1.3.0rc3/src/Fl_arg.cxx
fltk-1.3.0rc3/src/fl_cursor.cxx
fltk-1.3.0rc3/src/Fl_mac.cxx
fltk-1.3.0rc3/src/Fl_win32.cxx
fltk-1.3.0rc3/src/Fl_Window.cxx
fltk-1.3.0rc3/src/Fl_Window_fullscreen.cxx
fltk-1.3.0rc3/src/Fl_Window_hotspot.cxx
fltk-1.3.0rc3/src/Fl_Window_iconize.cxx
fltk-1.3.0rc3/src/Fl_x.cxx