SfR Fresh Dox - fltk: Fl_Image Class Reference
Fl_Image Class Reference
#include <Fl_Image.H>
Public Member Functions
int w () const
int h () const
int d () const
int ld () const
int count () const
const char *const data () const
Fl_Image (int W, int H, int D)
virtual ~Fl_Image ()
virtual Fl_Image * copy (int W, int H)
Fl_Image * copy ()
virtual void color_average (Fl_Color c, float i)
void inactive ()
virtual void desaturate ()
virtual void label (Fl_Widget *w)
virtual void label (Fl_Menu_Item *m)
virtual void draw (int X, int Y, int W, int H, int cx=0, int cy=0)
void draw (int X, int Y)
virtual void uncache ()
Protected Member Functions
void w (int W)
void h (int H)
void d (int D)
void ld (int LD)
void data (const char *const *p, int c)
void draw_empty (int X, int Y)
Static Protected Member Functions
static void labeltype (const Fl_Label *lo, int lx, int ly, int lw, int lh, Fl_Align la)
static void measure (const Fl_Label *lo, int &lw, int &lh)
Detailed Description
Fl_Image is the base class used for caching and drawing all kinds of images in FLTK. This class keeps track of common image data such as the pixels, colormap, width, height, and depth. Virtual methods are used to provide type-specific image handling.
Since the Fl_Image class does not support image drawing by itself, calling the draw() method results in a box with an X in it being drawn instead.
Definition at line 51 of file Fl_Image.H.
Constructor & Destructor Documentation
Fl_Image::Fl_Image (int W, int H, int D) [inline]
The constructor creates an empty image with the specified width, height, and depth. The width and height are in pixels. The depth is 0 for bitmaps, 1 for pixmap (colormap) images, and 1 to 4 for color images.
Definition at line 142 of file Fl_Image.H.
References H.
Fl_Image::~Fl_Image () [virtual]
The destructor is a virtual method that frees all memory used by the image.
Definition at line 50 of file Fl_Image.cxx.
Member Function Documentation
void Fl_Image::color_average (Fl_Color c, float i) [virtual]
The color_average() method averages the colors in the image with the FLTK color value c. The i argument specifies the amount of the original image to combine with the color, so a value of 1.0 results in no color blend, and a value of 0.0 results in a constant image of the specified color. The original image data is not altered by this method.
Reimplemented in Fl_RGB_Image, Fl_Pixmap, Fl_Shared_Image, and Fl_Tiled_Image.
Definition at line 99 of file Fl_Image.cxx.
Referenced by Fl_Tiled_Image::color_average(), and Fl_Shared_Image::color_average().
Fl_Image * Fl_Image::copy (int W, int H) [virtual]
The copy() method creates a copy of the specified image. If the width and height are provided, the image is resized to the specified size. The image should be deleted (or in the case of Fl_Shared_Image, released) when you are done with it.
Reimplemented in Fl_Bitmap, Fl_RGB_Image, Fl_Pixmap, Fl_Shared_Image, and Fl_Tiled_Image.
Definition at line 86 of file Fl_Image.cxx.
References d().
Referenced by Fl_Tiled_Image::color_average(), Fl_Shared_Image::copy(), Fl_Tiled_Image::desaturate(), and Fl_Shared_Image::reload().
Fl_Image* Fl_Image::copy () [inline]
The copy() method creates a copy of the specified image. If the width and height are provided, the image is resized to the specified size. The image should be deleted (or in the case of Fl_Shared_Image, released) when you are done with it.
Reimplemented in Fl_Bitmap, Fl_RGB_Image, Fl_Pixmap, Fl_Shared_Image, and Fl_Tiled_Image.
Definition at line 152 of file Fl_Image.H.
References copy(), h, and w.
Referenced by copy().
int Fl_Image::count () const [inline]
The count() method returns the number of data values associated with the image. The value will be 0 for images with no associated data, 1 for bitmap and color images, and greater than 2 for pixmap images.
Definition at line 125 of file Fl_Image.H.
Referenced by Fl_File_Icon::load_image(), Fl_Shared_Image::update(), and Fluid_Image::write_static().
int Fl_Image::d () const [inline]
The first form of the d() method returns the current image depth. The return value will be 0 for bitmaps, 1 for pixmaps, and 1 to 4 for color images.
The second form is a protected method that sets the current image depth.
Definition at line 109 of file Fl_Image.H.
Referenced by Fl_RGB_Image::color_average(), Fl_RGB_Image::copy(), copy(), Fl_RGB_Image::desaturate(), Fl_BMP_Image::Fl_BMP_Image(), Fl_GIF_Image::Fl_GIF_Image(), Fl_JPEG_Image::Fl_JPEG_Image(), Fl_PNG_Image::Fl_PNG_Image(), Fl_PNM_Image::Fl_PNM_Image(), and Fl_Shared_Image::update().
void Fl_Image::d (int D) [inline, protected]
The first form of the d() method returns the current image depth. The return value will be 0 for bitmaps, 1 for pixmaps, and 1 to 4 for color images.
The second form is a protected method that sets the current image depth.
Definition at line 85 of file Fl_Image.H.
Referenced by Fl_PostScript_Graphics_Driver::draw(), Fl_Xlib_Graphics_Driver::draw(), Fl_File_Icon::load_image(), Fl_Shared_Image::update(), and Fluid_Image::write_static().
void Fl_Image::data (const char *const * p, int c) [inline, protected]
See const char * const *data()
Definition at line 89 of file Fl_Image.H.
Referenced by Fl_PostScript_Graphics_Driver::draw(), Fl_Xlib_Graphics_Driver::draw(), Fl_File_Icon::load_image(), Fl_Shared_Image::update(), and Fluid_Image::write_static().
const char* const Fl_Image::data () const [inline]
The first form of the data() method returns a pointer to the current image data array. Use the count() method to find the size of the data array.
The second form is a protected method that sets the current array pointer and count of pointers in the array.
Definition at line 134 of file Fl_Image.H.
Referenced by Fl_Pixmap::color_average(), Fl_Pixmap::copy(), Fl_Pixmap::desaturate(), Fl_Bitmap::Fl_Bitmap(), Fl_GIF_Image::Fl_GIF_Image(), Fl_RGB_Image::Fl_RGB_Image(), Fl_XPM_Image::Fl_XPM_Image(), Fl_Pixmap::measure(), and Fl_Shared_Image::update().
void Fl_Image::desaturate () [virtual]
The desaturate() method converts an image to grayscale. If the image contains an alpha channel (depth = 4), the alpha channel is preserved. This method does not alter the original image data.
Reimplemented in Fl_RGB_Image, Fl_Pixmap, Fl_Shared_Image, and Fl_Tiled_Image.
Definition at line 108 of file Fl_Image.cxx.
Referenced by Fl_Tiled_Image::desaturate(), and Fl_Shared_Image::desaturate().
void Fl_Image::draw (int X, int Y) [inline]
The draw() methods draw the image. This form specifies the upper-lefthand corner of the image
Reimplemented in Fl_Bitmap, Fl_RGB_Image, Fl_Pixmap, Fl_Shared_Image, and Fl_Tiled_Image.
Definition at line 175 of file Fl_Image.H.
References draw(), h, and w.
Referenced by draw().
void Fl_Image::draw (int X, int Y, int W, int H, int cx = 0, int cy = 0) [virtual]
The draw() methods draw the image. This form specifies a bounding box for the image, with the origin (upper-lefthand corner) of the image offset by the cx and cy arguments.
Reimplemented in Fl_Bitmap, Fl_RGB_Image, Fl_Pixmap, Fl_Shared_Image, and Fl_Tiled_Image.
Definition at line 61 of file Fl_Image.cxx.
References draw_empty().
Referenced by Fl_Tree_Item::draw(), Fl_Tiled_Image::draw(), Fl_Shared_Image::draw(), fl_draw(), Fl_Browser::item_draw(), and labeltype().
void Fl_Image::draw_empty (int X, int Y) [protected]
The protected method draw_empty() draws a box with an X in it. It can be used to draw any image that lacks image data.
Definition at line 70 of file Fl_Image.cxx.
References fl_color(), FL_FOREGROUND_COLOR, fl_line(), fl_rect(), h(), and w().
Referenced by draw(), and Fl_Xlib_Graphics_Driver::draw().
void Fl_Image::h (int H) [inline, protected]
The first form of the h() method returns the current image height in pixels.
The second form is a protected method that sets the current image height.
Definition at line 76 of file Fl_Image.H.
References H.
Referenced by Fl_PostScript_Graphics_Driver::draw(), Fl_Tree_Item::draw(), Fl_Tiled_Image::draw(), Fl_Xlib_Graphics_Driver::draw(), Fl_Shared_Image::find(), Fluid_Image::find(), fl_draw(), fl_normal_measure(), Fl_Shared_Image::get(), Fl_Browser::icon(), Fl_Browser::item_height(), labeltype(), Fl_File_Icon::load_image(), measure(), Fl_Shared_Image::reload(), Fl_File_Chooser::rescan_keep_filename(), Fl_Shared_Image::update(), and Fluid_Image::write_static().
int Fl_Image::h () const [inline]
See void Fl_Image::h(int)
Definition at line 100 of file Fl_Image.H.
Referenced by Fl_RGB_Image::color_average(), Fl_Tiled_Image::copy(), Fl_Shared_Image::copy(), Fl_Pixmap::copy(), Fl_RGB_Image::copy(), Fl_Bitmap::copy(), Fl_RGB_Image::desaturate(), Fl_Tiled_Image::draw(), Fl_Shared_Image::draw(), Fl_Pixmap::draw(), Fl_RGB_Image::draw(), Fl_Bitmap::draw(), draw_empty(), Fl_BMP_Image::Fl_BMP_Image(), Fl_GIF_Image::Fl_GIF_Image(), Fl_JPEG_Image::Fl_JPEG_Image(), Fl_PNG_Image::Fl_PNG_Image(), Fl_PNM_Image::Fl_PNM_Image(), Fl_Tiled_Image::Fl_Tiled_Image(), Fl_XBM_Image::Fl_XBM_Image(), Fl_Pixmap::measure(), Fl_Shared_Image::reload(), and Fl_Shared_Image::update().
void Fl_Image::inactive () [inline]
The inactive() method calls color_average(FL_BACKGROUND_COLOR, 0.33f) to produce an image that appears grayed out. This method does not alter the original image data.
Definition at line 160 of file Fl_Image.H.
References f, and FL_GRAY.
void Fl_Image::label (Fl_Menu_Item * m) [virtual]
The label() methods are an obsolete way to set the image attribute of a widget or menu item. Use the image() or deimage() methods of the Fl_Widget and Fl_Menu_Item classes instead.
Reimplemented in Fl_Bitmap, Fl_RGB_Image, and Fl_Pixmap.
Definition at line 129 of file Fl_Image.cxx.
References _FL_IMAGE_LABEL, Fl_Menu_Item::label(), labeltype(), measure(), and Fl::set_labeltype().
void Fl_Image::label (Fl_Widget * widget) [virtual]
The label() methods are an obsolete way to set the image attribute of a widget or menu item. Use the image() or deimage() methods of the Fl_Widget and Fl_Menu_Item classes instead.
Reimplemented in Fl_Bitmap, Fl_RGB_Image, and Fl_Pixmap.
Definition at line 118 of file Fl_Image.cxx.
References Fl_Widget::image().
Referenced by Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), and Fl_Menu_Item::image().
void Fl_Image::labeltype (const Fl_Label * lo, int lx, int ly, int lw, int lh, Fl_Align la) [static, protected]
Definition at line 135 of file Fl_Image.cxx.
References Fl_Label::color, draw(), FL_ALIGN_BOTTOM, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_ALIGN_TOP, fl_color(), h(), Fl_Label::value, and w().
Referenced by Fl_Pixmap::label(), Fl_RGB_Image::label(), label(), and Fl_Bitmap::label().
void Fl_Image::ld (int LD) [inline, protected]
See int ld()
Definition at line 87 of file Fl_Image.H.
Referenced by Fl_PostScript_Graphics_Driver::draw(), Fl_Xlib_Graphics_Driver::draw(), Fl_File_Icon::load_image(), and Fluid_Image::write_static().
int Fl_Image::ld () const [inline]
The first form of the ld() method returns the current line data size in bytes. Line data is extra data that is included after each line of color image data and is normally not present.
The second form is a protected method that sets the current line data size in bytes.
Definition at line 118 of file Fl_Image.H.
Referenced by Fl_RGB_Image::color_average(), Fl_RGB_Image::copy(), Fl_RGB_Image::desaturate(), and Fl_RGB_Image::Fl_RGB_Image().
void Fl_Image::measure (const Fl_Label * lo, int & lw, int & lh) [static, protected]
Definition at line 160 of file Fl_Image.cxx.
References h(), Fl_Label::value, and w().
Referenced by Fl_Pixmap::Fl_Pixmap(), Fl_Pixmap::label(), Fl_RGB_Image::label(), label(), and Fl_Bitmap::label().
void Fl_Image::uncache () [virtual]
If the image has been cached for display, delete the cache data. This allows you to change the data used for the image and then redraw it without recreating an image object.
Reimplemented in Fl_Bitmap, Fl_RGB_Image, Fl_Pixmap, and Fl_Shared_Image.
Definition at line 58 of file Fl_Image.cxx.
Referenced by Fl_Shared_Image::uncache().
int Fl_Image::w () const [inline]
See void Fl_Image::w(int)
Definition at line 98 of file Fl_Image.H.
Referenced by Fl_RGB_Image::color_average(), Fl_Tiled_Image::copy(), Fl_Shared_Image::copy(), Fl_Pixmap::copy(), Fl_RGB_Image::copy(), Fl_Bitmap::copy(), Fl_RGB_Image::desaturate(), Fl_Tiled_Image::draw(), Fl_Shared_Image::draw(), Fl_Pixmap::draw(), Fl_RGB_Image::draw(), Fl_Bitmap::draw(), draw_empty(), Fl_BMP_Image::Fl_BMP_Image(), Fl_GIF_Image::Fl_GIF_Image(), Fl_JPEG_Image::Fl_JPEG_Image(), Fl_PNG_Image::Fl_PNG_Image(), Fl_PNM_Image::Fl_PNM_Image(), Fl_Tiled_Image::Fl_Tiled_Image(), Fl_XBM_Image::Fl_XBM_Image(), Fl_Pixmap::measure(), Fl_Shared_Image::reload(), and Fl_Shared_Image::update().
void Fl_Image::w (int W) [inline, protected]
The first form of the w() method returns the current image width in pixels.
The second form is a protected method that sets the current image width.
Definition at line 68 of file Fl_Image.H.
Referenced by Fl_PostScript_Graphics_Driver::draw(), Fl_Tree_Item::draw(), Fl_Tiled_Image::draw(), Fl_Xlib_Graphics_Driver::draw(), Fl_Shared_Image::find(), Fluid_Image::find(), fl_draw(), fl_normal_measure(), Fl_Shared_Image::get(), Fl_Browser::item_draw(), Fl_Browser::item_width(), labeltype(), Fl_File_Icon::load_image(), measure(), Fl_Shared_Image::reload(), Fl_File_Chooser::rescan_keep_filename(), Fl_Shared_Image::update(), and Fluid_Image::write_static().
The documentation for this class was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Image.H
fltk-1.3.0rc3/src/Fl_Image.cxx