SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/code.cxx File Reference
code.cxx File Reference
#include <stdio.h>
#include <stdlib.h>
#include "../src/flstring.h"
#include <stdarg.h>
#include <FL/Fl.H>
#include "Fl_Type.h"
#include "alignment_panel.h"
#include <FL/filename.H>
Classes
struct id
struct included
Functions
int is_id (char c)
const char * unique_id (void *o, const char *type, const char *name, const char *label)
const char * indent ()
int write_declare (const char *format,...)
void write_cstring (const char *w, int length)
void write_cstring (const char *w)
void write_cdata (const char *s, int length)
void write_c (const char *format,...)
void write_h (const char *format,...)
int write_code (const char *s, const char *t)
int write_strings (const char *sfile)
Variables
char i18n_program []
int i18n_type
const char * i18n_include
const char * i18n_function
const char * i18n_file
const char * i18n_set
int indentation
int varused_test
int varused
int write_number
int write_sourceview
Fl_Widget_Class_Type * current_widget_class
const char * header_file_name
Fl_Class_Type * current_class
Function Documentation
const char* indent ()
Definition at line 108 of file code.cxx.
References i, and indentation.
Referenced by main(), Fl_Text_Display::overstrike(), fl_margins::push(), Fl_Widget_Type::write_block_close(), Fluid_Image::write_code(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_CodeBlock_Type::write_code1(), Fl_Code_Type::write_code1(), Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), Fl_Menu_Type::write_code2(), Fl_Group_Type::write_code2(), Fl_CodeBlock_Type::write_code2(), Fl_Widget_Type::write_color(), Fl_Widget_Type::write_extra_code(), and Fl_Widget_Type::write_widget_code().
int is_id (char c)
Definition at line 49 of file code.cxx.
Referenced by Fl_Class_Type::open(), unique_id(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), and write_word().
const char* unique_id (void * o, const char * type, const char * name, const char * label)
Definition at line 72 of file code.cxx.
References buffer, i, is_id(), and name.
Referenced by Fl_Type::callback_name(), Fl_Menu_Item_Type::menu_name(), Fluid_Image::write_code(), Fl_Menu_Type::write_code2(), and Fluid_Image::write_static().
void write_c (const char * format, ...)
Definition at line 265 of file code.cxx.
References varused, and varused_test.
Referenced by Fl_Widget_Type::write_block_close(), Fluid_Image::write_code(), write_code(), Fl_Widget_Class_Type::write_code1(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Comment_Type::write_code1(), Fl_DeclBlock_Type::write_code1(), Fl_Data_Type::write_code1(), Fl_Decl_Type::write_code1(), Fl_CodeBlock_Type::write_code1(), Fl_Code_Type::write_code1(), Fl_Function_Type::write_code1(), Fl_Type::write_code1(), Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), Fl_Menu_Type::write_code2(), Fl_Group_Type::write_code2(), Fl_DeclBlock_Type::write_code2(), Fl_CodeBlock_Type::write_code2(), Fl_Function_Type::write_code2(), Fl_Widget_Type::write_color(), Fl_Type::write_comment_c(), Fl_Widget_Type::write_extra_code(), Fl_Menu_Item_Type::write_item(), Fluid_Image::write_static(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), and Fl_Widget_Type::write_widget_code().
void write_cdata (const char * s, int length)
Definition at line 233 of file code.cxx.
References length, varused, varused_test, w, and write_sourceview.
Referenced by Fl_Data_Type::write_code1(), and Fluid_Image::write_static().
int write_code (const char * s, const char * t)
Definition at line 346 of file code.cxx.
References b, Fl_Type::code_position, Fl_Type::code_position_end, f, Fl_Type::first, fl_filename_name(), fl_fopen(), FL_VERSION, header_file_name, Fl_Type::header_position, Fl_Type::header_position_end, i18n_file, i18n_include, i18n_program, i18n_type, include_H_from_C, indentation, int, Fl_Type::is_comment(), Fl_Type::last, Fl_Type::level, Fl_Type::next, NULL, write_c(), Fl_Type::write_code1(), write_declare(), write_number, write_sourceview, x, and y.
Referenced by update_sourceview_cb(), and write_cb().
void write_cstring (const char * w, int length)
Definition at line 163 of file code.cxx.
References length, varused, varused_test, and w.
Referenced by Fl_Widget_Class_Type::write_code1(), Fl_Widget_Type::write_code1(), Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), write_cstring(), Fl_Menu_Item_Type::write_item(), Fluid_Image::write_static(), and Fl_Widget_Type::write_widget_code().
void write_cstring (const char * w)
Definition at line 230 of file code.cxx.
References write_cstring().
int write_declare (const char * format, ...)
Definition at line 136 of file code.cxx.
References buf, i, and vsnprintf.
Referenced by write_code(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
void write_h (const char * format, ...)
Definition at line 276 of file code.cxx.
References varused_test.
Referenced by Fl_Widget_Class_Type::write_code1(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Class_Type::write_code1(), Fl_Comment_Type::write_code1(), Fl_DeclBlock_Type::write_code1(), Fl_Data_Type::write_code1(), Fl_Decl_Type::write_code1(), Fl_Function_Type::write_code1(), Fl_Type::write_code1(), Fl_Class_Type::write_code2(), Fl_DeclBlock_Type::write_code2(), Fl_Type::write_comment_h(), write_public(), and Fl_Widget_Type::write_static().
int write_strings (const char * sfile)
Definition at line 470 of file code.cxx.
References Fl_Type::first, fl_fopen(), FL_VERSION, fp, i, i18n_set, i18n_type, Fl_Type::is_widget(), Fl_Type::label(), Fl_Type::next, Fl_Widget_Type::tooltip(), and w.
Referenced by write_strings_cb().
Variable Documentation
Fl_Class_Type* current_class
Definition at line 1423 of file Fl_Function_Type.cxx.
Referenced by Fl_Class_Type::write_code1().
Fl_Widget_Class_Type* current_widget_class
Definition at line 1444 of file Fl_Window_Type.cxx.
const char* header_file_name
Definition at line 647 of file fluid.cxx.
Referenced by update_sourceview_cb(), and write_code().
const char* i18n_file
Definition at line 652 of file fluid.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), show_project_cb(), write_code(), Fl_Widget_Type::write_code1(), and Fl_Widget_Type::write_widget_code().
const char* i18n_function
Definition at line 651 of file fluid.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), show_project_cb(), Fl_Widget_Type::write_code1(), and Fl_Widget_Type::write_widget_code().
const char* i18n_include
Definition at line 650 of file fluid.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), show_project_cb(), and write_code().
char i18n_program[]
Definition at line 654 of file fluid.cxx.
Referenced by write_code().
const char* i18n_set
Definition at line 653 of file fluid.cxx.
Referenced by i18n_int_cb(), i18n_type_cb(), show_project_cb(), Fl_Widget_Type::write_code1(), write_strings(), and Fl_Widget_Type::write_widget_code().
int i18n_type
Definition at line 649 of file fluid.cxx.
Referenced by i18n_type_cb(), show_project_cb(), write_code(), Fl_Widget_Type::write_code1(), write_strings(), and Fl_Widget_Type::write_widget_code().
int indentation
Definition at line 107 of file code.cxx.
Referenced by indent(), Fl_Widget_Type::write_block_close(), write_code(), Fl_Widget_Type::write_code1(), Fl_CodeBlock_Type::write_code1(), Fl_Function_Type::write_code1(), Fl_CodeBlock_Type::write_code2(), and Fl_Function_Type::write_code2().
int varused
Definition at line 160 of file code.cxx.
Referenced by write_c(), write_cdata(), and write_cstring().
int varused_test
Definition at line 159 of file code.cxx.
Referenced by write_c(), write_cdata(), write_cstring(), and write_h().
int write_number
Definition at line 285 of file code.cxx.
Referenced by write_code(), Fluid_Image::write_static(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
int write_sourceview
Definition at line 286 of file code.cxx.
Referenced by update_sourceview_cb(), write_cdata(), write_code(), and Fl_Data_Type::write_code1().