SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/xutf8/utils/convert_map.c File Reference
convert_map.c File Reference
#include <wchar.h>
#include <stdio.h>
Functions
int JIS0208 (unsigned char *ptr)
int JIS0201 (unsigned char *ptr)
int ADOBE (unsigned char *ptr)
int JIS0212 (unsigned char *ptr)
int main (int argc, char **argv)
Variables
char buffer [1000000]
Function Documentation
int ADOBE (unsigned char * ptr)
Definition at line 77 of file convert_map.c.
References i, int, and NULL.
Referenced by main().
int JIS0201 (unsigned char * ptr)
Definition at line 56 of file convert_map.c.
References i, int, and NULL.
Referenced by main().
int JIS0208 (unsigned char * ptr)
Definition at line 36 of file convert_map.c.
References i, int, and NULL.
Referenced by main().
int JIS0212 (unsigned char * ptr)
Definition at line 99 of file convert_map.c.
References i, int, and NULL.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 125 of file convert_map.c.
References ADOBE(), buf, buffer, i, JIS0201(), JIS0208(), JIS0212(), and ptr.
Variable Documentation
char buffer[1000000]
Definition at line 34 of file convert_map.c.