SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/factory.cxx File Reference
factory.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Menu_Item.H>
#include <FL/Fl_Pixmap.H>
#include <FL/Fl_Tree.H>
#include <stdio.h>
#include "../src/flstring.h"
#include "undo.h"
#include "Fl_Widget_Type.h"
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Repeat_Button.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Check_Browser.H>
#include <FL/Fl_File_Browser.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_File_Input.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Clock.H>
#include <FL/Fl_Help_View.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Adjuster.H>
#include <FL/Fl_Dial.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Scrollbar.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Multi_Label.H>
#include <stdlib.h>
Classes
class Fl_Box_Type
class Fl_Button_Type
class Fl_Return_Button_Type
class Fl_Repeat_Button_Type
class Fl_Light_Button_Type
class Fl_Check_Button_Type
class Fl_Round_Button_Type
class Fl_Browser_Type
class Fl_Check_Browser_Type
class Fl_Tree_Type
class Fl_File_Browser_Type
class Fl_Counter_Type
class Fl_Spinner_Type
class Fl_Input_Type
class Fl_File_Input_Type
class Fl_Text_Display_Type
class Fl_Text_Editor_Type
class Fl_Clock_Type
class Fl_Help_View_Type
class Fl_Progress_Type
class Fl_Adjuster_Type
class Fl_Dial_Type
class Fl_Roller_Type
class Fl_Slider_Type
class Fl_Scrollbar_Type
class Fl_Output_Type
class Fl_Value_Input_Type
class Fl_Value_Output_Type
class Fl_Value_Slider_Type
struct symbol
Functions
void select (Fl_Type *, int)
void select_only (Fl_Type *)
void fill_in_New_Menu ()
Fl_Type * Fl_Type_make (const char *tn)
int lookup_symbol (const char *name, int &v, int numberok)
Variables
Fl_Pixmap * pixmap []
int compile_only
class Fl_Function_Type Fl_Function_type
class Fl_Code_Type Fl_Code_type
class Fl_CodeBlock_Type Fl_CodeBlock_type
class Fl_Data_Type Fl_Data_type
class Fl_Decl_Type Fl_Decl_type
class Fl_DeclBlock_Type Fl_DeclBlock_type
class Fl_Comment_Type Fl_Comment_type
class Fl_Class_Type Fl_Class_type
class Fl_Window_Type Fl_Window_type
class Fl_Widget_Class_Type Fl_Widget_Class_type
class Fl_Group_Type Fl_Group_type
class Fl_Pack_Type Fl_Pack_type
class Fl_Tabs_Type Fl_Tabs_type
class Fl_Scroll_Type Fl_Scroll_type
class Fl_Table_Type Fl_Table_type
class Fl_Tile_Type Fl_Tile_type
class Fl_Input_Choice_Type Fl_Input_Choice_type
class Fl_Choice_Type Fl_Choice_type
class Fl_Menu_Bar_Type Fl_Menu_Bar_type
class Fl_Menu_Button_Type Fl_Menu_Button_type
class Fl_Menu_Item_Type Fl_Menu_Item_type
class Fl_Submenu_Type Fl_Submenu_type
class Fl_Wizard_Type Fl_Wizard_type
Fl_Menu_Item New_Menu []
int reading_file
Function Documentation
void fill_in_New_Menu ()
Definition at line 1104 of file factory.cxx.
References i, Fl_Menu_Item::label(), m, New_Menu, Fl_Type::pixmapID(), Fl_Menu_Item::text, Fl_Type::type_name(), and Fl_Menu_Item::user_data().
Referenced by make_main_window().
Fl_Type* Fl_Type_make (const char * tn)
Definition at line 1123 of file factory.cxx.
References Fl_Type::alt_type_name(), i, m, Fl_Type::make(), New_Menu, Fl_Type::type_name(), and Fl_Menu_Item::user_data().
Referenced by read_fdesign(), and type_make_cb().
int lookup_symbol (const char * name, int & v, int numberok)
Definition at line 1268 of file factory.cxx.
References i, int, and symbol::value.
Referenced by Fl_Widget_Type::read_fdesign().
void select (Fl_Type * , int)
Definition at line 204 of file Fl_Type.cxx.
Referenced by DataReady::CheckData(), DataReady::DataReadyThread(), fl_ready(), fl_scandir(), fl_wait(), Fl_Window_Type::handle(), Fl_Text_Buffer::loadfile(), Fl_Type::read_property(), Fl_Tree::select(), Fl_Tree_Item::select_all(), and Fl_Tree_Item::select_toggle().
void select_only (Fl_Type *)
Definition at line 209 of file Fl_Type.cxx.
Referenced by cut_cb(), delete_cb(), and type_make_cb().
Variable Documentation
int compile_only
Definition at line 643 of file fluid.cxx.
Referenced by Fl_Data_Type::write_code1().
class Fl_Choice_Type Fl_Choice_type
Definition at line 527 of file Fl_Menu_Type.cxx.
class Fl_Class_Type Fl_Class_type
Definition at line 1421 of file Fl_Function_Type.cxx.
class Fl_Code_Type Fl_Code_type
Definition at line 469 of file Fl_Function_Type.cxx.
class Fl_CodeBlock_Type Fl_CodeBlock_type
Definition at line 546 of file Fl_Function_Type.cxx.
class Fl_Comment_Type Fl_Comment_type
Definition at line 1226 of file Fl_Function_Type.cxx.
class Fl_Data_Type Fl_Data_type
Definition at line 871 of file Fl_Function_Type.cxx.
class Fl_Decl_Type Fl_Decl_type
Definition at line 673 of file Fl_Function_Type.cxx.
class Fl_DeclBlock_Type Fl_DeclBlock_type
Definition at line 1018 of file Fl_Function_Type.cxx.
class Fl_Function_Type Fl_Function_type
Definition at line 244 of file Fl_Function_Type.cxx.
class Fl_Group_Type Fl_Group_type
Definition at line 46 of file Fl_Group_Type.cxx.
class Fl_Input_Choice_Type Fl_Input_Choice_type
Definition at line 529 of file Fl_Menu_Type.cxx.
class Fl_Menu_Bar_Type Fl_Menu_Bar_type
Definition at line 561 of file Fl_Menu_Type.cxx.
class Fl_Menu_Button_Type Fl_Menu_Button_type
Definition at line 521 of file Fl_Menu_Type.cxx.
class Fl_Menu_Item_Type Fl_Menu_Item_type
Definition at line 142 of file Fl_Menu_Type.cxx.
class Fl_Pack_Type Fl_Pack_type
Definition at line 146 of file Fl_Group_Type.cxx.
class Fl_Scroll_Type Fl_Scroll_type
Definition at line 428 of file Fl_Group_Type.cxx.
class Fl_Submenu_Type Fl_Submenu_type
Definition at line 143 of file Fl_Menu_Type.cxx.
class Fl_Table_Type Fl_Table_type
Definition at line 226 of file Fl_Group_Type.cxx.
class Fl_Tabs_Type Fl_Tabs_type
Definition at line 243 of file Fl_Group_Type.cxx.
class Fl_Tile_Type Fl_Tile_type
Definition at line 443 of file Fl_Group_Type.cxx.
class Fl_Widget_Class_Type Fl_Widget_Class_type
Definition at line 1443 of file Fl_Window_Type.cxx.
class Fl_Window_Type Fl_Window_type
Definition at line 512 of file Fl_Window_Type.cxx.
class Fl_Wizard_Type Fl_Wizard_type
Definition at line 274 of file Fl_Group_Type.cxx.
Fl_Menu_Item New_Menu[]
Definition at line 1011 of file factory.cxx.
Referenced by fill_in_New_Menu(), and Fl_Type_make().
Fl_Pixmap* pixmap[]
Definition at line 163 of file Fl_Type.cxx.
int reading_file
Definition at line 1122 of file factory.cxx.
Referenced by Fl_Widget_Type::make().