SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/file.cxx File Reference
file.cxx File Reference
#include <stdio.h>
#include <stdlib.h>
#include "../src/flstring.h"
#include <stdarg.h>
#include "alignment_panel.h"
#include <FL/fl_message.H>
#include <FL/Fl.H>
#include "Fl_Widget_Type.h"
#include <FL/Fl_Group.H>
Functions
int open_write (const char *s)
int close_write ()
int is_id (char)
void write_word (const char *w)
void write_string (const char *format,...)
void write_indent (int n)
void write_open (int)
void write_close (int n)
int open_read (const char *s)
int close_read ()
void read_error (const char *format,...)
const char * read_word (int wantbrace)
int write_file (const char *filename, int selected_only)
void read_fdesign ()
Fl_Type * Fl_Type_make (const char *tn)
void deselect ()
int read_file (const char *filename, int merge)
int read_fdesign_line (const char *&name, const char *&value)
Variables
int i18n_type
const char * i18n_include
const char * i18n_function
const char * i18n_file
const char * i18n_set
int header_file_set
int code_file_set
const char * header_file_name
const char * code_file_name
double read_version
int fdesign_flip
int fdesign_magic
Function Documentation
int close_read ()
Definition at line 145 of file file.cxx.
References x.
Referenced by read_file().
int close_write ()
Definition at line 52 of file file.cxx.
References x.
Referenced by write_file().
void deselect ()
Definition at line 213 of file Fl_Type.cxx.
Referenced by Fl_Tree::deselect(), Fl_Tree_Item::deselect_all(), Fl_Window_Type::handle(), read_file(), and Fl_Tree_Item::select_toggle().
Fl_Type* Fl_Type_make (const char * tn)
Definition at line 1123 of file factory.cxx.
int is_id (char)
Definition at line 49 of file code.cxx.
int open_read (const char * s)
Definition at line 135 of file file.cxx.
References f, and fl_fopen().
Referenced by read_file().
int open_write (const char * s)
Definition at line 44 of file file.cxx.
References f, and fl_fopen().
Referenced by write_file().
void read_error (const char * format, ...)
Definition at line 156 of file file.cxx.
References fl_message(), and vsnprintf.
Referenced by Fluid_Image::find(), Fl_Widget_Type::read_property(), Fl_Type::read_property(), and read_word().
void read_fdesign ()
Definition at line 593 of file file.cxx.
References Fl_Group::begin(), Fl_Group::current(), Fl_Type::current, Fl_Type_make(), Fl_Group::forms_end(), i, Fl_Type::label(), name, Fl_Type::name(), Fl_Widget_Type::o, Fl_Widget_Type::read_fdesign(), read_fdesign_line(), read_word(), and value.
int read_fdesign_line (const char *& name, const char *& value)
Definition at line 520 of file file.cxx.
References length, and x.
Referenced by read_fdesign().
int read_file (const char * filename, int merge)
Definition at line 501 of file file.cxx.
References Fl_Type::add_child(), close_read(), Fl_Type::current, delete_all(), deselect(), Fl_Type::first, Fl_Type::is_menu_button(), Fl_Type::next, open_read(), Fl_Type::selected, and selection_changed().
Referenced by duplicate_cb(), main(), new_cb(), open_cb(), open_history_cb(), paste_cb(), redo_cb(), revert_cb(), and undo_cb().
const char* read_word (int wantbrace)
Definition at line 235 of file file.cxx.
References length, read_error(), and x.
Referenced by Fl_BMP_Image::Fl_BMP_Image(), read_fdesign(), Fl_Window_Type::read_property(), Fl_Widget_Type::read_property(), Fl_Type::read_property(), Fl_Class_Type::read_property(), Fl_DeclBlock_Type::read_property(), Fl_Data_Type::read_property(), Fl_CodeBlock_Type::read_property(), and Fl_Function_Type::read_property().
void write_close (int n)
Definition at line 122 of file file.cxx.
References write_indent().
Referenced by Fl_Type::write().
int write_file (const char * filename, int selected_only)
Definition at line 320 of file file.cxx.
References close_write(), Fl_Type::first, FL_VERSION, include_H_from_C, open_write(), use_FL_COMMAND, write_string(), and write_word().
Referenced by copy_cb(), cut_cb(), duplicate_cb(), save_cb(), save_template_cb(), undo_cb(), and undo_checkpoint().
void write_indent (int n)
Definition at line 108 of file file.cxx.
Referenced by Fl_Type::write(), write_close(), Fl_Widget_Type::write_properties(), and Fl_Type::write_properties().
void write_open (int)
Definition at line 115 of file file.cxx.
Referenced by Fl_Type::write().
void write_string (const char * format, ...)
Definition at line 98 of file file.cxx.
Referenced by write_file(), Fl_Widget_Class_Type::write_properties(), Fl_Window_Type::write_properties(), Fl_Widget_Type::write_properties(), Fl_Class_Type::write_properties(), Fl_Comment_Type::write_properties(), Fl_DeclBlock_Type::write_properties(), Fl_Data_Type::write_properties(), Fl_Decl_Type::write_properties(), Fl_CodeBlock_Type::write_properties(), and Fl_Function_Type::write_properties().
void write_word (const char * w)
Definition at line 65 of file file.cxx.
References is_id(), and w.
Referenced by Fl_Type::write(), write_file(), Fl_Window_Type::write_properties(), Fl_Widget_Type::write_properties(), Fl_Type::write_properties(), Fl_Class_Type::write_properties(), Fl_DeclBlock_Type::write_properties(), Fl_Data_Type::write_properties(), Fl_CodeBlock_Type::write_properties(), and Fl_Function_Type::write_properties().
Variable Documentation
const char* code_file_name
Definition at line 648 of file fluid.cxx.
Referenced by update_sourceview_cb().
int code_file_set
Definition at line 646 of file fluid.cxx.
int fdesign_flip
Definition at line 558 of file file.cxx.
int fdesign_magic
Definition at line 559 of file file.cxx.
const char* header_file_name
Definition at line 647 of file fluid.cxx.
int header_file_set
Definition at line 645 of file fluid.cxx.
const char* i18n_file
Definition at line 652 of file fluid.cxx.
const char* i18n_function
Definition at line 651 of file fluid.cxx.
const char* i18n_include
Definition at line 650 of file fluid.cxx.
const char* i18n_set
Definition at line 653 of file fluid.cxx.
int i18n_type
Definition at line 649 of file fluid.cxx.
double read_version
Definition at line 363 of file file.cxx.