SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/filename_list.cxx File Reference
filename_list.cxx File Reference
#include <FL/filename.H>
#include <FL/fl_utf8.h>
#include "flstring.h"
#include <stdlib.h>
Functions
int fl_scandir (const char *dir, dirent ***namelist, int(*select)(dirent *), int(*compar)(dirent **, dirent **))
int fl_alphasort (struct dirent **a, struct dirent **b)
int fl_casealphasort (struct dirent **a, struct dirent **b)
int fl_filename_list (const char *d, dirent ***list, Fl_File_Sort_F *sort)
void fl_filename_free_list (struct dirent ***list, int n)
Free the list of filenames that is generated by fl_filename_list().
Function Documentation
void fl_filename_free_list (struct dirent *** list, int n)
Free the list of filenames that is generated by fl_filename_list().
Free everything that was allocated by a previous call to fl_filename_list(). Use the return values as parameters for this function.
Parameters:
[in,out] list table containing the resulting directory listing
[in] n number of entries in the list
Definition at line 190 of file filename_list.cxx.
References i.
int fl_filename_list (const char * d, dirent *** list, Fl_File_Sort_F * sort)
Portable and const-correct wrapper for the scandir() function. For each file in that directory a "dirent" structure is created. The only portable thing about a dirent is that dirent.d_name is the nul-terminated file name. An pointers array to these dirent's is created and a pointer to the array is returned in *list. The number of entries is given as a return value. If there is an error reading the directory a number less than zero is returned, and errno has the reason; errno does not work under WIN32.
Include:
   #include <FL/filename.H>
Parameters:
[in] d the name of the directory to list. It does not matter if it has a trailing slash.
[out] list table containing the resulting directory listing
[in] sort sorting functor:
fl_alphasort: The files are sorted in ascending alphabetical order; upper and lowercase letters are compared according to their ASCII ordering uppercase before lowercase.
fl_casealphasort: The files are sorted in ascending alphabetical order; upper and lowercase letters are compared equally case is not significant.
fl_casenumericsort: The files are sorted in ascending "alphanumeric" order, where an attempt is made to put unpadded numbers in consecutive order; upper and lowercase letters are compared equally case is not significant.
fl_numericsort: The files are sorted in ascending "alphanumeric" order, where an attempt is made to put unpadded numbers in consecutive order; upper and lowercase letters are compared according to their ASCII ordering - uppercase before lowercase.
Returns:
the number of entries if no error, a negative value otherwise.
Definition at line 82 of file filename_list.cxx.
References dirent, fl_filename_isdir(), FL_PATH_MAX, fl_scandir(), fl_utf8from_mb(), fl_utf8to_mb(), i, name, and NULL.
Referenced by Fl_File_Browser::load(), Fl_Plugin_Manager::loadAll(), and template_load().
int fl_scandir (const char * dir, dirent *** namelist, int(*)(dirent *) select, int(*)(dirent **, dirent **) compar)
Referenced by fl_filename_list().