SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/Fl.cxx File Reference
Fl.cxx File Reference
#include <config.h>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Tooltip.H>
#include <FL/x.H>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include "flstring.h"
#include <sys/time.h>
#include <FL/fl_draw.H>
Classes
struct Timeout
struct Check
struct handler_link
Defines
#define FOREVER 1e20
Functions
int fl_ready ()
int fl_wait (double time)
Fl_Window * fl_find (Window xid)
void fl_fix_focus ()
void fl_throw_focus (Fl_Widget *o)
Variables
Fl_Window * fl_xfocus
Fl_Window * fl_xmousewin
static Timeout * free_timeout
static int free_timeout_count
static Check * next_check
static Check * free_check
int(* fl_local_grab)(int)
Fl_Widget * fl_oldfocus
Fl_Widget * fl_selection_requestor
static int alloc_dwidgets = 0
Define Documentation
#define FOREVER 1e20
Definition at line 474 of file Fl.cxx.
Referenced by Fl::run(), and Fl::wait().
Function Documentation
Fl_Window* fl_find (Window xid)
Definition at line 616 of file Fl.cxx.
References Fl_X::first, Fl::modal(), Fl_X::next, Fl_X::w, Fl_Widget::window(), and Fl_X::xid.
Referenced by FLDropTarget::DragEnter(), Fl::first_window(), fl_handle(), and fl_read_image().
void fl_fix_focus ()
Definition at line 872 of file Fl.cxx.
References Fl::belowmouse(), Fl_Widget::contains(), Fl::e_keysym, Fl::e_number, Fl::e_x, Fl::e_x_root, Fl::e_y, Fl::e_y_root, Fl_Tooltip::enter, FL_Button, FL_ENTER, FL_LEFT_MOUSE, FL_MOVE, FL_RIGHT_MOUSE, fl_xfocus, fl_xmousewin, Fl::focus(), Fl::grab(), Fl_Widget::handle(), Fl::modal(), Fl_Widget::parent(), Fl::pushed(), Fl_Widget::take_focus(), w, Fl_Widget::x(), and Fl_Widget::y().
Referenced by fl_throw_focus(), Fl::grab(), Fl::handle(), Fl_X::make(), and Fl_X::set_xid().
int fl_ready ()
Check if there is actually a message pending!
Definition at line 480 of file Fl_mac.cxx.
References fl_display, NULL, and select().
Referenced by Fl::ready().
void fl_throw_focus (Fl_Widget * o)
Definition at line 934 of file Fl.cxx.
References Fl::belowmouse(), Fl_Widget::contains(), Fl_Tooltip::current(), Fl_Tooltip::exit, fl_fix_focus(), Fl::focus(), and Fl::pushed().
Referenced by Fl_Widget::deactivate(), Fl_Widget::hide(), Fl_Window::hide(), and Fl_Widget::~Fl_Widget().
int fl_wait (double time)
This public function handles all events. It wait a maximum of 'time' secods for an event. This version returns 1 if events other than the timeout timer were processed.
Todo:
there is no socket handling in this code whatsoever
Definition at line 793 of file Fl_mac.cxx.
References Fl::damage(), data, f, FALSE, Fl::first_window(), fl_display, FL_EXCEPT, fl_lock_function, FL_READ, fl_unlock_function, fl_wake_msg, FL_WRITE, Fl::flush(), func, Fl::get_awake_handler_(), i, Fl::idle, int, NULL, POLLERR, POLLIN, POLLOUT, and select().
Referenced by Fl::wait().
Variable Documentation
int alloc_dwidgets = 0
Definition at line 1559 of file Fl.cxx.
Referenced by Fl::delete_widget().
int(* fl_local_grab)(int)
Definition at line 765 of file Fl.cxx.
Referenced by Fl::handle().
Fl_Widget* fl_oldfocus
Definition at line 775 of file Fl.cxx.
Referenced by Fl_Group::handle().
Fl_Widget* fl_selection_requestor
Definition at line 2583 of file Fl_mac.cxx.
Fl_Window* fl_xfocus
Definition at line 96 of file Fl.cxx.
Referenced by fl_fix_focus().
Fl_Window* fl_xmousewin
Definition at line 97 of file Fl.cxx.
Referenced by fl_fix_focus().
Check * free_check
Definition at line 295 of file Fl.cxx.
Referenced by Fl::add_check(), and Fl::remove_check().
Timeout * free_timeout
Definition at line 196 of file Fl.cxx.
Referenced by Fl::remove_timeout(), and Fl::repeat_timeout().
int free_timeout_count
Definition at line 197 of file Fl.cxx.
Referenced by Fl::repeat_timeout(), and Fl::wait().
Check * next_check
Definition at line 295 of file Fl.cxx.