SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/fl_symbols.cxx File Reference
fl_symbols.cxx File Reference
#include <FL/Fl.H>
#include <FL/fl_draw.H>
#include <FL/math.h>
#include "flstring.h"
Classes
struct SYMBOL
Defines
#define MAXSYMBOL 211
#define BP fl_begin_polygon()
#define EP fl_end_polygon()
#define BCP fl_begin_complex_polygon()
#define ECP fl_end_complex_polygon()
#define BL fl_begin_line()
#define EL fl_end_line()
#define BC fl_begin_loop()
#define EC fl_end_loop()
#define vv(x, y) fl_vertex(x,y)
Functions
int fl_add_symbol (const char *name, void(*drawit)(Fl_Color), int scalable)
int fl_return_arrow (int x, int y, int w, int h)
int fl_draw_symbol (const char *label, int x, int y, int w, int h, Fl_Color col)
Define Documentation
#define BC fl_begin_loop()
Definition at line 186 of file fl_symbols.cxx.
#define BCP fl_begin_complex_polygon()
Definition at line 182 of file fl_symbols.cxx.
#define BL fl_begin_line()
Definition at line 184 of file fl_symbols.cxx.
#define BP fl_begin_polygon()
Definition at line 180 of file fl_symbols.cxx.
#define EC fl_end_loop()
Definition at line 187 of file fl_symbols.cxx.
#define ECP fl_end_complex_polygon()
Definition at line 183 of file fl_symbols.cxx.
#define EL fl_end_line()
Definition at line 185 of file fl_symbols.cxx.
#define EP fl_end_polygon()
Definition at line 181 of file fl_symbols.cxx.
#define MAXSYMBOL 211
Definition at line 49 of file fl_symbols.cxx.
Referenced by fl_add_symbol().
#define vv (x, y) fl_vertex(x,y)
Definition at line 188 of file fl_symbols.cxx.
Referenced by Fl_Clock_Output::value().
Function Documentation
int fl_return_arrow (int x, int y, int w, int h)
Definition at line 32 of file Fl_Return_Button.cxx.
References fl_color(), FL_DARK3, fl_gray_ramp(), FL_LIGHT3, fl_line(), fl_xyline(), fl_yxline(), h, size, and w.
Referenced by Fl_Return_Button::draw(), and fl_draw_symbol().