SfR Fresh Dox - fltk: fltk-1.3.0rc3/FL/fl_ask.H File Reference
fl_ask.H File Reference
#include "Enumerations.H"
Defines
#define __fl_attr(x)
Enumerations
enum {
FL_BEEP_DEFAULT = 0, FL_BEEP_MESSAGE, FL_BEEP_ERROR, FL_BEEP_QUESTION,
FL_BEEP_PASSWORD, FL_BEEP_NOTIFICATION
}
Functions
FL_EXPORT void fl_beep (int type=FL_BEEP_DEFAULT)
FL_EXPORT void fl_message (const char *,...) __fl_attr((__format__(__printf__
FL_EXPORT void FL_EXPORT void fl_alert (const char *,...) __fl_attr((__format__(__printf__
FL_EXPORT void FL_EXPORT void
FL_EXPORT int fl_ask (const char *,...) __fl_attr((__format__(__printf__
FL_EXPORT int fl_choice (const char *q, const char *b0, const char *b1, const char *b2,...) __fl_attr((__format__(__printf__
FL_EXPORT int FL_EXPORT const
char * fl_input (const char *label, const char *deflt=0,...) __fl_attr((__format__(__printf__
FL_EXPORT int FL_EXPORT const
char FL_EXPORT const char * fl_password (const char *label, const char *deflt=0,...) __fl_attr((__format__(__printf__
FL_EXPORT int FL_EXPORT const
char FL_EXPORT const char
FL_EXPORT Fl_Widget * fl_message_icon ()
void fl_message_font (Fl_Font f, Fl_Fontsize s)
Variables
FL_EXPORT void FL_EXPORT void
FL_EXPORT int __deprecated__
FL_EXPORT Fl_Font fl_message_font_
FL_EXPORT Fl_Fontsize fl_message_size_
FL_EXPORT const char * fl_no
string pointer used in common dialogs, you can change it to a foreign language
FL_EXPORT const char * fl_yes
string pointer used in common dialogs, you can change it to a foreign language
FL_EXPORT const char * fl_ok
string pointer used in common dialogs, you can change it to a foreign language
FL_EXPORT const char * fl_cancel
string pointer used in common dialogs, you can change it to a foreign language
FL_EXPORT const char * fl_close
string pointer used in common dialogs, you can change it to a foreign language
Define Documentation
#define __fl_attr (x)
Definition at line 47 of file fl_ask.H.
Enumeration Type Documentation
anonymous enum [related]
Different system beeps available.(int)
Enumerator:
FL_BEEP_DEFAULT
FL_BEEP_MESSAGE
FL_BEEP_ERROR
FL_BEEP_QUESTION
FL_BEEP_PASSWORD
FL_BEEP_NOTIFICATION
Definition at line 35 of file fl_ask.H.
Function Documentation
FL_EXPORT void FL_EXPORT void fl_alert (const char * , ...)
Referenced by do_shell_command(), Fl_PostScript_File_Device::end_job(), fl_show_alert(), new_cb(), Fl_Class_Type::open(), Fl_Comment_Type::open(), Fl_DeclBlock_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_CodeBlock_Type::open(), Fl_Code_Type::open(), Fl_Function_Type::open(), print_cb(), save_cb(), save_template_cb(), Fl_PostScript_Printer::start_job(), template_delete_cb(), and Fl_Data_Type::write_code1().
FL_EXPORT void FL_EXPORT void FL_EXPORT int fl_ask (const char * , ...)
FL_EXPORT int fl_choice (const char * q, const char * b0, const char * b1, const char * b2, ...)
Referenced by exit_cb(), fl_show_choice(), fl_show_question(), new_cb(), Fl_Comment_Type::open(), open_cb(), open_history_cb(), print_cb(), revert_cb(), save_cb(), save_template_cb(), and template_delete_cb().
FL_EXPORT int FL_EXPORT const char* fl_input (const char * label, const char * deflt = 0, ...)
Referenced by fl_show_input(), fl_show_simple_input(), Fl_Comment_Type::open(), and Fl_File_Chooser::rescan_keep_filename().
FL_EXPORT void fl_message (const char * , ...)
Referenced by Fl_Table_Type::add_child(), callback_cb(), copy_cb(), cut_cb(), duplicate_cb(), fl_show_message(), group_cb(), main(), Fl_Window_Type::make(), Fl_Widget_Type::make(), Fl_Menu_Item_Type::make(), Fl_CodeBlock_Type::make(), Fl_Code_Type::make(), Fl_Comment_Type::open(), open_cb(), open_history_cb(), openwidget_cb(), paste_cb(), read_error(), revert_cb(), show_global_settings_window(), ungroup_cb(), user_data_cb(), user_data_type_cb(), v_input_cb(), write_cb(), and write_strings_cb().
void fl_message_font (Fl_Font f, Fl_Fontsize s) [inline]
Definition at line 64 of file fl_ask.H.
References f.
Referenced by fl_set_goodies_font().
FL_EXPORT int FL_EXPORT const char FL_EXPORT const char* fl_password (const char * label, const char * deflt = 0, ...)
Variable Documentation
FL_EXPORT void FL_EXPORT void FL_EXPORT int __deprecated__
Definition at line 56 of file fl_ask.H.
FL_EXPORT Fl_Font fl_message_font_
Definition at line 57 of file fl_ask.cxx.
Referenced by resizeform().
FL_EXPORT Fl_Fontsize fl_message_size_
Definition at line 58 of file fl_ask.cxx.
Referenced by resizeform().