SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/Fl_Window_Type.cxx File Reference
Fl_Window_Type.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Overlay_Window.H>
#include <FL/fl_message.H>
#include <FL/fl_draw.H>
#include <FL/x.H>
#include <FL/Fl_Menu_Item.H>
#include <FL/Fl_Round_Button.H>
#include "Fl_Widget_Type.h"
#include "undo.h"
#include <math.h>
#include <stdlib.h>
#include "alignment_panel.h"
#include <stdio.h>
#include "widget_panel.h"
#include "../src/flstring.h"
Classes
class Overlay_Window
Functions
int fl_min (int a, int b)
void guides_cb (Fl_Check_Button *i, long)
void grid_cb (Fl_Int_Input *i, long v)
void default_widget_size_cb (Fl_Round_Button *b, long size)
void i18n_type_cb (Fl_Choice *c, void *)
void i18n_text_cb (Fl_Input *i, void *)
void i18n_int_cb (Fl_Int_Input *i, void *)
void show_project_cb (Fl_Widget *, void *)
void show_grid_cb (Fl_Widget *, void *)
void show_settings_cb (Fl_Widget *, void *)
void show_global_settings_cb (Fl_Widget *, void *)
void header_input_cb (Fl_Input *i, void *)
void code_input_cb (Fl_Input *i, void *)
void include_H_from_C_button_cb (Fl_Check_Button *b, void *)
void use_FL_COMMAND_button_cb (Fl_Check_Button *b, void *)
void modal_cb (Fl_Light_Button *i, void *v)
void non_modal_cb (Fl_Light_Button *i, void *v)
void border_cb (Fl_Light_Button *i, void *v)
void xclass_cb (Fl_Input *i, void *v)
void check_redraw_corresponding_parent (Fl_Type *s)
void redraw_overlays ()
void toggle_overlays (Fl_Widget *, void *)
void select (Fl_Type *, int)
void select_only (Fl_Type *)
void deselect ()
void fix_group_size (Fl_Type *t)
Variables
int gridx
int gridy
int snap
int show_guides
int include_H_from_C = 1
int use_FL_COMMAND = 0
int i18n_type
const char * i18n_include
const char * i18n_function
const char * i18n_file
const char * i18n_set
Fl_Preferences fluid_prefs
const char * header_file_name
const char * code_file_name
Fl_Menu_Item window_type_menu []
Fl_Window * main_window
Fl_Window_Type Fl_Window_type
Fl_Menu_Item Main_Menu []
Fl_Type * in_this_only
Fl_Menu_Item New_Menu []
int pasteoffset
Fl_Widget_Class_Type Fl_Widget_Class_type
Fl_Widget_Class_Type * current_widget_class = 0
Function Documentation
void border_cb (Fl_Light_Button * i, void * v)
Definition at line 468 of file Fl_Window_Type.cxx.
References Fl_Widget::hide(), Fl_Type::is_window(), LOAD, Fl_Widget_Type::o, set_modflag(), Fl_Widget::show(), and Fl_Button::value().
Referenced by make_widget_panel().
void check_redraw_corresponding_parent (Fl_Type * s)
Definition at line 1105 of file Fl_Window_Type.cxx.
References i, Fl_Type::is_widget(), Fl_Widget_Type::o, and Fl_Type::selected.
Referenced by selection_changed().
void code_input_cb (Fl_Input * i, void *)
Definition at line 258 of file Fl_Window_Type.cxx.
References set_modflag(), and Fl_Input_::value().
Referenced by make_project_window().
void default_widget_size_cb (Fl_Round_Button * b, long size)
Definition at line 121 of file Fl_Window_Type.cxx.
References Fl_Widget_Type::default_size, Fl_Preferences::set(), Fl_Button::setonly(), and size.
Referenced by make_layout_window().
void deselect ()
Definition at line 213 of file Fl_Type.cxx.
References Fl_Browser_::deselect().
void fix_group_size (Fl_Type * t)
Definition at line 52 of file Fl_Group_Type.cxx.
References b, Fl_Widget::h(), Fl_Type::is_group(), Fl_Type::level, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::resize(), Fl_Widget::w(), x, Fl_Widget::x(), y, and Fl_Widget::y().
Referenced by group_cb(), and Fl_Window_Type::moveallchildren().
int fl_min (int a, int b) [inline]
Definition at line 61 of file Fl_Window_Type.cxx.
Referenced by Fl_Window_Type::draw_overlay().
void grid_cb (Fl_Int_Input * i, long v)
Definition at line 87 of file Fl_Window_Type.cxx.
References Fl_Type::first, gridx, gridy, Fl::h(), Fl_Type::is_window(), Fl_Type::next, Fl_Widget_Type::o, Fl_Preferences::set(), snap, Fl_Input_::value(), Fl::w(), and w.
Referenced by main(), and make_layout_window().
void guides_cb (Fl_Check_Button * i, long)
Definition at line 75 of file Fl_Window_Type.cxx.
References Fl_Type::first, Fl_Type::next, Fl_Widget_Type::o, Fl_Preferences::set(), show_guides, Fl_Button::value(), and w.
Referenced by make_layout_window().
void header_input_cb (Fl_Input * i, void *)
Definition at line 253 of file Fl_Window_Type.cxx.
References set_modflag(), and Fl_Input_::value().
Referenced by make_project_window().
void i18n_int_cb (Fl_Int_Input * i, void *)
Definition at line 179 of file Fl_Window_Type.cxx.
References i18n_set, i18n_set_input, set_modflag(), undo_checkpoint(), and Fl_Input_::value().
Referenced by make_project_window().
void i18n_text_cb (Fl_Input * i, void *)
Definition at line 166 of file Fl_Window_Type.cxx.
References i18n_file, i18n_file_input, i18n_function, i18n_function_input, i18n_include, i18n_include_input, set_modflag(), undo_checkpoint(), and Fl_Input_::value().
Referenced by make_project_window().
void i18n_type_cb (Fl_Choice * c, void *)
Definition at line 129 of file Fl_Window_Type.cxx.
References Fl_Widget::hide(), i18n_file, i18n_file_input, i18n_function, i18n_function_input, i18n_include, i18n_include_input, i18n_set, i18n_set_input, i18n_type, set_modflag(), Fl_Widget::show(), undo_checkpoint(), Fl_Input_::value(), and Fl_Choice::value().
Referenced by make_project_window().
void include_H_from_C_button_cb (Fl_Check_Button * b, void *)
Definition at line 264 of file Fl_Window_Type.cxx.
References include_H_from_C, set_modflag(), and Fl_Button::value().
Referenced by make_project_window().
void modal_cb (Fl_Light_Button * i, void * v)
Definition at line 446 of file Fl_Window_Type.cxx.
References Fl_Widget::hide(), Fl_Type::is_window(), LOAD, set_modflag(), Fl_Widget::show(), and Fl_Button::value().
Referenced by make_widget_panel().
void non_modal_cb (Fl_Light_Button * i, void * v)
Definition at line 457 of file Fl_Window_Type.cxx.
References Fl_Widget::hide(), Fl_Type::is_window(), LOAD, set_modflag(), Fl_Widget::show(), and Fl_Button::value().
Referenced by make_widget_panel().
void redraw_overlays ()
Definition at line 1121 of file Fl_Window_Type.cxx.
References Fl_Type::first, and Fl_Type::next.
Referenced by selection_changed().
void select (Fl_Type * , int)
Definition at line 204 of file Fl_Type.cxx.
References Fl_Browser_::select().
void select_only (Fl_Type *)
Definition at line 209 of file Fl_Type.cxx.
void show_global_settings_cb (Fl_Widget * , void *)
Definition at line 248 of file Fl_Window_Type.cxx.
References global_settings_window, Fl_Window::hotspot(), and show_global_settings_window().
void show_grid_cb (Fl_Widget * , void *)
Definition at line 226 of file Fl_Window_Type.cxx.
References buf, def_widget_size, Fl_Widget_Type::default_size, grid_window, gridx, gridy, guides_toggle, horizontal_input, Fl_Window::hotspot(), Fl_Button::setonly(), Fl_Double_Window::show(), show_guides, snap, snap_input, Fl_Button::value(), Fl_Input_::value(), and vertical_input.
void show_project_cb (Fl_Widget * , void *)
Definition at line 191 of file Fl_Window_Type.cxx.
References code_file_input, header_file_input, Fl_Widget::hide(), Fl_Window::hotspot(), i18n_file, i18n_file_input, i18n_function, i18n_function_input, i18n_include, i18n_include_input, i18n_set, i18n_set_input, i18n_type, i18n_type_chooser, include_H_from_C, include_H_from_C_button, make_project_window(), project_window, Fl_Double_Window::show(), Fl_Widget::show(), use_FL_COMMAND, use_FL_COMMAND_button, Fl_Choice::value(), Fl_Input_::value(), and Fl_Button::value().
void show_settings_cb (Fl_Widget * , void *)
Definition at line 243 of file Fl_Window_Type.cxx.
References Fl_Window::hotspot(), settings_window, and Fl_Double_Window::show().
void toggle_overlays (Fl_Widget * , void *)
Definition at line 1126 of file Fl_Window_Type.cxx.
References Fl_Type::first, Fl_Menu_Item::label(), Fl_Type::next, and Fl_Widget_Type::o.
Referenced by Fl_Window_Type::handle(), and overlay_cb().
void use_FL_COMMAND_button_cb (Fl_Check_Button * b, void *)
Definition at line 271 of file Fl_Window_Type.cxx.
References set_modflag(), use_FL_COMMAND, and Fl_Button::value().
Referenced by make_project_window().
void xclass_cb (Fl_Input * i, void * v)
Definition at line 479 of file Fl_Window_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_button(), Fl_Type::is_menu_item(), Fl_Type::is_window(), LOAD, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::parent(), Fl_Widget_Type::redraw(), set_modflag(), Fl_Widget::show(), storestring(), Fl_Input_::value(), w, and Fl_Widget_Type::xclass.
Referenced by make_widget_panel().
Variable Documentation
const char* code_file_name
Definition at line 648 of file fluid.cxx.
Fl_Widget_Class_Type* current_widget_class = 0
Definition at line 1444 of file Fl_Window_Type.cxx.
Fl_Widget_Class_Type Fl_Widget_Class_type
Definition at line 1443 of file Fl_Window_Type.cxx.
Fl_Window_Type Fl_Window_type
Definition at line 512 of file Fl_Window_Type.cxx.
Fl_Preferences fluid_prefs
int gridx
Definition at line 98 of file fluid.cxx.
int gridy
Definition at line 99 of file fluid.cxx.
const char* header_file_name
Definition at line 647 of file fluid.cxx.
const char* i18n_file
Definition at line 652 of file fluid.cxx.
const char* i18n_function
Definition at line 651 of file fluid.cxx.
const char* i18n_include
Definition at line 650 of file fluid.cxx.
const char* i18n_set
Definition at line 653 of file fluid.cxx.
int i18n_type
Definition at line 649 of file fluid.cxx.
Fl_Type* in_this_only
Definition at line 697 of file Fl_Type.cxx.
Referenced by select_all_cb(), and select_none_cb().
int include_H_from_C = 1
Definition at line 51 of file Fl_Window_Type.cxx.
Referenced by delete_all(), include_H_from_C_button_cb(), show_project_cb(), write_code(), and write_file().
Fl_Menu_Item Main_Menu
Definition at line 1145 of file Fl_Window_Type.cxx.
Fl_Window* main_window
Definition at line 179 of file fluid.cxx.
Fl_Menu_Item New_Menu[]
Definition at line 1011 of file factory.cxx.
int pasteoffset
Definition at line 2507 of file Fl_Widget_Type.cxx.
int show_guides
Definition at line 101 of file fluid.cxx.
Referenced by Fl_Window_Type::draw_overlay(), guides_cb(), make_main_window(), and show_grid_cb().
int snap
Definition at line 100 of file fluid.cxx.
Referenced by grid_cb(), Fl_Window_Type::handle(), make_main_window(), Fl_Window_Type::newdx(), and show_grid_cb().
int use_FL_COMMAND = 0
Definition at line 52 of file Fl_Window_Type.cxx.
Referenced by delete_all(), Shortcut_Button::draw(), show_project_cb(), use_FL_COMMAND_button_cb(), write_file(), Fl_Menu_Item_Type::write_item(), and Fl_Widget_Type::write_widget_code().
Fl_Menu_Item window_type_menu[]
Initial value:
 {
  {"Single",0,0,(void*)FL_WINDOW},
  {"Double",0,0,(void*)(FL_WINDOW+1)},
  {0}}
Definition at line 280 of file Fl_Window_Type.cxx.
Referenced by Fl_Window_Type::subtypes().