SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/fl_font_mac.cxx File Reference
fl_font_mac.cxx File Reference
#include <config.h>
Defines
#define check_default_font() {if (!fl_fontsize) fl_font(0, 12);}
#define ENABLE_TRANSIENT_FONTS 1
Functions
unsigned fl_utf8toUtf16 (const char *src, unsigned srclen, unsigned short *dst, unsigned dstlen)
void fl_font (Fl_Font_Descriptor *s)
int fl_height ()
int fl_descent ()
double fl_width (const UniChar *txt, int n)
double fl_width (const char *txt, int n)
double fl_width (uchar c)
double fl_width (unsigned int wc)
void fl_text_extents (const UniChar *txt, int n, int &dx, int &dy, int &w, int &h)
void fl_text_extents (const char *c, int n, int &dx, int &dy, int &w, int &h)
void fl_draw (const char *str, int n, float x, float y)
Variables
Fl_Font_Descriptor * fl_fontsize = 0L
Fl_Fontdesc * fl_fonts = built_in_table
Fl_Font fl_font_ = 0
current font index
Fl_Fontsize fl_size_ = 0
current font size
Define Documentation
#define check_default_font () {if (!fl_fontsize) fl_font(0, 12);}
Definition at line 34 of file fl_font_mac.cxx.
Referenced by fl_descent(), fl_height(), fl_text_extents(), and fl_width().
#define ENABLE_TRANSIENT_FONTS 1
Function Documentation
void fl_draw (const char * str, int n, float x, float y)
Definition at line 85 of file fl_font.cxx.
References fl_draw().
void fl_font (Fl_Font_Descriptor * s)
Definition at line 216 of file fl_font_mac.cxx.
void fl_text_extents (const UniChar * txt, int n, int & dx, int & dy, int & w, int & h)
Definition at line 332 of file fl_font_mac.cxx.
References check_default_font, fl_gc, fl_mac_os_version, int, NULL, and rect().
double fl_width (uchar c)
Definition at line 323 of file fl_font_mac.cxx.
References fl_width().
double fl_width (const UniChar * txt, int n)
Definition at line 264 of file fl_font_mac.cxx.
References check_default_font, fl_gc, fl_mac_os_version, and NULL.
Variable Documentation
Fl_Fontdesc* fl_fonts = built_in_table
Definition at line 214 of file fl_font_mac.cxx.
Fl_Font_Descriptor* fl_fontsize = 0L
Definition at line 150 of file fl_font_mac.cxx.