SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/Fl_Widget_Type.cxx File Reference
Fl_Widget_Type.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Table.H>
#include <FL/Fl_Input.H>
#include "Fl_Widget_Type.h"
#include "alignment_panel.h"
#include <FL/fl_message.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Window.H>
#include "../src/flstring.h"
#include <stdio.h>
#include <stdlib.h>
#include "Fluid_Image.h"
#include "widget_panel.h"
#include <FL/fl_show_colormap.H>
Defines
#define ZERO_ENTRY 1000
Functions
const char * subclassname (Fl_Type *l)
void redraw_browser ()
Fl_Type * sort (Fl_Type *parent)
void name_cb (Fl_Input *o, void *v)
void name_public_member_cb (Fl_Choice *i, void *v)
void name_public_cb (Fl_Choice *i, void *v)
void label_cb (Fl_Input *i, void *v)
void image_cb (Fl_Input *i, void *v)
void image_browse_cb (Fl_Button *b, void *v)
void inactive_cb (Fl_Input *i, void *v)
void inactive_browse_cb (Fl_Button *b, void *v)
void tooltip_cb (Fl_Input *i, void *v)
void x_cb (Fl_Value_Input *i, void *v)
void y_cb (Fl_Value_Input *i, void *v)
void w_cb (Fl_Value_Input *i, void *v)
void h_cb (Fl_Value_Input *i, void *v)
void wc_relative_cb (Fl_Light_Button *i, void *v)
const char * item_name (Fl_Menu_Item *m, int i)
int item_number (Fl_Menu_Item *m, const char *i)
const char * boxname (int i)
int boxnumber (const char *i)
void box_cb (Fl_Choice *i, void *v)
void down_box_cb (Fl_Choice *i, void *v)
void when_cb (Fl_Choice *i, void *v)
void when_button_cb (Fl_Light_Button *i, void *v)
void resizable_cb (Fl_Light_Button *i, void *v)
void hotspot_cb (Fl_Light_Button *i, void *v)
void visible_cb (Fl_Light_Button *i, void *v)
void active_cb (Fl_Light_Button *i, void *v)
void labelfont_cb (Fl_Choice *i, void *v)
void labelsize_cb (Fl_Value_Input *i, void *v)
void labeltype_cb (Fl_Choice *i, void *v)
void color_cb (Fl_Button *i, void *v)
void color2_cb (Fl_Button *i, void *v)
void labelcolor_cb (Fl_Button *i, void *v)
void align_cb (Fl_Button *i, void *v)
void align_position_cb (Fl_Choice *i, void *v)
void align_text_image_cb (Fl_Choice *i, void *v)
void callback_cb (CodeEditor *i, void *v)
void user_data_cb (Fl_Input *i, void *v)
void user_data_type_cb (Fl_Input *i, void *v)
void v_input_cb (Fl_Input *i, void *v)
void subclass_cb (Fl_Input *i, void *v)
void textfont_cb (Fl_Choice *i, void *v)
void textsize_cb (Fl_Value_Input *i, void *v)
void textcolor_cb (Fl_Button *i, void *v)
void min_w_cb (Fl_Value_Input *i, void *v)
void min_h_cb (Fl_Value_Input *i, void *v)
void max_w_cb (Fl_Value_Input *i, void *v)
void max_h_cb (Fl_Value_Input *i, void *v)
void set_min_size_cb (Fl_Button *, void *v)
void set_max_size_cb (Fl_Button *, void *v)
void slider_size_cb (Fl_Value_Input *i, void *v)
void min_cb (Fl_Value_Input *i, void *v)
void max_cb (Fl_Value_Input *i, void *v)
void step_cb (Fl_Value_Input *i, void *v)
void value_cb (Fl_Value_Input *i, void *v)
void subtype_cb (Fl_Choice *i, void *v)
void propagate_load (Fl_Group *g, void *v)
void set_cb (Fl_Button *, void *)
void ok_cb (Fl_Return_Button *o, void *v)
void revert_cb (Fl_Button *, void *)
void cancel_cb (Fl_Button *o, void *v)
void toggle_overlays (Fl_Widget *, void *)
void overlay_cb (Fl_Button *o, void *v)
void leave_live_mode_cb (Fl_Widget *, void *)
void live_mode_cb (Fl_Button *o, void *)
void redraw_overlays ()
void check_redraw_corresponding_parent (Fl_Type *)
void update_sourceview_position ()
void selection_changed (Fl_Type *p)
int is_name (const char *c)
const char * array_name (Fl_Widget_Type *o)
int isdeclare (const char *c)
int lookup_symbol (const char *, int &, int numberok=0)
Variables
int reading_file
int force_parent
int gridx
int gridy
int i18n_type
const char * i18n_include
const char * i18n_function
const char * i18n_file
const char * i18n_set
Fl_Widget_Type * current_widget
void *const LOAD = "LOAD"
Fl_Value_Input * x_input
Fl_Value_Input * y_input
Fl_Value_Input * w_input
Fl_Value_Input * h_input
Fl_Menu_Item boxmenu []
Fl_Menu_Item whenmenu []
Fl_Menu_Item fontmenu []
const char * ui_find_image_name
Fl_Menu_Item labeltypemenu []
int varused_test
int varused
int pasteoffset
double read_version
Fl_Menu_Item boxmenu1 []
int fdesign_flip
Define Documentation
#define ZERO_ENTRY 1000
Definition at line 654 of file Fl_Widget_Type.cxx.
Referenced by box_cb(), boxname(), down_box_cb(), Fl_Widget_Type::read_fdesign(), Fl_Widget_Type::read_property(), and when_cb().
Function Documentation
void active_cb (Fl_Light_Button * i, void * v)
Definition at line 942 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::active(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_window(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), and Fl_Button::value().
Referenced by make_widget_panel().
void align_cb (Fl_Button * i, void * v)
Definition at line 1149 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::align(), Fl_Widget::argument(), b, Fl_Button::clear(), Fl_Widget::deactivate(), Fl_Type::first, FL_ALIGN_BOTTOM, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_ALIGN_TOP, Fl_Type::is_menu_item(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Widget::user_data(), Fl_Button::value(), x, and y.
Referenced by make_widget_panel().
void align_position_cb (Fl_Choice * i, void * v)
Definition at line 1187 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::align(), Fl_Menu_Item::argument(), b, Fl_Widget::deactivate(), Fl_Type::first, FL_ALIGN_POSITION_MASK, Fl_Type::is_menu_item(), Fl_Menu_::menu(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Menu_Item::text, Fl_Menu_Item::user_data(), Fl_Choice::value(), x, and y.
Referenced by make_widget_panel().
void align_text_image_cb (Fl_Choice * i, void * v)
Definition at line 1216 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::align(), Fl_Menu_Item::argument(), b, Fl_Widget::deactivate(), Fl_Type::first, FL_ALIGN_IMAGE_MASK, Fl_Type::is_menu_item(), Fl_Menu_::menu(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Menu_Item::text, Fl_Menu_Item::user_data(), Fl_Choice::value(), x, and y.
Referenced by make_widget_panel().
const char* array_name (Fl_Widget_Type * o)
Definition at line 1937 of file Fl_Widget_Type.cxx.
References buffer, Fl_Type::class_name(), Fl_Type::name(), num, Fl_Type::prev, and snprintf.
Referenced by Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
void box_cb (Fl_Choice * i, void * v)
Definition at line 727 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::box(), Fl_Widget::deactivate(), Fl_Type::first, int, Fl_Type::is_menu_item(), m, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Choice::value(), and ZERO_ENTRY.
Referenced by make_widget_panel().
const char* boxname (int i)
Definition at line 711 of file Fl_Widget_Type.cxx.
References i, int, and ZERO_ENTRY.
Referenced by Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
int boxnumber (const char * i)
Definition at line 718 of file Fl_Widget_Type.cxx.
References int.
Referenced by Fl_Widget_Type::read_fdesign(), and Fl_Widget_Type::read_property().
void callback_cb (CodeEditor * i, void * v)
Definition at line 1247 of file Fl_Widget_Type.cxx.
References Fl_Text_Display::buffer(), c_check(), Fl_Widget::callback(), Fl_Type::callback(), Fl_Type::first, fl_message(), Fl_Window::make_current(), set_modflag(), and Fl_Widget::window().
Referenced by make_widget_panel().
void cancel_cb (Fl_Button * o, void * v)
Definition at line 1778 of file Fl_Widget_Type.cxx.
References Fl_Window::hide(), and revert_cb().
Referenced by make_widget_panel().
void check_redraw_corresponding_parent (Fl_Type *)
Definition at line 1105 of file Fl_Window_Type.cxx.
References i, Fl_Type::is_widget(), Fl_Widget_Type::o, and Fl_Type::selected.
Referenced by selection_changed().
void color2_cb (Fl_Button * i, void * v)
Definition at line 1084 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Type::first, FL_BLACK, fl_contrast(), fl_show_colormap(), Fl_Type::is_menu_item(), Fl_Widget::labelcolor(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::redraw(), Fl_Widget::selection_color(), and set_modflag().
Referenced by make_widget_panel().
void color_cb (Fl_Button * i, void * v)
Definition at line 1060 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Type::first, FL_BLACK, fl_contrast(), fl_show_colormap(), Fl_Type::is_menu_item(), Fl_Widget::labelcolor(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::parent(), Fl_Type::parent, Fl_Widget::redraw(), set_modflag(), tabs_type_name, and Fl_Type::type_name().
Referenced by make_widget_panel().
void down_box_cb (Fl_Choice * i, void * v)
Definition at line 751 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, int, Fl_Type::is_button(), Fl_Type::is_menu_button(), Fl_Type::is_menu_item(), m, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Type::type_name(), Fl_Choice::value(), and ZERO_ENTRY.
Referenced by make_widget_panel().
void h_cb (Fl_Value_Input * i, void * v)
Definition at line 581 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, gridx, gridy, Fl::h(), i, int, Fl_Widget_Type::is_widget(), Fl_Type::next, Fl_Widget::redraw(), Fl_Widget::resize(), set_modflag(), Fl_Valuator::value(), Fl::w(), Fl_Widget::w(), w, Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by make_widget_panel().
void hotspot_cb (Fl_Light_Button * i, void * v)
Definition at line 892 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), current_widget, Fl_Widget::deactivate(), Fl_Widget_Type::hotspot(), Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::is_window(), Fl_Widget::label(), Fl_Type::level, Fl_Type::next, Fl_Type::parent, Fl_Widget_Type::redraw(), set_modflag(), and Fl_Button::value().
Referenced by make_widget_panel().
void image_browse_cb (Fl_Button * b, void * v)
Definition at line 423 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget_Type::is_widget(), Fl_Type::is_window(), Fl_Type::next, set_modflag(), ui_find_image(), ui_find_image_name, and Fl_Input_::value().
Referenced by make_widget_panel().
void image_cb (Fl_Input * i, void * v)
Definition at line 404 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, i, Fl_Widget_Type::is_widget(), Fl_Type::is_window(), Fl_Type::next, set_modflag(), Fl_Input_::static_value(), and Fl_Input_::value().
Referenced by make_widget_panel().
void inactive_browse_cb (Fl_Button * b, void * v)
Definition at line 465 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget_Type::is_widget(), Fl_Type::is_window(), Fl_Type::next, set_modflag(), ui_find_image(), ui_find_image_name, and Fl_Input_::value().
Referenced by make_widget_panel().
void inactive_cb (Fl_Input * i, void * v)
Definition at line 446 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, i, Fl_Widget_Type::is_widget(), Fl_Type::is_window(), Fl_Type::next, set_modflag(), Fl_Input_::static_value(), and Fl_Input_::value().
Referenced by make_widget_panel().
int is_name (const char * c)
Definition at line 1929 of file Fl_Widget_Type.cxx.
Referenced by Fl_Type::callback_name(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Menu_Item_Type::write_item(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
int isdeclare (const char * c)
Definition at line 1967 of file Fl_Widget_Type.cxx.
Referenced by Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Widget_Type::write_extra_code(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
const char* item_name (Fl_Menu_Item * m, int i)
Definition at line 632 of file Fl_Widget_Type.cxx.
References Fl_Menu_Item::argument(), buffer, i, and Fl_Menu_Item::label().
Referenced by Fl_Widget_Type::write_properties(), and Fl_Widget_Type::write_widget_code().
int item_number (Fl_Menu_Item * m, const char * i)
Definition at line 643 of file Fl_Widget_Type.cxx.
References Fl_Menu_Item::argument(), i, int, and Fl_Menu_Item::label().
Referenced by Fl_Widget_Type::read_fdesign(), and Fl_Widget_Type::read_property().
void label_cb (Fl_Input * i, void * v)
Definition at line 382 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Type::label(), Fl_Type::next, set_modflag(), Fl_Input_::static_value(), and Fl_Input_::value().
Referenced by make_widget_panel().
void labelcolor_cb (Fl_Button * i, void * v)
Definition at line 1105 of file Fl_Widget_Type.cxx.
References Fl_Widget::color(), Fl_Type::first, FL_BLACK, fl_contrast(), fl_show_colormap(), Fl_Widget::labelcolor(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::redraw(), Fl_Widget_Type::redraw(), and set_modflag().
Referenced by make_widget_panel().
void labelfont_cb (Fl_Choice * i, void * v)
Definition at line 983 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::labelfont(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), and Fl_Choice::value().
Referenced by make_widget_panel().
void labelsize_cb (Fl_Value_Input * i, void * v)
Definition at line 1003 of file Fl_Widget_Type.cxx.
References Fl_Widget_Type::default_size, Fl_Type::first, int, Fl_Widget::labelsize(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void labeltype_cb (Fl_Choice * i, void * v)
Definition at line 1034 of file Fl_Widget_Type.cxx.
References Fl_Type::first, FL_WHEN_RELEASE, int, Fl_Widget::labeltype(), m, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Choice::value(), and Fl_Widget::when().
Referenced by make_widget_panel().
void leave_live_mode_cb (Fl_Widget * , void *)
Definition at line 2767 of file Fl_Widget_Type.cxx.
References live_mode_cb().
Referenced by live_mode_cb().
void live_mode_cb (Fl_Button * o, void *)
Todo:
live mode should end gracefully when the application quits or when the user closes the live widget
Definition at line 1790 of file Fl_Widget_Type.cxx.
References Fl_Group::add(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Group::current(), current_widget, Fl::delete_widget(), Fl_Group::end(), Fl_Widget_Type::enter_live_mode(), FL_FLAT_BOX, FL_GREEN, FL_NO_BOX, Fl_Widget::h(), h, Fl_Window::hide(), Fl_Type::is_window(), Fl_Widget::labelsize(), Fl_Type::leave_live_mode(), leave_live_mode_cb(), Fl_Widget::position(), Fl_Group::resizable(), Fl_Window::set_modal(), Fl_Window::show(), Fl_Window::size_range(), Fl_Window_Type::sr_max_h, Fl_Window_Type::sr_max_w, Fl_Window_Type::sr_min_h, Fl_Window_Type::sr_min_w, Fl_Button::value(), Fl_Widget::w(), w, and wLiveMode.
Referenced by leave_live_mode_cb(), and make_widget_panel().
int lookup_symbol (const char * , int & , int numberok = 0)
Definition at line 1268 of file factory.cxx.
References i, int, and symbol::value.
Referenced by Fl_Widget_Type::read_fdesign().
void max_cb (Fl_Value_Input * i, void * v)
Definition at line 1595 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_spinner(), Fl_Type::is_valuator(), Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void max_h_cb (Fl_Value_Input * i, void * v)
Definition at line 1485 of file Fl_Widget_Type.cxx.
References Fl_Type::first, int, Fl_Type::is_window(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void max_w_cb (Fl_Value_Input * i, void * v)
Definition at line 1468 of file Fl_Widget_Type.cxx.
References Fl_Type::first, int, Fl_Type::is_window(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void min_cb (Fl_Value_Input * i, void * v)
Definition at line 1562 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_spinner(), Fl_Type::is_valuator(), Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void min_h_cb (Fl_Value_Input * i, void * v)
Definition at line 1451 of file Fl_Widget_Type.cxx.
References Fl_Type::first, int, Fl_Type::is_window(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void min_w_cb (Fl_Value_Input * i, void * v)
Definition at line 1433 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), int, Fl_Type::is_window(), Fl_Widget::parent(), set_modflag(), Fl_Widget::show(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void name_cb (Fl_Input * o, void * v)
Definition at line 311 of file Fl_Widget_Type.cxx.
References buf, Fl_Widget::hide(), Fl_Window::label(), Fl_Type::name(), Fl_Widget::show(), snprintf, Fl_Input_::static_value(), Fl_Type::title(), and Fl_Input_::value().
Referenced by make_widget_panel().
void name_public_cb (Fl_Choice * i, void * v)
Definition at line 360 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_in_class(), Fl_Type::next, Fl_Widget_Type::public_, redraw_browser(), set_modflag(), Fl_Widget::show(), and Fl_Choice::value().
Referenced by make_widget_panel().
void name_public_member_cb (Fl_Choice * i, void * v)
Definition at line 335 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_in_class(), Fl_Type::next, Fl_Widget_Type::public_, redraw_browser(), set_modflag(), Fl_Widget::show(), Fl_Choice::value(), and w.
Referenced by make_widget_panel().
void ok_cb (Fl_Return_Button * o, void * v)
Definition at line 1766 of file Fl_Widget_Type.cxx.
References Fl_Window::hide(), and set_cb().
Referenced by make_widget_panel().
void overlay_cb (Fl_Button * o, void * v)
Definition at line 1784 of file Fl_Widget_Type.cxx.
References toggle_overlays().
Referenced by make_widget_panel().
void propagate_load (Fl_Group * g, void * v)
Definition at line 1743 of file Fl_Widget_Type.cxx.
References Fl_Group::array(), Fl_Group::children(), and Fl_Widget::do_callback().
Referenced by make_widget_panel(), revert_cb(), set_max_size_cb(), and set_min_size_cb().
void redraw_browser ()
Definition at line 394 of file Fl_Type.cxx.
References Fl_Widget::redraw().
void redraw_overlays ()
Definition at line 1121 of file Fl_Window_Type.cxx.
References Fl_Type::first, and Fl_Type::next.
Referenced by selection_changed().
void resizable_cb (Fl_Light_Button * i, void * v)
Definition at line 880 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::is_menu_item(), Fl_Widget_Type::resizable(), set_modflag(), and Fl_Button::value().
Referenced by make_widget_panel().
void revert_cb (Fl_Button * , void *)
Definition at line 1771 of file Fl_Widget_Type.cxx.
References Fl_Type::label(), and propagate_load().
Referenced by cancel_cb(), and make_widget_panel().
void selection_changed (Fl_Type * p)
Definition at line 1892 of file Fl_Widget_Type.cxx.
References check_redraw_corresponding_parent(), Fl_Type::first, redraw_browser(), redraw_overlays(), Fl_Type::selected, set_cb(), update_sourceview_position(), and Fl_Widget::visible().
Referenced by Widget_Browser::callback(), delete_all(), read_file(), Fl_Type::remove(), select_all_cb(), and select_none_cb().
void set_cb (Fl_Button * , void *)
Definition at line 1753 of file Fl_Widget_Type.cxx.
References Fl_Group::array(), Fl_Widget::changed(), Fl_Group::children(), Fl_Widget::clear_changed(), and Fl_Widget::do_callback().
Referenced by ok_cb(), and selection_changed().
void set_max_size_cb (Fl_Button * , void * v)
Definition at line 1519 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::h(), Fl_Widget_Type::o, propagate_load(), set_modflag(), Fl_Window_Type::sr_max_h, Fl_Window_Type::sr_max_w, and Fl_Widget::w().
Referenced by make_widget_panel().
void set_min_size_cb (Fl_Button * , void * v)
Definition at line 1502 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::h(), Fl_Widget_Type::o, propagate_load(), set_modflag(), Fl_Window_Type::sr_min_h, Fl_Window_Type::sr_min_w, and Fl_Widget::w().
Referenced by make_widget_panel().
void slider_size_cb (Fl_Value_Input * i, void * v)
Definition at line 1536 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_valuator(), Fl_Type::is_window(), Fl_Widget_Type::o, Fl_Widget::parent(), Fl_Widget::redraw(), set_modflag(), Fl_Widget::show(), and Fl_Valuator::value().
Referenced by make_widget_panel().
Fl_Type* sort (Fl_Type * parent)
Definition at line 273 of file Fl_Widget_Type.cxx.
References f, Fl_Type::first, Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::level, Fl_Type::move_before(), Fl_Type::next, Fl_Type::selected, sort(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by sort().
void step_cb (Fl_Value_Input * i, void * v)
Definition at line 1628 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_spinner(), Fl_Type::is_valuator(), Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void subclass_cb (Fl_Input * i, void * v)
Definition at line 1338 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_menu_item(), set_modflag(), Fl_Input_::static_value(), Fl_Widget_Type::subclass(), and Fl_Input_::value().
Referenced by make_widget_panel().
const char* subclassname (Fl_Type * l)
Definition at line 64 of file Fl_Widget_Type.cxx.
References FL_FLOAT_INPUT, FL_INT_INPUT, FL_WINDOW, Fl_Type::is_class(), Fl_Type::is_widget(), Fl_Widget_Type::o, Fl_Widget_Type::subclass(), Fl_Widget::type(), and Fl_Type::type_name().
Referenced by Fl_Widget_Type::write_block_close(), Fl_Widget_Type::write_code1(), Fl_Function_Type::write_code1(), and Fl_Widget_Type::write_static().
void subtype_cb (Fl_Choice * i, void * v)
Definition at line 1703 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Menu_Item::argument(), Fl_Widget::deactivate(), Fl_Type::first, int, Fl_Type::is_spinner(), m, Fl_Menu_::menu(), Fl_Menu_::mvalue(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), Fl_Widget::redraw(), set_modflag(), Fl_Widget_Type::subtypes(), type, Fl_Widget::type(), and Fl_Choice::value().
Referenced by make_widget_panel().
void textcolor_cb (Fl_Button * i, void * v)
Definition at line 1407 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Type::first, FL_BLACK, fl_contrast(), fl_show_colormap(), Fl_Widget::labelcolor(), Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), and Fl_Widget_Type::textstuff().
Referenced by make_widget_panel().
void textfont_cb (Fl_Choice * i, void * v)
Definition at line 1363 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, FL_HELVETICA, Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), Fl_Widget_Type::textstuff(), and Fl_Choice::value().
Referenced by make_widget_panel().
void textsize_cb (Fl_Value_Input * i, void * v)
Definition at line 1385 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Widget_Type::default_size, Fl_Type::first, int, Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), Fl_Widget_Type::textstuff(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void toggle_overlays (Fl_Widget * , void *)
Definition at line 1126 of file Fl_Window_Type.cxx.
Referenced by Fl_Window_Type::handle(), and overlay_cb().
void tooltip_cb (Fl_Input * i, void * v)
Definition at line 486 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget_Type::is_widget(), Fl_Type::next, set_modflag(), Fl_Input_::static_value(), and Fl_Input_::value().
Referenced by make_widget_panel().
void update_sourceview_position ()
Definition at line 2117 of file fluid.cxx.
References Fl_Text_Display::buffer(), Fl_Type::code_position, Fl_Type::code_position_end, Fl_Type::current, Fl_Type::header_position, Fl_Type::header_position_end, Fl_Text_Display::scroll(), sourceview_panel, sv_autoposition, sv_header, sv_source, Fl_Button::value(), Fl_Widget::visible(), and Fl_Widget::visible_r().
Referenced by selection_changed(), update_sourceview_cb(), and update_sourceview_position_cb().
void user_data_cb (Fl_Input * i, void * v)
Definition at line 1271 of file Fl_Widget_Type.cxx.
References c_check(), Fl_Type::first, fl_message(), set_modflag(), Fl_Input_::static_value(), Fl_Widget::user_data(), Fl_Type::user_data(), and Fl_Input_::value().
Referenced by make_widget_panel().
void user_data_type_cb (Fl_Input * i, void * v)
Definition at line 1289 of file Fl_Widget_Type.cxx.
References c_check(), Fl_Type::first, fl_message(), set_modflag(), Fl_Input_::static_value(), Fl_Type::user_data_type(), and Fl_Input_::value().
Referenced by make_widget_panel().
void v_input_cb (Fl_Input * i, void * v)
Definition at line 1318 of file Fl_Widget_Type.cxx.
References c_check(), Fl_Widget_Type::extra_code(), Fl_Type::first, fl_message(), Fl_Widget::label(), set_modflag(), Fl_Input_::static_value(), Fl_Widget::user_data(), and Fl_Input_::value().
Referenced by make_widget_panel().
void value_cb (Fl_Value_Input * i, void * v)
Definition at line 1661 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_button(), Fl_Type::is_menu_item(), Fl_Type::is_spinner(), Fl_Type::is_valuator(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), value, and Fl_Valuator::value().
Referenced by make_widget_panel().
void visible_cb (Fl_Light_Button * i, void * v)
Definition at line 915 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_window(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::parent(), Fl_Type::parent, Fl_Widget_Type::redraw(), set_modflag(), Fl_Widget::show(), Fl_Type::type_name(), value, Fl_Button::value(), and Fl_Widget::visible().
Referenced by make_widget_panel().
void w_cb (Fl_Value_Input * i, void * v)
Definition at line 556 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, gridx, gridy, Fl::h(), Fl_Widget::h(), i, int, Fl_Widget_Type::is_widget(), Fl_Type::next, Fl_Widget::redraw(), Fl_Widget::resize(), set_modflag(), Fl_Valuator::value(), Fl::w(), w, Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by make_widget_panel().
void wc_relative_cb (Fl_Light_Button * i, void * v)
Definition at line 606 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), Fl_Type::next, set_modflag(), Fl_Widget::show(), Fl_Type::type_name(), Fl_Button::value(), and Fl_Widget_Class_Type::wc_relative.
Referenced by make_widget_panel().
void when_button_cb (Fl_Light_Button * i, void * v)
Definition at line 836 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, FL_WHEN_NOT_CHANGED, Fl_Type::is_menu_item(), Fl_Type::next, Fl_Widget_Type::o, set_modflag(), Fl_Button::value(), and Fl_Widget::when().
Referenced by make_widget_panel().
void when_cb (Fl_Choice * i, void * v)
Definition at line 812 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, FL_WHEN_NOT_CHANGED, int, Fl_Type::is_menu_item(), m, Fl_Type::next, Fl_Widget_Type::o, set_modflag(), Fl_Choice::value(), Fl_Widget::when(), and ZERO_ENTRY.
Referenced by make_widget_panel().
void x_cb (Fl_Value_Input * i, void * v)
Definition at line 506 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, gridx, gridy, Fl::h(), Fl_Widget::h(), i, Fl_Widget_Type::is_widget(), Fl_Type::next, Fl_Widget::redraw(), Fl_Widget::resize(), set_modflag(), Fl_Valuator::value(), Fl::w(), Fl_Widget::w(), w, Fl_Widget::window(), and Fl_Widget::y().
Referenced by make_widget_panel().
void y_cb (Fl_Value_Input * i, void * v)
Definition at line 531 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, gridx, gridy, Fl::h(), Fl_Widget::h(), i, int, Fl_Widget_Type::is_widget(), Fl_Type::next, Fl_Widget::redraw(), Fl_Widget::resize(), set_modflag(), Fl_Valuator::value(), Fl::w(), Fl_Widget::w(), w, Fl_Widget::window(), and Fl_Widget::x().
Referenced by make_widget_panel().
Variable Documentation
Fl_Menu_Item boxmenu[]
Definition at line 656 of file Fl_Widget_Type.cxx.
Referenced by make_widget_panel().
Fl_Menu_Item boxmenu1[]
Initial value:
 {
  {"NO_FRAME",          0,0,(void *)FL_NO_BOX},
  {"ROUNDED3D_UPBOX",   0,0,(void *)_FL_ROUND_UP_BOX},
  {"ROUNDED3D_DOWNBOX", 0,0,(void *)_FL_ROUND_DOWN_BOX},
  {"OVAL3D_UPBOX",      0,0,(void *)_FL_ROUND_UP_BOX},
  {"OVAL3D_DOWNBOX",    0,0,(void *)_FL_ROUND_DOWN_BOX},
  {"0",                 0,0,(void *)ZERO_ENTRY},
  {"1",                 0,0,(void *)FL_UP_BOX},
  {"2",                 0,0,(void *)FL_DOWN_BOX},
  {"3",                 0,0,(void *)FL_FLAT_BOX},
  {"4",                 0,0,(void *)FL_BORDER_BOX},
  {"5",                 0,0,(void *)FL_SHADOW_BOX},
  {"6",                 0,0,(void *)FL_FRAME_BOX},
  {"7",                 0,0,(void *)FL_ROUNDED_BOX},
  {"8",                 0,0,(void *)FL_RFLAT_BOX},
  {"9",                 0,0,(void *)FL_RSHADOW_BOX},
  {"10",                0,0,(void *)FL_UP_FRAME},
  {"11",                0,0,(void *)FL_DOWN_FRAME},
{0}}
Definition at line 2652 of file Fl_Widget_Type.cxx.
Fl_Widget_Type* current_widget
Definition at line 306 of file Fl_Widget_Type.cxx.
Referenced by hotspot_cb(), live_mode_cb(), and shortcut_in_cb().
int fdesign_flip
Definition at line 558 of file file.cxx.
Fl_Menu_Item fontmenu[]
Initial value:
 {
{"Helvetica"},
{"Helvetica bold"},
{"Helvetica italic"},
{"Helvetica bold italic"},
{"Courier"},
{"Courier bold"},
{"Courier italic"},
{"Courier bold italic"},
{"Times"},
{"Times bold"},
{"Times italic"},
{"Times bold italic"},
{"Symbol"},
{"Terminal"},
{"Terminal Bold"},
{"Zapf Dingbats"},
{0}}
Definition at line 964 of file Fl_Widget_Type.cxx.
Referenced by make_widget_panel().
int force_parent
Definition at line 50 of file Fl_Widget_Type.cxx.
Referenced by group_cb(), and Fl_Widget_Type::make().
int gridx
Definition at line 98 of file fluid.cxx.
Referenced by grid_cb(), h_cb(), Fl_Window_Type::handle(), Fl_Widget_Class_Type::make(), Fl_Window_Type::make(), Fl_Widget_Type::make(), make_main_window(), Fl_Window_Type::newdx(), Fl_Window_Type::open(), paste_cb(), show_grid_cb(), w_cb(), x_cb(), and y_cb().
int gridy
Definition at line 99 of file fluid.cxx.
Referenced by grid_cb(), h_cb(), Fl_Window_Type::handle(), Fl_Widget_Class_Type::make(), Fl_Window_Type::make(), Fl_Widget_Type::make(), make_main_window(), Fl_Window_Type::newdx(), Fl_Window_Type::open(), paste_cb(), show_grid_cb(), w_cb(), x_cb(), and y_cb().
Fl_Value_Input * h_input
Definition at line 504 of file Fl_Widget_Type.cxx.
const char* i18n_file
Definition at line 652 of file fluid.cxx.
const char* i18n_function
Definition at line 651 of file fluid.cxx.
const char* i18n_include
Definition at line 650 of file fluid.cxx.
const char* i18n_set
Definition at line 653 of file fluid.cxx.
int i18n_type
Definition at line 649 of file fluid.cxx.
Fl_Menu_Item labeltypemenu[]
Initial value:
 {
  {"NORMAL_LABEL",0,0,(void*)0},
  {"SHADOW_LABEL",0,0,(void*)FL_SHADOW_LABEL},
  {"ENGRAVED_LABEL",0,0,(void*)FL_ENGRAVED_LABEL},
  {"EMBOSSED_LABEL",0,0,(void*)FL_EMBOSSED_LABEL},
  {"NO_LABEL",0,0,(void*)(FL_NO_LABEL)},
{0}}
Definition at line 1026 of file Fl_Widget_Type.cxx.
Referenced by make_widget_panel().
void* const LOAD = "LOAD"
Definition at line 307 of file Fl_Widget_Type.cxx.
int pasteoffset
Definition at line 2507 of file Fl_Widget_Type.cxx.
Referenced by Fl_Widget_Type::read_fdesign(), and Fl_Widget_Type::read_property().
double read_version
Definition at line 363 of file file.cxx.
int reading_file
Definition at line 1122 of file factory.cxx.
Referenced by Fl_Widget_Type::make().
const char* ui_find_image_name
Definition at line 246 of file Fluid_Image.cxx.
Referenced by image_browse_cb(), inactive_browse_cb(), and ui_find_image().
int varused
Definition at line 160 of file code.cxx.
Referenced by write_c(), write_cdata(), and write_cstring().
int varused_test
Definition at line 159 of file code.cxx.
Referenced by write_c(), write_cdata(), write_cstring(), and write_h().
Fl_Value_Input * w_input
Definition at line 504 of file Fl_Widget_Type.cxx.
Fl_Menu_Item whenmenu[]
Initial value:
 {
  {"Never",0,0,(void*)ZERO_ENTRY},
  {"Release",0,0,(void*)FL_WHEN_RELEASE},
  {"Changed",0,0,(void*)FL_WHEN_CHANGED},
  {"Enter key",0,0,(void*)FL_WHEN_ENTER_KEY},
  {0}}
Definition at line 795 of file Fl_Widget_Type.cxx.
Referenced by make_widget_panel().
Fl_Value_Input* x_input
Definition at line 504 of file Fl_Widget_Type.cxx.
Fl_Value_Input * y_input
Definition at line 504 of file Fl_Widget_Type.cxx.