SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/Fl_Function_Type.cxx File Reference
Fl_Function_Type.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Preferences.H>
#include <FL/Fl_File_Chooser.H>
#include "Fl_Type.h"
#include <FL/fl_show_input.H>
#include "../src/flstring.h"
#include <stdio.h>
#include <stdlib.h>
#include "function_panel.h"
#include <FL/fl_ask.H>
#include "comments.h"
Functions
void redraw_browser ()
void goto_source_dir ()
void leave_source_dir ()
const char * _q_check (const char *&c, int type)
const char * _c_check (const char *&c, int type)
const char * c_check (const char *c, int type)
const char * subclassname (Fl_Type *)
void write_public (int state)
Variables
int i18n_type
const char * i18n_include
const char * i18n_function
const char * i18n_file
const char * i18n_set
char i18n_program []
int compile_only
Fl_Function_Type Fl_Function_type
Fl_Code_Type Fl_Code_type
Fl_CodeBlock_Type Fl_CodeBlock_type
Fl_Decl_Type Fl_Decl_type
Fl_Data_Type Fl_Data_type
Fl_DeclBlock_Type Fl_DeclBlock_type
Fl_Comment_Type Fl_Comment_type
Fl_Class_Type Fl_Class_type
Fl_Class_Type * current_class
Fl_Widget_Class_Type * current_widget_class
Function Documentation
const char* _c_check (const char *& c, int type)
Definition at line 71 of file Fl_Function_Type.cxx.
References _q_check().
Referenced by c_check().
const char* _q_check (const char *& c, int type)
Definition at line 57 of file Fl_Function_Type.cxx.
Referenced by _c_check().
const char* c_check (const char * c, int type)
Definition at line 121 of file Fl_Function_Type.cxx.
References _c_check().
Referenced by callback_cb(), Fl_Class_Type::open(), Fl_DeclBlock_Type::open(), Fl_Decl_Type::open(), Fl_CodeBlock_Type::open(), Fl_Code_Type::open(), Fl_Function_Type::open(), user_data_cb(), user_data_type_cb(), and v_input_cb().
void goto_source_dir ()
Definition at line 129 of file fluid.cxx.
Referenced by Fluid_Image::find(), Fl_Data_Type::open(), ui_find_image(), write_cb(), and write_strings_cb().
void leave_source_dir ()
Definition at line 146 of file fluid.cxx.
Referenced by Fluid_Image::find(), Fl_Data_Type::open(), ui_find_image(), write_cb(), and write_strings_cb().
void redraw_browser ()
Definition at line 394 of file Fl_Type.cxx.
const char* subclassname (Fl_Type *)
Definition at line 64 of file Fl_Widget_Type.cxx.
Referenced by Fl_Widget_Type::write_block_close(), Fl_Widget_Type::write_code1(), Fl_Function_Type::write_code1(), and Fl_Widget_Type::write_static().
void write_public (int state)
Definition at line 1425 of file Fl_Function_Type.cxx.
References state, write_h(), Fl_Widget_Class_Type::write_public_state, and Fl_Class_Type::write_public_state.
Referenced by Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Data_Type::write_code1(), Fl_Decl_Type::write_code1(), and Fl_Function_Type::write_code1().
Variable Documentation
int compile_only
Definition at line 643 of file fluid.cxx.
Fl_Class_Type* current_class
Definition at line 1423 of file Fl_Function_Type.cxx.
Referenced by Fl_Class_Type::write_code1().
Fl_Widget_Class_Type* current_widget_class
Definition at line 1444 of file Fl_Window_Type.cxx.
Fl_Class_Type Fl_Class_type
Definition at line 1421 of file Fl_Function_Type.cxx.
Fl_Code_Type Fl_Code_type
Definition at line 469 of file Fl_Function_Type.cxx.
Fl_CodeBlock_Type Fl_CodeBlock_type
Definition at line 546 of file Fl_Function_Type.cxx.
Fl_Comment_Type Fl_Comment_type
Definition at line 1226 of file Fl_Function_Type.cxx.
Fl_Data_Type Fl_Data_type
Definition at line 871 of file Fl_Function_Type.cxx.
Fl_Decl_Type Fl_Decl_type
Definition at line 673 of file Fl_Function_Type.cxx.
Fl_DeclBlock_Type Fl_DeclBlock_type
Definition at line 1018 of file Fl_Function_Type.cxx.
Fl_Function_Type Fl_Function_type
Definition at line 244 of file Fl_Function_Type.cxx.
const char* i18n_file
Definition at line 652 of file fluid.cxx.
const char* i18n_function
Definition at line 651 of file fluid.cxx.
const char* i18n_include
Definition at line 650 of file fluid.cxx.
char i18n_program[]
Definition at line 654 of file fluid.cxx.
const char* i18n_set
Definition at line 653 of file fluid.cxx.
int i18n_type
Definition at line 649 of file fluid.cxx.