SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/Fl_get_system_colors.cxx File Reference
Fl_get_system_colors.cxx File Reference
#include <FL/Fl.H>
#include <FL/fl_draw.H>
#include <FL/x.H>
#include <FL/math.h>
#include <FL/fl_utf8.h>
#include "flstring.h"
#include <stdio.h>
#include <stdlib.h>
#include <FL/Fl_Pixmap.H>
#include <FL/Fl_Tiled_Image.H>
#include "tile.xpm"
Defines
#define D1 BORDER_WIDTH
#define D2 (BORDER_WIDTH+BORDER_WIDTH)
Functions
int fl_parse_color (const char *p, uchar &r, uchar &g, uchar &b)
void fl_up_box (int, int, int, int, Fl_Color)
void fl_down_box (int, int, int, int, Fl_Color)
void fl_thin_up_box (int, int, int, int, Fl_Color)
void fl_thin_down_box (int, int, int, int, Fl_Color)
void fl_round_up_box (int, int, int, int, Fl_Color)
void fl_round_down_box (int, int, int, int, Fl_Color)
void fl_up_frame (int, int, int, int, Fl_Color)
void fl_down_frame (int, int, int, int, Fl_Color)
void fl_thin_up_frame (int, int, int, int, Fl_Color)
void fl_thin_down_frame (int, int, int, int, Fl_Color)
Variables
const char * fl_fg = NULL
const char * fl_bg = NULL
const char * fl_bg2 = NULL
Define Documentation
#define D1 BORDER_WIDTH
Definition at line 247 of file Fl_get_system_colors.cxx.
Referenced by Fl::reload_scheme().
#define D2 (BORDER_WIDTH+BORDER_WIDTH)
Definition at line 248 of file Fl_get_system_colors.cxx.
Referenced by Fl::reload_scheme().
Function Documentation
void fl_down_box (int x, int y, int w, int h, Fl_Color c)
Draws a box of type FL_DOWN_BOX
Definition at line 200 of file fl_boxtype.cxx.
References D1, D2, fl_color(), fl_down_frame(), and fl_rectf().
Referenced by Fl::reload_scheme().
void fl_down_frame (int x, int y, int w, int h, Fl_Color)
Draws a frame of type FL_DOWN_FRAME
Definition at line 187 of file fl_boxtype.cxx.
References fl_frame(), and fl_frame2().
Referenced by fl_down_box(), and Fl::reload_scheme().
int fl_parse_color (const char * p, uchar & r, uchar & g, uchar & b)
Definition at line 131 of file Fl_get_system_colors.cxx.
References fl_colormap, fl_display, fl_open_display(), and x.
Referenced by Fl_Pixmap::color_average(), Fl_Pixmap::desaturate(), and fl_draw_pixmap().
void fl_round_down_box (int , int , int , int , Fl_Color)
Definition at line 85 of file fl_round_box.cxx.
References CLOSED, FILL, fl_gray_ramp(), LOWER_RIGHT, and UPPER_LEFT.
Referenced by fl_define_FL_ROUND_UP_BOX(), and Fl::reload_scheme().
void fl_round_up_box (int , int , int , int , Fl_Color)
Definition at line 99 of file fl_round_box.cxx.
References CLOSED, FILL, fl_gray_ramp(), LOWER_RIGHT, and UPPER_LEFT.
Referenced by fl_define_FL_ROUND_UP_BOX(), and Fl::reload_scheme().
void fl_thin_down_box (int x, int y, int w, int h, Fl_Color c)
Draws a box of type FL_THIN_DOWN_BOX
Definition at line 145 of file fl_boxtype.cxx.
References fl_color(), fl_inactive(), fl_rectf(), and fl_thin_down_frame().
Referenced by Fl::reload_scheme().
void fl_thin_down_frame (int x, int y, int w, int h, Fl_Color)
Draws a frame of type FL_THIN_DOWN_FRAME
Definition at line 140 of file fl_boxtype.cxx.
References fl_frame2().
Referenced by fl_thin_down_box(), and Fl::reload_scheme().
void fl_thin_up_box (int x, int y, int w, int h, Fl_Color c)
Draws a box of type FL_THIN_UP_BOX
Definition at line 157 of file fl_boxtype.cxx.
References fl_color(), fl_inactive(), fl_rectf(), and fl_thin_up_frame().
Referenced by Fl::reload_scheme().
void fl_thin_up_frame (int x, int y, int w, int h, Fl_Color)
Draws a frame of type FL_THIN_UP_FRAME
Definition at line 152 of file fl_boxtype.cxx.
References fl_frame2().
Referenced by fl_thin_up_box(), and Fl::reload_scheme().
void fl_up_box (int x, int y, int w, int h, Fl_Color c)
Draws a box of type FL_UP_BOX
Definition at line 180 of file fl_boxtype.cxx.
References D1, D2, fl_color(), fl_inactive(), fl_rectf(), and fl_up_frame().
Referenced by Fl::reload_scheme().
void fl_up_frame (int x, int y, int w, int h, Fl_Color)
Draws a frame of type FL_UP_FRAME
Definition at line 164 of file fl_boxtype.cxx.
References fl_frame(), and fl_frame2().
Referenced by fl_up_box(), and Fl::reload_scheme().
Variable Documentation
const char* fl_bg = NULL
Definition at line 97 of file Fl_get_system_colors.cxx.
Referenced by Fl::get_system_colors().
const char* fl_bg2 = NULL
Definition at line 98 of file Fl_get_system_colors.cxx.
Referenced by Fl::get_system_colors().
const char* fl_fg = NULL
Definition at line 96 of file Fl_get_system_colors.cxx.
Referenced by Fl::get_system_colors().