SfR Fresh Dox - fltk: fltk-1.3.0rc3/FL/Fl_Shared_Image.H File Reference
Fl_Shared_Image.H File Reference
#include "Fl_Image.H"
Classes
class Fl_Shared_Image
Typedefs
typedef Fl_Image *(* Fl_Shared_Handler)(const char *name, uchar *header, int headerlen)
Functions
FL_EXPORT void fl_register_images ()
Register the image formats.
Detailed Description
Fl_Shared_Image class.
Definition in file Fl_Shared_Image.H.
Typedef Documentation
typedef Fl_Image*(* Fl_Shared_Handler)(const char *name, uchar *header, int headerlen)
Definition at line 38 of file Fl_Shared_Image.H.
Function Documentation
FL_EXPORT void fl_register_images ()
Register the image formats.
This function is provided in the fltk_images library and registers all of the "extra" image file formats that are not part of the core FLTK library.
Definition at line 63 of file fl_images_core.cxx.
References Fl_Shared_Image::add_handler().
Referenced by Fl_Help_Dialog::Fl_Help_Dialog(), Fl_File_Icon::load_system_icons(), and main().