SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/fl_labeltype.cxx File Reference
fl_labeltype.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Group.H>
#include <FL/fl_draw.H>
#include <FL/Fl_Image.H>
#include <FL/Fl_Input_.H>
Defines
#define MAX_LABELTYPE 16
Functions
void fl_no_label (const Fl_Label *, int, int, int, int, Fl_Align)
void fl_normal_label (const Fl_Label *o, int X, int Y, int W, int H, Fl_Align align)
void fl_normal_measure (const Fl_Label *o, int &W, int &H)
Define Documentation
#define MAX_LABELTYPE 16
Definition at line 59 of file fl_labeltype.cxx.
Function Documentation
void fl_no_label (const Fl_Label * , int , int , int , int , Fl_Align)
Definition at line 39 of file fl_labeltype.cxx.
void fl_normal_label (const Fl_Label * o, int X, int Y, int W, int H, Fl_Align align)
Definition at line 42 of file fl_labeltype.cxx.
References Fl_Label::color, fl_color(), fl_draw(), fl_font(), Fl_Label::font, Fl_Label::image, Fl_Label::size, and Fl_Label::value.
void fl_normal_measure (const Fl_Label * o, int & W, int & H)
Definition at line 50 of file fl_labeltype.cxx.
References fl_font(), fl_measure(), Fl_Label::font, Fl_Image::h(), Fl_Label::image, Fl_Label::size, Fl_Label::value, and Fl_Image::w().
Referenced by Fl_Label::measure().