SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/Fl_x.cxx File Reference
Fl_x.cxx File Reference
#include <config.h>
#include <FL/Fl.H>
#include <FL/x.H>
#include <FL/Fl_Window.H>
#include <FL/fl_utf8.h>
#include <FL/Fl_Tooltip.H>
#include <FL/fl_draw.H>
#include <stdio.h>
#include <stdlib.h>
#include "flstring.h"
#include <unistd.h>
#include <sys/time.h>
#include <X11/Xmd.h>
#include <X11/Xlocale.h>
#include <X11/Xlib.h>
Classes
struct FD
Defines
#define CONSOLIDATE_MOTION 1
#define POLLIN 1
#define POLLOUT 4
#define POLLERR 8
#define POOR_XIM
Functions
int fl_wait (double time_to_wait)
int fl_ready ()
char * fl_get_font_xfld (int fnum, int size)
void fl_new_ic ()
void fl_reset_spot (void)
void fl_set_spot (int font, int size, int X, int Y, int W, int H, Fl_Window *win)
void fl_set_status (int x, int y, int w, int h)
void fl_init_xim ()
void fl_open_display ()
void fl_open_display (Display *d)
void fl_close_display ()
void fl_sendClientMessage (Window window, Atom message, unsigned long d0, unsigned long d1=0, unsigned long d2=0, unsigned long d3=0, unsigned long d4=0)
int fl_handle (const XEvent &thisevent)
void fl_fix_focus ()
const char * fl_filename_name (const char *name)
Variables
FL_EXPORT Fl_Display_Device * fl_display_device = (Fl_Display_Device*)&fl_xlib_display
Points to the platform's display.
FL_EXPORT Fl_Graphics_Driver * fl_graphics_driver = (Fl_Graphics_Driver*)&fl_xlib_driver
Points to the driver that currently receives all graphics requests.
FL_EXPORT Fl_Surface_Device * fl_surface = (Fl_Surface_Device*)fl_display_device
Points to the surface that currently receives all graphics requests.
void(* fl_lock_function)() = nothing
void(* fl_unlock_function)() = nothing
Display * fl_display
END TIMERS //////////////////////////////////////////////////////////////////////////.
Window fl_message_window = 0
int fl_screen
XVisualInfo * fl_visual
Colormap fl_colormap
XIM fl_xim_im = 0
XIC fl_xim_ic = 0
char fl_is_over_the_spot = 0
Atom fl_XdndAware
Atom fl_XdndSelection
Atom fl_XdndEnter
Atom fl_XdndTypeList
Atom fl_XdndPosition
Atom fl_XdndLeave
Atom fl_XdndDrop
Atom fl_XdndStatus
Atom fl_XdndActionCopy
Atom fl_XdndFinished
Atom fl_XdndURIList
Atom fl_Xatextplainutf
Atom fl_Xatextplain
Atom fl_XaCompoundText
Atom fl_XaUtf8String
Atom fl_XaTextUriList
Atom fl_NET_WM_NAME
Atom fl_NET_WM_ICON_NAME
Fl_Widget * fl_selection_requestor
char * fl_selection_buffer [2]
int fl_selection_length [2]
int fl_selection_buffer_length [2]
char fl_i_own_selection [2] = {0,0}
Window fl_dnd_source_window
Atom * fl_dnd_source_types
Atom fl_dnd_type
Atom fl_dnd_source_action
Atom fl_dnd_action
const XEvent * fl_xevent
ulong fl_event_time
char fl_key_vector [32]
static int py
const int unknown_len = 10
char fl_show_iconic
int fl_background_pixel = -1
int fl_disable_transient_for
Window fl_window
GC fl_gc
Define Documentation
#define CONSOLIDATE_MOTION 1
Definition at line 34 of file Fl_x.cxx.
#define POLLERR 8
Definition at line 80 of file Fl_x.cxx.
Referenced by fl_wait().
#define POLLIN 1
Definition at line 78 of file Fl_x.cxx.
Referenced by fl_wait().
#define POLLOUT 4
Definition at line 79 of file Fl_x.cxx.
Referenced by fl_wait().
#define POOR_XIM
Function Documentation
void fl_close_display ()
get rid of allocated resources
Definition at line 639 of file Fl_x.cxx.
References Fl::remove_fd().
void fl_fix_focus ()
Definition at line 872 of file Fl.cxx.
References Fl::belowmouse(), Fl_Widget::contains(), Fl::e_keysym, Fl::e_number, Fl::e_x, Fl::e_x_root, Fl::e_y, Fl::e_y_root, Fl_Tooltip::enter, FL_Button, FL_ENTER, FL_LEFT_MOUSE, FL_MOVE, FL_RIGHT_MOUSE, fl_xfocus, fl_xmousewin, Fl::focus(), Fl::grab(), Fl_Widget::handle(), Fl::modal(), Fl_Widget::parent(), Fl::pushed(), Fl_Widget::take_focus(), w, Fl_Widget::x(), and Fl_Widget::y().
Referenced by fl_throw_focus(), Fl::grab(), Fl::handle(), Fl_X::make(), and Fl_X::set_xid().
char* fl_get_font_xfld (int fnum, int size)
Definition at line 232 of file fl_font_x.cxx.
References fl_fonts, fl_open_display(), and Fl_Fontdesc::name.
Referenced by fl_new_ic(), and fl_set_spot().
int fl_handle (const XEvent & thisevent)
Definition at line 850 of file Fl_x.cxx.
References Fl::belowmouse(), buffer, Fl_Widget::damage(), data, Fl::e_dy, Fl::e_is_click, Fl::e_keysym, Fl::e_length, Fl::e_number, Fl::e_original_keysym, Fl::e_state, Fl::e_text, Fl::e_x, Fl::e_x_root, Fl::e_y, Fl::e_y_root, Fl::first_window(), FL_BackSpace, FL_Button, FL_BUTTON1, FL_CLOSE, FL_DAMAGE_EXPOSE, FL_Delete, FL_DND_DRAG, FL_DND_ENTER, FL_DND_LEAVE, FL_DND_RELEASE, fl_dnd_source_types, FL_Down, FL_End, FL_ENTER, FL_F, fl_find(), FL_FOCUS, FL_HIDE, FL_Home, fl_init_xim(), FL_Insert, FL_KEYDOWN, FL_KEYUP, FL_KP, FL_KP_Last, FL_Left, FL_Menu, FL_Meta_L, FL_Meta_R, FL_MOUSEWHEEL, FL_MOVE, fl_new_ic(), FL_Page_Down, FL_Page_Up, FL_PASTE, FL_PUSH, FL_RELEASE, FL_Right, fl_sendClientMessage(), fl_set_spot(), FL_SHOW, FL_Tab, FL_UNFOCUS, FL_Up, fl_utf8encode(), fl_XaUtf8String, fl_XdndActionCopy, fl_xid(), H, Fl::handle(), Fl_Widget::handle(), XRectangle::height, Fl_X::i(), i, int, NULL, Fl_Widget::parent(), Fl_Widget::position(), Fl_Window::resize(), Fl_Window::show(), type, unknown_len, Fl_X::wait_for_expose, XRectangle::width, Fl_Widget::window(), Fl_Widget::x(), x, XRectangle::x, xim_im, XKeysymToUcs(), XUtf8LookupString(), Fl_Widget::y(), and XRectangle::y.
void fl_init_xim ()
Definition at line 537 of file Fl_x.cxx.
References fl_new_ic(), NULL, and Fl::warning.
Referenced by fl_handle(), and fl_open_display().
void fl_new_ic ()
Definition at line 360 of file Fl_x.cxx.
References fl_get_font_xfld(), i, and NULL.
Referenced by fl_handle(), and fl_init_xim().
void fl_open_display (Display * d)
Definition at line 587 of file Fl_x.cxx.
References Fl::add_fd(), fl_init_xim(), FL_RGB, num, and Fl::visual().
void fl_open_display ()
Definition at line 572 of file Fl_x.cxx.
References Fl::fatal, and fl_open_display().
Referenced by fl_beep(), Fl_Font_Descriptor::Fl_Font_Descriptor(), fl_get_font_xfld(), fl_open_display(), fl_parse_color(), Fl::get_key(), Fl::get_mouse(), Fl::get_system_colors(), Fl_X::make(), Fl::own_colormap(), Fl::scheme(), Fl::set_fonts(), and Fl::visual().
int fl_ready ()
Check if there is actually a message pending!
Definition at line 264 of file Fl_x.cxx.
References fl_display, and select().
Referenced by Fl::ready().
void fl_sendClientMessage (Window window, Atom message, unsigned long d0, unsigned long d1 = 0, unsigned long d2 = 0, unsigned long d3 = 0, unsigned long d4 = 0)
Definition at line 739 of file Fl_x.cxx.
Referenced by fl_handle().
int fl_wait (double time_to_wait)
This public function handles all events. It wait a maximum of 'time' secods for an event. This version returns 1 if events other than the timeout timer were processed.
Todo:
there is no socket handling in this code whatsoever
Definition at line 210 of file Fl_x.cxx.
References f, fl_display, fl_lock_function, fl_unlock_function, i, int, POLLERR, POLLIN, POLLOUT, and select().
Referenced by Fl::wait().
Variable Documentation
int fl_background_pixel = -1
Definition at line 1533 of file Fl_x.cxx.
Referenced by Fl_X::make_xid(), and Fl_Menu_Window::show().
Colormap fl_colormap
Definition at line 298 of file Fl_x.cxx.
Referenced by fl_parse_color(), fl_read_image(), fl_xpixel(), Fl::free_color(), Fl::own_colormap(), and Fl::visual().
int fl_disable_transient_for
Definition at line 1534 of file Fl_x.cxx.
Display* fl_display
END TIMERS //////////////////////////////////////////////////////////////////////////.
Definition at line 294 of file Fl_x.cxx.
Referenced by Fl_Graphics_Driver::arc(), Fl_Graphics_Driver::circle(), Fl_Xlib_Graphics_Driver::color(), Fl_Window::cursor(), Fl_Xlib_Graphics_Driver::draw(), Fl_Graphics_Driver::end_complex_polygon(), Fl_Graphics_Driver::end_line(), Fl_Graphics_Driver::end_points(), Fl_Graphics_Driver::end_polygon(), Fl_Menu_Window::erase(), Fl::event_key(), fl_beep(), fl_create_bitmask(), fl_parse_color(), fl_read_image(), fl_ready(), fl_restore_clip(), fl_scroll(), fl_wait(), fl_width(), fl_xpixel(), fl_xxfont(), Fl_Overlay_Window::flush(), Fl_Menu_Window::flush(), Fl_Double_Window::flush(), Fl::flush(), Fl::free_color(), Fl::get_key(), Fl::grab(), Fl_Window::handle(), Fl_Window::hide(), Fl_Window::iconize(), Fl_Graphics_Driver::line(), Fl_Graphics_Driver::line_style(), Fl_Graphics_Driver::loop(), Fl::own_colormap(), Fl_Graphics_Driver::pie(), Fl_Graphics_Driver::point(), Fl_Graphics_Driver::polygon(), Fl_Graphics_Driver::rect(), Fl_Graphics_Driver::rectf(), Fl_Double_Window::resize(), Fl_Xlib_Graphics_Driver::rtl_draw(), Fl::scheme(), Fl_Menu_Window::show(), Fl_Window::show(), Fl::visual(), Fl_Graphics_Driver::xyline(), and Fl_Graphics_Driver::yxline().
FL_EXPORT Fl_Display_Device* fl_display_device = (Fl_Display_Device*)&fl_xlib_display
Points to the platform's display.
Definition at line 56 of file Fl_x.cxx.
Referenced by Fl_Display_Device::display_device(), and fl_copy_offscreen().
Atom fl_dnd_action
Definition at line 737 of file Fl_x.cxx.
Atom fl_dnd_source_action
Definition at line 736 of file Fl_x.cxx.
Atom* fl_dnd_source_types
Definition at line 734 of file Fl_x.cxx.
Referenced by fl_handle().
Window fl_dnd_source_window
Definition at line 733 of file Fl_x.cxx.
Atom fl_dnd_type
Definition at line 735 of file Fl_x.cxx.
ulong fl_event_time
Definition at line 780 of file Fl_x.cxx.
Referenced by Fl::grab().
GC fl_gc
Definition at line 1861 of file Fl_x.cxx.
Referenced by Fl_Graphics_Driver::arc(), Fl_Graphics_Driver::circle(), Fl_Graphics_Driver::clip_box(), Fl_Xlib_Graphics_Driver::color(), Fl_Window::draw(), Fl_Xlib_Graphics_Driver::draw(), Fl_Graphics_Driver::end_complex_polygon(), Fl_Graphics_Driver::end_line(), Fl_Graphics_Driver::end_points(), Fl_Graphics_Driver::end_polygon(), fl_brush_action(), fl_draw_pixmap(), fl_GetDC(), Fl_PostScript_File_Device::Fl_PostScript_File_Device(), fl_read_image(), fl_restore_clip(), fl_restore_pen(), fl_save_pen(), fl_scroll(), fl_text_extents(), fl_width(), Fl_Menu_Window::flush(), Fl_Double_Window::flush(), Fl::flush(), Fl_Window::hide(), Fl_Graphics_Driver::line(), Fl_Graphics_Driver::line_style(), Fl_Graphics_Driver::loop(), Fl_Window::make_current(), Fl_Graphics_Driver::not_clipped(), Fl_Graphics_Driver::pie(), Fl_Graphics_Driver::point(), Fl_Graphics_Driver::polygon(), Fl_Paged_Device::print_window_part(), Fl_Graphics_Driver::rect(), Fl_Graphics_Driver::rectf(), Fl_Xlib_Graphics_Driver::rtl_draw(), Fl_Graphics_Driver::xyline(), and Fl_Graphics_Driver::yxline().
FL_EXPORT Fl_Graphics_Driver* fl_graphics_driver = (Fl_Graphics_Driver*)&fl_xlib_driver
Points to the driver that currently receives all graphics requests.
Definition at line 57 of file Fl_x.cxx.
Referenced by Fl_Pixmap::draw(), Fl_RGB_Image::draw(), Fl_Bitmap::draw(), fl_arc(), fl_begin_complex_polygon(), fl_begin_line(), fl_begin_loop(), fl_begin_points(), fl_begin_polygon(), fl_circle(), fl_clip_box(), fl_color(), fl_copy_offscreen(), fl_curve(), fl_draw(), fl_draw_image(), fl_draw_image_mono(), fl_draw_pixmap(), fl_end_complex_polygon(), fl_end_line(), fl_end_loop(), fl_end_points(), fl_end_polygon(), fl_font(), fl_gap(), fl_line(), fl_line_style(), fl_loop(), fl_not_clipped(), fl_pie(), fl_point(), fl_polygon(), fl_pop_clip(), fl_push_clip(), fl_push_no_clip(), fl_rect(), fl_rectf(), fl_rtl_draw(), fl_transformed_vertex(), fl_vertex(), fl_xyline(), fl_yxline(), and Fl_Surface_Device::set_current().
char fl_i_own_selection[2] = {0,0}
Definition at line 712 of file Fl_x.cxx.
char fl_is_over_the_spot = 0
Definition at line 301 of file Fl_x.cxx.
char fl_key_vector[32]
Definition at line 782 of file Fl_x.cxx.
Referenced by Fl::event_key(), and Fl::get_key().
void(* fl_lock_function)() = nothing
Definition at line 204 of file Fl_x.cxx.
Window fl_message_window = 0
Definition at line 295 of file Fl_x.cxx.
Referenced by fl_destroy_xft_draw().
Atom fl_NET_WM_ICON_NAME
Definition at line 328 of file Fl_x.cxx.
Atom fl_NET_WM_NAME
Definition at line 327 of file Fl_x.cxx.
int fl_screen
Definition at line 296 of file Fl_x.cxx.
Referenced by Fl_Window::cursor(), fl_read_image(), Fl_Window::iconize(), Fl::own_colormap(), and Fl::visual().
char* fl_selection_buffer[2]
Definition at line 709 of file Fl_x.cxx.
Referenced by FLDataObject::GetData().
int fl_selection_buffer_length[2]
Definition at line 711 of file Fl_x.cxx.
int fl_selection_length[2]
Definition at line 710 of file Fl_x.cxx.
Referenced by FLDataObject::GetData().
Fl_Widget* fl_selection_requestor
Definition at line 708 of file Fl_x.cxx.
char fl_show_iconic
Definition at line 1532 of file Fl_x.cxx.
Referenced by Fl_Window::iconize(), and Fl_X::make().
FL_EXPORT Fl_Surface_Device* fl_surface = (Fl_Surface_Device*)fl_display_device
Points to the surface that currently receives all graphics requests.
Definition at line 58 of file Fl_x.cxx.
Referenced by Fl_Surface_Device::set_current(), and Fl_Surface_Device::surface().
void(* fl_unlock_function)() = nothing
Definition at line 205 of file Fl_x.cxx.
XVisualInfo* fl_visual
Definition at line 297 of file Fl_x.cxx.
Referenced by fl_read_image(), fl_rectf(), fl_xpixel(), Fl::own_colormap(), and Fl::visual().
Window fl_window
Definition at line 1859 of file Fl_x.cxx.
Referenced by Fl_Graphics_Driver::arc(), Fl_Graphics_Driver::circle(), Fl_Xlib_Graphics_Driver::draw(), Fl_Graphics_Driver::end_complex_polygon(), Fl_Graphics_Driver::end_line(), Fl_Graphics_Driver::end_points(), Fl_Graphics_Driver::end_polygon(), fl_create_bitmask(), fl_read_image(), fl_restore_clip(), fl_scroll(), Fl_Menu_Window::flush(), Fl_Double_Window::flush(), Fl_Window::hide(), Fl_Graphics_Driver::line(), Fl_Graphics_Driver::loop(), Fl_Window::make_current(), Fl_Graphics_Driver::pie(), Fl_Graphics_Driver::point(), Fl_Graphics_Driver::polygon(), Fl_Graphics_Driver::rect(), Fl_Graphics_Driver::rectf(), Fl_Xlib_Graphics_Driver::rtl_draw(), Fl_Graphics_Driver::xyline(), and Fl_Graphics_Driver::yxline().
Atom fl_XaCompoundText
Definition at line 324 of file Fl_x.cxx.
Atom fl_Xatextplain
Definition at line 322 of file Fl_x.cxx.
Atom fl_Xatextplainutf
Definition at line 321 of file Fl_x.cxx.
Atom fl_XaTextUriList
Definition at line 326 of file Fl_x.cxx.
Atom fl_XaUtf8String
Definition at line 325 of file Fl_x.cxx.
Referenced by fl_handle().
Atom fl_XdndActionCopy
Definition at line 317 of file Fl_x.cxx.
Referenced by fl_handle().
Atom fl_XdndAware
Definition at line 309 of file Fl_x.cxx.
Atom fl_XdndDrop
Definition at line 315 of file Fl_x.cxx.
Atom fl_XdndEnter
Definition at line 311 of file Fl_x.cxx.
Atom fl_XdndFinished
Definition at line 318 of file Fl_x.cxx.
Atom fl_XdndLeave
Definition at line 314 of file Fl_x.cxx.
Atom fl_XdndPosition
Definition at line 313 of file Fl_x.cxx.
Atom fl_XdndSelection
Definition at line 310 of file Fl_x.cxx.
Atom fl_XdndStatus
Definition at line 316 of file Fl_x.cxx.
Atom fl_XdndTypeList
Definition at line 312 of file Fl_x.cxx.
Atom fl_XdndURIList
Definition at line 320 of file Fl_x.cxx.
const XEvent* fl_xevent
Definition at line 779 of file Fl_x.cxx.
XIC fl_xim_ic = 0
Definition at line 300 of file Fl_x.cxx.
Referenced by fl_set_spot().
XIM fl_xim_im = 0
Definition at line 299 of file Fl_x.cxx.
int py
Definition at line 786 of file Fl_x.cxx.
const int unknown_len = 10
Definition at line 827 of file Fl_x.cxx.
Referenced by fl_handle().