SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/Fl_Type.cxx File Reference
Fl_Type.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Browser_.H>
#include <FL/fl_draw.H>
#include <stdlib.h>
#include "../src/flstring.h"
#include <stdio.h>
#include "Fl_Type.h"
#include "undo.h"
#include <FL/Fl_Pixmap.H>
#include "pixmaps/lock.xpm"
#include "pixmaps/protected.xpm"
#include "pixmaps/flWindow.xpm"
#include "pixmaps/flButton.xpm"
#include "pixmaps/flCheckButton.xpm"
#include "pixmaps/flRoundButton.xpm"
#include "pixmaps/flBox.xpm"
#include "pixmaps/flGroup.xpm"
#include "pixmaps/flFunction.xpm"
#include "pixmaps/flCode.xpm"
#include "pixmaps/flCodeBlock.xpm"
#include "pixmaps/flComment.xpm"
#include "pixmaps/flData.xpm"
#include "pixmaps/flDeclaration.xpm"
#include "pixmaps/flDeclarationBlock.xpm"
#include "pixmaps/flClass.xpm"
#include "pixmaps/flTabs.xpm"
#include "pixmaps/flInput.xpm"
#include "pixmaps/flChoice.xpm"
#include "pixmaps/flMenuitem.xpm"
#include "pixmaps/flMenubar.xpm"
#include "pixmaps/flSubmenu.xpm"
#include "pixmaps/flScroll.xpm"
#include "pixmaps/flTile.xpm"
#include "pixmaps/flWizard.xpm"
#include "pixmaps/flPack.xpm"
#include "pixmaps/flReturnButton.xpm"
#include "pixmaps/flLightButton.xpm"
#include "pixmaps/flRepeatButton.xpm"
#include "pixmaps/flMenuButton.xpm"
#include "pixmaps/flOutput.xpm"
#include "pixmaps/flTextDisplay.xpm"
#include "pixmaps/flTextEdit.xpm"
#include "pixmaps/flFileInput.xpm"
#include "pixmaps/flBrowser.xpm"
#include "pixmaps/flCheckBrowser.xpm"
#include "pixmaps/flFileBrowser.xpm"
#include "pixmaps/flClock.xpm"
#include "pixmaps/flHelp.xpm"
#include "pixmaps/flProgress.xpm"
#include "pixmaps/flSlider.xpm"
#include "pixmaps/flScrollBar.xpm"
#include "pixmaps/flValueSlider.xpm"
#include "pixmaps/flAdjuster.xpm"
#include "pixmaps/flCounter.xpm"
#include "pixmaps/flDial.xpm"
#include "pixmaps/flRoller.xpm"
#include "pixmaps/flValueInput.xpm"
#include "pixmaps/flValueOutput.xpm"
#include "pixmaps/flSpinner.xpm"
#include "pixmaps/flWidgetClass.xpm"
#include "pixmaps/flTree.xpm"
#include "pixmaps/flTable.xpm"
Classes
class Widget_Browser
Functions
Fl_Widget * make_widget_browser (int x, int y, int w, int h)
void select (Fl_Type *o, int v)
void select_only (Fl_Type *o)
void deselect ()
const char * subclassname (Fl_Type *)
void redraw_browser ()
int storestring (const char *n, const char *&p, int nostrip)
void select_all_cb (Fl_Widget *, void *)
void select_none_cb (Fl_Widget *, void *)
void delete_all (int selected_only)
void earlier_cb (Fl_Widget *, void *)
void later_cb (Fl_Widget *, void *)
int has_toplevel_function (const char *rtype, const char *sig)
void reveal_in_browser (Fl_Type *t)
Variables
Fl_Pixmap * pixmap []
int show_comments
Fl_Type * in_this_only
Function Documentation
void delete_all (int selected_only)
Definition at line 757 of file Fl_Type.cxx.
References f, include_H_from_C, Fl_Type::next, Fl_Type::selected, selection_changed(), and use_FL_COMMAND.
Referenced by cut_cb(), delete_cb(), new_cb(), and read_file().
void deselect ()
Definition at line 213 of file Fl_Type.cxx.
References Fl_Browser_::deselect().
Referenced by Fl_Tree::deselect(), Fl_Tree_Item::deselect_all(), Fl_Window_Type::handle(), read_file(), and Fl_Tree_Item::select_toggle().
void earlier_cb (Fl_Widget * , void *)
Definition at line 796 of file Fl_Type.cxx.
References f, Fl_Type::level, Fl_Type::move_before(), Fl_Type::next, Fl_Type::prev, Fl_Type::selected, and set_modflag().
int has_toplevel_function (const char * rtype, const char * sig)
Return 1 if the list contains a function with the given signature at the top level
Definition at line 912 of file Fl_Type.cxx.
References Fl_Function_Type::has_signature(), Fl_Type::is_in_class(), Fl_Type::next, and Fl_Type::type_name().
Referenced by Fl_Widget_Type::write_static().
void later_cb (Fl_Widget * , void *)
Definition at line 814 of file Fl_Type.cxx.
References f, Fl_Type::level, Fl_Type::move_before(), Fl_Type::next, Fl_Type::prev, Fl_Type::selected, and set_modflag().
Fl_Widget* make_widget_browser (int x, int y, int w, int h)
Definition at line 200 of file Fl_Type.cxx.
References Fl_Type::Widget_Browser.
Referenced by make_main_window().
void redraw_browser ()
Definition at line 394 of file Fl_Type.cxx.
References Fl_Widget::redraw().
Referenced by name_public_cb(), name_public_member_cb(), Fl_Class_Type::open(), Fl_DeclBlock_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_Function_Type::open(), reveal_in_browser(), selection_changed(), and Fl_Widget_Type::subclass().
void reveal_in_browser (Fl_Type * t)
Make sure that the given item is visible in the browser by opening all parent groups and moving the item into the visible space.
Definition at line 974 of file Fl_Type.cxx.
References Fl_Browser_::display(), Fl_Type::open_, Fl_Type::parent, and redraw_browser().
Referenced by Fl_Window_Type::handle().
void select (Fl_Type * o, int v)
Definition at line 204 of file Fl_Type.cxx.
References Fl_Browser_::select().
Referenced by DataReady::CheckData(), DataReady::DataReadyThread(), fl_ready(), fl_scandir(), fl_wait(), Fl_Window_Type::handle(), Fl_Text_Buffer::loadfile(), Fl_Type::read_property(), Fl_Tree::select(), Fl_Tree_Item::select_all(), and Fl_Tree_Item::select_toggle().
void select_all_cb (Fl_Widget * , void *)
Definition at line 699 of file Fl_Type.cxx.
References Fl_Type::current, in_this_only, Fl_Type::level, Fl_Type::new_selected, Fl_Type::next, Fl_Type::parent, Fl_Browser_::select(), and selection_changed().
void select_none_cb (Fl_Widget * , void *)
Definition at line 723 of file Fl_Type.cxx.
References Fl_Type::current, in_this_only, Fl_Type::level, Fl_Type::new_selected, Fl_Type::next, Fl_Type::parent, Fl_Browser_::select(), and selection_changed().
void select_only (Fl_Type * o)
Definition at line 209 of file Fl_Type.cxx.
References Fl_Browser_::select_only().
Referenced by cut_cb(), delete_cb(), and type_make_cb().
int storestring (const char * n, const char *& p, int nostrip)
Definition at line 597 of file Fl_Type.cxx.
References length, set_modflag(), strlcpy, and undo_checkpoint().
Referenced by Fl_Type::callback(), Fl_Type::comment(), Fl_Widget_Type::extra_code(), Fl_Widget_Type::image_name(), Fl_Widget_Type::inactive_name(), Fl_Type::label(), Fl_Type::name(), Fl_Class_Type::open(), Fl_DeclBlock_Type::open(), Fl_CodeBlock_Type::open(), Fl_Function_Type::open(), Fl_Window_Type::read_property(), Fl_Class_Type::read_property(), Fl_DeclBlock_Type::read_property(), Fl_Data_Type::read_property(), Fl_CodeBlock_Type::read_property(), Fl_Function_Type::read_property(), Fl_Widget_Type::subclass(), Fl_Widget_Type::tooltip(), Fl_Type::user_data(), Fl_Type::user_data_type(), and xclass_cb().
const char* subclassname (Fl_Type *)
Definition at line 64 of file Fl_Widget_Type.cxx.
References FL_FLOAT_INPUT, FL_INT_INPUT, FL_WINDOW, Fl_Type::is_class(), Fl_Type::is_widget(), Fl_Widget_Type::o, Fl_Widget_Type::subclass(), Fl_Widget::type(), and Fl_Type::type_name().
Variable Documentation
Fl_Type* in_this_only
Definition at line 697 of file Fl_Type.cxx.
Referenced by select_all_cb(), and select_none_cb().
Fl_Pixmap* pixmap[]
Initial value:
 { 0, &window_pixmap, &button_pixmap, &checkbutton_pixmap, &roundbutton_pixmap,
 &box_pixmap, &group_pixmap, &function_pixmap, &code_pixmap, &codeblock_pixmap, &declaration_pixmap,
 &declarationblock_pixmap, &class_pixmap, &tabs_pixmap, &input_pixmap, &choice_pixmap,
 &menuitem_pixmap, &menubar_pixmap, &submenu_pixmap, &scroll_pixmap, &tile_pixmap, &wizard_pixmap,
 &pack_pixmap, &returnbutton_pixmap, &lightbutton_pixmap, &repeatbutton_pixmap, &menubutton_pixmap,
 &output_pixmap, &textdisplay_pixmap, &textedit_pixmap, &fileinput_pixmap, &browser_pixmap,
 &checkbrowser_pixmap, &filebrowser_pixmap, &clock_pixmap, &help_pixmap, &progress_pixmap,
 &slider_pixmap, &scrollbar_pixmap, &valueslider_pixmap, &adjuster_pixmap, &counter_pixmap,
 &dial_pixmap, &roller_pixmap, &valueinput_pixmap, &valueoutput_pixmap, &comment_pixmap,
 &spinner_pixmap, &widgetclass_pixmap, &data_pixmap, &tree_pixmap, &table_pixmap }
Definition at line 163 of file Fl_Type.cxx.
int show_comments
Definition at line 102 of file fluid.cxx.