SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/Fl_Chart.cxx File Reference
Fl_Chart.cxx File Reference
#include <FL/math.h>
#include <FL/Fl.H>
#include <FL/Fl_Chart.H>
#include <FL/fl_draw.H>
#include "flstring.h"
#include <stdlib.h>
Defines
#define ARCINC (2.0*M_PI/360.0)
#define FL_CHART_BOXTYPE FL_BORDER_BOX
#define FL_CHART_COL1 FL_COL1
#define FL_CHART_LCOL FL_LCOL
#define FL_CHART_ALIGN FL_ALIGN_BOTTOM
Functions
void fl_rectbound (int x, int y, int w, int h, Fl_Color color)
Define Documentation
#define ARCINC (2.0*M_PI/360.0)
Definition at line 35 of file Fl_Chart.cxx.
#define FL_CHART_ALIGN FL_ALIGN_BOTTOM
Definition at line 286 of file Fl_Chart.cxx.
#define FL_CHART_BOXTYPE FL_BORDER_BOX
Definition at line 283 of file Fl_Chart.cxx.
#define FL_CHART_COL1 FL_COL1
Definition at line 284 of file Fl_Chart.cxx.
#define FL_CHART_LCOL FL_LCOL
Definition at line 285 of file Fl_Chart.cxx.
Function Documentation
void fl_rectbound (int x, int y, int w, int h, Fl_Color bgcolor)
Draws a bounded rectangle with a given position, size and color. Equivalent to drawing a box of type FL_BORDER_BOX.
Definition at line 233 of file fl_boxtype.cxx.
References FL_BLACK, fl_color(), fl_inactive(), fl_rect(), and fl_rectf().