SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/Fl_Menu_Type.cxx File Reference
Fl_Menu_Type.cxx File Reference
#include <FL/Fl.H>
#include "Fl_Widget_Type.h"
#include "alignment_panel.h"
#include <FL/fl_message.H>
#include <FL/Fl_Menu_.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Text_Display.H>
#include "../src/flstring.h"
#include <stdio.h>
#include <stdlib.h>
#include "Fluid_Image.h"
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Output.H>
#include "Shortcut_Button.h"
#include <FL/fl_draw.H>
Functions
int is_name (const char *c)
const char * array_name (Fl_Widget_Type *o)
int isdeclare (const char *c)
void shortcut_in_cb (Shortcut_Button *i, void *v)
Variables
Fl_Menu_Item menu_item_type_menu []
int reading_file
int force_parent
int i18n_type
const char * i18n_include
const char * i18n_function
const char * i18n_file
const char * i18n_set
Fl_Menu_Item_Type Fl_Menu_Item_type
Fl_Submenu_Type Fl_Submenu_type
Fl_Menu_Item button_type_menu []
Fl_Menu_Button_Type Fl_Menu_Button_type
Fl_Menu_Item dummymenu [] = {{"CHOICE"},{0}}
Fl_Choice_Type Fl_Choice_type
Fl_Input_Choice_Type Fl_Input_Choice_type
Fl_Menu_Bar_Type Fl_Menu_Bar_type
Function Documentation
const char* array_name (Fl_Widget_Type * o)
Definition at line 1937 of file Fl_Widget_Type.cxx.
References buffer, Fl_Type::class_name(), Fl_Type::name(), num, Fl_Type::prev, and snprintf.
Referenced by Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
int is_name (const char * c)
Definition at line 1929 of file Fl_Widget_Type.cxx.
Referenced by Fl_Type::callback_name(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Menu_Item_Type::write_item(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
int isdeclare (const char * c)
Definition at line 1967 of file Fl_Widget_Type.cxx.
Referenced by Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Widget_Type::write_extra_code(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
void shortcut_in_cb (Shortcut_Button * i, void * v)
Definition at line 612 of file Fl_Menu_Type.cxx.
References b, current_widget, Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_button(), Fl_Type::is_input(), Fl_Type::is_text_display(), Fl_Type::is_value_input(), LOAD, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), Fl_Text_Display::shortcut(), Fl_Value_Input::shortcut(), Fl_Input_::shortcut(), Fl_Button::shortcut(), Fl_Widget::show(), and Shortcut_Button::svalue.
Referenced by make_widget_panel().
Variable Documentation
Fl_Menu_Item button_type_menu[]
Initial value:
 {
  {"normal",0,0,(void*)0},
  {"popup1",0,0,(void*)Fl_Menu_Button::POPUP1},
  {"popup2",0,0,(void*)Fl_Menu_Button::POPUP2},
  {"popup3",0,0,(void*)Fl_Menu_Button::POPUP3},
  {"popup12",0,0,(void*)Fl_Menu_Button::POPUP12},
  {"popup23",0,0,(void*)Fl_Menu_Button::POPUP23},
  {"popup13",0,0,(void*)Fl_Menu_Button::POPUP13},
  {"popup123",0,0,(void*)Fl_Menu_Button::POPUP123},
  {0}}
Definition at line 510 of file Fl_Menu_Type.cxx.
Fl_Menu_Item dummymenu[] = {{"CHOICE"},{0}}
Definition at line 525 of file Fl_Menu_Type.cxx.
Fl_Choice_Type Fl_Choice_type
Definition at line 527 of file Fl_Menu_Type.cxx.
Fl_Input_Choice_Type Fl_Input_Choice_type
Definition at line 529 of file Fl_Menu_Type.cxx.
Fl_Menu_Bar_Type Fl_Menu_Bar_type
Definition at line 561 of file Fl_Menu_Type.cxx.
Fl_Menu_Button_Type Fl_Menu_Button_type
Definition at line 521 of file Fl_Menu_Type.cxx.
Fl_Menu_Item_Type Fl_Menu_Item_type
Definition at line 142 of file Fl_Menu_Type.cxx.
Fl_Submenu_Type Fl_Submenu_type
Definition at line 143 of file Fl_Menu_Type.cxx.
int force_parent
Definition at line 50 of file Fl_Widget_Type.cxx.
const char* i18n_file
Definition at line 652 of file fluid.cxx.
const char* i18n_function
Definition at line 651 of file fluid.cxx.
const char* i18n_include
Definition at line 650 of file fluid.cxx.
const char* i18n_set
Definition at line 653 of file fluid.cxx.
int i18n_type
Definition at line 649 of file fluid.cxx.
Fl_Menu_Item menu_item_type_menu[]
Initial value:
 {
  {"Normal",0,0,(void*)0},
  {"Toggle",0,0,(void*)FL_MENU_BOX},
  {"Radio",0,0,(void*)FL_MENU_RADIO},
  {0}}
Definition at line 46 of file Fl_Menu_Type.cxx.
Referenced by Fl_Menu_Item_Type::subtypes().
int reading_file
Definition at line 1122 of file factory.cxx.