SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/fl_plastic.cxx File Reference
fl_plastic.cxx File Reference
#include <FL/Fl.H>
#include <FL/fl_draw.H>
#include "flstring.h"
Defines
#define USE_OLD_PLASTIC_COLOR
Functions
uchar * fl_gray_ramp ()
Fl_Color shade_color (uchar gc, Fl_Color bc)
void fl_internal_boxtype (Fl_Boxtype, Fl_Box_Draw_F *)
Fl_Boxtype fl_define_FL_PLASTIC_UP_BOX ()
Define Documentation
#define USE_OLD_PLASTIC_COLOR
Definition at line 45 of file fl_plastic.cxx.
Function Documentation
Fl_Boxtype fl_define_FL_PLASTIC_UP_BOX ()
Definition at line 365 of file fl_plastic.cxx.
References _FL_PLASTIC_DOWN_BOX, _FL_PLASTIC_DOWN_FRAME, _FL_PLASTIC_ROUND_DOWN_BOX, _FL_PLASTIC_ROUND_UP_BOX, _FL_PLASTIC_THIN_DOWN_BOX, _FL_PLASTIC_THIN_UP_BOX, _FL_PLASTIC_UP_BOX, _FL_PLASTIC_UP_FRAME, and fl_internal_boxtype().
uchar* fl_gray_ramp ()
Definition at line 66 of file fl_boxtype.cxx.
void fl_internal_boxtype (Fl_Boxtype t, Fl_Box_Draw_F * f)
Sets the drawing function for a given box type.
Parameters:
[in] t box type
[in] f box drawing function
Definition at line 363 of file fl_boxtype.cxx.
Fl_Color shade_color (uchar gc, Fl_Color bc) [inline]
Definition at line 49 of file fl_plastic.cxx.
References Fl::draw_box_active(), f, fl_color_average(), FL_GRAY, fl_rgb_color(), Fl::get_color(), green, and red.