SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/Fl_Group_Type.cxx File Reference
Fl_Group_Type.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Table.H>
#include <FL/fl_message.H>
#include "Fl_Widget_Type.h"
#include "../src/flstring.h"
#include <stdio.h>
#include <FL/Fl_Scroll.H>
Classes
class Fluid_Table
Functions
void fix_group_size (Fl_Type *tt)
void group_cb (Fl_Widget *, void *)
void ungroup_cb (Fl_Widget *, void *)
Variables
Fl_Group_Type Fl_Group_type
int force_parent
const char pack_type_name [] = "Fl_Pack"
Fl_Menu_Item pack_type_menu []
Fl_Pack_Type Fl_Pack_type
const char table_type_name [] = "Fl_Table"
Fl_Table_Type Fl_Table_type
const char tabs_type_name [] = "Fl_Tabs"
Fl_Tabs_Type Fl_Tabs_type
const char wizard_type_name [] = "Fl_Wizard"
Fl_Wizard_Type Fl_Wizard_type
const char scroll_type_name [] = "Fl_Scroll"
Fl_Menu_Item scroll_type_menu []
Fl_Scroll_Type Fl_Scroll_type
const char tile_type_name [] = "Fl_Tile"
Fl_Tile_Type Fl_Tile_type
Function Documentation
void fix_group_size (Fl_Type * tt)
Definition at line 52 of file Fl_Group_Type.cxx.
References b, Fl_Widget::h(), Fl_Type::is_group(), Fl_Type::level, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::resize(), Fl_Widget::w(), x, Fl_Widget::x(), y, and Fl_Widget::y().
Referenced by group_cb(), and Fl_Window_Type::moveallchildren().
void group_cb (Fl_Widget * , void *)
Definition at line 72 of file Fl_Group_Type.cxx.
References Fl_Type::add(), Fl_Type::current, Fl_Type::first, fix_group_size(), fl_message(), force_parent, Fl_Widget::h(), Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::level, Fl_Group_Type::make(), Fl_Type::move_before(), Fl_Widget_Type::o, Fl_Type::parent, Fl_Type::remove(), Fl_Widget::resize(), Fl_Type::selected, Fl_Type::type_name(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
void ungroup_cb (Fl_Widget * , void *)
Definition at line 95 of file Fl_Group_Type.cxx.
References Fl_Type::current, fl_message(), Fl_Type::insert(), Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::level, Fl_Type::next, Fl_Type::parent, Fl_Type::remove(), Fl_Type::selected, and Fl_Type::type_name().
Variable Documentation
Fl_Group_Type Fl_Group_type
Definition at line 46 of file Fl_Group_Type.cxx.
Fl_Pack_Type Fl_Pack_type
Definition at line 146 of file Fl_Group_Type.cxx.
Fl_Scroll_Type Fl_Scroll_type
Definition at line 428 of file Fl_Group_Type.cxx.
Fl_Table_Type Fl_Table_type
Definition at line 226 of file Fl_Group_Type.cxx.
Fl_Tabs_Type Fl_Tabs_type
Definition at line 243 of file Fl_Group_Type.cxx.
Fl_Tile_Type Fl_Tile_type
Definition at line 443 of file Fl_Group_Type.cxx.
Fl_Wizard_Type Fl_Wizard_type
Definition at line 274 of file Fl_Group_Type.cxx.
int force_parent
Definition at line 50 of file Fl_Widget_Type.cxx.
Referenced by group_cb(), and Fl_Widget_Type::make().
Fl_Menu_Item pack_type_menu[]
Initial value:
 {
  {"HORIZONTAL", 0, 0, (void*)Fl_Pack::HORIZONTAL},
  {"VERTICAL", 0, 0, (void*)Fl_Pack::VERTICAL},
  {0}}
Definition at line 141 of file Fl_Group_Type.cxx.
const char pack_type_name[] = "Fl_Pack"
Definition at line 139 of file Fl_Group_Type.cxx.
Referenced by Fl_Pack_Type::type_name().
Fl_Menu_Item scroll_type_menu[]
Initial value:
 {
  {"BOTH", 0, 0, 0},
  {"HORIZONTAL", 0, 0, (void*)Fl_Scroll::HORIZONTAL},
  {"VERTICAL", 0, 0, (void*)Fl_Scroll::VERTICAL},
  {"HORIZONTAL_ALWAYS", 0, 0, (void*)Fl_Scroll::HORIZONTAL_ALWAYS},
  {"VERTICAL_ALWAYS", 0, 0, (void*)Fl_Scroll::VERTICAL_ALWAYS},
  {"BOTH_ALWAYS", 0, 0, (void*)Fl_Scroll::BOTH_ALWAYS},
  {0}}
Definition at line 419 of file Fl_Group_Type.cxx.
const char scroll_type_name[] = "Fl_Scroll"
Definition at line 401 of file Fl_Group_Type.cxx.
Referenced by Fl_Scroll_Type::type_name().
const char table_type_name[] = "Fl_Table"
Definition at line 224 of file Fl_Group_Type.cxx.
Referenced by Fl_Table_Type::type_name().
const char tabs_type_name[] = "Fl_Tabs"
Definition at line 235 of file Fl_Group_Type.cxx.
Referenced by color_cb(), and Fl_Tabs_Type::type_name().
const char tile_type_name[] = "Fl_Tile"
Definition at line 441 of file Fl_Group_Type.cxx.
Referenced by Fl_Tile_Type::type_name().
const char wizard_type_name[] = "Fl_Wizard"
Definition at line 266 of file Fl_Group_Type.cxx.
Referenced by Fl_Wizard_Type::type_name().