SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/Fl_Widget.cxx File Reference
Fl_Widget.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Tooltip.H>
#include <FL/fl_draw.H>
#include <stdlib.h>
#include "flstring.h"
Functions
void fl_throw_focus (Fl_Widget *)
Variables
const int QUEUE_SIZE = 20
static int obj_tail
Fl_Fontsize FL_NORMAL_SIZE = 14
normal font size
Function Documentation
void fl_throw_focus (Fl_Widget *)
Definition at line 934 of file Fl.cxx.
References Fl::belowmouse(), Fl_Widget::contains(), Fl_Tooltip::current(), Fl_Tooltip::exit, fl_fix_focus(), Fl::focus(), and Fl::pushed().
Referenced by Fl_Widget::deactivate(), Fl_Widget::hide(), Fl_Window::hide(), and Fl_Widget::~Fl_Widget().
Variable Documentation
Fl_Fontsize FL_NORMAL_SIZE = 14
normal font size
Default font size for widgets
Definition at line 111 of file Fl_Widget.cxx.
Referenced by Fl_Menu_Item::draw(), Fl_Browser_::Fl_Browser_(), Fl_Counter::Fl_Counter(), Fl_Input_::Fl_Input_(), Fl_Menu_::Fl_Menu_(), Fl_Text_Display::Fl_Text_Display(), Fl_Tree_Prefs::Fl_Tree_Prefs(), Fl_Value_Output::Fl_Value_Output(), Fl_Widget::Fl_Widget(), and Fl_Menu_Item::measure().
int obj_tail
Definition at line 46 of file Fl_Widget.cxx.
Referenced by Fl_Widget::default_callback(), and Fl::readqueue().
const int QUEUE_SIZE = 20
Definition at line 43 of file Fl_Widget.cxx.
Referenced by Fl_Widget::default_callback(), and Fl::readqueue().