SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/fl_gtk.cxx File Reference
fl_gtk.cxx File Reference
#include <FL/Fl.H>
#include <FL/fl_draw.H>
Enumerations
enum { UPPER_LEFT, LOWER_RIGHT, CLOSED, FILL }
Functions
void fl_internal_boxtype (Fl_Boxtype, Fl_Box_Draw_F *)
void gtk_round_up_box (int x, int y, int w, int h, Fl_Color c)
void gtk_round_down_box (int x, int y, int w, int h, Fl_Color c)
Fl_Boxtype fl_define_FL_GTK_UP_BOX ()
Enumeration Type Documentation
anonymous enum
Enumerator:
UPPER_LEFT
LOWER_RIGHT
CLOSED
FILL
Definition at line 175 of file fl_gtk.cxx.
Function Documentation
Fl_Boxtype fl_define_FL_GTK_UP_BOX ()
Definition at line 286 of file fl_gtk.cxx.
References _FL_GTK_DOWN_BOX, _FL_GTK_DOWN_FRAME, _FL_GTK_ROUND_DOWN_BOX, _FL_GTK_ROUND_UP_BOX, _FL_GTK_THIN_DOWN_BOX, _FL_GTK_THIN_DOWN_FRAME, _FL_GTK_THIN_UP_BOX, _FL_GTK_THIN_UP_FRAME, _FL_GTK_UP_BOX, _FL_GTK_UP_FRAME, fl_internal_boxtype(), gtk_round_down_box(), and gtk_round_up_box().
void fl_internal_boxtype (Fl_Boxtype t, Fl_Box_Draw_F * f)
Sets the drawing function for a given box type.
Parameters:
[in] t box type
[in] f box drawing function
Definition at line 363 of file fl_boxtype.cxx.
void gtk_round_down_box (int x, int y, int w, int h, Fl_Color c)
Definition at line 246 of file fl_gtk.cxx.
References CLOSED, f, FILL, FL_BLACK, fl_color(), fl_color_average(), and UPPER_LEFT.
Referenced by fl_define_FL_GTK_UP_BOX().
void gtk_round_up_box (int x, int y, int w, int h, Fl_Color c)
Definition at line 215 of file fl_gtk.cxx.
References CLOSED, f, FILL, FL_BLACK, fl_color(), fl_color_average(), FL_WHITE, LOWER_RIGHT, and UPPER_LEFT.
Referenced by fl_define_FL_GTK_UP_BOX().