SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/Fl_Type.h File Reference
Fl_Type.h File Reference
#include <FL/Fl_Widget.H>
#include <FL/Fl_Menu.H>
#include <FL/Fl_Plugin.H>
#include "Fluid_Image.h"
#include <FL/fl_draw.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Wizard.H>
#include <FL/Fl_Menu_.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Bar.H>
Classes
class Fl_Type
class Fl_Function_Type
class Fl_Code_Type
class Fl_CodeBlock_Type
class Fl_Decl_Type
class Fl_Data_Type
class Fl_DeclBlock_Type
class Fl_Comment_Type
class Fl_Class_Type
class Fl_Widget_Type
class igroup
class itabs
class iwizard
class Fl_Group_Type
class Fl_Pack_Type
class Fl_Table_Type
class Fl_Tabs_Type
class Fl_Scroll_Type
class Fl_Tile_Type
class Fl_Wizard_Type
class Fl_Window_Type
class Fl_Widget_Class_Type
class Fl_Menu_Item_Type
class Fl_Submenu_Type
class Fl_Menu_Type
class Fl_Menu_Button_Type
class Fl_Choice_Type
class Fl_Input_Choice_Type
class Fl_Menu_Bar_Type
class Fl_Commandline_Plugin
Defines
#define NUM_EXTRA_CODE 4
#define __fl_attr(x)
Functions
void set_modflag (int mf)
Fl_Widget * make_widget_browser (int X, int Y, int W, int H)
void delete_all (int selected_only=0)
void selection_changed (Fl_Type *new_current)
void reveal_in_browser (Fl_Type *)
int has_toplevel_function (const char *rtype, const char *sig)
void write_word (const char *)
void write_string (const char *,...) __fl_attr((__format__(__printf__
void int write_file (const char *, int selected_only=0)
int write_code (const char *cfile, const char *hfile)
int write_strings (const char *sfile)
int write_declare (const char *,...) __fl_attr((__format__(__printf__
int int is_id (char)
const char * unique_id (void *o, const char *, const char *, const char *)
void write_c (const char *,...) __fl_attr((__format__(__printf__
void void write_h (const char *,...) __fl_attr((__format__(__printf__
void void void write_cstring (const char *)
void write_cstring (const char *, int length)
void write_cdata (const char *, int length)
void write_indent (int n)
void write_open (int)
void write_close (int n)
void write_public (int state)
const char * indent ()
int read_file (const char *, int merge)
const char * read_word (int wantbrace=0)
void read_error (const char *format,...)
const char * c_check (const char *c, int type=0)
int storestring (const char *n, const char *&p, int nostrip=0)
Variables
const char pack_type_name []
Fl_Menu_Item pack_type_menu []
const char table_type_name []
const char tabs_type_name []
const char scroll_type_name []
Fl_Menu_Item scroll_type_menu []
const char tile_type_name []
const char wizard_type_name []
Fl_Menu_Item window_type_menu []
Fl_Menu_Item menu_item_type_menu []
Fl_Menu_Item button_type_menu []
Fl_Menu_Item dummymenu []
int modflag
int write_number
int write_sourceview
int indentation
int include_H_from_C
int use_FL_COMMAND
Define Documentation
#define __fl_attr (x)
Definition at line 810 of file Fl_Type.h.
#define NUM_EXTRA_CODE 4
Definition at line 331 of file Fl_Type.h.
Referenced by Fl_Widget_Type::Fl_Widget_Type(), Fl_Widget_Type::read_property(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Widget_Type::write_extra_code(), Fl_Widget_Type::write_properties(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), and Fl_Widget_Type::~Fl_Widget_Type().
Function Documentation
const char* c_check (const char * c, int type = 0)
Definition at line 121 of file Fl_Function_Type.cxx.
References _c_check().
Referenced by callback_cb(), Fl_Class_Type::open(), Fl_DeclBlock_Type::open(), Fl_Decl_Type::open(), Fl_CodeBlock_Type::open(), Fl_Code_Type::open(), Fl_Function_Type::open(), user_data_cb(), user_data_type_cb(), and v_input_cb().
void delete_all (int selected_only = 0)
Definition at line 757 of file Fl_Type.cxx.
References f, include_H_from_C, Fl_Type::next, Fl_Type::selected, selection_changed(), and use_FL_COMMAND.
Referenced by cut_cb(), delete_cb(), new_cb(), and read_file().
int has_toplevel_function (const char * rtype, const char * sig)
Return 1 if the list contains a function with the given signature at the top level
Definition at line 912 of file Fl_Type.cxx.
References Fl_Function_Type::has_signature(), Fl_Type::is_in_class(), Fl_Type::next, and Fl_Type::type_name().
Referenced by Fl_Widget_Type::write_static().
const char* indent ()
Definition at line 108 of file code.cxx.
References i, and indentation.
Referenced by main(), Fl_Text_Display::overstrike(), fl_margins::push(), Fl_Widget_Type::write_block_close(), Fluid_Image::write_code(), Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_CodeBlock_Type::write_code1(), Fl_Code_Type::write_code1(), Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), Fl_Menu_Type::write_code2(), Fl_Group_Type::write_code2(), Fl_CodeBlock_Type::write_code2(), Fl_Widget_Type::write_color(), Fl_Widget_Type::write_extra_code(), and Fl_Widget_Type::write_widget_code().
int int is_id (char)
Definition at line 49 of file code.cxx.
Referenced by Fl_Class_Type::open(), unique_id(), Fl_Widget_Type::write_static(), Fl_Menu_Item_Type::write_static(), and write_word().
Fl_Widget* make_widget_browser (int X, int Y, int W, int H)
Definition at line 200 of file Fl_Type.cxx.
References Fl_Type::Widget_Browser.
Referenced by make_main_window().
void read_error (const char * format, ...)
Definition at line 156 of file file.cxx.
References fl_message(), and vsnprintf.
Referenced by Fluid_Image::find(), Fl_Widget_Type::read_property(), Fl_Type::read_property(), and read_word().
int read_file (const char * , int merge)
Definition at line 501 of file file.cxx.
References Fl_Type::add_child(), close_read(), Fl_Type::current, delete_all(), deselect(), Fl_Type::first, Fl_Type::is_menu_button(), Fl_Type::next, open_read(), Fl_Type::selected, and selection_changed().
Referenced by duplicate_cb(), main(), new_cb(), open_cb(), open_history_cb(), paste_cb(), redo_cb(), revert_cb(), and undo_cb().
const char* read_word (int wantbrace = 0)
Definition at line 235 of file file.cxx.
References length, read_error(), and x.
Referenced by Fl_BMP_Image::Fl_BMP_Image(), read_fdesign(), Fl_Window_Type::read_property(), Fl_Widget_Type::read_property(), Fl_Type::read_property(), Fl_Class_Type::read_property(), Fl_DeclBlock_Type::read_property(), Fl_Data_Type::read_property(), Fl_CodeBlock_Type::read_property(), and Fl_Function_Type::read_property().
void reveal_in_browser (Fl_Type * t)
Make sure that the given item is visible in the browser by opening all parent groups and moving the item into the visible space.
Definition at line 974 of file Fl_Type.cxx.
References Fl_Browser_::display(), Fl_Type::open_, Fl_Type::parent, and redraw_browser().
Referenced by Fl_Window_Type::handle().
void selection_changed (Fl_Type * new_current)
Definition at line 1892 of file Fl_Widget_Type.cxx.
References check_redraw_corresponding_parent(), Fl_Type::first, redraw_browser(), redraw_overlays(), Fl_Type::selected, set_cb(), update_sourceview_position(), and Fl_Widget::visible().
Referenced by Widget_Browser::callback(), delete_all(), read_file(), Fl_Type::remove(), select_all_cb(), and select_none_cb().
void set_modflag (int mf)
Definition at line 2213 of file fluid.cxx.
References Fl_Menu_Item::activate(), Fl::add_timeout(), Fl_Menu_Item::deactivate(), FL_PATH_MAX, Fl_Window::label(), modflag, NULL, Fl::remove_timeout(), snprintf, sourceview_panel, sv_autorefresh, update_sourceview_timer(), Fl_Button::value(), and Fl_Widget::visible().
Referenced by active_cb(), Fl_Type::add(), align_cb(), align_position_cb(), align_text_image_cb(), align_widget_cb(), border_cb(), box_cb(), callback_cb(), Fl_Tabs_Type::click_test(), code_input_cb(), color2_cb(), color_cb(), cut_cb(), delete_cb(), down_box_cb(), earlier_cb(), h_cb(), header_input_cb(), hotspot_cb(), i18n_int_cb(), i18n_text_cb(), i18n_type_cb(), image_browse_cb(), image_cb(), inactive_browse_cb(), inactive_cb(), include_H_from_C_button_cb(), label_cb(), labelcolor_cb(), labelfont_cb(), labelsize_cb(), labeltype_cb(), later_cb(), main(), max_cb(), max_h_cb(), max_w_cb(), min_cb(), min_h_cb(), min_w_cb(), modal_cb(), Fl_Window_Type::moveallchildren(), name_public_cb(), name_public_member_cb(), new_cb(), non_modal_cb(), Fl_Class_Type::open(), Fl_Comment_Type::open(), Fl_DeclBlock_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_Function_Type::open(), open_cb(), open_history_cb(), redo_cb(), resizable_cb(), Overlay_Window::resize(), revert_cb(), save_cb(), set_filename(), set_max_size_cb(), set_min_size_cb(), shortcut_in_cb(), slider_size_cb(), step_cb(), storestring(), subclass_cb(), subtype_cb(), textcolor_cb(), textfont_cb(), textsize_cb(), tooltip_cb(), type_make_cb(), undo_cb(), use_FL_COMMAND_button_cb(), user_data_cb(), user_data_type_cb(), v_input_cb(), value_cb(), visible_cb(), w_cb(), wc_relative_cb(), when_button_cb(), when_cb(), widget_size_cb(), x_cb(), xclass_cb(), and y_cb().
int storestring (const char * n, const char *& p, int nostrip = 0)
Definition at line 597 of file Fl_Type.cxx.
References length, set_modflag(), strlcpy, and undo_checkpoint().
Referenced by Fl_Type::callback(), Fl_Type::comment(), Fl_Widget_Type::extra_code(), Fl_Widget_Type::image_name(), Fl_Widget_Type::inactive_name(), Fl_Type::label(), Fl_Type::name(), Fl_Class_Type::open(), Fl_DeclBlock_Type::open(), Fl_CodeBlock_Type::open(), Fl_Function_Type::open(), Fl_Window_Type::read_property(), Fl_Class_Type::read_property(), Fl_DeclBlock_Type::read_property(), Fl_Data_Type::read_property(), Fl_CodeBlock_Type::read_property(), Fl_Function_Type::read_property(), Fl_Widget_Type::subclass(), Fl_Widget_Type::tooltip(), Fl_Type::user_data(), Fl_Type::user_data_type(), and xclass_cb().
const char* unique_id (void * o, const char * , const char * , const char *)
Definition at line 72 of file code.cxx.
References buffer, i, is_id(), and name.
Referenced by Fl_Type::callback_name(), Fl_Menu_Item_Type::menu_name(), Fluid_Image::write_code(), Fl_Menu_Type::write_code2(), and Fluid_Image::write_static().
void write_c (const char * , ...)
void write_cdata (const char * , int length)
Definition at line 233 of file code.cxx.
References length, varused, varused_test, w, and write_sourceview.
Referenced by Fl_Data_Type::write_code1(), and Fluid_Image::write_static().
void write_close (int n)
Definition at line 122 of file file.cxx.
References write_indent().
Referenced by Fl_Type::write().
int write_code (const char * cfile, const char * hfile)
Definition at line 346 of file code.cxx.
References b, Fl_Type::code_position, Fl_Type::code_position_end, f, Fl_Type::first, fl_filename_name(), fl_fopen(), FL_VERSION, header_file_name, Fl_Type::header_position, Fl_Type::header_position_end, i18n_file, i18n_include, i18n_program, i18n_type, include_H_from_C, indentation, int, Fl_Type::is_comment(), Fl_Type::last, Fl_Type::level, Fl_Type::next, NULL, write_c(), Fl_Type::write_code1(), write_declare(), write_number, write_sourceview, x, and y.
Referenced by update_sourceview_cb(), and write_cb().
void void void write_cstring (const char *)
Definition at line 230 of file code.cxx.
References write_cstring().
void write_cstring (const char * , int length)
Definition at line 163 of file code.cxx.
References length, varused, varused_test, and w.
Referenced by Fl_Widget_Class_Type::write_code1(), Fl_Widget_Type::write_code1(), Fl_Widget_Class_Type::write_code2(), Fl_Window_Type::write_code2(), write_cstring(), Fl_Menu_Item_Type::write_item(), Fluid_Image::write_static(), and Fl_Widget_Type::write_widget_code().
int write_declare (const char * , ...)
void int write_file (const char * , int selected_only = 0)
Definition at line 320 of file file.cxx.
References close_write(), Fl_Type::first, FL_VERSION, include_H_from_C, open_write(), use_FL_COMMAND, write_string(), and write_word().
Referenced by copy_cb(), cut_cb(), duplicate_cb(), save_cb(), save_template_cb(), undo_cb(), and undo_checkpoint().
void void write_h (const char * , ...)
void write_indent (int n)
Definition at line 108 of file file.cxx.
Referenced by Fl_Type::write(), write_close(), Fl_Widget_Type::write_properties(), and Fl_Type::write_properties().
void write_open (int)
Definition at line 115 of file file.cxx.
Referenced by Fl_Type::write().
void write_public (int state)
Definition at line 1425 of file Fl_Function_Type.cxx.
References state, write_h(), Fl_Widget_Class_Type::write_public_state, and Fl_Class_Type::write_public_state.
Referenced by Fl_Widget_Type::write_code1(), Fl_Menu_Item_Type::write_code1(), Fl_Data_Type::write_code1(), Fl_Decl_Type::write_code1(), and Fl_Function_Type::write_code1().
void write_string (const char * , ...)
int write_strings (const char * sfile)
Definition at line 470 of file code.cxx.
References Fl_Type::first, fl_fopen(), FL_VERSION, fp, i, i18n_set, i18n_type, Fl_Type::is_widget(), Fl_Type::label(), Fl_Type::next, Fl_Widget_Type::tooltip(), and w.
Referenced by write_strings_cb().
void write_word (const char *)
Definition at line 65 of file file.cxx.
References is_id(), and w.
Referenced by Fl_Type::write(), write_file(), Fl_Window_Type::write_properties(), Fl_Widget_Type::write_properties(), Fl_Type::write_properties(), Fl_Class_Type::write_properties(), Fl_DeclBlock_Type::write_properties(), Fl_Data_Type::write_properties(), Fl_CodeBlock_Type::write_properties(), and Fl_Function_Type::write_properties().
Variable Documentation
Fl_Menu_Item button_type_menu[]
Definition at line 510 of file Fl_Menu_Type.cxx.
Fl_Menu_Item dummymenu[]
Definition at line 525 of file Fl_Menu_Type.cxx.
int include_H_from_C
Definition at line 51 of file Fl_Window_Type.cxx.
Referenced by delete_all(), include_H_from_C_button_cb(), show_project_cb(), write_code(), and write_file().
int indentation
Definition at line 107 of file code.cxx.
Referenced by indent(), Fl_Widget_Type::write_block_close(), write_code(), Fl_Widget_Type::write_code1(), Fl_CodeBlock_Type::write_code1(), Fl_Function_Type::write_code1(), Fl_CodeBlock_Type::write_code2(), and Fl_Function_Type::write_code2().
Fl_Menu_Item menu_item_type_menu[]
Definition at line 46 of file Fl_Menu_Type.cxx.
Referenced by Fl_Menu_Item_Type::subtypes().
int modflag
Definition at line 125 of file fluid.cxx.
Referenced by exit_cb(), new_cb(), open_cb(), open_history_cb(), revert_cb(), set_filename(), set_modflag(), undo_checkpoint(), and undo_clear().
Fl_Menu_Item pack_type_menu[]
Definition at line 141 of file Fl_Group_Type.cxx.
const char pack_type_name[]
Definition at line 139 of file Fl_Group_Type.cxx.
Referenced by Fl_Pack_Type::type_name().
Fl_Menu_Item scroll_type_menu[]
Definition at line 419 of file Fl_Group_Type.cxx.
const char scroll_type_name[]
Definition at line 401 of file Fl_Group_Type.cxx.
Referenced by Fl_Scroll_Type::type_name().
const char table_type_name[]
Definition at line 224 of file Fl_Group_Type.cxx.
Referenced by Fl_Table_Type::type_name().
const char tabs_type_name[]
Definition at line 235 of file Fl_Group_Type.cxx.
Referenced by color_cb(), and Fl_Tabs_Type::type_name().
const char tile_type_name[]
Definition at line 441 of file Fl_Group_Type.cxx.
Referenced by Fl_Tile_Type::type_name().
int use_FL_COMMAND
Definition at line 52 of file Fl_Window_Type.cxx.
Referenced by delete_all(), Shortcut_Button::draw(), show_project_cb(), use_FL_COMMAND_button_cb(), write_file(), Fl_Menu_Item_Type::write_item(), and Fl_Widget_Type::write_widget_code().
Fl_Menu_Item window_type_menu[]
Definition at line 280 of file Fl_Window_Type.cxx.
Referenced by Fl_Window_Type::subtypes().
const char wizard_type_name[]
Definition at line 266 of file Fl_Group_Type.cxx.
Referenced by Fl_Wizard_Type::type_name().
int write_number
Definition at line 285 of file code.cxx.
Referenced by write_code(), Fluid_Image::write_static(), Fl_Widget_Type::write_static(), and Fl_Menu_Item_Type::write_static().
int write_sourceview
Definition at line 286 of file code.cxx.
Referenced by update_sourceview_cb(), write_cdata(), write_code(), and Fl_Data_Type::write_code1().