SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/fl_color_win32.cxx File Reference
fl_color_win32.cxx File Reference
#include <config.h>
#include <FL/Fl.H>
#include <FL/x.H>
#include <FL/fl_draw.H>
#include "fl_cmap.h"
Defines
#define FL_N_BRUSH 16
Functions
void fl_cleanup_pens (void)
void fl_save_pen (void)
void fl_restore_pen (void)
HBRUSH fl_brush ()
HBRUSH fl_brush_action (int action)
Variables
Fl_XMap fl_xmap [256]
Fl_XMap * fl_current_xmap
HPALETTE fl_palette
Fl_Color fl_color_
The current color.
Define Documentation
#define FL_N_BRUSH 16
Referenced by fl_brush_action().
Function Documentation
HBRUSH fl_brush ()
Definition at line 133 of file fl_color_win32.cxx.
References fl_brush_action().
Referenced by Fl_Graphics_Driver::circle(), Fl_Graphics_Driver::end_complex_polygon(), Fl_Graphics_Driver::end_polygon(), Fl_Graphics_Driver::pie(), Fl_Graphics_Driver::polygon(), and Fl_Graphics_Driver::rectf().
HBRUSH fl_brush_action (int action)
Definition at line 137 of file fl_color_win32.cxx.
References Fl_XMap::brush, fl_current_xmap, fl_gc, FL_N_BRUSH, i, NULL, and Fl_XMap::rgb.
Referenced by fl_brush().
void fl_cleanup_pens (void)
Definition at line 55 of file fl_color_win32.cxx.
References i.
void fl_restore_pen (void)
Definition at line 66 of file fl_color_win32.cxx.
References fl_gc.
void fl_save_pen (void)
Definition at line 61 of file fl_color_win32.cxx.
References fl_gc.
Variable Documentation
Fl_XMap* fl_current_xmap
Definition at line 49 of file fl_color_win32.cxx.
HPALETTE fl_palette
Definition at line 51 of file fl_color_win32.cxx.
Referenced by fl_rectf().
Fl_XMap fl_xmap[256]
HAVE_OVERLAY determines whether fl_xmap is one or two planes
Definition at line 47 of file fl_color_win32.cxx.