SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/fl_font_x.cxx File Reference
fl_font_x.cxx File Reference
Defines
#define MAXSIZE 32767
#define current_font (fl_fontsize->font)
Functions
const char * fl_font_word (const char *p, int n)
char * fl_find_fontsize (char *name)
int fl_correct_encoding (const char *name)
char * fl_get_font_xfld (int fnum, int size)
int fl_height ()
int fl_descent ()
double fl_width (const char *c, int n)
double fl_width (unsigned int c)
void fl_text_extents (const char *c, int n, int &dx, int &dy, int &W, int &H)
Variables
Fl_Font_Descriptor * fl_fontsize
Fl_XFont_On_Demand fl_xfont
Fl_Fontdesc * fl_fonts = built_in_table
const char * fl_encoding = "iso8859-1"
Fl_Font fl_font_ = 0
current font index
Fl_Fontsize fl_size_ = 0
current font size
void * fl_xftfont = 0
Define Documentation
#define current_font (fl_fontsize->font)
Definition at line 90 of file fl_font_x.cxx.
Referenced by Fl_Xlib_Graphics_Driver::draw(), fl_descent(), fl_height(), fl_width(), Fl_Xlib_Graphics_Driver::font(), and Fl_Xlib_Graphics_Driver::rtl_draw().
#define MAXSIZE 32767
Definition at line 88 of file fl_font_x.cxx.
Function Documentation
int fl_correct_encoding (const char * name)
Definition at line 117 of file fl_font_x.cxx.
References fl_font_word().
char* fl_find_fontsize (char * name)
Definition at line 99 of file fl_font_x.cxx.
References fl_font_word(), and name.
const char* fl_font_word (const char * p, int n)
Definition at line 93 of file fl_font_x.cxx.
Referenced by fl_correct_encoding(), and fl_find_fontsize().
char* fl_get_font_xfld (int fnum, int size)
Definition at line 232 of file fl_font_x.cxx.
References fl_fonts, fl_open_display(), and Fl_Fontdesc::name.
Referenced by fl_new_ic(), and fl_set_spot().
Variable Documentation
const char* fl_encoding = "iso8859-1"
Definition at line 114 of file fl_font_x.cxx.
Fl_Fontdesc* fl_fonts = built_in_table
Definition at line 86 of file fl_font_x.cxx.
Fl_Font_Descriptor* fl_fontsize
Definition at line 41 of file fl_font_x.cxx.
Fl_XFont_On_Demand fl_xfont
Definition at line 42 of file fl_font_x.cxx.
void* fl_xftfont = 0
Definition at line 265 of file fl_font_x.cxx.