SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/Fl_Font.H File Reference
Fl_Font.H File Reference
#include <config.h>
#include <FL/Xutf8.h>
Classes
class Fl_Font_Descriptor
struct Fl_Fontdesc
Functions
FL_EXPORT const char * fl_font_word (const char *p, int n)
FL_EXPORT char * fl_find_fontsize (char *name)
Variables
FL_EXPORT Fl_Font_Descriptor * fl_fontsize
FL_EXPORT Fl_Fontdesc * fl_fonts
Function Documentation
FL_EXPORT char* fl_find_fontsize (char * name)
Definition at line 99 of file fl_font_x.cxx.
References fl_font_word(), and name.
FL_EXPORT const char* fl_font_word (const char * p, int n)
Definition at line 93 of file fl_font_x.cxx.
Referenced by fl_correct_encoding(), and fl_find_fontsize().
Variable Documentation
FL_EXPORT Fl_Fontdesc* fl_fonts
Definition at line 214 of file fl_font_mac.cxx.
Referenced by fl_free_fonts(), fl_get_font_xfld(), Fl::get_font(), Fl::get_font_name(), Fl::get_font_sizes(), and Fl::set_font().
FL_EXPORT Fl_Font_Descriptor* fl_fontsize
Definition at line 150 of file fl_font_mac.cxx.