SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/fl_ask.cxx File Reference
fl_ask.cxx File Reference
#include <stdio.h>
#include <stdarg.h>
#include "flstring.h"
#include <FL/Fl.H>
#include <FL/fl_ask.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Secret_Input.H>
#include <FL/x.H>
#include <FL/fl_draw.H>
Functions
void resizeform ()
void fl_beep (int type)
void fl_message (const char *fmt,...)
void fl_alert (const char *fmt,...)
int fl_ask (const char *fmt,...)
int fl_choice (const char *fmt, const char *b0, const char *b1, const char *b2,...)
Fl_Widget * fl_message_icon ()
const char * fl_input (const char *fmt, const char *defstr,...)
const char * fl_password (const char *fmt, const char *defstr,...)
Variables
Fl_Font fl_message_font_ = FL_HELVETICA
Fl_Fontsize fl_message_size_ = 14
const char * fl_no = "No"
string pointer used in common dialogs, you can change it to a foreign language
const char * fl_yes = "Yes"
string pointer used in common dialogs, you can change it to a foreign language
const char * fl_ok = "OK"
string pointer used in common dialogs, you can change it to a foreign language
const char * fl_cancel = "Cancel"
string pointer used in common dialogs, you can change it to a foreign language
const char * fl_close = "Close"
string pointer used in common dialogs, you can change it to a foreign language
Function Documentation
void resizeform ()
Definition at line 122 of file fl_ask.cxx.
References fl_font(), fl_measure(), fl_message_font_, fl_message_size_, h, i, Fl_Widget::label(), Fl_Widget::labelsize(), Fl_Input_::resize(), Fl_Widget::resize(), Fl_Widget::size(), Fl_Window::size_range(), Fl_Widget::visible(), w, and x.
Variable Documentation
Fl_Font fl_message_font_ = FL_HELVETICA
Definition at line 57 of file fl_ask.cxx.
Referenced by resizeform().
Fl_Fontsize fl_message_size_ = 14
Definition at line 58 of file fl_ask.cxx.
Referenced by resizeform().