SfR Fresh Dox - fltk: fltk-1.3.0rc3/FL/Fl_File_Chooser.H File Reference
Fl_File_Chooser.H File Reference
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Preferences.H>
#include <FL/Fl_Tile.H>
#include <FL/Fl_File_Browser.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_File_Input.H>
#include <FL/Fl_Return_Button.H>
#include <FL/fl_ask.H>
Classes
class Fl_File_Chooser
Function Documentation
FL_EXPORT char* fl_dir_chooser (const char * message, const char * fname, int relative = 0) [related]
FL_EXPORT char* fl_file_chooser (const char * message, const char * pat, const char * fname, int relative = 0) [related]
Referenced by Fl_Comment_Type::open(), and Fl_Data_Type::open().
FL_EXPORT void fl_file_chooser_callback (void(*)(const char *) cb) [related]
FL_EXPORT void fl_file_chooser_ok_label (const char * l) [related]
Referenced by Fl_Comment_Type::open().