SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/fluid.cxx File Reference
fluid.cxx File Reference
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Icon.H>
#include <FL/Fl_Help_Dialog.H>
#include <FL/Fl_Hold_Browser.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Plugin.H>
#include <FL/fl_ask.H>
#include <FL/fl_draw.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/fl_message.H>
#include <FL/filename.H>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/stat.h>
#include <time.h>
#include "../src/flstring.h"
#include "alignment_panel.h"
#include "function_panel.h"
#include "template_panel.h"
#include "print_panel.cxx"
#include <unistd.h>
#include "about_panel.h"
#include "undo.h"
#include "Fl_Type.h"
#include <signal.h>
Classes
class Fl_Process
Defines
#define BROWSERWIDTH 300
#define BROWSERHEIGHT 500
#define WINWIDTH 300
#define MENUHEIGHT 25
#define WINHEIGHT (BROWSERHEIGHT+MENUHEIGHT)
#define SIGARG int
Functions
void load_history ()
void update_history (const char *)
void show_shell_window ()
void set_filename (const char *c)
void set_modflag (int mf)
void goto_source_dir ()
void leave_source_dir ()
char position_window (Fl_Window *w, const char *prefsName, int Visible, int X, int Y, int W=0, int H=0)
void save_position (Fl_Window *w, const char *prefsName)
void save_cb (Fl_Widget *, void *v)
void save_template_cb (Fl_Widget *, void *)
void revert_cb (Fl_Widget *, void *)
void exit_cb (Fl_Widget *, void *)
void open_cb (Fl_Widget *, void *v)
void open_history_cb (Fl_Widget *, void *v)
void new_cb (Fl_Widget *, void *v)
void write_cb (Fl_Widget *, void *)
void write_strings_cb (Fl_Widget *, void *)
void openwidget_cb (Fl_Widget *, void *)
void toggle_overlays (Fl_Widget *, void *)
void select_all_cb (Fl_Widget *, void *)
void select_none_cb (Fl_Widget *, void *)
void group_cb (Fl_Widget *, void *)
void ungroup_cb (Fl_Widget *, void *)
void copy_cb (Fl_Widget *, void *)
void select_only (Fl_Type *)
void cut_cb (Fl_Widget *, void *)
void delete_cb (Fl_Widget *, void *)
void paste_cb (Fl_Widget *, void *)
void duplicate_cb (Fl_Widget *, void *)
void earlier_cb (Fl_Widget *, void *)
void later_cb (Fl_Widget *, void *)
Fl_Type * sort (Fl_Type *parent)
void show_project_cb (Fl_Widget *, void *)
void show_grid_cb (Fl_Widget *, void *)
void show_settings_cb (Fl_Widget *, void *)
void show_global_settings_cb (Fl_Widget *, void *)
void align_widget_cb (Fl_Widget *, long)
void widget_size_cb (Fl_Widget *, long)
void about_cb (Fl_Widget *, void *)
void show_help (const char *name)
void help_cb (Fl_Widget *, void *)
void manual_cb (Fl_Widget *, void *)
void print_menu_cb (Fl_Widget *, void *)
void print_cb (Fl_Return_Button *, void *)
void toggle_widgetbin_cb (Fl_Widget *, void *)
void toggle_sourceview_cb (Fl_Double_Window *, void *)
void fill_in_New_Menu ()
void scheme_cb (Fl_Choice *, void *)
void toggle_sourceview_b_cb (Fl_Button *, void *)
void make_main_window ()
void shell_pipe_cb (int, void *)
void do_shell_command (Fl_Return_Button *, void *)
void update_sourceview_position ()
void update_sourceview_position_cb (Fl_Tabs *, void *)
void update_sourceview_cb (Fl_Button *, void *)
void update_sourceview_timer (void *)
int main (int argc, char **argv)
Variables
Fl_Preferences fluid_prefs (Fl_Preferences::USER,"fltk.org","fluid")
int gridx = 5
int gridy = 5
int snap = 1
int show_guides = 1
int show_comments = 1
int show_coredevmenus = 1
char absolute_history [10][FL_PATH_MAX]
char relative_history [10][FL_PATH_MAX]
Fl_Menu_Item * save_item = 0L
Fl_Menu_Item * history_item = 0L
Fl_Menu_Item * widgetbin_item = 0L
Fl_Menu_Item * sourceview_item = 0L
int modflag
Fl_Window * main_window
Fl_Menu_Bar * main_menubar
int exit_early = 0
int compile_only = 0
int compile_strings = 0
int header_file_set = 0
int code_file_set = 0
const char * header_file_name = ".h"
const char * code_file_name = ".cxx"
int i18n_type = 0
const char * i18n_include = ""
const char * i18n_function = ""
const char * i18n_file = ""
const char * i18n_set = ""
char i18n_program [FL_PATH_MAX] = ""
int pasteoffset
int force_parent
Fl_Menu_Item New_Menu []
Fl_Menu_Item Main_Menu []
int quit_flag = 0
Define Documentation
#define BROWSERHEIGHT 500
Definition at line 1682 of file fluid.cxx.
Referenced by make_main_window().
#define BROWSERWIDTH 300
Definition at line 1681 of file fluid.cxx.
Referenced by make_main_window().
#define MENUHEIGHT 25
Definition at line 1684 of file fluid.cxx.
Referenced by make_main_window().
#define SIGARG int
Definition at line 2284 of file fluid.cxx.
#define WINHEIGHT (BROWSERHEIGHT+MENUHEIGHT)
Definition at line 1685 of file fluid.cxx.
Referenced by main(), and make_main_window().
#define WINWIDTH 300
Definition at line 1683 of file fluid.cxx.
Referenced by main(), and make_main_window().
Function Documentation
void about_cb (Fl_Widget * , void *)
Definition at line 843 of file fluid.cxx.
References about_panel, make_about_panel(), and Fl_Double_Window::show().
void align_widget_cb (Fl_Widget * , long)
Definition at line 41 of file align_widget.cxx.
References BREAK_ON_FIRST, Fl_Type::first, Fl_Widget::h(), Fl_Type::is_menu_button(), Fl_Type::is_widget(), Fl_Type::level, min, Fl_Type::next, Fl_Type::parent, Fl_Widget::redraw(), Fl_Widget::resize(), Fl_Type::selected, set_modflag(), undo_checkpoint(), Fl_Widget::w(), w, Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
void copy_cb (Fl_Widget * , void *)
Definition at line 736 of file fluid.cxx.
References Fl_Type::current, fl_beep(), fl_message(), and write_file().
void cut_cb (Fl_Widget * , void *)
Definition at line 749 of file fluid.cxx.
References Fl_Type::current, delete_all(), fl_beep(), fl_message(), Fl_Type::parent, select_only(), Fl_Type::selected, set_modflag(), undo_checkpoint(), and write_file().
void delete_cb (Fl_Widget * , void *)
Definition at line 767 of file fluid.cxx.
References Fl_Type::current, delete_all(), fl_beep(), Fl_Type::parent, select_only(), Fl_Type::selected, set_modflag(), and undo_checkpoint().
void do_shell_command (Fl_Return_Button * , void *)
Definition at line 2042 of file fluid.cxx.
References Fl_Widget::activate(), Fl::add_fd(), Fl_Text_Buffer::append(), Fl_Widget::deactivate(), Fl_Process::desc(), fl_alert(), fl_beep(), Fl_Window::hotspot(), Fl_Window::label(), NULL, Fl_Process::popen(), shell_pipe_cb(), shell_run_buffer, shell_run_button, shell_run_display, shell_run_window, Fl_Double_Window::show(), Fl_Window::shown(), Fl_Text_Buffer::text(), and Fl::wait().
Referenced by make_shell_window().
void duplicate_cb (Fl_Widget * , void *)
Definition at line 800 of file fluid.cxx.
References Fl_Type::current, fl_beep(), fl_message(), read_file(), undo_checkpoint(), undo_resume(), undo_suspend(), and write_file().
void earlier_cb (Fl_Widget * , void *)
Definition at line 796 of file Fl_Type.cxx.
References f, Fl_Type::level, Fl_Type::move_before(), Fl_Type::next, Fl_Type::prev, Fl_Type::selected, and set_modflag().
void exit_cb (Fl_Widget * , void *)
Definition at line 381 of file fluid.cxx.
References about_panel, Fl_Group::find(), fl_choice(), fluid_prefs, modflag, NULL, save_cb(), save_position(), Fl_Preferences::set(), sourceview_panel, sv_autoposition, sv_autorefresh, sv_tab, undo_clear(), Fl_Tabs::value(), Fl_Button::value(), and widgetbin_panel.
Referenced by main().
void fill_in_New_Menu ()
Definition at line 1104 of file factory.cxx.
References i, Fl_Menu_Item::label(), m, New_Menu, Fl_Type::pixmapID(), Fl_Menu_Item::text, Fl_Type::type_name(), and Fl_Menu_Item::user_data().
Referenced by make_main_window().
void goto_source_dir ()
Definition at line 129 of file fluid.cxx.
References buffer, fl_filename_name(), FL_PATH_MAX, and strlcpy.
Referenced by Fluid_Image::find(), Fl_Data_Type::open(), ui_find_image(), write_cb(), and write_strings_cb().
void group_cb (Fl_Widget * , void *)
Definition at line 72 of file Fl_Group_Type.cxx.
References Fl_Type::add(), Fl_Type::current, Fl_Type::first, fix_group_size(), fl_message(), force_parent, Fl_Widget::h(), Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::level, Fl_Group_Type::make(), Fl_Type::move_before(), Fl_Widget_Type::o, Fl_Type::parent, Fl_Type::remove(), Fl_Widget::resize(), Fl_Type::selected, Fl_Type::type_name(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
void help_cb (Fl_Widget * , void *)
Definition at line 873 of file fluid.cxx.
References show_help().
void later_cb (Fl_Widget * , void *)
Definition at line 814 of file Fl_Type.cxx.
References f, Fl_Type::level, Fl_Type::move_before(), Fl_Type::next, Fl_Type::prev, Fl_Type::selected, and set_modflag().
void leave_source_dir ()
Definition at line 146 of file fluid.cxx.
Referenced by Fluid_Image::find(), Fl_Data_Type::open(), ui_find_image(), write_cb(), and write_strings_cb().
void load_history ()
Definition at line 1798 of file fluid.cxx.
References absolute_history, fl_filename_relative(), FL_MENU_DIVIDER, Fl_Menu_Item::flags, fluid_prefs, Fl_Preferences::get(), Fl_Menu_Item::hide(), i, and relative_history.
Referenced by make_main_window().
int main (int argc, char ** argv)
Definition at line 2297 of file fluid.cxx.
References absolute_history, Fl::args(), buf, Fl_Widget::callback(), exit_cb(), FL_DOUBLE, FL_INDEX, fl_message(), fl_open_callback(), fl_register_images(), grid_cb(), Fl_Commandline_Plugin::help(), Fl::help, horizontal_input, i, Fl_File_Icon::load_system_icons(), make_main_window(), open_history_cb(), openlast_button, Fl_Plugin_Manager::plugin(), Fl_Plugin_Manager::plugins(), position_window(), read_file(), Fl::run(), set_filename(), set_modflag(), Fl_Window::show(), toggle_sourceview_cb(), toggle_widgetbin_cb(), undo_clear(), undo_resume(), undo_suspend(), Fl_Button::value(), Fl::visual(), Fl::wait(), WINHEIGHT, WINWIDTH, write_cb(), and write_strings_cb().
void make_main_window ()
Definition at line 1758 of file fluid.cxx.
References Fl_Widget::box(), BROWSERHEIGHT, BROWSERWIDTH, Fl_Widget_Type::default_size, Fl_Group::end(), fill_in_New_Menu(), Fl_Menu_::find_item(), FL_FLAT_BOX, FL_NO_BOX, fluid_prefs, Fl_Preferences::get(), Fl_Menu_::global(), gridx, gridy, load_history(), make_global_settings_window(), make_layout_window(), make_settings_window(), make_shell_window(), make_widget_browser(), Fl_Menu_::menu(), MENUHEIGHT, open_history_cb(), Fl_Group::resizable(), show_comments, show_guides, snap, toggle_sourceview_cb(), toggle_widgetbin_cb(), Fl_Widget::tooltip(), WINHEIGHT, and WINWIDTH.
Referenced by main().
void manual_cb (Fl_Widget * , void *)
Definition at line 877 of file fluid.cxx.
References show_help().
void new_cb (Fl_Widget * , void * v)
Definition at line 535 of file fluid.cxx.
References Fl_Browser::add(), Fl_Browser::data(), Fl_Widget::deactivate(), delete_all(), fl_alert(), fl_choice(), fl_fopen(), Fl_Widget::hide(), infile, Fl_Window::label(), Fl_Widget::label(), make_template_panel(), modflag, NULL, outfile, ptr, read_file(), save_cb(), set_filename(), set_modflag(), Fl_Double_Window::show(), Fl_Widget::show(), Fl_Window::shown(), template_browser, template_clear(), template_delete, template_instance, template_load(), template_name, template_panel, template_submit, undo_clear(), undo_resume(), undo_suspend(), Fl_Browser::value(), Fl_Input_::value(), and Fl::wait().
void open_cb (Fl_Widget * , void * v)
Definition at line 457 of file fluid.cxx.
References fl_choice(), Fl_File_Chooser::fl_file_chooser(), Fl_File_Chooser::fl_file_chooser_ok_label(), fl_message(), modflag, NULL, read_file(), save_cb(), set_filename(), set_modflag(), undo_checkpoint(), undo_clear(), undo_resume(), and undo_suspend().
Referenced by fl_open_callback().
void open_history_cb (Fl_Widget * , void * v)
Definition at line 503 of file fluid.cxx.
References fl_choice(), fl_message(), Fl_Window::label(), modflag, NULL, read_file(), save_cb(), set_filename(), set_modflag(), undo_clear(), undo_resume(), and undo_suspend().
Referenced by main(), and make_main_window().
void openwidget_cb (Fl_Widget * , void *)
Definition at line 716 of file fluid.cxx.
References Fl_Type::current, fl_message(), and Fl_Type::open().
void paste_cb (Fl_Widget * , void *)
Definition at line 783 of file fluid.cxx.
References fl_message(), gridx, gridy, read_file(), undo_checkpoint(), undo_resume(), and undo_suspend().
char position_window (Fl_Window * w, const char * prefsName, int Visible, int X, int Y, int W = 0, int H = 0)
Definition at line 153 of file fluid.cxx.
References fluid_prefs, Fl_Preferences::get(), H, Fl_Widget::position(), prevpos_button, Fl_Window::resize(), and Fl_Button::value().
Referenced by main(), toggle_sourceview_cb(), and toggle_widgetbin_cb().
void print_cb (Fl_Return_Button * , void *)
Definition at line 1172 of file fluid.cxx.
Referenced by make_print_panel().
void print_menu_cb (Fl_Widget * , void *)
Definition at line 1131 of file fluid.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Widget::do_callback(), Fl_Type::first, Fl_Type::is_window(), make_print_panel(), Fl_Type::next, print_all, print_load(), print_panel, print_selection, Fl_Type::selected, Fl_Button::setonly(), and Fl_Double_Window::show().
void revert_cb (Fl_Widget * , void *)
Definition at line 365 of file fluid.cxx.
References fl_choice(), fl_message(), modflag, NULL, read_file(), set_modflag(), undo_clear(), undo_resume(), and undo_suspend().
void save_cb (Fl_Widget * , void * v)
Definition at line 197 of file fluid.cxx.
References fl_alert(), fl_choice(), Fl_File_Chooser::fl_file_chooser(), Fl_File_Chooser::fl_file_chooser_ok_label(), NULL, set_filename(), set_modflag(), undo_current, undo_save, and write_file().
Referenced by exit_cb(), new_cb(), open_cb(), open_history_cb(), write_cb(), and write_strings_cb().
void save_position (Fl_Window * w, const char * prefsName)
Definition at line 170 of file fluid.cxx.
References fluid_prefs, Fl_Widget::h(), Fl_Preferences::set(), Fl_Window::shown(), Fl_Widget::visible(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by exit_cb().
void save_template_cb (Fl_Widget * , void *)
Definition at line 234 of file fluid.cxx.
References Fl_Browser::add(), Fl_Widget::deactivate(), Fl_Type::first, fl_alert(), fl_choice(), fl_fopen(), FL_PATH_MAX, fluid_prefs, fp, Fl_Preferences::getUserdataPath(), h, Fl_Widget::hide(), i, Fl_Type::is_window(), Fl_Window::label(), Fl_Widget::label(), make_template_panel(), Fl_Type::next, NULL, PNG_COLOR_TYPE_RGB, PNG_COMPRESSION_TYPE_DEFAULT, png_create_info_struct(), png_create_write_struct(), png_destroy_write_struct(), PNG_FILTER_TYPE_DEFAULT, png_init_io(), PNG_INTERLACE_NONE, PNG_LIBPNG_VER_STRING, png_set_IHDR(), png_set_sRGB(), PNG_sRGB_INTENT_PERCEPTUAL, png_write_end(), png_write_info(), png_write_row(), ptr, Fl_Window_Type::read_image(), Fl_Double_Window::show(), Fl_Widget::show(), Fl_Window::shown(), strlcat, strlcpy, template_browser, template_clear(), template_delete, template_instance, template_load(), template_name, template_panel, template_submit, Fl_Input_::value(), w, Fl::wait(), and write_file().
void scheme_cb (Fl_Choice * , void *)
Definition at line 1689 of file fluid.cxx.
References fluid_prefs, NULL, Fl::scheme(), scheme_choice, Fl_Preferences::set(), and Fl_Choice::value().
Referenced by make_settings_window().
void select_all_cb (Fl_Widget * , void *)
Definition at line 699 of file Fl_Type.cxx.
References Fl_Type::current, in_this_only, Fl_Type::level, Fl_Type::new_selected, Fl_Type::next, Fl_Type::parent, Fl_Browser_::select(), and selection_changed().
void select_none_cb (Fl_Widget * , void *)
Definition at line 723 of file Fl_Type.cxx.
References Fl_Type::current, in_this_only, Fl_Type::level, Fl_Type::new_selected, Fl_Type::next, Fl_Type::parent, Fl_Browser_::select(), and selection_changed().
void select_only (Fl_Type *)
Definition at line 209 of file Fl_Type.cxx.
void set_filename (const char * c)
Definition at line 2095 of file fluid.cxx.
References modflag, NULL, set_modflag(), and update_history().
Referenced by main(), new_cb(), open_cb(), open_history_cb(), and save_cb().
void set_modflag (int mf)
Definition at line 2213 of file fluid.cxx.
References Fl_Menu_Item::activate(), Fl::add_timeout(), Fl_Menu_Item::deactivate(), FL_PATH_MAX, Fl_Window::label(), modflag, NULL, Fl::remove_timeout(), snprintf, sourceview_panel, sv_autorefresh, update_sourceview_timer(), Fl_Button::value(), and Fl_Widget::visible().
Referenced by active_cb(), Fl_Type::add(), align_cb(), align_position_cb(), align_text_image_cb(), align_widget_cb(), border_cb(), box_cb(), callback_cb(), Fl_Tabs_Type::click_test(), code_input_cb(), color2_cb(), color_cb(), cut_cb(), delete_cb(), down_box_cb(), earlier_cb(), h_cb(), header_input_cb(), hotspot_cb(), i18n_int_cb(), i18n_text_cb(), i18n_type_cb(), image_browse_cb(), image_cb(), inactive_browse_cb(), inactive_cb(), include_H_from_C_button_cb(), label_cb(), labelcolor_cb(), labelfont_cb(), labelsize_cb(), labeltype_cb(), later_cb(), main(), max_cb(), max_h_cb(), max_w_cb(), min_cb(), min_h_cb(), min_w_cb(), modal_cb(), Fl_Window_Type::moveallchildren(), name_public_cb(), name_public_member_cb(), new_cb(), non_modal_cb(), Fl_Class_Type::open(), Fl_Comment_Type::open(), Fl_DeclBlock_Type::open(), Fl_Data_Type::open(), Fl_Decl_Type::open(), Fl_Function_Type::open(), open_cb(), open_history_cb(), redo_cb(), resizable_cb(), Overlay_Window::resize(), revert_cb(), save_cb(), set_filename(), set_max_size_cb(), set_min_size_cb(), shortcut_in_cb(), slider_size_cb(), step_cb(), storestring(), subclass_cb(), subtype_cb(), textcolor_cb(), textfont_cb(), textsize_cb(), tooltip_cb(), type_make_cb(), undo_cb(), use_FL_COMMAND_button_cb(), user_data_cb(), user_data_type_cb(), v_input_cb(), value_cb(), visible_cb(), w_cb(), wc_relative_cb(), when_button_cb(), when_cb(), widget_size_cb(), x_cb(), xclass_cb(), and y_cb().
void shell_pipe_cb (int , void *)
Definition at line 2024 of file fluid.cxx.
References Fl_Text_Buffer::append(), Fl_Process::close(), Fl_Text_Display::count_lines(), Fl_Process::desc(), Fl_Process::get_line(), Fl_Text_Buffer::length(), NULL, Fl::remove_fd(), Fl_Text_Display::scroll(), shell_run_buffer, and shell_run_display.
Referenced by do_shell_command().
void show_global_settings_cb (Fl_Widget * , void *)
Definition at line 248 of file Fl_Window_Type.cxx.
References global_settings_window, Fl_Window::hotspot(), and show_global_settings_window().
void show_grid_cb (Fl_Widget * , void *)
Definition at line 226 of file Fl_Window_Type.cxx.
References buf, def_widget_size, Fl_Widget_Type::default_size, grid_window, gridx, gridy, guides_toggle, horizontal_input, Fl_Window::hotspot(), Fl_Button::setonly(), Fl_Double_Window::show(), show_guides, snap, snap_input, Fl_Button::value(), Fl_Input_::value(), and vertical_input.
void show_help (const char * name)
Definition at line 848 of file fluid.cxx.
References FL_PATH_MAX, FLTK_DOCDIR, Fl_Help_Dialog::load(), NULL, Fl_Help_Dialog::show(), snprintf, and strlcpy.
Referenced by help_cb(), and manual_cb().
void show_project_cb (Fl_Widget * , void *)
Definition at line 191 of file Fl_Window_Type.cxx.
References code_file_input, header_file_input, Fl_Widget::hide(), Fl_Window::hotspot(), i18n_file, i18n_file_input, i18n_function, i18n_function_input, i18n_include, i18n_include_input, i18n_set, i18n_set_input, i18n_type, i18n_type_chooser, include_H_from_C, include_H_from_C_button, make_project_window(), project_window, Fl_Double_Window::show(), Fl_Widget::show(), use_FL_COMMAND, use_FL_COMMAND_button, Fl_Choice::value(), Fl_Input_::value(), and Fl_Button::value().
void show_settings_cb (Fl_Widget * , void *)
Definition at line 243 of file Fl_Window_Type.cxx.
References Fl_Window::hotspot(), settings_window, and Fl_Double_Window::show().
void show_shell_window ()
Definition at line 2090 of file fluid.cxx.
References Fl_Window::hotspot(), shell_command_input, shell_window, and Fl_Double_Window::show().
Fl_Type* sort (Fl_Type * parent)
Definition at line 273 of file Fl_Widget_Type.cxx.
References f, Fl_Type::first, Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::level, Fl_Type::move_before(), Fl_Type::next, Fl_Type::selected, sort(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by sort().
void toggle_overlays (Fl_Widget * , void *)
Definition at line 1126 of file Fl_Window_Type.cxx.
References Fl_Type::first, Fl_Menu_Item::label(), Fl_Type::next, and Fl_Widget_Type::o.
void toggle_sourceview_b_cb (Fl_Button * , void *)
Definition at line 1754 of file fluid.cxx.
References toggle_sourceview_cb().
Referenced by make_sourceview().
void toggle_sourceview_cb (Fl_Double_Window * , void *)
Definition at line 1727 of file fluid.cxx.
References Fl_Widget::callback(), Fl_Group::child(), fluid_prefs, Fl_Preferences::get(), Fl_Double_Window::hide(), Fl_Menu_Item::label(), make_sourceview(), position_window(), Fl_Double_Window::show(), sourceview_panel, sv_autoposition, sv_autorefresh, sv_tab, toggle_sourceview_cb(), update_sourceview_cb(), Fl_Tabs::value(), Fl_Button::value(), and Fl_Widget::visible().
Referenced by main(), make_main_window(), make_sourceview(), toggle_sourceview_b_cb(), and toggle_sourceview_cb().
void toggle_widgetbin_cb (Fl_Widget * , void *)
Definition at line 1711 of file fluid.cxx.
References Fl_Window::hide(), Fl_Menu_Item::label(), make_widgetbin(), position_window(), Fl_Window::show(), Fl_Widget::visible(), and widgetbin_panel.
Referenced by main(), and make_main_window().
void ungroup_cb (Fl_Widget * , void *)
Definition at line 95 of file Fl_Group_Type.cxx.
References Fl_Type::current, fl_message(), Fl_Type::insert(), Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::level, Fl_Type::next, Fl_Type::parent, Fl_Type::remove(), Fl_Type::selected, and Fl_Type::type_name().
void update_history (const char * flname)
Definition at line 1825 of file fluid.cxx.
References absolute_history, fl_filename_absolute(), fl_filename_relative(), FL_MENU_DIVIDER, FL_PATH_MAX, Fl_Menu_Item::flags, fluid_prefs, Fl_Preferences::get(), Fl_Menu_Item::hide(), i, relative_history, Fl_Preferences::set(), and strlcpy.
Referenced by set_filename().
void update_sourceview_cb (Fl_Button * , void *)
Definition at line 2162 of file fluid.cxx.
References Fl_Text_Display::buffer(), code_file_name, fl_filename_name(), fl_filename_setext(), FL_PATH_MAX, fluid_prefs, Fl_Preferences::getUserdataPath(), header_file_name, Fl_Text_Display::scroll(), sourceview_panel, strlcat, strlcpy, sv_header, sv_source, CodeEditor::top_line(), update_sourceview_position(), Fl_Widget::visible(), write_code(), and write_sourceview.
Referenced by make_sourceview(), toggle_sourceview_cb(), and update_sourceview_timer().
void update_sourceview_position ()
Definition at line 2117 of file fluid.cxx.
References Fl_Text_Display::buffer(), Fl_Type::code_position, Fl_Type::code_position_end, Fl_Type::current, Fl_Type::header_position, Fl_Type::header_position_end, Fl_Text_Display::scroll(), sourceview_panel, sv_autoposition, sv_header, sv_source, Fl_Button::value(), Fl_Widget::visible(), and Fl_Widget::visible_r().
Referenced by selection_changed(), update_sourceview_cb(), and update_sourceview_position_cb().
void update_sourceview_position_cb (Fl_Tabs * , void *)
Definition at line 2150 of file fluid.cxx.
References update_sourceview_position().
Referenced by make_sourceview().
void update_sourceview_timer (void *)
Definition at line 2207 of file fluid.cxx.
References update_sourceview_cb().
Referenced by set_modflag().
void widget_size_cb (Fl_Widget * , long)
Definition at line 512 of file align_widget.cxx.
References f, Fl_Type::first, int, Fl_Widget::labelsize(), Fl_Type::next, Fl_Widget::redraw(), set_modflag(), undo_checkpoint(), w, and Fl_Widget::window().
void write_cb (Fl_Widget * , void *)
Definition at line 656 of file fluid.cxx.
References completion_button, fl_filename_name(), fl_filename_setext(), fl_message(), FL_PATH_MAX, goto_source_dir(), leave_source_dir(), NULL, save_cb(), strlcat, strlcpy, Fl_Button::value(), write_code(), and x.
Referenced by main().
void write_strings_cb (Fl_Widget * , void *)
Definition at line 693 of file fluid.cxx.
References completion_button, fl_filename_name(), fl_filename_setext(), fl_message(), FL_PATH_MAX, goto_source_dir(), leave_source_dir(), save_cb(), strlcpy, Fl_Button::value(), write_strings(), and x.
Referenced by main().
Variable Documentation
char absolute_history[10][FL_PATH_MAX]
Definition at line 106 of file fluid.cxx.
Referenced by load_history(), main(), and update_history().
const char* code_file_name = ".cxx"
Definition at line 648 of file fluid.cxx.
Referenced by update_sourceview_cb().
int code_file_set = 0
Definition at line 646 of file fluid.cxx.
int compile_only = 0
Definition at line 643 of file fluid.cxx.
Referenced by Fl_Data_Type::write_code1().
int compile_strings = 0
Definition at line 644 of file fluid.cxx.
int exit_early = 0
Definition at line 642 of file fluid.cxx.
Fl_Preferences fluid_prefs(Fl_Preferences::USER,"fltk.org","fluid")
Referenced by exit_cb(), load_history(), make_main_window(), make_settings_window(), make_shell_window(), position_window(), save_position(), save_template_cb(), scheme_cb(), toggle_sourceview_cb(), update_history(), and update_sourceview_cb().
int force_parent
Definition at line 50 of file Fl_Widget_Type.cxx.
int gridx = 5
Definition at line 98 of file fluid.cxx.
Referenced by grid_cb(), h_cb(), Fl_Window_Type::handle(), Fl_Widget_Class_Type::make(), Fl_Window_Type::make(), Fl_Widget_Type::make(), make_main_window(), Fl_Window_Type::newdx(), Fl_Window_Type::open(), paste_cb(), show_grid_cb(), w_cb(), x_cb(), and y_cb().
int gridy = 5
Definition at line 99 of file fluid.cxx.
Referenced by grid_cb(), h_cb(), Fl_Window_Type::handle(), Fl_Widget_Class_Type::make(), Fl_Window_Type::make(), Fl_Widget_Type::make(), make_main_window(), Fl_Window_Type::newdx(), Fl_Window_Type::open(), paste_cb(), show_grid_cb(), w_cb(), x_cb(), and y_cb().
const char* header_file_name = ".h"
Definition at line 647 of file fluid.cxx.
Referenced by update_sourceview_cb(), and write_code().
int header_file_set = 0
Definition at line 645 of file fluid.cxx.
Fl_Menu_Item* history_item = 0L
Definition at line 116 of file fluid.cxx.
const char* i18n_file = ""
Definition at line 652 of file fluid.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), show_project_cb(), write_code(), Fl_Widget_Type::write_code1(), and Fl_Widget_Type::write_widget_code().
const char* i18n_function = ""
Definition at line 651 of file fluid.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), show_project_cb(), Fl_Widget_Type::write_code1(), and Fl_Widget_Type::write_widget_code().
const char* i18n_include = ""
Definition at line 650 of file fluid.cxx.
Referenced by i18n_text_cb(), i18n_type_cb(), show_project_cb(), and write_code().
char i18n_program[FL_PATH_MAX] = ""
Definition at line 654 of file fluid.cxx.
Referenced by write_code().
const char* i18n_set = ""
Definition at line 653 of file fluid.cxx.
Referenced by i18n_int_cb(), i18n_type_cb(), show_project_cb(), Fl_Widget_Type::write_code1(), write_strings(), and Fl_Widget_Type::write_widget_code().
int i18n_type = 0
Definition at line 649 of file fluid.cxx.
Referenced by i18n_type_cb(), show_project_cb(), write_code(), Fl_Widget_Type::write_code1(), write_strings(), and Fl_Widget_Type::write_widget_code().
Fl_Menu_Item Main_Menu[]
Definition at line 1589 of file fluid.cxx.
Fl_Menu_Bar* main_menubar
Definition at line 180 of file fluid.cxx.
Fl_Window* main_window
Definition at line 179 of file fluid.cxx.
int modflag
Definition at line 125 of file fluid.cxx.
Referenced by exit_cb(), new_cb(), open_cb(), open_history_cb(), revert_cb(), set_filename(), set_modflag(), undo_checkpoint(), and undo_clear().
Fl_Menu_Item New_Menu[]
Definition at line 1011 of file factory.cxx.
Referenced by fill_in_New_Menu(), and Fl_Type_make().
int pasteoffset
Definition at line 2507 of file Fl_Widget_Type.cxx.
Referenced by Fl_Widget_Type::read_fdesign(), and Fl_Widget_Type::read_property().
int quit_flag = 0
Definition at line 2276 of file fluid.cxx.
char relative_history[10][FL_PATH_MAX]
Definition at line 107 of file fluid.cxx.
Referenced by load_history(), and update_history().
Fl_Menu_Item* save_item = 0L
Definition at line 115 of file fluid.cxx.
int show_comments = 1
Definition at line 102 of file fluid.cxx.
Referenced by make_main_window(), and make_settings_window().
int show_coredevmenus = 1
Definition at line 103 of file fluid.cxx.
int show_guides = 1
Definition at line 101 of file fluid.cxx.
Referenced by Fl_Window_Type::draw_overlay(), guides_cb(), make_main_window(), and show_grid_cb().
int snap = 1
Definition at line 100 of file fluid.cxx.
Referenced by grid_cb(), Fl_Window_Type::handle(), make_main_window(), Fl_Window_Type::newdx(), and show_grid_cb().
Fl_Menu_Item* sourceview_item = 0L
Definition at line 118 of file fluid.cxx.
Fl_Menu_Item* widgetbin_item = 0L
Definition at line 117 of file fluid.cxx.