SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/print_panel.h File Reference
print_panel.h File Reference
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Progress.H>
Functions
void print_cb (Fl_Return_Button *, void *)
Fl_Double_Window * make_print_panel ()
void print_load ()
void print_update_status ()
Variables
Fl_Double_Window * print_panel
Fl_Group * print_panel_controls
Fl_Choice * print_choice
Fl_Button * print_properties
Fl_Box * print_status
Fl_Round_Button * print_all
Fl_Round_Button * print_pages
Fl_Round_Button * print_selection
Fl_Int_Input * print_from
Fl_Int_Input * print_to
Fl_Spinner * print_copies
Fl_Check_Button * print_collate_button
Fl_Group * print_collate_group [2]
Fl_Progress * print_progress
Fl_Double_Window * print_properties_panel
Fl_Choice * print_page_size
Fl_Button * print_output_mode [4]
Fl_Menu_Item menu_print_page_size []
Function Documentation
Fl_Double_Window* make_print_panel ()
Definition at line 246 of file print_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Button::down_box(), Fl_Menu_::down_box(), Fl_Group::end(), FL_ALIGN_BOTTOM_RIGHT, FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_TOP_LEFT, FL_BACKGROUND2_COLOR, FL_BORDER_BOX, FL_DOWN_BOX, FL_FOREGROUND_COLOR, FL_ROUND_DOWN_BOX, FL_THIN_DOWN_BOX, FL_WHEN_CHANGED, Fl_Widget::hide(), Fl_Widget::image(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Menu_::menu(), print_cb(), print_properties_panel, Fl_Widget::selection_color(), Fl_Window::set_modal(), Fl_Input_::textfont(), Fl_Widget::type(), Fl_Button::value(), and Fl_Widget::when().
void print_cb (Fl_Return_Button * , void *)
Definition at line 1172 of file fluid.cxx.
References Fl_Widget::activate(), Fl::check(), Fl_Widget::deactivate(), Fl_Type::first, fl_alert(), fl_choice(), Fl_File_Chooser::fl_file_chooser(), Fl_File_Chooser::fl_file_chooser_ok_label(), fl_fopen(), FL_VERSION, h, Fl_Double_Window::hide(), Fl_Widget::hide(), i, Fl_Type::is_window(), Fl_Window::label(), Fl_Widget::label(), length, Fl_Progress::maximum(), Fl_Menu_::menu(), Fl_Progress::minimum(), Fl_Window::modal(), Fl_Type::next, NULL, outfile, print_all, print_choice, print_collate_button, print_copies, print_from, print_output_mode, print_page_size, print_pages, print_panel, print_panel_controls, print_progress, print_selection, print_to, ptr, Fl_Window_Type::read_image(), Fl_Group::resizable(), Fl_Type::selected, Fl_Widget::show(), snprintf, Fl_Menu_::text(), Fl_Menu_Item::user_data(), value, Fl_Choice::value(), Fl_Progress::value(), Fl_Input_::value(), Fl_Spinner::value(), Fl_Button::value(), w, and width.
void print_load ()
Definition at line 511 of file print_panel.cxx.
References Fl_Menu_::add(), Fl_Menu_::clear(), FL_MENU_DIVIDER, i, Fl_Menu_::menu(), name, NULL, print_update_status(), Fl_Menu_::size(), Fl_Menu_::text(), Fl_Menu_Item::user_data(), and Fl_Choice::value().
void print_update_status ()
Definition at line 558 of file print_panel.cxx.
References Fl_Preferences::get(), Fl_Widget::label(), Fl_Menu_::menu(), name, NULL, Fl_Button::setonly(), snprintf, Fl_Menu_Item::user_data(), val, and Fl_Choice::value().
Variable Documentation
Fl_Menu_Item menu_print_page_size[]
Definition at line 119 of file print_panel.cxx.
Fl_Round_Button* print_all
Definition at line 55 of file print_panel.cxx.
Referenced by print_cb(), print_menu_cb(), and Fl_PostScript_Printer::start_job().
Fl_Choice* print_choice
Definition at line 41 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Check_Button* print_collate_button
Definition at line 94 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Group* print_collate_group[2]
Definition at line 102 of file print_panel.cxx.
Fl_Spinner* print_copies
Definition at line 80 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Int_Input* print_from
Definition at line 76 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Button* print_output_mode[4]
Definition at line 218 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Choice* print_page_size
Definition at line 117 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Round_Button* print_pages
Definition at line 62 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Double_Window* print_panel
Definition at line 37 of file print_panel.cxx.
Referenced by print_cb(), print_menu_cb(), and Fl_PostScript_Printer::start_job().
Fl_Group* print_panel_controls
Definition at line 39 of file print_panel.cxx.
Referenced by print_cb().
Fl_Progress* print_progress
Definition at line 108 of file print_panel.cxx.
Referenced by print_cb().
Fl_Button* print_properties
Definition at line 47 of file print_panel.cxx.
Fl_Double_Window* print_properties_panel
Definition at line 110 of file print_panel.cxx.
Referenced by make_print_panel().
Fl_Round_Button* print_selection
Definition at line 69 of file print_panel.cxx.
Referenced by print_cb(), print_menu_cb(), and Fl_PostScript_Printer::start_job().
Fl_Box* print_status
Definition at line 53 of file print_panel.cxx.
Fl_Int_Input* print_to
Definition at line 78 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().