SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/Fluid_Image.h File Reference
Fluid_Image.h File Reference
#include <FL/Fl_Shared_Image.H>
Classes
class Fluid_Image
Functions
Fluid_Image * ui_find_image (const char *)
Variables
const char * ui_find_image_name
Function Documentation
Fluid_Image* ui_find_image (const char *)
Definition at line 247 of file Fluid_Image.cxx.
References Fluid_Image::find(), Fl_File_Chooser::fl_file_chooser(), Fl_File_Chooser::fl_file_chooser_ok_label(), goto_source_dir(), leave_source_dir(), name, NULL, and ui_find_image_name.
Referenced by image_browse_cb(), and inactive_browse_cb().
Variable Documentation
const char* ui_find_image_name
Definition at line 246 of file Fluid_Image.cxx.