SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/print_panel.cxx File Reference
print_panel.cxx File Reference
#include "print_panel.h"
#include <stdio.h>
#include <stdlib.h>
#include "../src/flstring.h"
#include <FL/Fl_Preferences.H>
#include <FL/Fl_Pixmap.H>
Functions
Fl_Double_Window * make_print_panel ()
void print_cb (Fl_Return_Button *, void *)
void print_load ()
void print_update_status ()
Variables
Fl_Preferences fluid_prefs
Fl_Double_Window * print_panel = (Fl_Double_Window *)0
Fl_Group * print_panel_controls = (Fl_Group *)0
Fl_Choice * print_choice = (Fl_Choice *)0
Fl_Button * print_properties = (Fl_Button *)0
Fl_Box * print_status = (Fl_Box *)0
Fl_Round_Button * print_all = (Fl_Round_Button *)0
Fl_Round_Button * print_pages = (Fl_Round_Button *)0
Fl_Round_Button * print_selection = (Fl_Round_Button *)0
Fl_Int_Input * print_from = (Fl_Int_Input *)0
Fl_Int_Input * print_to = (Fl_Int_Input *)0
Fl_Spinner * print_copies = (Fl_Spinner *)0
Fl_Check_Button * print_collate_button = (Fl_Check_Button *)0
Fl_Group * print_collate_group [2] = {(Fl_Group *)0}
Fl_Progress * print_progress = (Fl_Progress *)0
Fl_Double_Window * print_properties_panel = (Fl_Double_Window *)0
Fl_Choice * print_page_size = (Fl_Choice *)0
Fl_Menu_Item menu_print_page_size []
Fl_Button * print_output_mode [4] = {(Fl_Button *)0}
Function Documentation
Fl_Double_Window* make_print_panel ()
Definition at line 246 of file print_panel.cxx.
Referenced by print_menu_cb(), and Fl_PostScript_Printer::start_job().
void print_cb (Fl_Return_Button * , void *)
Definition at line 1172 of file fluid.cxx.
void print_load ()
Definition at line 511 of file print_panel.cxx.
Referenced by print_menu_cb(), and Fl_PostScript_Printer::start_job().
void print_update_status ()
Definition at line 558 of file print_panel.cxx.
Referenced by print_load().
Variable Documentation
Fl_Preferences fluid_prefs
Fl_Menu_Item menu_print_page_size[]
Initial value:
 {
 {"Letter", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"A4", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 119 of file print_panel.cxx.
Fl_Round_Button* print_all = (Fl_Round_Button *)0
Definition at line 55 of file print_panel.cxx.
Referenced by print_cb(), print_menu_cb(), and Fl_PostScript_Printer::start_job().
Fl_Choice* print_choice = (Fl_Choice *)0
Definition at line 41 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Check_Button* print_collate_button = (Fl_Check_Button *)0
Definition at line 94 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Group* print_collate_group[2] = {(Fl_Group *)0}
Definition at line 102 of file print_panel.cxx.
Fl_Spinner* print_copies = (Fl_Spinner *)0
Definition at line 80 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Int_Input* print_from = (Fl_Int_Input *)0
Definition at line 76 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Button* print_output_mode[4] = {(Fl_Button *)0}
Definition at line 218 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Choice* print_page_size = (Fl_Choice *)0
Definition at line 117 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Round_Button* print_pages = (Fl_Round_Button *)0
Definition at line 62 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().
Fl_Double_Window* print_panel = (Fl_Double_Window *)0
Definition at line 37 of file print_panel.cxx.
Referenced by print_cb(), print_menu_cb(), and Fl_PostScript_Printer::start_job().
Fl_Group* print_panel_controls = (Fl_Group *)0
Definition at line 39 of file print_panel.cxx.
Referenced by print_cb().
Fl_Progress* print_progress = (Fl_Progress *)0
Definition at line 108 of file print_panel.cxx.
Referenced by print_cb().
Fl_Button* print_properties = (Fl_Button *)0
Definition at line 47 of file print_panel.cxx.
Fl_Double_Window* print_properties_panel = (Fl_Double_Window *)0
Definition at line 110 of file print_panel.cxx.
Referenced by make_print_panel().
Fl_Round_Button* print_selection = (Fl_Round_Button *)0
Definition at line 69 of file print_panel.cxx.
Referenced by print_cb(), print_menu_cb(), and Fl_PostScript_Printer::start_job().
Fl_Box* print_status = (Fl_Box *)0
Definition at line 53 of file print_panel.cxx.
Fl_Int_Input* print_to = (Fl_Int_Input *)0
Definition at line 78 of file print_panel.cxx.
Referenced by print_cb(), and Fl_PostScript_Printer::start_job().