SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/forms_compatability.cxx File Reference
forms_compatability.cxx File Reference
#include <FL/forms.H>
#include <stdlib.h>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Repeat_Button.H>
Functions
void fl_end_form ()
void fl_initialize (int *argc, char **argv, const char *, FL_CMD_OPT *, int)
void fl_show_form (Fl_Window *f, int place, int b, const char *n)
Fl_Widget * fl_do_forms (void)
Fl_Widget * fl_check_forms ()
void fl_set_graphics_mode (int, int)
Fl_Button * fl_add_button (uchar t, int x, int y, int w, int h, const char *l)
void fl_show_message (const char *q1, const char *q2, const char *q3)
void fl_show_alert (const char *q1, const char *q2, const char *q3, int)
int fl_show_question (const char *q1, const char *q2, const char *q3)
int fl_show_choice (const char *q1, const char *q2, const char *q3, int, const char *b0, const char *b1, const char *b2)
char * fl_show_simple_input (const char *str1, const char *defstr)
Variables
char fl_flip = 2
char fl_modal_next
Function Documentation
Fl_Button* fl_add_button (uchar t, int x, int y, int w, int h, const char * l)
Definition at line 154 of file forms_compatability.cxx.
References b, FL_HIDDEN_BUTTON, FL_HIDDEN_RET_BUTTON, FL_INOUT_BUTTON, FL_RADIO_BUTTON, FL_RETURN_BUTTON, FL_TOGGLE_BUTTON, FL_TOUCH_BUTTON, FL_WHEN_CHANGED, Fl_Widget::type(), and Fl_Widget::when().
Referenced by fl_add_bitmapbutton(), and fl_add_pixmapbutton().
Fl_Widget* fl_check_forms ()
Definition at line 134 of file forms_compatability.cxx.
References Fl::check(), and Fl::readqueue().
Referenced by fl_check_only_forms().
Fl_Widget* fl_do_forms (void)
Definition at line 128 of file forms_compatability.cxx.
References Fl::readqueue(), and Fl::wait().
Referenced by fl_do_only_forms().
void fl_end_form ()
Definition at line 35 of file forms_compatability.cxx.
References Fl_Group::current(), and Fl_Group::forms_end().
void fl_initialize (int * argc, char ** argv, const char * , FL_CMD_OPT * , int)
Definition at line 76 of file forms_compatability.cxx.
References Fl::arg(), fl_flip, and i.
void fl_set_graphics_mode (int , int)
Definition at line 139 of file forms_compatability.cxx.
void fl_show_alert (const char * q1, const char * q2, const char * q3, int)
Definition at line 187 of file forms_compatability.cxx.
References fl_alert().
int fl_show_choice (const char * q1, const char * q2, const char * q3, int , const char * b0, const char * b1, const char * b2)
Definition at line 195 of file forms_compatability.cxx.
References fl_choice().
Referenced by fl_show_choices().
void fl_show_form (Fl_Window * f, int place, int b, const char * n)
Definition at line 92 of file forms_compatability.cxx.
References Fl_Window::clear_border(), FL_FREE_SIZE, fl_modal_next, FL_PLACE_CENTER, FL_PLACE_FREE, FL_PLACE_FULLSCREEN, FL_PLACE_GEOMETRY, FL_PLACE_MOUSE, FL_PLACE_POSITION, FL_PLACE_SIZE, FL_TRANSIENT, Fl_Window::free_position(), Fl_Window::fullscreen(), Fl::h(), Fl_Widget::h(), Fl_Window::hotspot(), Fl_Window::label(), Fl_Widget::position(), Fl_Group::resizable(), Fl::screen_xywh(), Fl_Window::set_modal(), Fl_Window::show(), Fl::w(), Fl_Widget::w(), Fl_Widget::x(), and Fl_Widget::y().
void fl_show_message (const char * q1, const char * q2, const char * q3)
Definition at line 183 of file forms_compatability.cxx.
References fl_message().
int fl_show_question (const char * q1, const char * q2, const char * q3)
Definition at line 191 of file forms_compatability.cxx.
References fl_choice().
char* fl_show_simple_input (const char * str1, const char * defstr)
Definition at line 206 of file forms_compatability.cxx.
References fl_input().
Variable Documentation
char fl_flip = 2
Definition at line 34 of file forms_compatability.cxx.
Referenced by fl_initialize(), and Fl_Group::forms_end().
char fl_modal_next
Definition at line 90 of file forms_compatability.cxx.
Referenced by fl_show_form().