SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/function_panel.cxx File Reference
function_panel.cxx File Reference
#include "function_panel.h"
#include <FL/Fl_Pixmap.H>
#include "Fl_Type.h"
#include "undo.h"
Functions
class Fl_Type * Fl_Type_make (const char *)
void select_only (Fl_Type *)
void exit_cb (Fl_Widget *, void *)
void toggle_widgetbin_cb (Fl_Widget *, void *)
Fl_Double_Window * make_function_panel ()
Fl_Double_Window * make_code_panel ()
Fl_Double_Window * make_codeblock_panel ()
Fl_Double_Window * make_declblock_panel ()
Fl_Double_Window * make_decl_panel ()
Fl_Double_Window * make_data_panel ()
Fl_Double_Window * make_class_panel ()
Fl_Double_Window * make_comment_panel ()
void type_make_cb (Fl_Widget *, void *d)
Fl_Window * make_widgetbin ()
Fl_Double_Window * make_sourceview ()
Variables
class Fl_Pixmap * pixmap []
Fl_Double_Window * function_panel = (Fl_Double_Window *)0
Fl_Choice * f_public_member_choice = (Fl_Choice *)0
Fl_Menu_Item menu_f_public_member_choice []
Fl_Choice * f_public_choice = (Fl_Choice *)0
Fl_Menu_Item menu_f_public_choice []
Fl_Light_Button * f_c_button = (Fl_Light_Button *)0
Fl_Input * f_name_input = (Fl_Input *)0
Fl_Input * f_return_type_input = (Fl_Input *)0
Fl_Return_Button * f_panel_ok = (Fl_Return_Button *)0
Fl_Button * f_panel_cancel = (Fl_Button *)0
Fl_Text_Editor * f_comment_input = (Fl_Text_Editor *)0
Fl_Double_Window * code_panel = (Fl_Double_Window *)0
CodeEditor * code_input = (CodeEditor *)0
Fl_Return_Button * code_panel_ok = (Fl_Return_Button *)0
Fl_Button * code_panel_cancel = (Fl_Button *)0
Fl_Double_Window * codeblock_panel = (Fl_Double_Window *)0
Fl_Input * code_before_input = (Fl_Input *)0
Fl_Input * code_after_input = (Fl_Input *)0
Fl_Return_Button * codeblock_panel_ok = (Fl_Return_Button *)0
Fl_Button * codeblock_panel_cancel = (Fl_Button *)0
Fl_Double_Window * declblock_panel = (Fl_Double_Window *)0
Fl_Choice * declblock_public_choice = (Fl_Choice *)0
Fl_Menu_Item menu_declblock_public_choice []
Fl_Light_Button * declblock_public_button_x = (Fl_Light_Button *)0
Fl_Input * decl_before_input = (Fl_Input *)0
Fl_Input * decl_after_input = (Fl_Input *)0
Fl_Return_Button * declblock_panel_ok = (Fl_Return_Button *)0
Fl_Button * declblock_panel_cancel = (Fl_Button *)0
Fl_Double_Window * decl_panel = (Fl_Double_Window *)0
Fl_Choice * decl_choice = (Fl_Choice *)0
Fl_Menu_Item menu_decl_choice []
Fl_Choice * decl_class_choice = (Fl_Choice *)0
Fl_Menu_Item menu_decl_class_choice []
Fl_Input * decl_input = (Fl_Input *)0
Fl_Return_Button * decl_panel_ok = (Fl_Return_Button *)0
Fl_Button * decl_panel_cancel = (Fl_Button *)0
Fl_Text_Editor * decl_comment_input = (Fl_Text_Editor *)0
Fl_Double_Window * data_panel = (Fl_Double_Window *)0
Fl_Choice * data_choice = (Fl_Choice *)0
Fl_Menu_Item menu_data_choice []
Fl_Choice * data_class_choice = (Fl_Choice *)0
Fl_Menu_Item menu_data_class_choice []
Fl_Input * data_input = (Fl_Input *)0
Fl_Input * data_filename = (Fl_Input *)0
Fl_Button * data_filebrowser = (Fl_Button *)0
Fl_Return_Button * data_panel_ok = (Fl_Return_Button *)0
Fl_Button * data_panel_cancel = (Fl_Button *)0
Fl_Text_Editor * data_comment_input = (Fl_Text_Editor *)0
Fl_Double_Window * class_panel = (Fl_Double_Window *)0
Fl_Light_Button * c_public_button = (Fl_Light_Button *)0
Fl_Input * c_name_input = (Fl_Input *)0
Fl_Input * c_subclass_input = (Fl_Input *)0
Fl_Text_Editor * c_comment_input = (Fl_Text_Editor *)0
Fl_Return_Button * c_panel_ok = (Fl_Return_Button *)0
Fl_Button * c_panel_cancel = (Fl_Button *)0
Fl_Double_Window * comment_panel = (Fl_Double_Window *)0
CodeEditor * comment_input = (CodeEditor *)0
Fl_Return_Button * comment_panel_ok = (Fl_Return_Button *)0
Fl_Button * comment_panel_cancel = (Fl_Button *)0
Fl_Light_Button * comment_in_source = (Fl_Light_Button *)0
Fl_Light_Button * comment_in_header = (Fl_Light_Button *)0
Fl_Menu_Button * comment_predefined = (Fl_Menu_Button *)0
Fl_Button * comment_load = (Fl_Button *)0
Fl_Window * widgetbin_panel = (Fl_Window *)0
Fl_Double_Window * sourceview_panel = (Fl_Double_Window *)0
Fl_Tabs * sv_tab = (Fl_Tabs *)0
CodeViewer * sv_source = (CodeViewer *)0
CodeViewer * sv_header = (CodeViewer *)0
Fl_Light_Button * sv_autorefresh = (Fl_Light_Button *)0
Fl_Light_Button * sv_autoposition = (Fl_Light_Button *)0
Function Documentation
void exit_cb (Fl_Widget * , void *)
Definition at line 381 of file fluid.cxx.
References about_panel, Fl_Group::find(), fl_choice(), fluid_prefs, modflag, NULL, save_cb(), save_position(), Fl_Preferences::set(), sourceview_panel, sv_autoposition, sv_autorefresh, sv_tab, undo_clear(), Fl_Tabs::value(), Fl_Button::value(), and widgetbin_panel.
Referenced by main().
class Fl_Type* Fl_Type_make (const char *)
Definition at line 1123 of file factory.cxx.
References Fl_Type::alt_type_name(), i, m, Fl_Type::make(), New_Menu, Fl_Type::type_name(), and Fl_Menu_Item::user_data().
Referenced by read_fdesign(), and type_make_cb().
Fl_Double_Window* make_class_panel ()
Definition at line 543 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Text_Display::buffer(), class_panel, Fl_Group::current(), Fl_Group::end(), FL_ALIGN_TOP_LEFT, FL_DOWN_BOX, FL_WHEN_NEVER, Fl_Widget::hide(), Fl_Window::hotspot(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Group::resizable(), Fl_Window::set_modal(), Fl_Button::shortcut(), Fl_Window::size_range(), Fl_Text_Display::textfont(), Fl_Input_::textfont(), Fl_Text_Display::textsize(), Fl_Input_::textsize(), Fl_Widget::tooltip(), Fl_Widget::when(), and Fl_Widget::window().
Referenced by Fl_Class_Type::open().
Fl_Double_Window* make_code_panel ()
Definition at line 158 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), code_panel, Fl_Widget::color(), Fl_Group::current(), Fl_Group::end(), FL_ALIGN_TOP, FL_BACKGROUND2_COLOR, FL_DOWN_BOX, FL_FOREGROUND_COLOR, FL_NORMAL_LABEL, FL_SELECTION_COLOR, FL_WHEN_ENTER_KEY_CHANGED, FL_WHEN_RELEASE, Fl_Window::hotspot(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), Fl_Group::resizable(), Fl_Widget::selection_color(), Fl_Window::set_modal(), Fl_Button::shortcut(), Fl_Window::size_range(), Fl_Text_Display::textfont(), Fl_Text_Display::textsize(), Fl_Widget::when(), and Fl_Widget::window().
Referenced by Fl_Code_Type::open().
Fl_Double_Window* make_codeblock_panel ()
Definition at line 209 of file function_panel.cxx.
References Fl_Widget::align(), codeblock_panel, Fl_Group::current(), Fl_Group::end(), FL_ALIGN_TOP_LEFT, FL_WHEN_NEVER, Fl_Widget::h(), Fl_Window::hotspot(), Fl_Widget::labelsize(), Fl_Group::resizable(), Fl_Window::set_modal(), Fl_Button::shortcut(), Fl_Window::size_range(), Fl_Input_::textfont(), Fl_Input_::textsize(), Fl_Widget::tooltip(), Fl::w(), Fl_Widget::w(), Fl_Widget::when(), and Fl_Widget::window().
Referenced by Fl_CodeBlock_Type::open().
Fl_Double_Window* make_comment_panel ()
Definition at line 625 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::color(), comment_panel, Fl_Group::current(), Fl_Group::end(), FL_ALIGN_TOP, FL_BACKGROUND2_COLOR, FL_DOWN_BOX, FL_FOREGROUND_COLOR, FL_NORMAL_LABEL, FL_SELECTION_COLOR, FL_WHEN_ENTER_KEY_CHANGED, FL_WHEN_NEVER, FL_WHEN_RELEASE, Fl_Window::hotspot(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), Fl_Group::resizable(), Fl_Widget::selection_color(), Fl_Window::set_modal(), Fl_Button::shortcut(), Fl_Window::size_range(), Fl_Text_Display::textfont(), Fl_Menu_::textsize(), Fl_Text_Display::textsize(), Fl_Widget::tooltip(), Fl_Widget::when(), and Fl_Widget::window().
Referenced by Fl_Comment_Type::open().
Fl_Double_Window* make_data_panel ()
Definition at line 456 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Text_Display::buffer(), Fl_Group::current(), data_panel, Fl_Menu_::down_box(), Fl_Group::end(), FL_ALIGN_CLIP, FL_ALIGN_INSIDE, FL_ALIGN_TOP_LEFT, FL_BORDER_BOX, FL_DOWN_BOX, FL_WHEN_NEVER, Fl_Window::hotspot(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Menu_::menu(), Fl_Group::resizable(), Fl_Button::shortcut(), Fl_Window::size_range(), Fl_Text_Display::textfont(), Fl_Input_::textfont(), Fl_Text_Display::textsize(), Fl_Input_::textsize(), Fl_Menu_::textsize(), Fl_Widget::tooltip(), Fl_Widget::when(), and Fl_Widget::window().
Referenced by Fl_Data_Type::open().
Fl_Double_Window* make_decl_panel ()
Definition at line 360 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Text_Display::buffer(), Fl_Group::current(), decl_panel, Fl_Menu_::down_box(), Fl_Group::end(), FL_ALIGN_CLIP, FL_ALIGN_INSIDE, FL_ALIGN_TOP_LEFT, FL_BORDER_BOX, FL_DOWN_BOX, FL_WHEN_NEVER, Fl_Window::hotspot(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Menu_::menu(), Fl_Group::resizable(), Fl_Button::shortcut(), Fl_Window::size_range(), Fl_Text_Display::textfont(), Fl_Input_::textfont(), Fl_Text_Display::textsize(), Fl_Input_::textsize(), Fl_Menu_::textsize(), Fl_Widget::tooltip(), Fl_Widget::when(), and Fl_Widget::window().
Referenced by Fl_Decl_Type::open().
Fl_Double_Window* make_declblock_panel ()
Definition at line 270 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Group::current(), declblock_panel, Fl_Menu_::down_box(), Fl_Group::end(), FL_ALIGN_TOP_LEFT, FL_BORDER_BOX, FL_WHEN_NEVER, Fl_Widget::h(), Fl_Widget::hide(), Fl_Window::hotspot(), Fl_Widget::labelsize(), Fl_Menu_::menu(), Fl_Group::resizable(), Fl_Window::set_modal(), Fl_Button::shortcut(), Fl_Window::size_range(), Fl_Input_::textfont(), Fl_Input_::textsize(), Fl_Menu_::textsize(), Fl_Widget::tooltip(), Fl::w(), Fl_Widget::w(), Fl_Widget::when(), and Fl_Widget::window().
Referenced by Fl_DeclBlock_Type::open().
Fl_Double_Window* make_function_panel ()
Definition at line 71 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Text_Display::buffer(), Fl_Group::current(), Fl_Menu_::down_box(), Fl_Group::end(), FL_ALIGN_TOP_LEFT, FL_BORDER_BOX, FL_DOWN_BOX, FL_WHEN_CHANGED, FL_WHEN_NEVER, function_panel, Fl_Window::hotspot(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Menu_::menu(), Fl_Group::resizable(), Fl_Window::set_modal(), Fl_Button::shortcut(), Fl_Text_Display::textfont(), Fl_Input_::textfont(), Fl_Text_Display::textsize(), Fl_Input_::textsize(), Fl_Menu_::textsize(), Fl_Widget::tooltip(), Fl_Widget::when(), and Fl_Widget::window().
Referenced by Fl_Function_Type::open().
Fl_Double_Window* make_sourceview ()
Definition at line 1071 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Group::current(), Fl_Group::end(), FL_ALIGN_CLIP, FL_ALIGN_INSIDE, FL_ALIGN_TOP, FL_BACKGROUND2_COLOR, FL_DOWN_FRAME, FL_FOREGROUND_COLOR, FL_NORMAL_LABEL, FL_SELECTION_COLOR, FL_WHEN_RELEASE, Fl_Widget::hide(), Fl_Widget::labelcolor(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Widget::labeltype(), Fl_Group::resizable(), Fl_Widget::selection_color(), Fl_Window::size_range(), sourceview_panel, Fl_Text_Display::textfont(), Fl_Text_Display::textsize(), toggle_sourceview_b_cb(), toggle_sourceview_cb(), update_sourceview_cb(), update_sourceview_position_cb(), and Fl_Widget::when().
Referenced by toggle_sourceview_cb().
Fl_Window* make_widgetbin ()
Definition at line 713 of file function_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Group::end(), FL_ALIGN_CLIP, FL_ALIGN_INSIDE, FL_THIN_UP_BOX, Fl_Widget::image(), Fl_Window::set_non_modal(), Fl_Widget::tooltip(), type_make_cb(), and widgetbin_panel.
Referenced by toggle_widgetbin_cb().
void select_only (Fl_Type *)
Definition at line 209 of file Fl_Type.cxx.
References Fl_Browser_::select_only().
void toggle_widgetbin_cb (Fl_Widget * , void *)
Definition at line 1711 of file fluid.cxx.
References Fl_Window::hide(), Fl_Menu_Item::label(), make_widgetbin(), position_window(), Fl_Window::show(), Fl_Widget::visible(), and widgetbin_panel.
Referenced by main(), and make_main_window().
void type_make_cb (Fl_Widget * , void * d)
Definition at line 691 of file function_panel.cxx.
References Fl_Type_make(), Fl_Type::open(), select_only(), set_modflag(), undo_checkpoint(), undo_current, and undo_last.
Referenced by make_widgetbin().
Variable Documentation
Fl_Text_Editor* c_comment_input = (Fl_Text_Editor *)0
Definition at line 537 of file function_panel.cxx.
Referenced by Fl_Class_Type::open().
Fl_Input* c_name_input = (Fl_Input *)0
Definition at line 533 of file function_panel.cxx.
Referenced by Fl_Class_Type::open().
Fl_Button* c_panel_cancel = (Fl_Button *)0
Definition at line 541 of file function_panel.cxx.
Referenced by Fl_Class_Type::open().
Fl_Return_Button* c_panel_ok = (Fl_Return_Button *)0
Definition at line 539 of file function_panel.cxx.
Referenced by Fl_Class_Type::open().
Fl_Light_Button* c_public_button = (Fl_Light_Button *)0
Definition at line 531 of file function_panel.cxx.
Referenced by Fl_Class_Type::open().
Fl_Input* c_subclass_input = (Fl_Input *)0
Definition at line 535 of file function_panel.cxx.
Referenced by Fl_Class_Type::open().
Fl_Double_Window* class_panel = (Fl_Double_Window *)0
Definition at line 529 of file function_panel.cxx.
Referenced by make_class_panel(), and Fl_Class_Type::open().
Fl_Input* code_after_input = (Fl_Input *)0
Definition at line 203 of file function_panel.cxx.
Referenced by Fl_CodeBlock_Type::open().
Fl_Input* code_before_input = (Fl_Input *)0
Definition at line 201 of file function_panel.cxx.
Referenced by Fl_CodeBlock_Type::open().
CodeEditor* code_input = (CodeEditor *)0
Definition at line 152 of file function_panel.cxx.
Referenced by Fl_Code_Type::open().
Fl_Double_Window* code_panel = (Fl_Double_Window *)0
Definition at line 150 of file function_panel.cxx.
Referenced by make_code_panel(), and Fl_Code_Type::open().
Fl_Button* code_panel_cancel = (Fl_Button *)0
Definition at line 156 of file function_panel.cxx.
Referenced by Fl_Code_Type::open().
Fl_Return_Button* code_panel_ok = (Fl_Return_Button *)0
Definition at line 154 of file function_panel.cxx.
Referenced by Fl_Code_Type::open().
Fl_Double_Window* codeblock_panel = (Fl_Double_Window *)0
Definition at line 199 of file function_panel.cxx.
Referenced by make_codeblock_panel(), and Fl_CodeBlock_Type::open().
Fl_Button* codeblock_panel_cancel = (Fl_Button *)0
Definition at line 207 of file function_panel.cxx.
Referenced by Fl_CodeBlock_Type::open().
Fl_Return_Button* codeblock_panel_ok = (Fl_Return_Button *)0
Definition at line 205 of file function_panel.cxx.
Referenced by Fl_CodeBlock_Type::open().
Fl_Light_Button* comment_in_header = (Fl_Light_Button *)0
Definition at line 619 of file function_panel.cxx.
Referenced by Fl_Comment_Type::open().
Fl_Light_Button* comment_in_source = (Fl_Light_Button *)0
Definition at line 617 of file function_panel.cxx.
Referenced by Fl_Comment_Type::open().
CodeEditor* comment_input = (CodeEditor *)0
Definition at line 611 of file function_panel.cxx.
Referenced by Fl_Comment_Type::open().
Fl_Button* comment_load = (Fl_Button *)0
Definition at line 623 of file function_panel.cxx.
Referenced by Fl_Comment_Type::open().
Fl_Double_Window* comment_panel = (Fl_Double_Window *)0
Definition at line 609 of file function_panel.cxx.
Referenced by make_comment_panel(), and Fl_Comment_Type::open().
Fl_Button* comment_panel_cancel = (Fl_Button *)0
Definition at line 615 of file function_panel.cxx.
Referenced by Fl_Comment_Type::open().
Fl_Return_Button* comment_panel_ok = (Fl_Return_Button *)0
Definition at line 613 of file function_panel.cxx.
Referenced by Fl_Comment_Type::open().
Fl_Menu_Button* comment_predefined = (Fl_Menu_Button *)0
Definition at line 621 of file function_panel.cxx.
Referenced by Fl_Comment_Type::open().
Fl_Choice* data_choice = (Fl_Choice *)0
Definition at line 425 of file function_panel.cxx.
Referenced by Fl_Data_Type::open().
Fl_Choice* data_class_choice = (Fl_Choice *)0
Definition at line 435 of file function_panel.cxx.
Referenced by Fl_Data_Type::open().
Fl_Text_Editor* data_comment_input = (Fl_Text_Editor *)0
Definition at line 454 of file function_panel.cxx.
Referenced by Fl_Data_Type::open().
Fl_Button* data_filebrowser = (Fl_Button *)0
Definition at line 448 of file function_panel.cxx.
Referenced by Fl_Data_Type::open().
Fl_Input* data_filename = (Fl_Input *)0
Definition at line 446 of file function_panel.cxx.
Referenced by Fl_Data_Type::open().
Fl_Input* data_input = (Fl_Input *)0
Definition at line 444 of file function_panel.cxx.
Referenced by Fl_Data_Type::open().
Fl_Double_Window* data_panel = (Fl_Double_Window *)0
Definition at line 423 of file function_panel.cxx.
Referenced by make_data_panel(), and Fl_Data_Type::open().
Fl_Button* data_panel_cancel = (Fl_Button *)0
Definition at line 452 of file function_panel.cxx.
Referenced by Fl_Data_Type::open().
Fl_Return_Button* data_panel_ok = (Fl_Return_Button *)0
Definition at line 450 of file function_panel.cxx.
Referenced by Fl_Data_Type::open().
Fl_Input* decl_after_input = (Fl_Input *)0
Definition at line 264 of file function_panel.cxx.
Referenced by Fl_DeclBlock_Type::open().
Fl_Input* decl_before_input = (Fl_Input *)0
Definition at line 262 of file function_panel.cxx.
Referenced by Fl_DeclBlock_Type::open().
Fl_Choice* decl_choice = (Fl_Choice *)0
Definition at line 333 of file function_panel.cxx.
Referenced by Fl_Decl_Type::open().
Fl_Choice* decl_class_choice = (Fl_Choice *)0
Definition at line 343 of file function_panel.cxx.
Referenced by Fl_Decl_Type::open().
Fl_Text_Editor* decl_comment_input = (Fl_Text_Editor *)0
Definition at line 358 of file function_panel.cxx.
Referenced by Fl_Decl_Type::open().
Fl_Input* decl_input = (Fl_Input *)0
Definition at line 352 of file function_panel.cxx.
Referenced by Fl_Decl_Type::open().
Fl_Double_Window* decl_panel = (Fl_Double_Window *)0
Definition at line 331 of file function_panel.cxx.
Referenced by make_decl_panel(), and Fl_Decl_Type::open().
Fl_Button* decl_panel_cancel = (Fl_Button *)0
Definition at line 356 of file function_panel.cxx.
Referenced by Fl_Decl_Type::open().
Fl_Return_Button* decl_panel_ok = (Fl_Return_Button *)0
Definition at line 354 of file function_panel.cxx.
Referenced by Fl_Decl_Type::open().
Fl_Double_Window* declblock_panel = (Fl_Double_Window *)0
Definition at line 250 of file function_panel.cxx.
Referenced by make_declblock_panel(), and Fl_DeclBlock_Type::open().
Fl_Button* declblock_panel_cancel = (Fl_Button *)0
Definition at line 268 of file function_panel.cxx.
Referenced by Fl_DeclBlock_Type::open().
Fl_Return_Button* declblock_panel_ok = (Fl_Return_Button *)0
Definition at line 266 of file function_panel.cxx.
Referenced by Fl_DeclBlock_Type::open().
Fl_Light_Button* declblock_public_button_x = (Fl_Light_Button *)0
Definition at line 260 of file function_panel.cxx.
Fl_Choice* declblock_public_choice = (Fl_Choice *)0
Definition at line 252 of file function_panel.cxx.
Referenced by Fl_DeclBlock_Type::open().
Fl_Light_Button* f_c_button = (Fl_Light_Button *)0
Definition at line 59 of file function_panel.cxx.
Referenced by Fl_Function_Type::open().
Fl_Text_Editor* f_comment_input = (Fl_Text_Editor *)0
Definition at line 69 of file function_panel.cxx.
Referenced by Fl_Function_Type::open().
Fl_Input* f_name_input = (Fl_Input *)0
Definition at line 61 of file function_panel.cxx.
Referenced by Fl_Function_Type::open().
Fl_Button* f_panel_cancel = (Fl_Button *)0
Definition at line 67 of file function_panel.cxx.
Referenced by Fl_Function_Type::open().
Fl_Return_Button* f_panel_ok = (Fl_Return_Button *)0
Definition at line 65 of file function_panel.cxx.
Referenced by Fl_Function_Type::open().
Fl_Choice* f_public_choice = (Fl_Choice *)0
Definition at line 51 of file function_panel.cxx.
Referenced by Fl_Function_Type::open().
Fl_Choice* f_public_member_choice = (Fl_Choice *)0
Definition at line 42 of file function_panel.cxx.
Referenced by Fl_Function_Type::open().
Fl_Input* f_return_type_input = (Fl_Input *)0
Definition at line 63 of file function_panel.cxx.
Referenced by Fl_Function_Type::open().
Fl_Double_Window* function_panel = (Fl_Double_Window *)0
Definition at line 40 of file function_panel.cxx.
Referenced by make_function_panel(), and Fl_Function_Type::open().
Fl_Menu_Item menu_data_choice[]
Initial value:
 {
 {"in source file only", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"in header file only", 0,  0, 0, 16, FL_NORMAL_LABEL, 0, 11, 0},
 {"\"static\" in source file", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"in source and \"extern\" in header", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 427 of file function_panel.cxx.
Fl_Menu_Item menu_data_class_choice[]
Initial value:
 {
 {"private", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"public", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"protected", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 437 of file function_panel.cxx.
Fl_Menu_Item menu_decl_choice[]
Initial value:
 {
 {"in source file only", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"in header file only", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"\"static\" in source file", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"in source and \"extern\" in header", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 335 of file function_panel.cxx.
Fl_Menu_Item menu_decl_class_choice[]
Initial value:
 {
 {"private", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"public", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"protected", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 345 of file function_panel.cxx.
Fl_Menu_Item menu_declblock_public_choice[]
Initial value:
 {
 {"in source code only", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"in header and source", 0,  0, (void*)(1), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 254 of file function_panel.cxx.
Fl_Menu_Item menu_f_public_choice[]
Initial value:
 {
 {"local", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"global", 0,  0, (void*)(1), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 53 of file function_panel.cxx.
Fl_Menu_Item menu_f_public_member_choice[]
Initial value:
 {
 {"private", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"public", 0,  0, (void*)(1), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"protected", 0,  0, (void*)(2), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 44 of file function_panel.cxx.
class Fl_Pixmap* pixmap[]
Definition at line 163 of file Fl_Type.cxx.
Fl_Double_Window* sourceview_panel = (Fl_Double_Window *)0
Definition at line 1059 of file function_panel.cxx.
Referenced by exit_cb(), make_sourceview(), set_modflag(), toggle_sourceview_cb(), update_sourceview_cb(), and update_sourceview_position().
Fl_Light_Button* sv_autoposition = (Fl_Light_Button *)0
Definition at line 1069 of file function_panel.cxx.
Referenced by exit_cb(), toggle_sourceview_cb(), and update_sourceview_position().
Fl_Light_Button* sv_autorefresh = (Fl_Light_Button *)0
Definition at line 1067 of file function_panel.cxx.
Referenced by exit_cb(), set_modflag(), and toggle_sourceview_cb().
CodeViewer* sv_header = (CodeViewer *)0
Definition at line 1065 of file function_panel.cxx.
Referenced by update_sourceview_cb(), and update_sourceview_position().
CodeViewer* sv_source = (CodeViewer *)0
Definition at line 1063 of file function_panel.cxx.
Referenced by update_sourceview_cb(), and update_sourceview_position().
Fl_Tabs* sv_tab = (Fl_Tabs *)0
Definition at line 1061 of file function_panel.cxx.
Referenced by exit_cb(), and toggle_sourceview_cb().
Fl_Window* widgetbin_panel = (Fl_Window *)0
Definition at line 704 of file function_panel.cxx.
Referenced by exit_cb(), make_widgetbin(), and toggle_widgetbin_cb().