SfR Fresh Dox - fltk: fltk-1.3.0rc3/FL/gl2opengl.h File Reference
gl2opengl.h File Reference
#include <FL/gl.h>
#include "gl_draw.H"
Defines
#define RGBcolor(r, g, b) glColor3ub(r,g,b)
#define bgnline() glBegin(GL_LINE_STRIP)
#define bgnpolygon() glBegin(GL_POLYGON)
#define bgnclosedline() glBegin(GL_LINE_LOOP)
#define endline() glEnd()
#define endpolygon() glEnd()
#define endclosedline() glEnd()
#define v2f(v) glVertex2fv(v)
#define v2s(v) glVertex2sv(v)
#define cmov(x, y, z) glRasterPos3f(x,y,z)
#define charstr(s) gl_draw(s)
#define fmprstr(s) gl_draw(s)
Typedefs
typedef float Matrix [4][4]
Functions
void clear ()
void pushmatrix ()
void popmatrix ()
void multmatrix (Matrix m)
void color (int n)
void rect (int x, int y, int r, int t)
void rectf (int x, int y, int r, int t)
void recti (int x, int y, int r, int t)
void rectfi (int x, int y, int r, int t)
void rects (int x, int y, int r, int t)
void rectfs (int x, int y, int r, int t)
Define Documentation
#define bgnclosedline () glBegin(GL_LINE_LOOP)
Definition at line 16 of file gl2opengl.h.
#define bgnline () glBegin(GL_LINE_STRIP)
Definition at line 14 of file gl2opengl.h.
#define bgnpolygon () glBegin(GL_POLYGON)
Definition at line 15 of file gl2opengl.h.
#define charstr (s) gl_draw(s)
Definition at line 23 of file gl2opengl.h.
#define cmov (x, y, z) glRasterPos3f(x,y,z)
Definition at line 22 of file gl2opengl.h.
#define endclosedline () glEnd()
Definition at line 19 of file gl2opengl.h.
#define endline () glEnd()
Definition at line 17 of file gl2opengl.h.
Referenced by Fl_Text_Buffer::insertfile().
#define endpolygon () glEnd()
Definition at line 18 of file gl2opengl.h.
#define fmprstr (s) gl_draw(s)
Definition at line 24 of file gl2opengl.h.
#define RGBcolor (r, g, b) glColor3ub(r,g,b)
Definition at line 13 of file gl2opengl.h.
#define v2f (v) glVertex2fv(v)
Definition at line 20 of file gl2opengl.h.
#define v2s (v) glVertex2sv(v)
Definition at line 21 of file gl2opengl.h.
Typedef Documentation
typedef float Matrix[4][4]
Definition at line 25 of file gl2opengl.h.
Function Documentation
void clear () [inline]
Definition at line 12 of file gl2opengl.h.
void color (int n) [inline]
Definition at line 29 of file gl2opengl.h.
Referenced by Fl_Pixmap::color_average(), Fl_Menu_Item::draw(), and Fl_BMP_Image::Fl_BMP_Image().
void multmatrix (Matrix m) [inline]
Definition at line 28 of file gl2opengl.h.
void popmatrix () [inline]
Definition at line 27 of file gl2opengl.h.
void pushmatrix () [inline]
Definition at line 26 of file gl2opengl.h.
void rect (int x, int y, int r, int t) [inline]
Definition at line 30 of file gl2opengl.h.
References gl_rect().
Referenced by Fl_Clock_Output::draw(), fl_draw_pixmap(), fl_scroll(), fl_text_extents(), and Fl_X::make().
void rectf (int x, int y, int r, int t) [inline]
Definition at line 31 of file gl2opengl.h.
void rectfi (int x, int y, int r, int t) [inline]
Definition at line 33 of file gl2opengl.h.
void rectfs (int x, int y, int r, int t) [inline]
Definition at line 35 of file gl2opengl.h.
void recti (int x, int y, int r, int t) [inline]
Definition at line 32 of file gl2opengl.h.
References gl_rect().
void rects (int x, int y, int r, int t) [inline]
Definition at line 34 of file gl2opengl.h.
References gl_rect().