SfR Fresh Dox - fltk: fltk-1.3.0rc3/FL/glut.H File Reference
glut.H File Reference
#include "gl.h"
#include "Fl.H"
#include "Fl_Gl_Window.H"
Classes
class Fl_Glut_Window
struct Fl_Glut_Bitmap_Font
struct Fl_Glut_StrokeVertex
struct Fl_Glut_StrokeStrip
struct Fl_Glut_StrokeChar
struct Fl_Glut_StrokeFont
Defines
#define GLUT_RGB FL_RGB
#define GLUT_RGBA FL_RGB
#define GLUT_INDEX FL_INDEX
#define GLUT_SINGLE FL_SINGLE
#define GLUT_DOUBLE FL_DOUBLE
#define GLUT_ACCUM FL_ACCUM
#define GLUT_ALPHA FL_ALPHA
#define GLUT_DEPTH FL_DEPTH
#define GLUT_STENCIL FL_STENCIL
#define GLUT_MULTISAMPLE FL_MULTISAMPLE
#define GLUT_STEREO FL_STEREO
#define GLUT_CURSOR_RIGHT_ARROW ((Fl_Cursor)2)
#define GLUT_CURSOR_LEFT_ARROW ((Fl_Cursor)67)
#define GLUT_CURSOR_INFO FL_CURSOR_HAND
#define GLUT_CURSOR_DESTROY ((Fl_Cursor)45)
#define GLUT_CURSOR_HELP FL_CURSOR_HELP
#define GLUT_CURSOR_CYCLE ((Fl_Cursor)26)
#define GLUT_CURSOR_SPRAY ((Fl_Cursor)63)
#define GLUT_CURSOR_WAIT FL_CURSOR_WAIT
#define GLUT_CURSOR_TEXT FL_CURSOR_INSERT
#define GLUT_CURSOR_CROSSHAIR FL_CURSOR_CROSS
#define GLUT_CURSOR_UP_DOWN FL_CURSOR_NS
#define GLUT_CURSOR_LEFT_RIGHT FL_CURSOR_WE
#define GLUT_CURSOR_TOP_SIDE FL_CURSOR_N
#define GLUT_CURSOR_BOTTOM_SIDE FL_CURSOR_S
#define GLUT_CURSOR_LEFT_SIDE FL_CURSOR_W
#define GLUT_CURSOR_RIGHT_SIDE FL_CURSOR_E
#define GLUT_CURSOR_TOP_LEFT_CORNER FL_CURSOR_NW
#define GLUT_CURSOR_TOP_RIGHT_CORNER FL_CURSOR_NE
#define GLUT_CURSOR_BOTTOM_RIGHT_CORNER FL_CURSOR_SE
#define GLUT_CURSOR_BOTTOM_LEFT_CORNER FL_CURSOR_SW
#define GLUT_CURSOR_INHERIT FL_CURSOR_DEFAULT
#define GLUT_CURSOR_NONE FL_CURSOR_NONE
#define GLUT_CURSOR_FULL_CROSSHAIR FL_CURSOR_CROSS
#define GLUT_LEFT_BUTTON 0
#define GLUT_MIDDLE_BUTTON 1
#define GLUT_RIGHT_BUTTON 2
#define GLUT_DOWN 0
#define GLUT_UP 1
#define GLUT_KEY_F1 1
#define GLUT_KEY_F2 2
#define GLUT_KEY_F3 3
#define GLUT_KEY_F4 4
#define GLUT_KEY_F5 5
#define GLUT_KEY_F6 6
#define GLUT_KEY_F7 7
#define GLUT_KEY_F8 8
#define GLUT_KEY_F9 9
#define GLUT_KEY_F10 10
#define GLUT_KEY_F11 11
#define GLUT_KEY_F12 12
#define GLUT_KEY_LEFT FL_Left
#define GLUT_KEY_UP FL_Up
#define GLUT_KEY_RIGHT FL_Right
#define GLUT_KEY_DOWN FL_Down
#define GLUT_KEY_PAGE_UP FL_Page_Up
#define GLUT_KEY_PAGE_DOWN FL_Page_Down
#define GLUT_KEY_HOME FL_Home
#define GLUT_KEY_END FL_End
#define GLUT_KEY_INSERT FL_Insert
#define GLUT_WINDOW_STENCIL_SIZE GL_STENCIL_BITS
#define GLUT_WINDOW_DEPTH_SIZE GL_DEPTH_BITS
#define GLUT_WINDOW_RED_SIZE GL_RED_BITS
#define GLUT_WINDOW_GREEN_SIZE GL_GREEN_BITS
#define GLUT_WINDOW_BLUE_SIZE GL_BLUE_BITS
#define GLUT_WINDOW_ALPHA_SIZE GL_ALPHA_BITS
#define GLUT_WINDOW_ACCUM_RED_SIZE GL_ACCUM_RED_BITS
#define GLUT_WINDOW_ACCUM_GREEN_SIZE GL_ACCUM_GREEN_BITS
#define GLUT_WINDOW_ACCUM_BLUE_SIZE GL_ACCUM_BLUE_BITS
#define GLUT_WINDOW_ACCUM_ALPHA_SIZE GL_ACCUM_ALPHA_BITS
#define GLUT_WINDOW_DOUBLEBUFFER GL_DOUBLEBUFFER
#define GLUT_WINDOW_RGBA GL_RGBA
#define GLUT_WINDOW_COLORMAP_SIZE GL_INDEX_BITS
#define GLUT_WINDOW_NUM_SAMPLES GLUT_RETURN_ZERO
#define GLUT_WINDOW_STEREO GL_STEREO
#define GLUT_HAS_KEYBOARD 600
#define GLUT_HAS_MOUSE 601
#define GLUT_HAS_SPACEBALL 602
#define GLUT_HAS_DIAL_AND_BUTTON_BOX 603
#define GLUT_HAS_TABLET 604
#define GLUT_NUM_MOUSE_BUTTONS 605
#define GLUT_NUM_SPACEBALL_BUTTONS 606
#define GLUT_NUM_BUTTON_BOX_BUTTONS 607
#define GLUT_NUM_DIALS 608
#define GLUT_NUM_TABLET_BUTTONS 609
#define GLUT_ACTIVE_SHIFT FL_SHIFT
#define GLUT_ACTIVE_CTRL FL_CTRL
#define GLUT_ACTIVE_ALT FL_ALT
#define GLUT_OVERLAY_POSSIBLE 800
#define GLUT_TRANSPARENT_INDEX 803
#define GLUT_NORMAL_DAMAGED 804
#define GLUT_OVERLAY_DAMAGED 805
#define GLUT_BITMAP_9_BY_15 (&glutBitmap9By15)
#define GLUT_BITMAP_8_BY_13 (&glutBitmap8By13)
#define GLUT_BITMAP_TIMES_ROMAN_10 (&glutBitmapTimesRoman10)
#define GLUT_BITMAP_TIMES_ROMAN_24 (&glutBitmapTimesRoman24)
#define GLUT_BITMAP_HELVETICA_10 (&glutBitmapHelvetica10)
#define GLUT_BITMAP_HELVETICA_12 (&glutBitmapHelvetica12)
#define GLUT_BITMAP_HELVETICA_18 (&glutBitmapHelvetica18)
#define GLUT_STROKE_ROMAN (&glutStrokeRoman)
#define GLUT_STROKE_MONO_ROMAN (&glutStrokeMonoRoman)
Typedefs
typedef void(* GLUTproc)()
Enumerations
enum { GLUT_NORMAL, GLUT_OVERLAY }
enum { GLUT_LEFT, GLUT_ENTERED }
enum { GLUT_NOT_VISIBLE, GLUT_VISIBLE }
enum { GLUT_MENU_NOT_IN_USE, GLUT_MENU_IN_USE }
enum {
GLUT_RETURN_ZERO = 0, GLUT_WINDOW_X, GLUT_WINDOW_Y, GLUT_WINDOW_WIDTH,
GLUT_WINDOW_HEIGHT, GLUT_WINDOW_PARENT, GLUT_SCREEN_WIDTH, GLUT_SCREEN_HEIGHT,
GLUT_MENU_NUM_ITEMS, GLUT_DISPLAY_MODE_POSSIBLE, GLUT_INIT_WINDOW_X, GLUT_INIT_WINDOW_Y,
GLUT_INIT_WINDOW_WIDTH, GLUT_INIT_WINDOW_HEIGHT, GLUT_INIT_DISPLAY_MODE, GLUT_WINDOW_BUFFER_SIZE,
GLUT_VERSION
}
Functions
FL_EXPORT void glutInit (int *argcp, char **argv)
FL_EXPORT void glutInitDisplayMode (unsigned int mode)
FL_EXPORT void glutInitWindowPosition (int x, int y)
FL_EXPORT void glutInitWindowSize (int w, int h)
FL_EXPORT void glutMainLoop ()
FL_EXPORT int glutCreateWindow (char *title)
FL_EXPORT int glutCreateWindow (const char *title)
FL_EXPORT int glutCreateSubWindow (int win, int x, int y, int width, int height)
FL_EXPORT void glutDestroyWindow (int win)
void glutPostRedisplay ()
FL_EXPORT void glutPostWindowRedisplay (int win)
FL_EXPORT void glutSwapBuffers ()
int glutGetWindow ()
FL_EXPORT void glutSetWindow (int win)
void glutSetWindowTitle (char *t)
void glutSetIconTitle (char *t)
void glutPositionWindow (int x, int y)
void glutReshapeWindow (int w, int h)
void glutPopWindow ()
void glutPushWindow ()
void glutIconifyWindow ()
void glutShowWindow ()
void glutHideWindow ()
void glutFullScreen ()
void glutSetCursor (Fl_Cursor cursor)
void glutWarpPointer (int, int)
void glutEstablishOverlay ()
void glutRemoveOverlay ()
void glutUseLayer (GLenum layer)
void glutPostOverlayRedisplay ()
void glutShowOverlay ()
void glutHideOverlay ()
FL_EXPORT int glutCreateMenu (void(*)(int))
FL_EXPORT void glutDestroyMenu (int menu)
int glutGetMenu ()
void glutSetMenu (int m)
FL_EXPORT void glutAddMenuEntry (char *label, int value)
FL_EXPORT void glutAddSubMenu (char *label, int submenu)
FL_EXPORT void glutChangeToMenuEntry (int item, char *labela, int value)
FL_EXPORT void glutChangeToSubMenu (int item, char *label, int submenu)
FL_EXPORT void glutRemoveMenuItem (int item)
void glutAttachMenu (int b)
void glutDetachMenu (int b)
void glutDisplayFunc (void(*f)())
void glutReshapeFunc (void(*f)(int w, int h))
void glutKeyboardFunc (void(*f)(uchar key, int x, int y))
void glutMouseFunc (void(*f)(int b, int state, int x, int y))
void glutMotionFunc (void(*f)(int x, int y))
void glutPassiveMotionFunc (void(*f)(int x, int y))
void glutEntryFunc (void(*f)(int s))
void glutVisibilityFunc (void(*f)(int s))
FL_EXPORT void glutIdleFunc (void(*f)())
void glutTimerFunc (unsigned int msec, void(*f)(int), int value)
void glutMenuStateFunc (void(*f)(int state))
void glutMenuStatusFunc (void(*f)(int status, int x, int y))
void glutSpecialFunc (void(*f)(int key, int x, int y))
void glutOverlayDisplayFunc (void(*f)())
FL_EXPORT int glutGet (GLenum type)
FL_EXPORT int glutDeviceGet (GLenum type)
int glutGetModifiers ()
FL_EXPORT int glutLayerGet (GLenum)
FL_EXPORT GLUTproc glutGetProcAddress (const char *procName)
FL_EXPORT void glutBitmapCharacter (void *font, int character)
FL_EXPORT int glutBitmapHeight (void *font)
FL_EXPORT int glutBitmapLength (void *font, const unsigned char *string)
FL_EXPORT void glutBitmapString (void *font, const unsigned char *string)
FL_EXPORT int glutBitmapWidth (void *font, int character)
FL_EXPORT int glutExtensionSupported (char *name)
FL_EXPORT void glutStrokeCharacter (void *font, int character)
FL_EXPORT GLfloat glutStrokeHeight (void *font)
FL_EXPORT int glutStrokeLength (void *font, const unsigned char *string)
FL_EXPORT void glutStrokeString (void *font, const unsigned char *string)
FL_EXPORT int glutStrokeWidth (void *font, int character)
FL_EXPORT void glutWireSphere (GLdouble radius, GLint slices, GLint stacks)
FL_EXPORT void glutSolidSphere (GLdouble radius, GLint slices, GLint stacks)
FL_EXPORT void glutWireCone (GLdouble base, GLdouble height, GLint slices, GLint stacks)
FL_EXPORT void glutSolidCone (GLdouble base, GLdouble height, GLint slices, GLint stacks)
FL_EXPORT void glutWireCube (GLdouble size)
FL_EXPORT void glutSolidCube (GLdouble size)
FL_EXPORT void glutWireTorus (GLdouble innerRadius, GLdouble outerRadius, GLint sides, GLint rings)
FL_EXPORT void glutSolidTorus (GLdouble innerRadius, GLdouble outerRadius, GLint sides, GLint rings)
FL_EXPORT void glutWireDodecahedron ()
FL_EXPORT void glutSolidDodecahedron ()
FL_EXPORT void glutWireTeapot (GLdouble size)
FL_EXPORT void glutSolidTeapot (GLdouble size)
FL_EXPORT void glutWireOctahedron ()
FL_EXPORT void glutSolidOctahedron ()
FL_EXPORT void glutWireTetrahedron ()
FL_EXPORT void glutSolidTetrahedron ()
FL_EXPORT void glutWireIcosahedron ()
FL_EXPORT void glutSolidIcosahedron ()
Variables
FL_EXPORT Fl_Glut_Window * glut_window
FL_EXPORT int glut_menu
FL_EXPORT void(* glut_idle_function)()
FL_EXPORT void(* glut_menustate_function)(int)
FL_EXPORT void(* glut_menustatus_function)(int, int, int)
FL_EXPORT struct
Fl_Glut_Bitmap_Font
glutBitmap9By15
glutBitmap8By13
glutBitmapTimesRoman10
glutBitmapTimesRoman24
glutBitmapHelvetica10
glutBitmapHelvetica12 glutBitmapHelvetica18
FL_EXPORT Fl_Glut_StrokeFont glutStrokeRoman
FL_EXPORT Fl_Glut_StrokeFont glutStrokeMonoRoman
Define Documentation
#define GLUT_ACCUM FL_ACCUM
Definition at line 100 of file glut.H.
#define GLUT_ACTIVE_ALT FL_ALT
Definition at line 373 of file glut.H.
Referenced by glutGetModifiers().
#define GLUT_ACTIVE_CTRL FL_CTRL
Definition at line 372 of file glut.H.
Referenced by glutGetModifiers().
#define GLUT_ACTIVE_SHIFT FL_SHIFT
Definition at line 371 of file glut.H.
Referenced by glutGetModifiers().
#define GLUT_ALPHA FL_ALPHA
Definition at line 101 of file glut.H.
#define GLUT_BITMAP_8_BY_13 (&glutBitmap8By13)
Definition at line 419 of file glut.H.
#define GLUT_BITMAP_9_BY_15 (&glutBitmap9By15)
Definition at line 418 of file glut.H.
#define GLUT_BITMAP_HELVETICA_10 (&glutBitmapHelvetica10)
Definition at line 422 of file glut.H.
#define GLUT_BITMAP_HELVETICA_12 (&glutBitmapHelvetica12)
Definition at line 423 of file glut.H.
#define GLUT_BITMAP_HELVETICA_18 (&glutBitmapHelvetica18)
Definition at line 424 of file glut.H.
#define GLUT_BITMAP_TIMES_ROMAN_10 (&glutBitmapTimesRoman10)
Definition at line 420 of file glut.H.
#define GLUT_BITMAP_TIMES_ROMAN_24 (&glutBitmapTimesRoman24)
Definition at line 421 of file glut.H.
#define GLUT_CURSOR_BOTTOM_LEFT_CORNER FL_CURSOR_SW
Definition at line 172 of file glut.H.
#define GLUT_CURSOR_BOTTOM_RIGHT_CORNER FL_CURSOR_SE
Definition at line 171 of file glut.H.
#define GLUT_CURSOR_BOTTOM_SIDE FL_CURSOR_S
Definition at line 166 of file glut.H.
#define GLUT_CURSOR_CROSSHAIR FL_CURSOR_CROSS
Definition at line 162 of file glut.H.
#define GLUT_CURSOR_CYCLE ((Fl_Cursor)26)
Definition at line 158 of file glut.H.
#define GLUT_CURSOR_DESTROY ((Fl_Cursor)45)
Definition at line 156 of file glut.H.
#define GLUT_CURSOR_FULL_CROSSHAIR FL_CURSOR_CROSS
Definition at line 175 of file glut.H.
#define GLUT_CURSOR_HELP FL_CURSOR_HELP
Definition at line 157 of file glut.H.
#define GLUT_CURSOR_INFO FL_CURSOR_HAND
Definition at line 155 of file glut.H.
#define GLUT_CURSOR_INHERIT FL_CURSOR_DEFAULT
Definition at line 173 of file glut.H.
#define GLUT_CURSOR_LEFT_ARROW ((Fl_Cursor)67)
Definition at line 154 of file glut.H.
#define GLUT_CURSOR_LEFT_RIGHT FL_CURSOR_WE
Definition at line 164 of file glut.H.
#define GLUT_CURSOR_LEFT_SIDE FL_CURSOR_W
Definition at line 167 of file glut.H.
#define GLUT_CURSOR_NONE FL_CURSOR_NONE
Definition at line 174 of file glut.H.
#define GLUT_CURSOR_RIGHT_ARROW ((Fl_Cursor)2)
Definition at line 153 of file glut.H.
#define GLUT_CURSOR_RIGHT_SIDE FL_CURSOR_E
Definition at line 168 of file glut.H.
#define GLUT_CURSOR_SPRAY ((Fl_Cursor)63)
Definition at line 159 of file glut.H.
#define GLUT_CURSOR_TEXT FL_CURSOR_INSERT
Definition at line 161 of file glut.H.
#define GLUT_CURSOR_TOP_LEFT_CORNER FL_CURSOR_NW
Definition at line 169 of file glut.H.
#define GLUT_CURSOR_TOP_RIGHT_CORNER FL_CURSOR_NE
Definition at line 170 of file glut.H.
#define GLUT_CURSOR_TOP_SIDE FL_CURSOR_N
Definition at line 165 of file glut.H.
#define GLUT_CURSOR_UP_DOWN FL_CURSOR_NS
Definition at line 163 of file glut.H.
#define GLUT_CURSOR_WAIT FL_CURSOR_WAIT
Definition at line 160 of file glut.H.
#define GLUT_DEPTH FL_DEPTH
Definition at line 102 of file glut.H.
#define GLUT_DOUBLE FL_DOUBLE
Definition at line 99 of file glut.H.
#define GLUT_DOWN 0
Definition at line 227 of file glut.H.
#define GLUT_HAS_DIAL_AND_BUTTON_BOX 603
Definition at line 361 of file glut.H.
#define GLUT_HAS_KEYBOARD 600
Definition at line 358 of file glut.H.
#define GLUT_HAS_MOUSE 601
Definition at line 359 of file glut.H.
#define GLUT_HAS_SPACEBALL 602
Definition at line 360 of file glut.H.
#define GLUT_HAS_TABLET 604
Definition at line 362 of file glut.H.
#define GLUT_INDEX FL_INDEX
Definition at line 97 of file glut.H.
#define GLUT_KEY_DOWN FL_Down
Definition at line 273 of file glut.H.
#define GLUT_KEY_END FL_End
Definition at line 277 of file glut.H.
#define GLUT_KEY_F1 1
Definition at line 257 of file glut.H.
#define GLUT_KEY_F10 10
Definition at line 266 of file glut.H.
#define GLUT_KEY_F11 11
Definition at line 267 of file glut.H.
#define GLUT_KEY_F12 12
Definition at line 268 of file glut.H.
#define GLUT_KEY_F2 2
Definition at line 258 of file glut.H.
#define GLUT_KEY_F3 3
Definition at line 259 of file glut.H.
#define GLUT_KEY_F4 4
Definition at line 260 of file glut.H.
#define GLUT_KEY_F5 5
Definition at line 261 of file glut.H.
#define GLUT_KEY_F6 6
Definition at line 262 of file glut.H.
#define GLUT_KEY_F7 7
Definition at line 263 of file glut.H.
#define GLUT_KEY_F8 8
Definition at line 264 of file glut.H.
#define GLUT_KEY_F9 9
Definition at line 265 of file glut.H.
#define GLUT_KEY_HOME FL_Home
Definition at line 276 of file glut.H.
#define GLUT_KEY_INSERT FL_Insert
Definition at line 278 of file glut.H.
#define GLUT_KEY_LEFT FL_Left
Definition at line 270 of file glut.H.
#define GLUT_KEY_PAGE_DOWN FL_Page_Down
Definition at line 275 of file glut.H.
#define GLUT_KEY_PAGE_UP FL_Page_Up
Definition at line 274 of file glut.H.
#define GLUT_KEY_RIGHT FL_Right
Definition at line 272 of file glut.H.
#define GLUT_KEY_UP FL_Up
Definition at line 271 of file glut.H.
#define GLUT_LEFT_BUTTON 0
Definition at line 224 of file glut.H.
#define GLUT_MIDDLE_BUTTON 1
Definition at line 225 of file glut.H.
#define GLUT_MULTISAMPLE FL_MULTISAMPLE
Definition at line 104 of file glut.H.
#define GLUT_NORMAL_DAMAGED 804
Definition at line 381 of file glut.H.
#define GLUT_NUM_BUTTON_BOX_BUTTONS 607
Definition at line 365 of file glut.H.
#define GLUT_NUM_DIALS 608
Definition at line 366 of file glut.H.
#define GLUT_NUM_MOUSE_BUTTONS 605
Definition at line 363 of file glut.H.
#define GLUT_NUM_SPACEBALL_BUTTONS 606
Definition at line 364 of file glut.H.
#define GLUT_NUM_TABLET_BUTTONS 609
Definition at line 367 of file glut.H.
#define GLUT_OVERLAY_DAMAGED 805
Definition at line 382 of file glut.H.
#define GLUT_OVERLAY_POSSIBLE 800
Definition at line 377 of file glut.H.
#define GLUT_RGB FL_RGB
Definition at line 95 of file glut.H.
#define GLUT_RGBA FL_RGB
Definition at line 96 of file glut.H.
#define GLUT_RIGHT_BUTTON 2
Definition at line 226 of file glut.H.
#define GLUT_SINGLE FL_SINGLE
Definition at line 98 of file glut.H.
#define GLUT_STENCIL FL_STENCIL
Definition at line 103 of file glut.H.
#define GLUT_STEREO FL_STEREO
Definition at line 105 of file glut.H.
#define GLUT_STROKE_MONO_ROMAN (&glutStrokeMonoRoman)
Definition at line 459 of file glut.H.
#define GLUT_STROKE_ROMAN (&glutStrokeRoman)
Definition at line 458 of file glut.H.
#define GLUT_TRANSPARENT_INDEX 803
Definition at line 380 of file glut.H.
#define GLUT_UP 1
Definition at line 228 of file glut.H.
#define GLUT_WINDOW_ACCUM_ALPHA_SIZE GL_ACCUM_ALPHA_BITS
Definition at line 347 of file glut.H.
#define GLUT_WINDOW_ACCUM_BLUE_SIZE GL_ACCUM_BLUE_BITS
Definition at line 346 of file glut.H.
#define GLUT_WINDOW_ACCUM_GREEN_SIZE GL_ACCUM_GREEN_BITS
Definition at line 345 of file glut.H.
#define GLUT_WINDOW_ACCUM_RED_SIZE GL_ACCUM_RED_BITS
Definition at line 344 of file glut.H.
#define GLUT_WINDOW_ALPHA_SIZE GL_ALPHA_BITS
Definition at line 343 of file glut.H.
#define GLUT_WINDOW_BLUE_SIZE GL_BLUE_BITS
Definition at line 342 of file glut.H.
#define GLUT_WINDOW_COLORMAP_SIZE GL_INDEX_BITS
Definition at line 350 of file glut.H.
#define GLUT_WINDOW_DEPTH_SIZE GL_DEPTH_BITS
Definition at line 339 of file glut.H.
#define GLUT_WINDOW_DOUBLEBUFFER GL_DOUBLEBUFFER
Definition at line 348 of file glut.H.
#define GLUT_WINDOW_GREEN_SIZE GL_GREEN_BITS
Definition at line 341 of file glut.H.
#define GLUT_WINDOW_NUM_SAMPLES GLUT_RETURN_ZERO
Definition at line 354 of file glut.H.
#define GLUT_WINDOW_RED_SIZE GL_RED_BITS
Definition at line 340 of file glut.H.
#define GLUT_WINDOW_RGBA GL_RGBA
Definition at line 349 of file glut.H.
#define GLUT_WINDOW_STENCIL_SIZE GL_STENCIL_BITS
Definition at line 338 of file glut.H.
#define GLUT_WINDOW_STEREO GL_STEREO
Definition at line 356 of file glut.H.
Typedef Documentation
typedef void(* GLUTproc)()
Definition at line 385 of file glut.H.
Enumeration Type Documentation
anonymous enum
Enumerator:
GLUT_NORMAL
GLUT_OVERLAY
Definition at line 185 of file glut.H.
anonymous enum
Enumerator:
GLUT_LEFT
GLUT_ENTERED
Definition at line 236 of file glut.H.
anonymous enum
Enumerator:
GLUT_NOT_VISIBLE
GLUT_VISIBLE
Definition at line 239 of file glut.H.
anonymous enum
Enumerator:
GLUT_MENU_NOT_IN_USE
GLUT_MENU_IN_USE
Definition at line 253 of file glut.H.
anonymous enum
Enumerator:
GLUT_RETURN_ZERO
GLUT_WINDOW_X
GLUT_WINDOW_Y
GLUT_WINDOW_WIDTH
GLUT_WINDOW_HEIGHT
GLUT_WINDOW_PARENT
GLUT_SCREEN_WIDTH
GLUT_SCREEN_HEIGHT
GLUT_MENU_NUM_ITEMS
GLUT_DISPLAY_MODE_POSSIBLE
GLUT_INIT_WINDOW_X
GLUT_INIT_WINDOW_Y
GLUT_INIT_WINDOW_WIDTH
GLUT_INIT_WINDOW_HEIGHT
GLUT_INIT_DISPLAY_MODE
GLUT_WINDOW_BUFFER_SIZE
GLUT_VERSION
Definition at line 313 of file glut.H.
Function Documentation
FL_EXPORT void glutAddMenuEntry (char * label, int value)
FL_EXPORT void glutAddSubMenu (char * label, int submenu)
void glutAttachMenu (int b) [inline]
Definition at line 211 of file glut.H.
References b, glut_menu, glut_window, and Fl_Glut_Window::menu.
FL_EXPORT void glutBitmapCharacter (void * font, int character)
FL_EXPORT int glutBitmapHeight (void * font)
FL_EXPORT int glutBitmapLength (void * font, const unsigned char * string)
FL_EXPORT void glutBitmapString (void * font, const unsigned char * string)
FL_EXPORT int glutBitmapWidth (void * font, int character)
FL_EXPORT void glutChangeToMenuEntry (int item, char * labela, int value)
FL_EXPORT void glutChangeToSubMenu (int item, char * label, int submenu)
FL_EXPORT int glutCreateMenu (void(*)(int))
FL_EXPORT int glutCreateSubWindow (int win, int x, int y, int width, int height)
FL_EXPORT int glutCreateWindow (char * title)
FL_EXPORT int glutCreateWindow (const char * title)
FL_EXPORT void glutDestroyMenu (int menu)
FL_EXPORT void glutDestroyWindow (int win)
void glutDetachMenu (int b) [inline]
Definition at line 213 of file glut.H.
References b, glut_window, and Fl_Glut_Window::menu.
FL_EXPORT int glutDeviceGet (GLenum type)
void glutDisplayFunc (void(*)() f) [inline]
Definition at line 215 of file glut.H.
References Fl_Glut_Window::display, f, and glut_window.
void glutEntryFunc (void(*)(int s) f) [inline]
Definition at line 235 of file glut.H.
References Fl_Glut_Window::entry, f, and glut_window.
void glutEstablishOverlay () [inline]
Definition at line 179 of file glut.H.
References glut_window, and Fl_Gl_Window::make_overlay_current().
FL_EXPORT int glutExtensionSupported (char * name)
void glutFullScreen () [inline]
Definition at line 149 of file glut.H.
References Fl_Window::fullscreen(), and glut_window.
FL_EXPORT int glutGet (GLenum type)
int glutGetMenu () [inline]
Definition at line 197 of file glut.H.
References glut_menu.
int glutGetModifiers () [inline]
Definition at line 374 of file glut.H.
References Fl::event_state(), GLUT_ACTIVE_ALT, GLUT_ACTIVE_CTRL, and GLUT_ACTIVE_SHIFT.
FL_EXPORT GLUTproc glutGetProcAddress (const char * procName)
int glutGetWindow () [inline]
Definition at line 127 of file glut.H.
References glut_window, and Fl_Glut_Window::number.
void glutHideOverlay () [inline]
Definition at line 191 of file glut.H.
References glut_window, and Fl_Gl_Window::hide_overlay().
void glutHideWindow () [inline]
Definition at line 147 of file glut.H.
References glut_window, and Fl_Gl_Window::hide().
void glutIconifyWindow () [inline]
Definition at line 143 of file glut.H.
References glut_window, and Fl_Window::iconize().
FL_EXPORT void glutIdleFunc (void(*)() f)
FL_EXPORT void glutInit (int * argcp, char ** argv)
FL_EXPORT void glutInitDisplayMode (unsigned int mode)
FL_EXPORT void glutInitWindowPosition (int x, int y)
FL_EXPORT void glutInitWindowSize (int w, int h)
void glutKeyboardFunc (void(*)(uchar key, int x, int y) f) [inline]
Definition at line 219 of file glut.H.
References f, glut_window, and Fl_Glut_Window::keyboard.
FL_EXPORT int glutLayerGet (GLenum)
FL_EXPORT void glutMainLoop ()
void glutMenuStateFunc (void(*)(int state) f) [inline]
Definition at line 248 of file glut.H.
References f, and glut_menustate_function.
void glutMenuStatusFunc (void(*)(int status, int x, int y) f) [inline]
Definition at line 251 of file glut.H.
References f, and glut_menustatus_function.
void glutMotionFunc (void(*)(int x, int y) f) [inline]
Definition at line 230 of file glut.H.
References f, glut_window, and Fl_Glut_Window::motion.
void glutMouseFunc (void(*)(int b, int state, int x, int y) f) [inline]
Definition at line 222 of file glut.H.
References f, glut_window, and Fl_Glut_Window::mouse.
void glutOverlayDisplayFunc (void(*)() f) [inline]
Definition at line 294 of file glut.H.
References f, glut_window, and Fl_Glut_Window::overlaydisplay.
void glutPassiveMotionFunc (void(*)(int x, int y) f) [inline]
Definition at line 232 of file glut.H.
References f, glut_window, and Fl_Glut_Window::passivemotion.
void glutPopWindow () [inline]
Definition at line 139 of file glut.H.
References glut_window, and Fl_Gl_Window::show().
void glutPositionWindow (int x, int y) [inline]
Definition at line 135 of file glut.H.
References glut_window, and Fl_Widget::position().
void glutPostOverlayRedisplay () [inline]
Definition at line 187 of file glut.H.
References glut_window, and Fl_Gl_Window::redraw_overlay().
void glutPostRedisplay () [inline]
Definition at line 121 of file glut.H.
References glut_window, and Fl_Widget::redraw().
FL_EXPORT void glutPostWindowRedisplay (int win)
void glutPushWindow () [inline]
Definition at line 141 of file glut.H.
FL_EXPORT void glutRemoveMenuItem (int item)
void glutRemoveOverlay () [inline]
Definition at line 181 of file glut.H.
References glut_window, and Fl_Gl_Window::hide_overlay().
void glutReshapeFunc (void(*)(int w, int h) f) [inline]
Definition at line 217 of file glut.H.
References f, glut_window, and Fl_Glut_Window::reshape.
void glutReshapeWindow (int w, int h) [inline]
Definition at line 137 of file glut.H.
References glut_window, and Fl_Widget::size().
void glutSetCursor (Fl_Cursor cursor) [inline]
Definition at line 151 of file glut.H.
References Fl_Window::cursor(), and glut_window.
void glutSetIconTitle (char * t) [inline]
Definition at line 133 of file glut.H.
References glut_window, and Fl_Window::iconlabel().
void glutSetMenu (int m) [inline]
Definition at line 199 of file glut.H.
References glut_menu, and m.
FL_EXPORT void glutSetWindow (int win)
void glutSetWindowTitle (char * t) [inline]
Definition at line 131 of file glut.H.
References glut_window, and Fl_Window::label().
void glutShowOverlay () [inline]
Definition at line 189 of file glut.H.
References glut_window, and Fl_Gl_Window::redraw_overlay().
void glutShowWindow () [inline]
Definition at line 145 of file glut.H.
References glut_window, and Fl_Gl_Window::show().
FL_EXPORT void glutSolidCone (GLdouble base, GLdouble height, GLint slices, GLint stacks)
Definition at line 321 of file freeglut_geometry.cxx.
References i.
FL_EXPORT void glutSolidCube (GLdouble size)
Definition at line 90 of file freeglut_geometry.cxx.
References N, size, and V.
FL_EXPORT void glutSolidDodecahedron ()
Definition at line 795 of file freeglut_geometry.cxx.
FL_EXPORT void glutSolidIcosahedron ()
Definition at line 963 of file freeglut_geometry.cxx.
References i.
FL_EXPORT void glutSolidOctahedron ()
Definition at line 865 of file freeglut_geometry.cxx.
References RADIUS.
FL_EXPORT void glutSolidSphere (GLdouble radius, GLint slices, GLint stacks)
Definition at line 167 of file freeglut_geometry.cxx.
References i.
FL_EXPORT void glutSolidTeapot (GLdouble size)
Definition at line 158 of file freeglut_teapot.cxx.
FL_EXPORT void glutSolidTetrahedron ()
Definition at line 919 of file freeglut_geometry.cxx.
FL_EXPORT void glutSolidTorus (GLdouble innerRadius, GLdouble outerRadius, GLint sides, GLint rings)
Definition at line 670 of file freeglut_geometry.cxx.
References i, and M_PI.
void glutSpecialFunc (void(*)(int key, int x, int y) f) [inline]
Definition at line 255 of file glut.H.
References f, glut_window, and Fl_Glut_Window::special.
FL_EXPORT void glutStrokeCharacter (void * font, int character)
FL_EXPORT GLfloat glutStrokeHeight (void * font)
FL_EXPORT int glutStrokeLength (void * font, const unsigned char * string)
FL_EXPORT void glutStrokeString (void * font, const unsigned char * string)
FL_EXPORT int glutStrokeWidth (void * font, int character)
FL_EXPORT void glutSwapBuffers ()
void glutTimerFunc (unsigned int msec, void(*)(int) f, int value) [inline]
Definition at line 244 of file glut.H.
References Fl::add_timeout(), and f.
void glutUseLayer (GLenum layer) [inline]
Definition at line 183 of file glut.H.
References glut_window, Fl_Glut_Window::make_current(), and Fl_Gl_Window::make_overlay_current().
void glutVisibilityFunc (void(*)(int s) f) [inline]
Definition at line 238 of file glut.H.
References f, glut_window, and Fl_Glut_Window::visibility.
void glutWarpPointer (int , int) [inline]
Definition at line 177 of file glut.H.
FL_EXPORT void glutWireCone (GLdouble base, GLdouble height, GLint slices, GLint stacks)
Definition at line 406 of file freeglut_geometry.cxx.
References i.
FL_EXPORT void glutWireCube (GLdouble size)
Definition at line 68 of file freeglut_geometry.cxx.
References N, size, and V.
FL_EXPORT void glutWireDodecahedron ()
Definition at line 744 of file freeglut_geometry.cxx.
FL_EXPORT void glutWireIcosahedron ()
Definition at line 941 of file freeglut_geometry.cxx.
References i.
FL_EXPORT void glutWireOctahedron ()
Definition at line 846 of file freeglut_geometry.cxx.
References RADIUS.
FL_EXPORT void glutWireSphere (GLdouble radius, GLint slices, GLint stacks)
Definition at line 253 of file freeglut_geometry.cxx.
References i, x, and y.
FL_EXPORT void glutWireTeapot (GLdouble size)
Definition at line 149 of file freeglut_teapot.cxx.
FL_EXPORT void glutWireTetrahedron ()
Definition at line 906 of file freeglut_geometry.cxx.
FL_EXPORT void glutWireTorus (GLdouble innerRadius, GLdouble outerRadius, GLint sides, GLint rings)
Definition at line 591 of file freeglut_geometry.cxx.
References i, and M_PI.
Variable Documentation
FL_EXPORT void(* glut_idle_function)()
FL_EXPORT int glut_menu
Referenced by glutAttachMenu(), glutGetMenu(), and glutSetMenu().
FL_EXPORT void(* glut_menustate_function)(int)
Referenced by glutMenuStateFunc().
FL_EXPORT void(* glut_menustatus_function)(int, int, int)
Referenced by glutMenuStatusFunc().
FL_EXPORT Fl_Glut_Window* glut_window
Referenced by glutAttachMenu(), glutDetachMenu(), glutDisplayFunc(), glutEntryFunc(), glutEstablishOverlay(), glutFullScreen(), glutGetWindow(), glutHideOverlay(), glutHideWindow(), glutIconifyWindow(), glutKeyboardFunc(), glutMotionFunc(), glutMouseFunc(), glutOverlayDisplayFunc(), glutPassiveMotionFunc(), glutPopWindow(), glutPositionWindow(), glutPostOverlayRedisplay(), glutPostRedisplay(), glutRemoveOverlay(), glutReshapeFunc(), glutReshapeWindow(), glutSetCursor(), glutSetIconTitle(), glutSetWindowTitle(), glutShowOverlay(), glutShowWindow(), glutSpecialFunc(), glutUseLayer(), and glutVisibilityFunc().
FL_EXPORT struct Fl_Glut_Bitmap_Font glutBitmap9By15 glutBitmap8By13 glutBitmapTimesRoman10 glutBitmapTimesRoman24 glutBitmapHelvetica10 glutBitmapHelvetica12 glutBitmapHelvetica18
FL_EXPORT Fl_Glut_StrokeFont glutStrokeMonoRoman
Definition at line 2848 of file freeglut_stroke_mono_roman.cxx.
FL_EXPORT Fl_Glut_StrokeFont glutStrokeRoman
Definition at line 2848 of file freeglut_stroke_roman.cxx.