SfR Fresh Dox - fltk: Screen functions
Screen functions
Functions
static int Fl::x ()
static int Fl::y ()
static int Fl::w ()
static int Fl::h ()
static int Fl::screen_count ()
static void Fl::screen_xywh (int &X, int &Y, int &W, int &H)
static void Fl::screen_xywh (int &X, int &Y, int &W, int &H, int mx, int my)
static void Fl::screen_xywh (int &X, int &Y, int &W, int &H, int n)
static void Fl::screen_dpi (float &h, float &v, int n=0)
Detailed Description
fl global screen functions declared in <FL/Fl.H>
Function Documentation
int Fl::h () [static, inherited]
Returns the height of the screen in pixels.
screen height (single monitor!?)
Definition at line 1610 of file Fl_mac.cxx.
Referenced by Fl::event_inside(), fl_show_form(), Fl_Tiled_Image::Fl_Tiled_Image(), Fl_Window::fullscreen(), grid_cb(), h_cb(), Fl_Window_Type::open(), Fl::reload_scheme(), Fl::screen_xywh(), w_cb(), x_cb(), and y_cb().
int Fl::screen_count () [static, inherited]
Gets the number of available screens.
Definition at line 169 of file screen_xywh.cxx.
void Fl::screen_dpi (float & h, float & v, int n = 0) [static, inherited]
Gets the screen resolution in dots-per-inch for the given screen.
Parameters:
[out] h,v horizontal and vertical resolution
[in] n the screen number (0 to Fl::screen_count() - 1)
See also:
void screen_xywh(int &x, int &y, int &w, int &h, int mx, int my)
Definition at line 294 of file screen_xywh.cxx.
void Fl::screen_xywh (int & X, int & Y, int & W, int & H, int mx, int my) [static, inherited]
Gets the bounding box of a screen that contains the specified screen position mx, my
Parameters:
[out] X,Y,W,H the corresponding screen bounding box
[in] mx,my the absolute screen position
Definition at line 181 of file screen_xywh.cxx.
References Fl::h(), height, i, void(), Fl::w(), width, Fl::x(), and Fl::y().
void Fl::screen_xywh (int & X, int & Y, int & W, int & H, int n) [static, inherited]
Gets the screen bounding rect for the given screen.
Parameters:
[out] X,Y,W,H the corresponding screen bounding box
[in] n the screen number (0 to Fl::screen_count() - 1)
See also:
void screen_xywh(int &x, int &y, int &w, int &h, int mx, int my)
Definition at line 250 of file screen_xywh.cxx.
References Fl::h(), void(), Fl::w(), Fl::x(), and Fl::y().
static void Fl::screen_xywh (int & X, int & Y, int & W, int & H) [inline, static, inherited]
Gets the bounding box of a screen that contains the mouse pointer.
Parameters:
[out] X,Y,W,H the corresponding screen bounding box
See also:
void screen_xywh(int &x, int &y, int &w, int &h, int mx, int my)
Definition at line 772 of file Fl.H.
Referenced by menuwindow::autoscroll(), fl_read_image(), fl_show_form(), Fl_Window::fullscreen(), Fl_Window::hotspot(), Fl_TooltipBox::layout(), Fl_X::make_xid(), and menuwindow::menuwindow().
int Fl::w () [static, inherited]
Returns the width of the screen in pixels.
screen width (single monitor!?)
Definition at line 1600 of file Fl_mac.cxx.
Referenced by Fl::dnd(), Fl::event_inside(), fl_show_form(), Fl_Tiled_Image::Fl_Tiled_Image(), Fl_Window::fullscreen(), grid_cb(), h_cb(), make_codeblock_panel(), make_declblock_panel(), Fl_Window_Type::open(), Fl::release_widget_pointer(), Fl::reload_scheme(), Fl::screen_xywh(), w_cb(), Fl::watch_widget_pointer(), x_cb(), and y_cb().
int Fl::x () [static, inherited]
Returns the origin of the current screen, where 0 indicates the left side of the screen.
smallest x ccordinate in screen space
Definition at line 1580 of file Fl_mac.cxx.
Referenced by Fl_Window::fullscreen(), Fl_X::make(), and Fl::screen_xywh().
int Fl::y () [static, inherited]
Returns the origin of the current screen, where 0 indicates the top edge of the screen.
smallest y ccordinate in screen space
Definition at line 1590 of file Fl_mac.cxx.
Referenced by Fl_Window::fullscreen(), Fl_X::make(), and Fl::screen_xywh().