SfR Fresh Dox - fltk: Multithreading support functions
Multithreading support functions
Functions
static void Fl::lock ()
static void Fl::unlock ()
static void Fl::awake (void *message=0)
static int Fl::awake (Fl_Awake_Handler cb, void *message=0)
static void * Fl::thread_message ()
Detailed Description
fl multithreading support functions declared in <FL/Fl.H>
Function Documentation
void Fl::awake (void * msg = 0) [static, inherited]
The awake() method sends a message pointer to the main thread, causing any pending Fl::wait() call to terminate so that the main thread can retrieve the message and any pending redraws can be processed.
Multiple calls to Fl::awake() will queue multiple pointers for the main thread to process, up to a system-defined (typically several thousand) depth. The default message handler saves the last message which can be accessed using the Fl::thread_message() function.
The second form of awake() registers a function that will be called by the main thread during the next message handling cycle. awake() will return 0 if the callback function was registered, and -1 if registration failed. Over a thousand awake callbacks can be registered simultaneously.
In the context of a threaded application, a call to Fl::awake() with no argument will trigger event loop handling in the main thread. Since it is not possible to call Fl::flush() from a subsidiary thread, Fl::awake() is the best (and only, really) substitute.
See also: Multithreading
Definition at line 396 of file Fl_lock.cxx.
Referenced by Fl::awake().
int Fl::awake (Fl_Awake_Handler func, void * data = 0) [static, inherited]
See void awake(void* message=0).
Let the main thread know an update is pending and have it call a specific function See void awake(void* message=0).
Definition at line 130 of file Fl_lock.cxx.
References Fl::add_awake_handler_(), and Fl::awake().
void Fl::lock () [static, inherited]
The lock() method blocks the current thread until it can safely access FLTK widgets and data. Child threads should call this method prior to updating any widgets or accessing data. The main thread must call lock() to initialize the threading support in FLTK.
Child threads must call unlock() when they are done accessing FLTK.
When the wait() method is waiting for input or timeouts, child threads are given access to FLTK. Similarly, when the main thread needs to do processing, it will wait until all child threads have called unlock() before processing additional data.
See also: Multithreading
void * Fl::thread_message () [static, inherited]
The thread_message() method returns the last message that was sent from a child by the awake() method.
See also: multithreading
Definition at line 335 of file Fl_win32.cxx.
void Fl::unlock () [static, inherited]
The unlock() method releases the lock that was set using the lock() method. Child threads should call this method as soon as they are finished accessing FLTK.
See also: Multithreading