SfR Fresh Dox - fltk: Windows handling functions
Windows handling functions
Windows and standard dialogs handling declared in <FL/Fl.H>
Functions
static Fl_Window * Fl::first_window ()
static void Fl::first_window (Fl_Window *)
static Fl_Window * Fl::next_window (const Fl_Window *)
static Fl_Window * Fl::modal ()
static Fl_Window * Fl::grab ()
static void Fl::grab (Fl_Window *)
static void Fl::set_abort (Fl_Abort_Handler f)
static void Fl::default_atclose (Fl_Window *, void *)
static void Fl::set_atclose (Fl_Atclose_Handler f)
Variables
static void(* Fl::atclose)(Fl_Window *, void *) = default_atclose
Detailed Description
Windows and standard dialogs handling declared in <FL/Fl.H>
Function Documentation
void Fl::default_atclose (Fl_Window * window, void * v) [static, inherited]
Default callback for window widgets. It hides the window and then calls the default widget callback.
Definition at line 167 of file Fl_Window.cxx.
References Fl_Widget::default_callback(), and Fl_Window::hide().
Fl_Window * Fl::first_window () [static, inherited]
Returns the first top-level window in the list of shown() windows. If a modal() window is shown this is the top-most modal window, otherwise it is the most recent window to get an event.
The second form sets the window that is returned by first_window. The window is removed from wherever it is in the list and inserted at the top. This is not done if Fl::modal() is on or if the window is not shown(). Because the first window is used to set the "parent" of modal windows, this is often useful.
Definition at line 651 of file Fl.cxx.
References i, and Fl_X::w.
Referenced by carbonKeyboardHandler(), carbonTextHandler(), fl_cursor(), fl_handle(), fl_text_extents(), fl_wait(), fl_width(), Fl::get_system_colors(), Fl::grab(), Fl_Input::handle(), Fl::handle(), Fl_Window::hide(), Fl_Paged_Device::print_window_part(), Fl_Window_Type::read_property(), Fl::reload_scheme(), Fl::scheme(), and Fl_Window::show().
void Fl::first_window (Fl_Window * window) [static, inherited]
See Fl_Window* first_window()
Definition at line 668 of file Fl.cxx.
References fl_find(), Fl_X::i(), and Fl_Window::shown().
static Fl_Window* Fl::grab () [inline, static, inherited]
This is used when pop-up menu systems are active.
Send all events to the passed window no matter where the pointer or focus is (including in other programs). The window does not have to be shown() , this lets the handle() method of a "dummy" window override all event handling and allows you to map and unmap a complex set of windows (under both X and WIN32 some window must be mapped because the system interface needs a window id).
If grab() is on it will also affect show() of windows by doing system-specific operations (on X it turns on override-redirect). These are designed to make menus popup reliably and faster on the system.
To turn off grabbing do Fl::grab(0).
Be careful that your program does not enter an infinite loop while grab() is on. On X this will lock up your screen! To avoid this potential lockup, all newer operating systems seem to limit mouse pointer grabbing to the time during which a mouse button is held down. Some OS's may not support grabbing at all.
Definition at line 459 of file Fl.H.
Referenced by Fl::belowmouse(), fl_fix_focus(), Fl::focus(), Fl::handle(), Fl_X::make(), Fl_X::make_xid(), Fl_Menu_Item::pulldown(), and ColorMenu::run().
void Fl::grab (Fl_Window * win) [static, inherited]
Selects the window to grab. See Fl_Window* Fl::grab()
Definition at line 53 of file Fl_grab.cxx.
References Fl::first_window(), fl_capture, fl_display, fl_event_time, fl_fix_focus(), fl_xid(), Fl::grab_, and i.
static Fl_Window* Fl::modal () [inline, static, inherited]
Returns the top-most modal() window currently shown.
This is the most recently shown() window with modal() true, or NULL if there are no modal() windows shown(). The modal() window has its handle() method called for all events, and no other windows will have handle() called (grab() overrides this).
Definition at line 434 of file Fl.H.
Referenced by fl_find(), fl_fix_focus(), and Fl::handle().
Fl_Window * Fl::next_window (const Fl_Window * window) [static, inherited]
Returns the next top-level window in the list of shown() windows. You can use this call to iterate through all the windows that are shown().
Definition at line 660 of file Fl.cxx.
References i, and Fl_X::w.
Referenced by Fl_Window::hide(), and Fl::reload_scheme().
static void Fl::set_abort (Fl_Abort_Handler f) [inline, static, inherited]
For back compatibility, sets the void Fl::fatal handler callback
Definition at line 879 of file Fl.H.
References f.
static void Fl::set_atclose (Fl_Atclose_Handler f) [inline, static, inherited]
For back compatibility, sets the Fl::atclose handler callback. You can now simply change the callback for the window instead.
See also:
Fl_Window::callback(Fl_Callback*)
Definition at line 885 of file Fl.H.
References f.
Variable Documentation
void(* Fl::atclose)(Fl_Window *, void *) = default_atclose [static, inherited]
Back compatibility: default window callback handler
See also:
Fl::set_atclose()
Definition at line 880 of file Fl.H.
Referenced by Fl_Window::default_callback().