SfR Fresh Dox - fltk: Drawing functions
Drawing functions
Defines
#define fl_clip fl_push_clip
Enumerations
enum {
FL_SOLID = 0, FL_DASH = 1, FL_DOT = 2, FL_DASHDOT = 3,
FL_DASHDOTDOT = 4, FL_CAP_FLAT = 0x100, FL_CAP_ROUND = 0x200, FL_CAP_SQUARE = 0x300,
FL_JOIN_MITER = 0x1000, FL_JOIN_ROUND = 0x2000, FL_JOIN_BEVEL = 0x3000
}
Functions
void fl_push_clip (int x, int y, int w, int h)
void fl_push_no_clip ()
void fl_pop_clip ()
int fl_not_clipped (int x, int y, int w, int h)
int fl_clip_box (int x, int y, int w, int h, int &X, int &Y, int &W, int &H)
void fl_restore_clip ()
FL_EXPORT void fl_clip_region (Fl_Region r)
Fl_Region fl_clip_region ()
void fl_point (int x, int y)
void fl_line_style (int style, int width=0, char *dashes=0)
void fl_rect (int x, int y, int w, int h)
void fl_rect (int x, int y, int w, int h, Fl_Color c)
void fl_rectf (int x, int y, int w, int h)
void fl_rectf (int x, int y, int w, int h, Fl_Color c)
FL_EXPORT void fl_rectf (int x, int y, int w, int h, uchar r, uchar g, uchar b)
void fl_line (int x, int y, int x1, int y1)
void fl_line (int x, int y, int x1, int y1, int x2, int y2)
void fl_loop (int x, int y, int x1, int y1, int x2, int y2)
void fl_loop (int x, int y, int x1, int y1, int x2, int y2, int x3, int y3)
void fl_polygon (int x, int y, int x1, int y1, int x2, int y2)
void fl_polygon (int x, int y, int x1, int y1, int x2, int y2, int x3, int y3)
void fl_xyline (int x, int y, int x1)
void fl_xyline (int x, int y, int x1, int y2)
void fl_xyline (int x, int y, int x1, int y2, int x3)
void fl_yxline (int x, int y, int y1)
void fl_yxline (int x, int y, int y1, int x2)
void fl_yxline (int x, int y, int y1, int x2, int y3)
void fl_arc (int x, int y, int w, int h, double a1, double a2)
void fl_pie (int x, int y, int w, int h, double a1, double a2)
FL_EXPORT void fl_chord (int x, int y, int w, int h, double a1, double a2)
FL_EXPORT void fl_push_matrix ()
FL_EXPORT void fl_pop_matrix ()
FL_EXPORT void fl_scale (double x, double y)
FL_EXPORT void fl_scale (double x)
FL_EXPORT void fl_translate (double x, double y)
FL_EXPORT void fl_rotate (double d)
FL_EXPORT void fl_mult_matrix (double a, double b, double c, double d, double x, double y)
void fl_begin_points ()
void fl_begin_line ()
void fl_begin_loop ()
void fl_begin_polygon ()
void fl_vertex (double x, double y)
void fl_curve (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3)
void fl_arc (double x, double y, double r, double start, double end)
void fl_circle (double x, double y, double r)
void fl_end_points ()
void fl_end_line ()
void fl_end_loop ()
void fl_end_polygon ()
void fl_begin_complex_polygon ()
void fl_gap ()
void fl_end_complex_polygon ()
FL_EXPORT double fl_transform_x (double x, double y)
FL_EXPORT double fl_transform_y (double x, double y)
FL_EXPORT double fl_transform_dx (double x, double y)
FL_EXPORT double fl_transform_dy (double x, double y)
void fl_transformed_vertex (double xf, double yf)
FL_EXPORT void fl_draw (const char *str, int x, int y)
FL_EXPORT void fl_draw (int angle, const char *str, int x, int y)
void fl_draw (const char *str, int n, int x, int y)
void fl_draw (int angle, const char *str, int n, int x, int y)
void fl_rtl_draw (const char *str, int n, int x, int y)
FL_EXPORT void fl_measure (const char *str, int &x, int &y, int draw_symbols=1)
FL_EXPORT void fl_draw (const char *str, int x, int y, int w, int h, Fl_Align align, Fl_Image *img=0, int draw_symbols=1)
FL_EXPORT void fl_draw (const char *str, int x, int y, int w, int h, Fl_Align align, void(*callthis)(const char *, int, int, int), Fl_Image *img=0, int draw_symbols=1)
FL_EXPORT void fl_frame (const char *s, int x, int y, int w, int h)
FL_EXPORT void fl_frame2 (const char *s, int x, int y, int w, int h)
FL_EXPORT void fl_draw_box (Fl_Boxtype, int x, int y, int w, int h, Fl_Color)
void fl_draw_image (const uchar *buf, int X, int Y, int W, int H, int D=3, int L=0)
void fl_draw_image_mono (const uchar *buf, int X, int Y, int W, int H, int D=1, int L=0)
void fl_draw_image (Fl_Draw_Image_Cb cb, void *data, int X, int Y, int W, int H, int D=3)
FL_EXPORT void fl_draw_image_mono (Fl_Draw_Image_Cb cb, void *data, int X, int Y, int W, int H, int D=1)
FL_EXPORT char fl_can_do_alpha_blending ()
FL_EXPORT uchar * fl_read_image (uchar *p, int X, int Y, int W, int H, int alpha=0)
FL_EXPORT int fl_draw_pixmap (char *const *data, int x, int y, Fl_Color=FL_GRAY)
FL_EXPORT int fl_draw_pixmap (const char *const *cdata, int x, int y, Fl_Color=FL_GRAY)
FL_EXPORT int fl_measure_pixmap (char *const *data, int &w, int &h)
FL_EXPORT int fl_measure_pixmap (const char *const *cdata, int &w, int &h)
FL_EXPORT void fl_scroll (int X, int Y, int W, int H, int dx, int dy, void(*draw_area)(void *, int, int, int, int), void *data)
FL_EXPORT const char * fl_shortcut_label (unsigned int shortcut)
FL_EXPORT const char * fl_shortcut_label (unsigned int shortcut, const char **eom)
FL_EXPORT unsigned int fl_old_shortcut (const char *s)
FL_EXPORT void fl_overlay_rect (int x, int y, int w, int h)
FL_EXPORT void fl_overlay_clear ()
FL_EXPORT void fl_cursor (Fl_Cursor, Fl_Color fg=FL_BLACK, Fl_Color bg=FL_WHITE)
FL_EXPORT const char * fl_expand_text (const char *from, char *buf, int maxbuf, double maxw, int &n, double &width, int wrap, int draw_symbols=0)
FL_EXPORT void fl_set_status (int X, int Y, int W, int H)
FL_EXPORT void fl_set_spot (int font, int size, int X, int Y, int W, int H, Fl_Window *win=0)
FL_EXPORT void fl_reset_spot (void)
FL_EXPORT int fl_draw_symbol (const char *label, int x, int y, int w, int h, Fl_Color)
FL_EXPORT int fl_add_symbol (const char *name, void(*drawit)(Fl_Color), int scalable)
void fl_copy_offscreen (int x, int y, int w, int h, Fl_Offscreen pixmap, int srcx, int srcy)
Detailed Description
FLTK global graphics and GUI drawing functions. These functions are declared in <FL/fl_draw.H>, and in <FL/x.H> for offscreen buffer-related ones.
Define Documentation
#define fl_clip fl_push_clip
The fl_clip() name is deprecated and will be removed from future releases
Definition at line 95 of file fl_draw.H.
Enumeration Type Documentation
anonymous enum
Enumerator:
FL_SOLID
line style: ___________
FL_DASH
line style: _ _ _ _ _ _
FL_DOT
line style: . . . . . .
FL_DASHDOT
line style: _ . _ . _ .
FL_DASHDOTDOT
line style: _ . . _ . .
FL_CAP_FLAT
cap style: end is flat
FL_CAP_ROUND
cap style: end is round
FL_CAP_SQUARE
cap style: end wraps end point
FL_JOIN_MITER
join style: line join extends to a point
FL_JOIN_ROUND
join style: line join is rounded
FL_JOIN_BEVEL
join style: line join is tidied
Definition at line 185 of file fl_draw.H.
Function Documentation
FL_EXPORT int fl_add_symbol (const char * name, void(*)(Fl_Color) drawit, int scalable)
Adds a symbol to the system.
Parameters:
[in] name name of symbol (without the "@")
[in] drawit function to draw symbol
[in] scalable set to 1 if drawit uses scalable vector drawing
Returns:
1 on success, 0 on failure
Definition at line 87 of file fl_symbols.cxx.
References SYMBOL::drawit, MAXSYMBOL, name, SYMBOL::name, SYMBOL::notempty, and SYMBOL::scalable.
void fl_arc (int x, int y, int w, int h, double a1, double a2) [inline]
Draw ellipse sections using integer coordinates.
These functions match the rather limited circle drawing code provided by X and WIN32. The advantage over using fl_arc with floating point coordinates is that they are faster because they often use the hardware, and they draw much nicer small circles, since the small sizes are often hard-coded bitmaps.
If a complete circle is drawn it will fit inside the passed bounding box. The two angles are measured in degrees counterclockwise from 3 o'clock and are the starting and ending angle of the arc, a2 must be greater or equal to a1.
fl_arc() draws a series of lines to approximate the arc. Notice that the integer version of fl_arc() has a different number of arguments than the double version fl_arc(double x, double y, double r, double start, double end)
Parameters:
[in] x,y,w,h bounding box of complete circle
[in] a1,a2 start and end angles of arc measured in degrees counter-clockwise from 3 o'clock. a2 must be greater than or equal to a1.
Definition at line 311 of file fl_draw.H.
References Fl_Graphics_Driver::arc(), and fl_graphics_driver.
Referenced by Fl_Menu_Item::draw(), Fl_Light_Button::draw(), Fl_Dial::draw(), and fl_arc_i().
void fl_arc (double x, double y, double r, double start, double end) [inline]
Add a series of points to the current path on the arc of a circle; you can get elliptical paths by using scale and rotate before calling fl_arc().
Parameters:
[in] x,y,r center and radius of circular arc
[in] start,end angles of start and end of arc measured in degrees counter-clockwise from 3 o'clock. If end is less than start then it draws the arc in a clockwise direction.
Definition at line 375 of file fl_draw.H.
References Fl_Graphics_Driver::arc(), and fl_graphics_driver.
void fl_begin_complex_polygon () [inline]
Starts drawing a complex filled polygon.
The polygon may be concave, may have holes in it, or may be several disconnected pieces. Call fl_gap() to separate loops of the path.
To outline the polygon, use fl_begin_loop() and replace each fl_gap() with fl_end_loop();fl_begin_loop() pairs.
Note:
For portability, you should only draw polygons that appear the same whether "even/odd" or "non-zero" winding rules are used to fill them. Holes should be drawn in the opposite direction to the outside loop.
Definition at line 414 of file fl_draw.H.
References Fl_Graphics_Driver::begin_complex_polygon(), and fl_graphics_driver.
Referenced by Fl_File_Icon::draw().
void fl_begin_line () [inline]
Starts drawing a list of lines.
Definition at line 343 of file fl_draw.H.
References Fl_Graphics_Driver::begin_line(), and fl_graphics_driver.
Referenced by Fl_File_Icon::draw().
void fl_begin_loop () [inline]
Starts drawing a closed sequence of lines.
Definition at line 347 of file fl_draw.H.
References Fl_Graphics_Driver::begin_loop(), and fl_graphics_driver.
Referenced by Fl_File_Icon::draw(), Fl_Dial::draw(), and Fl_Clock_Output::draw().
void fl_begin_points () [inline]
Starts drawing a list of points. Points are added to the list with fl_vertex()
Definition at line 339 of file fl_draw.H.
References Fl_Graphics_Driver::begin_points(), and fl_graphics_driver.
void fl_begin_polygon () [inline]
Starts drawing a convex filled polygon.
Definition at line 351 of file fl_draw.H.
References Fl_Graphics_Driver::begin_polygon(), and fl_graphics_driver.
Referenced by Fl_Dial::draw(), and Fl_Clock_Output::draw().
FL_EXPORT char fl_can_do_alpha_blending ()
Checks whether platform supports true alpha blending for RGBA images.
Returns:
1 if true alpha blending supported by platform
0 not supported so FLTK will use screen door transparency
FL_EXPORT void fl_chord (int x, int y, int w, int h, double a1, double a2)
fl_chord declaration is a place holder - the function does not yet exist
void fl_circle (double x, double y, double r) [inline]
fl_circle() is equivalent to fl_arc(x,y,r,0,360), but may be faster.
It must be the only thing in the path: if you want a circle as part of a complex polygon you must use fl_arc()
Parameters:
[in] x,y,r center and radius of circle
Definition at line 383 of file fl_draw.H.
References Fl_Graphics_Driver::circle(), and fl_graphics_driver.
Referenced by Fl_Dial::draw(), and Fl_Clock_Output::draw().
int fl_clip_box (int x, int y, int w, int h, int & X, int & Y, int & W, int & H) [inline]
Intersects the rectangle with the current clip region and returns the bounding box of the result.
Returns non-zero if the resulting rectangle is different to the original. This can be used to limit the necessary drawing to a rectangle. W and H are set to zero if the rectangle is completely outside the region.
Parameters:
[in] x,y,w,h position and size of rectangle
[out] X,Y,W,H position and size of resulting bounding box. W and H are set to zero if the rectangle is completely outside the region.
Returns:
Non-zero if the resulting rectangle is different to the original.
Definition at line 133 of file fl_draw.H.
References Fl_Graphics_Driver::clip_box(), and fl_graphics_driver.
Referenced by Fl_Text_Display::draw(), and Fl_Double_Window::flush().
Fl_Region fl_clip_region ()
returns the current clipping region.
Definition at line 564 of file fl_rect.cxx.
FL_EXPORT void fl_clip_region (Fl_Region r)
Replaces the top of the clipping stack with a clipping region of any shape.
Fl_Region is an operating system specific type.
Parameters:
[in] r clipping region
Definition at line 557 of file fl_rect.cxx.
Referenced by Fl_Menu_Window::flush(), Fl_Double_Window::flush(), Fl_Window::flush(), and Fl_Window::make_current().
void fl_copy_offscreen (int x, int y, int w, int h, Fl_Offscreen pixmap, int srcx, int srcy)
Copy a rectangular area of the given offscreen buffer into the current drawing destination.
Parameters:
x,y position where to draw the copied rectangle
w,h size of the copied rectangle
pixmap offscreen buffer containing the rectangle to copy
srcx,srcy origin in offscreen buffer of rectangle to copy
Definition at line 79 of file Fl_Double_Window.cxx.
References Fl_Surface_Device::driver(), fl_begin_offscreen(), fl_display_device, fl_draw_image(), fl_end_offscreen(), fl_graphics_driver, fl_read_image(), and NULL.
Referenced by Fl_Xlib_Graphics_Driver::draw(), and Fl_Double_Window::flush().
FL_EXPORT void fl_cursor (Fl_Cursor c, Fl_Color fg, Fl_Color bg)
Sets the cursor for the current window to the specified shape and colors. The cursors are defined in the <FL/Enumerations.H> header file.
Definition at line 46 of file fl_cursor.cxx.
References Fl_Window::cursor(), and Fl::first_window().
Referenced by Fl_Table::change_cursor(), and Fl_File_Chooser::show().
void fl_curve (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3) [inline]
Add a series of points on a Bezier curve to the path. The curve ends (and two of the points) are at X0,Y0 and X3,Y3.
Parameters:
[in] X0,Y0 curve start point
[in] X1,Y1 curve control point
[in] X2,Y2 curve control point
[in] X3,Y3 curve end point
Definition at line 365 of file fl_draw.H.
References Fl_Graphics_Driver::curve(), and fl_graphics_driver.
FL_EXPORT void fl_draw (const char * str, int x, int y, int w, int h, Fl_Align align, Fl_Image * img, int draw_symbols)
Fancy string drawing function which is used to draw all the labels.
The string is formatted and aligned inside the passed box. Handles '\t' and '\n', expands all other control characters to '^X', and aligns inside or against the edges of the box. See Fl_Widget::align() for values of align. The value FL_ALIGN_INSIDE is ignored, as this function always prints inside the box. If img is provided and is not NULL, the image is drawn above or below the text as specified by the align value. The draw_symbols argument specifies whether or not to look for symbol names starting with the '@' character' The text length is limited to 1024 characters per line.
Definition at line 376 of file fl_draw.cxx.
References FL_ALIGN_CLIP, FL_ALIGN_INSIDE, fl_draw(), fl_not_clipped(), fl_pop_clip(), and fl_push_clip().
FL_EXPORT void fl_draw (const char * str, int x, int y, int w, int h, Fl_Align align, void(*)(const char *, int, int, int) callthis, Fl_Image * img, int draw_symbols)
The same as fl_draw(const char*,int,int,int,int,Fl_Align,Fl_Image*,int) with the addition of the callthis parameter, which is a pointer to a text drawing function such as fl_draw(const char*, int, int, int) to do the real work
Definition at line 184 of file fl_draw.cxx.
References buf, Fl_Image::draw(), FL_ALIGN_BOTTOM, FL_ALIGN_IMAGE_BACKDROP, FL_ALIGN_IMAGE_NEXT_TO_TEXT, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_ALIGN_TEXT_OVER_IMAGE, FL_ALIGN_TOP, FL_ALIGN_WRAP, fl_color(), fl_descent(), fl_draw_symbol(), fl_expand_text(), fl_height(), fl_width(), Fl_Image::h(), height, int, MAXBUF, min, NULL, strlcpy, Fl_Image::w(), width, x, and y.
FL_EXPORT void fl_draw (const char * str, int x, int y)
Draws a nul-terminated string starting at the given location.
Text is aligned to the left and to the baseline of the font. To align to the bottom, subtract fl_descent() from y. To align to the top, subtract fl_descent() and add fl_height(). This version of fl_draw provides direct access to the text drawing function of the underlying OS. It does not apply any special handling to control characters.
Definition at line 67 of file fl_font.cxx.
References fl_draw().
Referenced by Fl_Timer::draw(), Fl_Value_Slider::draw(), Fl_Value_Output::draw(), Fl_Tree_Item::draw(), Fl_TooltipBox::draw(), Fl_Counter::draw(), Shortcut_Button::draw(), Fl_Text_Display::draw_string(), Fl_Input_::drawtext(), fl_draw(), fl_drw_text(), fl_drw_text_beside(), fl_normal_label(), and Fl_Browser::item_draw().
FL_EXPORT void fl_draw (int angle, const char * str, int x, int y)
Draws a nul-terminated string starting at the given location and rotating angle degrees counterclockwise. This version of fl_draw provides direct access to the text drawing function of the underlying OS and is supported by Xft, Win32 and MacOS fltk subsets.
Definition at line 71 of file fl_font.cxx.
References fl_draw().
void fl_draw (const char * str, int n, int x, int y) [inline]
Draws an array of n characters starting at the given location.
Definition at line 558 of file fl_draw.H.
References Fl_Graphics_Driver::draw(), and fl_graphics_driver.
void fl_draw (int angle, const char * str, int n, int x, int y) [inline]
Draws an array of n characters starting at the given location, rotating angle degrees counterclockwise.
Definition at line 563 of file fl_draw.H.
References Fl_Graphics_Driver::draw(), and fl_graphics_driver.
FL_EXPORT void fl_draw_box (Fl_Boxtype t, int x, int y, int w, int h, Fl_Color c)
Draws a box using given type, position, size and color.
Parameters:
[in] t box type
[in] x,y,w,h position and size
[in] c color
Definition at line 395 of file fl_boxtype.cxx.
References f.
Referenced by Fl_Tree_Item::draw(), Fl_Menu_Item::draw(), fl_drw_box(), and fl_drw_frame().
void fl_draw_image (const uchar * buf, int X, int Y, int W, int H, int D = 3, int L = 0) [inline]
Draw an 8-bit per color RGB or luminance image.
Parameters:
[in] buf points at the "r" data of the top-left pixel. Color data must be in r,g,b order.
[in] X,Y position where to put top-left corner of image
[in] W,H size of the image
[in] D delta to add to the pointer between pixels. it may be any value greater than or equal to 3, or it can be negative to flip the image horizontally
[in] L delta to add to the pointer between lines (if 0 is passed it uses W * D), and may be larger than W * D to crop data, or negative to flip the image vertically
It is highly recommended that you put the following code before the first show() of any window in your program to get rid of the dithering if possible:
  Fl::visual(FL_RGB);
Gray scale (1-channel) images may be drawn. This is done if abs(D) is less than 3, or by calling fl_draw_image_mono(). Only one 8-bit sample is used for each pixel, and on screens with different numbers of bits for red, green, and blue only gray colors are used. Setting D greater than 1 will let you display one channel of a color image.
Note:
The X version does not support all possible visuals. If FLTK cannot draw the image in the current visual it will abort. FLTK supports any visual of 8 bits or less, and all common TrueColor visuals up to 32 bits.
Definition at line 618 of file fl_draw.H.
References Fl_Graphics_Driver::draw_image(), and fl_graphics_driver.
Referenced by Flcc_ValueBox::draw(), Flcc_HueBox::draw(), fl_copy_offscreen(), fl_draw_pixmap(), and Fl_Paged_Device::print_window_part().
void fl_draw_image (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 3) [inline]
Draw image using callback function to generate image data. You can generate the image as it is being drawn, or do arbitrary decompression of stored data, provided it can be decompressed to individual scan lines easily.
Parameters:
[in] cb callback function to generate scan line data
[in] data user data passed to callback function
[in] X,Y
[in] W,H
[in] D
See also:
fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L)
The callback function cb is called with the void* data user data pointer to allow access to a structure of information about the image, and the x, y, and w of the scan line desired from the image. 0,0 is the upper-left corner of the image, not X, Y. A pointer to a buffer to put the data into is passed. You must copy w pixels from scanline y, starting at pixel x, to this buffer.
Due to cropping, less than the whole image may be requested. So x may be greater than zero, the first y may be greater than zero, and w may be less than W. The buffer is long enough to store the entire W * D pixels, this is for convenience with some decompression schemes where you must decompress the entire line at once: decompress it into the buffer, and then if x is not zero, copy the data over so the x'th pixel is at the start of the buffer.
You can assume the y's will be consecutive, except the first one may be greater than zero.
If D is 4 or more, you must fill in the unused bytes with zero.
Definition at line 660 of file fl_draw.H.
References Fl_Graphics_Driver::draw_image(), and fl_graphics_driver.
void fl_draw_image_mono (const uchar * buf, int X, int Y, int W, int H, int D = 1, int L = 0) [inline]
Draw a gray-scale (1 channel) image.
See also:
fl_draw_image(const uchar* buf, int X,int Y,int W,int H, int D, int L)
Definition at line 625 of file fl_draw.H.
References Fl_Graphics_Driver::draw_image_mono(), and fl_graphics_driver.
FL_EXPORT void fl_draw_image_mono (Fl_Draw_Image_Cb cb, void * data, int X, int Y, int W, int H, int D = 1)
Draw gray-scale image using callback function to generate image data.
See also:
fl_draw_image(Fl_Draw_Image_Cb cb, void* data, int X,int Y,int W,int H, int D)
FL_EXPORT int fl_draw_pixmap (char *const * data, int x, int y, Fl_Color bg)
Draw XPM image data, with the top-left corner at the given position. The image is dithered on 8-bit displays so you won't lose color space for programs displaying both images and pixmaps.
Parameters:
[in] data pointer to XPM image data
[in] x,y position of top-left corner
[in] bg background color
Returns:
0 if there was any error decoding the XPM data.
Definition at line 174 of file fl_draw_pixmap.cxx.
References fl_draw_pixmap().
Referenced by Fl_PostScript_Graphics_Driver::draw(), Fl_Xlib_Graphics_Driver::draw(), and fl_draw_pixmap().
FL_EXPORT int fl_draw_pixmap (const char *const * cdata, int x, int y, Fl_Color bg)
Draw XPM image data, with the top-left corner at the given position.
See also:
fl_draw_pixmap(char* const* data, int x, int y, Fl_Color bg)
Definition at line 216 of file fl_draw_pixmap.cxx.
References b, pixmap_data::byte1, chars_per_pixel, Fl_Device::class_name(), pixmap_data::colors, pixmap_data::data, data, dw, fl_draw_image(), fl_gc, fl_graphics_driver, fl_measure_pixmap(), fl_parse_color(), Fl::get_color(), pixmap_data::h, rect(), U32, pixmap_data::w, and x.
FL_EXPORT int fl_draw_symbol (const char * label, int x, int y, int w, int h, Fl_Color col)
Draw the named symbol in the given rectangle using the given color
Parameters:
[in] label name of symbol
[in] x,y position of symbol
[in] w,h size of symbol
[in] col color of symbox
Returns:
1 on success, 0 on failure
Definition at line 112 of file fl_symbols.cxx.
References SYMBOL::drawit, fl_pop_matrix(), fl_push_matrix(), fl_return_arrow(), fl_rotate(), fl_scale(), fl_translate(), h, and w.
Referenced by Fl_Counter::draw(), and fl_draw().
void fl_end_complex_polygon () [inline]
Ends complex filled polygon, and draws.
Definition at line 425 of file fl_draw.H.
References Fl_Graphics_Driver::end_complex_polygon(), and fl_graphics_driver.
Referenced by Fl_File_Icon::draw().
void fl_end_line () [inline]
Ends list of lines, and draws.
Definition at line 391 of file fl_draw.H.
References Fl_Graphics_Driver::end_line(), and fl_graphics_driver.
Referenced by Fl_File_Icon::draw().
void fl_end_loop () [inline]
Ends closed sequence of lines, and draws.
Definition at line 395 of file fl_draw.H.
References Fl_Graphics_Driver::end_loop(), and fl_graphics_driver.
Referenced by Fl_File_Icon::draw(), Fl_Dial::draw(), and Fl_Clock_Output::draw().
void fl_end_points () [inline]
Ends list of points, and draws.
Definition at line 387 of file fl_draw.H.
References Fl_Graphics_Driver::end_points(), and fl_graphics_driver.
void fl_end_polygon () [inline]
Ends convex filled polygon, and draws.
Definition at line 399 of file fl_draw.H.
References Fl_Graphics_Driver::end_polygon(), and fl_graphics_driver.
Referenced by Fl_File_Icon::draw(), Fl_Dial::draw(), and Fl_Clock_Output::draw().
FL_EXPORT const char* fl_expand_text (const char * from, char * buf, int maxbuf, double maxw, int & n, double & width, int wrap, int draw_symbols)
Copy from to buf, replacing unprintable characters with ^X and \nnn.
Stop at a newline or if MAXBUF characters written to buffer. Also word-wrap if width exceeds maxw. Returns a pointer to the start of the next line of characters. Sets n to the number of characters put into the buffer. Sets width to the width of the string in the current font.
Definition at line 114 of file fl_draw.cxx.
References buf, fl_draw_shortcut, fl_utf_nb_char(), fl_width(), and w.
Referenced by fl_draw(), and fl_measure().
FL_EXPORT void fl_frame (const char * s, int x, int y, int w, int h)
Draws a series of line segments around the given box. The string s must contain groups of 4 letters which specify one of 24 standard grayscale values, where 'A' is black and 'X' is white. The order of each set of 4 characters is: top, left, bottom, right. The result of calling fl_frame() with a string that is not a multiple of 4 characters in length is undefined. The only difference between this function and fl_frame2() is the order of the line segments.
Parameters:
[in] s sets of 4 grayscale values in top, left, bottom, right order
[in] x,y,w,h position and size
Definition at line 80 of file fl_boxtype.cxx.
References fl_color(), fl_gray_ramp(), fl_xyline(), and fl_yxline().
FL_EXPORT void fl_frame2 (const char * s, int x, int y, int w, int h)
Draws a series of line segments around the given box. The string s must contain groups of 4 letters which specify one of 24 standard grayscale values, where 'A' is black and 'X' is white. The order of each set of 4 characters is: bottom, right, top, left. The result of calling fl_frame2() with a string that is not a multiple of 4 characters in length is undefined. The only difference between this function and fl_frame() is the order of the line segments.
Parameters:
[in] s sets of 4 grayscale values in bottom, right, top, left order
[in] x,y,w,h position and size
Definition at line 114 of file fl_boxtype.cxx.
References fl_color(), fl_gray_ramp(), fl_xyline(), and fl_yxline().
Referenced by fl_down_frame(), fl_thin_down_frame(), fl_thin_up_frame(), and fl_up_frame().
void fl_gap () [inline]
Call fl_gap() to separate loops of the path.
It is unnecessary but harmless to call fl_gap() before the first vertex, after the last vertex, or several times in a row.
Definition at line 421 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::gap().
void fl_line (int x, int y, int x1, int y1, int x2, int y2) [inline]
Draws a line from (x,y) to (x1,y1) and another from (x1,y1) to (x2,y2)
Definition at line 234 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::line().
void fl_line (int x, int y, int x1, int y1) [inline]
Draws a line from (x,y) to (x1,y1)
Definition at line 230 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::line().
Referenced by Fl_Window::draw(), Fl_Slider::draw(), Fl_Menu_Button::draw(), Fl_Menu_Item::draw(), Fl_Light_Button::draw(), Fl_Text_Display::draw_cursor(), Fl_Image::draw_empty(), Fl_Tree_Item::draw_horizontal_connector(), Fl_Tree_Item::draw_vertical_connector(), Fl_Input_::drawtext(), fl_return_arrow(), and Fl_Browser::item_draw().
void fl_line_style (int style, int width = 0, char * dashes = 0) [inline]
Sets how to draw lines (the "pen"). If you change this it is your responsibility to set it back to the default using fl_line_style(0).
Parameters:
[in] style A bitmask which is a bitwise-OR of a line style, a cap style, and a join style. If you don't specify a dash type you will get a solid line. If you don't specify a cap or join type you will get a system-defined default of whatever value is fastest.
[in] width The thickness of the lines in pixels. Zero results in the system defined default, which on both X and Windows is somewhat different and nicer than 1.
[in] dashes A pointer to an array of dash lengths, measured in pixels. The first location is how long to draw a solid portion, the next is how long to draw the gap, then the solid, etc. It is terminated with a zero-length entry. A NULL pointer or a zero-length array results in a solid line. Odd array sizes are not supported and result in undefined behavior.
Note:
Because of how line styles are implemented on Win32 systems, you must set the line style after setting the drawing color. If you set the color after the line style you will lose the line style settings.
The dashes array does not work under Windows 95, 98 or Me, since those operating systems do not support complex line styles.
Definition at line 184 of file fl_draw.H.
References fl_graphics_driver, Fl_Graphics_Driver::line_style(), and width.
Referenced by Fl_Widget::draw_focus(), and Fl_Window_Type::draw_overlay().
void fl_loop (int x, int y, int x1, int y1, int x2, int y2, int x3, int y3) [inline]
Outlines a 4-sided polygon with lines
Definition at line 244 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::loop().
void fl_loop (int x, int y, int x1, int y1, int x2, int y2) [inline]
Outlines a 3-sided polygon with lines
Definition at line 240 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::loop().
FL_EXPORT void fl_measure (const char * str, int & w, int & h, int draw_symbols)
Measure how wide and tall the string will be when printed by the fl_draw() function with align parameter. If the incoming w is non-zero it will wrap to that width.
Parameters:
[in] str nul-terminated string
[out] w,h width and height of string in current font
[in] draw_symbols non-zero to enable @symbol handling [default=1]
Definition at line 400 of file fl_draw.cxx.
References buf, fl_expand_text(), fl_height(), h, int, MAXBUF, NULL, strlcpy, and width.
Referenced by Fl_Tree_Item::draw(), fl_normal_measure(), fl_text_extents(), Fl_TooltipBox::layout(), and resizeform().
FL_EXPORT int fl_measure_pixmap (char *const * data, int & w, int & h)
Get the dimensions of a pixmap. An XPM image contains the dimensions in its data. This function returns te width and height.
Parameters:
[in] data pointer to XPM image data.
[out] w,h width and height of image
Returns:
non-zero if the dimensions were parsed OK
0 if there were any problems
Definition at line 55 of file fl_draw_pixmap.cxx.
References fl_measure_pixmap().
Referenced by Fl_PostScript_Graphics_Driver::draw(), fl_draw_pixmap(), fl_measure_pixmap(), and Fl_Pixmap::measure().
FL_EXPORT int fl_measure_pixmap (const char *const * cdata, int & w, int & h)
Get the dimensions of a pixmap.
See also:
fl_measure_pixmap(char* const* data, int &w, int &h)
Definition at line 63 of file fl_draw_pixmap.cxx.
References chars_per_pixel, and i.
FL_EXPORT void fl_mult_matrix (double a, double b, double c, double d, double x, double y)
Concatenates another transformation onto the current one.
Parameters:
[in] a,b,c,d,x,y transformation matrix elements such that X' = aX + cY + x and Y' = bX +dY + y
Definition at line 82 of file fl_vertex.cxx.
References matrix::a, matrix::b, matrix::c, matrix::d, matrix::x, and matrix::y.
Referenced by fl_rotate(), fl_scale(), and fl_translate().
int fl_not_clipped (int x, int y, int w, int h) [inline]
Does the rectangle intersect the current clip region?
Parameters:
[in] x,y,w,h position and size of rectangle
Returns:
non-zero if any of the rectangle intersects the current clip region. If this returns 0 you don't have to draw the object.
Note:
Under X this returns 2 if the rectangle is partially clipped, and 1 if it is entirely inside the clip region.
Definition at line 118 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::not_clipped().
Referenced by Fl_Group::draw_child(), fl_draw(), and Fl_Group::update_child().
FL_EXPORT unsigned int fl_old_shortcut (const char * s)
Emulation of XForms named shortcuts.
Converts ascii shortcut specifications (eg. "^c") into the FLTK integer equivalent (eg. FL_CTRL+'c')
These ascii characters are used to specify the various keyboard modifier keys:
   # - Alt
   + - Shift
   ^ - Control
Definition at line 285 of file fl_shortcut.cxx.
FL_EXPORT void fl_overlay_clear ()
Erase a selection rectangle without drawing a new one
Definition at line 109 of file fl_overlay.cxx.
References pw.
FL_EXPORT void fl_overlay_rect (int x, int y, int w, int h)
Draws a selection rectangle, erasing a previous one by XOR'ing it first.
Definition at line 116 of file fl_overlay.cxx.
References h, ph, pw, py, w, x, and y.
void fl_pie (int x, int y, int w, int h, double a1, double a2) [inline]
Draw filled ellipse sections using integer coordinates.
Like fl_arc(), but fl_pie() draws a filled-in pie slice. This slice may extend outside the line drawn by fl_arc(); to avoid this use w - 1 and h - 1.
Parameters:
[in] x,y,w,h bounding box of complete circle
[in] a1,a2 start and end angles of arc measured in degrees counter-clockwise from 3 o'clock. a2 must be greater than or equal to a1.
Definition at line 324 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::pie().
Referenced by Fl_Menu_Item::draw(), Fl_Light_Button::draw(), and Fl_Dial::draw().
void fl_point (int x, int y) [inline]
Draws a single pixel at the given coordinates
Definition at line 154 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::point().
Referenced by Fl_Widget::draw_focus(), Fl_Tree_Item::draw_horizontal_connector(), and Fl_Tree_Item::draw_vertical_connector().
void fl_polygon (int x, int y, int x1, int y1, int x2, int y2, int x3, int y3) [inline]
Fills a 4-sided polygon. The polygon must be convex.
Definition at line 255 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::polygon().
void fl_polygon (int x, int y, int x1, int y1, int x2, int y2) [inline]
Fills a 3-sided polygon. The polygon must be convex.
Definition at line 251 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::polygon().
Referenced by Fl_Scrollbar::draw(), and Fl_Choice::draw().
void fl_pop_clip () [inline]
Restores the previous clip region.
You must call fl_pop_clip() once for every time you call fl_push_clip(). Unpredictable results may occur if the clip stack is not empty when you return to FLTK.
Definition at line 107 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::pop_clip().
Referenced by Fl_Tree::draw(), Fl_Tiled_Image::draw(), Fl_Text_Display::draw(), Fl_Tabs::draw(), Fl_Table::draw(), Fl_Scroll::draw(), Fl_Progress::draw(), Flcc_ValueBox::draw(), Flcc_HueBox::draw(), Fl_Choice::draw(), Fl_Chart::draw(), Fl_Browser_::draw(), Fl_Group::draw_children(), Fl_Text_Display::draw_string(), Fl_Text_Display::draw_text(), Fl_Input_::drawtext(), fl_draw(), and Fl_Paged_Device::print_widget().
FL_EXPORT void fl_pop_matrix ()
Restores the current transformation matrix from the stack.
Definition at line 69 of file fl_vertex.cxx.
References Fl::error.
Referenced by Fl_File_Icon::draw(), Fl_Dial::draw(), Fl_Clock_Output::draw(), and fl_draw_symbol().
void fl_push_clip (int x, int y, int w, int h) [inline]
Intersects the current clip region with a rectangle and pushes this new region onto the stack.
Parameters:
[in] x,y,w,h position and size
Definition at line 93 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::push_clip().
Referenced by Fl_Tree::draw(), Fl_Tiled_Image::draw(), Fl_Text_Display::draw(), Fl_Tabs::draw(), Fl_Table::draw(), Fl_Scroll::draw(), Fl_Progress::draw(), Flcc_ValueBox::draw(), Flcc_HueBox::draw(), Fl_Choice::draw(), Fl_Chart::draw(), Fl_Browser_::draw(), Fl_Group::draw_children(), Fl_Text_Display::draw_string(), Fl_Text_Display::draw_text(), Fl_Input_::drawtext(), fl_draw(), and Fl_Paged_Device::print_widget().
FL_EXPORT void fl_push_matrix ()
Saves the current transformation matrix on the stack. The maximum depth of the stack is 4.
Definition at line 59 of file fl_vertex.cxx.
References Fl::error, and m.
Referenced by Fl_File_Icon::draw(), Fl_Dial::draw(), Fl_Clock_Output::draw(), and fl_draw_symbol().
void fl_push_no_clip () [inline]
Pushes an empty clip region onto the stack so nothing will be clipped.
Definition at line 99 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::push_no_clip().
FL_EXPORT uchar* fl_read_image (uchar * p, int X, int Y, int W, int H, int alpha = 0)
Read an RGB(A) image from the current window or off-screen buffer.
Parameters:
[in] p pixel buffer, or NULL to allocate one
[in] X,Y position of top-left of image to read
[in] W,H width and height of image to read
[in] alpha alpha value for image (0 fr none)
Returns:
pointer to pixel buffer, or NULL if allocation failed.
The p argument points to a buffer that can hold the image and must be at least W*H*3 bytes when reading RGB images, or W*H*4 bytes when reading RGBA images. If NULL, fl_read_image() will create an array of the proper suze which can be freed using delete[].
The alpha parameter controls whether an alpha channel is created and the value that is placed in the alpha channel. If 0, no alpha channel is generated.
Definition at line 91 of file fl_read_image.cxx.
References b, bi, BI_RGB, buf, Fl_Window::current(), dx, dy, fl_bluemask, fl_blueshift, fl_colormap, fl_display, fl_find(), fl_gc, fl_greenmask, fl_greenshift, fl_redmask, fl_redshift, fl_screen, fl_visual, fl_window, h, i, image, NULL, Fl::screen_xywh(), tg, w, Fl_Widget::window(), x, and y.
Referenced by fl_copy_offscreen(), Fl_Paged_Device::print_window_part(), and Overlay_Window::read_image().
void fl_rect (int x, int y, int w, int h) [inline]
Draws a 1-pixel border inside the given bounding box. This function is meant for quick drawing of simple boxes. The behavior is undefined for line widths that are not 1.
Definition at line 208 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::rect().
Referenced by Fl_Image::draw_empty(), Fl_Widget::draw_focus(), Fl_Window_Type::draw_overlay(), fl_rect(), and fl_rectbound().
void fl_rect (int x, int y, int w, int h, Fl_Color c) [inline]
Draws with passed color a 1-pixel border inside the given bounding box
Definition at line 211 of file fl_draw.H.
References fl_color(), and fl_rect().
FL_EXPORT void fl_rectf (int x, int y, int w, int h, uchar r, uchar g, uchar b)
Color a rectangle with "exactly" the passed r,g,b color. On screens with less than 24 bits of color this is done by drawing a solid-colored block using fl_draw_image() so that the correct color shade is produced.
Definition at line 561 of file fl_draw_image.cxx.
References b, fl_color(), fl_palette, fl_rectf(), and fl_visual.
void fl_rectf (int x, int y, int w, int h) [inline]
Colors with current color a rectangle that exactly fills the given bounding box
Definition at line 213 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::rectf().
Referenced by Fl_Text_Display::clear_rect(), Fl_Value_Output::draw(), Fl_Tree_Item::draw(), Fl_Text_Display::draw(), Fl_Table::draw(), Fl_Scroll::draw(), Fl_Roller::draw(), Fl_Pack::draw(), Fl_Menu_Item::draw(), Fl_Light_Button::draw(), Fl_Browser_::draw(), Fl_Window_Type::draw_overlay(), Fl_Text_Display::draw_string(), Fl_Input_::drawtext(), fl_down_box(), fl_embossed_box(), fl_engraved_box(), fl_rectbound(), fl_rectf(), fl_thin_down_box(), fl_thin_up_box(), fl_up_box(), and Fl_Browser::item_draw().
void fl_rectf (int x, int y, int w, int h, Fl_Color c) [inline]
Colors with passsed color a rectangle that exactly fills the given bounding box
Definition at line 215 of file fl_draw.H.
References fl_color(), and fl_rectf().
FL_EXPORT void fl_reset_spot (void)
Todo:
provide user documentation for fl_reset_spot function
Definition at line 128 of file Fl_mac.cxx.
References XRectangle::x, and XRectangle::y.
Referenced by Fl_Input_::handletext().
void fl_restore_clip ()
Undoes any clobbering of clip done by your program
Definition at line 529 of file fl_rect.cxx.
Referenced by Fl_Xlib_Graphics_Driver::draw(), fl_clip_region(), Fl_Double_Window::flush(), Fl_Graphics_Driver::pop_clip(), Fl_Graphics_Driver::push_clip(), and Fl_Graphics_Driver::push_no_clip().
FL_EXPORT void fl_rotate (double d)
Concatenates rotation transformation onto the current one.
Parameters:
[in] d - rotation angle, counter-clockwise in degrees (not radians)
Definition at line 115 of file fl_vertex.cxx.
References fl_mult_matrix(), and M_PI.
Referenced by Fl_Dial::draw(), Fl_Clock_Output::draw(), and fl_draw_symbol().
void fl_rtl_draw (const char * str, int n, int x, int y) [inline]
Draws an array of n characters right to left starting at given location.
Definition at line 567 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::rtl_draw().
FL_EXPORT void fl_scale (double x)
Concatenates scaling transformation onto the current one.
Parameters:
[in] x scale factor in both x-direction and y-direction
Definition at line 103 of file fl_vertex.cxx.
References fl_mult_matrix().
FL_EXPORT void fl_scale (double x, double y)
Concatenates scaling transformation onto the current one.
Parameters:
[in] x,y scale factors in x-direction and y-direction
Definition at line 97 of file fl_vertex.cxx.
References fl_mult_matrix().
Referenced by Fl_File_Icon::draw(), Fl_Dial::draw(), Fl_Clock_Output::draw(), and fl_draw_symbol().
FL_EXPORT void fl_scroll (int X, int Y, int W, int H, int dx, int dy, void(*)(void *, int, int, int, int) draw_area, void * data)
Scroll a rectangle and draw the newly exposed portions.
Parameters:
[in] X,Y position of top-left of rectangle
[in] W,H size of rectangle
[in] dx,dy pixel offsets for shifting rectangle
[in] draw_area callback function to draw rectangular areas
[in] data pointer to user data for callback The contents of the rectangular area is first shifted by dx and dy pixels. The draw_area callback is then called for every newly exposed rectangular area.
Definition at line 49 of file fl_scroll_area.cxx.
References Fl_Window::current(), dx, dy, fl_display, fl_gc, fl_window, int, and rect().
Referenced by Fl_Scroll::draw().
FL_EXPORT void fl_set_spot (int font, int size, int X, int Y, int W, int H, Fl_Window * win = 0)
Todo:
provide user documentation for fl_set_spot function
Definition at line 132 of file Fl_mac.cxx.
References fl_get_font_xfld(), fl_xid(), fl_xim_ic, H, XRectangle::height, Fl_Widget::labelsize(), NULL, Fl_Widget::parent(), size, XRectangle::width, Fl_Widget::window(), XRectangle::x, and XRectangle::y.
Referenced by Fl_Input_::drawtext(), fl_handle(), and Fl_Input_::handletext().
FL_EXPORT void fl_set_status (int X, int Y, int W, int H)
Todo:
provide user documentation for fl_set_status function
Definition at line 136 of file Fl_mac.cxx.
References h, XRectangle::height, NULL, w, XRectangle::width, x, XRectangle::x, y, and XRectangle::y.
FL_EXPORT const char* fl_shortcut_label (unsigned int shortcut, const char ** eom)
Get a human-readable string from a shortcut value.
Parameters:
[in] shortcut the integer value containing the ascii charcter or extended keystroke plus modifiers
[in] eom if this pointer is set, it will receive a pointer to the end of the modifier text
Returns:
a pointer to a static buffer containing human readable text for the shortcut
See also:
fl_shortcut_label(unsigned int shortcut)
Definition at line 191 of file fl_shortcut.cxx.
References b, buf, FL_ALT, FL_CTRL, FL_Enter, FL_F, FL_F_Last, FL_KEY_MASK, FL_KP, FL_KP_Last, FL_META, FL_SHIFT, fl_tolower(), fl_toupper(), fl_utf8encode(), key, Keyname::name, and name.
FL_EXPORT const char* fl_shortcut_label (unsigned int shortcut)
Get a human-readable string from a shortcut value.
Unparse a shortcut value as used by Fl_Button or Fl_Menu_Item into a human-readable string like "Alt+N". This only works if the shortcut is a character key or a numbered function key. If the shortcut is zero then an empty string is returned. The return value points at a static buffer that is overwritten with each call.
Parameters:
[in] shortcut the integer value containing the ascii charcter or extended keystroke plus modifiers
Returns:
a pointer to a static buffer containing human readable text for the shortcut
Definition at line 179 of file fl_shortcut.cxx.
References fl_shortcut_label().
Referenced by Shortcut_Button::draw(), fl_shortcut_label(), and menuwindow::menuwindow().
FL_EXPORT double fl_transform_dx (double x, double y)
Transforms distance using current transformation matrix.
Parameters:
[in] x,y coordinate
Definition at line 172 of file fl_vertex.cxx.
References matrix::a, and matrix::c.
Referenced by Fl_Graphics_Driver::arc().
FL_EXPORT double fl_transform_dy (double x, double y)
Transforms distance using current transformation matrix.
Parameters:
[in] x,y coordinate
Definition at line 178 of file fl_vertex.cxx.
References matrix::b, and matrix::d.
Referenced by Fl_Graphics_Driver::arc().
FL_EXPORT double fl_transform_x (double x, double y)
Transforms coordinate using the current transformation matrix.
Parameters:
[in] x,y coordinate
Definition at line 160 of file fl_vertex.cxx.
References matrix::a, matrix::c, and matrix::x.
Referenced by Fl_Graphics_Driver::circle(), and Fl_Graphics_Driver::curve().
FL_EXPORT double fl_transform_y (double x, double y)
Transform coordinate using the current transformation matrix.
Parameters:
[in] x,y coordinate
Definition at line 166 of file fl_vertex.cxx.
References matrix::b, matrix::d, and matrix::y.
Referenced by Fl_Graphics_Driver::circle(), and Fl_Graphics_Driver::curve().
void fl_transformed_vertex (double xf, double yf) [inline]
Adds coordinate pair to the vertex list without further transformations.
Parameters:
[in] xf,yf transformed coordinate
Definition at line 435 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::transformed_vertex().
FL_EXPORT void fl_translate (double x, double y)
Concatenates translation transformation onto the current one.
Parameters:
[in] x,y translation factor in x-direction and y-direction
Definition at line 109 of file fl_vertex.cxx.
References fl_mult_matrix().
Referenced by Fl_File_Icon::draw(), Fl_Dial::draw(), Fl_Clock_Output::draw(), and fl_draw_symbol().
void fl_vertex (double x, double y) [inline]
Adds a single vertex to the current path.
Parameters:
[in] x,y coordinate
Definition at line 356 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::vertex().
Referenced by Fl_File_Icon::draw(), and Fl_Dial::draw().
void fl_xyline (int x, int y, int x1) [inline]
Draws a horizontal line from (x,y) to (x1,y)
Definition at line 262 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::xyline().
Referenced by Fl_Roller::draw(), Fl_Positioner::draw(), fl_frame(), fl_frame2(), and fl_return_arrow().
void fl_xyline (int x, int y, int x1, int y2) [inline]
Draws a horizontal line from (x,y) to (x1,y), then vertical from (x1,y) to (x1,y2)
Definition at line 266 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::xyline().
void fl_xyline (int x, int y, int x1, int y2, int x3) [inline]
Draws a horizontal line from (x,y) to (x1,y), then a vertical from (x1,y) to (x1,y2) and then another horizontal from (x1,y2) to (x3,y2)
Definition at line 271 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::xyline().
void fl_yxline (int x, int y, int y1) [inline]
Draws a vertical line from (x,y) to (x,y1)
Definition at line 277 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::yxline().
Referenced by Fl_Roller::draw(), Fl_Positioner::draw(), Fl_Menu_Bar::draw(), Fl_Choice::draw(), fl_frame(), fl_frame2(), and fl_return_arrow().
void fl_yxline (int x, int y, int y1, int x2) [inline]
Draws a vertical line from (x,y) to (x,y1), then a horizontal from (x,y1) to (x2,y1)
Definition at line 281 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::yxline().
void fl_yxline (int x, int y, int y1, int x2, int y3) [inline]
Draws a vertical line from (x,y) to (x,y1) then a horizontal from (x,y1) to (x2,y1), then another vertical from (x2,y1) to (x2,y3)
Definition at line 286 of file fl_draw.H.
References fl_graphics_driver, and Fl_Graphics_Driver::yxline().