SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jcmaster.c File Reference
jcmaster.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Classes
struct my_comp_master
Defines
#define JPEG_INTERNALS
#define MAX_AH_AL 10
Typedefs
typedef my_comp_master * my_master_ptr
Enumerations
enum c_pass_type { main_pass, huff_opt_pass, output_pass }
Functions
initial_setup (j_compress_ptr cinfo)
validate_script (j_compress_ptr cinfo)
select_scan_parameters (j_compress_ptr cinfo)
per_scan_setup (j_compress_ptr cinfo)
prepare_for_pass (j_compress_ptr cinfo)
pass_startup (j_compress_ptr cinfo)
finish_pass_master (j_compress_ptr cinfo)
jinit_c_master_control (j_compress_ptr cinfo, boolean transcode_only)
Define Documentation
#define JPEG_INTERNALS
Definition at line 14 of file jcmaster.c.
#define MAX_AH_AL 10
Referenced by validate_script().
Typedef Documentation
typedef my_comp_master* my_master_ptr
Definition at line 38 of file jcmaster.c.
Enumeration Type Documentation
enum c_pass_type
Enumerator:
main_pass
huff_opt_pass
output_pass
Definition at line 21 of file jcmaster.c.
Function Documentation
finish_pass_master (j_compress_ptr cinfo)
Definition at line 503 of file jcmaster.c.
References huff_opt_pass, main_pass, output_pass, my_comp_master::pass_number, my_comp_master::pass_type, and my_comp_master::scan_number.
Referenced by jinit_c_master_control().
initial_setup (j_compress_ptr cinfo)
Definition at line 46 of file jcmaster.c.
References BITS_IN_JSAMPLE, jpeg_component_info::component_index, jpeg_component_info::component_needed, compptr, jpeg_component_info::DCT_scaled_size, DCTSIZE, jpeg_component_info::downsampled_height, jpeg_component_info::downsampled_width, ERREXIT, ERREXIT1, ERREXIT2, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, jdiv_round_up(), JPEG_MAX_DIMENSION, MAX, MAX_COMPONENTS, MAX_SAMP_FACTOR, TRUE, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
Referenced by consume_markers(), and jinit_c_master_control().
jinit_c_master_control (j_compress_ptr cinfo, boolean transcode_only)
Definition at line 543 of file jcmaster.c.
References ERREXIT, FALSE, finish_pass_master(), huff_opt_pass, initial_setup(), jpeg_comp_master::is_last_pass, JPOOL_IMAGE, main_pass, NULL, output_pass, my_comp_master::pass_number, pass_startup(), my_comp_master::pass_type, prepare_for_pass(), my_comp_master::pub, my_comp_master::scan_number, SIZEOF, my_comp_master::total_passes, TRUE, and validate_script().
Referenced by jinit_compress_master(), and transencode_master_selection().
pass_startup (j_compress_ptr cinfo)
Definition at line 489 of file jcmaster.c.
References FALSE.
Referenced by jinit_c_master_control().
per_scan_setup (j_compress_ptr cinfo)
Definition at line 308 of file jcmaster.c.
References C_MAX_BLOCKS_IN_MCU, compptr, DCTSIZE, ERREXIT, ERREXIT2, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, int, jdiv_round_up(), jpeg_component_info::last_col_width, jpeg_component_info::last_row_height, MAX_COMPS_IN_SCAN, jpeg_component_info::MCU_blocks, jpeg_component_info::MCU_height, jpeg_component_info::MCU_sample_width, jpeg_component_info::MCU_width, MIN, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
Referenced by prepare_for_pass(), and start_input_pass().
prepare_for_pass (j_compress_ptr cinfo)
Definition at line 401 of file jcmaster.c.
References jpeg_comp_master::call_pass_startup, ERREXIT, FALSE, huff_opt_pass, jpeg_comp_master::is_last_pass, JBUF_CRANK_DEST, JBUF_PASS_THRU, JBUF_SAVE_AND_PASS, main_pass, NULL, output_pass, my_comp_master::pass_number, my_comp_master::pass_type, per_scan_setup(), my_comp_master::pub, my_comp_master::scan_number, select_scan_parameters(), my_comp_master::total_passes, and TRUE.
Referenced by jinit_c_master_control().
select_scan_parameters (j_compress_ptr cinfo)
Definition at line 267 of file jcmaster.c.
References DCTSIZE2, ERREXIT2, MAX_COMPS_IN_SCAN, NULL, and my_comp_master::scan_number.
Referenced by prepare_for_pass().
validate_script (j_compress_ptr cinfo)
Definition at line 130 of file jcmaster.c.
References jpeg_scan_info::Ah, jpeg_scan_info::Al, jpeg_scan_info::component_index, jpeg_scan_info::comps_in_scan, DCTSIZE2, ERREXIT, ERREXIT1, ERREXIT2, FALSE, MAX_AH_AL, MAX_COMPONENTS, MAX_COMPS_IN_SCAN, jpeg_scan_info::Se, jpeg_scan_info::Ss, and TRUE.
Referenced by jinit_c_master_control().