SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jcprepct.c File Reference
jcprepct.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Classes
struct my_prep_controller
Defines
#define JPEG_INTERNALS
#define CONTEXT_ROWS_SUPPORTED
Typedefs
typedef my_prep_controller * my_prep_ptr
Functions
start_pass_prep (j_compress_ptr cinfo, J_BUF_MODE pass_mode)
expand_bottom_edge (JSAMPARRAY image_data, JDIMENSION num_cols, int input_rows, int output_rows)
pre_process_data (j_compress_ptr cinfo, JSAMPARRAY input_buf, JDIMENSION *in_row_ctr, JDIMENSION in_rows_avail, JSAMPIMAGE output_buf, JDIMENSION *out_row_group_ctr, JDIMENSION out_row_groups_avail)
pre_process_context (j_compress_ptr cinfo, JSAMPARRAY input_buf, JDIMENSION *in_row_ctr, JDIMENSION in_rows_avail, JSAMPIMAGE output_buf, JDIMENSION *out_row_group_ctr, JDIMENSION out_row_groups_avail)
create_context_buffer (j_compress_ptr cinfo)
jinit_c_prep_controller (j_compress_ptr cinfo, boolean need_full_buffer)
Define Documentation
#define CONTEXT_ROWS_SUPPORTED
Definition at line 28 of file jcprepct.c.
#define JPEG_INTERNALS
Definition at line 17 of file jcprepct.c.
Typedef Documentation
typedef my_prep_controller* my_prep_ptr
Definition at line 70 of file jcprepct.c.
Function Documentation
create_context_buffer (j_compress_ptr cinfo)
Definition at line 267 of file jcprepct.c.
References my_prep_controller::color_buf, compptr, DCTSIZE, jpeg_component_info::h_samp_factor, i, JPOOL_IMAGE, MEMCOPY, SIZEOF, and jpeg_component_info::width_in_blocks.
Referenced by jinit_c_prep_controller().
expand_bottom_edge (JSAMPARRAY image_data, JDIMENSION num_cols, int input_rows, int output_rows)
Definition at line 106 of file jcprepct.c.
References jcopy_sample_rows(), and row.
Referenced by pre_process_context(), and pre_process_data().
jinit_c_prep_controller (j_compress_ptr cinfo, boolean need_full_buffer)
Definition at line 315 of file jcprepct.c.
References my_prep_controller::color_buf, compptr, create_context_buffer(), DCTSIZE, ERREXIT, jpeg_component_info::h_samp_factor, JPOOL_IMAGE, pre_process_context(), pre_process_data(), my_prep_controller::pub, SIZEOF, start_pass_prep(), and jpeg_component_info::width_in_blocks.
Referenced by jinit_compress_master().
pre_process_context (j_compress_ptr cinfo, JSAMPARRAY input_buf, JDIMENSION * in_row_ctr, JDIMENSION in_rows_avail, JSAMPIMAGE output_buf, JDIMENSION * out_row_group_ctr, JDIMENSION out_row_groups_avail)
Definition at line 195 of file jcprepct.c.
References my_prep_controller::color_buf, expand_bottom_edge(), int, jcopy_sample_rows(), MIN, my_prep_controller::next_buf_row, my_prep_controller::next_buf_stop, output_buf, row, my_prep_controller::rows_to_go, and my_prep_controller::this_row_group.
Referenced by jinit_c_prep_controller().
pre_process_data (j_compress_ptr cinfo, JSAMPARRAY input_buf, JDIMENSION * in_row_ctr, JDIMENSION in_rows_avail, JSAMPIMAGE output_buf, JDIMENSION * out_row_group_ctr, JDIMENSION out_row_groups_avail)
Definition at line 128 of file jcprepct.c.
References my_prep_controller::color_buf, compptr, DCTSIZE, expand_bottom_edge(), int, MIN, my_prep_controller::next_buf_row, output_buf, my_prep_controller::rows_to_go, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
Referenced by jinit_c_prep_controller().
start_pass_prep (j_compress_ptr cinfo, J_BUF_MODE pass_mode)
Definition at line 78 of file jcprepct.c.
References ERREXIT, JBUF_PASS_THRU, my_prep_controller::next_buf_row, my_prep_controller::next_buf_stop, my_prep_controller::rows_to_go, and my_prep_controller::this_row_group.
Referenced by jinit_c_prep_controller().