SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jdapimin.c File Reference
jdapimin.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Defines
#define JPEG_INTERNALS
Functions
jpeg_CreateDecompress (j_decompress_ptr cinfo, int version, size_t structsize)
jpeg_destroy_decompress (j_decompress_ptr cinfo)
jpeg_abort_decompress (j_decompress_ptr cinfo)
default_decompress_parms (j_decompress_ptr cinfo)
jpeg_read_header (j_decompress_ptr cinfo, boolean require_image)
jpeg_consume_input (j_decompress_ptr cinfo)
jpeg_input_complete (j_decompress_ptr cinfo)
jpeg_has_multiple_scans (j_decompress_ptr cinfo)
jpeg_finish_decompress (j_decompress_ptr cinfo)
Define Documentation
#define JPEG_INTERNALS
Definition at line 19 of file jdapimin.c.
Function Documentation
default_decompress_parms (j_decompress_ptr cinfo)
Definition at line 114 of file jdapimin.c.
References FALSE, JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_UNKNOWN, JCS_YCbCr, JCS_YCCK, JDCT_DEFAULT, JDITHER_FS, NULL, TRACEMS3, TRUE, and WARNMS1.
Referenced by jpeg_consume_input().
jpeg_abort_decompress (j_decompress_ptr cinfo)
Definition at line 103 of file jdapimin.c.
References jpeg_abort().
jpeg_consume_input (j_decompress_ptr cinfo)
Definition at line 287 of file jdapimin.c.
References default_decompress_parms(), DSTATE_BUFIMAGE, DSTATE_BUFPOST, DSTATE_INHEADER, DSTATE_PRELOAD, DSTATE_PRESCAN, DSTATE_RAW_OK, DSTATE_READY, DSTATE_SCANNING, DSTATE_START, DSTATE_STOPPING, ERREXIT1, JPEG_REACHED_SOS, and JPEG_SUSPENDED.
Referenced by jpeg_read_header().
jpeg_CreateDecompress (j_decompress_ptr cinfo, int version, size_t structsize)
Definition at line 30 of file jdapimin.c.
References DSTATE_START, ERREXIT2, i, jinit_input_controller(), jinit_marker_reader(), jinit_memory_mgr(), JPEG_LIB_VERSION, MEMZERO, NULL, NUM_HUFF_TBLS, NUM_QUANT_TBLS, SIZEOF, and TRUE.
jpeg_destroy_decompress (j_decompress_ptr cinfo)
Definition at line 91 of file jdapimin.c.
References jpeg_destroy().
Referenced by Fl_JPEG_Image::Fl_JPEG_Image().
jpeg_finish_decompress (j_decompress_ptr cinfo)
Definition at line 369 of file jdapimin.c.
References DSTATE_BUFIMAGE, DSTATE_RAW_OK, DSTATE_SCANNING, DSTATE_STOPPING, ERREXIT, ERREXIT1, FALSE, jpeg_abort(), JPEG_SUSPENDED, and TRUE.
Referenced by Fl_JPEG_Image::Fl_JPEG_Image().
jpeg_has_multiple_scans (j_decompress_ptr cinfo)
Definition at line 349 of file jdapimin.c.
References DSTATE_READY, DSTATE_STOPPING, and ERREXIT1.
jpeg_input_complete (j_decompress_ptr cinfo)
Definition at line 334 of file jdapimin.c.
References DSTATE_START, DSTATE_STOPPING, and ERREXIT1.
jpeg_read_header (j_decompress_ptr cinfo, boolean require_image)
Definition at line 241 of file jdapimin.c.
References DSTATE_INHEADER, DSTATE_START, ERREXIT, ERREXIT1, jpeg_abort(), jpeg_consume_input(), JPEG_HEADER_OK, JPEG_HEADER_TABLES_ONLY, JPEG_REACHED_EOI, JPEG_REACHED_SOS, and JPEG_SUSPENDED.
Referenced by Fl_JPEG_Image::Fl_JPEG_Image().