SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jdatadst.c File Reference
jdatadst.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jerror.h"
Classes
struct my_destination_mgr
Defines
#define OUTPUT_BUF_SIZE 4096
Typedefs
typedef my_destination_mgr * my_dest_ptr
Functions
init_destination (j_compress_ptr cinfo)
empty_output_buffer (j_compress_ptr cinfo)
term_destination (j_compress_ptr cinfo)
jpeg_stdio_dest (j_compress_ptr cinfo, FILE *outfile)
Define Documentation
#define OUTPUT_BUF_SIZE 4096
Definition at line 34 of file jdatadst.c.
Referenced by empty_output_buffer(), init_destination(), and term_destination().
Typedef Documentation
typedef my_destination_mgr* my_dest_ptr
Definition at line 32 of file jdatadst.c.
Function Documentation
empty_output_buffer (j_compress_ptr cinfo)
Definition at line 81 of file jdatadst.c.
References my_destination_mgr::buffer, ERREXIT, jpeg_destination_mgr::free_in_buffer, JFWRITE, jpeg_destination_mgr::next_output_byte, my_destination_mgr::outfile, OUTPUT_BUF_SIZE, my_destination_mgr::pub, and TRUE.
Referenced by jpeg_stdio_dest().
init_destination (j_compress_ptr cinfo)
Definition at line 43 of file jdatadst.c.
References my_destination_mgr::buffer, jpeg_destination_mgr::free_in_buffer, JPOOL_IMAGE, jpeg_destination_mgr::next_output_byte, OUTPUT_BUF_SIZE, my_destination_mgr::pub, and SIZEOF.
Referenced by jpeg_stdio_dest().
jpeg_stdio_dest (j_compress_ptr cinfo, FILE * outfile)
Definition at line 130 of file jdatadst.c.
References empty_output_buffer(), init_destination(), JPOOL_PERMANENT, NULL, my_destination_mgr::outfile, my_destination_mgr::pub, SIZEOF, and term_destination().
term_destination (j_compress_ptr cinfo)
Definition at line 106 of file jdatadst.c.
References my_destination_mgr::buffer, ERREXIT, jpeg_destination_mgr::free_in_buffer, JFWRITE, my_destination_mgr::outfile, OUTPUT_BUF_SIZE, and my_destination_mgr::pub.
Referenced by jpeg_stdio_dest().