SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jdinput.c File Reference
jdinput.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Classes
struct my_input_controller
Defines
#define JPEG_INTERNALS
Typedefs
typedef my_input_controller * my_inputctl_ptr
Functions
METHODDEF (int)
per_scan_setup (j_decompress_ptr cinfo)
latch_quant_tables (j_decompress_ptr cinfo)
start_input_pass (j_decompress_ptr cinfo)
finish_input_pass (j_decompress_ptr cinfo)
consume_markers (j_decompress_ptr cinfo)
reset_input_controller (j_decompress_ptr cinfo)
jinit_input_controller (j_decompress_ptr cinfo)
Define Documentation
#define JPEG_INTERNALS
Definition at line 14 of file jdinput.c.
Typedef Documentation
typedef my_input_controller* my_inputctl_ptr
Definition at line 27 of file jdinput.c.
Function Documentation
consume_markers (j_decompress_ptr cinfo)
Definition at line 288 of file jdinput.c.
References jpeg_input_controller::eoi_reached, ERREXIT, FALSE, jpeg_input_controller::has_multiple_scans, my_input_controller::inheaders, initial_setup(), JPEG_REACHED_EOI, JPEG_REACHED_SOS, JPEG_SUSPENDED, my_input_controller::pub, start_input_pass(), TRUE, and val.
Referenced by finish_input_pass(), jinit_input_controller(), and reset_input_controller().
finish_input_pass (j_decompress_ptr cinfo)
Definition at line 271 of file jdinput.c.
References consume_markers().
Referenced by jinit_input_controller().
jinit_input_controller (j_decompress_ptr cinfo)
Definition at line 361 of file jdinput.c.
References consume_markers(), jpeg_input_controller::eoi_reached, FALSE, finish_input_pass(), jpeg_input_controller::has_multiple_scans, my_input_controller::inheaders, JPOOL_PERMANENT, my_input_controller::pub, reset_input_controller(), SIZEOF, start_input_pass(), and TRUE.
Referenced by jpeg_CreateDecompress().
latch_quant_tables (j_decompress_ptr cinfo)
Definition at line 220 of file jdinput.c.
References compptr, ERREXIT1, JPOOL_IMAGE, MEMCOPY, NULL, NUM_QUANT_TBLS, jpeg_component_info::quant_table, jpeg_component_info::quant_tbl_no, and SIZEOF.
Referenced by start_input_pass().
METHODDEF (int)
Definition at line 31 of file jdinput.c.
References BITS_IN_JSAMPLE, jpeg_component_info::component_needed, compptr, jpeg_component_info::DCT_scaled_size, DCTSIZE, jpeg_component_info::downsampled_height, jpeg_component_info::downsampled_width, ERREXIT, ERREXIT1, ERREXIT2, FALSE, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, jdiv_round_up(), JPEG_MAX_DIMENSION, MAX, MAX_COMPONENTS, MAX_SAMP_FACTOR, NULL, jpeg_component_info::quant_table, TRUE, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
per_scan_setup (j_decompress_ptr cinfo)
Definition at line 121 of file jdinput.c.
References compptr, D_MAX_BLOCKS_IN_MCU, jpeg_component_info::DCT_scaled_size, DCTSIZE, ERREXIT, ERREXIT2, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, int, jdiv_round_up(), jpeg_component_info::last_col_width, jpeg_component_info::last_row_height, MAX_COMPS_IN_SCAN, jpeg_component_info::MCU_blocks, jpeg_component_info::MCU_height, jpeg_component_info::MCU_sample_width, jpeg_component_info::MCU_width, jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
reset_input_controller (j_decompress_ptr cinfo)
Definition at line 339 of file jdinput.c.
References consume_markers(), jpeg_input_controller::eoi_reached, FALSE, jpeg_input_controller::has_multiple_scans, my_input_controller::inheaders, NULL, my_input_controller::pub, and TRUE.
Referenced by jinit_input_controller().
start_input_pass (j_decompress_ptr cinfo)
Definition at line 254 of file jdinput.c.
References latch_quant_tables(), and per_scan_setup().