SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jdphuff.c File Reference
jdphuff.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jdhuff.h"
Classes
struct savable_state
struct phuff_entropy_decoder
Defines
#define JPEG_INTERNALS
#define ASSIGN_STATE(dest, src) ((dest) = (src))
#define HUFF_EXTEND(x, s) ((x) < extend_test[s] ? (x) + extend_offset[s] : (x))
Typedefs
typedef phuff_entropy_decoder * phuff_entropy_ptr
Functions
METHODDEF (boolean)
process_restart (j_decompress_ptr cinfo)
decode_mcu_DC_first (j_decompress_ptr cinfo, JBLOCKROW *MCU_data)
decode_mcu_AC_first (j_decompress_ptr cinfo, JBLOCKROW *MCU_data)
decode_mcu_DC_refine (j_decompress_ptr cinfo, JBLOCKROW *MCU_data)
decode_mcu_AC_refine (j_decompress_ptr cinfo, JBLOCKROW *MCU_data)
jinit_phuff_decoder (j_decompress_ptr cinfo)
Define Documentation
#define ASSIGN_STATE (dest, src) ((dest) = (src))
Definition at line 43 of file jdphuff.c.
Referenced by decode_mcu_DC_first().
#define HUFF_EXTEND (x, s) ((x) < extend_test[s] ? (x) + extend_offset[s] : (x))
Definition at line 207 of file jdphuff.c.
Referenced by decode_mcu_AC_first(), and decode_mcu_DC_first().
#define JPEG_INTERNALS
Definition at line 17 of file jdphuff.c.
Typedef Documentation
typedef phuff_entropy_decoder* phuff_entropy_ptr
Definition at line 74 of file jdphuff.c.
Function Documentation
decode_mcu_AC_first (j_decompress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 357 of file jdphuff.c.
References BITREAD_LOAD_STATE, BITREAD_SAVE_STATE, BITREAD_STATE_VARS, CHECK_BIT_BUFFER, phuff_entropy_encoder::EOBRUN, FALSE, GET_BITS, HUFF_DECODE, HUFF_EXTEND, jpeg_natural_order, process_restart(), phuff_entropy_encoder::pub, phuff_entropy_encoder::restarts_to_go, and TRUE.
Referenced by METHODDEF().
decode_mcu_AC_refine (j_decompress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 491 of file jdphuff.c.
References BITREAD_LOAD_STATE, BITREAD_SAVE_STATE, BITREAD_STATE_VARS, CHECK_BIT_BUFFER, DCTSIZE2, phuff_entropy_encoder::EOBRUN, FALSE, GET_BITS, HUFF_DECODE, jpeg_natural_order, process_restart(), phuff_entropy_encoder::pub, phuff_entropy_encoder::restarts_to_go, TRUE, and WARNMS.
Referenced by METHODDEF().
decode_mcu_DC_first (j_decompress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 286 of file jdphuff.c.
References ASSIGN_STATE, BITREAD_LOAD_STATE, BITREAD_SAVE_STATE, BITREAD_STATE_VARS, CHECK_BIT_BUFFER, compptr, jpeg_component_info::dc_tbl_no, phuff_entropy_encoder::derived_tbls, FALSE, GET_BITS, HUFF_DECODE, HUFF_EXTEND, process_restart(), phuff_entropy_encoder::pub, phuff_entropy_encoder::restarts_to_go, state, and TRUE.
Referenced by METHODDEF().
decode_mcu_DC_refine (j_decompress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 442 of file jdphuff.c.
References BITREAD_LOAD_STATE, BITREAD_SAVE_STATE, BITREAD_STATE_VARS, CHECK_BIT_BUFFER, FALSE, GET_BITS, process_restart(), phuff_entropy_encoder::restarts_to_go, and TRUE.
Referenced by METHODDEF().
jinit_phuff_decoder (j_decompress_ptr cinfo)
Definition at line 641 of file jdphuff.c.
References DCTSIZE2, phuff_entropy_encoder::derived_tbls, i, int, JPOOL_IMAGE, NULL, NUM_HUFF_TBLS, phuff_entropy_encoder::pub, and SIZEOF.
Referenced by master_selection(), and transdecode_master_selection().
METHODDEF (boolean)
Definition at line 77 of file jdphuff.c.
References jpeg_component_info::ac_tbl_no, compptr, jpeg_component_info::dc_tbl_no, DCTSIZE2, decode_mcu_AC_first(), decode_mcu_AC_refine(), decode_mcu_DC_first(), decode_mcu_DC_refine(), phuff_entropy_encoder::derived_tbls, phuff_entropy_encoder::EOBRUN, ERREXIT4, FALSE, jpeg_make_d_derived_tbl(), phuff_entropy_encoder::last_dc_val, phuff_entropy_encoder::pub, phuff_entropy_encoder::restarts_to_go, TRUE, and WARNMS2.
process_restart (j_decompress_ptr cinfo)
Definition at line 228 of file jdphuff.c.
References phuff_entropy_encoder::EOBRUN, FALSE, phuff_entropy_encoder::last_dc_val, phuff_entropy_encoder::pub, phuff_entropy_encoder::restarts_to_go, and TRUE.