SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jdpostct.c File Reference
jdpostct.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Classes
struct my_post_controller
Defines
#define JPEG_INTERNALS
Typedefs
typedef my_post_controller * my_post_ptr
Functions
METHODDEF (void)
post_process_1pass (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION *in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
post_process_prepass (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION *in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
post_process_2pass (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION *in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
jinit_d_post_controller (j_decompress_ptr cinfo, boolean need_full_buffer)
Define Documentation
#define JPEG_INTERNALS
Definition at line 19 of file jdpostct.c.
Typedef Documentation
typedef my_post_controller* my_post_ptr
Definition at line 42 of file jdpostct.c.
Function Documentation
jinit_d_post_controller (j_decompress_ptr cinfo, boolean need_full_buffer)
Definition at line 250 of file jdpostct.c.
References my_post_controller::buffer, ERREXIT, FALSE, JPOOL_IMAGE, jround_up(), NULL, my_post_controller::pub, SIZEOF, my_post_controller::strip_height, and my_post_controller::whole_image.
Referenced by master_selection().
METHODDEF (void)
Definition at line 46 of file jdpostct.c.
References my_post_controller::buffer, ERREXIT, JBUF_CRANK_DEST, JBUF_PASS_THRU, JBUF_SAVE_AND_PASS, my_post_controller::next_row, NULL, post_process_1pass(), post_process_2pass(), post_process_prepass(), my_post_controller::pub, my_post_controller::starting_row, my_post_controller::strip_height, TRUE, and my_post_controller::whole_image.
post_process_1pass (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION * in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 126 of file jdpostct.c.
References my_post_controller::buffer, num_rows, and my_post_controller::strip_height.
Referenced by METHODDEF().
post_process_2pass (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION * in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 202 of file jdpostct.c.
References my_post_controller::buffer, FALSE, my_post_controller::next_row, num_rows, my_post_controller::starting_row, my_post_controller::strip_height, and my_post_controller::whole_image.
Referenced by METHODDEF().
post_process_prepass (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION * in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 158 of file jdpostct.c.
References my_post_controller::buffer, int, my_post_controller::next_row, NULL, num_rows, my_post_controller::starting_row, my_post_controller::strip_height, TRUE, and my_post_controller::whole_image.
Referenced by METHODDEF().