SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jerror.c File Reference
jerror.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jversion.h"
#include "jerror.h"
#include <stdlib.h>
Defines
#define EXIT_FAILURE 1
#define JMESSAGE(code, string) string ,
Functions
error_exit (j_common_ptr cinfo)
output_message (j_common_ptr cinfo)
emit_message (j_common_ptr cinfo, int msg_level)
format_message (j_common_ptr cinfo, char *buffer)
reset_error_mgr (j_common_ptr cinfo)
jpeg_std_error (struct jpeg_error_mgr *err)
Variables
const char *const jpeg_std_message_table []
Define Documentation
#define EXIT_FAILURE 1
Definition at line 33 of file jerror.c.
Referenced by error_exit().
#define JMESSAGE (code, string) string ,
Definition at line 49 of file jerror.c.
Function Documentation
emit_message (j_common_ptr cinfo, int msg_level)
Definition at line 129 of file jerror.c.
References jpeg_error_mgr::num_warnings, and jpeg_error_mgr::trace_level.
Referenced by jpeg_std_error().
error_exit (j_common_ptr cinfo)
Definition at line 71 of file jerror.c.
References EXIT_FAILURE, and jpeg_destroy().
Referenced by jpeg_std_error().
format_message (j_common_ptr cinfo, char * buffer)
Definition at line 158 of file jerror.c.
References jpeg_error_mgr::addon_message_table, FALSE, jpeg_error_mgr::first_addon_message, jpeg_error_mgr::i, jpeg_error_mgr::jpeg_message_table, jpeg_error_mgr::last_addon_message, jpeg_error_mgr::last_jpeg_message, jpeg_error_mgr::msg_code, jpeg_error_mgr::msg_parm, NULL, jpeg_error_mgr::s, and TRUE.
Referenced by jpeg_std_error().
jpeg_std_error (struct jpeg_error_mgr * err)
Definition at line 232 of file jerror.c.
References emit_message(), error_exit(), format_message(), int, jpeg_std_message_table, NULL, output_message(), and reset_error_mgr().
Referenced by Fl_JPEG_Image::Fl_JPEG_Image().
output_message (j_common_ptr cinfo)
Definition at line 99 of file jerror.c.
References buffer, and JMSG_LENGTH_MAX.
Referenced by jpeg_std_error().
reset_error_mgr (j_common_ptr cinfo)
Definition at line 213 of file jerror.c.
Referenced by jpeg_std_error().
Variable Documentation
const char* const jpeg_std_message_table[]
Definition at line 51 of file jerror.c.
Referenced by jpeg_std_error().