SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jmemmgr.c File Reference
jmemmgr.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jmemsys.h"
Classes
union small_pool_struct
union large_pool_struct
struct my_memory_mgr
struct jvirt_sarray_control
struct jvirt_barray_control
Defines
#define JPEG_INTERNALS
#define AM_MEMORY_MANAGER
#define ALIGN_TYPE double
#define MIN_SLOP 50
Typedefs
typedef union small_pool_struct * small_pool_ptr
typedef union small_pool_struct small_pool_hdr
typedef union
large_pool_struct FAR * large_pool_ptr
typedef union large_pool_struct large_pool_hdr
typedef my_memory_mgr * my_mem_ptr
Functions
char *getenv JPP ((const char *name))
out_of_memory (j_common_ptr cinfo, int which)
alloc_small (j_common_ptr cinfo, int pool_id, size_t sizeofobject)
alloc_large (j_common_ptr cinfo, int pool_id, size_t sizeofobject)
alloc_sarray (j_common_ptr cinfo, int pool_id, JDIMENSION samplesperrow, JDIMENSION numrows)
alloc_barray (j_common_ptr cinfo, int pool_id, JDIMENSION blocksperrow, JDIMENSION numrows)
request_virt_sarray (j_common_ptr cinfo, int pool_id, boolean pre_zero, JDIMENSION samplesperrow, JDIMENSION numrows, JDIMENSION maxaccess)
request_virt_barray (j_common_ptr cinfo, int pool_id, boolean pre_zero, JDIMENSION blocksperrow, JDIMENSION numrows, JDIMENSION maxaccess)
realize_virt_arrays (j_common_ptr cinfo)
do_sarray_io (j_common_ptr cinfo, jvirt_sarray_ptr ptr, boolean writing)
do_barray_io (j_common_ptr cinfo, jvirt_barray_ptr ptr, boolean writing)
access_virt_sarray (j_common_ptr cinfo, jvirt_sarray_ptr ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable)
access_virt_barray (j_common_ptr cinfo, jvirt_barray_ptr ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable)
free_pool (j_common_ptr cinfo, int pool_id)
self_destruct (j_common_ptr cinfo)
jinit_memory_mgr (j_common_ptr cinfo)
Define Documentation
#define ALIGN_TYPE double
Definition at line 73 of file jmemmgr.c.
Referenced by alloc_large(), alloc_small(), and jinit_memory_mgr().
#define AM_MEMORY_MANAGER
Definition at line 28 of file jmemmgr.c.
#define JPEG_INTERNALS
Definition at line 27 of file jmemmgr.c.
#define MIN_SLOP 50
Definition at line 253 of file jmemmgr.c.
Referenced by alloc_small().
Typedef Documentation
typedef union large_pool_struct large_pool_hdr
typedef union large_pool_struct FAR* large_pool_ptr
Definition at line 100 of file jmemmgr.c.
typedef my_memory_mgr* my_mem_ptr
Definition at line 140 of file jmemmgr.c.
typedef union small_pool_struct small_pool_hdr
typedef union small_pool_struct* small_pool_ptr
Definition at line 89 of file jmemmgr.c.
Function Documentation
access_virt_barray (j_common_ptr cinfo, jvirt_barray_ptr ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable)
Definition at line 841 of file jmemmgr.c.
References do_barray_io(), ERREXIT, FALSE, FAR, jzero_far(), NULL, num_rows, SIZEOF, and TRUE.
Referenced by jinit_memory_mgr().
access_virt_sarray (j_common_ptr cinfo, jvirt_sarray_ptr ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable)
Definition at line 756 of file jmemmgr.c.
References do_sarray_io(), ERREXIT, FALSE, FAR, jzero_far(), NULL, num_rows, SIZEOF, and TRUE.
Referenced by jinit_memory_mgr().
alloc_barray (j_common_ptr cinfo, int pool_id, JDIMENSION blocksperrow, JDIMENSION numrows)
Definition at line 443 of file jmemmgr.c.
References alloc_large(), alloc_small(), ERREXIT, i, my_memory_mgr::last_rowsperchunk, MAX_ALLOC_CHUNK, MIN, and SIZEOF.
Referenced by jinit_memory_mgr(), and realize_virt_arrays().
alloc_large (j_common_ptr cinfo, int pool_id, size_t sizeofobject)
Definition at line 342 of file jmemmgr.c.
References ALIGN_TYPE, ERREXIT1, jpeg_get_large(), JPOOL_NUMPOOLS, my_memory_mgr::large_list, MAX_ALLOC_CHUNK, NULL, out_of_memory(), SIZEOF, sizeofobject, and my_memory_mgr::total_space_allocated.
Referenced by alloc_barray(), alloc_sarray(), and jinit_memory_mgr().
alloc_sarray (j_common_ptr cinfo, int pool_id, JDIMENSION samplesperrow, JDIMENSION numrows)
Definition at line 395 of file jmemmgr.c.
References alloc_large(), alloc_small(), ERREXIT, i, my_memory_mgr::last_rowsperchunk, MAX_ALLOC_CHUNK, MIN, and SIZEOF.
Referenced by jinit_memory_mgr(), and realize_virt_arrays().
alloc_small (j_common_ptr cinfo, int pool_id, size_t sizeofobject)
Definition at line 257 of file jmemmgr.c.
References ALIGN_TYPE, small_pool_struct::bytes_left, small_pool_struct::bytes_used, ERREXIT1, small_pool_struct::hdr, jpeg_get_small(), JPOOL_NUMPOOLS, MAX_ALLOC_CHUNK, MIN_SLOP, small_pool_struct::next, NULL, out_of_memory(), SIZEOF, sizeofobject, my_memory_mgr::small_list, and my_memory_mgr::total_space_allocated.
Referenced by alloc_barray(), alloc_sarray(), jinit_memory_mgr(), request_virt_barray(), and request_virt_sarray().
do_barray_io (j_common_ptr cinfo, jvirt_barray_ptr ptr, boolean writing)
Definition at line 723 of file jmemmgr.c.
References FAR, i, MIN, and SIZEOF.
Referenced by access_virt_barray().
do_sarray_io (j_common_ptr cinfo, jvirt_sarray_ptr ptr, boolean writing)
Definition at line 690 of file jmemmgr.c.
References FAR, i, MIN, and SIZEOF.
Referenced by access_virt_sarray().
free_pool (j_common_ptr cinfo, int pool_id)
Definition at line 930 of file jmemmgr.c.
References jvirt_barray_control::b_s_info, jvirt_sarray_control::b_s_info, jvirt_barray_control::b_s_open, jvirt_sarray_control::b_s_open, small_pool_struct::bytes_used, ERREXIT1, FALSE, FAR, small_pool_struct::hdr, large_pool_struct::hdr, jpeg_free_large(), jpeg_free_small(), JPOOL_IMAGE, JPOOL_NUMPOOLS, my_memory_mgr::large_list, small_pool_struct::next, large_pool_struct::next, jvirt_barray_control::next, jvirt_sarray_control::next, NULL, SIZEOF, my_memory_mgr::small_list, my_memory_mgr::total_space_allocated, my_memory_mgr::virt_barray_list, and my_memory_mgr::virt_sarray_list.
Referenced by jinit_memory_mgr(), and self_destruct().
jinit_memory_mgr (j_common_ptr cinfo)
Definition at line 1028 of file jmemmgr.c.
References access_virt_barray(), access_virt_sarray(), ALIGN_TYPE, alloc_barray(), alloc_large(), alloc_sarray(), alloc_small(), ERREXIT, ERREXIT1, free_pool(), jpeg_get_small(), jpeg_mem_init(), jpeg_mem_term(), JPOOL_NUMPOOLS, JPOOL_PERMANENT, my_memory_mgr::large_list, jpeg_memory_mgr::max_alloc_chunk, MAX_ALLOC_CHUNK, jpeg_memory_mgr::max_memory_to_use, NULL, my_memory_mgr::pub, realize_virt_arrays(), request_virt_barray(), request_virt_sarray(), self_destruct(), SIZEOF, my_memory_mgr::small_list, my_memory_mgr::total_space_allocated, my_memory_mgr::virt_barray_list, and my_memory_mgr::virt_sarray_list.
Referenced by jpeg_CreateCompress(), and jpeg_CreateDecompress().
char* getenv JPP ((const char *name))
out_of_memory (j_common_ptr cinfo, int which)
Definition at line 217 of file jmemmgr.c.
References ERREXIT1.
Referenced by alloc_large(), and alloc_small().
realize_virt_arrays (j_common_ptr cinfo)
Definition at line 583 of file jmemmgr.c.
References alloc_barray(), alloc_sarray(), FALSE, jpeg_mem_available(), jpeg_open_backing_store(), JPOOL_IMAGE, my_memory_mgr::last_rowsperchunk, jvirt_barray_control::maxaccess, NULL, SIZEOF, my_memory_mgr::total_space_allocated, TRUE, my_memory_mgr::virt_barray_list, and my_memory_mgr::virt_sarray_list.
Referenced by jinit_memory_mgr().
request_virt_barray (j_common_ptr cinfo, int pool_id, boolean pre_zero, JDIMENSION blocksperrow, JDIMENSION numrows, JDIMENSION maxaccess)
Definition at line 553 of file jmemmgr.c.
References alloc_small(), ERREXIT1, FALSE, JPOOL_IMAGE, NULL, SIZEOF, and my_memory_mgr::virt_barray_list.
Referenced by jinit_memory_mgr().
request_virt_sarray (j_common_ptr cinfo, int pool_id, boolean pre_zero, JDIMENSION samplesperrow, JDIMENSION numrows, JDIMENSION maxaccess)
Definition at line 523 of file jmemmgr.c.
References alloc_small(), ERREXIT1, FALSE, JPOOL_IMAGE, NULL, SIZEOF, and my_memory_mgr::virt_sarray_list.
Referenced by jinit_memory_mgr().
self_destruct (j_common_ptr cinfo)
Definition at line 1002 of file jmemmgr.c.
References free_pool(), jpeg_free_small(), jpeg_mem_term(), JPOOL_NUMPOOLS, JPOOL_PERMANENT, NULL, and SIZEOF.
Referenced by jinit_memory_mgr().