SfR Fresh Dox - fltk: fltk-1.3.0rc3/jpeg/jmemnobs.c File Reference
jmemnobs.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jmemsys.h"
Defines
#define JPEG_INTERNALS
Functions
void *malloc JPP ((size_t size))
void free JPP ((void *ptr))
jpeg_get_small (j_common_ptr cinfo, size_t sizeofobject)
jpeg_free_small (j_common_ptr cinfo, void *object, size_t sizeofobject)
jpeg_get_large (j_common_ptr cinfo, size_t sizeofobject)
jpeg_free_large (j_common_ptr cinfo, void FAR *object, size_t sizeofobject)
jpeg_mem_available (j_common_ptr cinfo, long min_bytes_needed, long max_bytes_needed, long already_allocated)
jpeg_open_backing_store (j_common_ptr cinfo, backing_store_ptr info, long total_bytes_needed)
jpeg_mem_init (j_common_ptr cinfo)
jpeg_mem_term (j_common_ptr cinfo)
Define Documentation
#define JPEG_INTERNALS
Definition at line 18 of file jmemnobs.c.
Function Documentation
jpeg_free_large (j_common_ptr cinfo, void FAR * object, size_t sizeofobject)
Definition at line 61 of file jmemnobs.c.
Referenced by free_pool().
jpeg_free_small (j_common_ptr cinfo, void * object, size_t sizeofobject)
Definition at line 41 of file jmemnobs.c.
Referenced by free_pool(), and self_destruct().
jpeg_get_large (j_common_ptr cinfo, size_t sizeofobject)
Definition at line 55 of file jmemnobs.c.
Referenced by alloc_large().
jpeg_get_small (j_common_ptr cinfo, size_t sizeofobject)
Definition at line 35 of file jmemnobs.c.
Referenced by alloc_small(), and jinit_memory_mgr().
jpeg_mem_available (j_common_ptr cinfo, long min_bytes_needed, long max_bytes_needed, long already_allocated)
Definition at line 73 of file jmemnobs.c.
References max_bytes_needed.
Referenced by realize_virt_arrays().
jpeg_mem_init (j_common_ptr cinfo)
Definition at line 100 of file jmemnobs.c.
Referenced by jinit_memory_mgr().
jpeg_mem_term (j_common_ptr cinfo)
Definition at line 106 of file jmemnobs.c.
Referenced by jinit_memory_mgr(), and self_destruct().
jpeg_open_backing_store (j_common_ptr cinfo, backing_store_ptr info, long total_bytes_needed)
Definition at line 87 of file jmemnobs.c.
References ERREXIT.
Referenced by realize_virt_arrays().
void* malloc JPP ((size_t size))
void free JPP ((void *ptr))