SfR Fresh Dox - fltk: fltk-1.3.0rc3/FL/mac.H File Reference
mac.H File Reference
#include <FL/Fl_Widget.H>
Typedefs
typedef void * Window
typedef void * Fl_Offscreen
typedef void * Fl_Bitmask
typedef void * Fl_Region
typedef void * Fl_CGContextRef
typedef void * Fl_PMPrintSettings
typedef void * Fl_PMPageFormat
typedef void * Fl_PMPrintSession
Functions
Window fl_xid (const Fl_Window *)
void fl_clip_region (Fl_Region)
FL_EXPORT Fl_Bitmask fl_create_bitmask (int w, int h, const uchar *data)
FL_EXPORT Fl_Bitmask fl_create_alphamask (int w, int h, int d, int ld, const uchar *data)
FL_EXPORT void fl_delete_bitmask (Fl_Bitmask bm)
Fl_Offscreen fl_create_offscreen (int w, int h)
void fl_copy_offscreen (int x, int y, int w, int h, Fl_Offscreen gWorld, int srcx, int srcy)
void fl_delete_offscreen (Fl_Offscreen gWorld)
void fl_begin_offscreen (Fl_Offscreen gWorld)
void fl_end_offscreen ()
FL_EXPORT int fl_parse_color (const char *p, uchar &r, uchar &g, uchar &b)
void fl_open_display ()
void fl_open_callback (void(*cb)(const char *))
Register a function called for each file dropped onto an application icon.
void fl_mac_set_about (Fl_Callback *cb, void *user_data, int shortcut=0)
Attaches a callback to the "About myprog" item of the system application menu.
Variables
FL_EXPORT Fl_CGContextRef fl_gc
FL_EXPORT class Fl_Sys_Menu_Bar * fl_sys_menu_bar
int fl_mac_os_version
The version number of the running Mac OS X (e.g., 0x1064 for 10.6.4)
Typedef Documentation
typedef void* Fl_Bitmask
Definition at line 40 of file mac.H.
typedef void* Fl_CGContextRef
Definition at line 45 of file mac.H.
typedef void* Fl_Offscreen
Definition at line 39 of file mac.H.
typedef void* Fl_PMPageFormat
Definition at line 47 of file mac.H.
typedef void* Fl_PMPrintSession
Definition at line 48 of file mac.H.
typedef void* Fl_PMPrintSettings
Definition at line 46 of file mac.H.
typedef void* Fl_Region
Definition at line 44 of file mac.H.
typedef void* Window
Definition at line 38 of file mac.H.
Function Documentation
void fl_begin_offscreen (Fl_Offscreen gWorld)
Referenced by Fl_Xlib_Graphics_Driver::draw(), fl_copy_offscreen(), Fl_Double_Window::flush(), and Overlay_Window::read_image().
FL_EXPORT Fl_Bitmask fl_create_alphamask (int w, int h, int d, int ld, const uchar * data)
Definition at line 179 of file Fl_Bitmap.cxx.
FL_EXPORT Fl_Bitmask fl_create_bitmask (int w, int h, const uchar * data)
Definition at line 165 of file Fl_Bitmap.cxx.
Referenced by Fl_Xlib_Graphics_Driver::draw(), and fl_create_alphamask().
Fl_Offscreen fl_create_offscreen (int w, int h)
Referenced by Fl_Xlib_Graphics_Driver::draw(), Fl_Double_Window::flush(), and Overlay_Window::read_image().
FL_EXPORT void fl_delete_bitmask (Fl_Bitmask bm)
Definition at line 170 of file Fl_Bitmap.cxx.
Referenced by Fl_Pixmap::uncache(), Fl_RGB_Image::uncache(), and Fl_Bitmap::uncache().
void fl_delete_offscreen (Fl_Offscreen gWorld)
Referenced by fl_delete_bitmask(), Fl_Double_Window::hide(), Overlay_Window::read_image(), Fl_Double_Window::resize(), Fl_Pixmap::uncache(), and Fl_RGB_Image::uncache().
void fl_end_offscreen ()
Referenced by Fl_Xlib_Graphics_Driver::draw(), fl_copy_offscreen(), Fl_Double_Window::flush(), and Overlay_Window::read_image().
void fl_open_display ()
Definition at line 1493 of file Fl_mac.cxx.
Referenced by fl_beep(), Fl_Font_Descriptor::Fl_Font_Descriptor(), fl_get_font_xfld(), fl_open_display(), fl_parse_color(), Fl::get_key(), Fl::get_mouse(), Fl::get_system_colors(), Fl_X::make(), Fl::own_colormap(), Fl::scheme(), Fl::set_fonts(), and Fl::visual().
FL_EXPORT int fl_parse_color (const char * p, uchar & r, uchar & g, uchar & b)
Definition at line 131 of file Fl_get_system_colors.cxx.
Referenced by Fl_Pixmap::color_average(), Fl_Pixmap::desaturate(), and fl_draw_pixmap().
Window fl_xid (const Fl_Window *) [inline]
Definition at line 97 of file win32.H.
References Fl_X::i(), and Fl_X::xid.
Referenced by Fl_Window::cursor(), FLDropTarget::Drop(), Fl_Menu_Window::erase(), fl_handle(), fl_set_spot(), fl_text_extents(), fl_width(), Fl_Overlay_Window::flush(), Fl_Double_Window::flush(), Fl::grab(), Fl_Window::handle(), Fl_Window::hide(), Fl_Window::label(), Fl_X::make(), Fl_X::make_xid(), and Fl_Window::show().
Variable Documentation
FL_EXPORT Fl_CGContextRef fl_gc
Definition at line 97 of file Fl_mac.cxx.
Referenced by Fl_Graphics_Driver::arc(), Fl_Graphics_Driver::circle(), Fl_Graphics_Driver::clip_box(), Fl_Xlib_Graphics_Driver::color(), Fl_Window::draw(), Fl_Xlib_Graphics_Driver::draw(), Fl_Graphics_Driver::end_complex_polygon(), Fl_Graphics_Driver::end_line(), Fl_Graphics_Driver::end_points(), Fl_Graphics_Driver::end_polygon(), fl_brush_action(), fl_draw_pixmap(), fl_GetDC(), Fl_PostScript_File_Device::Fl_PostScript_File_Device(), fl_read_image(), fl_restore_clip(), fl_restore_pen(), fl_save_pen(), fl_scroll(), fl_text_extents(), fl_width(), Fl_Menu_Window::flush(), Fl_Double_Window::flush(), Fl::flush(), Fl_Window::hide(), Fl_Graphics_Driver::line(), Fl_Graphics_Driver::line_style(), Fl_Graphics_Driver::loop(), Fl_Window::make_current(), Fl_Graphics_Driver::not_clipped(), Fl_Graphics_Driver::pie(), Fl_Graphics_Driver::point(), Fl_Graphics_Driver::polygon(), Fl_Paged_Device::print_window_part(), Fl_Graphics_Driver::rect(), Fl_Graphics_Driver::rectf(), Fl_Xlib_Graphics_Driver::rtl_draw(), Fl_Graphics_Driver::xyline(), and Fl_Graphics_Driver::yxline().
FL_EXPORT class Fl_Sys_Menu_Bar* fl_sys_menu_bar
Definition at line 99 of file Fl_mac.cxx.