SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/png.c File Reference
png.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
#define PNG_NO_EXTERN
Typedefs
typedef version_1_2_40 Your_png_h_is_not_version_1_2_40
Functions
void PNGAPI png_set_sig_bytes (png_structp png_ptr, int num_bytes)
int PNGAPI png_sig_cmp (png_bytep sig, png_size_t start, png_size_t num_to_check)
int PNGAPI png_check_sig (png_bytep sig, int num)
voidpf png_zalloc (voidpf png_ptr, uInt items, uInt size)
void png_zfree (voidpf png_ptr, voidpf ptr)
void png_reset_crc (png_structp png_ptr)
void png_calculate_crc (png_structp png_ptr, png_bytep ptr, png_size_t length)
png_infop PNGAPI png_create_info_struct (png_structp png_ptr)
void PNGAPI png_destroy_info_struct (png_structp png_ptr, png_infopp info_ptr_ptr)
void PNGAPI png_info_init (png_infop info_ptr)
void PNGAPI png_info_init_3 (png_infopp ptr_ptr, png_size_t png_info_struct_size)
void PNGAPI png_data_freer (png_structp png_ptr, png_infop info_ptr, int freer, png_uint_32 mask)
void PNGAPI png_free_data (png_structp png_ptr, png_infop info_ptr, png_uint_32 mask, int num)
void png_info_destroy (png_structp png_ptr, png_infop info_ptr)
png_voidp PNGAPI png_get_io_ptr (png_structp png_ptr)
void PNGAPI png_init_io (png_structp png_ptr, png_FILE_p fp)
png_charp PNGAPI png_convert_to_rfc1123 (png_structp png_ptr, png_timep ptime)
png_charp PNGAPI png_get_copyright (png_structp png_ptr)
png_charp PNGAPI png_get_libpng_ver (png_structp png_ptr)
png_charp PNGAPI png_get_header_ver (png_structp png_ptr)
png_charp PNGAPI png_get_header_version (png_structp png_ptr)
int PNGAPI png_handle_as_unknown (png_structp png_ptr, png_bytep chunk_name)
int PNGAPI png_reset_zstream (png_structp png_ptr)
png_uint_32 PNGAPI png_access_version_number (void)
int PNGAPI png_mmx_support (void)
void png_64bit_product (long v1, long v2, unsigned long *hi_product, unsigned long *lo_product)
int png_check_cHRM_fixed (png_structp png_ptr, png_fixed_point white_x, png_fixed_point white_y, png_fixed_point red_x, png_fixed_point red_y, png_fixed_point green_x, png_fixed_point green_y, png_fixed_point blue_x, png_fixed_point blue_y)
Variables
PNG_CONST char png_libpng_ver [18] = PNG_LIBPNG_VER_STRING
PNG_CONST png_byte FARDATA png_sig [8] = {137, 80, 78, 71, 13, 10, 26, 10}
PNG_IHDR
PNG_IDAT
PNG_IEND
PNG_PLTE
PNG_bKGD
PNG_cHRM
PNG_gAMA
PNG_hIST
PNG_iCCP
PNG_iTXt
PNG_oFFs
PNG_pCAL
PNG_sCAL
PNG_pHYs
PNG_sBIT
PNG_sPLT
PNG_sRGB
PNG_tEXt
PNG_tIME
PNG_tRNS
PNG_zTXt
PNG_CONST int FARDATA png_pass_start [] = {0, 4, 0, 2, 0, 1, 0}
PNG_CONST int FARDATA png_pass_inc [] = {8, 8, 4, 4, 2, 2, 1}
PNG_CONST int FARDATA png_pass_ystart [] = {0, 0, 4, 0, 2, 0, 1}
PNG_CONST int FARDATA png_pass_yinc [] = {8, 8, 8, 4, 4, 2, 2}
PNG_CONST int FARDATA png_pass_mask [] = {0x80, 0x08, 0x88, 0x22, 0xaa, 0x55, 0xff}
PNG_CONST int FARDATA png_pass_dsp_mask [] = {0xff, 0x0f, 0xff, 0x33, 0xff, 0x55, 0xff}
Define Documentation
#define PNG_INTERNAL
Definition at line 14 of file png.c.
#define PNG_NO_EXTERN
Definition at line 15 of file png.c.
Typedef Documentation
typedef version_1_2_40 Your_png_h_is_not_version_1_2_40
Definition at line 19 of file png.c.
Function Documentation
void png_64bit_product (long v1, long v2, unsigned long * hi_product, unsigned long * lo_product)
Definition at line 832 of file png.c.
References b, x, and y.
Referenced by png_check_cHRM_fixed().
png_uint_32 PNGAPI png_access_version_number (void)
Definition at line 780 of file png.c.
References PNG_LIBPNG_VER.
void png_calculate_crc (png_structp png_ptr, png_bytep ptr, png_size_t length)
Definition at line 217 of file png.c.
References crc32().
Referenced by png_crc_read(), png_push_crc_finish(), png_push_read_IDAT(), png_read_chunk_header(), png_write_chunk_data(), and png_write_chunk_start().
int png_check_cHRM_fixed (png_structp png_ptr, png_fixed_point white_x, png_fixed_point white_y, png_fixed_point red_x, png_fixed_point red_y, png_fixed_point green_x, png_fixed_point green_y, png_fixed_point blue_x, png_fixed_point blue_y)
Definition at line 857 of file png.c.
References NULL, png_64bit_product(), png_debug, PNG_UINT_31_MAX, and png_warning().
Referenced by png_set_cHRM_fixed(), png_set_sRGB_gAMA_and_cHRM(), png_write_cHRM(), and png_write_cHRM_fixed().
int PNGAPI png_check_sig (png_bytep sig, int num)
Definition at line 139 of file png.c.
References png_sig_cmp().
png_charp PNGAPI png_convert_to_rfc1123 (png_structp png_ptr, png_timep ptime)
Definition at line 656 of file png.c.
References NULL, PNG_CONST, png_malloc(), png_memcpy, png_sizeof, and png_snprintf6.
png_infop PNGAPI png_create_info_struct (png_structp png_ptr)
Definition at line 244 of file png.c.
References info_ptr, NULL, png_create_struct(), png_create_struct_2(), png_debug, png_info_init_3(), and png_sizeof.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), and save_template_cb().
void PNGAPI png_data_freer (png_structp png_ptr, png_infop info_ptr, int freer, png_uint_32 mask)
Definition at line 330 of file png.c.
References mask, NULL, png_debug, PNG_DESTROY_WILL_FREE_DATA, PNG_USER_WILL_FREE_DATA, and png_warning().
void PNGAPI png_destroy_info_struct (png_structp png_ptr, png_infopp info_ptr_ptr)
Definition at line 269 of file png.c.
References info_ptr, info_ptr_ptr, NULL, png_debug, png_destroy_struct(), png_destroy_struct_2(), and png_info_destroy().
void PNGAPI png_free_data (png_structp png_ptr, png_infop info_ptr, png_uint_32 mask, int num)
Definition at line 347 of file png.c.
References i, int, NULL, num, png_debug, png_free(), PNG_FREE_HIST, PNG_FREE_ICCP, PNG_FREE_MUL, PNG_FREE_PCAL, PNG_FREE_PLTE, PNG_FREE_ROWS, PNG_FREE_SCAL, PNG_FREE_SPLT, PNG_FREE_TEXT, PNG_FREE_TRNS, PNG_FREE_UNKN, PNG_INFO_hIST, PNG_INFO_iCCP, PNG_INFO_IDAT, PNG_INFO_pCAL, PNG_INFO_PLTE, PNG_INFO_sCAL, PNG_INFO_sPLT, PNG_INFO_tRNS, png_zfree(), and row.
Referenced by png_destroy_read_struct(), png_destroy_write_struct(), png_info_destroy(), png_read_png(), png_set_hIST(), png_set_iCCP(), png_set_PLTE(), png_set_rows(), and png_set_tRNS().
png_charp PNGAPI png_get_copyright (png_structp png_ptr)
Definition at line 705 of file png.c.
png_charp PNGAPI png_get_header_ver (png_structp png_ptr)
Definition at line 731 of file png.c.
References PNG_LIBPNG_VER_STRING.
png_charp PNGAPI png_get_header_version (png_structp png_ptr)
Definition at line 739 of file png.c.
References PNG_HEADER_VERSION_STRING, and PNG_READ_SUPPORTED.
png_voidp PNGAPI png_get_io_ptr (png_structp png_ptr)
Definition at line 626 of file png.c.
References NULL.
png_charp PNGAPI png_get_libpng_ver (png_structp png_ptr)
Definition at line 723 of file png.c.
References PNG_LIBPNG_VER_STRING.
int PNGAPI png_handle_as_unknown (png_structp png_ptr, png_bytep chunk_name)
Definition at line 753 of file png.c.
References i, NULL, and png_memcmp.
Referenced by png_handle_unknown(), png_push_handle_unknown(), png_push_read_chunk(), png_read_end(), png_read_info(), png_write_end(), png_write_info(), and png_write_info_before_PLTE().
void png_info_destroy (png_structp png_ptr, png_infop info_ptr)
Definition at line 602 of file png.c.
References NULL, png_debug, png_free(), PNG_FREE_ALL, png_free_data(), png_info_init_3(), and png_sizeof.
Referenced by png_destroy_info_struct(), and png_read_destroy().
void PNGAPI png_info_init (png_infop info_ptr)
Definition at line 300 of file png.c.
References png_info_init_3().
void PNGAPI png_info_init_3 (png_infopp ptr_ptr, png_size_t png_info_struct_size)
Definition at line 308 of file png.c.
References info_ptr, NULL, png_create_struct(), png_debug, png_destroy_struct(), png_memset, and png_sizeof.
Referenced by png_create_info_struct(), png_info_destroy(), and png_info_init().
void PNGAPI png_init_io (png_structp png_ptr, png_FILE_p fp)
Definition at line 642 of file png.c.
References NULL, and png_debug.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), and save_template_cb().
int PNGAPI png_mmx_support (void)
Definition at line 791 of file png.c.
void png_reset_crc (png_structp png_ptr)
Definition at line 206 of file png.c.
References crc32(), and Z_NULL.
Referenced by png_push_read_chunk(), png_push_read_IDAT(), png_read_chunk_header(), png_read_finish_row(), and png_write_chunk_start().
int PNGAPI png_reset_zstream (png_structp png_ptr)
Definition at line 770 of file png.c.
References inflateReset(), NULL, and Z_STREAM_ERROR.
void PNGAPI png_set_sig_bytes (png_structp png_ptr, int num_bytes)
Definition at line 96 of file png.c.
References NULL, png_debug, and png_error().
int PNGAPI png_sig_cmp (png_bytep sig, png_size_t start, png_size_t num_to_check)
Definition at line 116 of file png.c.
References png_memcmp, and start.
Referenced by png_check_sig(), png_push_read_sig(), and png_read_info().
voidpf png_zalloc (voidpf png_ptr, uInt items, uInt size)
Definition at line 153 of file png.c.
References NULL, num_bytes, png_malloc(), png_memset, PNG_UINT_32_MAX, png_warning(), and ptr.
Referenced by png_create_read_struct_2(), png_read_init_3(), and png_write_IHDR().
void png_zfree (voidpf png_ptr, voidpf ptr)
Definition at line 197 of file png.c.
References png_free().
Referenced by png_create_read_struct_2(), png_free_data(), png_read_destroy(), png_read_init_3(), and png_write_IHDR().
Variable Documentation
PNG_bKGD
Definition at line 40 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_bKGD().
PNG_cHRM
Definition at line 41 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), png_write_cHRM(), and png_write_cHRM_fixed().
PNG_gAMA
Definition at line 42 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), png_write_gAMA(), and png_write_gAMA_fixed().
PNG_hIST
Definition at line 43 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_hIST().
PNG_iCCP
Definition at line 44 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_iCCP().
PNG_IDAT
Definition at line 37 of file png.c.
Referenced by png_handle_unknown(), png_push_read_chunk(), png_push_read_IDAT(), png_read_end(), png_read_finish_row(), png_read_info(), png_read_row(), and png_write_IDAT().
PNG_IEND
Definition at line 38 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_IEND().
PNG_IHDR
Definition at line 36 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_IHDR().
PNG_iTXt
Definition at line 45 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
PNG_CONST char png_libpng_ver[18] = PNG_LIBPNG_VER_STRING
Definition at line 26 of file png.c.
Referenced by png_create_read_struct_2(), png_create_write_struct_2(), png_read_init_2(), png_read_init_3(), png_write_init_2(), and png_write_init_3().
PNG_oFFs
Definition at line 46 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_oFFs().
PNG_CONST int FARDATA png_pass_dsp_mask[] = {0xff, 0x0f, 0xff, 0x33, 0xff, 0x55, 0xff}
Definition at line 83 of file png.c.
Referenced by png_progressive_combine_row(), and png_read_row().
PNG_CONST int FARDATA png_pass_inc[] = {8, 8, 4, 4, 2, 2, 1}
Definition at line 65 of file png.c.
Referenced by png_do_read_interlace(), png_do_write_interlace(), png_read_finish_row(), png_read_push_finish_row(), png_read_start_row(), png_write_finish_row(), and png_write_start_row().
PNG_CONST int FARDATA png_pass_mask[] = {0x80, 0x08, 0x88, 0x22, 0xaa, 0x55, 0xff}
Definition at line 79 of file png.c.
Referenced by png_read_row().
PNG_CONST int FARDATA png_pass_start[] = {0, 4, 0, 2, 0, 1, 0}
Definition at line 62 of file png.c.
Referenced by png_do_write_interlace(), png_read_finish_row(), png_read_push_finish_row(), png_read_start_row(), png_write_finish_row(), and png_write_start_row().
PNG_CONST int FARDATA png_pass_yinc[] = {8, 8, 8, 4, 4, 2, 2}
Definition at line 71 of file png.c.
Referenced by png_read_finish_row(), png_read_push_finish_row(), png_read_start_row(), png_write_finish_row(), and png_write_start_row().
PNG_CONST int FARDATA png_pass_ystart[] = {0, 0, 4, 0, 2, 0, 1}
Definition at line 68 of file png.c.
Referenced by png_read_finish_row(), png_read_push_finish_row(), png_read_start_row(), png_write_finish_row(), and png_write_start_row().
PNG_pCAL
Definition at line 47 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_pCAL().
PNG_pHYs
Definition at line 49 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_pHYs().
PNG_PLTE
Definition at line 39 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_PLTE().
PNG_sBIT
Definition at line 50 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_sBIT().
PNG_sCAL
Definition at line 48 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_sCAL().
PNG_CONST png_byte FARDATA png_sig[8] = {137, 80, 78, 71, 13, 10, 26, 10}
Definition at line 32 of file png.c.
PNG_sPLT
Definition at line 51 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_sPLT().
PNG_sRGB
Definition at line 52 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_sRGB().
PNG_tEXt
Definition at line 53 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_tEXt().
PNG_tIME
Definition at line 54 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_tIME().
PNG_tRNS
Definition at line 55 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_tRNS().
PNG_zTXt
Definition at line 56 of file png.c.
Referenced by png_push_read_chunk(), png_read_end(), png_read_info(), and png_write_zTXt().