SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngget.c File Reference
pngget.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
Functions
png_uint_32 PNGAPI png_get_valid (png_structp png_ptr, png_infop info_ptr, png_uint_32 flag)
png_uint_32 PNGAPI png_get_rowbytes (png_structp png_ptr, png_infop info_ptr)
png_bytepp PNGAPI png_get_rows (png_structp png_ptr, png_infop info_ptr)
png_uint_32 PNGAPI png_get_image_width (png_structp png_ptr, png_infop info_ptr)
png_uint_32 PNGAPI png_get_image_height (png_structp png_ptr, png_infop info_ptr)
png_byte PNGAPI png_get_bit_depth (png_structp png_ptr, png_infop info_ptr)
png_byte PNGAPI png_get_color_type (png_structp png_ptr, png_infop info_ptr)
png_byte PNGAPI png_get_filter_type (png_structp png_ptr, png_infop info_ptr)
png_byte PNGAPI png_get_interlace_type (png_structp png_ptr, png_infop info_ptr)
png_byte PNGAPI png_get_compression_type (png_structp png_ptr, png_infop info_ptr)
png_uint_32 PNGAPI png_get_x_pixels_per_meter (png_structp png_ptr, png_infop info_ptr)
png_uint_32 PNGAPI png_get_y_pixels_per_meter (png_structp png_ptr, png_infop info_ptr)
png_uint_32 PNGAPI png_get_pixels_per_meter (png_structp png_ptr, png_infop info_ptr)
float PNGAPI png_get_pixel_aspect_ratio (png_structp png_ptr, png_infop info_ptr)
png_int_32 PNGAPI png_get_x_offset_microns (png_structp png_ptr, png_infop info_ptr)
png_int_32 PNGAPI png_get_y_offset_microns (png_structp png_ptr, png_infop info_ptr)
png_int_32 PNGAPI png_get_x_offset_pixels (png_structp png_ptr, png_infop info_ptr)
png_int_32 PNGAPI png_get_y_offset_pixels (png_structp png_ptr, png_infop info_ptr)
png_byte PNGAPI png_get_channels (png_structp png_ptr, png_infop info_ptr)
png_bytep PNGAPI png_get_signature (png_structp png_ptr, png_infop info_ptr)
png_uint_32 PNGAPI png_get_bKGD (png_structp png_ptr, png_infop info_ptr, png_color_16p *background)
png_uint_32 PNGAPI png_get_cHRM (png_structp png_ptr, png_infop info_ptr, double *white_x, double *white_y, double *red_x, double *red_y, double *green_x, double *green_y, double *blue_x, double *blue_y)
png_uint_32 PNGAPI png_get_cHRM_fixed (png_structp png_ptr, png_infop info_ptr, png_fixed_point *white_x, png_fixed_point *white_y, png_fixed_point *red_x, png_fixed_point *red_y, png_fixed_point *green_x, png_fixed_point *green_y, png_fixed_point *blue_x, png_fixed_point *blue_y)
png_uint_32 PNGAPI png_get_gAMA (png_structp png_ptr, png_infop info_ptr, double *file_gamma)
png_uint_32 PNGAPI png_get_gAMA_fixed (png_structp png_ptr, png_infop info_ptr, png_fixed_point *int_file_gamma)
png_uint_32 PNGAPI png_get_sRGB (png_structp png_ptr, png_infop info_ptr, int *file_srgb_intent)
png_uint_32 PNGAPI png_get_iCCP (png_structp png_ptr, png_infop info_ptr, png_charpp name, int *compression_type, png_charpp profile, png_uint_32 *proflen)
png_uint_32 PNGAPI png_get_sPLT (png_structp png_ptr, png_infop info_ptr, png_sPLT_tpp spalettes)
png_uint_32 PNGAPI png_get_hIST (png_structp png_ptr, png_infop info_ptr, png_uint_16p *hist)
png_uint_32 PNGAPI png_get_IHDR (png_structp png_ptr, png_infop info_ptr, png_uint_32 *width, png_uint_32 *height, int *bit_depth, int *color_type, int *interlace_type, int *compression_type, int *filter_type)
png_uint_32 PNGAPI png_get_oFFs (png_structp png_ptr, png_infop info_ptr, png_int_32 *offset_x, png_int_32 *offset_y, int *unit_type)
png_uint_32 PNGAPI png_get_pCAL (png_structp png_ptr, png_infop info_ptr, png_charp *purpose, png_int_32 *X0, png_int_32 *X1, int *type, int *nparams, png_charp *units, png_charpp *params)
png_uint_32 PNGAPI png_get_sCAL (png_structp png_ptr, png_infop info_ptr, int *unit, double *width, double *height)
png_uint_32 PNGAPI png_get_pHYs (png_structp png_ptr, png_infop info_ptr, png_uint_32 *res_x, png_uint_32 *res_y, int *unit_type)
png_uint_32 PNGAPI png_get_PLTE (png_structp png_ptr, png_infop info_ptr, png_colorp *palette, int *num_palette)
png_uint_32 PNGAPI png_get_sBIT (png_structp png_ptr, png_infop info_ptr, png_color_8p *sig_bit)
png_uint_32 PNGAPI png_get_text (png_structp png_ptr, png_infop info_ptr, png_textp *text_ptr, int *num_text)
png_uint_32 PNGAPI png_get_tIME (png_structp png_ptr, png_infop info_ptr, png_timep *mod_time)
png_uint_32 PNGAPI png_get_tRNS (png_structp png_ptr, png_infop info_ptr, png_bytep *trans, int *num_trans, png_color_16p *trans_values)
png_uint_32 PNGAPI png_get_unknown_chunks (png_structp png_ptr, png_infop info_ptr, png_unknown_chunkpp unknowns)
png_byte PNGAPI png_get_rgb_to_gray_status (png_structp png_ptr)
png_voidp PNGAPI png_get_user_chunk_ptr (png_structp png_ptr)
png_uint_32 PNGAPI png_get_compression_buffer_size (png_structp png_ptr)
png_uint_32 PNGAPI png_get_asm_flags (png_structp png_ptr)
png_uint_32 PNGAPI png_get_asm_flagmask (int flag_select)
png_uint_32 PNGAPI png_get_mmx_flagmask (int flag_select, int *compilerID)
png_byte PNGAPI png_get_mmx_bitdepth_threshold (png_structp png_ptr)
png_uint_32 PNGAPI png_get_mmx_rowbytes_threshold (png_structp png_ptr)
png_uint_32 PNGAPI png_get_user_width_max (png_structp png_ptr)
png_uint_32 PNGAPI png_get_user_height_max (png_structp png_ptr)
Define Documentation
#define PNG_INTERNAL
Definition at line 15 of file pngget.c.
Function Documentation
png_uint_32 PNGAPI png_get_asm_flagmask (int flag_select)
Definition at line 892 of file pngget.c.
png_uint_32 PNGAPI png_get_asm_flags (png_structp png_ptr)
Definition at line 884 of file pngget.c.
png_byte PNGAPI png_get_bit_depth (png_structp png_ptr, png_infop info_ptr)
Definition at line 72 of file pngget.c.
References NULL.
Referenced by Fl_PNG_Image::Fl_PNG_Image().
png_uint_32 PNGAPI png_get_bKGD (png_structp png_ptr, png_infop info_ptr, png_color_16p * background)
Definition at line 387 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_bKGD.
png_byte PNGAPI png_get_channels (png_structp png_ptr, png_infop info_ptr)
Definition at line 368 of file pngget.c.
References NULL.
png_uint_32 PNGAPI png_get_cHRM (png_structp png_ptr, png_infop info_ptr, double * white_x, double * white_y, double * red_x, double * red_y, double * green_x, double * green_y, double * blue_x, double * blue_y)
Definition at line 404 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_cHRM.
png_uint_32 PNGAPI png_get_cHRM_fixed (png_structp png_ptr, png_infop info_ptr, png_fixed_point * white_x, png_fixed_point * white_y, png_fixed_point * red_x, png_fixed_point * red_y, png_fixed_point * green_x, png_fixed_point * green_y, png_fixed_point * blue_x, png_fixed_point * blue_y)
Definition at line 434 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_cHRM.
png_byte PNGAPI png_get_color_type (png_structp png_ptr, png_infop info_ptr)
Definition at line 81 of file pngget.c.
References NULL.
Referenced by Fl_PNG_Image::Fl_PNG_Image().
png_uint_32 PNGAPI png_get_compression_buffer_size (png_structp png_ptr)
Definition at line 874 of file pngget.c.
png_byte PNGAPI png_get_compression_type (png_structp png_ptr, png_infop info_ptr)
Definition at line 108 of file pngget.c.
References NULL.
png_byte PNGAPI png_get_filter_type (png_structp png_ptr, png_infop info_ptr)
Definition at line 90 of file pngget.c.
References NULL.
png_uint_32 PNGAPI png_get_gAMA (png_structp png_ptr, png_infop info_ptr, double * file_gamma)
Definition at line 468 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_gAMA.
png_uint_32 PNGAPI png_get_gAMA_fixed (png_structp png_ptr, png_infop info_ptr, png_fixed_point * int_file_gamma)
Definition at line 482 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_gAMA.
png_uint_32 PNGAPI png_get_hIST (png_structp png_ptr, png_infop info_ptr, png_uint_16p * hist)
Definition at line 551 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_hIST.
png_uint_32 PNGAPI png_get_iCCP (png_structp png_ptr, png_infop info_ptr, png_charpp name, int * compression_type, png_charpp profile, png_uint_32 * proflen)
Definition at line 514 of file pngget.c.
References int, NULL, png_debug1, and PNG_INFO_iCCP.
png_uint_32 PNGAPI png_get_IHDR (png_structp png_ptr, png_infop info_ptr, png_uint_32 * width, png_uint_32 * height, int * bit_depth, int * color_type, int * interlace_type, int * compression_type, int * filter_type)
Definition at line 565 of file pngget.c.
References NULL, png_debug1, png_error(), PNG_UINT_31_MAX, PNG_UINT_32_MAX, and png_warning().
png_uint_32 PNGAPI png_get_image_height (png_structp png_ptr, png_infop info_ptr)
Definition at line 63 of file pngget.c.
References NULL.
Referenced by Fl_PNG_Image::Fl_PNG_Image().
png_uint_32 PNGAPI png_get_image_width (png_structp png_ptr, png_infop info_ptr)
Definition at line 54 of file pngget.c.
References NULL.
Referenced by Fl_PNG_Image::Fl_PNG_Image().
png_byte PNGAPI png_get_interlace_type (png_structp png_ptr, png_infop info_ptr)
Definition at line 99 of file pngget.c.
References NULL.
png_byte PNGAPI png_get_mmx_bitdepth_threshold (png_structp png_ptr)
Definition at line 912 of file pngget.c.
png_uint_32 PNGAPI png_get_mmx_flagmask (int flag_select, int * compilerID)
Definition at line 902 of file pngget.c.
png_uint_32 PNGAPI png_get_mmx_rowbytes_threshold (png_structp png_ptr)
Definition at line 920 of file pngget.c.
png_uint_32 PNGAPI png_get_oFFs (png_structp png_ptr, png_infop info_ptr, png_int_32 * offset_x, png_int_32 * offset_y, int * unit_type)
Definition at line 620 of file pngget.c.
References int, NULL, png_debug1, and PNG_INFO_oFFs.
png_uint_32 PNGAPI png_get_pCAL (png_structp png_ptr, png_infop info_ptr, png_charp * purpose, png_int_32 * X0, png_int_32 * X1, int * type, int * nparams, png_charp * units, png_charpp * params)
Definition at line 638 of file pngget.c.
References int, NULL, png_debug1, and PNG_INFO_pCAL.
png_uint_32 PNGAPI png_get_pHYs (png_structp png_ptr, png_infop info_ptr, png_uint_32 * res_x, png_uint_32 * res_y, int * unit_type)
Definition at line 698 of file pngget.c.
References int, NULL, png_debug1, and PNG_INFO_pHYs.
float PNGAPI png_get_pixel_aspect_ratio (png_structp png_ptr, png_infop info_ptr)
Definition at line 182 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_pHYs.
png_uint_32 PNGAPI png_get_pixels_per_meter (png_structp png_ptr, png_infop info_ptr)
Definition at line 159 of file pngget.c.
References NULL, png_debug1, PNG_INFO_pHYs, and PNG_RESOLUTION_METER.
png_uint_32 PNGAPI png_get_PLTE (png_structp png_ptr, png_infop info_ptr, png_colorp * palette, int * num_palette)
Definition at line 731 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_PLTE.
png_byte PNGAPI png_get_rgb_to_gray_status (png_structp png_ptr)
Definition at line 858 of file pngget.c.
png_uint_32 PNGAPI png_get_rowbytes (png_structp png_ptr, png_infop info_ptr)
Definition at line 30 of file pngget.c.
References NULL.
Referenced by png_read_png().
png_bytepp PNGAPI png_get_rows (png_structp png_ptr, png_infop info_ptr)
Definition at line 41 of file pngget.c.
References NULL.
png_uint_32 PNGAPI png_get_sBIT (png_structp png_ptr, png_infop info_ptr, png_color_8p * sig_bit)
Definition at line 748 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_sBIT.
Referenced by png_read_png().
png_uint_32 PNGAPI png_get_sCAL (png_structp png_ptr, png_infop info_ptr, int * unit, double * width, double * height)
Definition at line 663 of file pngget.c.
References NULL, and PNG_INFO_sCAL.
png_bytep PNGAPI png_get_signature (png_structp png_ptr, png_infop info_ptr)
Definition at line 377 of file pngget.c.
References NULL.
png_uint_32 PNGAPI png_get_sPLT (png_structp png_ptr, png_infop info_ptr, png_sPLT_tpp spalettes)
Definition at line 537 of file pngget.c.
References NULL.
png_uint_32 PNGAPI png_get_sRGB (png_structp png_ptr, png_infop info_ptr, int * file_srgb_intent)
Definition at line 499 of file pngget.c.
References int, NULL, png_debug1, and PNG_INFO_sRGB.
png_uint_32 PNGAPI png_get_text (png_structp png_ptr, png_infop info_ptr, png_textp * text_ptr, int * num_text)
Definition at line 763 of file pngget.c.
References NULL, and png_debug1.
png_uint_32 PNGAPI png_get_tIME (png_structp png_ptr, png_infop info_ptr, png_timep * mod_time)
Definition at line 788 of file pngget.c.
References NULL, png_debug1, and PNG_INFO_tIME.
png_uint_32 PNGAPI png_get_tRNS (png_structp png_ptr, png_infop info_ptr, png_bytep * trans, int * num_trans, png_color_16p * trans_values)
Definition at line 803 of file pngget.c.
References NULL, PNG_COLOR_TYPE_PALETTE, png_debug1, and PNG_INFO_tRNS.
Referenced by Fl_PNG_Image::Fl_PNG_Image().
png_uint_32 PNGAPI png_get_unknown_chunks (png_structp png_ptr, png_infop info_ptr, png_unknown_chunkpp unknowns)
Definition at line 844 of file pngget.c.
References NULL.
png_voidp PNGAPI png_get_user_chunk_ptr (png_structp png_ptr)
Definition at line 866 of file pngget.c.
References NULL.
png_uint_32 PNGAPI png_get_user_height_max (png_structp png_ptr)
Definition at line 936 of file pngget.c.
png_uint_32 PNGAPI png_get_user_width_max (png_structp png_ptr)
Definition at line 931 of file pngget.c.
png_uint_32 PNGAPI png_get_valid (png_structp png_ptr, png_infop info_ptr, png_uint_32 flag)
Definition at line 20 of file pngget.c.
References NULL.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), and png_read_png().
png_int_32 PNGAPI png_get_x_offset_microns (png_structp png_ptr, png_infop info_ptr)
Definition at line 204 of file pngget.c.
References NULL, png_debug1, PNG_INFO_oFFs, and PNG_OFFSET_MICROMETER.
png_int_32 PNGAPI png_get_x_offset_pixels (png_structp png_ptr, png_infop info_ptr)
Definition at line 248 of file pngget.c.
References NULL, png_debug1, PNG_INFO_oFFs, and PNG_OFFSET_PIXEL.
png_uint_32 PNGAPI png_get_x_pixels_per_meter (png_structp png_ptr, png_infop info_ptr)
Definition at line 117 of file pngget.c.
References NULL, png_debug1, PNG_INFO_pHYs, and PNG_RESOLUTION_METER.
png_int_32 PNGAPI png_get_y_offset_microns (png_structp png_ptr, png_infop info_ptr)
Definition at line 226 of file pngget.c.
References NULL, png_debug1, PNG_INFO_oFFs, and PNG_OFFSET_MICROMETER.
png_int_32 PNGAPI png_get_y_offset_pixels (png_structp png_ptr, png_infop info_ptr)
Definition at line 270 of file pngget.c.
References NULL, png_debug1, PNG_INFO_oFFs, and PNG_OFFSET_PIXEL.
png_uint_32 PNGAPI png_get_y_pixels_per_meter (png_structp png_ptr, png_infop info_ptr)
Definition at line 138 of file pngget.c.
References NULL, png_debug1, PNG_INFO_pHYs, and PNG_RESOLUTION_METER.