SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngmem.c File Reference
pngmem.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
Functions
png_voidp png_create_struct (int type)
png_voidp png_create_struct_2 (int type, png_malloc_ptr malloc_fn, png_voidp mem_ptr)
void png_destroy_struct (png_voidp struct_ptr)
void png_destroy_struct_2 (png_voidp struct_ptr, png_free_ptr free_fn, png_voidp mem_ptr)
png_voidp PNGAPI png_malloc (png_structp png_ptr, png_uint_32 size)
png_voidp PNGAPI png_malloc_default (png_structp png_ptr, png_uint_32 size)
void PNGAPI png_free (png_structp png_ptr, png_voidp ptr)
void PNGAPI png_free_default (png_structp png_ptr, png_voidp ptr)
png_voidp PNGAPI png_malloc_warn (png_structp png_ptr, png_uint_32 size)
png_voidp PNGAPI png_memcpy_check (png_structp png_ptr, png_voidp s1, png_voidp s2, png_uint_32 length)
png_voidp PNGAPI png_memset_check (png_structp png_ptr, png_voidp s1, int value, png_uint_32 length)
void PNGAPI png_set_mem_fn (png_structp png_ptr, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn)
png_voidp PNGAPI png_get_mem_ptr (png_structp png_ptr)
Define Documentation
#define PNG_INTERNAL
Definition at line 20 of file pngmem.c.
Function Documentation
png_voidp png_create_struct (int type)
Definition at line 337 of file pngmem.c.
References png_create_struct_2(), png_malloc_ptr_NULL, and png_voidp_NULL.
Referenced by png_create_info_struct(), png_create_read_struct_2(), png_create_write_struct_2(), png_info_init_3(), png_read_init_3(), and png_write_init_3().
png_voidp png_create_struct_2 (int type, png_malloc_ptr malloc_fn, png_voidp mem_ptr)
Definition at line 347 of file pngmem.c.
References malloc_fn, mem_ptr, png_struct_def::mem_ptr, NULL, png_memset, png_sizeof, and size.
Referenced by png_create_info_struct(), png_create_read_struct_2(), png_create_struct(), and png_create_write_struct_2().
void png_destroy_struct (png_voidp struct_ptr)
Definition at line 391 of file pngmem.c.
References png_destroy_struct_2(), png_free_ptr_NULL, and png_voidp_NULL.
Referenced by png_create_read_struct_2(), png_create_write_struct_2(), png_destroy_info_struct(), png_destroy_read_struct(), png_destroy_write_struct(), png_info_init_3(), png_read_init_3(), and png_write_init_3().
void png_destroy_struct_2 (png_voidp struct_ptr, png_free_ptr free_fn, png_voidp mem_ptr)
Definition at line 399 of file pngmem.c.
References free_fn, mem_ptr, png_struct_def::mem_ptr, and NULL.
Referenced by png_create_read_struct_2(), png_destroy_info_struct(), png_destroy_read_struct(), png_destroy_struct(), and png_destroy_write_struct().
void PNGAPI png_free (png_structp png_ptr, png_voidp ptr)
Definition at line 506 of file pngmem.c.
References NULL, png_free_default(), and ptr.
Referenced by png_check_keyword(), png_create_read_struct_2(), png_create_write_struct_2(), png_decompress_chunk(), png_destroy_write_struct(), png_free_data(), png_handle_iCCP(), png_handle_pCAL(), png_handle_sCAL(), png_handle_sPLT(), png_handle_tEXt(), png_handle_unknown(), png_handle_zTXt(), png_info_destroy(), png_push_handle_unknown(), png_push_read_tEXt(), png_push_read_zTXt(), png_push_save_buffer(), png_read_destroy(), png_read_start_row(), png_set_compression_buffer_size(), png_set_dither(), png_set_iCCP(), png_set_keep_unknown_chunks(), png_set_sPLT(), png_set_text_2(), png_set_unknown_chunks(), png_write_destroy(), png_write_iCCP(), png_write_pCAL(), png_write_sPLT(), png_write_tEXt(), png_write_zTXt(), and png_zfree().
void PNGAPI png_free_default (png_structp png_ptr, png_voidp ptr)
Definition at line 521 of file pngmem.c.
References NULL.
Referenced by png_free().
png_voidp PNGAPI png_get_mem_ptr (png_structp png_ptr)
Definition at line 613 of file pngmem.c.
References NULL.
png_voidp PNGAPI png_malloc (png_structp png_ptr, png_uint_32 size)
Definition at line 436 of file pngmem.c.
References NULL, png_error(), png_malloc_default(), and size.
Referenced by png_build_gamma_table(), png_convert_to_rfc1123(), png_create_read_struct_2(), png_create_write_struct_2(), png_handle_iCCP(), png_handle_sPLT(), png_handle_unknown(), png_malloc_warn(), png_push_handle_tEXt(), png_push_handle_unknown(), png_push_handle_zTXt(), png_push_read_tEXt(), png_push_read_zTXt(), png_push_save_buffer(), png_read_init_3(), png_read_png(), png_read_start_row(), png_set_compression_buffer_size(), png_set_dither(), png_set_filter(), png_set_filter_heuristics(), png_set_keep_unknown_chunks(), png_set_PLTE(), png_set_tRNS(), png_write_init_3(), png_write_pCAL(), png_write_start_row(), and png_zalloc().
png_voidp PNGAPI png_malloc_default (png_structp png_ptr, png_uint_32 size)
Definition at line 454 of file pngmem.c.
References NULL, and png_error().
Referenced by png_malloc().
png_voidp PNGAPI png_malloc_warn (png_structp png_ptr, png_uint_32 size)
Definition at line 550 of file pngmem.c.
References NULL, png_malloc(), ptr, and size.
Referenced by png_check_keyword(), png_decompress_chunk(), png_handle_pCAL(), png_handle_sCAL(), png_handle_sPLT(), png_handle_tEXt(), png_handle_zTXt(), png_set_dither(), png_set_hIST(), png_set_iCCP(), png_set_pCAL(), png_set_sPLT(), png_set_text_2(), and png_set_unknown_chunks().
png_voidp PNGAPI png_memcpy_check (png_structp png_ptr, png_voidp s1, png_voidp s2, png_uint_32 length)
Definition at line 566 of file pngmem.c.
References length, png_error(), png_memcpy, and size.
Referenced by png_push_process_row(), and png_write_row().
png_voidp PNGAPI png_memset_check (png_structp png_ptr, png_voidp s1, int value, png_uint_32 length)
Definition at line 579 of file pngmem.c.
References length, png_error(), png_memset, and size.
Referenced by png_read_finish_row(), png_read_push_finish_row(), and png_read_start_row().
void PNGAPI png_set_mem_fn (png_structp png_ptr, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn)
Definition at line 597 of file pngmem.c.
References free_fn, malloc_fn, mem_ptr, and NULL.
Referenced by png_create_read_struct_2(), and png_create_write_struct_2().