SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngpread.c File Reference
pngpread.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
#define PNG_READ_SIG_MODE 0
#define PNG_READ_CHUNK_MODE 1
#define PNG_READ_IDAT_MODE 2
#define PNG_SKIP_MODE 3
#define PNG_READ_tEXt_MODE 4
#define PNG_READ_zTXt_MODE 5
#define PNG_READ_DONE_MODE 6
#define PNG_READ_iTXt_MODE 7
#define PNG_ERROR_MODE 8
Functions
void PNGAPI png_process_data (png_structp png_ptr, png_infop info_ptr, png_bytep buffer, png_size_t buffer_size)
void png_process_some_data (png_structp png_ptr, png_infop info_ptr)
void png_push_read_sig (png_structp png_ptr, png_infop info_ptr)
void png_push_read_chunk (png_structp png_ptr, png_infop info_ptr)
void png_push_crc_skip (png_structp png_ptr, png_uint_32 skip)
void png_push_crc_finish (png_structp png_ptr)
void PNGAPI png_push_fill_buffer (png_structp png_ptr, png_bytep buffer, png_size_t length)
void png_push_save_buffer (png_structp png_ptr)
void png_push_restore_buffer (png_structp png_ptr, png_bytep buffer, png_size_t buffer_length)
void png_push_read_IDAT (png_structp png_ptr)
void png_process_IDAT_data (png_structp png_ptr, png_bytep buffer, png_size_t buffer_length)
void png_push_process_row (png_structp png_ptr)
void png_read_push_finish_row (png_structp png_ptr)
void png_push_handle_tEXt (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_push_read_tEXt (png_structp png_ptr, png_infop info_ptr)
void png_push_handle_zTXt (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_push_read_zTXt (png_structp png_ptr, png_infop info_ptr)
void png_push_handle_unknown (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_push_have_info (png_structp png_ptr, png_infop info_ptr)
void png_push_have_end (png_structp png_ptr, png_infop info_ptr)
void png_push_have_row (png_structp png_ptr, png_bytep row)
void PNGAPI png_progressive_combine_row (png_structp png_ptr, png_bytep old_row, png_bytep new_row)
void PNGAPI png_set_progressive_read_fn (png_structp png_ptr, png_voidp progressive_ptr, png_progressive_info_ptr info_fn, png_progressive_row_ptr row_fn, png_progressive_end_ptr end_fn)
png_voidp PNGAPI png_get_progressive_ptr (png_structp png_ptr)
Define Documentation
#define PNG_ERROR_MODE 8
Definition at line 27 of file pngpread.c.
#define PNG_INTERNAL
Definition at line 14 of file pngpread.c.
#define PNG_READ_CHUNK_MODE 1
Definition at line 20 of file pngpread.c.
Referenced by png_process_some_data(), png_push_crc_finish(), png_push_read_IDAT(), and png_push_read_sig().
#define PNG_READ_DONE_MODE 6
Definition at line 25 of file pngpread.c.
Referenced by png_push_read_chunk().
#define PNG_READ_IDAT_MODE 2
Definition at line 21 of file pngpread.c.
Referenced by png_process_some_data(), and png_push_read_chunk().
#define PNG_READ_iTXt_MODE 7
Definition at line 26 of file pngpread.c.
Referenced by png_process_some_data().
#define PNG_READ_SIG_MODE 0
Definition at line 19 of file pngpread.c.
Referenced by png_process_some_data().
#define PNG_READ_tEXt_MODE 4
Definition at line 23 of file pngpread.c.
Referenced by png_process_some_data(), and png_push_handle_tEXt().
#define PNG_READ_zTXt_MODE 5
Definition at line 24 of file pngpread.c.
Referenced by png_process_some_data(), and png_push_handle_zTXt().
#define PNG_SKIP_MODE 3
Definition at line 22 of file pngpread.c.
Referenced by png_process_some_data(), and png_push_crc_skip().
Function Documentation
png_voidp PNGAPI png_get_progressive_ptr (png_structp png_ptr)
Definition at line 1720 of file pngpread.c.
References NULL.
void PNGAPI png_process_data (png_structp png_ptr, png_infop info_ptr, png_bytep buffer, png_size_t buffer_size)
Definition at line 30 of file pngpread.c.
References NULL, png_process_some_data(), and png_push_restore_buffer().
void png_process_IDAT_data (png_structp png_ptr, png_bytep buffer, png_size_t buffer_length)
Definition at line 824 of file pngpread.c.
References inflate(), PNG_AFTER_IDAT, png_error(), png_push_process_row(), PNG_READ_INTERLACING_SUPPORTED, png_warning(), Z_BUF_ERROR, Z_OK, Z_PARTIAL_FLUSH, and Z_STREAM_END.
Referenced by png_push_read_IDAT().
void png_process_some_data (png_structp png_ptr, png_infop info_ptr)
Definition at line 48 of file pngpread.c.
References NULL, png_push_crc_finish(), png_push_read_chunk(), png_push_read_IDAT(), png_push_read_sig(), png_push_read_tEXt(), png_push_read_zTXt(), PNG_READ_CHUNK_MODE, PNG_READ_IDAT_MODE, PNG_READ_iTXt_MODE, PNG_READ_SIG_MODE, PNG_READ_tEXt_MODE, PNG_READ_zTXt_MODE, and PNG_SKIP_MODE.
Referenced by png_process_data().
void PNGAPI png_progressive_combine_row (png_structp png_ptr, png_bytep old_row, png_bytep new_row)
Definition at line 1690 of file pngpread.c.
References FARDATA, NULL, png_combine_row(), PNG_CONST, and png_pass_dsp_mask.
void png_push_crc_finish (png_structp png_ptr)
Definition at line 579 of file pngpread.c.
References png_calculate_crc(), png_crc_finish(), png_push_save_buffer(), and PNG_READ_CHUNK_MODE.
Referenced by png_process_some_data(), png_push_read_tEXt(), and png_push_read_zTXt().
void png_push_crc_skip (png_structp png_ptr, png_uint_32 skip)
Definition at line 572 of file pngpread.c.
References PNG_SKIP_MODE.
Referenced by png_push_handle_unknown(), and png_push_handle_zTXt().
void PNGAPI png_push_fill_buffer (png_structp png_ptr, png_bytep buffer, png_size_t length)
Definition at line 627 of file pngpread.c.
References png_struct_def::current_buffer_size, length, NULL, png_memcpy, ptr, and png_struct_def::save_buffer_size.
Referenced by png_push_read_chunk(), png_push_read_IDAT(), png_push_read_sig(), and png_set_progressive_read_fn().
void png_push_handle_tEXt (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1160 of file pngpread.c.
References info_ptr, length, png_error(), PNG_HAVE_IEND, PNG_HAVE_IHDR, png_malloc(), PNG_READ_tEXt_MODE, and png_warning().
Referenced by png_push_read_chunk().
void png_push_handle_unknown (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1583 of file pngpread.c.
References info_ptr, length, NULL, png_chunk_error(), png_crc_read(), png_free(), png_handle_as_unknown(), PNG_HANDLE_CHUNK_ALWAYS, png_malloc(), png_memcpy, png_push_crc_skip(), PNG_READ_USER_CHUNKS_SUPPORTED, png_set_unknown_chunks(), png_sizeof, and png_warning().
Referenced by png_push_read_chunk().
void png_push_handle_zTXt (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1258 of file pngpread.c.
References info_ptr, length, png_error(), PNG_HAVE_IEND, PNG_HAVE_IHDR, png_malloc(), png_push_crc_skip(), PNG_READ_zTXt_MODE, and png_warning().
Referenced by png_push_read_chunk().
void png_push_have_end (png_structp png_ptr, png_infop info_ptr)
Definition at line 1675 of file pngpread.c.
References info_ptr, and NULL.
Referenced by png_push_read_chunk().
void png_push_have_info (png_structp png_ptr, png_infop info_ptr)
Definition at line 1668 of file pngpread.c.
References info_ptr, and NULL.
Referenced by png_push_read_chunk().
void png_push_have_row (png_structp png_ptr, png_bytep row)
Definition at line 1682 of file pngpread.c.
References int, NULL, and row.
Referenced by png_push_process_row().
void png_push_process_row (png_structp png_ptr)
Definition at line 884 of file pngpread.c.
References i, png_bytep_NULL, png_do_read_interlace(), png_do_read_transformations(), png_memcpy_check(), png_push_have_row(), png_read_filter_row(), and png_read_push_finish_row().
Referenced by png_process_IDAT_data().
void png_push_read_chunk (png_structp png_ptr, png_infop info_ptr)
Definition at line 150 of file pngpread.c.
References PNG_AFTER_IDAT, PNG_bKGD, png_check_chunk_name(), PNG_cHRM, PNG_COLOR_TYPE_PALETTE, PNG_CONST, png_crc_read(), png_error(), PNG_gAMA, png_get_uint_31(), png_handle_as_unknown(), png_handle_bKGD(), png_handle_cHRM(), png_handle_gAMA(), png_handle_hIST(), png_handle_iCCP(), png_handle_IEND(), png_handle_IHDR(), png_handle_oFFs(), png_handle_pCAL(), png_handle_pHYs(), png_handle_PLTE(), png_handle_sBIT(), png_handle_sCAL(), png_handle_sPLT(), png_handle_sRGB(), png_handle_tIME(), png_handle_tRNS(), png_handle_unknown(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_hIST, PNG_iCCP, PNG_IDAT, PNG_IEND, PNG_IHDR, PNG_iTXt, png_memcmp, PNG_oFFs, PNG_pCAL, PNG_pHYs, PNG_PLTE, png_push_fill_buffer(), png_push_handle_tEXt(), png_push_handle_unknown(), png_push_handle_zTXt(), png_push_have_end(), png_push_have_info(), png_push_save_buffer(), PNG_READ_DONE_MODE, PNG_READ_IDAT_MODE, png_reset_crc(), PNG_sBIT, PNG_sCAL, PNG_sPLT, PNG_sRGB, PNG_tEXt, PNG_tIME, PNG_tRNS, and PNG_zTXt.
Referenced by png_process_some_data().
void png_push_read_IDAT (png_structp png_ptr)
Definition at line 729 of file pngpread.c.
References PNG_AFTER_IDAT, png_calculate_crc(), PNG_CONST, png_crc_finish(), png_crc_read(), png_error(), png_get_uint_31(), PNG_IDAT, png_memcmp, png_process_IDAT_data(), png_push_fill_buffer(), png_push_save_buffer(), PNG_READ_CHUNK_MODE, and png_reset_crc().
Referenced by png_process_some_data().
void png_push_read_sig (png_structp png_ptr, png_infop info_ptr)
Definition at line 118 of file pngpread.c.
References num_to_check, png_error(), png_push_fill_buffer(), PNG_READ_CHUNK_MODE, and png_sig_cmp().
Referenced by png_process_some_data().
void png_push_read_tEXt (png_structp png_ptr, png_infop info_ptr)
Definition at line 1190 of file pngpread.c.
References png_struct_def::current_text_size, key, NULL, png_crc_read(), png_free(), png_malloc(), png_push_crc_finish(), png_push_save_buffer(), png_set_text_2(), png_sizeof, PNG_TEXT_COMPRESSION_NONE, png_warning(), and text_ptr.
Referenced by png_process_some_data().
void png_push_read_zTXt (png_structp png_ptr, png_infop info_ptr)
Definition at line 1290 of file pngpread.c.
References inflate(), inflateReset(), key, NULL, png_crc_read(), png_free(), png_malloc(), png_memcpy, png_push_crc_finish(), png_push_save_buffer(), png_set_text_2(), png_sizeof, PNG_TEXT_COMPRESSION_zTXt, png_warning(), text_ptr, Z_OK, Z_PARTIAL_FLUSH, and Z_STREAM_END.
Referenced by png_process_some_data().
void png_push_restore_buffer (png_structp png_ptr, png_bytep buffer, png_size_t buffer_length)
Definition at line 719 of file pngpread.c.
Referenced by png_process_data().
void png_push_save_buffer (png_structp png_ptr)
Definition at line 669 of file pngpread.c.
References i, png_error(), png_free(), png_malloc(), png_memcpy, and PNG_SIZE_MAX.
Referenced by png_push_crc_finish(), png_push_read_chunk(), png_push_read_IDAT(), png_push_read_tEXt(), and png_push_read_zTXt().
void png_read_push_finish_row (png_structp png_ptr)
Definition at line 1090 of file pngpread.c.
References FARDATA, PNG_CONST, png_memset_check(), png_pass_inc, png_pass_start, png_pass_yinc, and png_pass_ystart.
Referenced by png_push_process_row().
void PNGAPI png_set_progressive_read_fn (png_structp png_ptr, png_voidp progressive_ptr, png_progressive_info_ptr info_fn, png_progressive_row_ptr row_fn, png_progressive_end_ptr end_fn)
Definition at line 1705 of file pngpread.c.
References end_fn, info_fn, NULL, png_push_fill_buffer(), png_set_read_fn(), and row_fn.