SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngread.c File Reference
pngread.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
Functions
png_structp PNGAPI png_create_read_struct (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn)
png_structp PNGAPI png_create_read_struct_2 (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn)
void PNGAPI png_read_init (png_structp png_ptr)
void PNGAPI png_read_init_2 (png_structp png_ptr, png_const_charp user_png_ver, png_size_t png_struct_size, png_size_t png_info_size)
void PNGAPI png_read_init_3 (png_structpp ptr_ptr, png_const_charp user_png_ver, png_size_t png_struct_size)
void PNGAPI png_read_info (png_structp png_ptr, png_infop info_ptr)
void PNGAPI png_read_update_info (png_structp png_ptr, png_infop info_ptr)
void PNGAPI png_start_read_image (png_structp png_ptr)
void PNGAPI png_read_row (png_structp png_ptr, png_bytep row, png_bytep dsp_row)
void PNGAPI png_read_rows (png_structp png_ptr, png_bytepp row, png_bytepp display_row, png_uint_32 num_rows)
void PNGAPI png_read_image (png_structp png_ptr, png_bytepp image)
void PNGAPI png_read_end (png_structp png_ptr, png_infop info_ptr)
void PNGAPI png_destroy_read_struct (png_structpp png_ptr_ptr, png_infopp info_ptr_ptr, png_infopp end_info_ptr_ptr)
void png_read_destroy (png_structp png_ptr, png_infop info_ptr, png_infop end_info_ptr)
void PNGAPI png_set_read_status_fn (png_structp png_ptr, png_read_status_ptr read_row_fn)
void PNGAPI png_read_png (png_structp png_ptr, png_infop info_ptr, int transforms, voidp params)
Define Documentation
#define PNG_INTERNAL
Definition at line 17 of file pngread.c.
Function Documentation
png_structp PNGAPI png_create_read_struct (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn)
Definition at line 23 of file pngread.c.
References png_create_read_struct_2(), png_free_ptr_NULL, png_malloc_ptr_NULL, and png_voidp_NULL.
Referenced by Fl_PNG_Image::Fl_PNG_Image().
png_structp PNGAPI png_create_read_struct_2 (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn)
Definition at line 34 of file pngread.c.
References i, inflateInit, png_struct_def::jmpbuf, malloc_fn, NULL, PNG_ABORT, png_create_struct(), png_create_struct_2(), png_debug, png_destroy_struct(), png_destroy_struct_2(), png_error(), png_free(), png_libpng_ver, png_malloc(), png_memcpy, png_rw_ptr_NULL, png_set_error_fn(), png_set_mem_fn(), png_set_read_fn(), png_sizeof, png_snprintf, PNG_USER_HEIGHT_MAX, PNG_USER_WIDTH_MAX, png_voidp_NULL, png_warning(), png_zalloc(), PNG_ZBUF_SIZE, png_zfree(), Z_MEM_ERROR, Z_OK, Z_STREAM_ERROR, and Z_VERSION_ERROR.
Referenced by png_create_read_struct().
void PNGAPI png_destroy_read_struct (png_structpp png_ptr_ptr, png_infopp info_ptr_ptr, png_infopp end_info_ptr_ptr)
Definition at line 1092 of file pngread.c.
References end_info_ptr_ptr, free_fn, info_ptr, info_ptr_ptr, mem_ptr, NULL, png_debug, png_destroy_struct(), png_destroy_struct_2(), png_free_data(), PNG_FREE_TEXT, and png_read_destroy().
Referenced by Fl_PNG_Image::Fl_PNG_Image().
void png_read_destroy (png_structp png_ptr, png_infop info_ptr, png_infop end_info_ptr)
Definition at line 1164 of file pngread.c.
References error_fn, error_ptr, free_fn, i, inflateEnd(), NULL, png_debug, png_free(), PNG_FREE_HIST, PNG_FREE_PLTE, PNG_FREE_TRNS, png_info_destroy(), png_memcpy, png_memset, png_sizeof, png_zfree(), and warning_fn.
Referenced by png_destroy_read_struct().
void PNGAPI png_read_end (png_structp png_ptr, png_infop info_ptr)
Definition at line 919 of file pngread.c.
References chunk_name, length, NULL, PNG_bKGD, PNG_cHRM, PNG_CONST, png_crc_finish(), png_debug, png_error(), PNG_gAMA, png_handle_as_unknown(), png_handle_bKGD(), png_handle_cHRM(), png_handle_gAMA(), png_handle_hIST(), png_handle_iCCP(), png_handle_IEND(), png_handle_IHDR(), png_handle_oFFs(), png_handle_pCAL(), png_handle_pHYs(), png_handle_PLTE(), png_handle_sBIT(), png_handle_sCAL(), png_handle_sPLT(), png_handle_sRGB(), png_handle_tEXt(), png_handle_tIME(), png_handle_tRNS(), png_handle_unknown(), png_handle_zTXt(), PNG_HAVE_IEND, PNG_HAVE_PLTE, PNG_hIST, PNG_iCCP, PNG_IDAT, PNG_IEND, PNG_IHDR, PNG_iTXt, png_memcmp, PNG_oFFs, PNG_pCAL, PNG_pHYs, PNG_PLTE, png_read_chunk_header(), PNG_sBIT, PNG_sCAL, PNG_sPLT, PNG_sRGB, PNG_tEXt, PNG_tIME, PNG_tRNS, and PNG_zTXt.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), and png_read_png().
void PNGAPI png_read_image (png_structp png_ptr, png_bytepp image)
Definition at line 878 of file pngread.c.
References i, image, NULL, png_struct_def::pass, png_bytep_NULL, png_debug, png_error(), png_read_row(), and png_set_interlace_handling().
Referenced by png_read_png().
void PNGAPI png_read_info (png_structp png_ptr, png_infop info_ptr)
Definition at line 332 of file pngread.c.
References chunk_name, length, NULL, num_to_check, PNG_AFTER_IDAT, PNG_bKGD, PNG_cHRM, PNG_COLOR_TYPE_PALETTE, PNG_CONST, png_debug, png_error(), PNG_gAMA, png_handle_as_unknown(), png_handle_bKGD(), png_handle_cHRM(), png_handle_gAMA(), png_handle_hIST(), png_handle_iCCP(), png_handle_IEND(), png_handle_IHDR(), png_handle_oFFs(), png_handle_pCAL(), png_handle_pHYs(), png_handle_PLTE(), png_handle_sBIT(), png_handle_sCAL(), png_handle_sPLT(), png_handle_sRGB(), png_handle_tEXt(), png_handle_tIME(), png_handle_tRNS(), png_handle_unknown(), png_handle_zTXt(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_hIST, PNG_iCCP, PNG_IDAT, PNG_IEND, PNG_IHDR, PNG_iTXt, png_memcmp, PNG_oFFs, PNG_pCAL, PNG_pHYs, PNG_PLTE, png_read_chunk_header(), png_read_data(), PNG_sBIT, PNG_sCAL, png_sig_cmp(), PNG_sPLT, PNG_sRGB, PNG_tEXt, PNG_tIME, PNG_tRNS, and PNG_zTXt.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), and png_read_png().
void PNGAPI png_read_init (png_structp png_ptr)
Definition at line 187 of file pngread.c.
References png_read_init_2().
void PNGAPI png_read_init_2 (png_structp png_ptr, png_const_charp user_png_ver, png_size_t png_struct_size, png_size_t png_info_size)
Definition at line 194 of file pngread.c.
References NULL, png_error(), png_libpng_ver, png_read_init_3(), png_sizeof, png_snprintf, and png_warning().
Referenced by png_read_init().
void PNGAPI png_read_init_3 (png_structpp ptr_ptr, png_const_charp user_png_ver, png_size_t png_struct_size)
Definition at line 242 of file pngread.c.
References i, inflateInit, NULL, png_create_struct(), png_debug, png_destroy_struct(), png_error(), png_libpng_ver, png_malloc(), png_memcpy, png_memset, png_rw_ptr_NULL, png_set_read_fn(), png_sizeof, PNG_USER_HEIGHT_MAX, PNG_USER_WIDTH_MAX, png_voidp_NULL, png_warning(), png_zalloc(), PNG_ZBUF_SIZE, png_zfree(), Z_MEM_ERROR, Z_OK, Z_STREAM_ERROR, and Z_VERSION_ERROR.
Referenced by png_read_init_2().
void PNGAPI png_read_png (png_structp png_ptr, png_infop info_ptr, int transforms, voidp params)
Definition at line 1320 of file pngread.c.
References int, NULL, params, PNG_COLOR_TYPE_PALETTE, png_error(), png_free_data(), PNG_FREE_ROWS, png_get_rowbytes(), png_get_sBIT(), png_get_valid(), PNG_INFO_IDAT, PNG_INFO_sBIT, PNG_INFO_tRNS, png_malloc(), png_memset, png_read_end(), png_read_image(), png_read_info(), png_read_update_info(), png_set_bgr(), png_set_expand(), png_set_invert_alpha(), png_set_invert_mono(), png_set_packing(), png_set_packswap(), png_set_shift(), png_set_strip_16(), png_set_strip_alpha(), png_set_swap(), png_set_swap_alpha(), png_sizeof, PNG_TRANSFORM_BGR, PNG_TRANSFORM_EXPAND, PNG_TRANSFORM_INVERT_ALPHA, PNG_TRANSFORM_INVERT_MONO, PNG_TRANSFORM_PACKING, PNG_TRANSFORM_PACKSWAP, PNG_TRANSFORM_SHIFT, PNG_TRANSFORM_STRIP_16, PNG_TRANSFORM_STRIP_ALPHA, PNG_TRANSFORM_SWAP_ALPHA, PNG_TRANSFORM_SWAP_ENDIAN, PNG_UINT_32_MAX, row, sig_bit, and transforms.
void PNGAPI png_read_row (png_structp png_ptr, png_bytep row, png_bytep dsp_row)
Definition at line 572 of file pngread.c.
References inflate(), NULL, PNG_AFTER_IDAT, png_combine_row(), PNG_CONST, png_crc_finish(), png_crc_read(), png_debug2, png_error(), PNG_HAVE_IDAT, PNG_IDAT, png_memcmp, png_pass_dsp_mask, png_pass_mask, png_read_chunk_header(), png_read_finish_row(), png_read_start_row(), png_warning(), Z_OK, Z_PARTIAL_FLUSH, and Z_STREAM_END.
Referenced by png_read_image(), and png_read_rows().
void PNGAPI png_read_rows (png_structp png_ptr, png_bytepp row, png_bytepp display_row, png_uint_32 num_rows)
Definition at line 827 of file pngread.c.
References display_row, i, NULL, num_rows, png_bytep_NULL, png_debug, png_read_row(), and row.
Referenced by Fl_PNG_Image::Fl_PNG_Image().
void PNGAPI png_read_update_info (png_structp png_ptr, png_infop info_ptr)
Definition at line 540 of file pngread.c.
References NULL, png_debug, png_read_start_row(), png_read_transform_info(), and png_warning().
Referenced by png_read_png().
void PNGAPI png_set_read_status_fn (png_structp png_ptr, png_read_status_ptr read_row_fn)
Definition at line 1309 of file pngread.c.
References NULL, and read_row_fn.
void PNGAPI png_start_read_image (png_structp png_ptr)
Definition at line 560 of file pngread.c.
References NULL, png_debug, and png_read_start_row().