SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngrtran.c File Reference
pngrtran.c File Reference
#include "png.h"
Classes
struct png_dsort_struct
Defines
#define PNG_INTERNAL
Typedefs
typedef struct png_dsort_struct png_dsort
typedef png_dsort FAR * png_dsortp
typedef png_dsort FAR *FAR png_dsortpp
Functions
void PNGAPI png_set_crc_action (png_structp png_ptr, int crit_action, int ancil_action)
void PNGAPI png_set_background (png_structp png_ptr, png_color_16p background_color, int background_gamma_code, int need_expand, double background_gamma)
void PNGAPI png_set_strip_16 (png_structp png_ptr)
void PNGAPI png_set_strip_alpha (png_structp png_ptr)
void PNGAPI png_set_dither (png_structp png_ptr, png_colorp palette, int num_palette, int maximum_colors, png_uint_16p histogram, int full_dither)
void PNGAPI png_set_gamma (png_structp png_ptr, double scrn_gamma, double file_gamma)
void PNGAPI png_set_expand (png_structp png_ptr)
void PNGAPI png_set_palette_to_rgb (png_structp png_ptr)
void PNGAPI png_set_expand_gray_1_2_4_to_8 (png_structp png_ptr)
void PNGAPI png_set_gray_1_2_4_to_8 (png_structp png_ptr)
void PNGAPI png_set_tRNS_to_alpha (png_structp png_ptr)
void PNGAPI png_set_gray_to_rgb (png_structp png_ptr)
void PNGAPI png_set_rgb_to_gray (png_structp png_ptr, int error_action, double red, double green)
void PNGAPI png_set_rgb_to_gray_fixed (png_structp png_ptr, int error_action, png_fixed_point red, png_fixed_point green)
void PNGAPI png_set_read_user_transform_fn (png_structp png_ptr, png_user_transform_ptr read_user_transform_fn)
void png_init_read_transformations (png_structp png_ptr)
void png_read_transform_info (png_structp png_ptr, png_infop info_ptr)
void png_do_read_transformations (png_structp png_ptr)
void png_do_unpack (png_row_infop row_info, png_bytep row)
void png_do_unshift (png_row_infop row_info, png_bytep row, png_color_8p sig_bits)
void png_do_chop (png_row_infop row_info, png_bytep row)
void png_do_read_swap_alpha (png_row_infop row_info, png_bytep row)
void png_do_read_invert_alpha (png_row_infop row_info, png_bytep row)
void png_do_read_filler (png_row_infop row_info, png_bytep row, png_uint_32 filler, png_uint_32 flags)
void png_do_gray_to_rgb (png_row_infop row_info, png_bytep row)
int png_do_rgb_to_gray (png_structp png_ptr, png_row_infop row_info, png_bytep row)
void PNGAPI png_build_grayscale_palette (int bit_depth, png_colorp palette)
void png_do_background (png_row_infop row_info, png_bytep row, png_color_16p trans_values, png_color_16p background, png_color_16p background_1, png_bytep gamma_table, png_bytep gamma_from_1, png_bytep gamma_to_1, png_uint_16pp gamma_16, png_uint_16pp gamma_16_from_1, png_uint_16pp gamma_16_to_1, int gamma_shift)
void png_do_gamma (png_row_infop row_info, png_bytep row, png_bytep gamma_table, png_uint_16pp gamma_16_table, int gamma_shift)
void png_do_expand_palette (png_row_infop row_info, png_bytep row, png_colorp palette, png_bytep trans, int num_trans)
void png_do_expand (png_row_infop row_info, png_bytep row, png_color_16p trans_value)
void png_do_dither (png_row_infop row_info, png_bytep row, png_bytep palette_lookup, png_bytep dither_lookup)
void png_build_gamma_table (png_structp png_ptr)
void png_do_read_intrapixel (png_row_infop row_info, png_bytep row)
Define Documentation
#define PNG_INTERNAL
Definition at line 19 of file pngrtran.c.
Typedef Documentation
typedef struct png_dsort_struct png_dsort
typedef png_dsort FAR* png_dsortp
Definition at line 153 of file pngrtran.c.
typedef png_dsort FAR* FAR png_dsortpp
Definition at line 154 of file pngrtran.c.
Function Documentation
void png_build_gamma_table (png_structp png_ptr)
Definition at line 4094 of file pngrtran.c.
References i, int, num, PNG_COLOR_MASK_COLOR, png_debug, png_malloc(), png_memset, png_sizeof, and sig_bit.
Referenced by png_init_read_transformations().
void PNGAPI png_build_grayscale_palette (int bit_depth, png_colorp palette)
Definition at line 2517 of file pngrtran.c.
References i, NULL, num_palette, and png_debug.
void png_do_background (png_row_infop row_info, png_bytep row, png_color_16p trans_values, png_color_16p background, png_color_16p background_1, png_bytep gamma_table, png_bytep gamma_from_1, png_bytep gamma_to_1, png_uint_16pp gamma_16, png_uint_16pp gamma_16_from_1, png_uint_16pp gamma_16_to_1, int gamma_shift)
Definition at line 2752 of file pngrtran.c.
References b, background, i, NULL, PNG_COLOR_MASK_ALPHA, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_composite, png_composite_16, png_debug, png_memcpy, row, w, and x.
Referenced by png_do_read_transformations().
void png_do_chop (png_row_infop row_info, png_bytep row)
Definition at line 1751 of file pngrtran.c.
References i, int, NULL, png_debug, and row.
Referenced by png_do_read_transformations().
void png_do_dither (png_row_infop row_info, png_bytep row, png_bytep palette_lookup, png_bytep dither_lookup)
Definition at line 3994 of file pngrtran.c.
References b, i, NULL, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_debug, and row.
Referenced by png_do_read_transformations().
void png_do_expand (png_row_infop row_info, png_bytep row, png_color_16p trans_value)
Definition at line 3782 of file pngrtran.c.
References green, i, int, NULL, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_debug, red, and value.
Referenced by png_do_read_transformations().
void png_do_expand_palette (png_row_infop row_info, png_bytep row, png_colorp palette, png_bytep trans, int num_trans)
Definition at line 3636 of file pngrtran.c.
References i, int, NULL, num_trans, PNG_COLOR_TYPE_PALETTE, png_debug, and value.
Referenced by png_do_read_transformations().
void png_do_gamma (png_row_infop row_info, png_bytep row, png_bytep gamma_table, png_uint_16pp gamma_16_table, int gamma_shift)
Definition at line 3448 of file pngrtran.c.
References b, i, int, NULL, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_debug, and row.
Referenced by png_do_read_transformations().
void png_do_gray_to_rgb (png_row_infop row_info, png_bytep row)
Definition at line 2175 of file pngrtran.c.
References i, NULL, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, and png_debug.
Referenced by png_do_read_transformations().
void png_do_read_filler (png_row_infop row_info, png_bytep row, png_uint_32 filler, png_uint_32 flags)
Definition at line 1999 of file pngrtran.c.
References i, NULL, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_RGB, and png_debug.
Referenced by png_do_read_transformations().
void png_do_read_intrapixel (png_row_infop row_info, png_bytep row)
Definition at line 4320 of file pngrtran.c.
References i, NULL, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_debug, red, s1, and s2.
void png_do_read_invert_alpha (png_row_infop row_info, png_bytep row)
Definition at line 1900 of file pngrtran.c.
References i, NULL, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_RGB_ALPHA, and png_debug.
Referenced by png_do_read_transformations().
void png_do_read_swap_alpha (png_row_infop row_info, png_bytep row)
Definition at line 1808 of file pngrtran.c.
References i, NULL, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_RGB_ALPHA, and png_debug.
Referenced by png_do_read_transformations().
void png_do_read_transformations (png_structp png_ptr)
Definition at line 1301 of file pngrtran.c.
References NULL, PNG_COLOR_MASK_ALPHA, PNG_COLOR_TYPE_PALETTE, png_debug, png_do_background(), png_do_bgr(), png_do_chop(), png_do_dither(), png_do_expand(), png_do_expand_palette(), png_do_gamma(), png_do_gray_to_rgb(), png_do_invert(), png_do_packswap(), png_do_read_filler(), png_do_read_invert_alpha(), png_do_read_swap_alpha(), png_do_rgb_to_gray(), png_do_strip_filler(), png_do_swap(), png_do_unpack(), png_do_unshift(), png_error(), PNG_READ_BACKGROUND_SUPPORTED, PNG_READ_GAMMA_SUPPORTED, png_snprintf2, and png_warning().
Referenced by png_push_process_row().
int png_do_rgb_to_gray (png_structp png_ptr, png_row_infop row_info, png_bytep row)
Definition at line 2278 of file pngrtran.c.
References gc, green, i, NULL, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_debug, red, row, and w.
Referenced by png_do_read_transformations().
void png_do_unpack (png_row_infop row_info, png_bytep row)
Definition at line 1550 of file pngrtran.c.
References i, int, NULL, and png_debug.
Referenced by png_do_read_transformations().
void png_do_unshift (png_row_infop row_info, png_bytep row, png_color_8p sig_bits)
Definition at line 1642 of file pngrtran.c.
References i, mask, NULL, PNG_COLOR_MASK_ALPHA, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, png_debug, row, and value.
Referenced by png_do_read_transformations().
void png_init_read_transformations (png_structp png_ptr)
Definition at line 745 of file pngrtran.c.
References png_color_struct::blue, color_type, green, png_color_struct::green, i, int, m, NULL, num_palette, palette, PNG_BACKGROUND_GAMMA_FILE, PNG_BACKGROUND_GAMMA_SCREEN, PNG_BACKGROUND_GAMMA_UNIQUE, png_build_gamma_table(), PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, png_composite, png_debug, red, png_color_struct::red, and w.
Referenced by png_read_start_row().
void png_read_transform_info (png_structp png_ptr, png_infop info_ptr)
Definition at line 1161 of file pngrtran.c.
References PNG_COLOR_MASK_ALPHA, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, and png_debug.
Referenced by png_read_update_info().
void PNGAPI png_set_background (png_structp png_ptr, png_color_16p background_color, int background_gamma_code, int need_expand, double background_gamma)
Definition at line 92 of file pngrtran.c.
References NULL, PNG_BACKGROUND_GAMMA_UNKNOWN, png_debug, png_memcpy, png_sizeof, and png_warning().
void PNGAPI png_set_crc_action (png_structp png_ptr, int crit_action, int ancil_action)
Definition at line 25 of file pngrtran.c.
References NULL, PNG_CRC_DEFAULT, PNG_CRC_ERROR_QUIT, PNG_CRC_NO_CHANGE, PNG_CRC_QUIET_USE, PNG_CRC_WARN_DISCARD, PNG_CRC_WARN_USE, png_debug, and png_warning().
void PNGAPI png_set_dither (png_structp png_ptr, png_colorp palette, int num_palette, int maximum_colors, png_uint_16p histogram, int full_dither)
Definition at line 157 of file pngrtran.c.
References b, i, int, maximum_colors, NULL, num_palette, palette, png_debug, png_free(), png_malloc(), png_malloc_warn(), png_memset, and png_sizeof.
void PNGAPI png_set_expand (png_structp png_ptr)
Definition at line 564 of file pngrtran.c.
References NULL, and png_debug.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), and png_read_png().
void PNGAPI png_set_expand_gray_1_2_4_to_8 (png_structp png_ptr)
Definition at line 604 of file pngrtran.c.
References NULL, and png_debug.
void PNGAPI png_set_gamma (png_structp png_ptr, double scrn_gamma, double file_gamma)
Definition at line 544 of file pngrtran.c.
References NULL, PNG_COLOR_MASK_ALPHA, PNG_COLOR_TYPE_PALETTE, and png_debug.
void PNGAPI png_set_gray_1_2_4_to_8 (png_structp png_ptr)
Definition at line 618 of file pngrtran.c.
References NULL, and png_debug.
void PNGAPI png_set_gray_to_rgb (png_structp png_ptr)
Definition at line 640 of file pngrtran.c.
References png_debug.
void PNGAPI png_set_palette_to_rgb (png_structp png_ptr)
Definition at line 592 of file pngrtran.c.
References NULL, and png_debug.
void PNGAPI png_set_read_user_transform_fn (png_structp png_ptr, png_user_transform_ptr read_user_transform_fn)
Definition at line 723 of file pngrtran.c.
References NULL, png_debug, png_warning(), and read_user_transform_fn.
void PNGAPI png_set_rgb_to_gray (png_structp png_ptr, int error_action, double red, double green)
Definition at line 655 of file pngrtran.c.
References int, NULL, and png_set_rgb_to_gray_fixed().
void PNGAPI png_set_rgb_to_gray_fixed (png_structp png_ptr, int error_action, png_fixed_point red, png_fixed_point green)
Definition at line 667 of file pngrtran.c.
References NULL, PNG_COLOR_TYPE_PALETTE, png_debug, and png_warning().
Referenced by png_set_rgb_to_gray().
void PNGAPI png_set_strip_16 (png_structp png_ptr)
Definition at line 117 of file pngrtran.c.
References NULL, and png_debug.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), and png_read_png().
void PNGAPI png_set_strip_alpha (png_structp png_ptr)
Definition at line 128 of file pngrtran.c.
References NULL, and png_debug.
Referenced by png_read_png().
void PNGAPI png_set_tRNS_to_alpha (png_structp png_ptr)
Definition at line 630 of file pngrtran.c.
References png_debug.
Referenced by Fl_PNG_Image::Fl_PNG_Image().