SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngrutil.c File Reference
pngrutil.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
#define png_strtod(p, a, b) strtod(a,b)
#define isnonalpha(c) ((c) < 65 || (c) > 122 || ((c) > 90 && (c) < 97))
Functions
png_uint_32 PNGAPI png_get_uint_31 (png_structp png_ptr, png_bytep buf)
png_uint_32 PNGAPI png_get_uint_32 (png_bytep buf)
png_int_32 PNGAPI png_get_int_32 (png_bytep buf)
png_uint_16 PNGAPI png_get_uint_16 (png_bytep buf)
png_uint_32 png_read_chunk_header (png_structp png_ptr)
void png_crc_read (png_structp png_ptr, png_bytep buf, png_size_t length)
int png_crc_finish (png_structp png_ptr, png_uint_32 skip)
int png_crc_error (png_structp png_ptr)
void png_decompress_chunk (png_structp png_ptr, int comp_type, png_size_t chunklength, png_size_t prefix_size, png_size_t *newlength)
void png_handle_IHDR (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_PLTE (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_IEND (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_gAMA (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_sBIT (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_cHRM (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_sRGB (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_iCCP (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_sPLT (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_tRNS (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_bKGD (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_hIST (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_pHYs (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_oFFs (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_pCAL (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_sCAL (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_tIME (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_tEXt (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_zTXt (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_handle_unknown (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
void png_check_chunk_name (png_structp png_ptr, png_bytep chunk_name)
void png_combine_row (png_structp png_ptr, png_bytep row, int mask)
void png_do_read_interlace (png_structp png_ptr)
void png_read_filter_row (png_structp png_ptr, png_row_infop row_info, png_bytep row, png_bytep prev_row, int filter)
void png_read_finish_row (png_structp png_ptr)
void png_read_start_row (png_structp png_ptr)
Define Documentation
#define isnonalpha (c) ((c) < 65 || (c) > 122 || ((c) > 90 && (c) < 97))
Definition at line 2339 of file pngrutil.c.
Referenced by png_check_chunk_name().
#define PNG_INTERNAL
Definition at line 17 of file pngrutil.c.
#define png_strtod (p, a, b) strtod(a,b)
Definition at line 47 of file pngrutil.c.
Referenced by png_handle_sCAL().
Function Documentation
void png_check_chunk_name (png_structp png_ptr, png_bytep chunk_name)
Definition at line 2342 of file pngrutil.c.
References isnonalpha, png_chunk_error(), and png_debug.
Referenced by png_push_read_chunk(), and png_read_chunk_header().
void png_combine_row (png_structp png_ptr, png_bytep row, int mask)
Definition at line 2364 of file pngrutil.c.
References i, m, png_debug, png_memcpy, row, and value.
Referenced by png_progressive_combine_row(), and png_read_row().
int png_crc_error (png_structp png_ptr)
Definition at line 188 of file pngrutil.c.
References png_get_uint_32(), and png_read_data().
Referenced by png_crc_finish(), and png_handle_PLTE().
int png_crc_finish (png_structp png_ptr, png_uint_32 skip)
Definition at line 151 of file pngrutil.c.
References i, png_chunk_error(), png_chunk_warning(), png_crc_error(), and png_crc_read().
Referenced by png_handle_bKGD(), png_handle_cHRM(), png_handle_gAMA(), png_handle_hIST(), png_handle_iCCP(), png_handle_IEND(), png_handle_IHDR(), png_handle_oFFs(), png_handle_pCAL(), png_handle_pHYs(), png_handle_PLTE(), png_handle_sBIT(), png_handle_sCAL(), png_handle_sPLT(), png_handle_sRGB(), png_handle_tEXt(), png_handle_tIME(), png_handle_tRNS(), png_handle_unknown(), png_handle_zTXt(), png_push_crc_finish(), png_push_read_IDAT(), png_read_end(), png_read_finish_row(), and png_read_row().
void png_crc_read (png_structp png_ptr, png_bytep buf, png_size_t length)
Definition at line 137 of file pngrutil.c.
References NULL, png_calculate_crc(), and png_read_data().
Referenced by png_crc_finish(), png_handle_bKGD(), png_handle_cHRM(), png_handle_gAMA(), png_handle_hIST(), png_handle_iCCP(), png_handle_IHDR(), png_handle_oFFs(), png_handle_pCAL(), png_handle_pHYs(), png_handle_PLTE(), png_handle_sBIT(), png_handle_sCAL(), png_handle_sPLT(), png_handle_sRGB(), png_handle_tEXt(), png_handle_tIME(), png_handle_tRNS(), png_handle_unknown(), png_handle_zTXt(), png_push_handle_unknown(), png_push_read_chunk(), png_push_read_IDAT(), png_push_read_tEXt(), png_push_read_zTXt(), png_read_finish_row(), and png_read_row().
void png_decompress_chunk (png_structp png_ptr, int comp_type, png_size_t chunklength, png_size_t prefix_size, png_size_t * newlength)
Definition at line 227 of file pngrutil.c.
References inflate(), inflateReset(), NULL, PNG_COMPRESSION_TYPE_BASE, PNG_CONST, png_error(), png_free(), png_malloc_warn(), png_memcpy, png_sizeof, png_snprintf, png_warning(), Z_BUF_ERROR, Z_DATA_ERROR, Z_OK, Z_PARTIAL_FLUSH, and Z_STREAM_END.
Referenced by png_handle_iCCP(), and png_handle_zTXt().
void png_do_read_interlace (png_structp png_ptr)
Definition at line 2570 of file pngrutil.c.
References i, int, NULL, PNG_CONST, png_debug, png_memcpy, png_pass_inc, and row.
Referenced by png_push_process_row().
png_int_32 PNGAPI png_get_int_32 (png_bytep buf)
Definition at line 85 of file pngrutil.c.
References i.
Referenced by png_handle_oFFs(), and png_handle_pCAL().
png_uint_16 PNGAPI png_get_uint_16 (png_bytep buf)
Definition at line 97 of file pngrutil.c.
References i.
Referenced by png_handle_bKGD(), png_handle_hIST(), png_handle_sPLT(), png_handle_tIME(), and png_handle_tRNS().
png_uint_32 PNGAPI png_get_uint_31 (png_structp png_ptr, png_bytep buf)
Definition at line 52 of file pngrutil.c.
References i, png_error(), png_get_uint_32(), and PNG_UINT_31_MAX.
Referenced by png_handle_IHDR(), png_push_read_chunk(), png_push_read_IDAT(), png_read_chunk_header(), and png_read_finish_row().
png_uint_32 PNGAPI png_get_uint_32 (png_bytep buf)
Definition at line 70 of file pngrutil.c.
References i.
Referenced by png_crc_error(), png_get_uint_31(), png_handle_cHRM(), png_handle_gAMA(), and png_handle_pHYs().
void png_handle_bKGD (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1365 of file pngrutil.c.
References buf, NULL, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_uint_16(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_bKGD, png_set_bKGD(), and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_cHRM (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 783 of file pngrutil.c.
References blue_x, blue_y, buf, green_x, green_y, NULL, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_uint_32(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_cHRM, PNG_INFO_sRGB, PNG_READ_sRGB_SUPPORTED, png_set_cHRM(), png_set_cHRM_fixed(), png_warning(), red_x, red_y, white_x, and white_y.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_gAMA (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 636 of file pngrutil.c.
References buf, file_gamma, NULL, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_uint_32(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_gAMA, PNG_INFO_sRGB, PNG_READ_sRGB_SUPPORTED, png_set_gAMA(), png_set_gAMA_fixed(), and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_hIST (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1454 of file pngrutil.c.
References buf, i, NULL, num, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_uint_16(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_hIST, PNG_MAX_PALETTE_LENGTH, png_set_hIST(), and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_iCCP (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1005 of file pngrutil.c.
References compression_type, NULL, png_crc_finish(), png_crc_read(), png_debug, png_decompress_chunk(), png_error(), png_free(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_iCCP, png_malloc(), png_set_iCCP(), png_warning(), and profile.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_IEND (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 614 of file pngrutil.c.
References info_ptr, PNG_AFTER_IDAT, png_crc_finish(), png_debug, png_error(), PNG_HAVE_IDAT, PNG_HAVE_IEND, PNG_HAVE_IHDR, and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_IHDR (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 398 of file pngrutil.c.
References bit_depth, buf, color_type, compression_type, height, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_crc_finish(), png_crc_read(), png_debug, png_debug1, png_error(), png_get_uint_31(), PNG_HAVE_IHDR, png_set_IHDR(), and width.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_oFFs (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1551 of file pngrutil.c.
References buf, NULL, offset_x, offset_y, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_int_32(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_INFO_oFFs, png_set_oFFs(), png_warning(), and unit_type.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_pCAL (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1595 of file pngrutil.c.
References buf, i, int, nparams, NULL, params, png_crc_finish(), png_crc_read(), png_debug, png_debug1, PNG_EQUATION_ARBITRARY, PNG_EQUATION_BASE_E, PNG_EQUATION_HYPERBOLIC, PNG_EQUATION_LAST, PNG_EQUATION_LINEAR, png_error(), png_free(), png_get_int_32(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_INFO_pCAL, png_malloc_warn(), png_set_pCAL(), png_sizeof, png_warning(), type, units, X0, and X1.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_pHYs (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1508 of file pngrutil.c.
References buf, NULL, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_uint_32(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_INFO_pHYs, png_set_pHYs(), png_warning(), res_x, res_y, and unit_type.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_PLTE (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 472 of file pngrutil.c.
References png_color_struct::blue, buf, png_color_struct::green, i, int, NULL, num, palette, png_chunk_error(), png_chunk_warning(), PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, png_crc_error(), png_crc_finish(), png_crc_read(), png_debug, png_error(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_tRNS, PNG_MAX_PALETTE_LENGTH, png_set_PLTE(), png_warning(), and png_color_struct::red.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_sBIT (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 717 of file pngrutil.c.
References buf, NULL, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, png_crc_finish(), png_crc_read(), png_debug, png_error(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_sBIT, png_set_sBIT(), and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_sCAL (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1729 of file pngrutil.c.
References height, NULL, png_crc_finish(), png_crc_read(), png_debug, png_debug1, png_error(), PNG_FLOATING_POINT_SUPPORTED, png_free(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_INFO_sCAL, png_malloc_warn(), png_memcpy, png_set_sCAL(), png_strlen, png_strtod, png_warning(), and width.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_sPLT (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1125 of file pngrutil.c.
References png_sPLT_struct::depth, png_sPLT_struct::entries, i, png_sPLT_struct::name, png_sPLT_struct::nentries, NULL, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_free(), png_get_uint_16(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, png_malloc(), png_malloc_warn(), png_set_sPLT(), PNG_SIZE_MAX, png_sizeof, and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_sRGB (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 907 of file pngrutil.c.
References buf, intent, NULL, png_crc_finish(), png_crc_read(), png_debug, png_error(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_cHRM, PNG_INFO_gAMA, PNG_INFO_sRGB, png_set_sRGB_gAMA_and_cHRM(), PNG_sRGB_INTENT_LAST, and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_tEXt (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1915 of file pngrutil.c.
References key, NULL, PNG_AFTER_IDAT, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_free(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, png_malloc_warn(), png_set_text_2(), png_sizeof, png_strlen, PNG_TEXT_COMPRESSION_NONE, png_warning(), and text_ptr.
Referenced by png_read_end(), and png_read_info().
void png_handle_tIME (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1871 of file pngrutil.c.
References buf, png_time_struct::day, png_time_struct::hour, png_time_struct::minute, mod_time, png_time_struct::month, NULL, PNG_AFTER_IDAT, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_uint_16(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_INFO_tIME, png_set_tIME(), png_warning(), png_time_struct::second, and png_time_struct::year.
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_tRNS (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 1270 of file pngrutil.c.
References buf, NULL, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_uint_16(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, PNG_HAVE_PLTE, PNG_INFO_tRNS, PNG_MAX_PALETTE_LENGTH, png_set_tRNS(), and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_unknown (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 2239 of file pngrutil.c.
References info_ptr, length, NULL, PNG_AFTER_IDAT, png_chunk_error(), PNG_CONST, png_crc_finish(), png_crc_read(), png_debug, png_free(), png_handle_as_unknown(), PNG_HANDLE_CHUNK_ALWAYS, PNG_HAVE_IDAT, PNG_IDAT, png_malloc(), png_memcmp, png_memcpy, PNG_READ_USER_CHUNKS_SUPPORTED, png_set_unknown_chunks(), png_sizeof, and png_warning().
Referenced by png_push_read_chunk(), png_read_end(), and png_read_info().
void png_handle_zTXt (png_structp png_ptr, png_infop info_ptr, png_uint_32 length)
Definition at line 2002 of file pngrutil.c.
References NULL, PNG_AFTER_IDAT, png_crc_finish(), png_crc_read(), png_debug, png_decompress_chunk(), png_error(), png_free(), PNG_HAVE_IDAT, PNG_HAVE_IHDR, png_malloc_warn(), png_set_text_2(), png_sizeof, PNG_TEXT_COMPRESSION_zTXt, png_warning(), and text_ptr.
Referenced by png_read_end(), and png_read_info().
png_uint_32 png_read_chunk_header (png_structp png_ptr)
Definition at line 110 of file pngrutil.c.
References buf, length, png_calculate_crc(), png_check_chunk_name(), png_debug2, png_get_uint_31(), png_memcpy, png_read_data(), and png_reset_crc().
Referenced by png_read_end(), png_read_info(), and png_read_row().
void png_read_filter_row (png_structp png_ptr, png_row_infop row_info, png_bytep row, png_bytep prev_row, int filter)
Definition at line 2792 of file pngrutil.c.
References b, i, int, png_debug, png_debug2, PNG_FILTER_VALUE_AVG, PNG_FILTER_VALUE_NONE, PNG_FILTER_VALUE_PAETH, PNG_FILTER_VALUE_SUB, PNG_FILTER_VALUE_UP, png_warning(), and row.
Referenced by png_push_process_row().
void png_read_finish_row (png_structp png_ptr)
Definition at line 2916 of file pngrutil.c.
References inflate(), inflateReset(), PNG_AFTER_IDAT, PNG_CONST, png_crc_finish(), png_crc_read(), png_debug, png_error(), png_get_uint_31(), PNG_IDAT, png_memcmp, png_memset_check(), png_pass_inc, png_pass_start, png_pass_yinc, png_pass_ystart, png_read_data(), png_reset_crc(), png_warning(), Z_OK, Z_PARTIAL_FLUSH, and Z_STREAM_END.
Referenced by png_read_row().
void png_read_start_row (png_structp png_ptr)
Definition at line 3049 of file pngrutil.c.
References PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, PNG_CONST, png_debug, png_debug1, png_error(), png_free(), png_init_read_transformations(), png_malloc(), png_memset, png_memset_check(), png_pass_inc, png_pass_start, png_pass_yinc, png_pass_ystart, PNG_READ_EXPAND_SUPPORTED, and PNG_SIZE_MAX.
Referenced by png_read_row(), png_read_update_info(), and png_start_read_image().