SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngset.c File Reference
pngset.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
Functions
void PNGAPI png_set_bKGD (png_structp png_ptr, png_infop info_ptr, png_color_16p background)
void PNGAPI png_set_cHRM (png_structp png_ptr, png_infop info_ptr, double white_x, double white_y, double red_x, double red_y, double green_x, double green_y, double blue_x, double blue_y)
void PNGAPI png_set_cHRM_fixed (png_structp png_ptr, png_infop info_ptr, png_fixed_point white_x, png_fixed_point white_y, png_fixed_point red_x, png_fixed_point red_y, png_fixed_point green_x, png_fixed_point green_y, png_fixed_point blue_x, png_fixed_point blue_y)
void PNGAPI png_set_gAMA (png_structp png_ptr, png_infop info_ptr, double file_gamma)
void PNGAPI png_set_gAMA_fixed (png_structp png_ptr, png_infop info_ptr, png_fixed_point int_gamma)
void PNGAPI png_set_hIST (png_structp png_ptr, png_infop info_ptr, png_uint_16p hist)
void PNGAPI png_set_IHDR (png_structp png_ptr, png_infop info_ptr, png_uint_32 width, png_uint_32 height, int bit_depth, int color_type, int interlace_type, int compression_type, int filter_type)
void PNGAPI png_set_oFFs (png_structp png_ptr, png_infop info_ptr, png_int_32 offset_x, png_int_32 offset_y, int unit_type)
void PNGAPI png_set_pCAL (png_structp png_ptr, png_infop info_ptr, png_charp purpose, png_int_32 X0, png_int_32 X1, int type, int nparams, png_charp units, png_charpp params)
void PNGAPI png_set_sCAL (png_structp png_ptr, png_infop info_ptr, int unit, double width, double height)
void PNGAPI png_set_pHYs (png_structp png_ptr, png_infop info_ptr, png_uint_32 res_x, png_uint_32 res_y, int unit_type)
void PNGAPI png_set_PLTE (png_structp png_ptr, png_infop info_ptr, png_colorp palette, int num_palette)
void PNGAPI png_set_sBIT (png_structp png_ptr, png_infop info_ptr, png_color_8p sig_bit)
void PNGAPI png_set_sRGB (png_structp png_ptr, png_infop info_ptr, int intent)
void PNGAPI png_set_sRGB_gAMA_and_cHRM (png_structp png_ptr, png_infop info_ptr, int intent)
void PNGAPI png_set_iCCP (png_structp png_ptr, png_infop info_ptr, png_charp name, int compression_type, png_charp profile, png_uint_32 proflen)
void PNGAPI png_set_text (png_structp png_ptr, png_infop info_ptr, png_textp text_ptr, int num_text)
int png_set_text_2 (png_structp png_ptr, png_infop info_ptr, png_textp text_ptr, int num_text)
void PNGAPI png_set_tIME (png_structp png_ptr, png_infop info_ptr, png_timep mod_time)
void PNGAPI png_set_tRNS (png_structp png_ptr, png_infop info_ptr, png_bytep trans, int num_trans, png_color_16p trans_values)
void PNGAPI png_set_sPLT (png_structp png_ptr, png_infop info_ptr, png_sPLT_tp entries, int nentries)
void PNGAPI png_set_unknown_chunks (png_structp png_ptr, png_infop info_ptr, png_unknown_chunkp unknowns, int num_unknowns)
void PNGAPI png_set_unknown_chunk_location (png_structp png_ptr, png_infop info_ptr, int chunk, int location)
void PNGAPI png_permit_empty_plte (png_structp png_ptr, int empty_plte_permitted)
png_uint_32 PNGAPI png_permit_mng_features (png_structp png_ptr, png_uint_32 mng_features)
void PNGAPI png_set_keep_unknown_chunks (png_structp png_ptr, int keep, png_bytep chunk_list, int num_chunks)
void PNGAPI png_set_read_user_chunk_fn (png_structp png_ptr, png_voidp user_chunk_ptr, png_user_chunk_ptr read_user_chunk_fn)
void PNGAPI png_set_rows (png_structp png_ptr, png_infop info_ptr, png_bytepp row_pointers)
void PNGAPI png_set_compression_buffer_size (png_structp png_ptr, png_uint_32 size)
void PNGAPI png_set_invalid (png_structp png_ptr, png_infop info_ptr, int mask)
void PNGAPI png_set_asm_flags (png_structp png_ptr, png_uint_32 asm_flags)
void PNGAPI png_set_mmx_thresholds (png_structp png_ptr, png_byte mmx_bitdepth_threshold, png_uint_32 mmx_rowbytes_threshold)
void PNGAPI png_set_user_limits (png_structp png_ptr, png_uint_32 user_width_max, png_uint_32 user_height_max)
Define Documentation
#define PNG_INTERNAL
Definition at line 19 of file pngset.c.
Function Documentation
void PNGAPI png_permit_empty_plte (png_structp png_ptr, int empty_plte_permitted)
Definition at line 1108 of file pngset.c.
References NULL, png_debug, and PNG_FLAG_MNG_EMPTY_PLTE.
png_uint_32 PNGAPI png_permit_mng_features (png_structp png_ptr, png_uint_32 mng_features)
Definition at line 1126 of file pngset.c.
References NULL, PNG_ALL_MNG_FEATURES, and png_debug.
void PNGAPI png_set_asm_flags (png_structp png_ptr, png_uint_32 asm_flags)
Definition at line 1244 of file pngset.c.
References asm_flags, and NULL.
void PNGAPI png_set_bKGD (png_structp png_ptr, png_infop info_ptr, png_color_16p background)
Definition at line 25 of file pngset.c.
References NULL, png_debug1, PNG_INFO_bKGD, png_memcpy, and png_sizeof.
Referenced by png_handle_bKGD().
void PNGAPI png_set_cHRM (png_structp png_ptr, png_infop info_ptr, double white_x, double white_y, double red_x, double red_y, double green_x, double green_y, double blue_x, double blue_y)
Definition at line 40 of file pngset.c.
References NULL, png_debug1, and PNG_INFO_cHRM.
Referenced by png_handle_cHRM(), and png_set_sRGB_gAMA_and_cHRM().
void PNGAPI png_set_cHRM_fixed (png_structp png_ptr, png_infop info_ptr, png_fixed_point white_x, png_fixed_point white_y, png_fixed_point red_x, png_fixed_point red_y, png_fixed_point green_x, png_fixed_point green_y, png_fixed_point blue_x, png_fixed_point blue_y)
Definition at line 73 of file pngset.c.
References blue_x, blue_y, green_x, green_y, NULL, png_check_cHRM_fixed(), png_debug1, PNG_INFO_cHRM, red_x, red_y, white_x, and white_y.
Referenced by png_handle_cHRM(), and png_set_sRGB_gAMA_and_cHRM().
void PNGAPI png_set_compression_buffer_size (png_structp png_ptr, png_uint_32 size)
Definition at line 1219 of file pngset.c.
References NULL, png_free(), and png_malloc().
void PNGAPI png_set_gAMA (png_structp png_ptr, png_infop info_ptr, double file_gamma)
Definition at line 115 of file pngset.c.
References file_gamma, int, NULL, png_debug1, PNG_INFO_gAMA, and png_warning().
Referenced by png_handle_gAMA(), and png_set_sRGB_gAMA_and_cHRM().
void PNGAPI png_set_gAMA_fixed (png_structp png_ptr, png_infop info_ptr, png_fixed_point int_gamma)
Definition at line 142 of file pngset.c.
References NULL, png_debug1, PNG_INFO_gAMA, PNG_UINT_31_MAX, and png_warning().
Referenced by png_handle_gAMA(), and png_set_sRGB_gAMA_and_cHRM().
void PNGAPI png_set_hIST (png_structp png_ptr, png_infop info_ptr, png_uint_16p hist)
Definition at line 181 of file pngset.c.
References i, NULL, png_debug1, png_free_data(), PNG_FREE_HIST, PNG_FREE_ME_SUPPORTED, PNG_INFO_hIST, png_malloc_warn(), PNG_MAX_PALETTE_LENGTH, png_sizeof, and png_warning().
Referenced by png_handle_hIST().
void PNGAPI png_set_iCCP (png_structp png_ptr, png_infop info_ptr, png_charp name, int compression_type, png_charp profile, png_uint_32 proflen)
Definition at line 667 of file pngset.c.
References length, NULL, png_debug1, png_free(), png_free_data(), PNG_FREE_ICCP, PNG_INFO_iCCP, png_malloc_warn(), png_memcpy, png_strlen, png_warning(), and proflen.
Referenced by png_handle_iCCP().
void PNGAPI png_set_IHDR (png_structp png_ptr, png_infop info_ptr, png_uint_32 width, png_uint_32 height, int bit_depth, int color_type, int interlace_type, int compression_type, int filter_type)
Definition at line 226 of file pngset.c.
References height, NULL, PNG_COLOR_MASK_ALPHA, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, PNG_COMPRESSION_TYPE_BASE, png_debug1, png_error(), PNG_FILTER_TYPE_BASE, PNG_FLAG_MNG_FILTER_64, PNG_INTERLACE_LAST, PNG_INTRAPIXEL_DIFFERENCING, PNG_UINT_31_MAX, PNG_UINT_32_MAX, PNG_USER_HEIGHT_MAX, PNG_USER_WIDTH_MAX, png_warning(), and width.
Referenced by png_handle_IHDR(), and save_template_cb().
void PNGAPI png_set_invalid (png_structp png_ptr, png_infop info_ptr, int mask)
Definition at line 1233 of file pngset.c.
void PNGAPI png_set_keep_unknown_chunks (png_structp png_ptr, int keep, png_bytep chunk_list, int num_chunks)
Definition at line 1140 of file pngset.c.
References i, keep, NULL, num_chunks, png_free(), PNG_FREE_LIST, PNG_HANDLE_CHUNK_ALWAYS, PNG_HANDLE_CHUNK_IF_SAFE, png_malloc(), and png_memcpy.
void PNGAPI png_set_mmx_thresholds (png_structp png_ptr, png_byte mmx_bitdepth_threshold, png_uint_32 mmx_rowbytes_threshold)
Definition at line 1254 of file pngset.c.
References mmx_bitdepth_threshold, mmx_rowbytes_threshold, and NULL.
void PNGAPI png_set_oFFs (png_structp png_ptr, png_infop info_ptr, png_int_32 offset_x, png_int_32 offset_y, int unit_type)
Definition at line 336 of file pngset.c.
References NULL, offset_x, offset_y, png_debug1, and PNG_INFO_oFFs.
Referenced by png_handle_oFFs().
void PNGAPI png_set_pCAL (png_structp png_ptr, png_infop info_ptr, png_charp purpose, png_int_32 X0, png_int_32 X1, int type, int nparams, png_charp units, png_charpp params)
Definition at line 353 of file pngset.c.
References i, length, nparams, NULL, png_debug, png_debug1, png_debug2, PNG_FREE_PCAL, PNG_INFO_pCAL, png_malloc_warn(), png_memcpy, png_memset, png_sizeof, png_strlen, png_warning(), X0, and X1.
Referenced by png_handle_pCAL().
void PNGAPI png_set_pHYs (png_structp png_ptr, png_infop info_ptr, png_uint_32 res_x, png_uint_32 res_y, int unit_type)
Definition at line 492 of file pngset.c.
References NULL, png_debug1, PNG_INFO_pHYs, res_x, and res_y.
Referenced by png_handle_pHYs().
void PNGAPI png_set_PLTE (png_structp png_ptr, png_infop info_ptr, png_colorp palette, int num_palette)
Definition at line 508 of file pngset.c.
References NULL, PNG_COLOR_TYPE_PALETTE, png_debug1, png_error(), png_free_data(), PNG_FREE_PLTE, PNG_INFO_PLTE, png_malloc(), PNG_MAX_PALETTE_LENGTH, png_memcpy, png_memset, png_sizeof, and png_warning().
Referenced by png_handle_PLTE().
void PNGAPI png_set_read_user_chunk_fn (png_structp png_ptr, png_voidp user_chunk_ptr, png_user_chunk_ptr read_user_chunk_fn)
Definition at line 1187 of file pngset.c.
References NULL, png_debug, read_user_chunk_fn, and user_chunk_ptr.
void PNGAPI png_set_rows (png_structp png_ptr, png_infop info_ptr, png_bytepp row_pointers)
Definition at line 1202 of file pngset.c.
References NULL, png_debug1, png_free_data(), PNG_FREE_ROWS, PNG_INFO_IDAT, and row_pointers.
void PNGAPI png_set_sBIT (png_structp png_ptr, png_infop info_ptr, png_color_8p sig_bit)
Definition at line 560 of file pngset.c.
References NULL, png_debug1, PNG_INFO_sBIT, png_memcpy, and png_sizeof.
Referenced by png_handle_sBIT().
void PNGAPI png_set_sCAL (png_structp png_ptr, png_infop info_ptr, int unit, double width, double height)
Definition at line 427 of file pngset.c.
References height, NULL, png_debug1, PNG_INFO_sCAL, and width.
Referenced by png_handle_sCAL().
void PNGAPI png_set_sPLT (png_structp png_ptr, png_infop info_ptr, png_sPLT_tp entries, int nentries)
Definition at line 962 of file pngset.c.
References i, length, nentries, NULL, png_free(), PNG_FREE_SPLT, PNG_INFO_sPLT, png_malloc_warn(), png_memcpy, png_sizeof, png_strlen, and png_warning().
Referenced by png_handle_sPLT().
void PNGAPI png_set_sRGB (png_structp png_ptr, png_infop info_ptr, int intent)
Definition at line 575 of file pngset.c.
References NULL, png_debug1, and PNG_INFO_sRGB.
Referenced by png_set_sRGB_gAMA_and_cHRM(), and save_template_cb().
void PNGAPI png_set_sRGB_gAMA_and_cHRM (png_structp png_ptr, png_infop info_ptr, int intent)
Definition at line 587 of file pngset.c.
References blue_x, blue_y, file_gamma, green_x, green_y, int_blue_x, int_blue_y, int_file_gamma, int_green_x, int_green_y, int_red_x, int_red_y, int_white_x, int_white_y, NULL, png_check_cHRM_fixed(), png_debug1, png_set_cHRM(), png_set_cHRM_fixed(), png_set_gAMA(), png_set_gAMA_fixed(), png_set_sRGB(), red_x, red_y, white_x, and white_y.
Referenced by png_handle_sRGB().
void PNGAPI png_set_text (png_structp png_ptr, png_infop info_ptr, png_textp text_ptr, int num_text)
Definition at line 715 of file pngset.c.
References png_error(), and png_set_text_2().
int png_set_text_2 (png_structp png_ptr, png_infop info_ptr, png_textp text_ptr, int num_text)
Definition at line 725 of file pngset.c.
References i, key, NULL, num_text, png_debug1, png_debug2, png_free(), PNG_FREE_TEXT, PNG_ITXT_COMPRESSION_NONE, png_malloc_warn(), png_memcpy, png_sizeof, png_strlen, PNG_TEXT_COMPRESSION_NONE, and png_warning().
Referenced by png_handle_tEXt(), png_handle_zTXt(), png_push_read_tEXt(), png_push_read_zTXt(), and png_set_text().
void PNGAPI png_set_tIME (png_structp png_ptr, png_infop info_ptr, png_timep mod_time)
Definition at line 888 of file pngset.c.
References NULL, png_debug1, PNG_INFO_tIME, png_memcpy, and png_sizeof.
Referenced by png_handle_tIME().
void PNGAPI png_set_tRNS (png_structp png_ptr, png_infop info_ptr, png_bytep trans, int num_trans, png_color_16p trans_values)
Definition at line 903 of file pngset.c.
References int, NULL, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_RGB, png_debug1, png_free_data(), PNG_FREE_TRNS, PNG_INFO_tRNS, png_malloc(), PNG_MAX_PALETTE_LENGTH, png_memcpy, png_sizeof, and png_warning().
Referenced by png_handle_tRNS().
void PNGAPI png_set_unknown_chunk_location (png_structp png_ptr, png_infop info_ptr, int chunk, int location)
Definition at line 1095 of file pngset.c.
References chunk, and NULL.
void PNGAPI png_set_unknown_chunks (png_structp png_ptr, png_infop info_ptr, png_unknown_chunkp unknowns, int num_unknowns)
Definition at line 1034 of file pngset.c.
References i, NULL, num_unknowns, png_free(), PNG_FREE_UNKN, png_malloc_warn(), png_memcpy, png_sizeof, and png_warning().
Referenced by png_handle_unknown(), and png_push_handle_unknown().
void PNGAPI png_set_user_limits (png_structp png_ptr, png_uint_32 user_width_max, png_uint_32 user_height_max)
Definition at line 1270 of file pngset.c.
References NULL, user_height_max, and user_width_max.