SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngtrans.c File Reference
pngtrans.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
Functions
void PNGAPI png_set_bgr (png_structp png_ptr)
void PNGAPI png_set_swap (png_structp png_ptr)
void PNGAPI png_set_packing (png_structp png_ptr)
void PNGAPI png_set_packswap (png_structp png_ptr)
void PNGAPI png_set_shift (png_structp png_ptr, png_color_8p true_bits)
int PNGAPI png_set_interlace_handling (png_structp png_ptr)
void PNGAPI png_set_filler (png_structp png_ptr, png_uint_32 filler, int filler_loc)
void PNGAPI png_set_add_alpha (png_structp png_ptr, png_uint_32 filler, int filler_loc)
void PNGAPI png_set_swap_alpha (png_structp png_ptr)
void PNGAPI png_set_invert_alpha (png_structp png_ptr)
void PNGAPI png_set_invert_mono (png_structp png_ptr)
void png_do_invert (png_row_infop row_info, png_bytep row)
void png_do_swap (png_row_infop row_info, png_bytep row)
void png_do_packswap (png_row_infop row_info, png_bytep row)
void png_do_strip_filler (png_row_infop row_info, png_bytep row, png_uint_32 flags)
void png_do_bgr (png_row_infop row_info, png_bytep row)
void PNGAPI png_set_user_transform_info (png_structp png_ptr, png_voidp user_transform_ptr, int user_transform_depth, int user_transform_channels)
png_voidp PNGAPI png_get_user_transform_ptr (png_structp png_ptr)
Define Documentation
#define PNG_INTERNAL
Definition at line 14 of file pngtrans.c.
Function Documentation
void png_do_bgr (png_row_infop row_info, png_bytep row)
Definition at line 565 of file pngtrans.c.
References i, NULL, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, and png_debug.
Referenced by png_do_read_transformations(), and png_do_write_transformations().
void png_do_invert (png_row_infop row_info, png_bytep row)
Definition at line 189 of file pngtrans.c.
References i, NULL, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, png_debug, and row.
Referenced by png_do_read_transformations(), and png_do_write_transformations().
void png_do_packswap (png_row_infop row_info, png_bytep row)
Definition at line 375 of file pngtrans.c.
References NULL, and png_debug.
Referenced by png_do_read_transformations(), and png_do_write_transformations().
void png_do_strip_filler (png_row_infop row_info, png_bytep row, png_uint_32 flags)
Definition at line 407 of file pngtrans.c.
References i, NULL, PNG_COLOR_MASK_ALPHA, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_debug, and row.
Referenced by png_do_read_transformations(), and png_do_write_transformations().
void png_do_swap (png_row_infop row_info, png_bytep row)
Definition at line 244 of file pngtrans.c.
References i, NULL, png_debug, and row.
Referenced by png_do_read_transformations(), and png_do_write_transformations().
png_voidp PNGAPI png_get_user_transform_ptr (png_structp png_ptr)
Definition at line 667 of file pngtrans.c.
References NULL.
void PNGAPI png_set_add_alpha (png_structp png_ptr, png_uint_32 filler, int filler_loc)
Definition at line 141 of file pngtrans.c.
References NULL, png_debug, and png_set_filler().
void PNGAPI png_set_bgr (png_structp png_ptr)
Definition at line 21 of file pngtrans.c.
References NULL, and png_debug.
Referenced by png_read_png(), and png_write_png().
void PNGAPI png_set_filler (png_structp png_ptr, png_uint_32 filler, int filler_loc)
Definition at line 107 of file pngtrans.c.
References NULL, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_RGB, png_debug, and PNG_FILLER_AFTER.
Referenced by png_set_add_alpha(), and png_write_png().
int PNGAPI png_set_interlace_handling (png_structp png_ptr)
Definition at line 87 of file pngtrans.c.
References png_debug.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), png_read_image(), and png_write_image().
void PNGAPI png_set_invert_alpha (png_structp png_ptr)
Definition at line 168 of file pngtrans.c.
References NULL, and png_debug.
Referenced by png_read_png(), and png_write_png().
void PNGAPI png_set_invert_mono (png_structp png_ptr)
Definition at line 179 of file pngtrans.c.
References NULL, and png_debug.
Referenced by png_read_png(), and png_write_png().
void PNGAPI png_set_packing (png_structp png_ptr)
Definition at line 46 of file pngtrans.c.
References NULL, and png_debug.
Referenced by Fl_PNG_Image::Fl_PNG_Image(), png_read_png(), and png_write_png().
void PNGAPI png_set_packswap (png_structp png_ptr)
Definition at line 62 of file pngtrans.c.
References NULL, and png_debug.
Referenced by png_read_png(), and png_write_png().
void PNGAPI png_set_shift (png_structp png_ptr, png_color_8p true_bits)
Definition at line 74 of file pngtrans.c.
References NULL, png_debug, and true_bits.
Referenced by png_read_png(), and png_write_png().
void PNGAPI png_set_swap (png_structp png_ptr)
Definition at line 33 of file pngtrans.c.
References NULL, and png_debug.
Referenced by png_read_png(), and png_write_png().
void PNGAPI png_set_swap_alpha (png_structp png_ptr)
Definition at line 156 of file pngtrans.c.
References NULL, and png_debug.
Referenced by png_read_png(), and png_write_png().
void PNGAPI png_set_user_transform_info (png_structp png_ptr, png_voidp user_transform_ptr, int user_transform_depth, int user_transform_channels)
Definition at line 643 of file pngtrans.c.
References NULL, png_debug, png_warning(), and user_transform_ptr.