SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngwrite.c File Reference
pngwrite.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
Functions
void PNGAPI png_write_info_before_PLTE (png_structp png_ptr, png_infop info_ptr)
void PNGAPI png_write_info (png_structp png_ptr, png_infop info_ptr)
void PNGAPI png_write_end (png_structp png_ptr, png_infop info_ptr)
void PNGAPI png_convert_from_struct_tm (png_timep ptime, struct tm FAR *ttime)
void PNGAPI png_convert_from_time_t (png_timep ptime, time_t ttime)
png_structp PNGAPI png_create_write_struct (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn)
png_structp PNGAPI png_create_write_struct_2 (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn)
void PNGAPI png_write_init (png_structp png_ptr)
void PNGAPI png_write_init_2 (png_structp png_ptr, png_const_charp user_png_ver, png_size_t png_struct_size, png_size_t png_info_size)
void PNGAPI png_write_init_3 (png_structpp ptr_ptr, png_const_charp user_png_ver, png_size_t png_struct_size)
void PNGAPI png_write_rows (png_structp png_ptr, png_bytepp row, png_uint_32 num_rows)
void PNGAPI png_write_image (png_structp png_ptr, png_bytepp image)
void PNGAPI png_write_row (png_structp png_ptr, png_bytep row)
void PNGAPI png_set_flush (png_structp png_ptr, int nrows)
void PNGAPI png_write_flush (png_structp png_ptr)
void PNGAPI png_destroy_write_struct (png_structpp png_ptr_ptr, png_infopp info_ptr_ptr)
void png_write_destroy (png_structp png_ptr)
void PNGAPI png_set_filter (png_structp png_ptr, int method, int filters)
void PNGAPI png_set_filter_heuristics (png_structp png_ptr, int heuristic_method, int num_weights, png_doublep filter_weights, png_doublep filter_costs)
void PNGAPI png_set_compression_level (png_structp png_ptr, int level)
void PNGAPI png_set_compression_mem_level (png_structp png_ptr, int mem_level)
void PNGAPI png_set_compression_strategy (png_structp png_ptr, int strategy)
void PNGAPI png_set_compression_window_bits (png_structp png_ptr, int window_bits)
void PNGAPI png_set_compression_method (png_structp png_ptr, int method)
void PNGAPI png_set_write_status_fn (png_structp png_ptr, png_write_status_ptr write_row_fn)
void PNGAPI png_set_write_user_transform_fn (png_structp png_ptr, png_user_transform_ptr write_user_transform_fn)
void PNGAPI png_write_png (png_structp png_ptr, png_infop info_ptr, int transforms, voidp params)
Define Documentation
#define PNG_INTERNAL
Definition at line 15 of file pngwrite.c.
Function Documentation
void PNGAPI png_convert_from_struct_tm (png_timep ptime, struct tm FAR * ttime)
Definition at line 427 of file pngwrite.c.
References png_debug.
Referenced by png_convert_from_time_t().
void PNGAPI png_convert_from_time_t (png_timep ptime, time_t ttime)
Definition at line 439 of file pngwrite.c.
References png_convert_from_struct_tm(), and png_debug.
png_structp PNGAPI png_create_write_struct (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn)
Definition at line 452 of file pngwrite.c.
References png_create_write_struct_2(), png_free_ptr_NULL, png_malloc_ptr_NULL, and png_voidp_NULL.
Referenced by save_template_cb().
png_structp PNGAPI png_create_write_struct_2 (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn)
Definition at line 462 of file pngwrite.c.
References i, malloc_fn, NULL, PNG_ABORT, png_create_struct(), png_create_struct_2(), png_debug, png_destroy_struct(), png_doublep_NULL, png_error(), PNG_FILTER_HEURISTIC_DEFAULT, png_flush_ptr_NULL, png_free(), png_libpng_ver, png_malloc(), png_memcpy, png_rw_ptr_NULL, png_set_error_fn(), png_set_filter_heuristics(), png_set_mem_fn(), png_set_write_fn(), png_sizeof, png_snprintf, PNG_USER_HEIGHT_MAX, PNG_USER_WIDTH_MAX, png_voidp_NULL, png_warning(), and PNG_ZBUF_SIZE.
Referenced by png_create_write_struct().
void PNGAPI png_destroy_write_struct (png_structpp png_ptr_ptr, png_infopp info_ptr_ptr)
Definition at line 1018 of file pngwrite.c.
References free_fn, info_ptr, info_ptr_ptr, mem_ptr, NULL, png_debug, png_destroy_struct(), png_destroy_struct_2(), png_free(), PNG_FREE_ALL, png_free_data(), and png_write_destroy().
Referenced by save_template_cb().
void PNGAPI png_set_compression_level (png_structp png_ptr, int level)
Definition at line 1393 of file pngwrite.c.
References level, NULL, and png_debug.
void PNGAPI png_set_compression_mem_level (png_structp png_ptr, int mem_level)
Definition at line 1403 of file pngwrite.c.
References mem_level, NULL, and png_debug.
void PNGAPI png_set_compression_method (png_structp png_ptr, int method)
Definition at line 1444 of file pngwrite.c.
References method, NULL, png_debug, and png_warning().
void PNGAPI png_set_compression_strategy (png_structp png_ptr, int strategy)
Definition at line 1413 of file pngwrite.c.
References NULL, png_debug, and strategy.
void PNGAPI png_set_compression_window_bits (png_structp png_ptr, int window_bits)
Definition at line 1423 of file pngwrite.c.
References NULL, png_warning(), and window_bits.
void PNGAPI png_set_filter (png_structp png_ptr, int method, int filters)
Definition at line 1156 of file pngwrite.c.
References NULL, PNG_ALL_FILTERS, png_debug, png_error(), PNG_FILTER_AVG, PNG_FILTER_NONE, PNG_FILTER_PAETH, PNG_FILTER_SUB, PNG_FILTER_TYPE_BASE, PNG_FILTER_UP, PNG_FILTER_VALUE_AVG, PNG_FILTER_VALUE_NONE, PNG_FILTER_VALUE_PAETH, PNG_FILTER_VALUE_SUB, PNG_FILTER_VALUE_UP, PNG_FLAG_MNG_FILTER_64, PNG_INTRAPIXEL_DIFFERENCING, png_malloc(), PNG_NO_FILTERS, and png_warning().
void PNGAPI png_set_filter_heuristics (png_structp png_ptr, int heuristic_method, int num_weights, png_doublep filter_weights, png_doublep filter_costs)
Definition at line 1275 of file pngwrite.c.
References i, NULL, num_weights, png_debug, PNG_FILTER_HEURISTIC_DEFAULT, PNG_FILTER_HEURISTIC_LAST, PNG_FILTER_HEURISTIC_UNWEIGHTED, PNG_FILTER_VALUE_LAST, png_malloc(), png_sizeof, and png_warning().
Referenced by png_create_write_struct_2(), and png_write_init_3().
void PNGAPI png_set_flush (png_structp png_ptr, int nrows)
Definition at line 953 of file pngwrite.c.
References nrows, NULL, and png_debug.
void PNGAPI png_set_write_status_fn (png_structp png_ptr, png_write_status_ptr write_row_fn)
Definition at line 1456 of file pngwrite.c.
References NULL, and write_row_fn.
void PNGAPI png_set_write_user_transform_fn (png_structp png_ptr, png_user_transform_ptr write_user_transform_fn)
Definition at line 1465 of file pngwrite.c.
References NULL, png_debug, and write_user_transform_fn.
void png_write_destroy (png_structp png_ptr)
Definition at line 1089 of file pngwrite.c.
References deflateEnd(), error_fn, error_ptr, free_fn, png_debug, png_free(), png_memcpy, png_memset, png_sizeof, and warning_fn.
Referenced by png_destroy_write_struct().
void PNGAPI png_write_end (png_structp png_ptr, png_infop info_ptr)
Definition at line 310 of file pngwrite.c.
References png_unknown_chunk_t::data, i, keep, png_unknown_chunk_t::location, png_unknown_chunk_t::name, NULL, PNG_AFTER_IDAT, png_debug, png_debug2, png_error(), png_flush(), png_handle_as_unknown(), PNG_HANDLE_CHUNK_ALWAYS, PNG_HANDLE_CHUNK_NEVER, PNG_HAVE_IDAT, PNG_INFO_tIME, PNG_TEXT_COMPRESSION_NONE, PNG_TEXT_COMPRESSION_NONE_WR, PNG_TEXT_COMPRESSION_zTXt, PNG_TEXT_COMPRESSION_zTXt_WR, png_warning(), png_write_chunk(), png_write_IEND(), png_write_tEXt(), png_write_tIME(), png_write_zTXt(), and png_unknown_chunk_t::size.
Referenced by png_write_png(), and save_template_cb().
void PNGAPI png_write_flush (png_structp png_ptr)
Definition at line 963 of file pngwrite.c.
References deflate(), NULL, png_debug, png_error(), png_flush(), png_write_IDAT(), Z_OK, and Z_SYNC_FLUSH.
void PNGAPI png_write_image (png_structp png_ptr, png_bytepp image)
Definition at line 745 of file pngwrite.c.
References i, NULL, png_debug, png_set_interlace_handling(), and png_write_row().
Referenced by png_write_png().
void PNGAPI png_write_info (png_structp png_ptr, png_infop info_ptr)
Definition at line 131 of file pngwrite.c.
References png_unknown_chunk_t::data, i, int, keep, png_unknown_chunk_t::location, png_unknown_chunk_t::name, NULL, PNG_COLOR_TYPE_PALETTE, png_debug, png_debug2, png_error(), png_handle_as_unknown(), PNG_HANDLE_CHUNK_ALWAYS, PNG_HANDLE_CHUNK_NEVER, PNG_HAVE_IDAT, PNG_HAVE_PLTE, PNG_INFO_bKGD, PNG_INFO_hIST, PNG_INFO_oFFs, PNG_INFO_pCAL, PNG_INFO_pHYs, PNG_INFO_PLTE, PNG_INFO_sCAL, PNG_INFO_sPLT, PNG_INFO_tIME, PNG_INFO_tRNS, PNG_TEXT_COMPRESSION_NONE, PNG_TEXT_COMPRESSION_NONE_WR, PNG_TEXT_COMPRESSION_zTXt, PNG_TEXT_COMPRESSION_zTXt_WR, png_warning(), png_write_bKGD(), png_write_chunk(), png_write_hIST(), png_write_info_before_PLTE(), png_write_oFFs(), png_write_pCAL(), png_write_pHYs(), png_write_PLTE(), png_write_sCAL(), png_write_sPLT(), png_write_tEXt(), png_write_tIME(), png_write_tRNS(), png_write_zTXt(), and png_unknown_chunk_t::size.
Referenced by png_write_png(), and save_template_cb().
void PNGAPI png_write_info_before_PLTE (png_structp png_ptr, png_infop info_ptr)
Definition at line 29 of file pngwrite.c.
References png_unknown_chunk_t::data, keep, png_unknown_chunk_t::location, png_unknown_chunk_t::name, NULL, PNG_COMPRESSION_TYPE_BASE, png_debug, png_handle_as_unknown(), PNG_HANDLE_CHUNK_ALWAYS, PNG_HANDLE_CHUNK_NEVER, PNG_HAVE_IDAT, PNG_HAVE_PLTE, PNG_INFO_cHRM, PNG_INFO_gAMA, PNG_INFO_iCCP, PNG_INFO_sBIT, PNG_INFO_sRGB, png_warning(), png_write_cHRM(), png_write_cHRM_fixed(), png_write_chunk(), png_write_gAMA(), png_write_gAMA_fixed(), png_write_iCCP(), png_write_IHDR(), PNG_WRITE_INTERLACING_SUPPORTED, png_write_sBIT(), png_write_sig(), png_write_sRGB(), and png_unknown_chunk_t::size.
Referenced by png_write_info().
void PNGAPI png_write_init (png_structp png_ptr)
Definition at line 592 of file pngwrite.c.
References png_write_init_2().
void PNGAPI png_write_init_2 (png_structp png_ptr, png_const_charp user_png_ver, png_size_t png_struct_size, png_size_t png_info_size)
Definition at line 599 of file pngwrite.c.
References NULL, png_error(), png_libpng_ver, png_sizeof, png_snprintf, png_warning(), and png_write_init_3().
Referenced by png_write_init().
void PNGAPI png_write_init_3 (png_structpp ptr_ptr, png_const_charp user_png_ver, png_size_t png_struct_size)
Definition at line 647 of file pngwrite.c.
References i, NULL, png_create_struct(), png_debug, png_destroy_struct(), png_doublep_NULL, PNG_FILTER_HEURISTIC_DEFAULT, png_flush_ptr_NULL, png_libpng_ver, png_malloc(), png_memcpy, png_memset, png_rw_ptr_NULL, png_set_filter_heuristics(), png_set_write_fn(), png_sizeof, PNG_USER_HEIGHT_MAX, PNG_USER_WIDTH_MAX, png_voidp_NULL, png_warning(), and PNG_ZBUF_SIZE.
Referenced by png_write_init_2().
void PNGAPI png_write_png (png_structp png_ptr, png_infop info_ptr, int transforms, voidp params)
Definition at line 1479 of file pngwrite.c.
References NULL, params, PNG_FILLER_AFTER, PNG_FILLER_BEFORE, PNG_INFO_IDAT, PNG_INFO_sBIT, png_set_bgr(), png_set_filler(), png_set_invert_alpha(), png_set_invert_mono(), png_set_packing(), png_set_packswap(), png_set_shift(), png_set_swap(), png_set_swap_alpha(), PNG_TRANSFORM_BGR, PNG_TRANSFORM_INVERT_ALPHA, PNG_TRANSFORM_INVERT_MONO, PNG_TRANSFORM_PACKING, PNG_TRANSFORM_PACKSWAP, PNG_TRANSFORM_SHIFT, PNG_TRANSFORM_STRIP_FILLER_AFTER, PNG_TRANSFORM_STRIP_FILLER_BEFORE, PNG_TRANSFORM_SWAP_ALPHA, PNG_TRANSFORM_SWAP_ENDIAN, png_write_end(), png_write_image(), png_write_info(), and transforms.
void PNGAPI png_write_row (png_structp png_ptr, png_bytep row)
Definition at line 776 of file pngwrite.c.
References NULL, png_debug1, png_debug2, png_do_write_interlace(), png_do_write_intrapixel(), png_do_write_transformations(), png_error(), PNG_FLAG_MNG_FILTER_64, PNG_INTRAPIXEL_DIFFERENCING, png_memcpy_check(), png_warning(), png_write_find_filter(), png_write_finish_row(), and png_write_start_row().
Referenced by png_write_image(), png_write_rows(), and save_template_cb().
void PNGAPI png_write_rows (png_structp png_ptr, png_bytepp row, png_uint_32 num_rows)
Definition at line 723 of file pngwrite.c.
References i, NULL, num_rows, png_debug, and png_write_row().