SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngwutil.c File Reference
pngwutil.c File Reference
#include "png.h"
Classes
struct compression_state
Defines
#define PNG_INTERNAL
#define PNG_MAXSUM (((png_uint_32)(-1)) >> 1)
#define PNG_HISHIFT 10
#define PNG_LOMASK ((png_uint_32)0xffffL)
#define PNG_HIMASK ((png_uint_32)(~PNG_LOMASK >> PNG_HISHIFT))
Functions
void PNGAPI png_save_uint_32 (png_bytep buf, png_uint_32 i)
void PNGAPI png_save_int_32 (png_bytep buf, png_int_32 i)
void PNGAPI png_save_uint_16 (png_bytep buf, unsigned int i)
void png_write_sig (png_structp png_ptr)
void PNGAPI png_write_chunk (png_structp png_ptr, png_bytep chunk_name, png_bytep data, png_size_t length)
void PNGAPI png_write_chunk_start (png_structp png_ptr, png_bytep chunk_name, png_uint_32 length)
void PNGAPI png_write_chunk_data (png_structp png_ptr, png_bytep data, png_size_t length)
void PNGAPI png_write_chunk_end (png_structp png_ptr)
void png_write_IHDR (png_structp png_ptr, png_uint_32 width, png_uint_32 height, int bit_depth, int color_type, int compression_type, int filter_type, int interlace_type)
void png_write_PLTE (png_structp png_ptr, png_colorp palette, png_uint_32 num_pal)
void png_write_IDAT (png_structp png_ptr, png_bytep data, png_size_t length)
void png_write_IEND (png_structp png_ptr)
void png_write_gAMA (png_structp png_ptr, double file_gamma)
void png_write_gAMA_fixed (png_structp png_ptr, png_fixed_point file_gamma)
void png_write_sRGB (png_structp png_ptr, int srgb_intent)
void png_write_iCCP (png_structp png_ptr, png_charp name, int compression_type, png_charp profile, int profile_len)
void png_write_sPLT (png_structp png_ptr, png_sPLT_tp spalette)
void png_write_sBIT (png_structp png_ptr, png_color_8p sbit, int color_type)
void png_write_cHRM (png_structp png_ptr, double white_x, double white_y, double red_x, double red_y, double green_x, double green_y, double blue_x, double blue_y)
void png_write_cHRM_fixed (png_structp png_ptr, png_fixed_point white_x, png_fixed_point white_y, png_fixed_point red_x, png_fixed_point red_y, png_fixed_point green_x, png_fixed_point green_y, png_fixed_point blue_x, png_fixed_point blue_y)
void png_write_tRNS (png_structp png_ptr, png_bytep trans, png_color_16p tran, int num_trans, int color_type)
void png_write_bKGD (png_structp png_ptr, png_color_16p back, int color_type)
void png_write_hIST (png_structp png_ptr, png_uint_16p hist, int num_hist)
png_size_t png_check_keyword (png_structp png_ptr, png_charp key, png_charpp new_key)
void png_write_tEXt (png_structp png_ptr, png_charp key, png_charp text, png_size_t text_len)
void png_write_zTXt (png_structp png_ptr, png_charp key, png_charp text, png_size_t text_len, int compression)
void png_write_oFFs (png_structp png_ptr, png_int_32 x_offset, png_int_32 y_offset, int unit_type)
void png_write_pCAL (png_structp png_ptr, png_charp purpose, png_int_32 X0, png_int_32 X1, int type, int nparams, png_charp units, png_charpp params)
void png_write_sCAL (png_structp png_ptr, int unit, double width, double height)
void png_write_pHYs (png_structp png_ptr, png_uint_32 x_pixels_per_unit, png_uint_32 y_pixels_per_unit, int unit_type)
void png_write_tIME (png_structp png_ptr, png_timep mod_time)
void png_write_start_row (png_structp png_ptr)
void png_write_finish_row (png_structp png_ptr)
void png_do_write_interlace (png_row_infop row_info, png_bytep row, int pass)
void png_write_find_filter (png_structp png_ptr, png_row_infop row_info)
void png_write_filtered_row (png_structp png_ptr, png_bytep filtered_row)
Define Documentation
#define PNG_HIMASK ((png_uint_32)(~PNG_LOMASK >> PNG_HISHIFT))
Definition at line 2144 of file pngwutil.c.
Referenced by png_write_find_filter().
#define PNG_HISHIFT 10
Definition at line 2142 of file pngwutil.c.
Referenced by png_write_find_filter().
#define PNG_INTERNAL
Definition at line 14 of file pngwutil.c.
#define PNG_LOMASK ((png_uint_32)0xffffL)
Definition at line 2143 of file pngwutil.c.
Referenced by png_write_find_filter().
#define PNG_MAXSUM (((png_uint_32)(-1)) >> 1)
Definition at line 2141 of file pngwutil.c.
Referenced by png_write_find_filter().
Function Documentation
png_size_t png_check_keyword (png_structp png_ptr, png_charp key, png_charpp new_key)
Definition at line 1224 of file pngwutil.c.
References NULL, png_debug, png_debug1, png_free(), png_malloc_warn(), png_snprintf, png_strlen, and png_warning().
Referenced by png_write_iCCP(), png_write_pCAL(), png_write_sPLT(), png_write_tEXt(), and png_write_zTXt().
void png_do_write_interlace (png_row_infop row_info, png_bytep row, int pass)
Definition at line 1974 of file pngwutil.c.
References i, int, NULL, png_debug, png_memcpy, png_pass_inc, png_pass_start, row, and value.
Referenced by png_write_row().
void PNGAPI png_save_int_32 (png_bytep buf, png_int_32 i)
Definition at line 36 of file pngwutil.c.
Referenced by png_write_oFFs(), and png_write_pCAL().
void PNGAPI png_save_uint_16 (png_bytep buf, unsigned int i)
Definition at line 49 of file pngwutil.c.
Referenced by png_write_bKGD(), png_write_hIST(), png_write_sPLT(), png_write_tIME(), and png_write_tRNS().
void PNGAPI png_save_uint_32 (png_bytep buf, png_uint_32 i)
Definition at line 23 of file pngwutil.c.
Referenced by png_write_cHRM(), png_write_cHRM_fixed(), png_write_chunk_end(), png_write_chunk_start(), png_write_gAMA(), png_write_gAMA_fixed(), png_write_IHDR(), and png_write_pHYs().
void png_write_bKGD (png_structp png_ptr, png_color_16p back, int color_type)
Definition at line 1128 of file pngwutil.c.
References buf, PNG_bKGD, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, png_debug, PNG_FLAG_MNG_EMPTY_PLTE, PNG_MNG_FEATURES_SUPPORTED, png_save_uint_16(), png_warning(), and png_write_chunk().
Referenced by png_write_info().
void png_write_cHRM (png_structp png_ptr, double white_x, double white_y, double red_x, double red_y, double green_x, double green_y, double blue_x, double blue_y)
Definition at line 984 of file pngwutil.c.
References buf, int_blue_x, int_blue_y, int_green_x, int_green_y, int_red_x, int_red_y, int_white_x, int_white_y, png_check_cHRM_fixed(), PNG_cHRM, png_debug, png_save_uint_32(), and png_write_chunk().
Referenced by png_write_info_before_PLTE().
void png_write_cHRM_fixed (png_structp png_ptr, png_fixed_point white_x, png_fixed_point white_y, png_fixed_point red_x, png_fixed_point red_y, png_fixed_point green_x, png_fixed_point green_y, png_fixed_point blue_x, png_fixed_point blue_y)
Definition at line 1032 of file pngwutil.c.
References buf, png_check_cHRM_fixed(), PNG_cHRM, png_debug, png_save_uint_32(), and png_write_chunk().
Referenced by png_write_info_before_PLTE().
void PNGAPI png_write_chunk (png_structp png_ptr, png_bytep chunk_name, png_bytep data, png_size_t length)
Definition at line 83 of file pngwutil.c.
References NULL, png_write_chunk_data(), png_write_chunk_end(), and png_write_chunk_start().
Referenced by png_write_bKGD(), png_write_cHRM(), png_write_cHRM_fixed(), png_write_end(), png_write_gAMA(), png_write_gAMA_fixed(), png_write_IDAT(), png_write_IEND(), png_write_IHDR(), png_write_info(), png_write_info_before_PLTE(), png_write_oFFs(), png_write_pHYs(), png_write_sBIT(), png_write_sCAL(), png_write_sRGB(), png_write_tIME(), and png_write_tRNS().
void PNGAPI png_write_chunk_data (png_structp png_ptr, png_bytep data, png_size_t length)
Definition at line 126 of file pngwutil.c.
References NULL, png_calculate_crc(), and png_write_data().
Referenced by png_write_chunk(), png_write_hIST(), png_write_iCCP(), png_write_pCAL(), png_write_PLTE(), png_write_sPLT(), png_write_tEXt(), and png_write_zTXt().
void PNGAPI png_write_chunk_end (png_structp png_ptr)
Definition at line 143 of file pngwutil.c.
References buf, NULL, png_save_uint_32(), and png_write_data().
Referenced by png_write_chunk(), png_write_hIST(), png_write_iCCP(), png_write_pCAL(), png_write_PLTE(), png_write_sPLT(), png_write_tEXt(), and png_write_zTXt().
void PNGAPI png_write_chunk_start (png_structp png_ptr, png_bytep chunk_name, png_uint_32 length)
Definition at line 98 of file pngwutil.c.
References buf, NULL, png_calculate_crc(), png_debug2, png_memcpy, png_reset_crc(), png_save_uint_32(), and png_write_data().
Referenced by png_write_chunk(), png_write_hIST(), png_write_iCCP(), png_write_pCAL(), png_write_PLTE(), png_write_sPLT(), png_write_tEXt(), and png_write_zTXt().
void png_write_filtered_row (png_structp png_ptr, png_bytep filtered_row)
Definition at line 2766 of file pngwutil.c.
References deflate(), NULL, png_debug, png_debug1, png_error(), png_write_IDAT(), Z_NO_FLUSH, and Z_OK.
Referenced by png_write_find_filter().
void png_write_find_filter (png_structp png_ptr, png_row_infop row_info)
Definition at line 2146 of file pngwutil.c.
References b, i, int, png_debug, PNG_FILTER_AVG, PNG_FILTER_HEURISTIC_WEIGHTED, PNG_FILTER_NONE, PNG_FILTER_PAETH, PNG_FILTER_SUB, PNG_FILTER_UP, PNG_FILTER_VALUE_AVG, PNG_FILTER_VALUE_NONE, PNG_FILTER_VALUE_PAETH, PNG_FILTER_VALUE_SUB, PNG_FILTER_VALUE_UP, PNG_HIMASK, PNG_HISHIFT, PNG_LOMASK, PNG_MAXSUM, and png_write_filtered_row().
Referenced by png_write_row().
void png_write_finish_row (png_structp png_ptr)
Definition at line 1854 of file pngwutil.c.
References deflate(), deflateReset(), NULL, png_debug, png_error(), png_memset, png_pass_inc, png_pass_start, png_pass_yinc, png_pass_ystart, png_write_IDAT(), Z_BINARY, Z_FINISH, Z_OK, and Z_STREAM_END.
Referenced by png_write_row().
void png_write_gAMA (png_structp png_ptr, double file_gamma)
Definition at line 707 of file pngwutil.c.
References buf, png_debug, PNG_gAMA, png_save_uint_32(), and png_write_chunk().
Referenced by png_write_info_before_PLTE().
void png_write_gAMA_fixed (png_structp png_ptr, png_fixed_point file_gamma)
Definition at line 725 of file pngwutil.c.
References buf, png_debug, PNG_gAMA, png_save_uint_32(), and png_write_chunk().
Referenced by png_write_info_before_PLTE().
void png_write_hIST (png_structp png_ptr, png_uint_16p hist, int num_hist)
Definition at line 1182 of file pngwutil.c.
References buf, i, png_debug, png_debug2, PNG_hIST, png_save_uint_16(), png_warning(), png_write_chunk_data(), png_write_chunk_end(), and png_write_chunk_start().
Referenced by png_write_info().
void png_write_iCCP (png_structp png_ptr, png_charp name, int compression_type, png_charp profile, int profile_len)
Definition at line 764 of file pngwutil.c.
References compression_state::input, compression_state::input_len, compression_state::max_output_ptr, NULL, compression_state::num_output_ptr, compression_state::output_ptr, png_check_keyword(), PNG_COMPRESSION_TYPE_BASE, png_debug, png_free(), PNG_iCCP, png_warning(), png_write_chunk_data(), png_write_chunk_end(), and png_write_chunk_start().
Referenced by png_write_info_before_PLTE().
void png_write_IDAT (png_structp png_ptr, png_bytep data, png_size_t length)
Definition at line 635 of file pngwutil.c.
References PNG_COMPRESSION_TYPE_BASE, png_debug, png_error(), PNG_HAVE_IDAT, PNG_IDAT, and png_write_chunk().
Referenced by png_write_filtered_row(), png_write_finish_row(), and png_write_flush().
void png_write_IEND (png_structp png_ptr)
Definition at line 690 of file pngwutil.c.
References png_bytep_NULL, png_debug, PNG_HAVE_IEND, PNG_IEND, and png_write_chunk().
Referenced by png_write_end().
void png_write_IHDR (png_structp png_ptr, png_uint_32 width, png_uint_32 height, int bit_depth, int color_type, int compression_type, int filter_type, int interlace_type)
Definition at line 390 of file pngwutil.c.
References buf, deflateInit2, height, PNG_ALL_FILTERS, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, PNG_COMPRESSION_TYPE_BASE, png_debug, png_error(), PNG_FILTER_NONE, PNG_FILTER_TYPE_BASE, PNG_FLAG_MNG_FILTER_64, PNG_HAVE_IHDR, PNG_IHDR, PNG_INTERLACE_ADAM7, PNG_INTERLACE_NONE, PNG_INTRAPIXEL_DIFFERENCING, PNG_MNG_FEATURES_SUPPORTED, png_save_uint_32(), png_warning(), png_write_chunk(), png_zalloc(), png_zfree(), width, Z_BINARY, Z_DEFAULT_COMPRESSION, Z_DEFAULT_STRATEGY, Z_FILTERED, Z_MEM_ERROR, Z_OK, Z_STREAM_ERROR, and Z_VERSION_ERROR.
Referenced by png_write_info_before_PLTE().
void png_write_oFFs (png_structp png_ptr, png_int_32 x_offset, png_int_32 y_offset, int unit_type)
Definition at line 1536 of file pngwutil.c.
References buf, png_debug, PNG_oFFs, PNG_OFFSET_LAST, png_save_int_32(), png_warning(), and png_write_chunk().
Referenced by png_write_info().
void png_write_pCAL (png_structp png_ptr, png_charp purpose, png_int_32 X0, png_int_32 X1, int type, int nparams, png_charp units, png_charpp params)
Definition at line 1559 of file pngwutil.c.
References buf, i, nparams, png_check_keyword(), png_debug1, png_debug2, PNG_EQUATION_LAST, png_free(), png_malloc(), PNG_pCAL, png_save_int_32(), png_sizeof, png_strlen, png_warning(), png_write_chunk_data(), png_write_chunk_end(), and png_write_chunk_start().
Referenced by png_write_info().
void png_write_pHYs (png_structp png_ptr, png_uint_32 x_pixels_per_unit, png_uint_32 y_pixels_per_unit, int unit_type)
Definition at line 1696 of file pngwutil.c.
References png_debug, PNG_pHYs, PNG_RESOLUTION_LAST, png_save_uint_32(), png_warning(), and png_write_chunk().
Referenced by png_write_info().
void png_write_PLTE (png_structp png_ptr, png_colorp palette, png_uint_32 num_pal)
Definition at line 570 of file pngwutil.c.
References buf, i, palette, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, png_debug, png_debug1, png_error(), PNG_FLAG_MNG_EMPTY_PLTE, PNG_HAVE_PLTE, PNG_MNG_FEATURES_SUPPORTED, PNG_PLTE, png_warning(), png_write_chunk_data(), png_write_chunk_end(), and png_write_chunk_start().
Referenced by png_write_info().
void png_write_sBIT (png_structp png_ptr, png_color_8p sbit, int color_type)
Definition at line 926 of file pngwutil.c.
References buf, PNG_COLOR_MASK_ALPHA, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, png_debug, PNG_sBIT, png_warning(), png_write_chunk(), and size.
Referenced by png_write_info_before_PLTE().
void png_write_sCAL (png_structp png_ptr, int unit, double width, double height)
Definition at line 1623 of file pngwutil.c.
References buf, NULL, png_debug, png_debug1, PNG_sCAL, png_snprintf, png_strlen, and png_write_chunk().
Referenced by png_write_info().
void png_write_sig (png_structp png_ptr)
Definition at line 62 of file pngwutil.c.
References png_write_data().
Referenced by png_write_info_before_PLTE().
void png_write_sPLT (png_structp png_ptr, png_sPLT_tp spalette)
Definition at line 845 of file pngwutil.c.
References entries, green, i, png_check_keyword(), png_debug, png_free(), png_save_uint_16(), PNG_sPLT, png_write_chunk_data(), png_write_chunk_end(), png_write_chunk_start(), and red.
Referenced by png_write_info().
void png_write_sRGB (png_structp png_ptr, int srgb_intent)
Definition at line 744 of file pngwutil.c.
References buf, png_debug, PNG_sRGB, PNG_sRGB_INTENT_LAST, png_warning(), and png_write_chunk().
Referenced by png_write_info_before_PLTE().
void png_write_start_row (png_structp png_ptr)
Definition at line 1753 of file pngwutil.c.
References png_debug, PNG_FILTER_AVG, PNG_FILTER_PAETH, PNG_FILTER_SUB, PNG_FILTER_UP, PNG_FILTER_VALUE_AVG, PNG_FILTER_VALUE_NONE, PNG_FILTER_VALUE_PAETH, PNG_FILTER_VALUE_SUB, PNG_FILTER_VALUE_UP, png_malloc(), png_memset, png_pass_inc, png_pass_start, png_pass_yinc, and png_pass_ystart.
Referenced by png_write_row().
void png_write_tEXt (png_structp png_ptr, png_charp key, png_charp text, png_size_t text_len)
Definition at line 1346 of file pngwutil.c.
References NULL, png_check_keyword(), png_debug, png_free(), png_strlen, PNG_tEXt, png_write_chunk_data(), png_write_chunk_end(), and png_write_chunk_start().
Referenced by png_write_end(), png_write_info(), and png_write_zTXt().
void png_write_tIME (png_structp png_ptr, png_timep mod_time)
Definition at line 1723 of file pngwutil.c.
References png_debug, png_save_uint_16(), PNG_tIME, png_warning(), and png_write_chunk().
Referenced by png_write_end(), and png_write_info().
void png_write_tRNS (png_structp png_ptr, png_bytep trans, png_color_16p tran, int num_trans, int color_type)
Definition at line 1071 of file pngwutil.c.
References buf, PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, png_debug, png_save_uint_16(), PNG_tRNS, png_warning(), and png_write_chunk().
Referenced by png_write_info().
void png_write_zTXt (png_structp png_ptr, png_charp key, png_charp text, png_size_t text_len, int compression)
Definition at line 1387 of file pngwutil.c.
References buf, compression_state::input, compression_state::input_len, compression_state::max_output_ptr, NULL, compression_state::num_output_ptr, compression_state::output_ptr, png_check_keyword(), png_debug, png_free(), png_strlen, PNG_TEXT_COMPRESSION_NONE, png_write_chunk_data(), png_write_chunk_end(), png_write_chunk_start(), png_write_tEXt(), and PNG_zTXt.
Referenced by png_write_end(), and png_write_info().