SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngwio.c File Reference
pngwio.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
Functions
void png_write_data (png_structp png_ptr, png_bytep data, png_size_t length)
void PNGAPI png_default_write_data (png_structp png_ptr, png_bytep data, png_size_t length)
void png_flush (png_structp png_ptr)
void PNGAPI png_default_flush (png_structp png_ptr)
void PNGAPI png_set_write_fn (png_structp png_ptr, png_voidp io_ptr, png_rw_ptr write_data_fn, png_flush_ptr output_flush_fn)
Define Documentation
#define PNG_INTERNAL
Definition at line 21 of file pngwio.c.
Function Documentation
void PNGAPI png_default_flush (png_structp png_ptr)
Definition at line 142 of file pngwio.c.
References CVT_PTR, io_ptr, and NULL.
Referenced by png_set_write_fn().
void PNGAPI png_default_write_data (png_structp png_ptr, png_bytep data, png_size_t length)
Definition at line 49 of file pngwio.c.
References NULL, and png_error().
Referenced by png_set_write_fn().
void png_flush (png_structp png_ptr)
Definition at line 134 of file pngwio.c.
References NULL.
Referenced by png_write_end(), and png_write_flush().
void PNGAPI png_set_write_fn (png_structp png_ptr, png_voidp io_ptr, png_rw_ptr write_data_fn, png_flush_ptr output_flush_fn)
Definition at line 187 of file pngwio.c.
References io_ptr, NULL, output_flush_fn, png_default_flush(), png_default_write_data(), png_warning(), and write_data_fn.
Referenced by png_create_write_struct_2(), and png_write_init_3().
void png_write_data (png_structp png_ptr, png_bytep data, png_size_t length)
Definition at line 33 of file pngwio.c.
References data, length, NULL, and png_error().
Referenced by png_write_chunk_data(), png_write_chunk_end(), png_write_chunk_start(), and png_write_sig().