SfR Fresh Dox - fltk: fltk-1.3.0rc3/png/pngwtran.c File Reference
pngwtran.c File Reference
#include "png.h"
Defines
#define PNG_INTERNAL
Functions
void png_do_write_transformations (png_structp png_ptr)
void png_do_pack (png_row_infop row_info, png_bytep row, png_uint_32 bit_depth)
void png_do_shift (png_row_infop row_info, png_bytep row, png_color_8p bit_depth)
void png_do_write_swap_alpha (png_row_infop row_info, png_bytep row)
void png_do_write_invert_alpha (png_row_infop row_info, png_bytep row)
void png_do_write_intrapixel (png_row_infop row_info, png_bytep row)
Define Documentation
#define PNG_INTERNAL
Definition at line 14 of file pngwtran.c.
Function Documentation
void png_do_pack (png_row_infop row_info, png_bytep row, png_uint_32 bit_depth)
Definition at line 90 of file pngwtran.c.
References i, mask, NULL, png_debug, row, and value.
Referenced by png_do_write_transformations().
void png_do_shift (png_row_infop row_info, png_bytep row, png_color_8p bit_depth)
Definition at line 216 of file pngwtran.c.
References NULL, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_PALETTE, and png_debug.
Referenced by png_do_write_transformations().
void png_do_write_intrapixel (png_row_infop row_info, png_bytep row)
Definition at line 518 of file pngwtran.c.
References i, NULL, PNG_COLOR_MASK_COLOR, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_debug, red, s1, and s2.
Referenced by png_write_row().
void png_do_write_invert_alpha (png_row_infop row_info, png_bytep row)
Definition at line 428 of file pngwtran.c.
References i, NULL, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_RGB_ALPHA, and png_debug.
Referenced by png_do_write_transformations().
void png_do_write_swap_alpha (png_row_infop row_info, png_bytep row)
Definition at line 340 of file pngwtran.c.
References i, NULL, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_RGB_ALPHA, and png_debug.
Referenced by png_do_write_transformations().
void png_do_write_transformations (png_structp png_ptr)
Definition at line 22 of file pngwtran.c.
References NULL, png_debug, png_do_bgr(), png_do_invert(), png_do_pack(), png_do_packswap(), png_do_shift(), png_do_strip_filler(), png_do_swap(), png_do_write_invert_alpha(), and png_do_write_swap_alpha().
Referenced by png_write_row().