SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/print_panel.cxx File Reference
print_panel.cxx File Reference
#include "print_panel.h"
#include <stdio.h>
#include <stdlib.h>
#include "../src/flstring.h"
#include <FL/Fl_Preferences.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Pixmap.H>
Functions
Fl_Double_Window * make_print_panel ()
void print_cb (Fl_Return_Button *, void *)
void print_load ()
void print_update_status ()
Function Documentation
Fl_Double_Window* make_print_panel ()
Definition at line 249 of file print_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Printer::dialog_all, Fl_Printer::dialog_cancel_button, Fl_Printer::dialog_copies, Fl_Printer::dialog_copyNo, Fl_Printer::dialog_from, Fl_Printer::dialog_pages, Fl_Printer::dialog_print_button, Fl_Printer::dialog_printer, Fl_Printer::dialog_properties, Fl_Printer::dialog_range, Fl_Printer::dialog_title, Fl_Printer::dialog_to, Fl_Button::down_box(), Fl_Menu_::down_box(), Fl_Group::end(), FL_ALIGN_BOTTOM_RIGHT, FL_ALIGN_CLIP, FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_TOP_LEFT, FL_BACKGROUND2_COLOR, FL_BORDER_BOX, FL_DOWN_BOX, FL_FOREGROUND_COLOR, FL_HELVETICA, FL_ROUND_DOWN_BOX, FL_THIN_DOWN_BOX, FL_WHEN_CHANGED, Fl_Widget::hide(), Fl_Widget::image(), Fl_Widget::labelfont(), Fl_Widget::labelsize(), Fl_Menu_::menu(), print_cb(), print_properties_panel, Fl_Printer::property_cancel, Fl_Printer::property_mode, Fl_Printer::property_pagesize, Fl_Printer::property_save, Fl_Printer::property_title, Fl_Printer::property_use, Fl_Widget::selection_color(), Fl_Window::set_modal(), Fl_Input_::textfont(), Fl_Widget::type(), Fl_Button::value(), Fl_Widget::w(), and Fl_Widget::when().
void print_cb (Fl_Return_Button * , void *)
Definition at line 513 of file print_panel.cxx.
References Fl_Widget::activate(), Fl::check(), Fl_Widget::deactivate(), Fl_Type::first, fl_alert(), fl_choice(), Fl_File_Chooser::fl_file_chooser(), Fl_File_Chooser::fl_file_chooser_ok_label(), fl_fopen(), FL_VERSION, h, Fl_Double_Window::hide(), Fl_Widget::hide(), i, Fl_Type::is_window(), Fl_Window::label(), Fl_Widget::label(), length, Fl_Progress::maximum(), Fl_Menu_::menu(), Fl_Progress::minimum(), Fl_Window::modal(), Fl_Type::next, NULL, outfile, print_all, print_choice, print_collate_button, print_copies, print_from, print_output_mode, print_page_size, print_pages, print_panel, print_panel_controls, print_progress, print_selection, print_to, ptr, Fl_Window_Type::read_image(), Fl_Group::resizable(), Fl_Type::selected, Fl_Widget::show(), snprintf, Fl_Menu_::text(), Fl_Menu_Item::user_data(), value, Fl_Choice::value(), Fl_Progress::value(), Fl_Input_::value(), Fl_Spinner::value(), Fl_Button::value(), w, and width.
void print_load ()
Definition at line 518 of file print_panel.cxx.
References Fl_Menu_::add(), Fl_Menu_::clear(), Fl_Printer::dialog_print_to_file, FL_MENU_DIVIDER, i, Fl_Menu_::menu(), name, NULL, print_update_status(), Fl_Menu_::size(), Fl_Menu_::text(), Fl_Menu_Item::user_data(), and Fl_Choice::value().
void print_update_status ()
Definition at line 567 of file print_panel.cxx.
References Fl_Preferences::get(), Fl_Widget::label(), Fl_Menu_::menu(), name, NULL, Fl_Button::setonly(), snprintf, Fl_Menu_Item::user_data(), val, and Fl_Choice::value().