SfR Fresh Dox - fltk: Fl_Multi_Label Struct Reference
Fl_Multi_Label Struct Reference
#include <Fl_Multi_Label.H>
Public Member Functions
void label (Fl_Widget *)
void label (Fl_Menu_Item *)
Public Attributes
const char * labela
const char * labelb
uchar typea
uchar typeb
Detailed Description
Definition at line 34 of file Fl_Multi_Label.H.
Member Function Documentation
void Fl_Multi_Label::label (Fl_Widget * o)
Definition at line 68 of file Fl_Multi_Label.cxx.
References _FL_MULTI_LABEL, Fl_Widget::label(), and Fl::set_labeltype().
void Fl_Multi_Label::label (Fl_Menu_Item * o)
Definition at line 73 of file Fl_Multi_Label.cxx.
References _FL_MULTI_LABEL, Fl_Menu_Item::label(), and Fl::set_labeltype().
Member Data Documentation
const char* Fl_Multi_Label::labela
Definition at line 35 of file Fl_Multi_Label.H.
const char* Fl_Multi_Label::labelb
Definition at line 36 of file Fl_Multi_Label.H.
uchar Fl_Multi_Label::typea
Definition at line 37 of file Fl_Multi_Label.H.
uchar Fl_Multi_Label::typeb
Definition at line 38 of file Fl_Multi_Label.H.
The documentation for this struct was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Multi_Label.H
fltk-1.3.0rc3/src/Fl_Multi_Label.cxx