SfR Fresh Dox - fltk: Fl_Help_Font_Stack Struct Reference
Fl_Help_Font_Stack Struct Reference
#include <Fl_Help_View.H>
Public Member Functions
Fl_Help_Font_Stack ()
void init (Fl_Font f, Fl_Fontsize s, Fl_Color c)
void top (Fl_Font &f, Fl_Fontsize &s, Fl_Color &c)
void push (Fl_Font f, Fl_Fontsize s, Fl_Color c)
void pop (Fl_Font &f, Fl_Fontsize &s, Fl_Color &c)
size_t count () const
Protected Attributes
size_t nfonts_
current number of fonts in stack
Fl_Help_Font_Style elts_ [100]
font elements
Detailed Description
Definition at line 105 of file Fl_Help_View.H.
Constructor & Destructor Documentation
Fl_Help_Font_Stack::Fl_Help_Font_Stack () [inline]
font stack construction, initialize attributes.
Definition at line 107 of file Fl_Help_View.H.
References nfonts_.
Member Function Documentation
size_t Fl_Help_Font_Stack::count () const [inline]
Gets the current count of font style elements in the stack.
Definition at line 132 of file Fl_Help_View.H.
References nfonts_.
void Fl_Help_Font_Stack::init (Fl_Font f, Fl_Fontsize s, Fl_Color c) [inline]
Definition at line 111 of file Fl_Help_View.H.
References elts_, fl_color(), fl_font(), nfonts_, and Fl_Help_Font_Style::set().
void Fl_Help_Font_Stack::pop (Fl_Font & f, Fl_Fontsize & s, Fl_Color & c) [inline]
Pops from the stack the font style triplet and calls fl_font() & fl_color() adequately
Definition at line 126 of file Fl_Help_View.H.
References fl_color(), fl_font(), nfonts_, and top().
void Fl_Help_Font_Stack::push (Fl_Font f, Fl_Fontsize s, Fl_Color c) [inline]
Pushes the font style triplet on the stack, also calls fl_font() & fl_color() adequately
Definition at line 120 of file Fl_Help_View.H.
References elts_, fl_color(), fl_font(), MAX_FL_HELP_FS_ELTS, nfonts_, and Fl_Help_Font_Style::set().
void Fl_Help_Font_Stack::top (Fl_Font & f, Fl_Fontsize & s, Fl_Color & c) [inline]
Gets the top (current) element on the stack.
Definition at line 118 of file Fl_Help_View.H.
References elts_, Fl_Help_Font_Style::get(), and nfonts_.
Referenced by pop().
Member Data Documentation
Fl_Help_Font_Style Fl_Help_Font_Stack::elts_[100] [protected]
font elements
Definition at line 136 of file Fl_Help_View.H.
Referenced by init(), push(), and top().
size_t Fl_Help_Font_Stack::nfonts_ [protected]
current number of fonts in stack
Definition at line 135 of file Fl_Help_View.H.
Referenced by count(), Fl_Help_Font_Stack(), init(), pop(), push(), and top().
The documentation for this struct was generated from the following file:
fltk-1.3.0rc3/FL/Fl_Help_View.H