SfR Fresh Dox - fltk: Fl_Menu_Item Struct Reference
Fl_Menu_Item Struct Reference
#include <Fl_Menu_Item.H>
Public Member Functions
const Fl_Menu_Item * next (int=1) const
Fl_Menu_Item * next (int i=1)
const Fl_Menu_Item * first () const
Fl_Menu_Item * first ()
const char * label () const
void label (const char *a)
void label (Fl_Labeltype a, const char *b)
Fl_Labeltype labeltype () const
void labeltype (Fl_Labeltype a)
Fl_Color labelcolor () const
void labelcolor (Fl_Color a)
Fl_Font labelfont () const
void labelfont (Fl_Font a)
Fl_Fontsize labelsize () const
void labelsize (Fl_Fontsize a)
Fl_Callback_p callback () const
void callback (Fl_Callback *c, void *p)
void callback (Fl_Callback *c)
void callback (Fl_Callback0 *c)
void callback (Fl_Callback1 *c, long p=0)
void * user_data () const
void user_data (void *v)
long argument () const
void argument (long v)
int shortcut () const
void shortcut (int s)
int submenu () const
int checkbox () const
int radio () const
int value () const
void set ()
void clear ()
void setonly ()
int visible () const
void show ()
void hide ()
int active () const
void activate ()
void deactivate ()
int activevisible () const
void image (Fl_Image *a)
void image (Fl_Image &a)
int measure (int *h, const Fl_Menu_ *) const
void draw (int x, int y, int w, int h, const Fl_Menu_ *, int t=0) const
const Fl_Menu_Item * popup (int X, int Y, const char *title=0, const Fl_Menu_Item *picked=0, const Fl_Menu_ *=0) const
const Fl_Menu_Item * pulldown (int X, int Y, int W, int H, const Fl_Menu_Item *picked=0, const Fl_Menu_ *=0, const Fl_Menu_Item *title=0, int menubar=0) const
const Fl_Menu_Item * test_shortcut () const
const Fl_Menu_Item * find_shortcut (int *ip=0, const bool require_alt=false) const
void do_callback (Fl_Widget *o) const
void do_callback (Fl_Widget *o, void *arg) const
void do_callback (Fl_Widget *o, long arg) const
int checked () const
void check ()
void uncheck ()
int insert (int, const char *, int, Fl_Callback *, void *=0, int=0)
int add (const char *, int shortcut, Fl_Callback *, void *=0, int=0)
int add (const char *a, const char *b, Fl_Callback *c, void *d=0, int e=0)
int size () const
Public Attributes
const char * text
menu item text, returned by label()
int shortcut_
menu item shortcut
Fl_Callback * callback_
menu item callback
void * user_data_
menu item user_data for the menu's callback
int flags
menu item flags like FL_MENU_TOGGLE, FL_MENU_RADIO
uchar labeltype_
how the menu item text looks like
Fl_Font labelfont_
which font for this menu item text
Fl_Fontsize labelsize_
size of menu item text
Fl_Color labelcolor_
menu item text color
Detailed Description
The Fl_Menu_Item structure defines a single menu item that is used by the Fl_Menu_ class.
  struct Fl_Menu_Item {
   const char*          text;     // label()
   ulong                shortcut_;
   Fl_Callback*         callback_;
   void*                user_data_;
   int                  flags;
   uchar                labeltype_;
   uchar                labelfont_;
   uchar                labelsize_;
   uchar                labelcolor_;
  };
  enum { // values for flags:
   FL_MENU_INACTIVE     = 1,      // Deactivate menu item (gray out)
   FL_MENU_TOGGLE       = 2,      // Item is a checkbox toggle (shows checkbox for on/off state)
   FL_MENU_VALUE        = 4,      // The on/off state for checkbox/radio buttons (if set, state is 'on')
   FL_MENU_RADIO        = 8,      // Item is a radio button (one checkbox of many can be on)
   FL_MENU_INVISIBLE    = 0x10,   // Item will not show up (shortcut will work)
   FL_SUBMENU_POINTER   = 0x20,   // Indicates user_data() is a pointer to another menu array
   FL_SUBMENU           = 0x40,   // This item is a submenu to other items
   FL_MENU_DIVIDER      = 0x80,   // Creates divider line below this item. Also ends a group of radio buttons.
   FL_MENU_HORIZONTAL   = 0x100   // ??? -- reserved
  };
Typically menu items are statically defined; for example:
  Fl_Menu_Item popup[] = {
   {"&alpha",   FL_ALT+'a', the_cb, (void*)1},
   {"&beta",    FL_ALT+'b', the_cb, (void*)2},
   {"gamma",    FL_ALT+'c', the_cb, (void*)3, FL_MENU_DIVIDER},
   {"&strange",  0,   strange_cb},
   {"&charm",    0,   charm_cb},
   {"&truth",    0,   truth_cb},
   {"b&eauty",   0,   beauty_cb},
   {"sub&menu",  0,   0, 0, FL_SUBMENU},
   {"one"},
   {"two"},
   {"three"},
   {0},
   {"inactive", FL_ALT+'i', 0, 0, FL_MENU_INACTIVE|FL_MENU_DIVIDER},
   {"invisible",FL_ALT+'i', 0, 0, FL_MENU_INVISIBLE},
   {"check",    FL_ALT+'i', 0, 0, FL_MENU_TOGGLE|FL_MENU_VALUE},
   {"box",      FL_ALT+'i', 0, 0, FL_MENU_TOGGLE},
   {0}};
produces:
A submenu title is identified by the bit FL_SUBMENU in the flags field, and ends with a label() that is NULL. You can nest menus to any depth. A pointer to the first item in the submenu can be treated as an Fl_Menu array itself. It is also possible to make separate submenu arrays with FL_SUBMENU_POINTER flags.
You should use the method functions to access structure members and not access them directly to avoid compatibility problems with future releases of FLTK.
Definition at line 118 of file Fl_Menu_Item.H.
Member Function Documentation
void Fl_Menu_Item::activate () [inline]
Allows a menu item to be picked.
Definition at line 343 of file Fl_Menu_Item.H.
References FL_MENU_INACTIVE, and flags.
Referenced by Fl_Choice::draw(), redo_cb(), set_modflag(), undo_cb(), and undo_checkpoint().
int Fl_Menu_Item::active () const [inline]
Gets whether or not the item can be picked.
Definition at line 340 of file Fl_Menu_Item.H.
References FL_MENU_INACTIVE, and flags.
Referenced by draw(), and Fl_Choice::draw().
int Fl_Menu_Item::activevisible () const [inline]
Returns non 0 if FL_INACTIVE and FL_INVISIBLE are cleared, 0 otherwise.
Definition at line 350 of file Fl_Menu_Item.H.
References FL_MENU_INACTIVE, FL_MENU_INVISIBLE, and flags.
Referenced by find_shortcut(), pulldown(), and test_shortcut().
int Fl_Menu_Item::add (const char * mytext, int sc, Fl_Callback * cb, void * data = 0, int myflags = 0)
Adds an item. The text is split at '/' characters to automatically produce submenus (actually a totally unnecessary feature as you can now add submenu titles directly by setting SUBMENU in the flags):
Definition at line 110 of file Fl_Menu_add.cxx.
References insert().
Referenced by Fl_Input_Choice::add().
int Fl_Menu_Item::add (const char * a, const char * b, Fl_Callback * c, void * d = 0, int e = 0) [inline]
See int add(const char*, int shortcut, Fl_Callback*, void*, int)
Definition at line 417 of file Fl_Menu_Item.H.
References fl_old_shortcut().
long Fl_Menu_Item::argument () const [inline]
Gets the user_data() argument that is sent to the callback function. For convenience you can also define the callback as taking a long argument. This method casts the stored userdata() argument to long and returns it as a long value.
Definition at line 268 of file Fl_Menu_Item.H.
Referenced by align_position_cb(), align_text_image_cb(), item_name(), item_number(), and subtype_cb().
void Fl_Menu_Item::argument (long v) [inline]
Sets the user_data() argument that is sent to the callback function. For convenience you can also define the callback as taking a long argument. This method casts the given argument v to void* and stores it in the menu item's userdata() member. This may not be portable to some machines.
Definition at line 276 of file Fl_Menu_Item.H.
Fl_Callback_p Fl_Menu_Item::callback () const [inline]
Returns the callback function that is set for the menu item. Each item has space for a callback function and an argument for that function. Due to back compatibility, the Fl_Menu_Item itself is not passed to the callback, instead you have to get it by calling ((Fl_Menu_*)w)->mvalue() where w is the widget argument.
Definition at line 223 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), Fl_Input_Choice::Fl_Input_Choice(), and Fl_Window_Type::handle().
void Fl_Menu_Item::callback (Fl_Callback0 * c) [inline]
Sets the menu item's callback function. This method does not set the userdata() argument.
See also:
Fl_Callback_p Fl_MenuItem::callback() const
Definition at line 243 of file Fl_Menu_Item.H.
void Fl_Menu_Item::callback (Fl_Callback * c) [inline]
Sets the menu item's callback function. This method does not set the userdata() argument.
See also:
Fl_Callback_p Fl_MenuItem::callback() const
Definition at line 236 of file Fl_Menu_Item.H.
void Fl_Menu_Item::callback (Fl_Callback * c, void * p) [inline]
Sets the menu item's callback function and userdata() argument.
See also:
Fl_Callback_p Fl_MenuItem::callback() const
Definition at line 229 of file Fl_Menu_Item.H.
void Fl_Menu_Item::callback (Fl_Callback1 * c, long p = 0) [inline]
Sets the menu item's callback function and userdata() argument. This method does not set the userdata() argument. The argument is cast to void* and stored as the userdata() for the menu item's callback function.
See also:
Fl_Callback_p Fl_MenuItem::callback() const
Definition at line 252 of file Fl_Menu_Item.H.
void Fl_Menu_Item::check () [inline]
back compatibility only
Deprecated:
.
Definition at line 408 of file Fl_Menu_Item.H.
References FL_MENU_VALUE, and flags.
int Fl_Menu_Item::checkbox () const [inline]
Returns true if a checkbox will be drawn next to this item. This is true if FL_MENU_TOGGLE or FL_MENU_RADIO is set in the flags.
Definition at line 309 of file Fl_Menu_Item.H.
References FL_MENU_TOGGLE, and flags.
int Fl_Menu_Item::checked () const [inline]
back compatibility only
Deprecated:
.
Definition at line 405 of file Fl_Menu_Item.H.
References FL_MENU_VALUE, and flags.
void Fl_Menu_Item::clear () [inline]
Turns the check or radio item "off" for the menu item.
Definition at line 326 of file Fl_Menu_Item.H.
References FL_MENU_VALUE, and flags.
Referenced by Fl_Input_Choice::clear(), and setonly().
void Fl_Menu_Item::deactivate () [inline]
Prevents a menu item from being picked. Note that this will also cause the menu item to appear grayed-out.
Definition at line 348 of file Fl_Menu_Item.H.
References FL_MENU_INACTIVE, and flags.
Referenced by Fl_Choice::draw(), redo_cb(), set_modflag(), undo_cb(), and undo_checkpoint().
void Fl_Menu_Item::do_callback (Fl_Widget * o, void * arg) const [inline]
Calls the Fl_Menu_Item item's callback, and provides the Fl_Widget argument. This call overrides the callback's second argument with the given value arg. You must first check that callback() is non-zero before calling this.
Definition at line 391 of file Fl_Menu_Item.H.
void Fl_Menu_Item::do_callback (Fl_Widget * o, long arg) const [inline]
Calls the Fl_Menu_Item item's callback, and provides the Fl_Widget argument. This call overrides the callback's second argument with the given value arg. long arg is cast to void* when calling the callback. You must first check that callback() is non-zero before calling this.
Definition at line 400 of file Fl_Menu_Item.H.
void Fl_Menu_Item::do_callback (Fl_Widget * o) const [inline]
Calls the Fl_Menu_Item item's callback, and provides the Fl_Widget argument. The callback is called with the stored user_data() as its second argument. You must first check that callback() is non-zero before calling this.
Definition at line 384 of file Fl_Menu_Item.H.
Referenced by Fl_Window_Type::handle(), and Fl_Menu_::picked().
void Fl_Menu_Item::draw (int x, int y, int w, int h, const Fl_Menu_ * m, int selected = 0) const
Draws the menu item in bounding box x,y,w,h, optionally selects the item.
Definition at line 146 of file Fl_Menu.cxx.
References active(), b, Fl_Widget::box(), Fl::box_dw(), Fl::box_dx(), Fl_Widget::color(), color(), Fl_Label::color, Fl_Label::deimage, Fl_Menu_::down_box(), Fl_Label::draw(), f, FL_ALIGN_LEFT, fl_arc(), FL_BACKGROUND2_COLOR, fl_color(), fl_color_average(), FL_COLOR_CUBE, fl_contrast(), FL_DOWN_BOX, fl_draw_box(), fl_draw_shortcut, FL_FLAT_BOX, FL_FOREGROUND_COLOR, FL_GRAY, FL_HELVETICA, fl_inactive(), fl_line(), FL_MENU_RADIO, FL_MENU_TOGGLE, FL_NORMAL_SIZE, fl_pie(), fl_rectf(), FL_ROUND_DOWN_BOX, FL_SELECTION_COLOR, FL_UP_BOX, FL_WHITE, flags, Fl_Label::font, Fl_Label::image, int, labelcolor_, labelfont_, labelsize_, labeltype_, LEADING, Fl::scheme(), Fl_Widget::selection_color(), Fl_Label::size, text, Fl_Menu_::textcolor(), Fl_Menu_::textfont(), Fl_Menu_::textsize(), Fl_Label::type, value(), and Fl_Label::value.
Referenced by Fl_Menu_Bar::draw(), and Fl_Choice::draw().
const Fl_Menu_Item * Fl_Menu_Item::find_shortcut (int * ip = 0, const bool require_alt = false) const
Search only the top level menu for a shortcut. Either &x in the label or the shortcut fields are used.
This tests the current event, which must be an FL_KEYBOARD or FL_SHORTCUT, against a shortcut value.
Parameters:
ip returns the index of the item, if ip is not NULL.
require_alt if true: match only if Alt key is pressed.
Returns:
found Fl_Menu_Item or NULL
Definition at line 1000 of file Fl_Menu.cxx.
References activevisible(), first(), m, next(), shortcut_, test_shortcut(), Fl::test_shortcut(), and text.
Referenced by Fl_Menu_Bar::handle().
Fl_Menu_Item* Fl_Menu_Item::first () [inline]
Returns the first menu item, same as next(0).
Definition at line 144 of file Fl_Menu_Item.H.
const Fl_Menu_Item* Fl_Menu_Item::first () const [inline]
Returns the first menu item, same as next(0).
Definition at line 141 of file Fl_Menu_Item.H.
Referenced by menuwindow::find_selected(), find_shortcut(), menuwindow::menuwindow(), test_shortcut(), and menuwindow::titlex().
void Fl_Menu_Item::hide () [inline]
Hides an item in the menu.
Definition at line 337 of file Fl_Menu_Item.H.
References FL_MENU_INVISIBLE, and flags.
Referenced by load_history(), and update_history().
void Fl_Menu_Item::image (Fl_Image * a) [inline]
compatibility api for FLUID, same as a->label(this)
Definition at line 355 of file Fl_Menu_Item.H.
References Fl_Image::label().
void Fl_Menu_Item::image (Fl_Image & a) [inline]
compatibility api for FLUID, same as a.label(this)
Definition at line 358 of file Fl_Menu_Item.H.
References Fl_Image::label().
int Fl_Menu_Item::insert (int index, const char * mytext, int sc, Fl_Callback * cb, void * data = 0, int myflags = 0)
Inserts an item at position index.
If index is -1, the item is added the same way as Fl_Menu_Item::add().
If 'mytext' contains any un-escaped front slashes (/), it's assumed a menu pathname is being specified, and the value of index will be ignored.
In all other aspects, the behavior of insert() is the same as add().
Parameters:
index insert new items here
mytext new label string, details see above
sc keyboard shortcut for new item
cb callback function for new item
data user data for new item
myflags menu flags as described in FL_Menu_Item
Returns:
the index into the menu() array, where the entry was added
Definition at line 141 of file Fl_Menu_add.cxx.
References buf, callback_, data, FL_MENU_DIVIDER, FL_SUBMENU, flags, next(), shortcut_, size(), text, and user_data_.
Referenced by add(), and Fl_Menu_::insert().
void Fl_Menu_Item::label (Fl_Labeltype a, const char * b) [inline]
See const char* Fl_Menu_Item::label() const
Definition at line 160 of file Fl_Menu_Item.H.
References b.
const char* Fl_Menu_Item::label () const [inline]
Returns the title of the item. A NULL here indicates the end of the menu (or of a submenu). A '&' in the item will print an underscore under the next letter, and if the menu is popped up that letter will be a "shortcut" to pick that item. To get a real '&' put two in a row.
Definition at line 154 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), fill_in_New_Menu(), Fl_Menu_::find_index(), Fl_Window_Type::fix_overlay(), item_name(), item_number(), Fl_Menu_::item_pathname(), Fl_Pixmap::label(), Fl_Multi_Label::label(), Fl_RGB_Image::label(), Fl_Image::label(), Fl_Bitmap::label(), toggle_overlays(), toggle_sourceview_cb(), and toggle_widgetbin_cb().
void Fl_Menu_Item::label (const char * a) [inline]
See const char* Fl_Menu_Item::label() const
Definition at line 157 of file Fl_Menu_Item.H.
void Fl_Menu_Item::labelcolor (Fl_Color a) [inline]
Sets the menu item's label color.
See also:
Fl_Color Fl_Menu_Item::labelcolor() const
Definition at line 193 of file Fl_Menu_Item.H.
Fl_Color Fl_Menu_Item::labelcolor () const [inline]
Gets the menu item's label color. This color is passed to the labeltype routine, and is typically the color of the label text. This defaults to FL_BLACK. If this color is not black fltk will not use overlay bitplanes to draw the menu - this is so that images put in the menu draw correctly.
Definition at line 187 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_Type::build_menu(), and Fl_Input_Choice_Type::build_menu().
Fl_Font Fl_Menu_Item::labelfont () const [inline]
Gets the menu item's label font. Fonts are identified by small 8-bit indexes into a table. See the enumeration list for predefined fonts. The default value is a Helvetica font. The function Fl::set_font() can define new fonts.
Definition at line 200 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_Type::build_menu(), and Fl_Input_Choice_Type::build_menu().
void Fl_Menu_Item::labelfont (Fl_Font a) [inline]
Sets the menu item's label font. Fonts are identified by small 8-bit indexes into a table. See the enumeration list for predefined fonts. The default value is a Helvetica font. The function Fl::set_font() can define new fonts.
Definition at line 208 of file Fl_Menu_Item.H.
Fl_Fontsize Fl_Menu_Item::labelsize () const [inline]
Gets the label font pixel size/height.
Definition at line 211 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_Type::build_menu(), and Fl_Input_Choice_Type::build_menu().
void Fl_Menu_Item::labelsize (Fl_Fontsize a) [inline]
Sets the label font pixel size/height.
Definition at line 214 of file Fl_Menu_Item.H.
Fl_Labeltype Fl_Menu_Item::labeltype () const [inline]
Returns the menu item's labeltype. A labeltype identifies a routine that draws the label of the widget. This can be used for special effects such as emboss, or to use the label() pointer as another form of data such as a bitmap. The value FL_NORMAL_LABEL prints the label as text.
Definition at line 169 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_Type::build_menu(), and Fl_Input_Choice_Type::build_menu().
void Fl_Menu_Item::labeltype (Fl_Labeltype a) [inline]
Sets the menu item's labeltype. A labeltype identifies a routine that draws the label of the widget. This can be used for special effects such as emboss, or to use the label() pointer as another form of data such as a bitmap. The value FL_NORMAL_LABEL prints the label as text.
Definition at line 178 of file Fl_Menu_Item.H.
int Fl_Menu_Item::measure (int * hp, const Fl_Menu_ * m) const
Measures width of label, including effect of & characters. Optionally, can get height if hp is not NULL.
Definition at line 128 of file Fl_Menu.cxx.
References Fl_Label::color, Fl_Label::deimage, fl_draw_shortcut, FL_FOREGROUND_COLOR, FL_HELVETICA, FL_MENU_RADIO, FL_MENU_TOGGLE, FL_NORMAL_SIZE, flags, Fl_Label::font, h, Fl_Label::image, labelfont_, labelsize_, labeltype_, Fl_Label::measure(), Fl_Label::size, text, Fl_Menu_::textfont(), Fl_Menu_::textsize(), Fl_Label::type, Fl_Label::value, and w.
Referenced by Fl_Menu_Bar::draw(), menuwindow::find_selected(), menuwindow::menuwindow(), and menuwindow::titlex().
Fl_Menu_Item* Fl_Menu_Item::next (int i = 1) [inline]
Advances a pointer by n items through a menu array, skipping the contents of submenus and invisible items. There are two calls so that you can advance through const and non-const data.
Definition at line 137 of file Fl_Menu_Item.H.
References i.
const Fl_Menu_Item * Fl_Menu_Item::next (int n = 1) const
Advance a pointer by n items through a menu array, skipping the contents of submenus and invisible items. There are two calls so that you can advance through const and non-const data.
Definition at line 61 of file Fl_Menu.cxx.
References FL_SUBMENU, flags, m, text, and visible().
Referenced by Fl_Menu_Bar::draw(), menuwindow::find_selected(), find_shortcut(), insert(), menuwindow::menuwindow(), Fl_Menu_::remove(), test_shortcut(), and menuwindow::titlex().
const Fl_Menu_Item * Fl_Menu_Item::popup (int X, int Y, const char * title = 0, const Fl_Menu_Item * picked = 0, const Fl_Menu_ * button = 0) const
This method is called by widgets that want to display menus.
The menu stays up until the user picks an item or dismisses it. The selected item (or NULL if none) is returned. This does not do the callbacks or change the state of check or radio items.
X,Y is the position of the mouse cursor, relative to the window that got the most recent event (usually you can pass Fl::event_x() and Fl::event_y() unchanged here).
title is a character string title for the menu. If non-zero a small box appears above the menu with the title in it.
The menu is positioned so the cursor is centered over the item picked. This will work even if picked is in a submenu. If picked is zero or not in the menu item table the menu is positioned with the cursor in the top-left corner.
button is a pointer to an Fl_Menu_ from which the color and boxtypes for the menu are pulled. If NULL then defaults are used.
Definition at line 977 of file Fl_Menu.cxx.
References pulldown(), and text.
Referenced by Fl_Window_Type::handle(), and Fl_Menu_Button::popup().
const Fl_Menu_Item * Fl_Menu_Item::pulldown (int X, int Y, int W, int H, const Fl_Menu_Item * initial_item = 0, const Fl_Menu_ * pbutton = 0, const Fl_Menu_Item * t = 0, int menubar = 0) const
Pulldown() is similar to popup(), but a rectangle is provided to position the menu. The menu is made at least W wide, and the picked item is centered over the rectangle (like Fl_Choice uses). If picked is zero or not found, the menu is aligned just below the rectangle (like a pulldown menu).
The title and menubar arguments are used internally by the Fl_Menu_Bar widget.
Definition at line 803 of file Fl_Menu.cxx.
References activevisible(), menuwindow::autoscroll(), Fl_Group::current(), menustate::current_item, DONE_STATE, dx, dy, Fl::event_x(), Fl::event_x_root(), Fl::event_y(), Fl::event_y_root(), menustate::fakemenu, FL_DRAG, FL_SUBMENU, flags, Fl::grab(), Fl_Widget::h(), menuwindow::handle(), Fl_Menu_Window::hide(), INITIAL_STATE, menustate::item_number, menuwindow::itemheight, m, menuwindow::menu, menustate::menu_number, menustate::menubar, menustate::nummenus, menustate::p, menuwindow::position(), menuwindow::selected, menuwindow::set_selected(), Fl_Menu_Window::show(), Fl_Window::shown(), menustate::state, submenu(), menuwindow::title, menuwindow::titlex(), user_data_, Fl_Widget::w(), w, Fl::wait(), Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by Fl_Menu_Bar::handle(), Fl_Choice::handle(), Fl_Menu_Button::popup(), and popup().
int Fl_Menu_Item::radio () const [inline]
Returns true if this item is a radio item. When a radio button is selected all "adjacent" radio buttons are turned off. A set of radio items is delimited by an item that has radio() false, or by an item with FL_MENU_DIVIDER turned on.
Definition at line 316 of file Fl_Menu_Item.H.
References FL_MENU_RADIO, and flags.
Referenced by HandleMenu(), Fl_Menu_::picked(), and setonly().
void Fl_Menu_Item::set () [inline]
Turns the check or radio item "on" for the menu item. Note that this does not turn off any adjacent radio items like set_only() does.
Definition at line 323 of file Fl_Menu_Item.H.
References FL_MENU_VALUE, and flags.
void Fl_Menu_Item::setonly ()
Turns the radio item "on" for the menu item and turns off adjacent radio items set.
Definition at line 288 of file Fl_Menu_.cxx.
References clear(), FL_MENU_DIVIDER, FL_MENU_RADIO, FL_MENU_VALUE, flags, radio(), and text.
void Fl_Menu_Item::shortcut (int s) [inline]
Sets exactly what key combination will trigger the menu item. The value is a logical 'or' of a key and a set of shift flags, for instance FL_ALT+'a' or FL_ALT+FL_F+10 or just 'a'. A value of zero disables the shortcut.
The key can be any value returned by Fl::event_key(), but will usually be an ASCII letter. Use a lower-case letter unless you require the shift key to be held down.
The shift flags can be any set of values accepted by Fl::event_state(). If the bit is on that shift key must be pushed. Meta, Alt, Ctrl, and Shift must be off if they are not in the shift flags (zero for the other bits indicates a "don't care" setting).
Definition at line 296 of file Fl_Menu_Item.H.
int Fl_Menu_Item::shortcut () const [inline]
Gets what key combination shortcut will trigger the menu item.
Definition at line 279 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), and Fl_Menu_::shortcut().
void Fl_Menu_Item::show () [inline]
Makes an item visible in the menu.
Definition at line 334 of file Fl_Menu_Item.H.
References FL_MENU_INVISIBLE, and flags.
int Fl_Menu_Item::size () const
Size of the menu starting from this menu item
Definition at line 42 of file Fl_Menu.cxx.
References FL_SUBMENU, flags, m, and text.
Referenced by Fl_Menu_::copy(), insert(), and Fl_Menu_::size().
int Fl_Menu_Item::submenu () const [inline]
Returns true if either FL_SUBMENU or FL_SUBMENU_POINTER is on in the flags. FL_SUBMENU indicates an embedded submenu that goes from the next item through the next one with a NULL label(). FL_SUBMENU_POINTER indicates that user_data() is a pointer to another menu array.
Definition at line 304 of file Fl_Menu_Item.H.
References FL_SUBMENU, FL_SUBMENU_POINTER, and flags.
Referenced by Fl_Menu_Bar::handle(), Fl_Choice::handle(), Fl_Menu_::item_pathname(), pulldown(), and test_shortcut().
const Fl_Menu_Item * Fl_Menu_Item::test_shortcut () const
This is designed to be called by a widgets handle() method in response to a FL_SHORTCUT event. If the current event matches one of the items shortcut, that item is returned. If the keystroke does not match any shortcuts then NULL is returned. This only matches the shortcut() fields, not the letters in the title preceeded by '
Definition at line 1024 of file Fl_Menu.cxx.
References activevisible(), first(), FL_SUBMENU, flags, next(), shortcut_, submenu(), test_shortcut(), Fl::test_shortcut(), text, and user_data_.
Referenced by find_shortcut(), Fl_Choice::handle(), Fl_Window_Type::handle(), and test_shortcut().
void Fl_Menu_Item::uncheck () [inline]
back compatibility only
Deprecated:
.
Definition at line 411 of file Fl_Menu_Item.H.
References FL_MENU_VALUE, and flags.
void* Fl_Menu_Item::user_data () const [inline]
Gets the user_data() argument that is sent to the callback function.
Definition at line 257 of file Fl_Menu_Item.H.
Referenced by align_position_cb(), align_text_image_cb(), Fl_Input_Choice_Type::click_test(), Fl_Menu_Type::click_test(), fill_in_New_Menu(), Fl_Type_make(), print_cb(), print_load(), print_update_status(), and Fl_PostScript_Printer::start_job().
void Fl_Menu_Item::user_data (void * v) [inline]
Sets the user_data() argument that is sent to the callback function.
Definition at line 261 of file Fl_Menu_Item.H.
int Fl_Menu_Item::value () const [inline]
Returns the current value of the check or radio item.
Definition at line 318 of file Fl_Menu_Item.H.
References FL_MENU_VALUE, and flags.
Referenced by draw(), Fl_Menu_::picked(), and Fl_Input_Choice::value().
int Fl_Menu_Item::visible () const [inline]
Gets the visibility of an item.
Definition at line 331 of file Fl_Menu_Item.H.
References FL_MENU_INVISIBLE, and flags.
Referenced by next().
Member Data Documentation
Fl_Callback* Fl_Menu_Item::callback_
menu item callback
Definition at line 121 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_::copy(), Fl_Menu_::find_item(), insert(), and Fl_Menu_::picked().
int Fl_Menu_Item::flags
menu item flags like FL_MENU_TOGGLE, FL_MENU_RADIO
Definition at line 123 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_Type::build_menu(), Fl_Input_Choice_Type::build_menu(), Fl_Input_Choice_Type::click_test(), Fl_Menu_Type::click_test(), Fl_Menu_Bar::draw(), draw(), Fl_Menu_::find_index(), HandleMenu(), insert(), load_history(), measure(), menuwindow::menuwindow(), Fl_Menu_::mode(), next(), Fl_Menu_::picked(), pulldown(), setonly(), size(), test_shortcut(), and update_history().
Fl_Color Fl_Menu_Item::labelcolor_
menu item text color
Definition at line 127 of file Fl_Menu_Item.H.
Referenced by draw(), Fl_Choice::draw(), menutitle::menutitle(), and menuwindow::menuwindow().
Fl_Font Fl_Menu_Item::labelfont_
which font for this menu item text
Definition at line 125 of file Fl_Menu_Item.H.
Referenced by draw(), Fl_Choice::draw(), and measure().
Fl_Fontsize Fl_Menu_Item::labelsize_
size of menu item text
Definition at line 126 of file Fl_Menu_Item.H.
Referenced by draw(), Fl_Choice::draw(), and measure().
uchar Fl_Menu_Item::labeltype_
how the menu item text looks like
Definition at line 124 of file Fl_Menu_Item.H.
Referenced by draw(), Fl_Choice::draw(), measure(), menutitle::menutitle(), and menuwindow::menuwindow().
int Fl_Menu_Item::shortcut_
menu item shortcut
Definition at line 120 of file Fl_Menu_Item.H.
Referenced by find_shortcut(), insert(), menuwindow::menuwindow(), and test_shortcut().
const char* Fl_Menu_Item::text
menu item text, returned by label()
Definition at line 119 of file Fl_Menu_Item.H.
Referenced by align_position_cb(), align_text_image_cb(), Fl_Menu_Bar::draw(), draw(), Fl_Choice::draw(), fill_in_New_Menu(), menuwindow::find_selected(), find_shortcut(), HandleMenu(), insert(), measure(), menuwindow::menuwindow(), next(), popup(), Fl_Menu_::remove(), Fl_Menu_::replace(), setonly(), size(), test_shortcut(), Fl_Menu_::text(), and Fl_Input_Choice::value().
void* Fl_Menu_Item::user_data_
menu item user_data for the menu's callback
Definition at line 122 of file Fl_Menu_Item.H.
Referenced by Fl_Menu_::copy(), insert(), pulldown(), and test_shortcut().
The documentation for this struct was generated from the following files:
fltk-1.3.0rc3/FL/Fl_Menu_Item.H
fltk-1.3.0rc3/src/Fl_Menu.cxx
fltk-1.3.0rc3/src/Fl_Menu_.cxx
fltk-1.3.0rc3/src/Fl_Menu_add.cxx