SfR Fresh Dox - fltk: Fl_Help_Font_Style Struct Reference
Fl_Help_Font_Style Struct Reference
#include <Fl_Help_View.H>
Public Member Functions
void get (Fl_Font &afont, Fl_Fontsize &asize, Fl_Color &acolor)
Gets current font attributes.
void set (Fl_Font afont, Fl_Fontsize asize, Fl_Color acolor)
Sets current font attributes.
Fl_Help_Font_Style (Fl_Font afont, Fl_Fontsize asize, Fl_Color acolor)
Fl_Help_Font_Style ()
Public Attributes
Fl_Font f
Font.
Fl_Fontsize s
Font Size.
Fl_Color c
Font Color.
Detailed Description
Fl_Help_View font stack element definition.
Definition at line 92 of file Fl_Help_View.H.
Constructor & Destructor Documentation
Fl_Help_Font_Style::Fl_Help_Font_Style (Fl_Font afont, Fl_Fontsize asize, Fl_Color acolor) [inline]
Definition at line 98 of file Fl_Help_View.H.
Fl_Help_Font_Style::Fl_Help_Font_Style () [inline]
Definition at line 99 of file Fl_Help_View.H.
Member Function Documentation
void Fl_Help_Font_Style::get (Fl_Font & afont, Fl_Fontsize & asize, Fl_Color & acolor) [inline]
Gets current font attributes.
Definition at line 96 of file Fl_Help_View.H.
References c, f, and s.
Referenced by Fl_Help_Font_Stack::top().
void Fl_Help_Font_Style::set (Fl_Font afont, Fl_Fontsize asize, Fl_Color acolor) [inline]
Sets current font attributes.
Definition at line 97 of file Fl_Help_View.H.
References c, f, and s.
Referenced by Fl_Help_Font_Stack::init(), and Fl_Help_Font_Stack::push().
Member Data Documentation
Fl_Color Fl_Help_Font_Style::c
Font Color.
Definition at line 95 of file Fl_Help_View.H.
Referenced by get(), and set().
Fl_Font Fl_Help_Font_Style::f
Font.
Definition at line 93 of file Fl_Help_View.H.
Referenced by get(), and set().
Fl_Fontsize Fl_Help_Font_Style::s
Font Size.
Definition at line 94 of file Fl_Help_View.H.
Referenced by get(), and set().
The documentation for this struct was generated from the following file:
fltk-1.3.0rc3/FL/Fl_Help_View.H