SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/template_panel.h File Reference
template_panel.h File Reference
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
Functions
Fl_Double_Window * make_template_panel ()
void template_clear ()
void template_delete_cb (Fl_Button *, void *)
void template_load ()
Variables
Fl_Double_Window * template_panel
Fl_Browser * template_browser
Fl_Box * template_preview
Fl_Input * template_name
Fl_Input * template_instance
Fl_Button * template_delete
Fl_Return_Button * template_submit
Function Documentation
Fl_Double_Window* make_template_panel ()
Definition at line 144 of file template_panel.cxx.
References Fl_Widget::align(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Group::current(), Fl_Group::end(), FL_ALIGN_INSIDE, FL_ALIGN_TOP_LEFT, FL_THIN_DOWN_BOX, Fl_Widget::hide(), Fl_Widget::labelfont(), Fl_Group::resizable(), Fl_Window::set_modal(), template_delete_cb(), template_panel, Fl_Input_::textfont(), Fl_Widget::type(), and Fl_Widget::when().
Referenced by new_cb(), and save_template_cb().
void template_clear ()
Definition at line 191 of file template_panel.cxx.
References Fl_Browser::clear(), Fl_Browser::data(), Fl_Browser_::deselect(), i, NULL, and Fl_Browser::size().
Referenced by new_cb(), and save_template_cb().
void template_delete_cb (Fl_Button * , void *)
Definition at line 203 of file template_panel.cxx.
References Fl_Browser::data(), Fl_Widget::do_callback(), fl_alert(), fl_choice(), name, Fl_Browser::remove(), Fl_Browser::text(), and Fl_Browser::value().
Referenced by make_template_panel().
void template_load ()
Definition at line 223 of file template_panel.cxx.
References Fl_Browser::add(), dirent, fl_filename_list(), fl_filename_match(), Fl_Preferences::getUserdataPath(), i, name, ptr, snprintf, strlcat, and strlcpy.
Referenced by new_cb(), and save_template_cb().
Variable Documentation
Fl_Browser* template_browser
Definition at line 59 of file template_panel.cxx.
Referenced by new_cb(), and save_template_cb().
Fl_Button* template_delete
Definition at line 121 of file template_panel.cxx.
Referenced by new_cb(), and save_template_cb().
Fl_Input* template_instance
Definition at line 119 of file template_panel.cxx.
Referenced by new_cb(), and save_template_cb().
Fl_Input* template_name
Definition at line 110 of file template_panel.cxx.
Referenced by new_cb(), and save_template_cb().
Fl_Double_Window* template_panel
Definition at line 46 of file template_panel.cxx.
Referenced by make_template_panel(), new_cb(), and save_template_cb().
Fl_Box* template_preview
Definition at line 108 of file template_panel.cxx.
Fl_Return_Button* template_submit
Definition at line 134 of file template_panel.cxx.
Referenced by new_cb(), and save_template_cb().