SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/xutf8/ucs2fontmap.c File Reference
ucs2fontmap.c File Reference
#include <stdlib.h>
#include <string.h>
#include "lcUniConv/cp936ext.h"
#include "lcUniConv/big5.h"
#include "lcUniConv/gb2312.h"
#include "lcUniConv/iso8859_10.h"
#include "lcUniConv/iso8859_11.h"
#include "lcUniConv/iso8859_13.h"
#include "lcUniConv/iso8859_14.h"
#include "lcUniConv/iso8859_15.h"
#include "lcUniConv/iso8859_2.h"
#include "lcUniConv/iso8859_3.h"
#include "lcUniConv/iso8859_4.h"
#include "lcUniConv/iso8859_5.h"
#include "lcUniConv/iso8859_6.h"
#include "lcUniConv/iso8859_7.h"
#include "lcUniConv/iso8859_8.h"
#include "lcUniConv/iso8859_9.h"
#include "lcUniConv/jisx0201.h"
#include "lcUniConv/jisx0208.h"
#include "lcUniConv/jisx0212.h"
#include "lcUniConv/koi8_r.h"
#include "lcUniConv/koi8_u.h"
#include "lcUniConv/ksc5601.h"
#include "lcUniConv/cp1251.h"
#include "headers/symbol_.h"
#include "headers/dingbats_.h"
Classes
struct Summary16
Defines
#define RET_ILSEQ -1
#define RET_TOOFEW(x) (-10 - x)
#define RET_TOOSMALL -2
#define conv_t void*
#define ucs4_t unsigned int
#define NEED_TOMB
Functions
int ucs2fontmap (char *s, unsigned int ucs, int enc)
int encoding_number (const char *enc)
Define Documentation
#define conv_t void*
Definition at line 32 of file ucs2fontmap.c.
#define NEED_TOMB
Definition at line 39 of file ucs2fontmap.c.
#define RET_ILSEQ -1
Definition at line 29 of file ucs2fontmap.c.
#define RET_TOOFEW (x) (-10 - x)
Definition at line 30 of file ucs2fontmap.c.
#define RET_TOOSMALL -2
Definition at line 31 of file ucs2fontmap.c.
#define ucs4_t unsigned int
Definition at line 33 of file ucs2fontmap.c.
Function Documentation
int encoding_number (const char * enc)
Definition at line 311 of file ucs2fontmap.c.
int ucs2fontmap (char * s, unsigned int ucs, int enc)
Definition at line 69 of file ucs2fontmap.c.
References NULL.
Referenced by XGetUtf8FontAndGlyph(), XUtf8DrawRtlString(), XUtf8DrawString(), XUtf8TextWidth(), and XUtf8UcsWidth().