SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/undo.cxx File Reference
undo.cxx File Reference
#include <FL/Fl.H>
#include "Fl_Type.h"
#include "undo.h"
#include <FL/Fl_Preferences.H>
#include <FL/filename.H>
#include "../src/flstring.h"
#include <unistd.h>
Defines
#define UNDO_ITEM 25
#define REDO_ITEM 26
Functions
void redo_cb (Fl_Widget *, void *)
void undo_cb (Fl_Widget *, void *)
void undo_checkpoint ()
void undo_clear ()
void undo_resume ()
void undo_suspend ()
Variables
Fl_Preferences fluid_prefs
Fl_Menu_Item Main_Menu []
int undo_current = 0
int undo_last = 0
int undo_max = 0
int undo_save = -1
Define Documentation
#define REDO_ITEM 26
Definition at line 52 of file undo.cxx.
Referenced by redo_cb(), undo_cb(), and undo_checkpoint().
#define UNDO_ITEM 25
Definition at line 51 of file undo.cxx.
Referenced by redo_cb(), undo_cb(), and undo_checkpoint().
Function Documentation
void redo_cb (Fl_Widget * , void *)
Definition at line 83 of file undo.cxx.
References Fl_Menu_Item::activate(), Fl_Menu_Item::deactivate(), FL_PATH_MAX, read_file(), REDO_ITEM, set_modflag(), undo_current, UNDO_ITEM, undo_last, undo_resume(), undo_save, and undo_suspend().
void undo_cb (Fl_Widget * , void *)
Definition at line 106 of file undo.cxx.
References Fl_Menu_Item::activate(), Fl_Menu_Item::deactivate(), FL_PATH_MAX, read_file(), REDO_ITEM, set_modflag(), undo_current, UNDO_ITEM, undo_last, undo_resume(), undo_save, undo_suspend(), and write_file().
void undo_checkpoint ()
Definition at line 134 of file undo.cxx.
References Fl_Menu_Item::activate(), Fl_Menu_Item::deactivate(), FL_PATH_MAX, modflag, REDO_ITEM, undo_current, UNDO_ITEM, undo_last, undo_max, undo_save, and write_file().
Referenced by Fl_Type::add(), align_widget_cb(), cut_cb(), delete_cb(), duplicate_cb(), i18n_int_cb(), i18n_text_cb(), i18n_type_cb(), Fl_Window_Type::moveallchildren(), open_cb(), paste_cb(), storestring(), type_make_cb(), and widget_size_cb().
void undo_clear ()
Definition at line 165 of file undo.cxx.
References FL_PATH_MAX, i, modflag, undo_current, undo_last, undo_max, and undo_save.
Referenced by exit_cb(), main(), new_cb(), open_cb(), open_history_cb(), and revert_cb().
void undo_resume ()
Definition at line 181 of file undo.cxx.
Referenced by duplicate_cb(), main(), new_cb(), open_cb(), open_history_cb(), paste_cb(), redo_cb(), revert_cb(), and undo_cb().
void undo_suspend ()
Definition at line 186 of file undo.cxx.
Referenced by duplicate_cb(), main(), new_cb(), open_cb(), open_history_cb(), paste_cb(), redo_cb(), revert_cb(), and undo_cb().
Variable Documentation
Fl_Preferences fluid_prefs
Fl_Menu_Item Main_Menu[]
Definition at line 1589 of file fluid.cxx.
int undo_current = 0
Definition at line 63 of file undo.cxx.
Referenced by redo_cb(), save_cb(), type_make_cb(), undo_cb(), undo_checkpoint(), and undo_clear().
int undo_last = 0
Definition at line 64 of file undo.cxx.
Referenced by redo_cb(), type_make_cb(), undo_cb(), undo_checkpoint(), and undo_clear().
int undo_max = 0
Definition at line 65 of file undo.cxx.
Referenced by undo_checkpoint(), and undo_clear().
int undo_save = -1
Definition at line 66 of file undo.cxx.
Referenced by redo_cb(), save_cb(), undo_cb(), undo_checkpoint(), and undo_clear().