SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/xutf8/utf8Utils.c File Reference
utf8Utils.c File Reference
#include "../../FL/Xutf8.h"
Functions
int XConvertUtf8ToUcs (const unsigned char *buf, int len, unsigned int *ucs)
int XConvertUcsToUtf8 (unsigned int ucs, char *buf)
int XUtf8CharByteLen (const unsigned char *buf, int len)
int XCountUtf8Char (const unsigned char *buf, int len)
int XFastConvertUtf8ToUcs (const unsigned char *buf, int len, unsigned int *ucs)
Function Documentation
int XConvertUcsToUtf8 (unsigned int ucs, char * buf)
Definition at line 112 of file utf8Utils.c.
Referenced by XConvertBig5ToUtf8(), XConvertCp936extToUtf8(), XConvertEucCnToUtf8(), XConvertEucJpToUtf8(), XConvertEucKrToUtf8(), XConvertEucTwToUtf8(), XConvertGb2312ToUtf8(), and XUtf8LookupString().
int XConvertUtf8ToUcs (const unsigned char * buf, int len, unsigned int * ucs)
Definition at line 42 of file utf8Utils.c.
References int.
Referenced by XUtf8CharByteLen().
int XCountUtf8Char (const unsigned char * buf, int len)
Definition at line 160 of file utf8Utils.c.
References i, and XUtf8CharByteLen().
int XFastConvertUtf8ToUcs (const unsigned char * buf, int len, unsigned int * ucs)
Definition at line 178 of file utf8Utils.c.
References int.
Referenced by XUtf8DrawRtlString(), XUtf8DrawString(), and XUtf8TextWidth().
int XUtf8CharByteLen (const unsigned char * buf, int len)
Definition at line 150 of file utf8Utils.c.
References XConvertUtf8ToUcs().
Referenced by XCountUtf8Char().