SfR Fresh Dox - fltk: fltk-1.3.0rc3/src/xutf8/utf8Input.c File Reference
utf8Input.c File Reference
#include <config.h>
#include "../../FL/Xutf8.h"
#include <X11/X.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <string.h>
#include <stdlib.h>
#include "lcUniConv/big5.h"
#include "lcUniConv/gb2312.h"
#include "lcUniConv/cp936ext.h"
#include "lcUniConv/jisx0201.h"
#include "lcUniConv/jisx0208.h"
#include "lcUniConv/jisx0212.h"
#include "lcUniConv/ksc5601.h"
Classes
struct Summary16
Defines
#define RET_ILSEQ -1
#define RET_TOOFEW(x) (-10 - x)
#define RET_TOOSMALL -2
#define conv_t void*
#define ucs4_t unsigned int
#define NEED_TOWC
Functions
int XConvertEucTwToUtf8 (char *buffer_return, int len)
int XConvertEucKrToUtf8 (char *buffer_return, int len)
int XConvertBig5ToUtf8 (char *buffer_return, int len)
int XConvertCp936extToUtf8 (char *buffer_return, int len)
int XConvertGb2312ToUtf8 (char *buffer_return, int len)
int XConvertEucCnToUtf8 (char *buffer_return, int len)
int XConvertEucJpToUtf8 (char *buffer_return, int len)
int XConvertEucToUtf8 (const char *locale, char *buffer_return, int len, int bytes_buffer)
int XUtf8LookupString (XIC ic, XKeyPressedEvent *event, char *buffer_return, int bytes_buffer, KeySym *keysym, Status *status_return)
Define Documentation
#define conv_t void*
Definition at line 48 of file utf8Input.c.
#define NEED_TOWC
Definition at line 55 of file utf8Input.c.
#define RET_ILSEQ -1
Definition at line 45 of file utf8Input.c.
#define RET_TOOFEW (x) (-10 - x)
Definition at line 46 of file utf8Input.c.
#define RET_TOOSMALL -2
Definition at line 47 of file utf8Input.c.
#define ucs4_t unsigned int
Definition at line 49 of file utf8Input.c.
Function Documentation
int XConvertBig5ToUtf8 (char * buffer_return, int len)
Definition at line 167 of file utf8Input.c.
References b, buf, i, NULL, and XConvertUcsToUtf8().
Referenced by XConvertEucToUtf8().
int XConvertCp936extToUtf8 (char * buffer_return, int len)
Definition at line 196 of file utf8Input.c.
References b, buf, i, NULL, and XConvertUcsToUtf8().
Referenced by XConvertEucToUtf8().
int XConvertEucCnToUtf8 (char * buffer_return, int len)
Definition at line 268 of file utf8Input.c.
References b, buf, i, NULL, and XConvertUcsToUtf8().
Referenced by XConvertEucToUtf8().
int XConvertEucJpToUtf8 (char * buffer_return, int len)
Definition at line 307 of file utf8Input.c.
References b, buf, i, NULL, and XConvertUcsToUtf8().
Referenced by XConvertEucToUtf8().
int XConvertEucKrToUtf8 (char * buffer_return, int len)
Definition at line 127 of file utf8Input.c.
References b, buf, i, NULL, and XConvertUcsToUtf8().
Referenced by XConvertEucToUtf8().
int XConvertEucToUtf8 (const char * locale, char * buffer_return, int len, int bytes_buffer)
Definition at line 380 of file utf8Input.c.
References XConvertBig5ToUtf8(), XConvertCp936extToUtf8(), XConvertEucCnToUtf8(), XConvertEucJpToUtf8(), XConvertEucKrToUtf8(), XConvertEucTwToUtf8(), and XConvertGb2312ToUtf8().
Referenced by XUtf8LookupString().
int XConvertEucTwToUtf8 (char * buffer_return, int len)
Definition at line 65 of file utf8Input.c.
References b, buf, i, and XConvertUcsToUtf8().
Referenced by XConvertEucToUtf8().
int XConvertGb2312ToUtf8 (char * buffer_return, int len)
Definition at line 233 of file utf8Input.c.
References b, buf, i, NULL, and XConvertUcsToUtf8().
Referenced by XConvertEucToUtf8().
int XUtf8LookupString (XIC ic, XKeyPressedEvent * event, char * buffer_return, int bytes_buffer, KeySym * keysym, Status * status_return)
Definition at line 414 of file utf8Input.c.
References XConvertEucToUtf8(), XConvertUcsToUtf8(), and XKeysymToUcs().
Referenced by fl_handle(), and main().