SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/widget_panel.cxx File Reference
widget_panel.cxx File Reference
#include "widget_panel.h"
Functions
Fl_Double_Window * make_widget_panel ()
Variables
Fl_Menu_Item menu_ []
Fl_Menu_Item menu_1 []
Fl_Value_Input * widget_x_input = (Fl_Value_Input *)0
Fl_Value_Input * widget_y_input = (Fl_Value_Input *)0
Fl_Value_Input * widget_w_input = (Fl_Value_Input *)0
Fl_Value_Input * widget_h_input = (Fl_Value_Input *)0
Fl_Menu_Item menu_2 []
Fl_Menu_Item menu_3 []
Fl_Input * v_input [4] = {(Fl_Input *)0}
Fl_Button * wLiveMode = (Fl_Button *)0
Function Documentation
Fl_Double_Window* make_widget_panel ()
Definition at line 90 of file widget_panel.cxx.
References active_cb(), Fl_Widget::align(), align_cb(), align_position_cb(), align_text_image_cb(), border_cb(), Fl_Widget::box(), box_cb(), boxmenu, Fl_Widget::callback(), callback_cb(), cancel_cb(), Fl_Widget::color(), color2_cb(), color_cb(), Fl_Group::current(), Fl_Menu_::down_box(), down_box_cb(), Fl_Group::end(), FL_ALIGN_BOTTOM, FL_ALIGN_CENTER, FL_ALIGN_CLIP, FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_ALIGN_TOP, FL_ALIGN_TOP_LEFT, FL_ALIGN_WRAP, FL_BACKGROUND2_COLOR, FL_BORDER_BOX, FL_DOWN_BOX, FL_FOREGROUND_COLOR, FL_INACTIVE_COLOR, FL_NORMAL_LABEL, FL_SELECTION_COLOR, FL_THIN_UP_BOX, FL_WHEN_CHANGED, FL_WHEN_NEVER, FL_WHEN_RELEASE, fontmenu, Fl_Widget::h(), h_cb(), Fl_Widget::hide(), Fl_Window::hotspot(), hotspot_cb(), image_browse_cb(), image_cb(), inactive_browse_cb(), inactive_cb(), label_cb(), Fl_Widget::labelcolor(), labelcolor_cb(), Fl_Widget::labelfont(), labelfont_cb(), Fl_Widget::labelsize(), labelsize_cb(), Fl_Widget::labeltype(), labeltype_cb(), labeltypemenu, live_mode_cb(), max_cb(), max_h_cb(), max_w_cb(), Fl_Valuator::maximum(), Fl_Menu_::menu(), min_cb(), min_h_cb(), min_w_cb(), modal_cb(), name_cb(), name_public_cb(), name_public_member_cb(), non_modal_cb(), ok_cb(), overlay_cb(), propagate_load(), Fl_Group::resizable(), resizable_cb(), revert_cb(), Fl_Widget::selection_color(), set_max_size_cb(), set_min_size_cb(), shortcut_in_cb(), Fl_Window::size_range(), slider_size_cb(), Fl_Valuator::step(), step_cb(), subclass_cb(), subtype_cb(), textcolor_cb(), Fl_Text_Display::textfont(), Fl_Input_::textfont(), textfont_cb(), Fl_Text_Display::textsize(), Fl_Value_Input::textsize(), Fl_Menu_::textsize(), Fl_Input_::textsize(), textsize_cb(), Fl_Widget::tooltip(), tooltip_cb(), Fl_Widget::type(), user_data_cb(), user_data_type_cb(), v_input_cb(), Fl_Valuator::value(), value_cb(), visible_cb(), Fl_Widget::w(), w, w_cb(), wc_relative_cb(), Fl_Widget::when(), when_button_cb(), when_cb(), whenmenu, x_cb(), xclass_cb(), and y_cb().
Referenced by Fl_Widget_Type::open().
Variable Documentation
Fl_Menu_Item menu_[]
Initial value:
 {
 {"   Image Alignment   ", 0,  0, (void*)(0xFFFFFFFF), 1, FL_NORMAL_LABEL, 2, 11, 0},
 {"image over text", 0,  0, (void*)(FL_ALIGN_IMAGE_OVER_TEXT), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"text over image", 0,  0, (void*)(FL_ALIGN_TEXT_OVER_IMAGE), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"text next to image", 0,  0, (void*)(FL_ALIGN_TEXT_NEXT_TO_IMAGE), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"image next to text", 0,  0, (void*)(FL_ALIGN_IMAGE_NEXT_TO_TEXT), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"image is backdrop", 0,  0, (void*)(FL_ALIGN_IMAGE_BACKDROP), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 36 of file widget_panel.cxx.
Referenced by Fl_Input_Choice::add(), Fl_Input_Choice::clear(), Fl_Input_Choice::down_box(), Fl_Input_Choice::Fl_Input_Choice(), Fl_Menu_::menu(), Fl_Input_Choice::menu(), Fl_Input_Choice::menubutton(), Fl_Menu_::mode(), Fl_Input_Choice::resize(), Fl_Menu_::shortcut(), Fl_Menu_::text(), Fl_Menu_::value(), and Fl_Input_Choice::value().
Fl_Menu_Item menu_1[]
Initial value:
 {
 {"   Inside && Outside   ", 0,  0, (void*)(0xFFFFFFFF), 1, FL_NORMAL_LABEL, 2, 11, 0},
 {"top left", 0,  0, (void*)(FL_ALIGN_TOP_LEFT), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"top", 0,  0, (void*)(FL_ALIGN_TOP), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"top right", 0,  0, (void*)(FL_ALIGN_TOP_RIGHT), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"left", 0,  0, (void*)(FL_ALIGN_LEFT), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"center", 0,  0, (void*)(FL_ALIGN_CENTER), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"right", 0,  0, (void*)(FL_ALIGN_RIGHT), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"bottom left", 0,  0, (void*)(FL_ALIGN_BOTTOM_LEFT), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"bottom", 0,  0, (void*)(FL_ALIGN_BOTTOM), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"bottom right", 0,  0, (void*)(FL_ALIGN_BOTTOM_RIGHT), 128, FL_NORMAL_LABEL, 0, 11, 0},
 {"   Outside Alignment   ", 0,  0, (void*)(0xFFFFFFFF), 1, FL_NORMAL_LABEL, 2, 11, 0},
 {"left top", 0,  0, (void*)(FL_ALIGN_LEFT_TOP), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"right top", 0,  0, (void*)(FL_ALIGN_RIGHT_TOP), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"left bottom", 0,  0, (void*)(FL_ALIGN_LEFT_BOTTOM), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"right bottom", 0,  0, (void*)(FL_ALIGN_RIGHT_BOTTOM), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 46 of file widget_panel.cxx.
Fl_Menu_Item menu_2[]
Initial value:
 {
 {"private", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"public", 0,  0, (void*)(1), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"protected", 0,  0, (void*)(2), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 73 of file widget_panel.cxx.
Fl_Menu_Item menu_3[]
Initial value:
 {
 {"local", 0,  0, (void*)(0), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"global", 0,  0, (void*)(1), 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 80 of file widget_panel.cxx.
Fl_Input* v_input[4] = {(Fl_Input *)0}
Definition at line 86 of file widget_panel.cxx.
Fl_Value_Input* widget_h_input = (Fl_Value_Input *)0
Definition at line 71 of file widget_panel.cxx.
Fl_Value_Input* widget_w_input = (Fl_Value_Input *)0
Definition at line 69 of file widget_panel.cxx.
Fl_Value_Input* widget_x_input = (Fl_Value_Input *)0
Definition at line 65 of file widget_panel.cxx.
Fl_Value_Input* widget_y_input = (Fl_Value_Input *)0
Definition at line 67 of file widget_panel.cxx.
Fl_Button* wLiveMode = (Fl_Button *)0
Definition at line 88 of file widget_panel.cxx.
Referenced by live_mode_cb().