SfR Fresh Dox - fltk: fltk-1.3.0rc3/fluid/widget_panel.h File Reference
widget_panel.h File Reference
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Light_Button.H>
#include "Shortcut_Button.h"
#include "CodeEditor.h"
#include <FL/Fl_Return_Button.H>
Functions
void propagate_load (Fl_Group *, void *)
void label_cb (Fl_Input *, void *)
void labeltype_cb (Fl_Choice *, void *)
void image_cb (Fl_Input *, void *)
void image_browse_cb (Fl_Button *, void *)
void inactive_cb (Fl_Input *, void *)
void inactive_browse_cb (Fl_Button *, void *)
void align_cb (Fl_Button *, void *)
void align_text_image_cb (Fl_Choice *, void *)
void align_position_cb (Fl_Choice *, void *)
void x_cb (Fl_Value_Input *, void *)
void y_cb (Fl_Value_Input *, void *)
void w_cb (Fl_Value_Input *, void *)
void h_cb (Fl_Value_Input *, void *)
void wc_relative_cb (Fl_Light_Button *, void *)
void slider_size_cb (Fl_Value_Input *, void *)
void min_cb (Fl_Value_Input *, void *)
void max_cb (Fl_Value_Input *, void *)
void step_cb (Fl_Value_Input *, void *)
void value_cb (Fl_Value_Input *, void *)
void min_w_cb (Fl_Value_Input *, void *)
void min_h_cb (Fl_Value_Input *, void *)
void set_min_size_cb (Fl_Button *, void *)
void max_w_cb (Fl_Value_Input *, void *)
void max_h_cb (Fl_Value_Input *, void *)
void set_max_size_cb (Fl_Button *, void *)
void shortcut_in_cb (Shortcut_Button *, void *)
void xclass_cb (Fl_Input *, void *)
void border_cb (Fl_Light_Button *, void *)
void modal_cb (Fl_Light_Button *, void *)
void non_modal_cb (Fl_Light_Button *, void *)
void visible_cb (Fl_Light_Button *, void *)
void active_cb (Fl_Light_Button *, void *)
void resizable_cb (Fl_Light_Button *, void *)
void hotspot_cb (Fl_Light_Button *, void *)
void tooltip_cb (Fl_Input *, void *)
void labelfont_cb (Fl_Choice *, void *)
void labelsize_cb (Fl_Value_Input *, void *)
void labelcolor_cb (Fl_Button *, void *)
void box_cb (Fl_Choice *, void *)
void color_cb (Fl_Button *, void *)
void down_box_cb (Fl_Choice *, void *)
void color2_cb (Fl_Button *, void *)
void textfont_cb (Fl_Choice *, void *)
void textsize_cb (Fl_Value_Input *, void *)
void textcolor_cb (Fl_Button *, void *)
void subclass_cb (Fl_Input *, void *)
void subtype_cb (Fl_Choice *, void *)
void name_cb (Fl_Input *, void *)
void name_public_member_cb (Fl_Choice *, void *)
void name_public_cb (Fl_Choice *, void *)
void v_input_cb (Fl_Input *, void *)
void callback_cb (CodeEditor *, void *)
void user_data_cb (Fl_Input *, void *)
void when_cb (Fl_Choice *, void *)
void user_data_type_cb (Fl_Input *, void *)
void when_button_cb (Fl_Light_Button *, void *)
void overlay_cb (Fl_Button *, void *)
void revert_cb (Fl_Button *, void *)
void ok_cb (Fl_Return_Button *, void *)
void cancel_cb (Fl_Button *, void *)
void live_mode_cb (Fl_Button *, void *)
Fl_Double_Window * make_widget_panel ()
Variables
Fl_Menu_Item labeltypemenu []
Fl_Value_Input * widget_x_input
Fl_Value_Input * widget_y_input
Fl_Value_Input * widget_w_input
Fl_Value_Input * widget_h_input
Fl_Menu_Item fontmenu []
Fl_Menu_Item boxmenu []
Fl_Input * v_input [4]
Fl_Menu_Item whenmenu []
Fl_Button * wLiveMode
Fl_Menu_Item menu_ []
Fl_Menu_Item menu_1 []
Fl_Menu_Item menu_2 []
Fl_Menu_Item menu_3 []
Function Documentation
void active_cb (Fl_Light_Button * , void *)
Definition at line 942 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::active(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_window(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), and Fl_Button::value().
Referenced by make_widget_panel().
void align_cb (Fl_Button * , void *)
Definition at line 1149 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::align(), Fl_Widget::argument(), b, Fl_Button::clear(), Fl_Widget::deactivate(), Fl_Type::first, FL_ALIGN_BOTTOM, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_ALIGN_TOP, Fl_Type::is_menu_item(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Widget::user_data(), Fl_Button::value(), x, and y.
Referenced by make_widget_panel().
void align_position_cb (Fl_Choice * , void *)
Definition at line 1187 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::align(), Fl_Menu_Item::argument(), b, Fl_Widget::deactivate(), Fl_Type::first, FL_ALIGN_POSITION_MASK, Fl_Type::is_menu_item(), Fl_Menu_::menu(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Menu_Item::text, Fl_Menu_Item::user_data(), Fl_Choice::value(), x, and y.
Referenced by make_widget_panel().
void align_text_image_cb (Fl_Choice * , void *)
Definition at line 1216 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::align(), Fl_Menu_Item::argument(), b, Fl_Widget::deactivate(), Fl_Type::first, FL_ALIGN_IMAGE_MASK, Fl_Type::is_menu_item(), Fl_Menu_::menu(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Menu_Item::text, Fl_Menu_Item::user_data(), Fl_Choice::value(), x, and y.
Referenced by make_widget_panel().
void border_cb (Fl_Light_Button * , void *)
Definition at line 468 of file Fl_Window_Type.cxx.
References Fl_Widget::hide(), Fl_Type::is_window(), LOAD, Fl_Widget_Type::o, set_modflag(), Fl_Widget::show(), and Fl_Button::value().
Referenced by make_widget_panel().
void box_cb (Fl_Choice * , void *)
Definition at line 727 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::box(), Fl_Widget::deactivate(), Fl_Type::first, int, Fl_Type::is_menu_item(), m, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Choice::value(), and ZERO_ENTRY.
Referenced by make_widget_panel().
void callback_cb (CodeEditor * , void *)
Definition at line 1247 of file Fl_Widget_Type.cxx.
References Fl_Text_Display::buffer(), c_check(), Fl_Widget::callback(), Fl_Type::callback(), Fl_Type::first, fl_message(), Fl_Window::make_current(), set_modflag(), and Fl_Widget::window().
Referenced by make_widget_panel().
void cancel_cb (Fl_Button * , void *)
Definition at line 1778 of file Fl_Widget_Type.cxx.
References Fl_Window::hide(), and revert_cb().
Referenced by make_widget_panel().
void color2_cb (Fl_Button * , void *)
Definition at line 1084 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Type::first, FL_BLACK, fl_contrast(), fl_show_colormap(), Fl_Type::is_menu_item(), Fl_Widget::labelcolor(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::redraw(), Fl_Widget::selection_color(), and set_modflag().
Referenced by make_widget_panel().
void color_cb (Fl_Button * , void *)
Definition at line 1060 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Type::first, FL_BLACK, fl_contrast(), fl_show_colormap(), Fl_Type::is_menu_item(), Fl_Widget::labelcolor(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::parent(), Fl_Type::parent, Fl_Widget::redraw(), set_modflag(), tabs_type_name, and Fl_Type::type_name().
Referenced by make_widget_panel().
void down_box_cb (Fl_Choice * , void *)
Definition at line 751 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, int, Fl_Type::is_button(), Fl_Type::is_menu_button(), Fl_Type::is_menu_item(), m, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Type::type_name(), Fl_Choice::value(), and ZERO_ENTRY.
Referenced by make_widget_panel().
void h_cb (Fl_Value_Input * , void *)
Definition at line 581 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, gridx, gridy, Fl::h(), i, int, Fl_Widget_Type::is_widget(), Fl_Type::next, Fl_Widget::redraw(), Fl_Widget::resize(), set_modflag(), Fl_Valuator::value(), Fl::w(), Fl_Widget::w(), w, Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by make_widget_panel().
void hotspot_cb (Fl_Light_Button * , void *)
Definition at line 892 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), current_widget, Fl_Widget::deactivate(), Fl_Widget_Type::hotspot(), Fl_Type::is_menu_item(), Fl_Type::is_widget(), Fl_Type::is_window(), Fl_Widget::label(), Fl_Type::level, Fl_Type::next, Fl_Type::parent, Fl_Widget_Type::redraw(), set_modflag(), and Fl_Button::value().
Referenced by make_widget_panel().
void image_browse_cb (Fl_Button * , void *)
Definition at line 423 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget_Type::is_widget(), Fl_Type::is_window(), Fl_Type::next, set_modflag(), ui_find_image(), ui_find_image_name, and Fl_Input_::value().
Referenced by make_widget_panel().
void image_cb (Fl_Input * , void *)
Definition at line 404 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, i, Fl_Widget_Type::is_widget(), Fl_Type::is_window(), Fl_Type::next, set_modflag(), Fl_Input_::static_value(), and Fl_Input_::value().
Referenced by make_widget_panel().
void inactive_browse_cb (Fl_Button * , void *)
Definition at line 465 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget_Type::is_widget(), Fl_Type::is_window(), Fl_Type::next, set_modflag(), ui_find_image(), ui_find_image_name, and Fl_Input_::value().
Referenced by make_widget_panel().
void inactive_cb (Fl_Input * , void *)
Definition at line 446 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, i, Fl_Widget_Type::is_widget(), Fl_Type::is_window(), Fl_Type::next, set_modflag(), Fl_Input_::static_value(), and Fl_Input_::value().
Referenced by make_widget_panel().
void label_cb (Fl_Input * , void *)
Definition at line 382 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Type::label(), Fl_Type::next, set_modflag(), Fl_Input_::static_value(), and Fl_Input_::value().
Referenced by make_widget_panel().
void labelcolor_cb (Fl_Button * , void *)
Definition at line 1105 of file Fl_Widget_Type.cxx.
References Fl_Widget::color(), Fl_Type::first, FL_BLACK, fl_contrast(), fl_show_colormap(), Fl_Widget::labelcolor(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::redraw(), Fl_Widget_Type::redraw(), and set_modflag().
Referenced by make_widget_panel().
void labelfont_cb (Fl_Choice * , void *)
Definition at line 983 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::labelfont(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), and Fl_Choice::value().
Referenced by make_widget_panel().
void labelsize_cb (Fl_Value_Input * , void *)
Definition at line 1003 of file Fl_Widget_Type.cxx.
References Fl_Widget_Type::default_size, Fl_Type::first, int, Fl_Widget::labelsize(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void labeltype_cb (Fl_Choice * , void *)
Definition at line 1034 of file Fl_Widget_Type.cxx.
References Fl_Type::first, FL_WHEN_RELEASE, int, Fl_Widget::labeltype(), m, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), Fl_Choice::value(), and Fl_Widget::when().
Referenced by make_widget_panel().
void live_mode_cb (Fl_Button * , void *)
Todo:
live mode should end gracefully when the application quits or when the user closes the live widget
Definition at line 1790 of file Fl_Widget_Type.cxx.
References Fl_Group::add(), Fl_Widget::box(), Fl_Widget::callback(), Fl_Widget::color(), Fl_Group::current(), current_widget, Fl::delete_widget(), Fl_Group::end(), Fl_Widget_Type::enter_live_mode(), FL_FLAT_BOX, FL_GREEN, FL_NO_BOX, Fl_Widget::h(), h, Fl_Window::hide(), Fl_Type::is_window(), Fl_Widget::labelsize(), Fl_Type::leave_live_mode(), leave_live_mode_cb(), Fl_Widget::position(), Fl_Group::resizable(), Fl_Window::set_modal(), Fl_Window::show(), Fl_Window::size_range(), Fl_Window_Type::sr_max_h, Fl_Window_Type::sr_max_w, Fl_Window_Type::sr_min_h, Fl_Window_Type::sr_min_w, Fl_Button::value(), Fl_Widget::w(), w, and wLiveMode.
Referenced by leave_live_mode_cb(), and make_widget_panel().
Fl_Double_Window* make_widget_panel ()
Definition at line 90 of file widget_panel.cxx.
References active_cb(), Fl_Widget::align(), align_cb(), align_position_cb(), align_text_image_cb(), border_cb(), Fl_Widget::box(), box_cb(), boxmenu, Fl_Widget::callback(), callback_cb(), cancel_cb(), Fl_Widget::color(), color2_cb(), color_cb(), Fl_Group::current(), Fl_Menu_::down_box(), down_box_cb(), Fl_Group::end(), FL_ALIGN_BOTTOM, FL_ALIGN_CENTER, FL_ALIGN_CLIP, FL_ALIGN_INSIDE, FL_ALIGN_LEFT, FL_ALIGN_RIGHT, FL_ALIGN_TOP, FL_ALIGN_TOP_LEFT, FL_ALIGN_WRAP, FL_BACKGROUND2_COLOR, FL_BORDER_BOX, FL_DOWN_BOX, FL_FOREGROUND_COLOR, FL_INACTIVE_COLOR, FL_NORMAL_LABEL, FL_SELECTION_COLOR, FL_THIN_UP_BOX, FL_WHEN_CHANGED, FL_WHEN_NEVER, FL_WHEN_RELEASE, fontmenu, Fl_Widget::h(), h_cb(), Fl_Widget::hide(), Fl_Window::hotspot(), hotspot_cb(), image_browse_cb(), image_cb(), inactive_browse_cb(), inactive_cb(), label_cb(), Fl_Widget::labelcolor(), labelcolor_cb(), Fl_Widget::labelfont(), labelfont_cb(), Fl_Widget::labelsize(), labelsize_cb(), Fl_Widget::labeltype(), labeltype_cb(), labeltypemenu, live_mode_cb(), max_cb(), max_h_cb(), max_w_cb(), Fl_Valuator::maximum(), Fl_Menu_::menu(), min_cb(), min_h_cb(), min_w_cb(), modal_cb(), name_cb(), name_public_cb(), name_public_member_cb(), non_modal_cb(), ok_cb(), overlay_cb(), propagate_load(), Fl_Group::resizable(), resizable_cb(), revert_cb(), Fl_Widget::selection_color(), set_max_size_cb(), set_min_size_cb(), shortcut_in_cb(), Fl_Window::size_range(), slider_size_cb(), Fl_Valuator::step(), step_cb(), subclass_cb(), subtype_cb(), textcolor_cb(), Fl_Text_Display::textfont(), Fl_Input_::textfont(), textfont_cb(), Fl_Text_Display::textsize(), Fl_Value_Input::textsize(), Fl_Menu_::textsize(), Fl_Input_::textsize(), textsize_cb(), Fl_Widget::tooltip(), tooltip_cb(), Fl_Widget::type(), user_data_cb(), user_data_type_cb(), v_input_cb(), Fl_Valuator::value(), value_cb(), visible_cb(), Fl_Widget::w(), w, w_cb(), wc_relative_cb(), Fl_Widget::when(), when_button_cb(), when_cb(), whenmenu, x_cb(), xclass_cb(), and y_cb().
Referenced by Fl_Widget_Type::open().
void max_cb (Fl_Value_Input * , void *)
Definition at line 1595 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_spinner(), Fl_Type::is_valuator(), Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void max_h_cb (Fl_Value_Input * , void *)
Definition at line 1485 of file Fl_Widget_Type.cxx.
References Fl_Type::first, int, Fl_Type::is_window(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void max_w_cb (Fl_Value_Input * , void *)
Definition at line 1468 of file Fl_Widget_Type.cxx.
References Fl_Type::first, int, Fl_Type::is_window(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void min_cb (Fl_Value_Input * , void *)
Definition at line 1562 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_spinner(), Fl_Type::is_valuator(), Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void min_h_cb (Fl_Value_Input * , void *)
Definition at line 1451 of file Fl_Widget_Type.cxx.
References Fl_Type::first, int, Fl_Type::is_window(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void min_w_cb (Fl_Value_Input * , void *)
Definition at line 1433 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), int, Fl_Type::is_window(), Fl_Widget::parent(), set_modflag(), Fl_Widget::show(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void modal_cb (Fl_Light_Button * , void *)
Definition at line 446 of file Fl_Window_Type.cxx.
References Fl_Widget::hide(), Fl_Type::is_window(), LOAD, set_modflag(), Fl_Widget::show(), and Fl_Button::value().
Referenced by make_widget_panel().
void name_cb (Fl_Input * , void *)
Definition at line 311 of file Fl_Widget_Type.cxx.
References buf, Fl_Widget::hide(), Fl_Window::label(), Fl_Type::name(), Fl_Widget::show(), snprintf, Fl_Input_::static_value(), Fl_Type::title(), and Fl_Input_::value().
Referenced by make_widget_panel().
void name_public_cb (Fl_Choice * , void *)
Definition at line 360 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_in_class(), Fl_Type::next, Fl_Widget_Type::public_, redraw_browser(), set_modflag(), Fl_Widget::show(), and Fl_Choice::value().
Referenced by make_widget_panel().
void name_public_member_cb (Fl_Choice * , void *)
Definition at line 335 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_in_class(), Fl_Type::next, Fl_Widget_Type::public_, redraw_browser(), set_modflag(), Fl_Widget::show(), Fl_Choice::value(), and w.
Referenced by make_widget_panel().
void non_modal_cb (Fl_Light_Button * , void *)
Definition at line 457 of file Fl_Window_Type.cxx.
References Fl_Widget::hide(), Fl_Type::is_window(), LOAD, set_modflag(), Fl_Widget::show(), and Fl_Button::value().
Referenced by make_widget_panel().
void ok_cb (Fl_Return_Button * , void *)
Definition at line 1766 of file Fl_Widget_Type.cxx.
References Fl_Window::hide(), and set_cb().
Referenced by make_widget_panel().
void overlay_cb (Fl_Button * , void *)
Definition at line 1784 of file Fl_Widget_Type.cxx.
References toggle_overlays().
Referenced by make_widget_panel().
void propagate_load (Fl_Group * , void *)
Definition at line 1743 of file Fl_Widget_Type.cxx.
References Fl_Group::array(), Fl_Group::children(), and Fl_Widget::do_callback().
Referenced by make_widget_panel(), revert_cb(), set_max_size_cb(), and set_min_size_cb().
void resizable_cb (Fl_Light_Button * , void *)
Definition at line 880 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::is_menu_item(), Fl_Widget_Type::resizable(), set_modflag(), and Fl_Button::value().
Referenced by make_widget_panel().
void revert_cb (Fl_Button * , void *)
Definition at line 1771 of file Fl_Widget_Type.cxx.
References Fl_Type::label(), and propagate_load().
Referenced by cancel_cb(), and make_widget_panel().
void set_max_size_cb (Fl_Button * , void *)
Definition at line 1519 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::h(), Fl_Widget_Type::o, propagate_load(), set_modflag(), Fl_Window_Type::sr_max_h, Fl_Window_Type::sr_max_w, and Fl_Widget::w().
Referenced by make_widget_panel().
void set_min_size_cb (Fl_Button * , void *)
Definition at line 1502 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::h(), Fl_Widget_Type::o, propagate_load(), set_modflag(), Fl_Window_Type::sr_min_h, Fl_Window_Type::sr_min_w, and Fl_Widget::w().
Referenced by make_widget_panel().
void shortcut_in_cb (Shortcut_Button * , void *)
Definition at line 612 of file Fl_Menu_Type.cxx.
References b, current_widget, Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_button(), Fl_Type::is_input(), Fl_Type::is_text_display(), Fl_Type::is_value_input(), LOAD, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), Fl_Text_Display::shortcut(), Fl_Value_Input::shortcut(), Fl_Input_::shortcut(), Fl_Button::shortcut(), Fl_Widget::show(), and Shortcut_Button::svalue.
Referenced by make_widget_panel().
void slider_size_cb (Fl_Value_Input * , void *)
Definition at line 1536 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_valuator(), Fl_Type::is_window(), Fl_Widget_Type::o, Fl_Widget::parent(), Fl_Widget::redraw(), set_modflag(), Fl_Widget::show(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void step_cb (Fl_Value_Input * , void *)
Definition at line 1628 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_spinner(), Fl_Type::is_valuator(), Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void subclass_cb (Fl_Input * , void *)
Definition at line 1338 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_menu_item(), set_modflag(), Fl_Input_::static_value(), Fl_Widget_Type::subclass(), and Fl_Input_::value().
Referenced by make_widget_panel().
void subtype_cb (Fl_Choice * , void *)
Definition at line 1703 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Menu_Item::argument(), Fl_Widget::deactivate(), Fl_Type::first, int, Fl_Type::is_spinner(), m, Fl_Menu_::menu(), Fl_Menu_::mvalue(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), Fl_Widget::redraw(), set_modflag(), Fl_Widget_Type::subtypes(), type, Fl_Widget::type(), and Fl_Choice::value().
Referenced by make_widget_panel().
void textcolor_cb (Fl_Button * , void *)
Definition at line 1407 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::color(), Fl_Widget::deactivate(), Fl_Type::first, FL_BLACK, fl_contrast(), fl_show_colormap(), Fl_Widget::labelcolor(), Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), and Fl_Widget_Type::textstuff().
Referenced by make_widget_panel().
void textfont_cb (Fl_Choice * , void *)
Definition at line 1363 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, FL_HELVETICA, Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), Fl_Widget_Type::textstuff(), and Fl_Choice::value().
Referenced by make_widget_panel().
void textsize_cb (Fl_Value_Input * , void *)
Definition at line 1385 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Widget_Type::default_size, Fl_Type::first, int, Fl_Widget_Type::o, Fl_Widget::redraw(), set_modflag(), Fl_Widget_Type::textstuff(), and Fl_Valuator::value().
Referenced by make_widget_panel().
void tooltip_cb (Fl_Input * , void *)
Definition at line 486 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget_Type::is_widget(), Fl_Type::next, set_modflag(), Fl_Input_::static_value(), and Fl_Input_::value().
Referenced by make_widget_panel().
void user_data_cb (Fl_Input * , void *)
Definition at line 1271 of file Fl_Widget_Type.cxx.
References c_check(), Fl_Type::first, fl_message(), set_modflag(), Fl_Input_::static_value(), Fl_Widget::user_data(), Fl_Type::user_data(), and Fl_Input_::value().
Referenced by make_widget_panel().
void user_data_type_cb (Fl_Input * , void *)
Definition at line 1289 of file Fl_Widget_Type.cxx.
References c_check(), Fl_Type::first, fl_message(), set_modflag(), Fl_Input_::static_value(), Fl_Type::user_data_type(), and Fl_Input_::value().
Referenced by make_widget_panel().
void v_input_cb (Fl_Input * , void *)
Definition at line 1318 of file Fl_Widget_Type.cxx.
References c_check(), Fl_Widget_Type::extra_code(), Fl_Type::first, fl_message(), Fl_Widget::label(), set_modflag(), Fl_Input_::static_value(), Fl_Widget::user_data(), and Fl_Input_::value().
Referenced by make_widget_panel().
void value_cb (Fl_Value_Input * , void *)
Definition at line 1661 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Type::is_button(), Fl_Type::is_menu_item(), Fl_Type::is_spinner(), Fl_Type::is_valuator(), Fl_Widget_Type::o, Fl_Widget_Type::redraw(), set_modflag(), value, and Fl_Valuator::value().
Referenced by make_widget_panel().
void visible_cb (Fl_Light_Button * , void *)
Definition at line 915 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_window(), Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::parent(), Fl_Type::parent, Fl_Widget_Type::redraw(), set_modflag(), Fl_Widget::show(), Fl_Type::type_name(), value, Fl_Button::value(), and Fl_Widget::visible().
Referenced by make_widget_panel().
void w_cb (Fl_Value_Input * , void *)
Definition at line 556 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, gridx, gridy, Fl::h(), Fl_Widget::h(), i, int, Fl_Widget_Type::is_widget(), Fl_Type::next, Fl_Widget::redraw(), Fl_Widget::resize(), set_modflag(), Fl_Valuator::value(), Fl::w(), w, Fl_Widget::window(), Fl_Widget::x(), and Fl_Widget::y().
Referenced by make_widget_panel().
void wc_relative_cb (Fl_Light_Button * , void *)
Definition at line 606 of file Fl_Widget_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), Fl_Type::next, set_modflag(), Fl_Widget::show(), Fl_Type::type_name(), Fl_Button::value(), and Fl_Widget_Class_Type::wc_relative.
Referenced by make_widget_panel().
void when_button_cb (Fl_Light_Button * , void *)
Definition at line 836 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, FL_WHEN_NOT_CHANGED, Fl_Type::is_menu_item(), Fl_Type::next, Fl_Widget_Type::o, set_modflag(), Fl_Button::value(), and Fl_Widget::when().
Referenced by make_widget_panel().
void when_cb (Fl_Choice * , void *)
Definition at line 812 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, FL_WHEN_NOT_CHANGED, int, Fl_Type::is_menu_item(), m, Fl_Type::next, Fl_Widget_Type::o, set_modflag(), Fl_Choice::value(), Fl_Widget::when(), and ZERO_ENTRY.
Referenced by make_widget_panel().
void x_cb (Fl_Value_Input * , void *)
Definition at line 506 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, gridx, gridy, Fl::h(), Fl_Widget::h(), i, Fl_Widget_Type::is_widget(), Fl_Type::next, Fl_Widget::redraw(), Fl_Widget::resize(), set_modflag(), Fl_Valuator::value(), Fl::w(), Fl_Widget::w(), w, Fl_Widget::window(), and Fl_Widget::y().
Referenced by make_widget_panel().
void xclass_cb (Fl_Input * , void *)
Definition at line 479 of file Fl_Window_Type.cxx.
References Fl_Type::first, Fl_Widget::hide(), Fl_Type::is_button(), Fl_Type::is_menu_item(), Fl_Type::is_window(), LOAD, Fl_Type::next, Fl_Widget_Type::o, Fl_Widget::parent(), Fl_Widget_Type::redraw(), set_modflag(), Fl_Widget::show(), storestring(), Fl_Input_::value(), w, and Fl_Widget_Type::xclass.
Referenced by make_widget_panel().
void y_cb (Fl_Value_Input * , void *)
Definition at line 531 of file Fl_Widget_Type.cxx.
References Fl_Widget::activate(), Fl_Widget::deactivate(), Fl_Type::first, gridx, gridy, Fl::h(), Fl_Widget::h(), i, int, Fl_Widget_Type::is_widget(), Fl_Type::next, Fl_Widget::redraw(), Fl_Widget::resize(), set_modflag(), Fl_Valuator::value(), Fl::w(), Fl_Widget::w(), w, Fl_Widget::window(), and Fl_Widget::x().
Referenced by make_widget_panel().
Variable Documentation
Fl_Menu_Item boxmenu[]
Definition at line 656 of file Fl_Widget_Type.cxx.
Referenced by make_widget_panel().
Fl_Menu_Item fontmenu[]
Definition at line 964 of file Fl_Widget_Type.cxx.
Referenced by make_widget_panel().
Fl_Menu_Item labeltypemenu[]
Definition at line 1026 of file Fl_Widget_Type.cxx.
Referenced by make_widget_panel().
Fl_Menu_Item menu_[]
Definition at line 36 of file widget_panel.cxx.
Referenced by Fl_Input_Choice::add(), Fl_Input_Choice::clear(), Fl_Input_Choice::down_box(), Fl_Input_Choice::Fl_Input_Choice(), Fl_Menu_::menu(), Fl_Input_Choice::menu(), Fl_Input_Choice::menubutton(), Fl_Menu_::mode(), Fl_Input_Choice::resize(), Fl_Menu_::shortcut(), Fl_Menu_::text(), Fl_Menu_::value(), and Fl_Input_Choice::value().
Fl_Menu_Item menu_1[]
Definition at line 46 of file widget_panel.cxx.
Fl_Menu_Item menu_2[]
Definition at line 73 of file widget_panel.cxx.
Fl_Menu_Item menu_3[]
Definition at line 80 of file widget_panel.cxx.
Fl_Input* v_input[4]
Definition at line 86 of file widget_panel.cxx.
Fl_Menu_Item whenmenu[]
Definition at line 795 of file Fl_Widget_Type.cxx.
Referenced by make_widget_panel().
Fl_Value_Input* widget_h_input
Definition at line 71 of file widget_panel.cxx.
Fl_Value_Input* widget_w_input
Definition at line 69 of file widget_panel.cxx.
Fl_Value_Input* widget_x_input
Definition at line 65 of file widget_panel.cxx.
Fl_Value_Input* widget_y_input
Definition at line 67 of file widget_panel.cxx.
Fl_Button* wLiveMode
Definition at line 88 of file widget_panel.cxx.
Referenced by live_mode_cb().