SfR Fresh Dox - fltk: fltk-1.3.0rc3/FL/x.H File Reference
x.H File Reference
#include "Enumerations.H"
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xatom.h>
#include "Fl_Window.H"
#include "Xutf8.h"
Classes
class Fl_XFont_On_Demand
class Fl_X
Defines
#define Fl_X_H
#define fl_create_offscreen(w, h)
#define fl_begin_offscreen(pixmap)
#define fl_end_offscreen() fl_pop_clip(); fl_window = _sw; _ss->set_current()
#define fl_delete_offscreen(pixmap) XFreePixmap(fl_display, pixmap)
Typedefs
typedef Region Fl_Region
typedef ulong Fl_Offscreen
typedef ulong Fl_Bitmask
Functions
FL_EXPORT void fl_open_display ()
FL_EXPORT void fl_open_display (Display *)
FL_EXPORT void fl_close_display ()
FL_EXPORT ulong fl_xpixel (Fl_Color i)
FL_EXPORT ulong fl_xpixel (uchar r, uchar g, uchar b)
FL_EXPORT void fl_clip_region (Fl_Region)
FL_EXPORT Fl_Region fl_clip_region ()
FL_EXPORT Fl_Region XRectangleRegion (int x, int y, int w, int h)
FL_EXPORT int fl_handle (const XEvent &)
void fl_copy_offscreen (int x, int y, int w, int h, Fl_Offscreen pixmap, int srcx, int srcy)
FL_EXPORT Fl_Bitmask fl_create_bitmask (int w, int h, const uchar *data)
FL_EXPORT Fl_Bitmask fl_create_alphamask (int w, int h, int d, int ld, const uchar *data)
FL_EXPORT void fl_delete_bitmask (Fl_Bitmask bm)
Window fl_xid (const Fl_Window *w)
FL_EXPORT Fl_Window * fl_find (Window xid)
void fl_open_callback (void(*)(const char *))
Register a function called for each file dropped onto an application icon.
FL_EXPORT int fl_parse_color (const char *p, uchar &r, uchar &g, uchar &b)
Variables
FL_EXPORT Display * fl_display
END TIMERS //////////////////////////////////////////////////////////////////////////.
FL_EXPORT Window fl_message_window
FL_EXPORT int fl_screen
FL_EXPORT XVisualInfo * fl_visual
FL_EXPORT Colormap fl_colormap
FL_EXPORT Fl_XFont_On_Demand fl_xfont
FL_EXPORT GC fl_gc
FL_EXPORT Window fl_window
FL_EXPORT void * fl_xftfont
FL_EXPORT const XEvent * fl_xevent
FL_EXPORT ulong fl_event_time
FL_EXPORT char fl_override_redirect
FL_EXPORT int fl_background_pixel
Define Documentation
#define fl_begin_offscreen (pixmap)
Value:
Window _sw=fl_window; fl_window=pixmap; \
  Fl_Surface_Device *_ss = fl_surface; fl_display_device->set_current(); \
  fl_push_no_clip()
Definition at line 119 of file x.H.
#define fl_create_offscreen (w, h)
Value:
XCreatePixmap(fl_display, \
              (fl_surface->class_name() == Fl_Display_Device::class_id ? \
              fl_window : fl_xid(Fl::first_window()) ) , \
              w, h, fl_visual->depth)
Definition at line 113 of file x.H.
#define fl_delete_offscreen (pixmap) XFreePixmap(fl_display, pixmap)
Definition at line 127 of file x.H.
#define fl_end_offscreen () fl_pop_clip(); fl_window = _sw; _ss->set_current()
Definition at line 123 of file x.H.
#define Fl_X_H
Definition at line 34 of file x.H.
Typedef Documentation
typedef ulong Fl_Bitmask
Definition at line 130 of file x.H.
typedef ulong Fl_Offscreen
Definition at line 112 of file x.H.
typedef Region Fl_Region
Definition at line 55 of file x.H.
Function Documentation
FL_EXPORT void fl_close_display ()
get rid of allocated resources
Definition at line 1573 of file Fl_mac.cxx.
References Fl::remove_fd().
FL_EXPORT Fl_Bitmask fl_create_alphamask (int w, int h, int d, int ld, const uchar * data)
Definition at line 179 of file Fl_Bitmap.cxx.
References dataptr, fl_create_bitmask(), h, w, x, and y.
FL_EXPORT Fl_Bitmask fl_create_bitmask (int w, int h, const uchar * data)
Definition at line 165 of file Fl_Bitmap.cxx.
References fl_display, and fl_window.
FL_EXPORT void fl_delete_bitmask (Fl_Bitmask bm)
Definition at line 170 of file Fl_Bitmap.cxx.
References fl_delete_offscreen().
FL_EXPORT Fl_Window* fl_find (Window xid)
Definition at line 616 of file Fl.cxx.
FL_EXPORT int fl_handle (const XEvent &)
Definition at line 850 of file Fl_x.cxx.
References Fl::belowmouse(), buffer, Fl_Widget::damage(), data, Fl::e_dy, Fl::e_is_click, Fl::e_keysym, Fl::e_length, Fl::e_number, Fl::e_original_keysym, Fl::e_state, Fl::e_text, Fl::e_x, Fl::e_x_root, Fl::e_y, Fl::e_y_root, Fl::first_window(), FL_BackSpace, FL_Button, FL_BUTTON1, FL_CLOSE, FL_DAMAGE_EXPOSE, FL_Delete, FL_DND_DRAG, FL_DND_ENTER, FL_DND_LEAVE, FL_DND_RELEASE, fl_dnd_source_types, FL_Down, FL_End, FL_ENTER, FL_F, fl_find(), FL_FOCUS, FL_HIDE, FL_Home, fl_init_xim(), FL_Insert, FL_KEYDOWN, FL_KEYUP, FL_KP, FL_KP_Last, FL_Left, FL_Menu, FL_Meta_L, FL_Meta_R, FL_MOUSEWHEEL, FL_MOVE, fl_new_ic(), FL_Page_Down, FL_Page_Up, FL_PASTE, FL_PUSH, FL_RELEASE, FL_Right, fl_sendClientMessage(), fl_set_spot(), FL_SHOW, FL_Tab, FL_UNFOCUS, FL_Up, fl_utf8encode(), fl_XaUtf8String, fl_XdndActionCopy, fl_xid(), H, Fl::handle(), Fl_Widget::handle(), XRectangle::height, Fl_X::i(), i, int, NULL, Fl_Widget::parent(), Fl_Widget::position(), Fl_Window::resize(), Fl_Window::show(), type, unknown_len, Fl_X::wait_for_expose, XRectangle::width, Fl_Widget::window(), Fl_Widget::x(), x, XRectangle::x, xim_im, XKeysymToUcs(), XUtf8LookupString(), Fl_Widget::y(), and XRectangle::y.
FL_EXPORT void fl_open_display (Display *)
Definition at line 587 of file Fl_x.cxx.
References Fl::add_fd(), fl_init_xim(), FL_RGB, num, and Fl::visual().
FL_EXPORT void fl_open_display ()
Definition at line 1493 of file Fl_mac.cxx.
References CPSEnableForegroundOperation(), Fl::fatal, fl_default_cursor, fl_open_display(), and NULL.
FL_EXPORT int fl_parse_color (const char * p, uchar & r, uchar & g, uchar & b)
Definition at line 131 of file Fl_get_system_colors.cxx.
References fl_colormap, fl_display, fl_open_display(), and x.
Window fl_xid (const Fl_Window * w) [inline]
Definition at line 161 of file x.H.
References Fl_X::i(), and Fl_X::xid.
Referenced by Fl_Window::cursor(), FLDropTarget::Drop(), Fl_Menu_Window::erase(), fl_handle(), fl_set_spot(), fl_text_extents(), fl_width(), Fl_Overlay_Window::flush(), Fl_Double_Window::flush(), Fl::grab(), Fl_Window::handle(), Fl_Window::hide(), Fl_Window::label(), Fl_X::make(), Fl_X::make_xid(), and Fl_Window::show().
FL_EXPORT Fl_Region XRectangleRegion (int x, int y, int w, int h)
Definition at line 519 of file fl_rect.cxx.
References Fl_Display_Device::class_id, h, XRectangle::height, Fl_Surface_Device::surface(), w, XRectangle::width, x, XRectangle::x, y, and XRectangle::y.
Variable Documentation
FL_EXPORT int fl_background_pixel
Definition at line 1533 of file Fl_x.cxx.
FL_EXPORT Colormap fl_colormap
Definition at line 298 of file Fl_x.cxx.
Referenced by fl_parse_color(), fl_read_image(), fl_xpixel(), Fl::free_color(), Fl::own_colormap(), and Fl::visual().
FL_EXPORT Display* fl_display
END TIMERS //////////////////////////////////////////////////////////////////////////.
Definition at line 1687 of file Fl_win32.cxx.
FL_EXPORT ulong fl_event_time
Definition at line 102 of file Fl_mac.cxx.
Referenced by Fl::grab().
FL_EXPORT GC fl_gc
Definition at line 97 of file Fl_mac.cxx.
FL_EXPORT Window fl_message_window
Definition at line 295 of file Fl_x.cxx.
Referenced by fl_destroy_xft_draw().
FL_EXPORT char fl_override_redirect
FL_EXPORT int fl_screen
Definition at line 96 of file Fl_mac.cxx.
Referenced by Fl_Window::cursor(), fl_read_image(), Fl_Window::iconize(), Fl::own_colormap(), and Fl::visual().
FL_EXPORT XVisualInfo* fl_visual
Definition at line 297 of file Fl_x.cxx.
Referenced by fl_read_image(), fl_rectf(), fl_xpixel(), Fl::own_colormap(), and Fl::visual().
FL_EXPORT Window fl_window
Definition at line 108 of file Fl_mac.cxx.
FL_EXPORT const XEvent* fl_xevent
Definition at line 779 of file Fl_x.cxx.
FL_EXPORT Fl_XFont_On_Demand fl_xfont
Definition at line 42 of file fl_font_x.cxx.
FL_EXPORT void* fl_xftfont
Definition at line 265 of file fl_font_x.cxx.
Referenced by fl_font().